### ISSUE TITLE
Crash Conditional Plots/Map: Try Replicating

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1000]
From: 
 Details:
os: 1-10-12
vs: 1-10-0-12
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Volumes/TCM/Barranquilla/Analysis/Dengue/Shapefile/Season_Year/UPDATE_COMPLETE/Dengue_season_year_COMP2016.shp
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::SetDetailsForItem
Open VarGroupingEditorDlg.
In VarGroupingEditorDlg::OnNewGroupNameChange
In WeightsManFrame::OnActivate
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnCreateGrpClick
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
Open LisaMapFrame (OnOpenDiffLisa).
Open DiffMoranVarSettingDlg.
Click DiffMoranVarSettingDlg::OnOK
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnShowAsConditionalMap()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
INC_Q
INC_Q
Open ConditionalNewFrame -- LISA.

**Comment by lixun910** [comment]
same problem, see fix #999
