### ISSUE TITLE
Allow GeoDa to read strings as categories

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1005]
Right now GeoDa only takes numeric values as inputs for its mapping and statistical views. Add new feature to allow it to read strings as separate categories (we could apply same rules as for unique values in cases where there are too many categories).

For instance, users could then map categories like race, religion, regions etc., loop through categories in the map movie, select string categories in the table's selection tool, and use them to segment the X and Y axes in the conditional maps.

FYI from user in this context:

The inability to use categorical values … (at least in the histogram) but, presumably in the other link-brush abilities….  Ouch.  Look, for example, at SAS JMP, which is where I do most of my stats work these days, and in recent versions it has the ability to mount shp files as background…..  My dream would be to have that kind of dynamic cross-linking and brushing with a truly spatial-analytic element….  JMP is amazing for dynamic exploration and stats on the non-spatial table data end but still crude on the spatial end.  QGIS is great on the GIS end, and infinitely expandable with Python/R etc., not to mention SAGA, GRASS, Orfeo, etc. for spatial statistics, but in a static kind of way.

**Comment by jkoschinsky** [comment]
Let's set a limit to the max number of different string categories we can input -- maybe the same as we have for unique values (12?).

Otherwise you get results like this one :)

<img width="1227" alt="check cty -- unique values" src="https://user-images.githubusercontent.com/13679743/30284426-862d4704-96e0-11e7-8121-5aea573d376b.png">

**Comment by lixun910** [comment]
Yes, it is the same with what we have for unique values. See the screenshot. I think in this case it makes sense (e.g. W S C N E). However, the user needs to be careful what variables with what values they are using in conditional plots. If in your case, it doesn't make sense even we set a max number of categories. 

<img width="1405" alt="screen shot 2018-01-29 at 5 26 57 pm" src="https://user-images.githubusercontent.com/2423887/35541846-1b5c0908-051a-11e8-8a16-96e08bdb9de1.png">
