### ISSUE TITLE
Add boxplot's option for "Fixed Scale Over Time" as averages chart option

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1006]
In boxplots for grouped variables, we have "Scale Option --> "Fixed Scale Over Time":

<img width="722" alt="screen shot 2017-08-03 at 11 58 06 am" src="https://user-images.githubusercontent.com/13679743/28933651-82d430ec-7843-11e7-9207-8abd7bd8eec2.png">

Add this same option to averages chart if people want to compare results using the same scale. 

Right now, the scale changes for each selection, which can be confusing if you want to compare results, e.g.:

<img width="801" alt="screen shot 2017-08-03 at 11 58 35 am" src="https://user-images.githubusercontent.com/13679743/28933667-948694b0-7843-11e7-9537-4c3f257a68ca.png">

<img width="800" alt="screen shot 2017-08-03 at 11 56 06 am" src="https://user-images.githubusercontent.com/13679743/28933677-9f17ee42-7843-11e7-8cfa-ecfaa51fe341.png">

**Comment by luluzhou766** [comment]
Win 10, 64bit
Geoda 1.12.1.131
Verified
![img_0954](https://user-images.githubusercontent.com/36253697/39612766-c2bc4662-4f94-11e8-831d-56f921f2416d.JPG)

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.12.1.133 OSX
