### ISSUE TITLE
change window options for local cluster statistics

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1012]
The standard use case for local statistics, such as local Moran, G, and local Geary is to focus on the cluster map. As it stands, the default dialog "What windows to open?" has all options checked. A more logical default (involving fewer clicks) would be to only have the Cluster Map option checked (shown below)
<img width="255" alt="screen shot 2017-08-11 at 11 25 17 am" src="https://user-images.githubusercontent.com/4008351/29226700-d1426330-7e87-11e7-8293-a653a71dab03.png">
, so that the other options involve an additional click. As it stands, removing the other options involves one to two additional clicks.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
Verified

**Comment by jkoschinsky** [comment]
Verified fix in Geoda 1.12.1.111
OSX
