### ISSUE TITLE
simplify custom significance dialog for local statistics

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1013]
I think the check box with "Use selected as specified alpha level" can be removed. Since custom inference is checked already, there are clear choices indicated by the radio buttons. Not sure what the check box adds.

<img width="338" alt="screen shot 2017-08-11 at 11 31 44 am" src="https://user-images.githubusercontent.com/4008351/29226972-e413d4ca-7e88-11e7-8998-1157f7af2825.png">

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.73 (OSX Yosemite, 10.10.5).

For local Moran, local join count, uni+multivariate Geary's c, local G.
