### ISSUE TITLE
spectral clustering settings dialog

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1014]
- fix typo in Guassian (kernel)
- provide default value for "Gamma"

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
Guassian is corrected, but I cannot find "Gamma"

![16 mar 01](https://user-images.githubusercontent.com/36253697/37545996-d78fb0d6-2962-11e8-9236-270acda86883.PNG)

**Comment by jkoschinsky** [comment]
gamma replaced by Gaussian Sigma

Fix confirmed in GeoDa v113
OSX
