### ISSUE TITLE
Crash: Weights Creation?

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1015]
From: 
 Details:
os: 1-10-12
vs: 1-10-0-8
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/etalen/Desktop/Block Score V. 2/Block_DailyLife Essentials.shp
Open Layer:Block_DailyLife Essentials
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/etalen/Desktop/Block Score V. 2/Block_DailyLife Essentials.shp
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
DummyTotal
Open HistogramFrame.
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
In GdaFrame::OnDisplayStatistics()
In HistogramFrame::OnDisplayStatistics()
In TableFrame::OnActivate
Open FieldNewCalcSheetDlg.
Open DataViewerAddColDlg.
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
In DataViewerAddColDlg::OnChoiceType()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditLength()
Entering DataViewerAddColDlg::OnOkClick
Inserting new column DDUMMY into Table
In TableFrame::OnActivate
Open RangeSelectionDlg
In RangeSelectionDlg::OnRangeTextChange()
In RangeSelectionDlg::OnRangeTextChange()
In RangeSelectionDlg::OnRangeTextChange()
In RangeSelectionDlg::OnRangeTextChange()
In RangeSelectionDlg::OnSelUnselTextChange()
In RangeSelectionDlg::CheckApplySaveSettings()
In RangeSelectionDlg::OnSelUnselTextChange()
In RangeSelectionDlg::CheckApplySaveSettings()
In RangeSelectionDlg::OnSelUnselTextChange()
In RangeSelectionDlg::CheckApplySaveSettings()
In RangeSelectionDlg::OnSelUnselTextChange()
In RangeSelectionDlg::CheckApplySaveSettings()
In RangeSelectionDlg::CheckApplySaveSettings()
In RangeSelectionDlg::OnFieldChoice()
In RangeSelectionDlg::OnRangeTextChange()
In RangeSelectionDlg::OnRangeTextChange()
In RangeSelectionDlg::OnRangeTextChange()
Entering RangeSelectionDlg::OnApplySelClick
In RangeSelectionDlg::CheckApplySaveSettings()
In RangeSelectionDlg::OnSaveFieldChoice()
In RangeSelectionDlg::CheckApplySaveSettings()
In RangeSelectionDlg::OnAddField()
Open DataViewerAddColDlg.
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditLength()
In TableFrame::OnActivate
In RangeSelectionDlg::OnApplySaveClick()
In RangeSelectionDlg::CheckApplySaveSettings()
In TableFrame::OnActivate
Click GdaFrame::OnSaveProject
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs
New Datasource Name:/Users/etalen/Desktop/Block Score V. 2/GdaTmp_Block_DailyLife Essentials.shp
Project::GetSpatialReference()
Project::GetGdaGeometries()
ScrolledWidgetsPane::IsFieldNameValid
statefp10
ScrolledWidgetsPane::IsFieldNameValid
countyfp10
ScrolledWidgetsPane::IsFieldNameValid
tractce10
ScrolledWidgetsPane::IsFieldNameValid
geoid10
ScrolledWidgetsPane::IsFieldNameValid
blockce10
ScrolledWidgetsPane::IsFieldNameValid
tract_bloc
ScrolledWidgetsPane::IsFieldNameValid
name10
ScrolledWidgetsPane::IsFieldNameValid
Daycare ce
ScrolledWidgetsPane::IsFieldNameValid
Farmersmar
ScrolledWidgetsPane::IsFieldNameValid
Senior Cen
ScrolledWidgetsPane::IsFieldNameValid
Library
ScrolledWidgetsPane::IsFieldNameValid
School
ScrolledWidgetsPane::IsFieldNameValid
Clinic
ScrolledWidgetsPane::IsFieldNameValid
Grocery St
ScrolledWidgetsPane::IsFieldNameValid
DummyTotal
ScrolledWidgetsPane::IsFieldNameValid
DDUMMY
ScrolledWidgetsPane::RemoveIllegalChars
Daycare ce
Daycarece
ScrolledWidgetsPane::TruncateFieldName
Daycarece
ScrolledWidgetsPane::RenameDupFieldName
Daycarece
Daycarece
ScrolledWidgetsPane::RemoveIllegalChars
Senior Cen
SeniorCen
ScrolledWidgetsPane::TruncateFieldName
SeniorCen
ScrolledWidgetsPane::RenameDupFieldName
SeniorCen
SeniorCen
ScrolledWidgetsPane::RemoveIllegalChars
Grocery St
GrocerySt
ScrolledWidgetsPane::TruncateFieldName
GrocerySt
ScrolledWidgetsPane::RenameDupFieldName
GrocerySt
GrocerySt
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
Daycarece
ScrolledWidgetsPane::IsFieldNameValid
SeniorCen
ScrolledWidgetsPane::IsFieldNameValid
GrocerySt
In RangeSelectionDlg::CheckApplySaveSettings()
In RangeSelectionDlg::CheckApplySaveSettings()
In RangeSelectionDlg::CheckApplySaveSettings()
Exit FieldNameCorrectionDlg
Exiting Project::SaveDataSourceData
Entering Project::SaveProjectConf
Exiting Project::SaveProjectConf
In RangeSelectionDlg::OnFieldChoice()
In RangeSelectionDlg::OnRangeTextChange()
Entering RangeSelectionDlg::OnApplySelClick
In RangeSelectionDlg::CheckApplySaveSettings()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
Close CreatingWeightDlg
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate

**Comment by jkoschinsky** [comment]
Luc, this looks like it crashed on Emily for weights creation for GdaTmp_Block_DailyLife Essentials.shp? I can try to replicate if you have the data. thx

**Comment by lanselin** [comment]
I'm pretty sure this is fixed by now.
