### ISSUE TITLE
interaction between significance filter and custom colors

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1016]
When one sets one of the colors in a cluster map to a custom value, e.g., the low-low in a Gi* cluster map to white (if one is only interested in the high-high locations), then this custom color is lost after the significance filter is changed. For example, one generates the default map, then changes the blue for low-low to white, then changes significance to a custom value, the new map has the old red and blue, and not the newly customized colors.
It would be nice if the customization would persist between significance levels.

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.73 (OSX Yosemite, 10.10.5).

**Comment by YidanJ-Wu** [comment]
Windows 8 1.10.1.73 
Verified
