### ISSUE TITLE
local join count as special case of local Gi*

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1017]
In the special case of a binary variable, the local Gi* can also be interpreted as a form of local join count statistic (with the weights in binary form, i.e., not row-standardized). It would be nice to add this as an additional item in the local statistics menu, e.g., below Gi*, as Local Join Count.
Basically, this would require verifying that the variable is binary, making sure the weights are not row-standardized and running local Gi*. The resulting cluster map and significance map should only contain the results for high-high (i.e., value of 1 surrounded by value of 1). The low-low (0 surrounded by 0) should be left blank (white).

**Comment by lanselin** [comment]
Note: the local Gi* statistic needs some adjustment to work as a local join count statistic. Specifically, it should only be computed for those locations that have a 1. Otherwise, applying the logic of Gi*, one could end up with a "cluster" of values of 1 surrounding a 0 (Gi statistic is insensitive to spatial outliers) misleadingly identified as a high-high cluster. So, skip the 0 observations, and compute the Gi* statistic only for those with a 1, using binary weights.

**Comment by lanselin** [comment]
version 1.10.1.27

the cluster map for the local join count statistic should only show the high category, the low category is irrelevant since we ignore observation with 0.

the output of the save as command should be customized:
- use JC instead of G for the actual statistic
- drop C_ID
- only show the p-values for those observations with 1
- in addition, show:
   - number of neighbors with value 1, say NN_1
   - number of neighbors, say NN

**Comment by lixun910** [comment]
OK. Got it.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
**Not Sure how to verify "•use JC instead of G for the actual statistic"**
The rest is verified

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v113
OSX
