### ISSUE TITLE
Crash Report: Linux (1019-21 same user)

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1019]
From: 
 Details:
os: 3-4-10
vs: 1-10-0-8
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/estanleyslao/Dropbox/ADMU-ASOG/Potential Implications of Switching to Federalism/Data/GIS Data Working File/Provinces.shp.xml
Open Layer:Provinces.shp
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/estanleyslao/Dropbox/ADMU-ASOG/Potential Implications of Switching to Federalism/Data/GIS Data Working File/Provinces.shp.xml
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/estanleyslao/Dropbox/ADMU-ASOG/Potential Implications of Switching to Federalism/Data/GIS Data Working File/Provinces.shp
Open Layer:Provinces
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/estanleyslao/Dropbox/ADMU-ASOG/Potential Implications of Switching to Federalism/Data/GIS Data Working File/Provinces.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open MergeTableDlg.
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/estanleyslao/Dropbox/ADMU-ASOG/Potential Implications of Switching to Federalism/Data/ASoG POLITICAL DYNASTIES DATA.ods
Open Layer:ASoG POLITICAL DYNASTIES DATA
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
ds:/home/estanleyslao/Dropbox/ADMU-ASOG/Potential Implications of Switching to Federalism/Data/ASoG POLITICAL DYNASTIES DATA.ods layer: ASoG POLITICAL DYNASTIES DATA
In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnKeyChoice()
Entering MergeTableDlg::OnIncAllClick()
Entering MergeTableDlg::OnExclOneClick()
In MergeTableDlg::OnMergeClick()
Open FieldNameCorrectionDlg:
ScrolledWidgetsPane::RemoveIllegalChars
PROVINCE_AIM
PROVINCE_AIM
ScrolledWidgetsPane::TruncateFieldName
PROVINCE_AIM
PROVI__AIM
ScrolledWidgetsPane::RenameDupFieldName
PROVI__AIM
PROVI__AIM
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
PROVI_AIM
Exit FieldNameCorrectionDlg
In MergeTableDlg::OnCloseClick()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnActivate
In TableFrame::OnActivate
Entering MergeTableDlg::OnExclAllClick()
Entering MergeTableDlg::OnExclAllClick()
Entering MergeTableDlg::OnIncAllClick()
Entering MergeTableDlg::OnExclOneClick()
In MergeTableDlg::OnMergeClick()
Open FieldNameCorrectionDlg:
ScrolledWidgetsPane::RemoveIllegalChars
PROVINCE_AIM
PROVINCE_AIM
ScrolledWidgetsPane::TruncateFieldName
PROVINCE_AIM
PROVI__AIM
ScrolledWidgetsPane::RenameDupFieldName
PROVI__AIM
PROVI__AIM
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
PROVI_M
Exit FieldNameCorrectionDlg
In TableFrame::OnActivate
In TableFrame::OnActivate
Entering GdaFrame::OnMapChoices
In GdaFrame::OnOpenStddev()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
Open VarGroupingEditorDlg.
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnClose
Open CatClassifFrame
CatClassifPanel::OnButtonNew
Entering GdaFrame::OnMapChoices
In GdaFrame::OnOpenUniqueValues()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
REGCODE
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
MapCanvas::~MapCanvas()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
Click GdaFrame::OnSaveAsProject
Project::GetProjectFullPath()
Project::SpecifyProjectConfFile()
Project::SetProjectFullPath()
Entering Project::SaveProjectConf
In Project::UpdateProjectConf
Exiting Project::SaveProjectConf
Wrote GeoDa Project File: 
In TableFrame::OnActivate
In TableFrame::OnActivate
MapCanvas::~MapCanvas()
In TableFrame::OnActivate
Entering GdaFrame::OnMapChoices
In GdaFrame::OnOpenUniqueValues()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
REGCODE
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnSaveCategories()
MapCanvas::OnSaveCategories()
Open CatClassifFrame
In GdaFrame::OnSaveCategories()
MapCanvas::OnSaveCategories()
Open CatClassifFrame
CatClassifPanel::OnButtonNew
CatClassifPanel::OnButtonNew
CatClassifPanel::OnAssocVarChoice
FEDSTATCOD
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
Open DataViewerDeleteColDlg.
In TableFrame::OnActivate
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnDelete()
REGIONS
In TableFrame::OnActivate
Click GdaFrame::OnSaveProject
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs
New Datasource Name:/home/estanleyslao/Dropbox/ADMU-ASOG/Potential Implications of Switching to Federalism/Data/GIS Data Working File/GdaTmp_Provinces.shp
Project::GetSpatialReference()
Project::GetGdaGeometries()
ScrolledWidgetsPane::IsFieldNameValid
ID_0
ScrolledWidgetsPane::IsFieldNameValid
ISO
ScrolledWidgetsPane::IsFieldNameValid
NAME_0
ScrolledWidgetsPane::IsFieldNameValid
ID_1
ScrolledWidgetsPane::IsFieldNameValid
NAME_1
ScrolledWidgetsPane::IsFieldNameValid
NL_NAME_1
ScrolledWidgetsPane::IsFieldNameValid
VARNAME_1
ScrolledWidgetsPane::IsFieldNameValid
TYPE_1
ScrolledWidgetsPane::IsFieldNameValid
ENGTYPE_1
ScrolledWidgetsPane::IsFieldNameValid
PROVINCE
ScrolledWidgetsPane::IsFieldNameValid
REGION
ScrolledWidgetsPane::IsFieldNameValid
PROVI_M
ScrolledWidgetsPane::IsFieldNameValid
REGION_AIM
ScrolledWidgetsPane::IsFieldNameValid
REGCODE
ScrolledWidgetsPane::IsFieldNameValid
FEDSTATE
ScrolledWidgetsPane::IsFieldNameValid
FEDSTATCOD
ScrolledWidgetsPane::IsFieldNameValid
PVTARMCT09
ScrolledWidgetsPane::IsFieldNameValid
PVTARMCT12
ScrolledWidgetsPane::IsFieldNameValid
DYNSHR13
ScrolledWidgetsPane::IsFieldNameValid
DYNSHR16
ScrolledWidgetsPane::IsFieldNameValid
PVRTR12
ScrolledWidgetsPane::IsFieldNameValid
HDI2009
ScrolledWidgetsPane::IsFieldNameValid
HDI2012
ScrolledWidgetsPane::IsFieldNameValid
MIN17
ScrolledWidgetsPane::IsFieldNameValid
CONF16
ScrolledWidgetsPane::IsFieldNameValid
CONFELEV16
ScrolledWidgetsPane::IsFieldNameValid
CONFMIL16
ScrolledWidgetsPane::IsFieldNameValid
CONFOTH16
ScrolledWidgetsPane::IsFieldNameValid
CONFAON16
Exit FieldNameCorrectionDlg
Exiting Project::SaveDataSourceData
Entering Project::SaveProjectConf
In Project::UpdateProjectConf
Exiting Project::SaveProjectConf
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In OnAddMeanCenters()
In Project::AddMeanCenters
Project::GetMeanCenters()
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
Open DataViewerDeleteColDlg.
In TableFrame::OnActivate
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnDelete()
COORD_Y
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnDelete()
COORD_X
In TableFrame::OnActivate
Click GdaFrame::OnClose
Project::GetProjectFullPath()
Project::GetProjectFullPath()
Project::HasUnsavedChange()
Click GdaFrame::OnSaveProject
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs
New Datasource Name:/home/estanleyslao/Dropbox/ADMU-ASOG/Potential Implications of Switching to Federalism/Data/GIS Data Working File/GdaTmp_Provinces.shp
Project::GetSpatialReference()
Project::GetGdaGeometries()
ScrolledWidgetsPane::IsFieldNameValid
ID_0
ScrolledWidgetsPane::IsFieldNameValid
ISO
ScrolledWidgetsPane::IsFieldNameValid
NAME_0
ScrolledWidgetsPane::IsFieldNameValid
ID_1
ScrolledWidgetsPane::IsFieldNameValid
NAME_1
ScrolledWidgetsPane::IsFieldNameValid
NL_NAME_1
ScrolledWidgetsPane::IsFieldNameValid
VARNAME_1
ScrolledWidgetsPane::IsFieldNameValid
TYPE_1
ScrolledWidgetsPane::IsFieldNameValid
ENGTYPE_1
ScrolledWidgetsPane::IsFieldNameValid
PROVINCE
ScrolledWidgetsPane::IsFieldNameValid
REGION
ScrolledWidgetsPane::IsFieldNameValid
PROVI_M
ScrolledWidgetsPane::IsFieldNameValid
REGION_AIM
ScrolledWidgetsPane::IsFieldNameValid
REGCODE
ScrolledWidgetsPane::IsFieldNameValid
FEDSTATE
ScrolledWidgetsPane::IsFieldNameValid
FEDSTATCOD
ScrolledWidgetsPane::IsFieldNameValid
PVTARMCT09
ScrolledWidgetsPane::IsFieldNameValid
PVTARMCT12
ScrolledWidgetsPane::IsFieldNameValid
DYNSHR13
ScrolledWidgetsPane::IsFieldNameValid
DYNSHR16
ScrolledWidgetsPane::IsFieldNameValid
PVRTR12
ScrolledWidgetsPane::IsFieldNameValid
HDI2009
ScrolledWidgetsPane::IsFieldNameValid
HDI2012
ScrolledWidgetsPane::IsFieldNameValid
MIN17
ScrolledWidgetsPane::IsFieldNameValid
CONF16
ScrolledWidgetsPane::IsFieldNameValid
CONFELEV16
ScrolledWidgetsPane::IsFieldNameValid
CONFMIL16
ScrolledWidgetsPane::IsFieldNameValid
CONFOTH16
ScrolledWidgetsPane::IsFieldNameValid
CONFAON16
Exit FieldNameCorrectionDlg
Exiting Project::SaveDataSourceData
Entering Project::SaveProjectConf
In Project::UpdateProjectConf
Exiting Project::SaveProjectConf
In TableFrame::OnActivate
Open FieldNewCalcSheetDlg.
In FieldNewCalcSheetDlg::OnPageChange()
In TableFrame::OnActivate
In FieldNewCalcSheetDlg::OnClose()
In TableFrame::OnActivate
Open DataViewerEditFieldPropertiesDlg
Open CatClassifFrame
CatClassifPanel::OnButtonDelete
CatClassifPanel::OnButtonNew
CatClassifPanel::OnAssocVarChoice
REGCODE
CatClassifPanel::OnBreaksChoice
CatClassifPanel::OnAutomaticLabelsCb
CatClassifPanel::OnAutomaticLabelsCb
CatClassifPanel::OnAutomaticLabelsCb
CatClassifPanel::OnAutomaticLabelsCb
CatClassifPanel::OnColorSchemeChoice
CatClassifPanel::OnColorSchemeChoice
CatClassifPanel::OnColorSchemeChoice
CatClassifPanel::OnAssocVarChoice
FEDSTATCOD
Click GdaFrame::OnCopyImageToClipboard
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
SVG selected
In TableFrame::OnActivate
In TableFrame::OnActivate
Entering GdaFrame::OnMapChoices
In TableFrame::OnActivate
Entering GdaFrame::OnMapChoices
In GdaFrame::OnOpenUniqueValues()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
FEDSTATCOD
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
MapCanvas::~MapCanvas()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
Click GdaFrame::OnSaveProject
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs
New Datasource Name:/home/estanleyslao/Dropbox/ADMU-ASOG/Potential Implications of Switching to Federalism/Data/GIS Data Working File/GdaTmp_Provinces.shp
Project::GetSpatialReference()
Project::GetGdaGeometries()
ScrolledWidgetsPane::IsFieldNameValid
ID_0
ScrolledWidgetsPane::IsFieldNameValid
ISO
ScrolledWidgetsPane::IsFieldNameValid
NAME_0
ScrolledWidgetsPane::IsFieldNameValid
ID_1
ScrolledWidgetsPane::IsFieldNameValid
NAME_1
ScrolledWidgetsPane::IsFieldNameValid
NL_NAME_1
ScrolledWidgetsPane::IsFieldNameValid
VARNAME_1
ScrolledWidgetsPane::IsFieldNameValid
TYPE_1
ScrolledWidgetsPane::IsFieldNameValid
ENGTYPE_1
ScrolledWidgetsPane::IsFieldNameValid
PROVINCE
ScrolledWidgetsPane::IsFieldNameValid
REGION
ScrolledWidgetsPane::IsFieldNameValid
PROVI_M
ScrolledWidgetsPane::IsFieldNameValid
REGION_AIM
ScrolledWidgetsPane::IsFieldNameValid
REGCODE
ScrolledWidgetsPane::IsFieldNameValid
FEDSTATE
ScrolledWidgetsPane::IsFieldNameValid
FEDSTATCOD
ScrolledWidgetsPane::IsFieldNameValid
PVTARMCT09
ScrolledWidgetsPane::IsFieldNameValid
PVTARMCT12
ScrolledWidgetsPane::IsFieldNameValid
DYNSHR13
ScrolledWidgetsPane::IsFieldNameValid
DYNSHR16
ScrolledWidgetsPane::IsFieldNameValid
PVRTR12
ScrolledWidgetsPane::IsFieldNameValid
HDI2009
ScrolledWidgetsPane::IsFieldNameValid
HDI2012
ScrolledWidgetsPane::IsFieldNameValid
MIN17
ScrolledWidgetsPane::IsFieldNameValid
CONF16
ScrolledWidgetsPane::IsFieldNameValid
CONFELEV16
ScrolledWidgetsPane::IsFieldNameValid
CONFMIL16
ScrolledWidgetsPane::IsFieldNameValid
CONFOTH16
ScrolledWidgetsPane::IsFieldNameValid
CONFAON16
Exit FieldNameCorrectionDlg
Exiting Project::SaveDataSourceData
Entering Project::SaveProjectConf
In Project::UpdateProjectConf
Exiting Project::SaveProjectConf
Entering GdaFrame::OnMapChoices
In GdaFrame::OnOpenUniqueValues()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
FEDSTATCOD
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
Open DataViewerEditFieldPropertiesDlg
In TableFrame::OnActivate
In GdaFrame::OnOpenUniqueValues()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnActivate
Click GdaFrame::OnLegendUseScientificNotation
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnLegendUseScientificNotation
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
Entering GdaFrame::OnMapChoices
In GdaFrame::OnOpenUniqueValues()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
FEDSTATCOD
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
SVG selected
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
Entering GdaFrame::OnMapChoices
In GdaFrame::OnOpenUniqueValues()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
REGCODE
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnActivate
In TableFrame::OnActivate

**Comment by jkoschinsky** [comment]
same as https://github.com/GeoDaCenter/geoda/issues/1020
