### ISSUE TITLE
Crash: Dropbox data source causing the problem?

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1022]
From: 
 Details:
os: 1-10-12
vs: 1-10-0-12
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/gshaw/Dropbox/Shaw Research Lab/Melissa Spring 2017/HistParPlaces.shp
Open Layer:HistParPlaces
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/gshaw/Dropbox/Shaw Research Lab/Melissa Spring 2017/HistParPlaces.shp
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
MapCanvas::~MapCanvas()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
GdaFrame::OpenProject()
/Users/gshaw/Dropbox/Shaw Research Lab/Melissa Spring 2017/1268_boroughs.shp
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/gshaw/Dropbox/Shaw Research Lab/Melissa Spring 2017/1268_boroughs.shp
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()

**Comment by jkoschinsky** [comment]
Leaving this open for Julie to test: Several of the crash reports I can't replicate are pulling their data in from Dropbox. I tried this on Mac and couldn't replicate a crash but maybe it's a Windows problem. We've had this before and fixed it but there might still be a problem left.

**Comment by lixun910** [comment]
same as #1566 dropbox related issue.
