### ISSUE TITLE
Linux Crash: Check ODS file input

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1027]
From: 
 Details:
os: 3-4-4
vs: 1-10-0-8
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/agrs1mg0302ce11/Descargas/inec_prv.ods
Open Layer:inec_prv
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/agrs1mg0302ce11/Descargas/inec_prv.ods
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
Open VariableSettingsDlg
In TableFrame::OnActivate
In TableFrame::OnActivate
Click VariableSettingsDlg::OnOkClick:
Km2
Densi
NBI
TasaAnalf
Open ScatterNewPlotFrame.
Open ScatterPlotMatFrame.
In ScatterPlotMatFrame::OnActivate
Open ScatterPlotMatFrame.
In ScatterPlotMatFrame::OnActivate
In ScatterPlotMatFrame::OnActivate
In ScatterPlotMatFrame::OnActivate
In ScatterPlotMatFrame::OnActivate
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/agrs1mg0302ce11/Descargas/inec_prv.ods
Open Layer:inec_prv
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/agrs1mg0302ce11/Descargas/inec_prv.ods
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
Open KMeanDlg.
Close HClusterDlg
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
Open ScatterPlotMatFrame.
In ScatterPlotMatFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnActivate
Open LisaScatterPlotFrame (OnOpenMSPL).
Open LisaScatterPlotFrame (OnOpenDiffMoran).
Open LisaScatterPlotFrame (OnOpenMoranEB).
In TableFrame::OnActivate
In TableFrame::OnActivate
Click GdaFrame::OnSaveProject
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs
New Datasource Name:/home/agrs1mg0302ce11/Descargas/GdaTmp_inec_prv.ods
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs
New Datasource Name:/home/agrs1mg0302ce11/Descargas/GdaTmp_inec_prv.ods

**Comment by jkoschinsky** [comment]
Looks like it crashed on ODS file type -- Julia to check this

**Comment by lixun910** [comment]
Can't replicate this crash using GeoDa 1.10 on Ubuntu 16.04. 
Try to save Natregimes from GeoDa to nat.ods. Then, load nat.ods file in GeoDa, and load weights and try global moran statistics (as shown in the report). Then save current ods file.

**Comment by lixun910** [comment]
Can't replicate this crash using GeoDa 1.14 on Ubuntu 16.04 and Ubuntu 18.04.
