### ISSUE TITLE
GeoDa crashes after change "display length" when convert string field to real 

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1030]
GeoDa 1.10.1.5 (July 25, 2017)
Data: will email Xun

Steps:
1. open table
2. try to convert FIPS field from string to real
3. try to change "display precision" from 5 to 0
--> crash
Note: string to integer works

From: JuliaK
 Details:
os: 1-10-10
vs: 1-10-1-5
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/Julia/Box Sync/Julia/CSDS/Network/NORC/Chicago Data/Chi-SDOH.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open TimeChooserDlg.
Open VarGroupingEditorDlg.
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnCreateGrpClick
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
Open LineChartFrame(Average Charts).
In LineChartFrame::OnActivate()
In LineChartFrame::OnVariableChoice()
var: WHT50PCT, time1:-1, time2:-1, group1:0, group2:1
In LineChartFrame::OnVariableChoice()
var: Group, time1:0, time2:0, group1:0, group2:1
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Group
Open BoxPlotCanvas.
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
BLCK50PCT
Open HistogramFrame.
In HistogramFrame::OnActivate()
In LineChartFrame::OnActivate()
In HistogramFrame::OnActivate()
In GdaFrame::OnFixedScaleVariable1()
In LineChartFrame::OnActivate()
In LineChartFrame::OnActivate()
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
In VarGroupingEditorDlg::OnClose
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In VarGroupingEditorDlg::OnClose
Close TimeChooserDlg::OnClose
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
Close BoxPlotCanvas.
MapCanvas::~MapCanvas()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
ConnectDatasourceDlg::OnSample()
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Applications/GeoDa.app/Contents/MacOS/../Resources/samples.sqlite
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open TimeChooserDlg.
Open VarGroupingEditorDlg.
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListEdit
In VarGroupingEditorDlg::OnIncludeListEditEnd
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListEdit
In VarGroupingEditorDlg::OnIncludeListEditEnd
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListEdit
In VarGroupingEditorDlg::OnIncludeListEditEnd
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListEdit
In VarGroupingEditorDlg::OnIncludeListEditEnd
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnCreateGrpClick
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In TableFrame::OnActivate
In TableFrame::OnActivate
In GdaFrame::OnHinge15()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
HR
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TimeChooserDlg::OnPlayPauseButton
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
In TimeChooserDlg::OnPlayPauseButton
Open LineChartFrame(Average Charts).
In LineChartFrame::OnActivate()
In LineChartFrame::OnVariableChoice()
var: regions, time1:-1, time2:-1, group1:0, group2:1
In LineChartFrame::OnVariableChoice()
var: HR, time1:0, time2:0, group1:0, group2:1
In LineChartFrame::OnActivate()
In LineChartFrame::OnTime2Choice()
var: HR, time1:0, time2:1, group1:0, group2:1
In LineChartFrame::OnApplyButton()
Run LineChartFrame::RunDIDTest
Open RegressionReportDlg.
In LineChartFrame::OnActivate()
In LineChartFrame::OnActivate()
In LineChartFrame::OnActivate()
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In VarGroupingEditorDlg::OnClose
Close TimeChooserDlg::OnClose
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
MapCanvas::~MapCanvas()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/Julia/Box Sync/Julia/CSDS/Data/Testing/Unable_to_merge_table_Data/UScounties/UScounties.shp
Open Layer:UScounties
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/Julia/Box Sync/Julia/CSDS/Data/Testing/Unable_to_merge_table_Data/UScounties/UScounties.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
Open DataViewerEditFieldPropertiesDlg
In DataViewerEditFieldPropertiesDlg::OnGridComboBox
0
Entering DataViewerEditFieldPropertiesDlg::OnFieldSelected
Entering DataViewerEditFieldPropertiesDlg::OnCellChanging
changing row 4, col 1 from string to real
Entering DataViewerEditFieldPropertiesDlg::OnCellChanging
changing row 4, col 4 from 5 to 0

**Comment by YidanJ-Wu** [comment]
Windows 8 1.10.1.77
No longer crashes. Instead, when I change the number of displayed digits to 0 and press enter, it reverts back to the previous value. 
![image](https://user-images.githubusercontent.com/22801047/30894178-d078d980-a307-11e7-8dd8-4bfcaa1e89fc.png)
after
![image](https://user-images.githubusercontent.com/22801047/30894189-de8fb110-a307-11e7-93cf-369c3b746087.png)

**Comment by jkoschinsky** [comment]
confirmed -- no longer crashes in GeoDa 1.10.1.73 (OSX Yosemite, 10.10.5).
Leaving open bc of issue above.

**Comment by lixun910** [comment]
I just checked, GeoDa originally has code to prevent user to input 0 display decimal for a floating point number. I think this can help to distinguish float and integer number, which is a good design. Let me know if you need to change this design.

**Comment by jkoschinsky** [comment]
GeoDa 1.10.1.83 (OSX Yosemite, 10.10.5).

Steps:
1. open csv
2. convert string to real
3. try to change displayed decimal places

--> the field is locked and can't be edited. You have to close the "Edit Variable Properties" dialog and re-open it: Now you can edit "displayed decimal places." Can you enable this at the same time as you're converting from string to real so you don't have to close and re-open?

<img width="494" alt="screen shot 2017-09-29 at 12 21 21 pm" src="https://user-images.githubusercontent.com/13679743/31027729-f28634f4-a510-11e7-8bef-d2ec228c6dea.png">

**Comment by lixun910** [comment]
From the screenshot, you click on the “Address_1” which is a string type — so the displayed decimal places can’t be edited. Same to an integer type, you can’t edit its decimal places.

**Comment by jkoschinsky** [comment]
no, I tried Address_3, which is numeric and converted fine to real.

**Comment by jkoschinsky** [comment]
GeoDa 1.10.1.85 (OSX Yosemite, 10.10.5).

I can now edit the displayed decimal places and they're correctly applied. However, when I save the csv, close and re-open, the displayed decimal places aren't saved (e.g. I set them to 2 and the re-opended file has 7 and the 2 is no longer under edit variable properties).

**Comment by lixun910** [comment]
We don’t save this information.

**Comment by lixun910** [comment]
We don’t save this information. It’s based on each file and has to associate with file. So it’s complex to do.
