### ISSUE TITLE
Field Name Correction Dialog update

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1031]
When do merge in GeoDa,  field names from imported dataset maybe invalid (e.g. for dbf merge, has to be numbers and letter and no more than 16 characters), or are duplicated with existing table fields. Field Name Correction Dialog will be popped to show user suggested field names. 

Current field name correct dialog: 
<img width="678" alt="screen shot 2017-08-16 at 9 47 14 pm" src="https://user-images.githubusercontent.com/2423887/29396511-2afa653c-82cd-11e7-8061-a4538efe9979.png">
Will be updated to:
<img width="722" alt="screen shot 2017-08-16 at 9 39 18 pm" src="https://user-images.githubusercontent.com/2423887/29396517-31c4fd6e-82cd-11e7-9947-125073eb9ef9.png">
1. First column: "Field name" will be the ones need new names. The reason why it needs a new name is shown in the text next to it. 
2. Second column: "Suggest field name" will be new field names automatically generated for user.
3. If user changed suggested field name, and GeoDa will check if user input is valid or not. If it's not valid, user input text will be colored in red with description text next to it.
<img width="799" alt="screen shot 2017-08-16 at 9 39 33 pm" src="https://user-images.githubusercontent.com/2423887/29396523-3bdf8b70-82cd-11e7-9a76-eab2e408f964.png">

**Comment by jkoschinsky** [comment]
great solution, thx

**Comment by lixun910** [comment]
Hi Julia

Can you share this with Mark?
https://www.dropbox.com/s/h7nccpxcfqruavg/GeoDa1.10.1.25-Installer.dmg?dl=0

Xun

Xun Li, Ph.D

Assistant Director for Data Science
Center for Spatial Data Science
University of Chicago
http://spatial.uchicago.edu

**Comment by YidanJ-Wu** [comment]
Windows 1.10.1.77 
Verified

**Comment by jkoschinsky** [comment]
Right now this is the text you get when you save a csv as a spatial file with field names that need to be updated (e.g. in the vehicles data for Luc's class):


I would suggest the following language instead:
View header: Field Name Correction --> Update Field Name
Field name --> Current field name
Suggest field name --> Suggested field name to match new table format

(Field name is not valid) --> (Incompatible format)

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.83 (OSX Yosemite, 10.10.5).

<img width="722" alt="screen shot 2017-09-29 at 12 12 02 pm" src="https://user-images.githubusercontent.com/13679743/31027330-725f8a38-a50f-11e7-8c5c-e0d4a2ff7214.png">
