### ISSUE TITLE
variable calculation -- add binary weights option

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1033]
in the variable calculation dialog, under spatial lag, it would be useful to add an option to use a non row-standardized spatial weights matrix. especially in the case where the variable under consideration is a 0-1 binary variable, this would yield the count of neighbors with a value of 1. for the other cases, it would compute the sum of the values in the neighbors. once we have inverse distance weights enabled, this would compute a distance discounted sum of the neighbor values, or an accessibility measure, useful in the estimation of SLX models.

**Comment by lixun910** [comment]
Yes, just checked the code, it's only row standardized lag calculation.
Will add a checkbox to allow use non row-standardized weights.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
Verified 

![15 mar 8](https://user-images.githubusercontent.com/36253697/37496550-0cf92b02-28ab-11e8-9060-3664bab1c468.PNG)

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v113
OSX
