### ISSUE TITLE
variable calculation -- add self-neighbor option

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1034]
in the variable calculation spatial lag dialog, add an option to include the diagonal of the weights matrix (i.e., self-neighbor relations). this would be in combination with the option to use "raw" non-standardized weights (or not) -- see #1033.

this would allow the computation of a window average (using row-standardization) or window sum (using non-standardized weights), useful in regression analysis of market sheds.

**Comment by jkoschinsky** [comment]
Great, this is what we need for the access score calculation

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
Verified 

![15 mar 8](https://user-images.githubusercontent.com/36253697/37496579-3ac89f72-28ab-11e8-82ac-4bb1fe0e309b.PNG)

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v113
OSX
