### ISSUE TITLE
k-means -- add weighting for geometric centroids

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1035]
As currently implemented, the k-means approach with the geometric centroids included treats the latter as two additional variables, standardized (if that option is chosen).  It would be nice if there were an option to treat the total dissimilarity as a weighted sum of the dissimilarity on the features and the dissimilarity on the centroids, allowing for an explicit evaluation of the trade-offs between the two (this is the approach used in SAGE by Haining et al). In the current approach, there is an indirect weighting, in that as there are more variables included they will affect the dissimilarity measure more than the two coordinates. Since the dissimilarity measures are additive, we can implement this as a weighted sum. The default could be to leave as is (indirect weighting), with the weight as an option in the dialog.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
Verified 

![15 mar 7](https://user-images.githubusercontent.com/36253697/37496260-6276cca8-28a9-11e8-9e4f-f68f09b14f70.PNG)

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v113
OSX
