### ISSUE TITLE
k-means and others -- add option for minimum size

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1036]
Add an option to include an additional constraint that ensures that each "cluster" has at least x of a given variable z. For example, this could ensure that each cluster has at least some minimum population size. The variable to set the constraint does not need to be part of the features and should be a simple integer count. This is similar to the approach taken in max-p, but should ideally be included as an option in all the clustering routines.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
Verified 

![15 mar 6](https://user-images.githubusercontent.com/36253697/37496003-ff3b7036-28a7-11e8-980d-5658606eea63.PNG)

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v113
OSX
