### ISSUE TITLE
clustering module -- add MDS

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1037]
Include multidimensional scaling as one of the options in the clustering module. Output should be x,y coordinates added to data table and plotted as a point map (same "geography" as original data) to allow linking/brushing with original polygon map(s).

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
Verified 

![15 mar 5](https://user-images.githubusercontent.com/36253697/37495600-dc1ee670-28a5-11e8-93b9-01d4e0197468.PNG)

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v113
OSX
