### ISSUE TITLE
Crash: Map + Category Editor

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1038]
From: 
 Details:
os: 3-4-10
vs: 1-10-0-8
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/estanleyslao/Dropbox/ADMU-ASOG/Potential Implications of Switching to Federalism/Data/GIS Data Working File/Bangsamoro/Bangsamoro.shp
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Entering GdaFrame::OnMapChoices
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
MapCanvas::~MapCanvas()

**Comment by jkoschinsky** [comment]
Julia will try to replicate

Steps: 

1. open map
2. update categories

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.14.1

Updating categories works however I noticed something odd while interacting with the histogram and looking at the map. Although the plot says that each of the 8 categories exist at least once, the map does not show that with either the color or variable key on the left side. Although the map says that only one of the categories occurs, when you click on one of the categories for the histogram, the corresponding sections of the map are highlighted as shown below. This only occurs when you create a new custom break as the original still functions normally.

(Histogram with saved custom breaks map)
<img width="1396" alt="screen shot 2018-07-09 at 3 46 55 pm" src="https://user-images.githubusercontent.com/37029239/42475130-5d8ef4ea-838f-11e8-9290-04b2777908c1.png">

(Original custom breaks map)
<img width="593" alt="screen shot 2018-07-09 at 3 51 29 pm" src="https://user-images.githubusercontent.com/37029239/42475371-0d340066-8390-11e8-9af3-803aea5ac275.png">

**Comment by VeraB620** [comment]
OS X El Capitan 10.11.6
GeoDa 1.12.1.141

updating categories works, however the histogram does not fit on the screen no matter how big I make it
<img width="1276" alt="screen shot 2018-07-17 at 11 41 13 am" src="https://user-images.githubusercontent.com/4943475/42832308-739fb0f8-89b6-11e8-82e6-c0df632c933a.png">
