### ISSUE TITLE
Crash: EB LISA

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1041]
Details:
os: 2-6-1
vs: 1-8-16-4
Check auto update:
Open LisaMapFrame (OnOpenLisaEB).
Open VariableSettingsDlg
Error: XRC error: 1505: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1534: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1541: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
EtabInfT
Densidade
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Click GdaFrame::OnSaveCanvasImageAs
Click GdaFrame::OnSaveCanvasImageAs
Click GdaFrame::OnSaveCanvasImageAs
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
PMigrPend
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
DEmp1
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
DEmp2
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
DEmp3
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
DEmp4
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
DEmp5
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
EtabInf1
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
TotEtab1
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
TotEtab2
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
TotEtab3
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
TotEtab4
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
TotEtab5
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenLisaEB).
Open VariableSettingsDlg
Error: XRC error: 1505: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1534: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1541: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
TotEtab1
Densidade
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
TotEtab2
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenLisaEB).
Open VariableSettingsDlg
Error: XRC error: 1505: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1534: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1541: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
TotEtab2
Densidade
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
In GdaFrame::OnOpenStddev()
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
TotEtab1
Open MapFrame.
In GdaFrame::OnOpenStddev()
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
TotEtab2
Open MapFrame.
In GdaFrame::OnOpenStddev()
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
DEmp1
Open MapFrame.
Open LisaMapFrame (OnOpenLisaEB).
Open VariableSettingsDlg
Error: XRC error: 1505: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1534: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1541: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
TotEtab3
Densidade
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenLisaEB).
Open VariableSettingsDlg
Error: XRC error: 1505: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1534: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1541: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
TotEtab4
Densidade
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenLisaEB).
Open VariableSettingsDlg
Error: XRC error: 1505: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1534: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1541: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
TotEtab5
Densidade
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
EtabFInd
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenLisaEB).
Open VariableSettingsDlg
Error: XRC error: 1505: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1534: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1541: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
EtabFInd
Densidade
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenLisaEB).
Open VariableSettingsDlg
Error: XRC error: 1505: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1534: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1541: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
EtabFInd
TotEtabTot
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenLisaEB).
Open VariableSettingsDlg
Error: XRC error: 1505: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1534: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1541: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
EtabFInd
EtabFTot
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
EtabFInd
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
EtabFServ
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
EtabFCom
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
EtabFAg
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
TotEtab1
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
TotEtab2
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenLisaEB).
Open VariableSettingsDlg
Error: XRC error: 1505: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1534: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1541: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
PMaisUma
Densidade
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
PMaisUma
VariableSettingsDlg::GetWeightsId() weight: WeightRio
VariableSettingsDlg::GetWeightsId() weight: WeightRio
Click GdaFrame::OnClose

**Comment by jkoschinsky** [comment]
Julia will try to replicate

Steps: 

1. open LISAEB
2. create weights

--> keeps getting this error (LEFT or RIGHT): "horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead"

what is this referring to?

**Comment by lixun910** [comment]
This is an old bug in 1.8, and has been fixed in 1.10
