### ISSUE TITLE
Crash: Field name issues

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1042]
From: lanselin@gmail.com
 Details:
os: 1-10-12
vs: 1-10-1-35
/Users/luc/Desktop/GeoDa.1.10.1.35.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
GdaFrame::OpenProject()
/Users/luc/Dropbox/1950, 1980, 2010 income/AlllayersBlockScoresV2/NEWVARS/AllLayersBlockScoresV2.gda
Entering Project::Project (existing project)
/Users/luc/Dropbox/1950, 1980, 2010 income/AlllayersBlockScoresV2/NEWVARS/AllLayersBlockScoresV2.gda
Project::SetProjectFullPath()
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/luc/Dropbox/1950, 1980, 2010 income/AlllayersBlockScoresV2/NEWVARS/AllLayersBlockScoresV2.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open project file:/Users/luc/Dropbox/1950, 1980, 2010 income/AlllayersBlockScoresV2/NEWVARS/AllLayersBlockScoresV2.gda
Entering GdaFrame::OnMapChoices
In TableFrame::OnActivate
Entering GdaFrame::OnMapChoices
In GdaFrame::OnOpenUniqueValues()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
DEssential
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open OnOpenLocalJoinCount().
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
DEssential
VariableSettingsDlg::GetWeightsId() weight: AllLayersBlockScoresV2._qgal
VariableSettingsDlg::GetWeightsId() weight: AllLayersBlockScoresV2._qgal
Entering GetisOrdMapFrame::GetisOrdMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Exiting GetisOrdMapFrame::GetisOrdMapFrame
In GdaFrame::OnSaveGetisOrd()
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In GdaFrame::OnSelectCoresAndNeighbors()
Entering GetisOrdMapFrame::OnSelectCoresAndNeighbors
Exiting GetisOrdMapFrame::OnSelectCoresAndNeighbors
Click GdaFrame::OnSaveSelectedToColumn
Open SaveSelectionDlg.
Click SaveSelectionDlg::OnSelUnselTextChange
Click SaveSelectionDlg::OnSelUnselTextChange
Click SaveSelectionDlg::OnSelUnselTextChange
Click SaveSelectionDlg::OnSelUnselTextChange
Click SaveSelectionDlg::OnApplySaveClick
Click SaveSelectionDlg::OnCancelClick
In TableFrame::OnActivate
In TableFrame::OnActivate
Open RangeSelectionDlg
In RangeSelectionDlg::OnRangeTextChange()
In RangeSelectionDlg::OnRangeTextChange()
In RangeSelectionDlg::OnRangeTextChange()
In RangeSelectionDlg::OnRangeTextChange()
In RangeSelectionDlg::OnSelUnselTextChange()
In RangeSelectionDlg::CheckApplySaveSettings()
In RangeSelectionDlg::OnSelUnselTextChange()
In RangeSelectionDlg::CheckApplySaveSettings()
In RangeSelectionDlg::OnSelUnselTextChange()
In RangeSelectionDlg::CheckApplySaveSettings()
In RangeSelectionDlg::OnSelUnselTextChange()
In RangeSelectionDlg::CheckApplySaveSettings()
In RangeSelectionDlg::CheckApplySaveSettings()
In RangeSelectionDlg::OnFieldChoice()
In RangeSelectionDlg::OnRangeTextChange()
Entering RangeSelectionDlg::OnApplySelClick
In RangeSelectionDlg::CheckApplySaveSettings()
In RangeSelectionDlg::OnAddField()
Open DataViewerAddColDlg.
DataViewerAddColDlg::CreateControls()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
In DataViewerAddColDlg::SetDefaultsByType()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::UpdateMinMaxValues()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::UpdateMinMaxValues()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnOkClick()
Inserting new column S1_ESSENT into Table
In RangeSelectionDlg::CheckApplySaveSettings()
In TableFrame::OnActivate
In RangeSelectionDlg::CheckApplySaveSettings()
In RangeSelectionDlg::OnApplySaveClick()
In RangeSelectionDlg::CheckApplySaveSettings()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In RangeSelectionDlg::CheckApplySaveSettings()
Open DataViewerDeleteColDlg.
In TableFrame::OnActivate
In GdaFrame::OnSelectCores()
Entering GetisOrdMapFrame::OnSelectCores
Exiting GetisOrdMapFrame::OnSelectCores
Click GdaFrame::OnSaveSelectedToColumn
Open SaveSelectionDlg.
Click SaveSelectionDlg::OnSelUnselTextChange
Click SaveSelectionDlg::OnSelUnselTextChange
Click SaveSelectionDlg::OnSelUnselTextChange
Click SaveSelectionDlg::OnSelUnselTextChange
Click SaveSelectionDlg::OnApplySaveClick
In RangeSelectionDlg::CheckApplySaveSettings()
In RangeSelectionDlg::CheckApplySaveSettings()
Click SaveSelectionDlg::OnCancelClick
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In RangeSelectionDlg::CheckApplySaveSettings()
Open DataViewerDeleteColDlg.
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnDelete()
PP_VAL
In RangeSelectionDlg::CheckApplySaveSettings()
JC
In RangeSelectionDlg::CheckApplySaveSettings()
In TableFrame::OnActivate
Click GdaFrame::OnSaveProject
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs
New Datasource Name:/Users/luc/Dropbox/1950, 1980, 2010 income/AlllayersBlockScoresV2/NEWVARS/GdaTmp_AllLayersBlockScoresV2.shp
Project::GetSpatialReference()
Project::GetGdaGeometries()
ScrolledWidgetsPane::IsFieldNameValid
statefp10
ScrolledWidgetsPane::IsFieldNameValid
countyfp10
ScrolledWidgetsPane::IsFieldNameValid
tractce10
ScrolledWidgetsPane::IsFieldNameValid
geoid10
ScrolledWidgetsPane::IsFieldNameValid
blockce10
ScrolledWidgetsPane::IsFieldNameValid
tract_bloc
ScrolledWidgetsPane::IsFieldNameValid
name10
ScrolledWidgetsPane::IsFieldNameValid
DummyTotal
ScrolledWidgetsPane::IsFieldNameValid
Block_Dail
ScrolledWidgetsPane::IsFieldNameValid
Block_Da_1
ScrolledWidgetsPane::IsFieldNameValid
Block_degr
ScrolledWidgetsPane::IsFieldNameValid
Block_Empl
ScrolledWidgetsPane::IsFieldNameValid
Block_Land
ScrolledWidgetsPane::IsFieldNameValid
Block_pct_
ScrolledWidgetsPane::IsFieldNameValid
Block_Rati
ScrolledWidgetsPane::IsFieldNameValid
DEssential
ScrolledWidgetsPane::IsFieldNameValid
DOption
ScrolledWidgetsPane::IsFieldNameValid
DDegrade
ScrolledWidgetsPane::IsFieldNameValid
DSidewalk
ScrolledWidgetsPane::IsFieldNameValid
DEmploy
ScrolledWidgetsPane::IsFieldNameValid
DLand
ScrolledWidgetsPane::IsFieldNameValid
Chainpct
ScrolledWidgetsPane::IsFieldNameValid
DWidth
ScrolledWidgetsPane::IsFieldNameValid
Dchainpct
ScrolledWidgetsPane::IsFieldNameValid
totalDvar
ScrolledWidgetsPane::IsFieldNameValid
AREA
ScrolledWidgetsPane::IsFieldNameValid
justgood
ScrolledWidgetsPane::IsFieldNameValid
justbad
ScrolledWidgetsPane::IsFieldNameValid
Dwidthnew
ScrolledWidgetsPane::IsFieldNameValid
DDegradnew
ScrolledWidgetsPane::IsFieldNameValid
NN
ScrolledWidgetsPane::IsFieldNameValid
NN_1_essen
ScrolledWidgetsPane::IsFieldNameValid
S_essential
ScrolledWidgetsPane::IsFieldNameValid
S1_ESSENT
ScrolledWidgetsPane::IsFieldNameValid
C_essen
ScrolledWidgetsPane::RemoveIllegalChars
S_essential
S_essential
ScrolledWidgetsPane::TruncateFieldName
S_essential
S_ess_tial
ScrolledWidgetsPane::RenameDupFieldName
S_ess_tial
S_ess_tial
ScrolledWidgetsPane::IsFieldNameValid
S_essen
ScrolledWidgetsPane::IsFieldNameValid
S_essen
ScrolledWidgetsPane::IsFieldNameValid
S_essen

**Comment by lanselin** [comment]
I think this has been reported before. When saving the table, after adding new variables, one of the variable names was too long. So the field name correction dialog pops up. However, after the name is changed (as shown on screen shot), GeoDa just freezes (not even spinning ball). Cancel doesn't work, the only thing that works is a hard "kill" in the terminal. The data set is quite large, dbf is 89 Mb, so maybe that's it.

<img width="405" alt="screen shot 2017-08-23 at 8 27 07 am" src="https://user-images.githubusercontent.com/4008351/29624134-3150cc18-87dd-11e7-934d-3aba0882e146.png">

**Comment by jkoschinsky** [comment]
See tickets https://github.com/GeoDaCenter/geoda/issues/1044 and https://github.com/GeoDaCenter/geoda/issues/1031

**Comment by lanselin** [comment]
Sorry, forgot to mention using 1.10.1.61

**Comment by YidanJ-Wu** [comment]
Windows 8 1.10.1.77 
Verified

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.73 (OSX Yosemite, 10.10.5).
