### ISSUE TITLE
I can't add variables

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1044]
I just can't add any new variable; when I type it, red letters apper and the add option is not enabled

os: 1-10-12
vs: 1-10-0-12
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/emilianoisaza/Desktop/datos clase geoda/Data/stl_hom
Open Layer:stl_hom
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/emilianoisaza/Desktop/datos clase geoda/Data/stl_hom
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open FieldNewCalcSheetDlg.
In FieldNewCalcSheetDlg::OnClose()
Open DataViewerAddColDlg.
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
In GdaFrame::OnReportBug()
Open ReportBugDlg.
In ReportBugDlg::OnOkClick()

**Comment by lixun910** [comment]
Thanks for your report! 

Can you tell us what field name you are trying to input? GeoDa will check your input if it's valid for certain predefined restrictions. E.g. If you open a shp/dbf dataset, the field name has to follow the dbf restrictions: only numbers and letters allowed, start with letter and the length should be no more than 12 characters. 

Xun

**Comment by jkoschinsky** [comment]
See ticket https://github.com/GeoDaCenter/geoda/issues/1031

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.77 (OSX Yosemite, 10.10.5).

**Comment by deannamorra** [comment]
Hello,

I'm also having the same issue as the original poster. Is there a way to resolve this?

Thanks!

**Comment by lixun910** [comment]
@deannamorra Can you try our latest GeoDa to see if it has been fixed? Thanks!
Win64: https://www.dropbox.com/s/cnnb1e1mo329ush/GeoDa-1.12.1.19-Windows-64bit.exe?dl=0
Mac OSX: https://www.dropbox.com/s/wnvychvrpl1djz0/GeoDa1.12.1.19-Installer.dmg?dl=0

**Comment by deannamorra** [comment]
@lixun910 I tried the latest GeoDa and the error is still occurring

**Comment by lixun910** [comment]
@deannamorra Can you send me a screenshot of what the error looks like on your side? Thanks!
lixun910@gmail.com
