### ISSUE TITLE
table - add aggregation option

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1045]
It would be relatively straightforward to add an aggregation function to the table, where units are combined into larger units based on a unique identifier for the larger unit. For example, in a table containing data for points, but also an identifier for the census tract of those point, the point data could be aggregated by census tract and saved as a separate table. This could then be joined with a census tract layer. The aggregation could be for selected variables, or for all. Aggregation functions could be: sum, mean, median, max, min. The key is the presence of a unique identifier for each aggregate unit.

**Comment by YidanJ-Wu** [comment]
Windows 1.10.1.77 
Verified

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.73 (OSX Yosemite, 10.10.5).
