### ISSUE TITLE
exit with unsaved changes not behaving well

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1049]
There still seems to be something goofy with the logic behind the "Exit with unsaved changes" dialog. For example, after editing the table, and using the save icon to save the changes - so all changes have been saved - upon exit, the unsaved changes dialog appears anyway. It would seem that after one uses the save icon dialog (or file save) the flag for unsaved changes should be updated.

**Comment by lanselin** [comment]
There still is a problem. Use case: I open GeoDa, load the Guerry sample data set, don't do anything, close GeoDa and get an unsaved changes message (see attached - also note there is a typo in the message). Nothing was changed.

<img width="419" alt="screen shot 2017-08-29 at 8 58 37 am" src="https://user-images.githubusercontent.com/4008351/29830955-854892be-8c98-11e7-9ea0-b0b6254ff3a9.png">

**Comment by YidanJ-Wu** [comment]
Windows 8 
1.10.1.77 
Verified

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.79 (OSX Yosemite, 10.10.5).
