### ISSUE TITLE
PCA - add correlation matrix in output

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1050]
Add the correlation matrix between the original variables and the principal components in the output pane for PCA. This is a better/easier way to interpret the importance of individual variables in each of the components (note: the sign is irrelevant, the magnitude is what matters). So, this is a simple correlation matrix between (vars, PC), in the same format as the Eigenvectors table.

**Comment by lanselin** [comment]
Actually, even better would be the squared correlations, since these directly show the % of variance in the original variable explained by the component (the sum of the squared correlations across all principal components equals 1).

**Comment by lanselin** [comment]
Rename "Eigenvectors" to "Eigenvectors/Variable Loadings"

**Comment by lanselin** [comment]
There should also be a way to print out/save the output of the PCA analysis to a text file.

**Comment by lixun910** [comment]
I think we have "save" feature when you right click on PCA output box.

**Comment by lanselin** [comment]
OK, see it now.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
Verified 

![15 mar 3](https://user-images.githubusercontent.com/36253697/37495344-bd25eff8-28a4-11e8-80ce-1cdc58b14325.PNG)
![15 mar 4](https://user-images.githubusercontent.com/36253697/37495350-c0ba27ba-28a4-11e8-8aa7-580fce94f092.PNG)

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v113
OSX
