### ISSUE TITLE
Tools - points from table doesn't work

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1051]
The functionality to create a point layer from a table doesn't seem to be working anymore when a polygon or point file has been loaded (see first screen shot). It only works when a table is loaded in isolation (second screen shot). For example, it does not work when centroids were added to the table but not saved. I also doesn't work when MDS coordinates have been added to the table, which is pretty critical.

<img width="312" alt="screen shot 2017-08-29 at 8 32 09 am" src="https://user-images.githubusercontent.com/4008351/29829785-2c48bafc-8c95-11e7-84a5-994967a839a7.png">

<img width="311" alt="screen shot 2017-08-29 at 8 33 37 am" src="https://user-images.githubusercontent.com/4008351/29829797-33985114-8c95-11e7-95c8-b6e73cc9c655.png">

**Comment by YidanJ-Wu** [comment]
Windows 8 1.10.1.65 
Fixed

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.79 (OSX Yosemite, 10.10.5).
