### ISSUE TITLE
max-p issues

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1052]
Several issues pertaining to the max-p interface:

- no need for "use geometric centroids"

- floor variable is required for minimum bound, this should not be an option (as it stands, the program won't run if there isn't a minimum bound, but it does not require a minimum bound variable; there should be a way to run without minimum bound (the latter is not a requirement in max-p, but an option), but when a floor variable is specified, there should be a minimum bound (there should be a suggested value, since this totally depends on the scale of the "floor variable"); the minimum bound box should be below the Set floor variable check box and only be active if the latter is checked and a variable specified.

- set initial groups should only allow integer valued variables, the idea is to seed the initial clusters using a regime variable (or the results of a previous cluster analysis), so this should not be allowed for just any real-valued variable

- transformation default should be set to "Standardize", not "Raw"

- distance options should be included (to compute intra-region homogeneity)

- save cluster in Field should have a default variable (see also issues for all cluster approaches)

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
Verified 

![15 mar 01](https://user-images.githubusercontent.com/36253697/37494569-404e1ad0-28a1-11e8-8476-7e149335fc5c.PNG)
![15 mar 2](https://user-images.githubusercontent.com/36253697/37494572-4486c9a8-28a1-11e8-916c-ce1ab12ae431.JPG)

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v113
OSX
