### ISSUE TITLE
cluster methods - misc issues

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1053]
These issues are common to all the cluster methods:

- interface should suggest a variable name for "Save Cluster in Field", e.g., CL; as it stands, leaving this empty generates an error message

- distance options should be limited to Euclidean and Manhattan (others are too complex)

- output should include performance statistics, e.g., summary of intra-group "distance" measure for each group, centroids/mean-median centers for each group, sum of intra-group distance measures, similar to output for PCA.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
Verified 

![14 mar 07](https://user-images.githubusercontent.com/36253697/37437903-78ec2edc-27e7-11e8-90b5-ada487dcbb97.JPG)

<img width="550" alt="14 mar 08" src="https://user-images.githubusercontent.com/36253697/37437898-7173e3fc-27e7-11e8-9443-5e58b11a1d6c.PNG">

<img width="956" alt="14 mar 09" src="https://user-images.githubusercontent.com/36253697/37437908-83091de4-27e7-11e8-95ed-8bf72dab0991.PNG">

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v113
OSX
