### ISSUE TITLE
bivariate local join count statistic

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1061]
Implement three versions of bivariate local join count statistic, and extension to multiple categories of co-locational multivariate join count statistic.

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.14.1

<img width="284" alt="screen shot 2018-07-09 at 3 12 06 pm" src="https://user-images.githubusercontent.com/37029239/42473529-82673eda-838a-11e8-82b0-55d6c0af1b43.png">

<img width="597" alt="screen shot 2018-07-09 at 3 11 41 pm" src="https://user-images.githubusercontent.com/37029239/42473531-8282d5e6-838a-11e8-84df-cd809635076f.png">

<img width="597" alt="screen shot 2018-07-09 at 3 11 31 pm" src="https://user-images.githubusercontent.com/37029239/42473532-828e6b9a-838a-11e8-9fb9-537c711fa3c2.png">

<img width="282" alt="screen shot 2018-07-09 at 3 16 09 pm" src="https://user-images.githubusercontent.com/37029239/42473747-111f9924-838b-11e8-9220-13da22615fb6.png">

<img width="597" alt="screen shot 2018-07-09 at 3 10 13 pm" src="https://user-images.githubusercontent.com/37029239/42473533-829e78aa-838a-11e8-9caf-e01ca6cf4fa2.png">

**Comment by jkoschinsky** [comment]
leaving ticket open to test current fix

**Comment by VeraB620** [comment]
OS X El Capitan 10.11.6
GeoDa 1.12.1.147

<img width="226" alt="screen shot 2018-07-23 at 12 58 13 pm" src="https://user-images.githubusercontent.com/4943475/43091451-1c8ab422-8e78-11e8-956b-7580afcaa914.png">

Univariate Local Join Count:
<img width="598" alt="screen shot 2018-07-23 at 12 56 39 pm" src="https://user-images.githubusercontent.com/4943475/43091540-54b8e0c6-8e78-11e8-8914-a997a528fd71.png">


Bivariate Local Join Count:
<img width="599" alt="screen shot 2018-07-23 at 12 56 45 pm" src="https://user-images.githubusercontent.com/4943475/43091510-44b1d7aa-8e78-11e8-97f9-2379e6fc97fc.png">


Multivariate Local Join Count (4 variables):
<img width="592" alt="screen shot 2018-07-23 at 12 56 51 pm" src="https://user-images.githubusercontent.com/4943475/43091526-4d623c64-8e78-11e8-94af-2135f1c6b532.png">
