### ISSUE TITLE
Crash: While loading csv file after specifying XY

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1062]
From: Julia Koschinsky
 Details:
os: 1-10-10
vs: 1-10-1-5
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/Julia/Box Sync/Julia/CSDS/Grants/RWJ/Data/LEHD Cook County/LEHD_CookCounty.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
In GdaFrame::OnMoveSelectedToTop
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
In TableFrame::OnActivate
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
MapCanvas::~MapCanvas()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
Open CsvFieldConfDlg.
CsvFieldConfDlg::PrereadCSV()
CsvFieldConfDlg::UpdateFieldGrid()
CsvFieldConfDlg::ReadCSVT()
CsvFieldConfDlg::UpdatePreviewGrid()
CsvFieldConfDlg::UpdateXYcombox()
CsvFieldConfDlg::OnOkClick()
CsvFieldConfDlg::WriteCSVT()
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/Julia/Box Sync/Julia/CSDS/Grants/RWJ/Data/Chicago contracts/chicago_contracts_XY.csv
Open Layer:chicago_contracts_XY
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/Julia/Box Sync/Julia/CSDS/Grants/RWJ/Data/Chicago contracts/chicago_contracts_XY.csv

**Comment by lixun910** [comment]
Thanks, Julia!

One thing: This is reported from version 1.10.1.5. It's a very old internal test version. The latest one is 1.10.1.45. I'd suggest you use public release one for testing, which is 1.10.0.18.

Xun

**Comment by jkoschinsky** [comment]
Thanks, Xun. You're right, this was an older version. I just tried with the
latest internal version I had (1.10.1.43) and the crash persisted. Will try
next with 1.10.0.18. Could you send me the URL for 45?

**Comment by lixun910** [comment]
Thanks, Julia!

Here is the link of 45:
https://www.dropbox.com/s/xjyjj2h3udvtp1k/GeoDa1.10.1.45-Installer.dmg?dl=0

Xun

**Comment by jkoschinsky** [comment]
ok, confirmed crash on 1.10.1.5, 1.10.0.18, and 1.10.1.43. Testing  1.10.1.45
now :)

**Comment by jkoschinsky** [comment]
crash confirmed on 1.10.1.45, too, so we have a real one!
will send you the link to the csv file now

**Comment by jkoschinsky** [comment]
Steps:

1. Open csv file
2. specify XY
3. crash while loading data

**Comment by lixun910** [comment]
Hi Julia, Can you share the data with me? Thanks!

**Comment by jkoschinsky** [comment]
here you go:
[test.zip](https://github.com/GeoDaCenter/geoda/files/1329408/test.zip)

**Comment by YidanJ-Wu** [comment]
Windows 8 1.10.1.75
Verified

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.77 (OSX Yosemite, 10.10.5).
