### ISSUE TITLE
load csv with empty x(lat) and y(lng)

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1068]
From Luc:

After closing GeoDa and then upon opening taking out the recent file,
close again and reopen. I get the “nice” (but wrong) Chicago points and
can add base map (first two screen shots).

Then, I delete the csvt file and load the csv again, and get the “ugly”
but correct points. When adding a background layer I get the whole
world. But earlier, I got the error message of incorrect projection information.
I have not been able to replicate that yet.

**Comment by lixun910** [comment]
This is a bug of "Shape->Points from Table": 

First of all, there are some rows with empty lat/lng values (not lat=0 lng=0). So, when draw the map using lat/lng, the observations with empty lat/lng values should not be displayed. Then the "nice" map (with basemap layer) is actually correct.

When you delete the csvt file, and load the csv again from "Recent" panel, you need to get the points map using "Shape->Points from Table". However this features does NOT handle the empties (undefined), instead it uses lat=0 lng=0 for these empties -- which is not correct.

**Comment by jkoschinsky** [comment]
when you save as point layer and open, then empty records are displayed as zeros. 

Instead, solution should be:
- flag with listing of records with empty coordinates
- option to save that list
- don't display the records without coordinates

**Comment by lixun910** [comment]
Hi Julia

This has been fixed, can you help to verify it? Empty x/y will be saved as empty geometries, so no data loss. Or one can also save selected (with geometries)

Xun

**Comment by jkoschinsky** [comment]
yes, we'll verify everything that has the "fixed: verify" label. Luc wanted
to make sure the problem is also fixed for opening the saved spatial files.
Thx

**Comment by lixun910** [comment]
Got it. Will check as well.

**Comment by lanselin** [comment]
The saved files load with the proper spatial extent (ignoring the missing coordinates),
but there is no warning that there are missing coordinates. There should be a warning,
listing the record numbers of the missing coordinates.

**Comment by jkoschinsky** [comment]
Thx, we also need warning label.

**Comment by YidanJ-Wu** [comment]
Windows 8 1.10.1.75
Verified

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.79 (OSX Yosemite, 10.10.5).

Warning label and only points with geometries displayed (see difference in N):

<img width="1060" alt="screen shot 2017-09-27 at 4 42 58 pm" src="https://user-images.githubusercontent.com/13679743/30939434-047e17cc-a3a3-11e7-9bf1-4b4e7e603804.png">

<img width="377" alt="screen shot 2017-09-27 at 4 43 17 pm" src="https://user-images.githubusercontent.com/13679743/30939431-00ae29b6-a3a3-11e7-96fe-b842d1ea1d02.png">
