### ISSUE TITLE
support conversion between date/time and other data types

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1069]

**Comment by YidanJ-Wu** [comment]
Successfully changed a variable from string to datetime. There was a delay and the screen froze, then unfroze. 
Then, changed the variable back to string, which crashed GeoDa.
Windows 8 1.10.1.65

**Comment by YidanJ-Wu** [comment]
Windows 8 1.10.1.81 
Verified

**Comment by jkoschinsky** [comment]
When you convert string to date for a format that GeoDa doesn't support, it returns empty cells and you can't get back to the original dates. A better solution would be to add a flag: Your date format is not supported by default. Please add it in Preferences.

That way people won't lose their data (or avoid having to exist without saving, which can be annoying if you made other changes you want to keep.

**Comment by jkoschinsky** [comment]
could you check this for these data:
[test3.zip](https://github.com/GeoDaCenter/geoda/files/1345178/test3.zip)

I added %m/%d/%y %H:%M to the date format to match this format:
<img width="93" alt="screen shot 2017-09-29 at 12 34 23 pm" src="https://user-images.githubusercontent.com/13679743/31028178-b28b739e-a512-11e7-9ac2-9dfb6cb848d7.png">

but when you convert from string to date, it still returns empty cells. Is there something wrong with my formula or is there another problem?

**Comment by lixun910** [comment]
This is an interesting case! 

Actually, if you put the %m%d%y %H:%M in the front in preference dialog. It will work.

It is because in the predefined date/time format, there is a %H:%M which matches 5/26/00 0:00. However, since in date format, no hours/minutes/seconds will be displayed, you will see an empty string.

I will update a fuzzy match to an exact match, so you won’t get an empty string.

**Comment by jkoschinsky** [comment]
another issue: when I replace all of the date formats with only %m%d%y %H:%M and choose close, it seems to reset and default back to the original settings?

<img width="734" alt="screen shot 2017-09-29 at 1 11 46 pm" src="https://user-images.githubusercontent.com/13679743/31029594-f026a93a-a517-11e7-97fc-44673711e1bb.png">

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.85 (OSX Yosemite, 10.10.5).

works now except for one thing: the hours and minutes aren't preserved:

<img width="879" alt="screen shot 2017-09-29 at 9 44 33 pm" src="https://user-images.githubusercontent.com/13679743/31041704-9b285f62-a55f-11e7-8790-eb04f12c1f9d.png">

even though this is specified under preferences:

<img width="691" alt="screen shot 2017-09-29 at 9 45 01 pm" src="https://user-images.githubusercontent.com/13679743/31041709-a56a846e-a55f-11e7-987a-eea9969a6451.png">

**Comment by lixun910** [comment]
Yes, you need to specify datetime type. Note: dbf only supports Date.

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.85 (OSX Yosemite, 10.10.5).
