### ISSUE TITLE
[Proposal] Debian packages provided for download should include the release in the version

### ISSUE THREAD

**Issue by papamoose** [GeoDaCenter/geoda#1074]
I propose that the [debian packages you provide](http://geodacenter.github.io/download_linux.html) should include the release name in their version. e.g.: `1.10-1xenial1` or `1.10-1ubuntu1~xenial1`

The reason for this is that when adding these packages to a debian repository there is a name conflict that cannot be resolved when the deb packages get copied into `pool`.

```
root@storage9:# umask 022; reprepro --keepunreferencedfiles -Vb /local/repository/repo includedeb xenial GeoDa-1.10-Ubuntu-16.04-64bit.deb
GeoDa-1.10-Ubuntu-16.04-64bit.deb: component guessed as 'main'
Created directory "/local/repository/repo/pool/main/g/geoda"
Exporting indices...
 looking for changes in 'xenial|main|amd64'...
  replacing '/local/repository/repo/dists/xenial/main/binary-amd64/Packages' (uncompressed,gzipped)
 looking for changes in 'xenial|main|i386'...
 looking for changes in 'xenial|main|i486'...
Successfully created '/local/repository/repo/dists/xenial/Release.gpg.new'
Successfully created '/local/repository/repo/dists/xenial/InRelease.new'

root@storage9:# umask 022; reprepro --keepunreferencedfiles -Vb /local/repository/repo includedeb trusty GeoDa-1.10-Ubuntu-14.04-64bit.deb
GeoDa-1.10-Ubuntu-14.04-64bit.deb: component guessed as 'main'
ERROR: 'GeoDa-1.10-Ubuntu-14.04-64bit.deb' cannot be included as 'pool/main/g/geoda/geoda_1.10_amd64.deb'.
Already existing files can only be included again, if they are the same, but:
md5 expected: f0be795302cbd1f59da683802eb196fa, got: ef5e7e94dac6630e8a125b3e51ecdc78
sha1 expected: b1b5fa56d2f9c9507f115bb7db76b50390fd646d, got: 779a7fc14fd7f62691c378bdb9c66fdd8e8daa9b
sha256 expected: cff07b4b89cd8ae1902743770b7d4b6b29e72ea65eefc370658b1b62d3ffb3b9, got: e1e88033bef0a165ffd8a7b2f5084e11b502650b87d42a00d697baae3654da2e
size expected: 20215148, got: 19393776
There have been errors!
```

I get around this issue by changing the version number inside the deb package like so:

```
wget -c https://s3-us-west-2.amazonaws.com/geodasoftware/GeoDa-1.10-Ubuntu-16.04-64bit.deb
wget -c https://s3-us-west-2.amazonaws.com/geodasoftware/GeoDa-1.10-Ubuntu-14.04-64bit.deb

rm -rf geoda_1.10-1xenial1_amd64 geoda_1.10-1trusty1_amd64
mkdir -p geoda_1.10-1xenial1_amd64 geoda_1.10-1trusty1_amd64

dpkg-deb -R GeoDa-1.10-Ubuntu-16.04-64bit.deb geoda_1.10-1xenial1_amd64
dpkg-deb -R GeoDa-1.10-Ubuntu-14.04-64bit.deb geoda_1.10-1trusty1_amd64

sed -i 's/Version: 1.10/Version: 1.10-1trusty1/' geoda_1.10-1trusty1_amd64/DEBIAN/control
sed -i 's/Version: 1.10/Version: 1.10-1xenial1/' geoda_1.10-1xenial1_amd64/DEBIAN/control

dpkg -b geoda_1.10-1xenial1_amd64
dpkg -b geoda_1.10-1trusty1_amd64
```
We can now see that I am able to add both packages into the repository.
```
# ls -1 /local/repository/repo/pool/main/g/geoda/
geoda_1.10-1trusty1_amd64.deb
geoda_1.10-1xenial1_amd64.deb

```

The [Debian policy](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version) doesn't seem to offer a clear way forward on this and in my experience I've seen just about everything. `~xenial1` seems less desirable because `~` seems to imply a beta release which is not what you are trying to convey. 

Of course, I also know that I am probably the only one adding these Debian packages to my own repository to enable deployment on many machines. Feel free to ignore this and I will rebuild the debian packages you release to suit my needs. :P

Am I totally off base here?

**Comment by papamoose** [comment]
Upon further review, it looks like Ubuntu does take advantage of the `~` to denote the release version.

Ubuntu 14.04 
Here we can see them not using it in 14.04, but maybe that 14 at the end means 14.04.
```
# apt-cache policy binutils
binutils:
  Installed: 2.24-5ubuntu14.2
  Candidate: 2.24-5ubuntu14.2
  Version table:
 *** 2.24-5ubuntu14.2 0
        500 http://mirror.cs.uchicago.edu/ubuntu/ trusty-security/main amd64 Packages
        500 http://mirror.cs.uchicago.edu/ubuntu/ trusty-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     2.24-5ubuntu3 0
        500 http://mirror.cs.uchicago.edu/ubuntu/ trusty/main amd64 Packages
```

Ubuntu 16.04
In 16.04 their notions on how to use the `~` clearly changed to denote the release version. I think this is entirely reasonable and think you should follow this pattern. Meaning your version numbers would look like this: `1.10-1ubuntu1~16.04`, `1.10-1ubuntu1~14.04`
You can safely leave out the point release.

If you ever make changes to the deb package and not the software version increment like this: `1.10-1ubuntu1~16.04` -> `1.10-1ubuntu2~16.04`

```
$ apt-cache policy binutils
binutils:
  Installed: 2.26.1-1ubuntu1~16.04.4
  Candidate: 2.26.1-1ubuntu1~16.04.4
  Version table:
 *** 2.26.1-1ubuntu1~16.04.4 500
        500 http://mirror.cs.uchicago.edu/ubuntu xenial-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     2.26.1-1ubuntu1~16.04.3 500
        500 http://mirror.cs.uchicago.edu/ubuntu xenial-security/main amd64 Packages
     2.26-8ubuntu2 500
        500 http://mirror.cs.uchicago.edu/ubuntu xenial/main amd64 Packages
```

**Comment by lixun910** [comment]
Thanks for your proposal, @papamoose ! Yes, this looks good to me. I know there are some computer labs deployed GeoDa debian packages on their machines. So, your proposal is definitely helpful for our next release.

**Comment by lixun910** [comment]
ssue #1074 ubuntu build script update
