### ISSUE TITLE
 clicked "cancel" when load large csv data set

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1077]
From: lanselin@gmail.com
 Details:
os: 1-10-12
vs: 1-10-1-51
/Users/luc/Desktop/GeoDa.1.10.1.51.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
Open CsvFieldConfDlg.
CsvFieldConfDlg::PrereadCSV()
CsvFieldConfDlg::UpdateFieldGrid()
CsvFieldConfDlg::ReadCSVT()
CsvFieldConfDlg::UpdatePreviewGrid()
CsvFieldConfDlg::UpdateXYcombox()
CsvFieldConfDlg::OnCancelClick()
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/luc/Dropbox/z_Courses/uc_spatial_data_science17/labs/1_datascience/311_Service_Requests_-_Abandoned_Vehicles copy.csv
Open Layer:311_Service_Requests_-_Abandoned_Vehicles copy
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/luc/Dropbox/z_Courses/uc_spatial_data_science17/labs/1_datascience/311_Service_Requests_-_Abandoned_Vehicles copy.csv

**Comment by lanselin** [comment]
Loading a very large csv file (970 Mb) -- worked fine earlier -- but clicked "cancel" in the dialog before actually loading the file. Spinning ball, had to force quit the program.

**Comment by YidanJ-Wu** [comment]
I had the same issue when loading a smaller (77 megabyte) file: 
![image](https://user-images.githubusercontent.com/22801047/30777034-b0bda554-a077-11e7-942f-c6c411b08d20.png)

The screen froze for a while and showed "Not Responding" for a while after I clicked "Cancel" but the file eventually loaded. 
![image](https://user-images.githubusercontent.com/22801047/30777047-e6af0d10-a077-11e7-92bd-2354185baee4.png)


Windows 8 1.10.1.65

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.79 (OSX Yosemite, 10.10.5).
Tried with 20MB csv - loaded fast.

**Comment by YidanJ-Wu** [comment]
Windows 8 1.10.1.81
Tried with 46mb csv. Pressed "cancel" while it was loading, and did not crash. 
![image](https://user-images.githubusercontent.com/22801047/30946803-ad9de30a-a3cb-11e7-8b26-6c2fc1e739f4.png)
Just got this window:
![image](https://user-images.githubusercontent.com/22801047/30946819-c06c0f7a-a3cb-11e7-9191-442aa954773e.png)

**Comment by lixun910** [comment]
Yes, this is what GeoDa supposed to do: shows a warning dialog and then allow user to open another datasource.

**Comment by jkoschinsky** [comment]
GeoDa 1.10.1.83 (OSX Yosemite, 10.10.5).

Loaded 200Mb csv, cancelled, no crash.
