### ISSUE TITLE
local G and G* cluster maps - no color for low

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1081]
Version 1.10.1.51 - local cluster map for G and G* does not show the low clusters as blue, but the same shade as not significant.

<img width="534" alt="screen shot 2017-09-09 at 8 30 19 am" src="https://user-images.githubusercontent.com/4008351/30241488-3481ac7c-9539-11e7-9404-609bb349b349.png">

**Comment by jkoschinsky** [comment]
Fix confirmed for GeoDa 1.10.1.55 -- Mac OSX

<img width="600" alt="screen shot 2017-09-11 at 6 54 05 am" src="https://user-images.githubusercontent.com/13679743/30273299-0baeaf12-96be-11e7-999a-7c8c346cd190.png">
