### ISSUE TITLE
Crash: Setting permutations to 99999 in local Geary map

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1082]
From: lanselin@gmail.com
 Details:
os: 1-10-12
vs: 1-10-1-51
/Users/luc/Desktop/GeoDa.1.10.1.51.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/luc/Desktop/guerry/Guerry_85.shp
Open Layer:Guerry_85
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/luc/Desktop/guerry/Guerry_85.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Crm_prs
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
In OnSpecifySeedDlg()
In OnRanOtherPer()
LisaScatterPlotFrame::OnRanOtherPer
9999
Open RandomizationDlg (univariate).
Close RandomizationDlg
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Crm_prp
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
In OnSpecifySeedDlg()
In OnRanOtherPer()
LisaScatterPlotFrame::OnRanOtherPer
9999
Open RandomizationDlg (univariate).
Close RandomizationDlg
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Litercy
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
In OnRanOtherPer()
LisaScatterPlotFrame::OnRanOtherPer
9999
Open RandomizationDlg (univariate).
Close RandomizationDlg
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Donatns
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
In OnRanOtherPer()
LisaScatterPlotFrame::OnRanOtherPer
9999
Open RandomizationDlg (univariate).
Close RandomizationDlg
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Infants
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
In OnRanOtherPer()
LisaScatterPlotFrame::OnRanOtherPer
9999
Open RandomizationDlg (univariate).
Close RandomizationDlg
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Suicids
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
In OnRanOtherPer()
LisaScatterPlotFrame::OnRanOtherPer
9999
Open RandomizationDlg (univariate).
Close RandomizationDlg
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Infants
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In OnSpecifySeedDlg()
In OnRanOtherPer()
9999
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In OnRanOtherPer()
99999
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In InferenceSettingsDlg::OnOkClick()
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Crm_prp
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In OnRanOtherPer()
99999
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In InferenceSettingsDlg::OnOkClick()
Open GetisOrdMapFrame (OnOpenGetisOrdStar).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Crm_prp
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
Entering GetisOrdMapFrame::GetisOrdMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Exiting GetisOrdMapFrame::GetisOrdMapFrame
In OnRanOtherPer()
99999
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In InferenceSettingsDlg::OnOkClick()
Open GetisOrdMapFrame (OnOpenGetisOrd).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Crm_prp
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
Entering GetisOrdMapFrame::GetisOrdMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Exiting GetisOrdMapFrame::GetisOrdMapFrame
Open GetisOrdMapFrame (OnOpenGetisOrdStar).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Crm_prp
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
Entering GetisOrdMapFrame::GetisOrdMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Exiting GetisOrdMapFrame::GetisOrdMapFrame
In GetisOrdMapFrame::~GetisOrdMapFrame
MapCanvas::~MapCanvas()
In OnRanOtherPer()
99999
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In InferenceSettingsDlg::OnOkClick()
Open LocalGearyFrame (OnOpenUniLocalGeary).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Crm_prp
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In OnRanOtherPer()
99999
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In InferenceSettingsDlg::OnOkClick()
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In InferenceSettingsDlg::OnOkClick()
Open LocalGearyFrame (OnOpenUniLocalGeary).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Litercy
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In OnRanOtherPer()
99999
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In InferenceSettingsDlg::OnOkClick()
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Litercy
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In OnRanOtherPer()
99999
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In InferenceSettingsDlg::OnOkClick()
Open GetisOrdMapFrame (OnOpenGetisOrdStar).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Litercy
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
Entering GetisOrdMapFrame::GetisOrdMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Exiting GetisOrdMapFrame::GetisOrdMapFrame
In OnRanOtherPer()
99999
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In InferenceSettingsDlg::OnOkClick()
Open GetisOrdMapFrame (OnOpenGetisOrd).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Litercy
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
VariableSettingsDlg::GetWeightsId() weight: Guerry_85_q
Entering GetisOrdMapFrame::GetisOrdMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Exiting GetisOrdMapFrame::GetisOrdMapFrame
In OnRanOtherPer()
99999
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In InferenceSettingsDlg::OnOkClick()
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In InferenceSettingsDlg::OnOkClick()
In OnRanOtherPer()
99999
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In InferenceSettingsDlg::OnOkClick()
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In InferenceSettingsDlg::OnOkClick()
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In InferenceSettingsDlg::OnOkClick()
Open LocalGearyFrame (OnOpenMultiLocalGeary).
Open MultiVariableSettingsDlg.
Click MultiVariableSettingsDlg::OnOK
Close MultiVariableSettingsDlg.
Open LocalGearyFrame (OnOpenMultiLocalGeary).
Open MultiVariableSettingsDlg.
Click MultiVariableSettingsDlg::OnOK
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In OnRanOtherPer()
99999
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In InferenceSettingsDlg::OnOkClick()
MapCanvas::~MapCanvas()
Open LocalGearyFrame (OnOpenMultiLocalGeary).
Open MultiVariableSettingsDlg.
Click MultiVariableSettingsDlg::OnOK
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In OnRanOtherPer()
99999
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In InferenceSettingsDlg::OnOkClick()
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In InferenceSettingsDlg::OnOkClick()
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
MapCanvas::~MapCanvas()
In GetisOrdMapFrame::~GetisOrdMapFrame
MapCanvas::~MapCanvas()
In GetisOrdMapFrame::~GetisOrdMapFrame
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
In GetisOrdMapFrame::~GetisOrdMapFrame
MapCanvas::~MapCanvas()
In GetisOrdMapFrame::~GetisOrdMapFrame
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/luc/Dropbox/z_Data/pedro_sp/municipio/data_anselin.shp
Open Layer:data_anselin
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/luc/Dropbox/z_Data/pedro_sp/municipio/data_anselin.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
In TableFrame::OnActivate
Open MergeTableDlg.
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/luc/Dropbox/z_Data/pedro_sp/municipio/data_anselin.csv
Open Layer:data_anselin
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
In TableFrame::OnActivate
Exiting ConnectDatasourceDlg::OnOkClick
ds:/Users/luc/Dropbox/z_Data/pedro_sp/municipio/data_anselin.csv layer: data_anselin
In TableFrame::OnActivate
Entering MergeTableDlg::OnIncAllClick()
In MergeTableDlg::OnMergeClick()
Open FieldNameCorrectionDlg:
ScrolledWidgetsPane::RemoveIllegalChars
municipality
municipality
ScrolledWidgetsPane::TruncateFieldName
municipality
munic_lity
ScrolledWidgetsPane::RenameDupFieldName
munic_lity
munic_lity
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
muni
In TableFrame::OnActivate
Exit FieldNameCorrectionDlg
In TableFrame::OnActivate
In TableFrame::OnActivate
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In MergeTableDlg::OnClose()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
MapCanvas::~MapCanvas()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
GdaFrame::OpenProject()
/Users/luc/Desktop/chicago_data/Chi-SDOH.gda
Entering Project::Project (existing project)
/Users/luc/Desktop/chicago_data/Chi-SDOH.gda
Project::SetProjectFullPath()
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/luc/Desktop/chicago_data/Chi-SDOH.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open project file:/Users/luc/Desktop/chicago_data/Chi-SDOH.gda
Entering GdaFrame::OnMapChoices
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
MapCanvas::~MapCanvas()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
GdaFrame::OpenProject()
/Users/luc/Desktop/norc/chicago_data/Chi-SDOH_2.gda
Entering Project::Project (existing project)
/Users/luc/Desktop/norc/chicago_data/Chi-SDOH_2.gda
Project::SetProjectFullPath()
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/luc/Desktop/norc/chicago_data/Chi-SDOH.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open project file:/Users/luc/Desktop/norc/chicago_data/Chi-SDOH_2.gda
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
In TableFrame::OnActivate
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
YPLL_rate
VariableSettingsDlg::GetWeightsId() weight: Chi-SDOH_q
VariableSettingsDlg::GetWeightsId() weight: Chi-SDOH_q
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In OnRanOtherPer()
99999
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In InferenceSettingsDlg::OnOkClick()
Open LocalGearyFrame (OnOpenUniLocalGeary).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
YPLL_rate
VariableSettingsDlg::GetWeightsId() weight: Chi-SDOH_q
VariableSettingsDlg::GetWeightsId() weight: Chi-SDOH_q
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In OnRanOtherPer()
99999
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In InferenceSettingsDlg::OnOkClick()
Open GetisOrdMapFrame (OnOpenGetisOrdStar).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
YPLL_rate
VariableSettingsDlg::GetWeightsId() weight: Chi-SDOH_q
VariableSettingsDlg::GetWeightsId() weight: Chi-SDOH_q
Entering GetisOrdMapFrame::GetisOrdMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Exiting GetisOrdMapFrame::GetisOrdMapFrame
In OnRanOtherPer()
99999
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In InferenceSettingsDlg::OnOkClick()
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In InferenceSettingsDlg::OnOkClick()
In OnSigFilter01()
In OnSigFilter01()
In OnSigFilter01()
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In InferenceSettingsDlg::OnOkClick()
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In InferenceSettingsDlg::OnOkClick()
In OnSigFilterSetup()
Open InferenceSettingsDlg.
In InferenceSettingsDlg::OnOkClick()
Open LocalGearyFrame (OnOpenUniLocalGeary).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
ForclRt
VariableSettingsDlg::GetWeightsId() weight: Chi-SDOH_q
VariableSettingsDlg::GetWeightsId() weight: Chi-SDOH_q
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In OnRanOtherPer()
99999

**Comment by lanselin** [comment]
Long story short. Crashed when setting number of permutations to 99999 in local Geary map, with lots of windows open (changing custom significance, etc.). Using 1.10.1.51. Chicago census tract layer with 791 observations.

**Comment by lixun910** [comment]
Got it. Seems like an old one. Will fix todays issues soon (am implementing
the date field type support).

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.73 (OSX Yosemite, 10.10.5).

Stress-tested it with 99999 perms for uni- and multi-variate Geary, which worked fine -- no more crash.
