### ISSUE TITLE
LOWESS smoother - bandwidth cannot be less than 0.01

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1087]
It appears that the bandwidth for the LOWESS smoother cannot be less than 0.01. This may be fine for small-medium sized data sets, but it is not for larger ones. For example, for 36,500 census blocks in Chicago, 0.01 is still 365 observations, hardly very "local". Can this be made more flexible?

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.73 (OSX Yosemite, 10.10.5).

<img width="495" alt="screen shot 2017-09-26 at 10 44 28 pm" src="https://user-images.githubusercontent.com/13679743/30894903-4b62ee16-a30c-11e7-9a80-67a8f9b76b46.png">
