### ISSUE TITLE
Crash Scientific Notation

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1093]
From: 
 Details:
os: 1-10-12
vs: 1-10-0-12
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/c00397205/Dropbox/W/[W] localism/ArcGIS/tl_2016_39_unsd/tl_2016_39_unsd.shp
Open Layer:tl_2016_39_unsd
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/c00397205/Dropbox/W/[W] localism/ArcGIS/tl_2016_39_unsd/tl_2016_39_unsd.shp
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
Open ExportDataDlg in its Init()
In ExportDataDlg::BrowseExportDataSource()
In ExportDataDlg::OnOkClick()
ds:/Users/c00397205/Desktop/sd.shp
Project::GetSpatialReference()
ScrolledWidgetsPane::IsFieldNameValid
STATEFP
ScrolledWidgetsPane::IsFieldNameValid
UNSDLEA
ScrolledWidgetsPane::IsFieldNameValid
GEOID
ScrolledWidgetsPane::IsFieldNameValid
NAME
ScrolledWidgetsPane::IsFieldNameValid
LSAD
ScrolledWidgetsPane::IsFieldNameValid
LOGRADE
ScrolledWidgetsPane::IsFieldNameValid
HIGRADE
ScrolledWidgetsPane::IsFieldNameValid
MTFCC
ScrolledWidgetsPane::IsFieldNameValid
SDTYP
ScrolledWidgetsPane::IsFieldNameValid
FUNCSTAT
ScrolledWidgetsPane::IsFieldNameValid
ALAND
ScrolledWidgetsPane::IsFieldNameValid
AWATER
ScrolledWidgetsPane::IsFieldNameValid
INTPTLAT
ScrolledWidgetsPane::IsFieldNameValid
INTPTLON
Exit FieldNameCorrectionDlg
In TableFrame::OnActivate
In TableFrame::OnActivate
MapCanvas::~MapCanvas()
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
GdaFrame::OpenProject()
/Users/c00397205/Dropbox/W/[W] localism/ArcGIS/localism.gda
Entering Project::Project (existing project)
/Users/c00397205/Dropbox/W/[W] localism/ArcGIS/localism.gda
Project::SetProjectFullPath()
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/c00397205/Dropbox/W/[W] localism/ArcGIS/sd.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
Open MergeTableDlg.
Entering MergeTableDlg::OnOpenClick()
In TableFrame::OnActivate
Entering MergeTableDlg::OnOpenClick()
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/c00397205/Dropbox/W/[W] localism/ArcGIS/sd_oep.csv
Open Layer:sd_oep
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
ds:/Users/c00397205/Dropbox/W/[W] localism/ArcGIS/sd_oep.csv layer: sd_oep
In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnKeyChoice()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
In MergeTableDlg::OnMergeClick()
In TableFrame::OnActivate
Click GdaFrame::OnSaveProject
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs
New Datasource Name:/Users/c00397205/Dropbox/W/[W] localism/ArcGIS/GdaTmp_sd.shp
Project::GetSpatialReference()
Project::GetGdaGeometries()
ScrolledWidgetsPane::IsFieldNameValid
STATEFP
ScrolledWidgetsPane::IsFieldNameValid
UNSDLEA
ScrolledWidgetsPane::IsFieldNameValid
GEOID
ScrolledWidgetsPane::IsFieldNameValid
NAME
ScrolledWidgetsPane::IsFieldNameValid
LSAD
ScrolledWidgetsPane::IsFieldNameValid
LOGRADE
ScrolledWidgetsPane::IsFieldNameValid
HIGRADE
ScrolledWidgetsPane::IsFieldNameValid
MTFCC
ScrolledWidgetsPane::IsFieldNameValid
SDTYP
ScrolledWidgetsPane::IsFieldNameValid
FUNCSTAT
ScrolledWidgetsPane::IsFieldNameValid
ALAND
ScrolledWidgetsPane::IsFieldNameValid
AWATER
ScrolledWidgetsPane::IsFieldNameValid
INTPTLAT
ScrolledWidgetsPane::IsFieldNameValid
INTPTLON
ScrolledWidgetsPane::IsFieldNameValid
oe_sd
ScrolledWidgetsPane::IsFieldNameValid
oe_irn
ScrolledWidgetsPane::IsFieldNameValid
oep
Exit FieldNameCorrectionDlg
Exiting Project::SaveDataSourceData
Entering Project::SaveProjectConf
In Project::UpdateProjectConf
Exiting Project::SaveProjectConf
In GdaFrame::OnOpenUniqueValues()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
oep
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnLegendUseScientificNotation
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnLegendUseScientificNotation
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
In TableFrame::OnActivate
Open DataViewerAddColDlg.
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
In DataViewerAddColDlg::OnChoiceType()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditLength()
Entering DataViewerAddColDlg::OnOkClick
Inserting new column OEP_NAME into Table
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
Open DataViewerDeleteColDlg.
In TableFrame::OnActivate
Open FieldNewCalcSheetDlg.
In FieldNewCalcSheetDlg::OnPageChange()
In FieldNewCalcSheetDlg::OnPageChange()
In FieldNewCalcSheetDlg::OnPageChange()
In FieldNewCalcSheetDlg::OnPageChange()
In FieldNewCalcSheetDlg::OnPageChange()
In FieldNewCalcSheetDlg::OnPageChange()
Open DataViewerDeleteColDlg.
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnDelete()
OEP_NAME
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In FieldNewCalcSheetDlg::OnPageChange()
Open DataViewerAddColDlg.
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
In DataViewerAddColDlg::OnChoiceType()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditLength()
Entering DataViewerAddColDlg::OnOkClick
Inserting new column OEP_NAME into Table
In TableFrame::OnActivate
In FieldNewCalcSheetDlg::OnPageChange()
In FieldNewCalcSheetDlg::OnPageChange()
In FieldNewCalcSheetDlg::OnPageChange()
In FieldNewCalcSheetDlg::OnPageChange()
In TableFrame::OnActivate
In TableFrame::OnActivate
In GdaFrame::OnOpenUniqueValues()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
oep
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnClearSelection
In TableFrame::OnActivate
In FieldNewCalcSheetDlg::OnPageChange()
In FieldNewCalcSheetDlg::OnPageChange()
In FieldNewCalcSheetDlg::OnPageChange()
In FieldNewCalcSheetDlg::OnPageChange()
In FieldNewCalcSheetDlg::OnPageChange()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnLabelLeftClickEvent()
Open DataViewerDeleteColDlg.
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnDelete()
OEP_NAME
In TableFrame::OnActivate
Click GdaFrame::OnLegendUseScientificNotation

**Comment by jkoschinsky** [comment]
When you right-click on the map legend to turn scientific notation on or off, nothing happens.

**Comment by lixun910** [comment]
Will be in version 81.

**Comment by YidanJ-Wu** [comment]
Windows 8 1.10.1.81 
Verified

**Comment by jkoschinsky** [comment]
For attached data, when you map award_amount with a Boxmap, by default scientific notation is used. When you right-click to turn this off, nothing happens.

[chicago_contracts_XY.csv.zip](https://github.com/GeoDaCenter/geoda/files/1343118/chicago_contracts_XY.csv.zip)

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.81ß (OSX Yosemite, 10.10.5).
