### ISSUE TITLE
labels are different between the map and the category editor (Natural Breaks)

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1097]

**Comment by lixun910** [comment]
As suggested by Luc: apply a fixed random seed (can be configured in Preference dialog), so all randomization starts at the same point, and lead to same natural breaks results.

**Comment by YidanJ-Wu** [comment]
Windows 1.10.1.77
To clarify, is this how it's supposed to look? 
![image](https://user-images.githubusercontent.com/22801047/30917485-befc5736-a361-11e7-8ec9-29619601bb63.png)

**Comment by jkoschinsky** [comment]
GeoDa 1.10.1.79 (OSX Yosemite, 10.10.5):

I don't see the option to set the random seed in the preferences dialog: Where is it?

<img width="725" alt="screen shot 2017-09-27 at 2 20 13 pm" src="https://user-images.githubusercontent.com/13679743/30933128-33d1d130-a38f-11e7-9443-a9db29738c02.png">

<img width="732" alt="screen shot 2017-09-27 at 2 20 28 pm" src="https://user-images.githubusercontent.com/13679743/30933122-30b8e88a-a38f-11e7-8ae6-f1c32dc41ffd.png">

**Comment by lixun910** [comment]
I just checked: This is missing, will add into preference dialog. Thanks!

**Comment by YidanJ-Wu** [comment]
Windows 8 1.10.1.81
I can see it in the preference dialog now, but it's cut off a bit and there is no option to enlarge the window or scroll down. 
![image](https://user-images.githubusercontent.com/22801047/30947086-4f425122-a3cd-11e7-91ba-cbc1a28ad76b.png)

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.83 (OSX Yosemite, 10.10.5).

verify in Win

**Comment by jkoschinsky** [comment]
GeoDa 1.10.1.83 (OSX Yosemite, 10.10.5).
SIDS data
Steps:
1. Open SIDS74 with natural breaks (6 categories)
2. Create  SIDS74 with natural breaks (6 categories)
--results are now identical except for one issue:

for observations on the border of a category, category assignment differs.
e.g. the selected value of 23 below is assigned to 13-23 in one case and 23-38 in the other.

<img width="1457" alt="screen shot 2017-09-29 at 12 53 57 pm" src="https://user-images.githubusercontent.com/13679743/31029074-f2bbaa58-a515-11e7-9c45-453df2859a40.png">


Can you implement the same assignment rule for the natural break map and category editor?

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.85 (OSX Yosemite, 10.10.5).

<img width="1203" alt="screen shot 2017-09-29 at 9 33 05 pm" src="https://user-images.githubusercontent.com/13679743/31041670-ed19232a-a55e-11e7-8c60-0429bfeab1df.png">
<img width="1210" alt="screen shot 2017-09-29 at 9 31 24 pm" src="https://user-images.githubusercontent.com/13679743/31041669-ed192dde-a55e-11e7-9237-d553269efbea.png">

**Comment by jkoschinsky** [comment]
confirm in Win since there was a crash related to this in Win

**Comment by YidanJ-Wu** [comment]
Windows 8 1.10.1.85
Created Natural Breaks map. Right click > Create New Custom then crashed.

**Comment by YidanJ-Wu** [comment]
Windows 8 1.10.1.85
Started with Themeless Map. Right click > Create New Custom 
![image](https://user-images.githubusercontent.com/22801047/31056200-8bd8ba2c-a693-11e7-9ff7-e56c6fe9c6ef.png)

Colors look fine, labels are incorrect. 
Closed custom map and opened Maps > Natural Breaks Map > 5

![image](https://user-images.githubusercontent.com/22801047/31056230-e80ad302-a693-11e7-9965-2fa5c4594f44.png)

**Comment by lixun910** [comment]
Thanks for finding this crash! 
Will fix it soon.

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12
Started with Themeless Map. Right click > Create New Custom
![image](https://user-images.githubusercontent.com/22801047/31134609-31f92c4e-a828-11e7-991d-687a0a43ed39.png)
The colors look identical to the map created by Maps > Natural Breaks > 5 (shown below) but the labels seem to be Quantile labels. 
![image](https://user-images.githubusercontent.com/22801047/31134667-6ba538ac-a828-11e7-9a99-bbc75454755d.png)

Right click > Change Current Map Type > Custom Map (schoolcnt) to display the custom map created earlier, this time with correct labels.
![image](https://user-images.githubusercontent.com/22801047/31134720-954ec5e2-a828-11e7-86e2-ffa0d48ba866.png)

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12 
Right Click > Create New Custom no longer crashes.

**Comment by lixun910** [comment]
Got it. Thanks! Will fix this.

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12
Map > Natural Break Map for hoval variable
From the open window, Change Current Map Type > Create New Custom
In the Category Editor that opens, I change the associated variable from hoval to area. However the label still says hoval. 
![image](https://user-images.githubusercontent.com/22801047/31135489-c1b8344a-a82a-11e7-99fa-8ce7a7230660.png)
Change associated variable to x. Label still says hoval. 
![image](https://user-images.githubusercontent.com/22801047/31135544-ed87eea8-a82a-11e7-84a9-32942759037d.png)

**Comment by lixun910** [comment]
Thanks, Julie! 

You got a good one, which impacts all related maps/plots if use “custom breaks” eg PCP-> create new custom etc.

**Comment by lixun910** [comment]
@YidanJ-Wu  This is correct, since the "custom breaks" only defines the intervals of the breaks. The choropleth map specify which variable (e.g. hoval) used in current map, so the label (e.g. hoval) won't change. But you can change the name of the "custom breaks" (say you change it to "my breaks (area)", and you will see it changed in the choropleth map using this "custom breaks":

<img width="507" alt="screen shot 2019-01-15 at 9 57 33 pm" src="https://user-images.githubusercontent.com/2423887/51227234-97e43f80-1910-11e9-8544-627f300ac80a.png">
