### ISSUE TITLE
Table: delete variables has incomplete variables list

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1099]
The list of variables available for deletion does not seem to be complete. For example, this is what is offered by the delete variables dialog:

<img width="322" alt="screen shot 2017-09-18 at 3 18 40 pm" src="https://user-images.githubusercontent.com/4008351/30560216-2dcc5fdc-9c85-11e7-8d55-56f34d0d552e.png">

But this is the full list of variables.

<img width="163" alt="screen shot 2017-09-18 at 3 19 45 pm" src="https://user-images.githubusercontent.com/4008351/30560230-3c775104-9c85-11e7-90e6-d909cda56b26.png">

For example, the variables SSA and Location after Comm  are not available for deletion.
The full list of variables not available seems to include all the string variables (as well as a date variable). Are these somehow overlooked in the listing?

(version 1.10.1.61)

**Comment by YidanJ-Wu** [comment]
Windows 8 1.10.1.75 
Verified

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.79 (OSX Yosemite, 10.10.5).
