### ISSUE TITLE
Table Aggregation issues

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1101]
There are several issues with the Table Aggregation feature:

- the Aggregation functionality only works from the menu Table > Aggregation, but it does not work from the option menu in the table: right click and selecting Aggregation does nothing.

- the aggregation operation does not work when no variables are specified, this precludes a simple count -- I suggest to add "Count" to the options to just compute "AGG_COUNT", so when Count is selected, no additional variables need to be specified.

- I verified the count aggregation using "Sum" on a value of 1 and the totals are the same.

**Comment by YidanJ-Wu** [comment]
Windows 8 1.10.1.75 
Verified

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.79 (OSX Yosemite, 10.10.5).

Question:
Selection of multiple variables in the merge and aggregate dialogs does not work. Is this easy to add?

**Comment by lixun910** [comment]
It’s easy to do. But, there are many similar controls that can be updated with multiple selection (as well as related code), so the best way to do is to create one control with multiple selection and replaced all current single selection control. I would leave it for next release, since we have >> and << for select/deselect all and it’s not a bug or blocking issue.

**Comment by jkoschinsky** [comment]
sounds good!

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
Verified 

<img width="321" alt="14 mar 05" src="https://user-images.githubusercontent.com/36253697/37435823-d949c7c2-27dc-11e8-89e9-aba53815d19f.PNG">
<img width="329" alt="14 mar 06" src="https://user-images.githubusercontent.com/36253697/37435824-d96a6cc0-27dc-11e8-8e43-b5c093d85437.PNG">

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v113
OSX
