### ISSUE TITLE
Crash: Loading csv after columns were deleted

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1103]
From: lanselin@gmail.com
 Details:
os: 1-10-12
vs: 1-10-1-63
/Users/luc/Desktop/GeoDa.1.10.1.63.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
Open CsvFieldConfDlg.
CsvFieldConfDlg::PrereadCSV()
CsvFieldConfDlg::UpdateFieldGrid()
CsvFieldConfDlg::ReadCSVT()
CsvFieldConfDlg::UpdatePreviewGrid()
CsvFieldConfDlg::UpdateXYcombox()
CsvFieldConfDlg::OnHeaderCmbClick()
CsvFieldConfDlg::PrereadCSV()
CsvFieldConfDlg::UpdateFieldGrid()
CsvFieldConfDlg::UpdatePreviewGrid()
CsvFieldConfDlg::UpdateXYcombox()
CsvFieldConfDlg::OnOkClick()
CsvFieldConfDlg::WriteCSVT()
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/luc/Dropbox/z_Data/mary/disease.csv
Open Layer:disease
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/luc/Dropbox/z_Data/mary/disease.csv
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
In TableFrame::OnActivate
Open DataViewerDeleteColDlg.
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnDelete()
field_2
field_1
In TableFrame::OnActivate
Open ExportDataDlg in its Init()
In ExportDataDlg::BrowseExportDataSource()
In ExportDataDlg::OnOkClick()
ds:/Users/luc/Dropbox/z_Data/mary/test1.dbf
Project::GetSpatialReference()
ScrolledWidgetsPane::IsFieldNameValid
DOB
ScrolledWidgetsPane::IsFieldNameValid
Address
ScrolledWidgetsPane::IsFieldNameValid
ZIP
ScrolledWidgetsPane::IsFieldNameValid
Sex
ScrolledWidgetsPane::IsFieldNameValid
Location
ScrolledWidgetsPane::IsFieldNameValid
Race
ScrolledWidgetsPane::IsFieldNameValid
Ethnicity
ScrolledWidgetsPane::IsFieldNameValid
EthnicityCoded
ScrolledWidgetsPane::IsFieldNameValid
InsuranceType
ScrolledWidgetsPane::IsFieldNameValid
Visits
ScrolledWidgetsPane::IsFieldNameValid
Diabetes
ScrolledWidgetsPane::IsFieldNameValid
Asthma
ScrolledWidgetsPane::IsFieldNameValid
Obesity
ScrolledWidgetsPane::IsFieldNameValid
Hypertension
ScrolledWidgetsPane::IsFieldNameValid
Substance Abuse
ScrolledWidgetsPane::IsFieldNameValid
Depression
ScrolledWidgetsPane::IsFieldNameValid
Anxiety
ScrolledWidgetsPane::IsFieldNameValid
Lead levels
ScrolledWidgetsPane::RemoveIllegalChars
EthnicityCoded
EthnicityCoded
ScrolledWidgetsPane::TruncateFieldName
EthnicityCoded
Ethni_oded
ScrolledWidgetsPane::RenameDupFieldName
Ethni_oded
Ethni_oded
ScrolledWidgetsPane::RemoveIllegalChars
InsuranceType
InsuranceType
ScrolledWidgetsPane::TruncateFieldName
InsuranceType
Insur_Type
ScrolledWidgetsPane::RenameDupFieldName
Insur_Type
Insur_Type
ScrolledWidgetsPane::RemoveIllegalChars
Hypertension
Hypertension
ScrolledWidgetsPane::TruncateFieldName
Hypertension
Hyper_sion
ScrolledWidgetsPane::RenameDupFieldName
Hyper_sion
Hyper_sion
ScrolledWidgetsPane::RemoveIllegalChars
Substance Abuse
SubstanceAbuse
ScrolledWidgetsPane::TruncateFieldName
SubstanceAbuse
Subst_buse
ScrolledWidgetsPane::RenameDupFieldName
Subst_buse
Subst_buse
ScrolledWidgetsPane::RemoveIllegalChars
Lead levels
Leadlevels
ScrolledWidgetsPane::TruncateFieldName
Leadlevels
ScrolledWidgetsPane::RenameDupFieldName
Leadlevels
Leadlevels
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
Ethni_oded
ScrolledWidgetsPane::IsFieldNameValid
Insur_Type
ScrolledWidgetsPane::IsFieldNameValid
Hyper_sion
ScrolledWidgetsPane::IsFieldNameValid
Subst_buse
ScrolledWidgetsPane::IsFieldNameValid
Leadlevels
Exit FieldNameCorrectionDlg
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/luc/Dropbox/z_Data/mary/test1.dbf
Open Layer:test1
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/luc/Dropbox/z_Data/mary/test1.dbf
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
In TableFrame::OnActivate
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
Open CsvFieldConfDlg.
CsvFieldConfDlg::PrereadCSV()
CsvFieldConfDlg::UpdateFieldGrid()
CsvFieldConfDlg::ReadCSVT()
CsvFieldConfDlg::UpdatePreviewGrid()

**Comment by lanselin** [comment]
crash occurs when loading csv file that was created by GeoDa after deleting some columns from the original csv file and then save as csv.

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.79 (OSX Yosemite, 10.10.5).

**Comment by YidanJ-Wu** [comment]
Windows 8 1.10.1.81
I deleted a column from a .csv and did "Save As" another csv with different name. Didn't crash but got this error message. 
![image](https://user-images.githubusercontent.com/22801047/30946954-8d24a266-a3cc-11e7-9cd6-79e03da48f29.png)

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.83 (OSX Yosemite, 10.10.5).

verify in Windows

**Comment by YidanJ-Wu** [comment]
Windows 8 1.10.1.85 
Verified

**Comment by lixun910** [comment]
Verified on Mac and Ubuntu using GeoDa 1.14
