### ISSUE TITLE
Table merge: data source does not appear in input file box

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1104]
When selecting a file to merge with a current data set, the file name does not appear in the dialog, it remains a white box, even after the variables have been loaded. See below.

<img width="489" alt="screen shot 2017-09-19 at 4 16 56 pm" src="https://user-images.githubusercontent.com/4008351/30614595-08e82c5c-9d5a-11e7-890e-6621827e3562.png">

Version 1.10.1.63 (the fixed one)

**Comment by YidanJ-Wu** [comment]
Windows 8 1.10.1.75
Verified

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.77 (OSX Yosemite, 10.10.5).
