### ISSUE TITLE
Point map - selected not shown when changing base map transparency

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1107]
There seems to be some strange interaction between changing the map transparency when a base map is used and the differentiated transparency between selected and unselected points.

Here's the use case. First a standard point map, with points selected.

<img width="845" alt="screen shot 2017-09-20 at 5 13 41 pm" src="https://user-images.githubusercontent.com/4008351/30670396-b9c4e4a2-9e27-11e7-8848-98f487bca4fb.png">

Then, add basemap (Nokia day). You can still see the selection.

<img width="752" alt="screen shot 2017-09-20 at 5 14 00 pm" src="https://user-images.githubusercontent.com/4008351/30670403-c4400484-9e27-11e7-9ecf-25170f21cc9a.png">

Then after changing transparency, you can no longer see the selection.

<img width="450" alt="screen shot 2017-09-20 at 5 14 39 pm" src="https://user-images.githubusercontent.com/4008351/30670415-d028e7fc-9e27-11e7-86db-93bb9a42f971.png">

(version 1.10.1.65)

**Comment by jkoschinsky** [comment]
also, how about we use smaller circles with filled color so it's easier to
differentiate the points against the basemap and vs. unselected? They're
hard to see right now.

**Comment by lanselin** [comment]
This is an old issue or desired feature somewhere: make the points solid in the green base map.
Same for choropleth maps for points. It is almost impossible to see the points as circles.
But I seem to remember there is a performance issue behind this.

**Comment by lixun910** [comment]
The performance issue is for “real” transparency support. In current solution, we can fill the points with colors, but we can’t see some effects like: dense points area has darker color.

**Comment by lixun910** [comment]
I just checked: when you change the map transparency, it is actually changing the transparency of unselected points. So, when unselected points are getting less transparency, they will be looking close to highlighted points. That's why you can't see the selection.  One solution is checking the "Use classic yellow-hatching to highlight selection in map" box in Preference dialog. By doing this, you will see the selected points are colored with red.

**Comment by YidanJ-Wu** [comment]
Windows 1.10.1.77
Confirmed

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.73 (OSX Yosemite, 10.10.5).

<img width="760" alt="screen shot 2017-09-26 at 10 47 22 pm" src="https://user-images.githubusercontent.com/13679743/30894963-b338bc50-a30c-11e7-9f94-37eee7060540.png">
