### ISSUE TITLE
Tools-Shape-Points from Table function in version 10.0.8

### ISSUE THREAD

**Issue by jl-scott** [GeoDaCenter/geoda#1110]
Hi! The points from table function of my GeoDa is not working. The option is greyed out and not possible to click on. I have the new version of GeoDa, 10. I want to create Thiessen polygons from a point file and cannot. How do I fix this?

Thank you!

**Comment by lixun910** [comment]
@jl-scott  Thanks for reporting this! In GeoDa version <= 1.10.0.12, the "points from table" menu will be enabled only when you load a Table dataset (e.g. csv, excel etc.). 

We've fixed this in our latest internal versions, you can try: 
Mac 107+: https://www.dropbox.com/s/br2jo627bmkyph6/GeoDa1.10.1.73-Installer.dmg?dl=0
Win 64: https://www.dropbox.com/s/rpab1lx6snft84w/GeoDa-1.10.1.73-Windows-64bit.exe?dl=0
Ubuntu 64: https://www.dropbox.com/s/mbd7sazryfwvvis/GeoDa-1.10.1.73-Ubuntu16.04-64bit.deb?dl=0

**Comment by jl-scott** [comment]
Thank you again for this response. I downloaded it to my laptop as I was travelling but came back home and tried to download the update to my office mac and I think the link is disabled. Is there anyway to get a new link?

Thank you!

---
Jen Scott, PhD, MS, MIA, LMSW
Assistant Professor
School of Social Work
College of Human Sciences & Education
Louisiana State University

office: (225) 578-0433 | email: jenscott@lsu.edu<mailto:jenscott@lsu.edu>

"If you have come here to help me, you are wasting your time. But if you have come because your liberation is bound up with mine, then let us work together."
-Lilla Watson

**Comment by lixun910** [comment]
Please download GeoDa 1.12 at http://geodacenter.github.io/. Thanks!

**Comment by jl-scott** [comment]
Hello,


I have downloaded GeoDa 1.12 but I am still finding the same issue - I am not able to open the Points from Table function. Is there another solution?


Thank you!

Jen


---
Jen Scott, PhD, MS, MIA, LMSW
Assistant Professor
School of Social Work
College of Human Sciences & Education
Louisiana State University


"If you have come here to help me, you are wasting your time. But if you have come because your liberation is bound up with mine, then let us work together."
-Lilla Watson


________________________________
