### ISSUE TITLE
Add map view title for local cluster stats

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1111]
For later:

When you create a map based on local clusters for REDCAP, k-means, hierarchical clusters, or Spectral Clustering, the map view header just says "Map" instead of the local cluster type (as it does for PCA). When you run different types, you end up with lots of "map" views without being able to trace what cluster statistic they represent. Add REDCAP, k-means or Spectral Clustering to the header so people know what the map shows. Later it would also be good to save the local cluster settings in the project file so you have a record of what choices you specified.

<img width="1258" alt="screen shot 2017-09-25 at 8 59 03 pm" src="https://user-images.githubusercontent.com/13679743/30838988-83381ef2-a234-11e7-990a-43d7752618fd.png">

**Comment by lixun910** [comment]
same with #1279
