### ISSUE TITLE
Averages chart: Problem with huge p-values

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1114]
Something isn't right with these p-values:
Will send you the data.

<img width="1492" alt="screen shot 2017-09-25 at 8 46 08 pm" src="https://user-images.githubusercontent.com/13679743/30843249-7833cef2-a24d-11e7-8212-c7b5af1d0afa.png">

**Comment by lixun910** [comment]
From the attached screenshot, it's comparing two exactly same dataset: selected 1990 vs selected 1990. I think that's why the results are weird.
This looks like a selection restriction issue -- GeoDa shouldn't allow user to make such a combination.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
Verified 

<img width="599" alt="14 mar 04" src="https://user-images.githubusercontent.com/36253697/37434435-79aeb750-27d7-11e8-83d2-17385c4fb7e0.PNG">

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v113
OSX
