### ISSUE TITLE
Dependency Issue on Ubuntu 16.04. Is a hard dependency on libcurl4-gnutls-dev required? 

### ISSUE THREAD

**Issue by papamoose** [GeoDaCenter/geoda#1115]
Given the Ubuntu 16.04 debian package provided here:  http://geodacenter.github.io/download_linux.html

You make a choice to depend on 'libcurl4-gnutls-dev'. 

```
# apt-cache show geoda | grep Depends
Depends: zlib1g, libexpat1, freeglut3, libreadline6, libcurl4-gnutls-dev, libgtk-3-0, libc-dev-bin, libssl1.0.0, libwebkitgtk-1.0-0
```

'libcurl4-gnutls-dev' and 'libcurl4-openssl-dev' conflict and should not be used interchangeably. 

```
# apt-cache show libcurl4-gnutls-dev | grep Conflicts | uniq
Conflicts: libcurl4-nss-dev, libcurl4-openssl-dev
```

```
# apt-cache show libcurl4-openssl-dev | grep Conflicts |  uniq
Conflicts: libcurl4-gnutls-dev, libcurl4-nss-dev
```

The preferred package to use for most other packages will be 'libcurl4-openssl-dev'.

1) Does the debian package need to depend on 'libcurl4-gnutls-dev'? If yes, is there a possibility to switch the dependency to 'libcurl-openssl-dev'?
2) Does the package really depend on the development files? Maybe this dependency can be removed?

For reference this is the specific issue I am dealing with now. I'm sure there will be others.
```
# apt-get install geoda
(Reading database ... 1297689 files and directories currently installed.)
Removing r-cran-tidyverse (1.1.1-1cran1ppa0trusty0) ...
Removing r-cran-rvest (0.3.2-1cran1ppa0trusty0) ...
Removing r-cran-httr (1.3.1-1cran1ppa0trusty0) ...
Removing r-cran-curl (2.8.1-1cran1ppa0trusty0) ...
Removing libcurl4-openssl-dev:amd64 (7.35.0-1ubuntu2.10) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Selecting previously unselected package libcurl4-gnutls-dev:amd64.
(Reading database ... 1297503 files and directories currently installed.)
Preparing to unpack .../libcurl4-gnutls-dev_7.35.0-1ubuntu2.10_amd64.deb ...
Unpacking libcurl4-gnutls-dev:amd64 (7.35.0-1ubuntu2.10) ...
Selecting previously unselected package geoda.
Preparing to unpack .../geoda_1.10-1ubuntu1~14.04_amd64.deb ...
Unpacking geoda (1.10-1ubuntu1~14.04) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.13-1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu1.1) ...
Processing triggers for bamfdaemon (0.5.1+14.04.20140409-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
Setting up libcurl4-gnutls-dev:amd64 (7.35.0-1ubuntu2.10) ...
Setting up geoda (1.10-1ubuntu1~14.04) ...
```
Notice how apt first removes a bunch of packages which 'depend' on libcurl4-openssl-dev'.

```
# apt-cache show r-cran-curl | grep Depends
Depends: libcurl4-openssl-dev, r-base-core, libc6 (>= 2.14), libcurl3 (>= 7.28.0)
```

**Comment by lixun910** [comment]
Thanks Phil!

Does the debian package need to depend on 'libcurl4-gnutls-dev'? If yes, is there a possibility to switch the dependency to 'libcurl-openssl-dev’
Does the package really depend on the development files? Maybe this dependency can be removed?
yes, GeoDa uses libcurl in basemap, Carto, geocoding features. I think there might be a historical issue leading to use libcurl4-gnutls-dev. But I do believe GeoDa can switch to ‘libcurl-openssl-dev’. I will check on that.

We are generating new GeoDa builds (v 1.12), will keep you updated. 

Xun

**Comment by papamoose** [comment]
Not to stop you from getting those new 1.12 build done... but is it possible 'libcurl4-gnutls-dev' is only a build dependency?

**Comment by lixun910** [comment]
@papamoose  I just changed the GeoDa build to use libcurl compiled by ourself (a libcurl.so will be shipped with GeoDa). So you will have no conflicting issue of libcurl. Let me know if this version works:
https://www.dropbox.com/s/9raz2b80yg78fp7/GeoDa-1.10.1.77-Ubuntu16.04-64bit.deb?dl=0

apt-cache show geoda | grep Depends
Depends: zlib1g, libexpat1, freeglut3, libreadline6, libgtk-3-0, libc-dev-bin, libssl1.0.0, libwebkitgtk-1.0-0

**Comment by papamoose** [comment]
Thanks for the effort you are putting into this. It is much appreciated.

Here are my notes after installing your deb package:

```
kauffman@hester2:~$ /usr/local/geoda/GeoDa
/usr/local/geoda/GeoDa: error while loading shared libraries: libgdal.so.20: cannot open shared object file: No such file or directory
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "canberra-gtk-module"
ERROR 4: sqlite3_open(/usr/local/geoda/cache.sqlite) failed: unable to open database file
```

No problem. Just install the dependencies it needs.
```
apt-get install libgdal20 overlay-scrollbar overlay-scrollbar-gtk2 libcanberra-gtk-module
```

```
$ /usr/bin/run_geoda.sh
chmod: cannot access '/usr/local/geoda/plugins/*.so': No such file or directory
chmod: changing permissions of '/usr/local/geoda/GeoDa': Operation not permitted
ERROR 4: sqlite3_open(/usr/local/geoda/cache.sqlite) failed: unable to open database file
```
Interesting. What happens when multiple users launch GeoDa on the same computer?
Also, the 'chmod +x' in /usr/bin/run_geoda.sh is concerning. What happens if $USER (who launched the application) does not have rights to modify /usr/local/geoda? We should probably trust that the package specified the proper permissions.


Ok fine. What changed?
```
root@hester2:/local# mkdir og new
root@hester2:/local# dpkg-deb -R GeoDa-1.10-Ubuntu-16.04-64bit.deb og/
root@hester2:/local# dpkg-deb -R GeoDa-1.10.1.77-Ubuntu16.04-64bit.deb new/
root@hester2:/local# diff og/usr/local/geoda new/usr/local/geoda
root@hester2:/local# diff -c og/usr/local/geoda new/usr/local/geoda | grep -v "Common subdirectories"
Only in og/usr/local/geoda: cache.sqlite
Binary files og/usr/local/geoda/GeoDa and new/usr/local/geoda/GeoDa differ
Only in og/usr/local/geoda: geoda_prefs.json
Only in og/usr/local/geoda: geoda_prefs.sqlite
```
Copying cache.sqlite from the previous deb into /usr/local/geoda allowed the program to successfully run.

**Comment by lixun910** [comment]
Basically, if you have any permission concerning, you don’t need to install GeoDa from deb installer. 

You can copy the directory /usr/local/geoda to a safe location, then run it using run.sh

GeoDa depends on its own libgdal library, so libgal apt-get will crash GeoDa in some functions. 

Other requires libraries:
zlib1g, libexpat1, freeglut3, libreadline6, libgtk-3-0, libc-dev-bin, libssl1.0.0, libwebkitgtk-1.0-0

**Comment by papamoose** [comment]
> Basically, if you have any permission concerning, you don’t need to install GeoDa from deb installer.
> You can copy the directory /usr/local/geoda to a safe location, then run it using run.sh

I'm not super concerned. Those commands will just fail if you install from a deb and use the /usr/share/applications/Geoda.desktop to start the application. That may or may not be what you intended, which is why I brought it up.

> GeoDa depends on its own libgdal library, so libgal apt-get will crash GeoDa in some functions.

Good to know.

Should I rebuild the deb with 'geoda_prefs.*' and 'cache.sqlite' included in the deb package this time?
Can I copy those files from the vanilla 1.10 install? Or are you building a new one now?

**Comment by lixun910** [comment]
I am building a new one now, so will address the file issues. Thanks!

If multiple user launches GeoDa on one machine, the GeoDa configurations might be messed up (if all users save their GeoDa preferences), as well as some potential crash when all load basemap in GeoDa. This issues has been on our list https://github.com/GeoDaCenter/geoda/issues/623 <https://github.com/GeoDaCenter/geoda/issues/623>, we might fix it in next major release.

**Comment by lixun910** [comment]
@papamoose 

Here is a new deb file with cache.sqlite and geoda_prefs.*: https://www.dropbox.com/s/8yn1ijx9917yup9/GeoDa-1.10.1.79-Ubuntu-64bit.deb?dl=0

Also, I created a tar ball: https://www.dropbox.com/s/faw1zy8hhbmdngs/geoda_1.10.1.79.tar.gz?dl=0 So, one can run GeoDa using script run.sh after extracting the geoda directory to a safe location.  (note: one needs to make sure the dependent libraries are installed: zlib1g, libexpat1, freeglut3, libreadline6, libgtk-3-0, libc-dev-bin, libssl1.0.0, libwebkitgtk-1.0-0)

Let me know any issues. Thanks!

**Comment by papamoose** [comment]
This one is looking good. I can launch GeoDa and use the menus. (I have no idea if it actually works since I am not a user).

Obviously, issue #623 still remains.
```
$ run_geoda.sh 
Warning 4: Failed to open /usr/local/geoda/cache.sqlite, Permission denied.
ERROR 1: In ExecuteSQL(): sqlite3_step(UPDATE history SET param_val='false' WHERE param_key='NoCrash'):
  SQL logic error or missing database

os: 3-4-4
vs: 1-10-1-79
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
```

Ok, I'll close my eyes, forget everything I know, and tentatively change the permissions on `cache.sqlite` to `0777`. 

```
$ run_geoda.sh 
ERROR 1: In ExecuteSQL(): sqlite3_step(UPDATE history SET param_val='false' WHERE param_key='NoCrash'):
  SQL logic error or missing database

os: 3-4-4
vs: 1-10-1-79
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
```
No permission issue displayed this time, but I believe it still has to do with permissions.

```
$ ls -l /usr/local/geoda/cache.sqlite 
-rwxrwxrwx 1 root root 5120 Sep 27 10:05 /usr/local/geoda/cache.sqlite

$ sqlite3 /usr/local/geoda/cache.sqlite 
SQLite version 3.11.0 2016-02-15 17:29:24
Enter ".help" for usage hints.
sqlite> UPDATE history SET param_val='false' WHERE param_key='NoCrash';
Error: unable to open database file
```
Is GeoDa able to function without the `cache.sqlite` file?

**Comment by lixun910** [comment]
Thanks, @papamoose ! GeoDa does run without the cache.sqlite file, but then users can't save their preferences/settings in GeoDa. 

Yes, you are right. Another permission issue is the directory basemap_cache/, where the basemap tiles (png files) will be downloaded and saved.

**Comment by papamoose** [comment]
I hesitate to set `o+w` on `/usr/local/geoda`.
Are these permissions required? What is the impact if they are not set?

**Comment by lixun910** [comment]
I don’t think it will impact GeoDa running, since that is for auto-upgrade feature.

**Comment by lixun910** [comment]
original issue has been solved. The last question is the same as: cache.sqlite located in room directory #623. Close this issue and keep #623.
