### ISSUE TITLE
add URL to geocoding

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1116]
add this URL to Geocoding Places API button:
https://developers.google.com/places/web-service/get-api-key

<img width="612" alt="screen shot 2017-09-26 at 1 41 34 pm" src="https://user-images.githubusercontent.com/13679743/30877822-7d7f2d5c-a2c0-11e7-8bf4-8b6795b0a916.png">

**Comment by lixun910** [comment]
<img width="438" alt="screen shot 2017-09-26 at 11 57 05 am" src="https://user-images.githubusercontent.com/2423887/30878585-e8db9ae0-a2b1-11e7-90b1-1870b010e146.png">
