### ISSUE TITLE
Table field text

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1117]
Right now this is the text you get when you save a csv as a spatial file with field names that need to be updated (e.g. in the vehicles data for Luc's class):

<img width="719" alt="screen shot 2017-09-26 at 1 47 19 pm" src="https://user-images.githubusercontent.com/13679743/30878038-453c158a-a2c1-11e7-94e7-9dbe477dafdf.png">

I would suggest the following language instead:
View header: Field Name Correction --> Update Field Name
Field name --> Current field name
Suggest field name --> Suggested field name to match new table format

delete: (Field name is not valid)

**Comment by jkoschinsky** [comment]
Merged with https://github.com/GeoDaCenter/geoda/issues/1031.

**Comment by jkoschinsky** [comment]
Suggested field name to match new table format --> Suggested field name
() --> (name exceeds 10 chars)

- make the entry box exactly 10 characters, so that one cannot enter a longer variable name

![image](https://user-images.githubusercontent.com/13679743/30983919-77040b5e-a451-11e7-8ba6-86f0659040bc.png)

**Comment by luluzhou766** [comment]
Win 10, 64bit
Geoda 1.12.1.131

When I created a csv file, I did not meet any warning to update the names. And created a csv with the original names. 

When I saved selections as dbf file, I got this update field name window.  
It still showed "Field name is not valid", not " (name exceeds 10 chars)"

![01](https://user-images.githubusercontent.com/36253697/39611354-9b2422ce-4f89-11e8-828d-b8425af1d761.PNG)

**Comment by lixun910** [comment]
Yes, this works as designed.

 I talked with Julia that, in Update Field Name dialog, GeoDa only shows one of the two warning messages: “Field name is not valid” or “Field name is duplicated”. 
The reason for not showing details is that for different file formats, the field name restrictions are different: 

e.g. field name in csv has no length limit (cannot contains comma etc.), but in standard dbf file, the field name should not exceeds 10 chars.

so we use a generic message here.
