### ISSUE TITLE
Aggregate text

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1118]
To differentiate merging from aggregating, should we rename the Merge button below to Aggregate?

<img width="493" alt="screen shot 2017-09-26 at 3 06 19 pm" src="https://user-images.githubusercontent.com/13679743/30881755-7a087e42-a2cc-11e7-8382-07c8d570c370.png">

**Comment by lanselin** [comment]
Agreed. I missed that one.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
Verified 

<img width="329" alt="14 mar 03" src="https://user-images.githubusercontent.com/36253697/37430862-67c22dda-27cb-11e8-9ab1-03cd5504c734.PNG">

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v113
OSX
