### ISSUE TITLE
Histogram - Choose intervals no longer available

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1119]
The Choose intervals option in the histogram is no longer available, it is greyed out. The only available option is the custom intervals.

Also, the order of these options should be reversed: choose intervals is much more common than custom intervals.

<img width="236" alt="screen shot 2017-09-26 at 8 52 45 pm" src="https://user-images.githubusercontent.com/4008351/30892229-14305488-a2fd-11e7-90fe-a30171bd1c31.png">

**Comment by lanselin** [comment]
Using build 75

**Comment by lanselin** [comment]
works in 1.10.0.12, but not in 1.20.1.31

**Comment by YidanJ-Wu** [comment]
Windows 1.10.1.81 
Verified
![image](https://user-images.githubusercontent.com/22801047/30945860-362332ee-a3c6-11e7-8d93-4ed1f4da736e.png)

**Comment by jkoschinsky** [comment]
Choose interval option no longer greyed out:
Fix verified in GeoDa 1.10.1.81ß (OSX Yosemite, 10.10.5).

However, choose intervals is still below histogram classification but should be above.

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.83 (OSX Yosemite, 10.10.5).
