### ISSUE TITLE
Crash Basemap: Try Replicating

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1120]
From: 
 Details:
os: 1-10-12
vs: 1-10-0-12
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:

Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnCreateNewIdClick
Try to insert unique id (integer, POLY_ID) column in table.
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnCRadioKnnSelected
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Click CreatingWeightDlg::OnCreateClick
In WeightsManFrame::OnActivate

In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnActivate
Close CreatingWeightDlg
In WeightsManFrame::OnActivate
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
In WeightsManFrame::OnActivate
Click VariableSettingsDlg::OnOkClick:
new

In WeightsManFrame::OnActivate

In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In MapFrame::OnMapBasemap()
Click GdaFrame::OnSetBasemap8

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12
I tried the functions in this crash report (weights, create new ID variable, LISA), changed basemaps several times. Have not been able to replicate crash.

**Comment by lixun910** [comment]
Can't replicate this crash. 
Basemap feature in GeoDa has many updates since v1.10. Will close this issue since this is only basemap related crash and it is from old 1.10 version.
