### ISSUE TITLE
Crash Averages Chart: Try Replicating

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1121]
From: 
 Details:
os: 3-4-10
vs: 1-10-0-8
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/media/caillaul/DATA/Enseignements/2017-18/PPST/S_Physiq/TD_Reunion/fire_archive_M6_17905.shp
Open Layer:fire_archive_M6_17905
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/media/caillaul/DATA/Enseignements/2017-18/PPST/S_Physiq/TD_Reunion/fire_archive_M6_17905.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
Open DataViewerEditFieldPropertiesDlg
In TableFrame::OnActivate
In TableFrame::OnActivate
Open DataMovieDlg.
Entering DataMovieDlg::OnFieldChoice
Close DataMovieDlg::OnClose
In TableFrame::OnActivate
In TableFrame::OnActivate
Open TimeChooserDlg.
Open VarGroupingEditorDlg.
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnCreateGrpClick
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnClose
Open VarGroupingEditorDlg.
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnClose
Close TimeChooserDlg::OnClose
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
Entering GdaFrame::OnMapChoices
In GdaFrame::OpenQuantile(6)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
FRP
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Entering GdaFrame::OnMapChoices
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
Open DataViewerEditFieldPropertiesDlg
In DataViewerEditFieldPropertiesDlg::OnGridComboBox
0
Entering DataViewerEditFieldPropertiesDlg::OnFieldSelected
Entering DataViewerEditFieldPropertiesDlg::OnCellChanging
changing row 5, col 1 from date to real
Open LineChartFrame(Average Charts).
In LineChartFrame::OnVariableChoice()
var: LATITUDE, time1:-1, time2:-1, group1:0, group2:1
In LineChartFrame::OnActivate()
In LineChartFrame::OnVariableChoice()
var: ACQ_DATE, time1:-1, time2:-1, group1:0, group2:1

**Comment by YidanJ-Wu** [comment]
Windows 8 1.10.1.85
Ran the averages chart but did not crash. However I did notice that some buttons disappear when the window is resized. 
![image](https://user-images.githubusercontent.com/22801047/31057633-9faa50de-a6ab-11e7-940f-fc4184d3c634.png)
![image](https://user-images.githubusercontent.com/22801047/31057637-bc1dbcba-a6ab-11e7-91c2-8da80b159b2f.png)

**Comment by bsalas11** [comment]
Win 1.14

No crash detected using averages chart. Buttons do not disappear when resizing. 

When selecting different observations on the map, the averages chart y-axis does not change to accommodate the new numerical range. This results in graph points falling above and below what is visible on the chart. 

![average](https://user-images.githubusercontent.com/46054957/62896526-db702200-bd16-11e9-892f-65328fa385e3.PNG)
![average off](https://user-images.githubusercontent.com/46054957/62896527-dc08b880-bd16-11e9-8d0f-97776ab84333.PNG)
![avgoff2](https://user-images.githubusercontent.com/46054957/62896528-dc08b880-bd16-11e9-8369-f1dcef4883d1.PNG)

**Comment by lixun910** [comment]
@bsalas11 Yes, there is a right-click menu option to control if the averages chart y-axis change with the selection. 

<img width="772" alt="Screen Shot 2019-08-12 at 2 09 23 PM" src="https://user-images.githubusercontent.com/2423887/62898654-dd33e880-bd0a-11e9-9254-c27657947360.png">
