### ISSUE TITLE
Crash: csv file loading fails

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1126]
From: lanselin@gmail.com
 Details:
os: 1-10-12
vs: 1-10-1-81
/Users/luc/Desktop/GeoDa.1.10.1.81.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
Open CsvFieldConfDlg.
CsvFieldConfDlg::PrereadCSV()
CsvFieldConfDlg::UpdateFieldGrid()
CsvFieldConfDlg::ReadCSVT()
CsvFieldConfDlg::UpdatePreviewGrid()
CsvFieldConfDlg::UpdateXYcombox()
CsvFieldConfDlg::OnOkClick()
CsvFieldConfDlg::WriteCSVT()
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/luc/Dropbox/z_Courses/uc_spatial_data_science17/labs/1_datascience/test/311_Service_Requests_-_Abandoned_Vehicles.csv
Open Layer:311_Service_Requests_-_Abandoned_Vehicles
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/luc/Dropbox/z_Courses/uc_spatial_data_science17/labs/1_datascience/test/311_Service_Requests_-_Abandoned_Vehicles.csv

**Comment by lanselin** [comment]
csv file for the lab doesn't load in 81! spinning ball ...

**Comment by lixun910** [comment]
It's working on my side. Can you share your data with me?

<img width="785" alt="screen shot 2017-09-28 at 7 45 05 am" src="https://user-images.githubusercontent.com/2423887/30973037-fcddae96-a420-11e7-9420-a7687ba002b1.png">

**Comment by lanselin** [comment]
I think you have the data, it’s the 975Mb 331 abandoned vehicles file, with some 172,000 observations

**Comment by lixun910** [comment]
The one I have with 137,867 records. It loads fine with 81 on my side, see screenshot. Can you Skype?

**Comment by jkoschinsky** [comment]
Let's check the dropbox link, too, since that's been a weak spot.

**Comment by lanselin** [comment]
false alarm, the Duplicate command in Mac OS had created a corrupted copy of the csv file. all works fine with the original!
