### ISSUE TITLE
Ubuntu date problem

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1130]
from Rodrigo:
On page 10 says: "In order for GeoDa to recognize dates such as 1/1/11, we need to enter %m/%d/%y into the options box, as shown below".

However, at least in the Ubuntu version, it's necessary to enter %m/%d/%Y (capital y). If I use "y", it recognizes 2011 as 2020.

from Luc:
That is a bug. The standard convention is to use %y for a two digit year and %Y for
a four digit year. There must be something weird with the Ubuntu implementation
of the dates functionality. I have cc-d Xun, since it should be the same as for
Mac/Windows, i.e., %y for a year as 11.

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.14.1

Could not locate anywhere in the current GeoDa version where the date format used is %m/%d/%y
Below is the date format that seems to be used in the current version or am I looking in the wrong place? (GeoDa > Preferences > Data Source > Date/Time formats)

<img width="670" alt="screen shot 2018-07-09 at 3 30 13 pm" src="https://user-images.githubusercontent.com/37029239/42474383-0ba7f598-838d-11e8-878e-9bb37ba3873e.png">

**Comment by jkoschinsky** [comment]
Steps to replicate in Ubuntu:

workbook chapter that ticket is referencing:
http://geodacenter.github.io/workbook/1_datascience/lab1.html#converting-a-string-to-date-format

1. add %m/%d/%y and see if it reads in the year correctly (e.g. 2011) or wrongly (e.g. 2020)

**Comment by lixun910** [comment]
verified in V191:
add %m/%d/%y and it works in GeoDa V191 on Ubuntu 18.04
GeoDa download link: https://www.dropbox.com/s/9koxx141lguh3bh/geoda_1.12.1.191-1xenial1.deb?dl=0

<img width="778" alt="screen shot 2019-01-17 at 11 38 43 am" src="https://user-images.githubusercontent.com/2423887/51341813-7342b180-1a4f-11e9-8c4a-1934b3b7379b.png">
