### ISSUE TITLE
can't apply scientific notation on natural breaks and it breaks custom categories 

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1131]
Steps: 
1. create a natural breaks using sid74 (SID NC in sample dataset)
1. Right click on legend, "use scientific notation" doenst work

Steps:
1. using SID NC
2. create custom categories
<img width="733" alt="screen shot 2017-09-29 at 5 25 55 pm" src="https://user-images.githubusercontent.com/2423887/31040376-a23dcec8-a53b-11e7-8ef8-254c1e7e498c.png">
3.use created categories to create a thematic map
<img width="601" alt="screen shot 2017-09-29 at 5 26 12 pm" src="https://user-images.githubusercontent.com/2423887/31040378-a78dea20-a53b-11e7-8931-563a355e7199.png">
4. right click on legend, click "use scientific notation"
<img width="604" alt="screen shot 2017-09-29 at 5 26 23 pm" src="https://user-images.githubusercontent.com/2423887/31040393-d64082f6-a53b-11e7-88fd-ef72be5a4ad8.png">

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.85 (OSX Yosemite, 10.10.5).
