### ISSUE TITLE
Add hyperlink to sample data

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1134]
Below GeoDa's sample data, add hyperlink (Data Link) to these data URLs (instead of overall sample data site):

<img width="366" alt="screen shot 2017-09-30 at 6 28 56 pm" src="https://user-images.githubusercontent.com/13679743/31050348-61f63724-a60d-11e7-94f0-a3657f076351.png">

Guerry: https://geodacenter.github.io/data-and-lab//Guerry_documentation/
NCOVR: https://geodacenter.github.io/data-and-lab//ncovr/
Balt: https://geodacenter.github.io/data-and-lab//baltim/
Boston: https://geodacenter.github.io/data-and-lab//boston-housing_old/
Columbus: https://geodacenter.github.io/data-and-lab//columbus/
SIDS: https://geodacenter.github.io/data-and-lab//sids2/
Nepal: https://geodacenter.github.io/data-and-lab//nepal/
NYC: https://geodacenter.github.io/data-and-lab//nyc/
Colombia: https://geodacenter.github.io/data-and-lab//colomb_malaria/
Phx: https://geodacenter.github.io/data-and-lab//phx/
SF Crime: https://geodacenter.github.io/data-and-lab//SFcrimes_vars/

**Comment by lixun910** [comment]
I thought it should be a description page for each dataset. Why just add the url to the zip file? since the sample data (data itself) already come with GeoDa?

**Comment by jkoschinsky** [comment]
yes, makes sense - I updated the URLs to point to the new data pages

**Comment by lixun910** [comment]
Hi Julia, 

Some of the links with too long url (see below), can you make these two urls shorter? Thanks!
https://geodacenter.github.io/data-and-lab/Guerry_documentation/  
to https://geodacenter.github.io/data-and-lab/Guerry/
https://geodacenter.github.io/data-and-lab/boston-housing_old/
to
https://geodacenter.github.io/data-and-lab/boston-housing/
<img width="443" alt="screen shot 2017-10-02 at 4 29 16 pm" src="https://user-images.githubusercontent.com/2423887/31103967-e6e058a2-a78e-11e7-9e90-3ada279e3b04.png">

**Comment by jkoschinsky** [comment]
We could just run them through bit.ly or google url shortener?

**Comment by lixun910** [comment]
I just updated the urls. Didn't use bit.ly or goog.le, since these are looking "unsafe".

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.5 
Verified

**Comment by VeraB620** [comment]
OS X El Capitan 10.11.16
Verified
All hyperlinks connect to the correct location
