### ISSUE TITLE
inconsistencies in PCP labels

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1136]
I noticed that there is a slight inconsistency between the variable selection
dialogs for EDA. For the scatter plot matrix, 3D scatter, conditional plots, etc.
the variables are as they are in the table. For example, for the NYC sample
data set, these are lower case. However the PCP dialog somehow has them
in all caps. Maybe they should be consistent and follow the same setting as
in the table?
L.

![image](https://user-images.githubusercontent.com/13679743/31061436-f9a27fea-a6e6-11e7-82a6-dfb84e6ac736.png)

![image](https://user-images.githubusercontent.com/13679743/31061439-fce910c4-a6e6-11e7-85be-f7157789690a.png)

**Comment by lanselin** [comment]
btw, the PCP graphs have the variable names in lower case again

**Comment by lixun910** [comment]
This is a very poor design. Will fix this.

**Comment by YidanJ-Wu** [comment]
Windows 1.12.1.5
Verified
![image](https://user-images.githubusercontent.com/22801047/31310030-437c4e7a-ab56-11e7-8c3f-e22cb91a6301.png)
![image](https://user-images.githubusercontent.com/22801047/31310032-495dce9a-ab56-11e7-964c-513afa6d2b09.png)

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.137
Verified

<img width="527" alt="screen shot 2018-06-20 at 10 30 39 pm" src="https://user-images.githubusercontent.com/37029239/41696411-9b232ce6-74d9-11e8-8747-48204d8c361e.png">
