### ISSUE TITLE
Just going through the new lab and under preferences:data source: there isn't an option to change the date format.  I am using the latest version on MacOS.

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1141]
[Steps you took before something went wrong]

Downloaded the abandoned vehicles data from Chicago in csv format
Dragged it into GeoDa
Opened table menu
Opened preferences menu

os: 1-10-13
vs: 1-10-0-8
/Applications/GeoDa/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/jms7/Desktop/MW_Health/MWHealth.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnReportBug()
Open ReportBugDlg.
In ReportBugDlg::OnOkClick()
In ReportBugDlg::OnOkClick()

**Comment by lixun910** [comment]
Thanks! The version you use is vs: 1.10.0.8, which is not the latest. Please use version 1.12:
https://s3-us-west-2.amazonaws.com/geodasoftware/GeoDa1.12.0.0-Installer.dmg
