### ISSUE TITLE
geoda can open shapefile without dbf file

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1143]
reported by a user. GeoDa should detect missing dbf file and raise warning if not exist. Otherwise, any further operations will crash GeoDa.

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.5
Currently does not raise error message when I load a shapefile without DBF. It just displays the table without values: 
![image](https://user-images.githubusercontent.com/22801047/31310334-ebdf4e46-ab5b-11e7-892b-b6092039bd6c.png)

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.5
(Deleted earlier comment because I misread the ticket)
Verified
![image](https://user-images.githubusercontent.com/22801047/31310346-46628a9a-ab5c-11e7-83c6-abbb39dc61cd.png)

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.137

map still shows up even without a dbf file
(deleted the dbf file after downloading the folder and the map still opened)

<img width="593" alt="screen shot 2018-07-02 at 1 45 25 pm" src="https://user-images.githubusercontent.com/37029239/42180883-7d5ca81c-7dfe-11e8-9c8b-0cffa956fc0d.png">
<img width="301" alt="screen shot 2018-07-02 at 1 44 55 pm" src="https://user-images.githubusercontent.com/37029239/42180884-7d748c52-7dfe-11e8-9b1e-dbc0b3e61756.png">

**Comment by jkoschinsky** [comment]
@ncarola: what happens when you click on the table icon?

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.157
Verified

Table contains no values

<img width="420" alt="screen shot 2018-07-03 at 9 03 38 pm" src="https://user-images.githubusercontent.com/37029239/42252903-a403719c-7f04-11e8-97a5-6478ba9947b9.png">
