### ISSUE TITLE
Geoda doesn't handle empty column data

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1144]
Steps
1: open Guerry from sample panel
2 Add Variable from Table, e.g. TEST (double) -- now it's an empty column
3 Open Box plot, select TEST, 
4 GeoDa will crash

**Comment by lixun910** [comment]
This also applies to all other plots/maps:
Thematic maps
PCP
Scatter Matrix
HIstogram
etc.

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.5
Now displays error message instead of crashing: 
![image](https://user-images.githubusercontent.com/22801047/31310154-a1e3abe6-ab58-11e7-9209-279ce13ea6b8.png)

**Comment by VeraB620** [comment]
OS X El Capitan 10.11.6
GeoDa 1.12.1.137
-adding a variable no option for double (not sure if this should be an option)
-no crash, error message instead
<img width="391" alt="screen shot 2018-06-30 at 11 36 29 am" src="https://user-images.githubusercontent.com/4943475/42127209-dd373096-7c59-11e8-901d-87f8aa0f6187.png">
<img width="740" alt="screen shot 2018-06-30 at 11 33 23 am" src="https://user-images.githubusercontent.com/4943475/42127212-ded19bd0-7c59-11e8-9588-91d36b58407c.png">
<img width="668" alt="screen shot 2018-06-30 at 11 34 15 am" src="https://user-images.githubusercontent.com/4943475/42127214-dfbfef10-7c59-11e8-93c3-45947318ff69.png">
