### ISSUE TITLE
cartogram image save option doesn't have svg and postscript that the map views have

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1147]

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.5
Verified
![image](https://user-images.githubusercontent.com/22801047/31310080-46583996-ab57-11e7-9027-c10d368955fb.png)

**Comment by jkoschinsky** [comment]
Save image as for Table: also missing svg + postscript
add this to all views

**Comment by lixun910** [comment]
What do you mean “save image for Table”? The plots cannot be saved as svg or postscript in current design.

**Comment by jkoschinsky** [comment]
sorry, meant histogram, not table!

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.137
Verified


<img width="346" alt="screen shot 2018-06-20 at 7 33 05 pm" src="https://user-images.githubusercontent.com/37029239/41691589-fb169fb6-74c0-11e8-8d19-60c3b468d3d7.png">
<img width="589" alt="screen shot 2018-06-20 at 7 32 53 pm" src="https://user-images.githubusercontent.com/37029239/41691590-fb24b74a-74c0-11e8-9868-12b2b71139ba.png">

Histogram still can not be saved as svg or postscript

**Comment by jkoschinsky** [comment]
ony maps have svg an ps,not plots
