### ISSUE TITLE
category editor problems

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1149]
from Luc:
when you change the number of categories from 4 to 5, the histogram all of a sudden only has one bin.

![image](https://user-images.githubusercontent.com/13679743/31243862-59d6ffea-a9cf-11e7-9378-acf64393f8da.png)

**Comment by lanselin** [comment]
so, above is the starting point (strange starting value of < 0, but that's a different issue). so when changing the number of categories to 5, the following happens

<img width="721" alt="screen shot 2017-10-05 at 12 36 18 pm" src="https://user-images.githubusercontent.com/4008351/31245374-c59bb50e-a9cf-11e7-9360-7fa8c7930c14.png">

**Comment by lanselin** [comment]
it may have to do with a combination of the following two items: user defined breaks, and automatic labels turned off; maybe the logic of the histogram cannot deal with this combination

<img width="725" alt="screen shot 2017-10-05 at 1 21 18 pm" src="https://user-images.githubusercontent.com/4008351/31245522-449b98e2-a9d0-11e7-843a-39144e903e84.png">
<img width="721" alt="screen shot 2017-10-05 at 1 21 29 pm" src="https://user-images.githubusercontent.com/4008351/31245523-44a14e9a-a9d0-11e7-96c1-c3094f199212.png">

**Comment by lixun910** [comment]
yes, this is a bug. Will fix it.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
Verified 

<img width="546" alt="14 mar 02" src="https://user-images.githubusercontent.com/36253697/37429109-48e7d7c0-27c6-11e8-8c12-5421896fb3be.PNG">
<img width="549" alt="14 mar 01" src="https://user-images.githubusercontent.com/36253697/37429111-490104ca-27c6-11e8-81c2-3a762cad8c03.PNG">

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v113
rent2008 variable from NYC data
OSX

<img width="732" alt="screen shot 2018-03-19 at 3 30 42 pm" src="https://user-images.githubusercontent.com/13679743/37620549-8bee62d8-2b8a-11e8-8735-2c8b3343c33a.png">
