### ISSUE TITLE
I noticed quite a delay when drawing a selection rectangle in a box plot.

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1152]
selection in the map is super fast, but on the box plot very slow by comparison. 
also, seems like there is a lag between drawing the rectangle and it actually appearing.

**Comment by jkoschinsky** [comment]
there used to be a ticket about this ...

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.5
How long is the lag on other people's devices/operating systems? On mine it's less than a second but definitely noticeable.

**Comment by VeraB620** [comment]
OS X El Capitan 10.11.16
No lag in box plot or map.
