### ISSUE TITLE
Co-location map legend bug

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1153]
from Luc:
In the co-location map, there is a drop down list with different  options
for “select color scheme”. In the example below, I selected “box map”
as the scheme, but nothing happens to the colors for the legend.
And the map that is generated uses the original unique values colors,
not the box map scheme. See below, the colors are not the box map 
colors. And the map is the same as before, not with box map colors.

![image](https://user-images.githubusercontent.com/13679743/31260054-dbbf2eec-aa10-11e7-880b-6bb7413fd38c.png)

![image](https://user-images.githubusercontent.com/13679743/31260056-e10a6fc4-aa10-11e7-914b-d4d28cd5b167.png)

**Comment by jkoschinsky** [comment]
from Luc: 
There is a bit of a disconnect between the spirit behind the unique values
map, which is a categorical map, and the use of three digits of precision in
the legend. I don’t remember this being the case in the past. For example,
in the screen shot below, there are five categories. They should be labeled
1, 2, 3, etc., NOT 1.000, 2.000 etc. since these are labels for categories,
not real variables. This is probably an easy fix. If that is the case, could I 
have it right away? I need this for the mapping lab screen shots.
Btw, this is not an issue for the co-location map.

![image](https://user-images.githubusercontent.com/13679743/31260086-22438c28-aa11-11e7-87cd-acfa874c2ba5.png)

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111

Precision are fixed. 
The unique value color scheme is different from that of box now. 

But the color scheme for box, percentile and std-dev are the same. Not sure it is designed this way. 

<img width="332" alt="13 mar 07" src="https://user-images.githubusercontent.com/36253697/37361837-c18394e8-26eb-11e8-8d14-aff95ced5e74.PNG">
<img width="355" alt="13 mar 07box" src="https://user-images.githubusercontent.com/36253697/37361836-c127c028-26eb-11e8-97d2-188d9da84ea3.PNG">
<img width="354" alt="13 mar 07percentile" src="https://user-images.githubusercontent.com/36253697/37361838-c1e9fbac-26eb-11e8-84e8-ac46d287be1c.PNG">

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v113
OSX
