### ISSUE TITLE
Saving an image:  Default type vs. default extension vs. actual filetype saved

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1156]
When saving an image, the default type is PNG, but the extension shown at the end of the filename is .bmp.  I hit Enter to accept the default filename and it saved a PNG.

@emochoa 

os: 3-4-4
vs: 1-12-0-0
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
In GdaFrame::OnHelpAbout()
In GdaFrame::OnCheckUpdates()
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::OnSample()
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/usr/local/geoda/web_plugins/samples.sqlite
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
kids2009
Open HistogramFrame.
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
In OnHistogramIntervals()
In HistogramFrame::OnHistogramIntervals()
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
In HistogramFrame::OnActivate()
PNG selected
In HistogramFrame::OnActivate()
In GdaFrame::OnReportBug()
Open ReportBugDlg.
In HistogramFrame::OnActivate()
In ReportBugDlg::OnOkClick()

**Comment by lixun910** [comment]
@emochoa This is a normal behavior on Ubuntu GTK. If you check Firefox browser, you will see the same behavior:  when you try to save a webpage, the default extension is .html, and it won't change even if you select save as plain text file  (should be .txt). See the screenshot:

<img width="1043" alt="screen shot 2017-10-06 at 3 40 28 pm" src="https://user-images.githubusercontent.com/2423887/31304718-fd976e68-aadc-11e7-8510-3aa6717ae546.png">
