### ISSUE TITLE
Datetime format: support AM/PM 

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1158]
e.g. 2017/10/04 1:00 PM
should be recognized as:  %Y/%m/%d %H:%M %p

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.11
%p does not show up in default. I had to add it manually. 
![image](https://user-images.githubusercontent.com/22801047/31527668-7a7db9e4-af94-11e7-98c7-3fe7b6d14db2.png)
Also there is no option for Time/Date format when creating a new variable: 
![image](https://user-images.githubusercontent.com/22801047/31527722-d8a8e098-af94-11e7-94be-7e3c77e5ecc1.png)

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.137

%p is replaced by %S

<img width="702" alt="screen shot 2018-06-19 at 10 08 02 pm" src="https://user-images.githubusercontent.com/37029239/41635251-57082cc2-740d-11e8-8834-86cfbe6548b3.png">

**Comment by VeraB620** [comment]
OS X El Captain 10.11.6
GeoDa 1.12.1.137
I too have %S
<img width="690" alt="screen shot 2018-06-26 at 8 55 53 am" src="https://user-images.githubusercontent.com/4943475/41916969-e9304920-791e-11e8-814d-dd1493d9d4b3.png">

**Comment by lixun910** [comment]
%S is a regular expression for second, %p is a regular expression for AM/PM

The idea is to allow user to define the data/time format in preference dialog.
I've added %Y/%m/%d %H:%M %p at the end as an example. This regex is for string like "2012/01/01 09:10 AM". 

There are many other combinations e.g. time only: %H:%M:%S %p
