### ISSUE TITLE
Blank map view with raw rate

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1159]
GeoDa 1.12.1.5 (OSX Yosemite, 10.10.5.
ohiolung.shp

Luc and Julia replicated:
something strange with the raw rate map. Sometimes it does not
create a map, but only an empty window, but other times it works.

It is very strange, and not consistent. Sometimes it works and sometimes 
it doesn’t - see below.

<img width="605" alt="screen shot 2017-10-07 at 10 50 49 am" src="https://user-images.githubusercontent.com/13679743/31309568-c40a72be-ab4d-11e7-92c4-76e65509c098.png">

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.5
I ran this a few times on different shapefiles and geojsons. Haven't gotten a blank map yet. Does this only happen with certain combinations of data types (e.g. an integer and a double)?

**Comment by luluzhou766** [comment]
Win 10, 64bit
Geoda 1.12.1.131


Tried few times of raw rate, didnot get blank maps.

![01](https://user-images.githubusercontent.com/36253697/39576221-020daf3e-4f10-11e8-9d70-9df6d4a12dc0.PNG)

**Comment by jkoschinsky** [comment]
Can't replicate in GeoDa 1.12.1.133 OSX
