### ISSUE TITLE
Crash Report:  category editor crash in conditional plot (verified)

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1170]
From: 
 Details:
os: 1-10-11
vs: 1-12-0-0
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
In GdaFrame::OnHelpAbout()
In GdaFrame::OnCheckUpdates()
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
ConnectDatasourceDlg::OnSample()
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Applications/GeoDa.app/Contents/MacOS/../Resources/samples.sqlite
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
bor_subb
Open HistogramFrame.
In HistogramFrame::OnActivate()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
bor_subb
Open HistogramFrame.
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
In OnHistogramIntervals()
In HistogramFrame::OnHistogramIntervals()
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
In OnHistogramIntervals()
In HistogramFrame::OnHistogramIntervals()
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
In OnHistogramIntervals()
In HistogramFrame::OnHistogramIntervals()
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
In GdaFrame::OnDisplayStatistics()
In HistogramFrame::OnDisplayStatistics()
In HistogramFrame::OnActivate()
Click GdaFrame::OnSetDisplayPrecision
AxisLabelPrecisionDlg with precision = 1.
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
kids2008
Open HistogramFrame.
In HistogramFrame::OnActivate()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
kids2009
Open HistogramFrame.
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
kids2009
Open BoxPlotCanvas.
Open TimeChooserDlg.
Open VarGroupingEditorDlg.
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnRemoveFrListClick
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListRightUp
In VarGroupingEditorDlg::OnIncludeListEdit
In VarGroupingEditorDlg::OnIncludePopupClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnIncludeListEditEnd
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnMoveUpClick
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnMoveUpClick
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnMoveUpClick
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnMoveUpClick
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnRemoveFrListClick
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListRightUp
In VarGroupingEditorDlg::OnIncludePopupClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnCreateGrpClick
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In TimeChooserDlg::OnStepForwardButton
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
In TimeChooserDlg::OnStepForwardButton
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
In TimeChooserDlg::OnStepForwardButton
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
In TimeChooserDlg::OnStepForwardButton
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
In TimeChooserDlg::OnStepForwardButton
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
In TimeChooserDlg::OnStepBackButton
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
In TimeChooserDlg::OnStepBackButton
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
In TimeChooserDlg::OnStepBackButton
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
In TimeChooserDlg::OnStepBackButton
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
In TimeChooserDlg::OnStepBackButton
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
In TimeChooserDlg::OnStepBackButton
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
Close TimeChooserDlg::OnClose
In VarGroupingEditorDlg::OnClose
Close BoxPlotCanvas.
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
kids200
forhis08
Open ScatterNewPlotFrame.
In GdaFrame::OnViewLowessSmoother()
In GdaFrame::OnEditLowessParams()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
kids200
rentpct08
hhsiz08
hhsiz08
Open ScatterNewPlotFrame.
Open BubbleSizeDlg.
In BubbleSizeSliderDlg::OnSliderChange()
In BubbleSizeSliderDlg::OnSliderChange()
In BubbleSizeSliderDlg::OnSliderChange()
In BubbleSizeSliderDlg::OnSliderChange()
In BubbleSizeSliderDlg::OnSliderChange()
In BubbleSizeSliderDlg::OnSliderChange()
In BubbleSizeSliderDlg::OnReset()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
kids200
rentpct02
hhsiz02
Open C3DPlotCanvas.
Close C3DPlotCanvas.
Open PCPDlg.
Click PCPDlg::OnOkClick
Open PCPFrame.
In GdaFrame::ChangeToQuantile(5)
In GdaFrame::ChangeToQuantile(10)
In GdaFrame::OnThemelessMap()
In GdaFrame::OnHinge15()
In GdaFrame::OnCondPlotChoices()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
kids200
rentpct02
hhsiz1990
hhsiz02
Open ConditionalScatterPlotFrame.
In GdaFrame::OnCondHorizThemelessMap()
In GdaFrame::OnCondHorizThemelessMap()
In GdaFrame::OnNewCustomCatClassifC()
Open CatClassifFrame
In CatClassifPanel::PromptNew
suggested title:
field name:kids200

**Comment by lixun910** [comment]
same with #1171
close duplicated one
