### ISSUE TITLE
Bug: variable type can't be changed if first observation is undefined

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1173]
from Coro:
wants to run local Moran with EB rates
Bug: variable type can't be changed if first observation is undefined

Data table:
population and event but first row is undefined. 

In this case, GeoDa treats the population variable as string and this can't be changed to numeric.
If it's not the first observation, then type can be changed.

**Comment by lixun910** [comment]
Can you share the data with me? I just tried, even the first row is
undefined (empty), the string type column can be changed to numeric (you
have to do in Table->Edit properties, not in CSV config dialog). Thanks!

Xun Li, Ph.D

Assistant Director for Data Science
Center for Spatial Data Science
University of Chicago
http://spatial.uchicago.edu

**Comment by jkoschinsky** [comment]
from Coro:
I tried again and it worked!!!!! I've been able to convert the string to an integer without problems.
