### ISSUE TITLE
Connectivity map -- selection is incorrect

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1175]
When opening the connectivity map for a weights file, the selection starts as soon as the pointer is moved, even though the pointer may be outside the map. The location selected at this point (in the example, a county in Florida) has nothing to do with where the pointer is. Something is off.

<img width="476" alt="geodascreensnapz355" src="https://user-images.githubusercontent.com/4008351/31412192-d0e6a1fe-add9-11e7-985f-1a66c5993a2b.png">

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.11
Verified
![image](https://user-images.githubusercontent.com/22801047/31527398-854df214-af92-11e7-88d7-030ccfce7f67.png)

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.137
Verified

<img width="944" alt="screen shot 2018-06-19 at 8 32 28 pm" src="https://user-images.githubusercontent.com/37029239/41632516-f6de6b2a-73ff-11e8-9af5-147f48abaf75.png">
