### ISSUE TITLE
Calculator -- spatial lag dialog

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1178]
Instead of the option "include diagonal of weights matrix", we should have "include self-neighbors".
Strictly speaking, the diagonal of the weights matrix is zero, so that wouldn't make a difference. Self-neighbors holds no matter what.

<img width="259" alt="screen shot 2017-10-12 at 11 31 08 am" src="https://user-images.githubusercontent.com/4008351/31510132-0ba0f944-af41-11e7-954e-42e46f52df62.png">

**Comment by lanselin** [comment]
btw, diagonal is misspelled as diagnoal - but it should disappear anyway

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
Not fixed yet

<img width="561" alt="13 mar 05" src="https://user-images.githubusercontent.com/36253697/37360387-04453f1a-26e8-11e8-92d2-579788f5d25f.PNG">

**Comment by lixun910** [comment]
This issue has been updated and fixed. Please see notes from Luc:

First is an interface issue. While it is fine for inverse distance weights to have the
four options, here is how they should be implemented:

- row-standardized, no diagonal (this is the default as i); this should NOT be the
  default for inverse distance. for the latter, the default should be not row-standardiized
  and no diagonal included: that uses the actual weights, as should be the case
- not-rowstandardized no diagonal
- row standardized with diagonal
- not row-standardized with diagonal

For the kernel weights, the only available option should be NOT row-standardized and
INCLUDE diagonal. This is the only option that makes sense.

See the attached spreadsheet for details:
[lags.xlsx](https://github.com/GeoDaCenter/geoda/files/1835567/lags.xlsx)
