### ISSUE TITLE
PCP - full range not visible

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1179]
There seems to be a problem displaying the full range of the values on the axes in a PCP when the values are large, e.g., house prices (see below). The low value is cut off. Resizing the plot does not help.

<img width="238" alt="screen shot 2017-10-12 at 1 24 56 pm" src="https://user-images.githubusercontent.com/4008351/31515054-10393f92-af51-11e7-8d0a-371ec0a1b237.png">

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.19
Verified

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.137
Verified

<img width="593" alt="screen shot 2018-06-20 at 7 26 40 pm" src="https://user-images.githubusercontent.com/37029239/41691387-f716985e-74bf-11e8-9f2d-2946bdafb5df.png">
