### ISSUE TITLE
Moran scatterplot - no clean exit

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1182]
In the Moran scatter plot, after checking the regimes option and brushing the scatter plot, there is weird behavior at the end. So, checking the regimes option back off and clearing the selection,
leaves a red line and a black line (v 1.12.1.11).

<img width="978" alt="screen shot 2017-10-13 at 10 46 11 am" src="https://user-images.githubusercontent.com/4008351/31556965-40b04d9c-b004-11e7-93b2-6009e1881d6d.png">

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
Verified

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v113
OSX
