### ISSUE TITLE
Moran scatterplot -- insufficient white space at edge of window

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1183]
After activating the regimes option, the two auxiliary scatter plots seem squished, especially on the right hand side (unselected). The edge of the window view more or less coincides with the edge of the plot, leaving insufficient space for the labels.

<img width="604" alt="screen shot 2017-10-13 at 10 51 17 am" src="https://user-images.githubusercontent.com/4008351/31557084-b11ca3b4-b004-11e7-8da1-7d24c7b78837.png">

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
Verified 
<img width="448" alt="13 mar 04" src="https://user-images.githubusercontent.com/36253697/37359356-45613416-26e5-11e8-84db-4e695a75dcb4.PNG">

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v113
OSX
