### ISSUE TITLE
Table - spatial lag calculator

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1184]
Something very strange in the spatial lag operator in the table. I noticed that the MORAN_LAG saved as an option in the Moran scatter plot is different from the spatial lag calculated in the table on a standardized variable. The MORAN_STD and the standardized value in the table are the same, but the spatial lags are not. Also, when using the spatial lag in the table on the MORAN_STD variable, the result is different from the MORAN_LAG generated from the moran scatter plot. The latter is correct, the Moran's I has been verified in R and is exactly the same. Which leaves the possibility that the something is wrong with the spatial lag operator in the Table? All values given below: MORAN_STD and MORAN_LAG generated by the moran scatter plot, CHECK2 is the table spatial lag applied to MORAN_STD, STAN is the table standardization applied to the same variable (identical to MORAN_STD), and WSTAN is the table spatial lag applied to STAN (same result as CHECK2 but different from MORAN_LAG). MORAN_LAG is the correct one.

<img width="532" alt="screen shot 2017-10-13 at 11 12 31 am" src="https://user-images.githubusercontent.com/4008351/31557952-367ac916-b008-11e7-9672-760627175c49.png">

**Comment by lanselin** [comment]
verified on mac with .19

<img width="462" alt="1_433_lagintable" src="https://user-images.githubusercontent.com/4008351/31693881-a3e86204-b366-11e7-8117-9c2c8f43cd67.png">

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111

<img width="558" alt="13 mar 03" src="https://user-images.githubusercontent.com/36253697/37359184-d721fa62-26e4-11e8-8833-beb55f75214a.PNG">

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v113
OSX
