### ISSUE TITLE
Moran scatter plot -- save image as not working properly

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1185]
The save image as option in the Moran scatter plot only saves the central plot, not the plots for the selected and unselected. See below, saved as png compared to the screen shot.

![clev_sls_154_corelisascatterplotframe2](https://user-images.githubusercontent.com/4008351/31558444-180dcf6c-b00a-11e7-83b6-0a4793846508.png)

<img width="594" alt="screen shot 2017-10-13 at 11 30 38 am" src="https://user-images.githubusercontent.com/4008351/31558453-1f34e6d6-b00a-11e7-94f0-49eb75f85768.png">

**Comment by lanselin** [comment]
on mac, v 1.12.1.11

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111

![13 mar 02](https://user-images.githubusercontent.com/36253697/37355871-a7b74a1e-26dc-11e8-919e-bfbc072b0593.png)

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v113
OSX
