### ISSUE TITLE
Cluster map - save image as better align legend

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1188]
Comparing the image saved as for a standard choropleth map (e.g., natural breaks) vs the image saved for a cluster map, the latter has too much extra white space between the legend and the actual map.

I thought that had been fixed, but apparently it was fixed for the standard maps, but not for the cluster maps. Compare the two saved images below. The cluster map one should be like the natural breaks one.

![pc1_nat_breaks](https://user-images.githubusercontent.com/4008351/31576540-5cdb6ef0-b0ba-11e7-966e-a6a397df8ac3.png)
![pc1_g_01](https://user-images.githubusercontent.com/4008351/31576543-61877606-b0ba-11e7-8e0f-bfe902cca558.png)

**Comment by lanselin** [comment]
Co-location map is fine.

![colocation_pc1m_pc1ge](https://user-images.githubusercontent.com/4008351/31576591-0dfb7478-b0bb-11e7-8a9b-5912c8d9cbfe.png)

**Comment by lanselin** [comment]
verified on mac version 1.12.1.19

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111

![13 mar 01](https://user-images.githubusercontent.com/36253697/37355417-aa1824dc-26db-11e8-8733-059ef65bd5e3.png)

**Comment by luluzhou766** [comment]
Win 10, 64bit
Geoda 1.12.1.131
Verified

![guerry lisa](https://user-images.githubusercontent.com/36253697/39575770-519e57a8-4f0e-11e8-8cb0-a08586dd8efe.png)
![guerry local geary](https://user-images.githubusercontent.com/36253697/39575772-5443a6ac-4f0e-11e8-9292-30e2846742fe.png)
![guerrygetisordmapframe](https://user-images.githubusercontent.com/36253697/39575774-56188d80-4f0e-11e8-9d14-b430d9fb5726.png)
