### ISSUE TITLE
Moran scatter plot -- View option not working

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1189]
The View option in the Moran scatter plot does not seem to be working anymore, other than the regimes regression option.  For example, unchecking the Linear Smoother option does nothing (the line remains), checking LOWESS smoother does nothing (no smoother appears - see below), but the LOWESS parameters interface works (but it doesn't do anything since there is no LOWESS curve).
This worked fine in earlier versions (this is V1.12.1.11).

<img width="626" alt="screen shot 2017-10-14 at 9 25 09 am" src="https://user-images.githubusercontent.com/4008351/31576901-11d23ff8-b0c2-11e7-934b-1c375c4d2753.png">

**Comment by lanselin** [comment]
This issue goes back several versions, so maybe it is a duplicate ticket. I noticed that the view options do seem to work properly in the two side graphs for the regimes regression. For example, with the Linear smoother unchecked, there is no regression line in the red and the black plot, but the line in the main plot remains.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
Verified 

<img width="445" alt="12 mar 13" src="https://user-images.githubusercontent.com/36253697/37313649-12aede76-2648-11e8-9916-7cdf00b86ade.PNG">
<img width="450" alt="12 mar 12" src="https://user-images.githubusercontent.com/36253697/37313650-12ce6656-2648-11e8-80ce-86d0e4f90654.PNG">
<img width="447" alt="12 mar 14" src="https://user-images.githubusercontent.com/36253697/37313651-12ec80be-2648-11e8-9ae2-660248f2919c.PNG">

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v113
OSX
