### ISSUE TITLE
Error message when saving conditional map as PNG

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#1193]
Windows 8 1.12.1.11
Created conditional map. Left click save as image. Selected folder location, clicked save. 
![image](https://user-images.githubusercontent.com/22801047/31587314-3bce3dfa-b1a5-11e7-9829-107cbfd19ce0.png)

Edit: Attempted to save a conditional map from a different shapefile. Got a shorter error message this time. 
![image](https://user-images.githubusercontent.com/22801047/31587335-afaa12bc-b1a5-11e7-9134-b8e902c8a7ec.png)

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.19
Saves as PNG without any issues. The text size scales up a bit. 
![image](https://user-images.githubusercontent.com/22801047/31871375-6b755dc0-b779-11e7-87cd-1ca0106d140f.png)
![guerryconditionalmapframe](https://user-images.githubusercontent.com/22801047/31871381-7407333c-b779-11e7-8bf2-059bdbc19a7d.png)

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.29
Saved PNG of conditional map without error. 
Should there be more formats available, or just PNG and BMP? 
![image](https://user-images.githubusercontent.com/22801047/32024583-ab90f588-b9a2-11e7-8a10-0e218ff452d9.png)

**Comment by lixun910** [comment]
For conditional map, there are only bmp and png.

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.137
Verified
Successful save of conditional map as PNG without error

<img width="348" alt="screen shot 2018-06-14 at 3 33 02 pm" src="https://user-images.githubusercontent.com/37029239/41436786-5a7ff3f4-6fe8-11e8-9985-4a59cbaca5df.png">
<img width="698" alt="screen shot 2018-06-14 at 3 32 27 pm" src="https://user-images.githubusercontent.com/37029239/41436787-5a9b9492-6fe8-11e8-911b-4ff1e75bd8ef.png">
