### ISSUE TITLE
is there a reason why the display precision on axes cannot be smaller than 1? sometimes, it makes sense to have 0.

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1203]
1.set precision=0 automatically when an integer number display on map/plot/axis
2.allow user set display precision to 0

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
Verified 

<img width="449" alt="12 mar 11" src="https://user-images.githubusercontent.com/36253697/37312547-557abb76-2643-11e8-8ce3-1d0e5f436295.PNG">

![12 mar 10](https://user-images.githubusercontent.com/36253697/37312551-5a69aa98-2643-11e8-8c7b-9f458867fbba.JPG)

<img width="375" alt="12 mar 09" src="https://user-images.githubusercontent.com/36253697/37312558-5e812070-2643-11e8-89dd-a480dfc6589f.PNG">

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v113
OSX
