### ISSUE TITLE
category editor broken from toolbar icon

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1204]
When invoking the category editor from the toolbar icon, the dialog appears, but it does not have the initial box where a name for the category should be filled in. No reaction to any clicks. This is broken.

**Comment by lanselin** [comment]
OK, not broken, but not intuitive. Click on New starts the process, but the New button is not distinct in any way. In any case, I suggest having the interface being the same for the toolbar icon and invoking from the options menu makes more sense.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
Verified 

<img width="547" alt="12 mar 08" src="https://user-images.githubusercontent.com/36253697/37312164-e18886b8-2641-11e8-9f7d-f25a6ae0de48.PNG">

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v111
OSX
