### ISSUE TITLE
custom categories not available from map menu

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1205]
After creating a custom category, it can only be invoked from a current map, using the options menu (right click on a current map and Change Current Map Type). However, it cannot be invoked from the map menu or the map icon. So, there is a bit of a disconnect here, where one first needs to make a map in a different classification before the custom classification can be called up. I think it would be more logical if the Create New Custom (and any created custom categories) were also listed at the bottom of the map menu and the list provided from the map icon.

**Comment by lixun910** [comment]
This fix has  14 changed files with 1,880 additions and 2,926 deletions. 
Many redundant code has been removed and replaced with simple logic. So testing needs to be focused on all related maps and plots:
Maps and Rates, Conditional Maps/Histogram, Cartogram, Histogram, Bubble Chart, PCP,

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.43
The feature works fine when accessed from the Maps menu
![image](https://user-images.githubusercontent.com/22801047/32693873-e6e1504e-c6f7-11e7-93f7-0e98b79f497b.png)
![image](https://user-images.githubusercontent.com/22801047/32693876-fa068996-c6f7-11e7-8781-8da18147e079.png)

Will update as I do more testing.

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.43
GeoDa keeps custom breaks that were created in a session, even after opening/closing individual files. 
Open Guerry 
Create custom breaks for the "suicids" variable
Click Map > Custom Breaks > Custom Breaks (suicids)
clicking does not generate a dialog or anything. GeoDa is unresponsive.
![image](https://user-images.githubusercontent.com/22801047/32693903-d4bf6bc0-c6f8-11e7-9b5a-3875c0cdc74c.png)

**Comment by lixun910** [comment]
@YidanJ-Wu Thanks for finding this!! Just fixed this in 1.45.

**Comment by luluzhou766** [comment]
Win 10, 64bit
Geoda 1.12.1.131
Verified

I created a custom break in Guerry, saved the project, closed project.
Then opened US  Homicides data.
There is no custom break left from Guerry.

**Comment by YidanJ-Wu** [comment]
Windows 8 
GeoDa 1.12.1.131

Looks like closing Geoda clears the custom breaks. If you just close Guerry, but don't close GeoDa, it retains the custom breaks.

**Comment by lixun910** [comment]
Yes. The custom breaks should be saved in the gda project file. When you close current project, and open the saved gda file, the custom breaks should be loaded.

**Comment by YidanJ-Wu** [comment]
Windows 8 
1.12.1.13

- Create a custom break in GeoDa.
- Save project file
- Exit and reopen GeoDa
- Custom break not visible: 
![image](https://user-images.githubusercontent.com/22801047/39727580-e1874cfa-5218-11e8-87e7-35d08b777695.png)

**Comment by lixun910** [comment]
Did you reopen the gda file?

**Comment by jkoschinsky** [comment]
@YidanJ-Wu

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.137

- Open Guerry
- Create custom breaks for the "suicids" variable
- Save project
- Close Guerry
- Open Guerry
- Click Map > Custom Breaks > Custom Breaks (suicids)
- GeoDa is unresponsive, no plot is created

**Comment by VeraB620** [comment]
When I reopen Guerry and go to Custom Breaks (suicids) this opens:

<img width="801" alt="screen shot 2018-07-09 at 1 49 56 pm" src="https://user-images.githubusercontent.com/4943475/42470162-406f90be-837f-11e8-8f06-6d5de5088ce3.png">

when variables are selected:
<img width="1195" alt="screen shot 2018-07-09 at 1 50 13 pm" src="https://user-images.githubusercontent.com/4943475/42470172-47e78a04-837f-11e8-90f0-50af89dd3cca.png">
<img width="1194" alt="screen shot 2018-07-09 at 1 49 36 pm" src="https://user-images.githubusercontent.com/4943475/42470173-48d146f8-837f-11e8-91cd-44cb2428a8bb.png">

Then I closed the project and opened Columbus Crime. I was still able to Click Map > Custom Breaks > Custom Breaks (suicids) but it was unresponsive.
<img width="741" alt="screen shot 2018-07-09 at 1 55 02 pm" src="https://user-images.githubusercontent.com/4943475/42470387-e5da1894-837f-11e8-8029-034d73c589b2.png">
