### ISSUE TITLE
box map with hinges inconsistent menu items

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1210]
The way the box map is invoked from the options menu and from the main map menu is not consistent. In one, both hinge options are in the list, in the other, there is an extra click required to get the hinge.

<img width="328" alt="screen shot 2017-10-17 at 6 58 09 am" src="https://user-images.githubusercontent.com/4008351/31692542-c509b8e0-b35f-11e7-939b-690df3c19dfb.png">
<img width="233" alt="screen shot 2017-10-17 at 6 58 19 am" src="https://user-images.githubusercontent.com/4008351/31692547-c78b5754-b35f-11e7-82c5-11c1d0b2b089.png">

**Comment by lanselin** [comment]
works on mac version 1.12.1.25

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
Verified 
![12 mar 06](https://user-images.githubusercontent.com/36253697/37311616-dff4d790-263f-11e8-8d3e-9e37787c1aa9.JPG)
![12 mar 07](https://user-images.githubusercontent.com/36253697/37311627-e57e5024-263f-11e8-968f-48ebf28b15dc.JPG)

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v111
OSX
