### ISSUE TITLE
correlogram -- no way to turn off statistics

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1211]
The default for the spatial correlogram has all kinds of statistics at the bottom. This did not use to be the case. The default used to be the histogram with no statistics at all. This would be fine if there were a way to turn the statistics off, but there isn't. I suggest the default should be as before, without all the statistics, and the View > Display statistics added as one of the options 

<img width="807" alt="screen shot 2017-10-17 at 9 21 22 pm" src="https://user-images.githubusercontent.com/4008351/31698148-81a8599a-b381-11e7-8efb-920d99330afe.png">
<img width="184" alt="screen shot 2017-10-17 at 9 23 30 pm" src="https://user-images.githubusercontent.com/4008351/31698155-85332040-b381-11e7-91c8-1604127b4683.png">

**Comment by lanselin** [comment]
works on mac version 1.12.1.25

**Comment by YidanJ-Wu** [comment]
Windows 1.12.1.29
Verified 
![image](https://user-images.githubusercontent.com/22801047/32128740-0172c2fc-bb46-11e7-9171-6667ef669d86.png)
![image](https://user-images.githubusercontent.com/22801047/32128743-0aa10f6e-bb46-11e7-9484-28a8311a4e63.png)

**Comment by VeraB620** [comment]
OS El Capitan 10.11.5
My default is _without_ statistics, not sure which the default should be.
However, displaying statistics does work
<img width="1031" alt="screen shot 2018-06-26 at 9 00 05 am" src="https://user-images.githubusercontent.com/4943475/41917247-8309fabe-791f-11e8-9ddc-ed145b25e4ec.png">
<img width="639" alt="screen shot 2018-06-26 at 8 59 28 am" src="https://user-images.githubusercontent.com/4943475/41917248-867a6670-791f-11e8-9a38-4581f16a693d.png">
