### ISSUE TITLE
Crash Report: HCluster in Ubuntu

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1213]
From: 
 Details:
os: 3-4-10
vs: 1-12-0-0
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/media/alain/USB2/TD2/GEOFLA_COMMUNE/COMMUNE.shp
Open Layer:COMMUNE
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/media/alain/USB2/TD2/GEOFLA_COMMUNE/COMMUNE.shp
Project::SetupEncoding()
1252
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
POPULATION
X_CHF_LIEU
Open CartogramNewFrame.
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Project::GetVoronoiRookNeighborGal()
Project::GetVoronoiRookNeighborMap()
Project::IsPointDuplicates()
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
In CartogramNewFrame::OnActivate()
In CartogramNewFrame::OnActivate()
In CartogramNewFrame::OnMapZoom()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
POPULATION
Open HistogramFrame.
In HistogramFrame::OnActivate()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
POPULATION
X_CENTROID
Y_CHF_LIEU
Y_CHF_LIEU
Open ScatterNewPlotFrame.
Open LisaMapFrame (OnOpenDiffLisa).
In TableFrame::OnActivate
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
Click CreatingWeightDlg::OnIdVariableSelected
selected:0
Click CreatingWeightDlg::OnCRadioRookSelected
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/home/alain/Téléchargements/COMMUNE.gal
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnActivate
WeightsManFrame::OnHistogramBtn()
Open ConnectivityHistFrame
In WeightsManFrame::OnActivate
ConnectivityHistFrame::OnActivate
In WeightsManFrame::OnActivate
WeightsManFrame::OnConnectMapBtn()
Open ConnectivityMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In WeightsManFrame::OnActivate
In ConnectivityMapFrame::OnActivate
Click GdaFrame::OnFitToWindowMode
MapCanvas::~MapCanvas()
In WeightsManFrame::OnActivate
Open DataMovieDlg.
Entering DataMovieDlg::OnFieldChoice
DataMovieDlg::OnPlayPauseButton
DataMovieDlg::OnPlayPauseButton
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
In DataMovieDlg::OnMoveSpeedSlider
DataMovieDlg::OnPlayPauseButton
Close DataMovieDlg::OnClose
MapCanvas::~MapCanvas()
Open AbstractClusterDlg.
Open HClusterDlg.
InitVariableCombobox HClusterDlg.
Click HClusterDlg::OnOK
Click HClusterDlg::OnOK
Project::GetCentroids()

**Comment by lixun910** [comment]
same with #1251
