### ISSUE TITLE
Correlogram: add random seed option to replicate results

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1217]

**Comment by lanselin** [comment]
works on mac version 1.12.1.25

**Comment by YidanJ-Wu** [comment]
Windows 1.12.1.29 
Verified
![image](https://user-images.githubusercontent.com/22801047/32128766-4d12999e-bb46-11e7-84c0-7dadbf8f0f28.png)

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.137
Verified

<img width="313" alt="screen shot 2018-06-19 at 12 11 01 pm" src="https://user-images.githubusercontent.com/37029239/41613021-11890f5c-73ba-11e8-9030-cf03a5d5dcf5.png">
<img width="1173" alt="screen shot 2018-06-19 at 12 10 12 pm" src="https://user-images.githubusercontent.com/37029239/41613022-11960522-73ba-11e8-91b8-8860289ced9f.png">
