### ISSUE TITLE
Crash Report: w/data -- pls try replicating

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1221]
From: 
 Details:
os: 1-10-12
vs: 1-12-0-0
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/alokikmishra/Desktop/Classes/Sem1/GIS/MidTerm/ZCTA_2010Census_DP1/Question2_Midterm_final.shp
Open Layer:Question2_Midterm_final
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/alokikmishra/Desktop/Classes/Sem1/GIS/MidTerm/ZCTA_2010Census_DP1/Question2_Midterm_final.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnCreateNewIdClick
Try to insert unique id (integer, POLY_ID) column in table.
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnCRadioQueenSelected
Click CreatingWeightDlg::OnCreateClick
In WeightsManFrame::OnActivate
CreateWeights()/Users/alokikmishra/Desktop/Classes/Sem1/GIS/MidTerm/ZCTA_2010Census_DP1/Question2_Midterm_final.gal
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnActivate
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Count_Drug
VariableSettingsDlg::GetWeightsId() weight: Question2_Midterm_final
VariableSettingsDlg::GetWeightsId() weight: Question2_Midterm_final
Entering LisaCoordinator::LisaCoordinator().
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
Entering LisaCoordinator::InitFromVarInfo()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Entering LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::CalcLisa()
Entering LisaCoordinator::CalcPseudoP()
Entering LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP()
Exiting LisaCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
In LisaCoordinator::registerObserver()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
In GdaFrame::OnSaveLisa()
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Entering LisaCoordinator::removeObserver
Exiting LisaCoordinator::removeObserver
MapCanvas::~MapCanvas()
Entering LisaCoordinator::removeObserver
Exiting LisaCoordinator::removeObserver
Entering LisaCoordinator::removeObserver
In LisaCoordinator::~LisaCoordinator().
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::removeObserver
MapCanvas::~MapCanvas()
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Count_Weap
VariableSettingsDlg::GetWeightsId() weight: Question2_Midterm_final
VariableSettingsDlg::GetWeightsId() weight: Question2_Midterm_final
Entering LisaCoordinator::LisaCoordinator().
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
Entering LisaCoordinator::InitFromVarInfo()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Entering LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::CalcLisa()
Entering LisaCoordinator::CalcPseudoP()
Entering LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP()
Exiting LisaCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
In LisaCoordinator::registerObserver()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
In GdaFrame::OnSaveLisa()
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Entering LisaCoordinator::removeObserver
Exiting LisaCoordinator::removeObserver
MapCanvas::~MapCanvas()
Entering LisaCoordinator::removeObserver
Exiting LisaCoordinator::removeObserver
Entering LisaCoordinator::removeObserver
In LisaCoordinator::~LisaCoordinator().
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::removeObserver
MapCanvas::~MapCanvas()
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Count_Robb
VariableSettingsDlg::GetWeightsId() weight: Question2_Midterm_final
VariableSettingsDlg::GetWeightsId() weight: Question2_Midterm_final
Entering LisaCoordinator::LisaCoordinator().
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
Entering LisaCoordinator::InitFromVarInfo()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Entering LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::CalcLisa()
Entering LisaCoordinator::CalcPseudoP()
Entering LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP()
Exiting LisaCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
In LisaCoordinator::registerObserver()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
In GdaFrame::OnSaveLisa()
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Entering LisaCoordinator::removeObserver
Exiting LisaCoordinator::removeObserver
MapCanvas::~MapCanvas()
Entering LisaCoordinator::removeObserver
Exiting LisaCoordinator::removeObserver
Entering LisaCoordinator::removeObserver
In LisaCoordinator::~LisaCoordinator().
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::removeObserver
MapCanvas::~MapCanvas()
Click GdaFrame::OnSaveProject
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs
New Datasource Name:/Users/alokikmishra/Desktop/Classes/Sem1/GIS/MidTerm/ZCTA_2010Census_DP1/GdaTmp_Question2_Midterm_final.shp
Project::GetSpatialReference()
Project::GetGdaGeometries()
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
POLY_ID
ScrolledWidgetsPane::IsFieldNameValid
ZCTA5CE10
ScrolledWidgetsPane::IsFieldNameValid
GEOID10
ScrolledWidgetsPane::IsFieldNameValid
ALAND10
ScrolledWidgetsPane::IsFieldNameValid
AWATER10
ScrolledWidgetsPane::IsFieldNameValid
INTPTLAT10
ScrolledWidgetsPane::IsFieldNameValid
INTPTLON10
ScrolledWidgetsPane::IsFieldNameValid
DP0010001
ScrolledWidgetsPane::IsFieldNameValid
DP0010002
ScrolledWidgetsPane::IsFieldNameValid
DP0010003
ScrolledWidgetsPane::IsFieldNameValid
DP0010004
ScrolledWidgetsPane::IsFieldNameValid
DP0010005
ScrolledWidgetsPane::IsFieldNameValid
DP0010006
ScrolledWidgetsPane::IsFieldNameValid
DP0010007
ScrolledWidgetsPane::IsFieldNameValid
DP0010008
ScrolledWidgetsPane::IsFieldNameValid
DP0010009
ScrolledWidgetsPane::IsFieldNameValid
DP0010010
ScrolledWidgetsPane::IsFieldNameValid
DP0010011
ScrolledWidgetsPane::IsFieldNameValid
DP0010012
ScrolledWidgetsPane::IsFieldNameValid
DP0010013
ScrolledWidgetsPane::IsFieldNameValid
DP0010014
ScrolledWidgetsPane::IsFieldNameValid
DP0010015
ScrolledWidgetsPane::IsFieldNameValid
DP0010016
ScrolledWidgetsPane::IsFieldNameValid
DP0010017
ScrolledWidgetsPane::IsFieldNameValid
DP0010018
ScrolledWidgetsPane::IsFieldNameValid
DP0010019
ScrolledWidgetsPane::IsFieldNameValid
DP0010020
ScrolledWidgetsPane::IsFieldNameValid
DP0010021
ScrolledWidgetsPane::IsFieldNameValid
DP0010022
ScrolledWidgetsPane::IsFieldNameValid
DP0010023
ScrolledWidgetsPane::IsFieldNameValid
DP0010024
ScrolledWidgetsPane::IsFieldNameValid
DP0010025
ScrolledWidgetsPane::IsFieldNameValid
DP0010026
ScrolledWidgetsPane::IsFieldNameValid
DP0010027
ScrolledWidgetsPane::IsFieldNameValid
DP0010028
ScrolledWidgetsPane::IsFieldNameValid
DP0010029
ScrolledWidgetsPane::IsFieldNameValid
DP0010030
ScrolledWidgetsPane::IsFieldNameValid
DP0010031
ScrolledWidgetsPane::IsFieldNameValid
DP0010032
ScrolledWidgetsPane::IsFieldNameValid
DP0010033
ScrolledWidgetsPane::IsFieldNameValid
DP0010034
ScrolledWidgetsPane::IsFieldNameValid
DP0010035
ScrolledWidgetsPane::IsFieldNameValid
DP0010036
ScrolledWidgetsPane::IsFieldNameValid
DP0010037
ScrolledWidgetsPane::IsFieldNameValid
DP0010038
ScrolledWidgetsPane::IsFieldNameValid
DP0010039
ScrolledWidgetsPane::IsFieldNameValid
DP0010040
ScrolledWidgetsPane::IsFieldNameValid
DP0010041
ScrolledWidgetsPane::IsFieldNameValid
DP0010042
ScrolledWidgetsPane::IsFieldNameValid
DP0010043
ScrolledWidgetsPane::IsFieldNameValid
DP0010044
ScrolledWidgetsPane::IsFieldNameValid
DP0010045
ScrolledWidgetsPane::IsFieldNameValid
DP0010046
ScrolledWidgetsPane::IsFieldNameValid
DP0010047
ScrolledWidgetsPane::IsFieldNameValid
DP0010048
ScrolledWidgetsPane::IsFieldNameValid
DP0010049
ScrolledWidgetsPane::IsFieldNameValid
DP0010050
ScrolledWidgetsPane::IsFieldNameValid
DP0010051
ScrolledWidgetsPane::IsFieldNameValid
DP0010052
ScrolledWidgetsPane::IsFieldNameValid
DP0010053
ScrolledWidgetsPane::IsFieldNameValid
DP0010054
ScrolledWidgetsPane::IsFieldNameValid
DP0010055
ScrolledWidgetsPane::IsFieldNameValid
DP0010056
ScrolledWidgetsPane::IsFieldNameValid
DP0010057
ScrolledWidgetsPane::IsFieldNameValid
DP0020001
ScrolledWidgetsPane::IsFieldNameValid
DP0020002
ScrolledWidgetsPane::IsFieldNameValid
DP0020003
ScrolledWidgetsPane::IsFieldNameValid
DP0030001
ScrolledWidgetsPane::IsFieldNameValid
DP0030002
ScrolledWidgetsPane::IsFieldNameValid
DP0030003
ScrolledWidgetsPane::IsFieldNameValid
DP0040001
ScrolledWidgetsPane::IsFieldNameValid
DP0040002
ScrolledWidgetsPane::IsFieldNameValid
DP0040003
ScrolledWidgetsPane::IsFieldNameValid
DP0050001
ScrolledWidgetsPane::IsFieldNameValid
DP0050002
ScrolledWidgetsPane::IsFieldNameValid
DP0050003
ScrolledWidgetsPane::IsFieldNameValid
DP0060001
ScrolledWidgetsPane::IsFieldNameValid
DP0060002
ScrolledWidgetsPane::IsFieldNameValid
DP0060003
ScrolledWidgetsPane::IsFieldNameValid
DP0070001
ScrolledWidgetsPane::IsFieldNameValid
DP0070002
ScrolledWidgetsPane::IsFieldNameValid
DP0070003
ScrolledWidgetsPane::IsFieldNameValid
DP0080001
ScrolledWidgetsPane::IsFieldNameValid
DP0080002
ScrolledWidgetsPane::IsFieldNameValid
DP0080003
ScrolledWidgetsPane::IsFieldNameValid
DP0080004
ScrolledWidgetsPane::IsFieldNameValid
DP0080005
ScrolledWidgetsPane::IsFieldNameValid
DP0080006
ScrolledWidgetsPane::IsFieldNameValid
DP0080007
ScrolledWidgetsPane::IsFieldNameValid
DP0080008
ScrolledWidgetsPane::IsFieldNameValid
DP0080009
ScrolledWidgetsPane::IsFieldNameValid
DP0080010
ScrolledWidgetsPane::IsFieldNameValid
DP0080011
ScrolledWidgetsPane::IsFieldNameValid
DP0080012
ScrolledWidgetsPane::IsFieldNameValid
DP0080013
ScrolledWidgetsPane::IsFieldNameValid
DP0080014
ScrolledWidgetsPane::IsFieldNameValid
DP0080015
ScrolledWidgetsPane::IsFieldNameValid
DP0080016
ScrolledWidgetsPane::IsFieldNameValid
DP0080017
ScrolledWidgetsPane::IsFieldNameValid
DP0080018
ScrolledWidgetsPane::IsFieldNameValid
DP0080019
ScrolledWidgetsPane::IsFieldNameValid
DP0080020
ScrolledWidgetsPane::IsFieldNameValid
DP0080021
ScrolledWidgetsPane::IsFieldNameValid
DP0080022
ScrolledWidgetsPane::IsFieldNameValid
DP0080023
ScrolledWidgetsPane::IsFieldNameValid
DP0080024
ScrolledWidgetsPane::IsFieldNameValid
DP0090001
ScrolledWidgetsPane::IsFieldNameValid
DP0090002
ScrolledWidgetsPane::IsFieldNameValid
DP0090003
ScrolledWidgetsPane::IsFieldNameValid
DP0090004
ScrolledWidgetsPane::IsFieldNameValid
DP0090005
ScrolledWidgetsPane::IsFieldNameValid
DP0090006
ScrolledWidgetsPane::IsFieldNameValid
DP0100001
ScrolledWidgetsPane::IsFieldNameValid
DP0100002
ScrolledWidgetsPane::IsFieldNameValid
DP0100003
ScrolledWidgetsPane::IsFieldNameValid
DP0100004
ScrolledWidgetsPane::IsFieldNameValid
DP0100005
ScrolledWidgetsPane::IsFieldNameValid
DP0100006
ScrolledWidgetsPane::IsFieldNameValid
DP0100007
ScrolledWidgetsPane::IsFieldNameValid
DP0110001
ScrolledWidgetsPane::IsFieldNameValid
DP0110002
ScrolledWidgetsPane::IsFieldNameValid
DP0110003
ScrolledWidgetsPane::IsFieldNameValid
DP0110004
ScrolledWidgetsPane::IsFieldNameValid
DP0110005
ScrolledWidgetsPane::IsFieldNameValid
DP0110006
ScrolledWidgetsPane::IsFieldNameValid
DP0110007
ScrolledWidgetsPane::IsFieldNameValid
DP0110008
ScrolledWidgetsPane::IsFieldNameValid
DP0110009
ScrolledWidgetsPane::IsFieldNameValid
DP0110010
ScrolledWidgetsPane::IsFieldNameValid
DP0110011
ScrolledWidgetsPane::IsFieldNameValid
DP0110012
ScrolledWidgetsPane::IsFieldNameValid
DP0110013
ScrolledWidgetsPane::IsFieldNameValid
DP0110014
ScrolledWidgetsPane::IsFieldNameValid
DP0110015
ScrolledWidgetsPane::IsFieldNameValid
DP0110016
ScrolledWidgetsPane::IsFieldNameValid
DP0110017
ScrolledWidgetsPane::IsFieldNameValid
DP0120001
ScrolledWidgetsPane::IsFieldNameValid
DP0120002
ScrolledWidgetsPane::IsFieldNameValid
DP0120003
ScrolledWidgetsPane::IsFieldNameValid
DP0120004
ScrolledWidgetsPane::IsFieldNameValid
DP0120005
ScrolledWidgetsPane::IsFieldNameValid
DP0120006
ScrolledWidgetsPane::IsFieldNameValid
DP0120007
ScrolledWidgetsPane::IsFieldNameValid
DP0120008
ScrolledWidgetsPane::IsFieldNameValid
DP0120009
ScrolledWidgetsPane::IsFieldNameValid
DP0120010
ScrolledWidgetsPane::IsFieldNameValid
DP0120011
ScrolledWidgetsPane::IsFieldNameValid
DP0120012
ScrolledWidgetsPane::IsFieldNameValid
DP0120013
ScrolledWidgetsPane::IsFieldNameValid
DP0120014
ScrolledWidgetsPane::IsFieldNameValid
DP0120015
ScrolledWidgetsPane::IsFieldNameValid
DP0120016
ScrolledWidgetsPane::IsFieldNameValid
DP0120017
ScrolledWidgetsPane::IsFieldNameValid
DP0120018
ScrolledWidgetsPane::IsFieldNameValid
DP0120019
ScrolledWidgetsPane::IsFieldNameValid
DP0120020
ScrolledWidgetsPane::IsFieldNameValid
DP0130001
ScrolledWidgetsPane::IsFieldNameValid
DP0130002
ScrolledWidgetsPane::IsFieldNameValid
DP0130003
ScrolledWidgetsPane::IsFieldNameValid
DP0130004
ScrolledWidgetsPane::IsFieldNameValid
DP0130005
ScrolledWidgetsPane::IsFieldNameValid
DP0130006
ScrolledWidgetsPane::IsFieldNameValid
DP0130007
ScrolledWidgetsPane::IsFieldNameValid
DP0130008
ScrolledWidgetsPane::IsFieldNameValid
DP0130009
ScrolledWidgetsPane::IsFieldNameValid
DP0130010
ScrolledWidgetsPane::IsFieldNameValid
DP0130011
ScrolledWidgetsPane::IsFieldNameValid
DP0130012
ScrolledWidgetsPane::IsFieldNameValid
DP0130013
ScrolledWidgetsPane::IsFieldNameValid
DP0130014
ScrolledWidgetsPane::IsFieldNameValid
DP0130015
ScrolledWidgetsPane::IsFieldNameValid
DP0140001
ScrolledWidgetsPane::IsFieldNameValid
DP0150001
ScrolledWidgetsPane::IsFieldNameValid
DP0160001
ScrolledWidgetsPane::IsFieldNameValid
DP0170001
ScrolledWidgetsPane::IsFieldNameValid
DP0180001
ScrolledWidgetsPane::IsFieldNameValid
DP0180002
ScrolledWidgetsPane::IsFieldNameValid
DP0180003
ScrolledWidgetsPane::IsFieldNameValid
DP0180004
ScrolledWidgetsPane::IsFieldNameValid
DP0180005
ScrolledWidgetsPane::IsFieldNameValid
DP0180006
ScrolledWidgetsPane::IsFieldNameValid
DP0180007
ScrolledWidgetsPane::IsFieldNameValid
DP0180008
ScrolledWidgetsPane::IsFieldNameValid
DP0180009
ScrolledWidgetsPane::IsFieldNameValid
DP0190001
ScrolledWidgetsPane::IsFieldNameValid
DP0200001
ScrolledWidgetsPane::IsFieldNameValid
DP0210001
ScrolledWidgetsPane::IsFieldNameValid
DP0210002
ScrolledWidgetsPane::IsFieldNameValid
DP0210003
ScrolledWidgetsPane::IsFieldNameValid
DP0220001
ScrolledWidgetsPane::IsFieldNameValid
DP0220002
ScrolledWidgetsPane::IsFieldNameValid
DP0230001
ScrolledWidgetsPane::IsFieldNameValid
DP0230002
ScrolledWidgetsPane::IsFieldNameValid
Shape_Leng
ScrolledWidgetsPane::IsFieldNameValid
Shape_Area
ScrolledWidgetsPane::IsFieldNameValid
zcta
ScrolledWidgetsPane::IsFieldNameValid
bcode
ScrolledWidgetsPane::IsFieldNameValid
note
ScrolledWidgetsPane::IsFieldNameValid
pctownocc
ScrolledWidgetsPane::IsFieldNameValid
pct_family
ScrolledWidgetsPane::IsFieldNameValid
pct_retire
ScrolledWidgetsPane::IsFieldNameValid
sumCMPLNT_
ScrolledWidgetsPane::IsFieldNameValid
meanCMPLNT
ScrolledWidgetsPane::IsFieldNameValid
minCMPLNT_
ScrolledWidgetsPane::IsFieldNameValid
maxCMPLNT_
ScrolledWidgetsPane::IsFieldNameValid
medianCMPL
ScrolledWidgetsPane::IsFieldNameValid
sumKY_CD
ScrolledWidgetsPane::IsFieldNameValid
meanKY_CD
ScrolledWidgetsPane::IsFieldNameValid
minKY_CD
ScrolledWidgetsPane::IsFieldNameValid
maxKY_CD
ScrolledWidgetsPane::IsFieldNameValid
medianKY_C
ScrolledWidgetsPane::IsFieldNameValid
sumPD_CD
ScrolledWidgetsPane::IsFieldNameValid
meanPD_CD
ScrolledWidgetsPane::IsFieldNameValid
minPD_CD
ScrolledWidgetsPane::IsFieldNameValid
maxPD_CD
ScrolledWidgetsPane::IsFieldNameValid
medianPD_C
ScrolledWidgetsPane::IsFieldNameValid
sumADDR_PC
ScrolledWidgetsPane::IsFieldNameValid
meanADDR_P
ScrolledWidgetsPane::IsFieldNameValid
minADDR_PC
ScrolledWidgetsPane::IsFieldNameValid
maxADDR_PC
ScrolledWidgetsPane::IsFieldNameValid
medianADDR
ScrolledWidgetsPane::IsFieldNameValid
sumLatitud
ScrolledWidgetsPane::IsFieldNameValid
meanLatitu
ScrolledWidgetsPane::IsFieldNameValid
minLatitud
ScrolledWidgetsPane::IsFieldNameValid
maxLatitud
ScrolledWidgetsPane::IsFieldNameValid
medianLati
ScrolledWidgetsPane::IsFieldNameValid
sumLongitu
ScrolledWidgetsPane::IsFieldNameValid
meanLongit
ScrolledWidgetsPane::IsFieldNameValid
minLongitu
ScrolledWidgetsPane::IsFieldNameValid
maxLongitu
ScrolledWidgetsPane::IsFieldNameValid
medianLong
ScrolledWidgetsPane::IsFieldNameValid
count
ScrolledWidgetsPane::IsFieldNameValid
Count_Drug
ScrolledWidgetsPane::IsFieldNameValid
Count_Weap
ScrolledWidgetsPane::IsFieldNameValid
Count_Robb
ScrolledWidgetsPane::IsFieldNameValid
LISA_Drug_index
ScrolledWidgetsPane::IsFieldNameValid
LISA_Drug_Clusters
ScrolledWidgetsPane::IsFieldNameValid
LISA_Drug_Significance
ScrolledWidgetsPane::IsFieldNameValid
LISA_Weapons_I
ScrolledWidgetsPane::IsFieldNameValid
LISA_Weapons_Cluster
ScrolledWidgetsPane::IsFieldNameValid
LISA_Weapons_Significance
ScrolledWidgetsPane::IsFieldNameValid
LISA_Robb_I
ScrolledWidgetsPane::IsFieldNameValid
LISA_Robb_Clusters
ScrolledWidgetsPane::IsFieldNameValid
LISA_Robb_Significance
ScrolledWidgetsPane::RemoveIllegalChars
LISA_Drug_index
LISA_Drug_index
ScrolledWidgetsPane::TruncateFieldName
LISA_Drug_index
LISA__ndex
ScrolledWidgetsPane::RenameDupFieldName
LISA__ndex
LISA__ndex
ScrolledWidgetsPane::RemoveIllegalChars
LISA_Drug_Clusters
LISA_Drug_Clusters
ScrolledWidgetsPane::TruncateFieldName
LISA_Drug_Clusters
LISA__ters
ScrolledWidgetsPane::RenameDupFieldName
LISA__ters
LISA__ters
ScrolledWidgetsPane::RemoveIllegalChars
LISA_Drug_Significance
LISA_Drug_Significance
ScrolledWidgetsPane::TruncateFieldName
LISA_Drug_Significance
LISA__ance
ScrolledWidgetsPane::RenameDupFieldName
LISA__ance
LISA__ance
ScrolledWidgetsPane::RemoveIllegalChars
LISA_Weapons_I
LISA_Weapons_I
ScrolledWidgetsPane::TruncateFieldName
LISA_Weapons_I
LISA__ns_I
ScrolledWidgetsPane::RenameDupFieldName
LISA__ns_I
LISA__ns_I
ScrolledWidgetsPane::RemoveIllegalChars
LISA_Weapons_Cluster
LISA_Weapons_Cluster
ScrolledWidgetsPane::TruncateFieldName
LISA_Weapons_Cluster
LISA__ster
ScrolledWidgetsPane::RenameDupFieldName
LISA__ster
LISA__ster
ScrolledWidgetsPane::RemoveIllegalChars
LISA_Weapons_Significance
LISA_Weapons_Significance
ScrolledWidgetsPane::TruncateFieldName
LISA_Weapons_Significance
LISA__ance
ScrolledWidgetsPane::RenameDupFieldName
LISA__ance
ScrolledWidgetsPane::TruncateFieldName
LISA__ance
LISA_nce
LISA_nce_1
ScrolledWidgetsPane::RemoveIllegalChars
LISA_Robb_I
LISA_Robb_I
ScrolledWidgetsPane::TruncateFieldName
LISA_Robb_I
LISA__bb_I
ScrolledWidgetsPane::RenameDupFieldName
LISA__bb_I
LISA__bb_I
ScrolledWidgetsPane::RemoveIllegalChars
LISA_Robb_Clusters
LISA_Robb_Clusters
ScrolledWidgetsPane::TruncateFieldName
LISA_Robb_Clusters
LISA__ters
ScrolledWidgetsPane::RenameDupFieldName
LISA__ters
ScrolledWidgetsPane::TruncateFieldName
LISA__ters
LISA_ers
LISA_ers_1
ScrolledWidgetsPane::RemoveIllegalChars
LISA_Robb_Significance
LISA_Robb_Significance
ScrolledWidgetsPane::TruncateFieldName
LISA_Robb_Significance
LISA__ance
ScrolledWidgetsPane::RenameDupFieldName
LISA__ance
ScrolledWidgetsPane::TruncateFieldName
LISA__ance
LISA_nce
LISA_nce_2
Click FieldNameCorrectionDlg::OnCancelClick
Exit FieldNameCorrectionDlg

**Comment by lixun910** [comment]
I was able to find the datasource: https://www2.census.gov/geo/tiger/TIGER2010DP1/ZCTA_2010Census_DP1.zip

**Comment by jkoschinsky** [comment]
@DarcyLinde 
please try replicating with the data above:

1. run LISA
2. right-click: save results
3. save as new shapefile

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.193 (macOS Mojave, 10.14.1). Jan. 24 build.

Followed the same steps with same data (also merged this dataset with external zipcode level dataset with missings), long variable names. Can't replicate this crash. But the dataset is big and GeoDa becomes slow.
