### ISSUE TITLE
scatter plot doesn't recognized time grouped variables

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1222]
The scatter plot variable selection of the same variable for two different periods is not reflected in a correct plot. For example, selecting yrhom for 2002 as the x variable and yrhom for 2005 as the y variable yields a plot of 2002 on 2002, of course a perfect fit. The time period specified for the y variable doesn't seem to be recognized.

<img width="402" alt="screen shot 2017-10-22 at 9 34 33 am" src="https://user-images.githubusercontent.com/4008351/31862969-b9b58432-b70c-11e7-9cba-f4ac31a66933.png">
<img width="497" alt="screen shot 2017-10-22 at 9 34 44 am" src="https://user-images.githubusercontent.com/4008351/31862971-bf60bd8e-b70c-11e7-83e6-bf5857e40cfd.png">

**Comment by lanselin** [comment]
Apparently, this was broken in version 1.10.1.15 of 8/11, in 1.10.1.13 it works fine.

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.29
Verified
![image](https://user-images.githubusercontent.com/22801047/32128689-b7a7647a-bb45-11e7-8140-4497164b4e6a.png)

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.137
Verified

<img width="495" alt="screen shot 2018-06-15 at 3 48 34 pm" src="https://user-images.githubusercontent.com/37029239/41488910-a62db7ac-70b3-11e8-99e2-5017bdf189f6.png">
<img width="394" alt="screen shot 2018-06-15 at 3 48 15 pm" src="https://user-images.githubusercontent.com/37029239/41488911-a665eb86-70b3-11e8-9892-9146e72f17fa.png">
