### ISSUE TITLE
time enabled scatter plot ignores fixed axes setting

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1223]
In version 1.10.1.13, where the time enabled scatter plot still works, the fixed axes setting seems to be ignored. For example, the two scatter plots below look exactly the same with and without the fixed axes setting checked. I would expect the axes extent to remain exactly the same (as is the case for a box plot, for example), but it does not.

<img width="599" alt="screen shot 2017-10-22 at 11 28 38 am" src="https://user-images.githubusercontent.com/4008351/31864041-91bf2d4c-b71c-11e7-8636-b654a4cbe9c6.png">
<img width="600" alt="screen shot 2017-10-22 at 11 28 53 am" src="https://user-images.githubusercontent.com/4008351/31864043-94d4b1a0-b71c-11e7-9865-b479ccac670f.png">

**Comment by lanselin** [comment]
The same issue also applies to the bivariate moran scatter plot. The time period for the second variable is ignored. For example, HR 80 is specified (with time as 1980), but HR 60 is used.

<img width="394" alt="screen shot 2017-10-22 at 6 40 05 pm" src="https://user-images.githubusercontent.com/4008351/31867623-b75e597e-b758-11e7-948b-15038e29907f.png">

<img width="599" alt="screen shot 2017-10-22 at 6 40 15 pm" src="https://user-images.githubusercontent.com/4008351/31867625-bbcb1dbc-b758-11e7-9828-5a7747fbcdfb.png">

**Comment by lanselin** [comment]
works correctly in version 1.10.1.13

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.29
Is this referring to the Time Player? 
I grouped POPMW68, POPMW78, POPMW88 as POPMW. Then I created a scatter plot with POPMW68 AND POPMW78. 
![image](https://user-images.githubusercontent.com/22801047/32034782-6de59030-b9da-11e7-9ed8-f1b264c0003d.png)
When running the Time Player, checking "fixed axes" does not have an effect. The axes still change.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
The fix setting works fine now.
Fixed X scales
<img width="374" alt="12 mar 04fixed" src="https://user-images.githubusercontent.com/36253697/37310932-7e8987f0-263d-11e8-83a8-b057e1b24524.PNG">

Not Fixed
<img width="374" alt="12 mar 04a" src="https://user-images.githubusercontent.com/36253697/37310955-89fadd6e-263d-11e8-9bcd-a4651e2fd1fd.PNG">

But some of the bivariate Moran's I have no points in the scatter plot.
<img width="734" alt="12 mar 05" src="https://user-images.githubusercontent.com/36253697/37311029-cc525390-263d-11e8-955f-488264d48a2d.PNG">

**Comment by lixun910** [comment]
@luluzhou766 Can you share the data in this issue with me? Thanks!

**Comment by luluzhou766** [comment]
@lixun910 sent you an email with the data.
