### ISSUE TITLE
No Basemap

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1226]
I'm using the sample Data set: US Homicides and I am having trouble producing a Basemap.

**Comment by jkoschinsky** [comment]
Click on the icon second from the right on the map toolbar.
<img width="606" alt="screen shot 2017-10-23 at 12 48 39 pm" src="https://user-images.githubusercontent.com/13679743/31904338-964b111c-b7f0-11e7-94ee-091f0274077b.png">

**Comment by jkoschinsky** [comment]
also see a more detailed description in the new GeoDa workbook:
http://geodacenter.github.io/workbook/1_datascience/lab1.html#choropleth-map
