### ISSUE TITLE
GeoDa doesn't run properly on hybrid Windows 7 (32-64 bit)

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1227]
From Lee:
GeoDa 1.12 doesn't run properly on hybrid Windows 7 (32-64 bit).
E.g.:

- options tab is blank 
- natregimes data with Anselin and Rey example (with regimes)  After 30 minutes the program still had not finished running: Took under a minute on Win 8.

**Comment by lixun910** [comment]
Some questions: 
What is a hybrid windows 7 (32-64 bit)? Is there specific OS related to a "hybrid windows 7"?
"Took under a minute on Win 8." --- Is this another test using Win 8?

**Comment by jkoschinsky** [comment]
The Win 8 is the normal performance of running a spatial regression with regimes using natregimes.

The Win 7 performance isn't normal (hanging, no options). Am getting more details about what hybrid means here.

**Comment by lixun910** [comment]
Got it. Thanks!

**Comment by jkoschinsky** [comment]
More info on the hybrid: It's an operating system that reads both 32 bit and 64 bit programs.  It was released between windows 7 (32 only) and windows 8 (64 only).

**Comment by lixun910** [comment]
I am testing on windows 7 using both 32bit or 64bit GeoDa. It works fine using natregime dataset. Can you ask what's the configuration of the regression?

**Comment by jkoschinsky** [comment]
It's this one from p. 299 of Luc's and Serge's book:

[image: Inline images 1]
