### ISSUE TITLE
Grouped variables crashes Conditional maps/plots

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1228]
If specify all time variable in conditional map/plot, GeoDa will crash when select on map/plot. Steps:

<img width="598" alt="screen shot 2017-10-23 at 12 53 28 pm" src="https://user-images.githubusercontent.com/2423887/31914452-8b6db4f2-b7ff-11e7-9232-995ec20f7d41.png">

<img width="698" alt="screen shot 2017-10-23 at 12 28 29 pm" src="https://user-images.githubusercontent.com/2423887/31914476-ab6ddb9c-b7ff-11e7-801e-05b038425282.png">

**Comment by lixun910** [comment]
Related features should be tested w or w/o time variables: 
1. Variable setting dialogs
2. Box plots
3. Conditional Histogram
4. Conditional Map
5. Conditional Scatter plot
6. Scatter Matrix
7. Time editor

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.29
Created time variables and tested all the features listed. No crash.

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.137
Verified

Time variables do not cause any issues with features mentioned above although the histogram still shows up odd as in #1230 .

<img width="729" alt="screen shot 2018-06-18 at 10 26 00 pm" src="https://user-images.githubusercontent.com/37029239/41574284-9f9800ce-7346-11e8-84f8-48b4f2d5c4ec.png">
<img width="1677" alt="screen shot 2018-06-18 at 10 22 39 pm" src="https://user-images.githubusercontent.com/37029239/41574285-9fa2cfe0-7346-11e8-9e04-d4693290132e.png">
