### ISSUE TITLE
Category Editor bug 

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1230]
The Category Editor doesn't show correct histogram:
Step: local Guerry data, Open Category Editor, Select variable "count"

Also, the time chooser is confusing, and should only be displayed when time grouped variable is selected.

<img width="731" alt="screen shot 2017-10-24 at 3 45 29 pm" src="https://user-images.githubusercontent.com/2423887/31971815-630f13b0-b8d2-11e7-9adb-d17401e68cb2.png">

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.29
Had the same issue. Histogram looks normal at first:
![image](https://user-images.githubusercontent.com/22801047/32034020-c14f9734-b9d5-11e7-9873-7c3d517b8779.png)
But then, when clicking "OK", the histogram changes:
![image](https://user-images.githubusercontent.com/22801047/32034052-e89cf476-b9d5-11e7-8f06-1b44cac49d7d.png)

**Comment by lixun910** [comment]
Yes, this is working correctly

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.137
Verified

The correct histogram is shown, however the width of each bar is still odd after "ok" is clicked.

<img width="727" alt="screen shot 2018-06-18 at 10 04 08 pm" src="https://user-images.githubusercontent.com/37029239/41573737-c158f69e-7343-11e8-97b3-f96fa57a5cb5.png">
<img width="723" alt="screen shot 2018-06-18 at 10 03 50 pm" src="https://user-images.githubusercontent.com/37029239/41573738-c1a57e74-7343-11e8-9c14-162522f92ca6.png">
