### ISSUE TITLE
Merge Table crashes when drag-n-drop folder with shapefiles to GeoDa

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1231]
From: johnv@uchicago.edu
 Details:
os: 1-10-12
vs: 1-12-1-7
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/jpveillet/Desktop/Repositories/Spatial Data Science/Assignment 3/Boundaries - Community Areas (current)
Open Layer:geo_export_4172ec7b-4427-47af-98e2-99e47be94f18
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/jpveillet/Desktop/Repositories/Spatial Data Science/Assignment 3/Boundaries - Community Areas (current)
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
Open MergeTableDlg.
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/jpveillet/Desktop/Repositories/Spatial Data Science/Assignment 3/census_data.dbf
Open Layer:census_data
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
ds:/Users/jpveillet/Desktop/Repositories/Spatial Data Science/Assignment 3/census_data.dbf layer: census_data
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnMergeClick()
Open FieldNameCorrectionDlg:
ScrolledWidgetsPane::RemoveIllegalChars
crowded
ScrolledWidgetsPane::TruncateFieldName
crowded
ScrolledWidgetsPane::RenameDupFieldName
crowded
crowded
ScrolledWidgetsPane::RemoveIllegalChars
income
ScrolledWidgetsPane::TruncateFieldName
income
ScrolledWidgetsPane::RenameDupFieldName
income
income
ScrolledWidgetsPane::RemoveIllegalChars
no_diploms
ScrolledWidgetsPane::TruncateFieldName
no_diploms
ScrolledWidgetsPane::RenameDupFieldName
no_diploms
no_diploms
ScrolledWidgetsPane::RemoveIllegalChars
not18to64
ScrolledWidgetsPane::TruncateFieldName
not18to64
ScrolledWidgetsPane::RenameDupFieldName
not18to64
not18to64
ScrolledWidgetsPane::RemoveIllegalChars
poverty
ScrolledWidgetsPane::TruncateFieldName
poverty
ScrolledWidgetsPane::RenameDupFieldName
poverty
poverty
ScrolledWidgetsPane::RemoveIllegalChars
unemp
ScrolledWidgetsPane::TruncateFieldName
unemp
ScrolledWidgetsPane::RenameDupFieldName
unemp
unemp
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
crowded
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
income
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
no_diploms
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
not18to64
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
poverty
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
unemp
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
Click FieldNameCorrectionDlg::OnCancelClick
Exit FieldNameCorrectionDlg
In MergeTableDlg::OnCloseClick()
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/jpveillet/Desktop/Repositories/Spatial Data Science/Assignment 3/Census_Data_-_Selected_socioeconomic_indicators_in_Chicago__2008___2012.csv
Open Layer:Census_Data_-_Selected_socioeconomic_indicators_in_Chicago__2008___2012
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
ds:/Users/jpveillet/Desktop/Repositories/Spatial Data Science/Assignment 3/Census_Data_-_Selected_socioeconomic_indicators_in_Chicago__2008___2012.csv layer: Census_Data_-_Selected_socioeconomic_indicators_in_Chicago__2008___2012
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnMergeClick()
Open FieldNameCorrectionDlg:
ScrolledWidgetsPane::RemoveIllegalChars
PER CAPITA INCOME
ScrolledWidgetsPane::TruncateFieldName
PER CAPITA INCOME
ScrolledWidgetsPane::RenameDupFieldName
PER CAPITA INCOME
PER CAPITA INCOME
ScrolledWidgetsPane::RemoveIllegalChars
PERCENT AGED 16+ UNEMPLOYED
ScrolledWidgetsPane::TruncateFieldName
PERCENT AGED 16+ UNEMPLOYED
ScrolledWidgetsPane::RenameDupFieldName
PERCENT AGED 16+ UNEMPLOYED
PERCENT AGED 16+ UNEMPLOYED
ScrolledWidgetsPane::RemoveIllegalChars
PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA
ScrolledWidgetsPane::TruncateFieldName
PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA
ScrolledWidgetsPane::RenameDupFieldName
PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA
PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA
ScrolledWidgetsPane::RemoveIllegalChars
PERCENT AGED UNDER 18 OR OVER 64
ScrolledWidgetsPane::TruncateFieldName
PERCENT AGED UNDER 18 OR OVER 64
ScrolledWidgetsPane::RenameDupFieldName
PERCENT AGED UNDER 18 OR OVER 64
PERCENT AGED UNDER 18 OR OVER 64
ScrolledWidgetsPane::RemoveIllegalChars
PERCENT HOUSEHOLDS BELOW POVERTY
ScrolledWidgetsPane::TruncateFieldName
PERCENT HOUSEHOLDS BELOW POVERTY
ScrolledWidgetsPane::RenameDupFieldName
PERCENT HOUSEHOLDS BELOW POVERTY
PERCENT HOUSEHOLDS BELOW POVERTY
ScrolledWidgetsPane::RemoveIllegalChars
PERCENT OF HOUSING CROWDED
ScrolledWidgetsPane::TruncateFieldName
PERCENT OF HOUSING CROWDED
ScrolledWidgetsPane::RenameDupFieldName
PERCENT OF HOUSING CROWDED
PERCENT OF HOUSING CROWDED
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
income
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
unemp
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
nodiploma
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
not18to64
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
poverty
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
crowded
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
income
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
unemp
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
nodiploma
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
not18to64
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
poverty
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
crowded
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
Click FieldNameCorrectionDlg::OnCancelClick
Exit FieldNameCorrectionDlg
In MergeTableDlg::OnMergeClick()
Open FieldNameCorrectionDlg:
ScrolledWidgetsPane::RemoveIllegalChars
PER CAPITA INCOME
ScrolledWidgetsPane::TruncateFieldName
PER CAPITA INCOME
ScrolledWidgetsPane::RenameDupFieldName
PER CAPITA INCOME
PER CAPITA INCOME
ScrolledWidgetsPane::RemoveIllegalChars
PERCENT AGED 16+ UNEMPLOYED
ScrolledWidgetsPane::TruncateFieldName
PERCENT AGED 16+ UNEMPLOYED
ScrolledWidgetsPane::RenameDupFieldName
PERCENT AGED 16+ UNEMPLOYED
PERCENT AGED 16+ UNEMPLOYED
ScrolledWidgetsPane::RemoveIllegalChars
PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA
ScrolledWidgetsPane::TruncateFieldName
PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA
ScrolledWidgetsPane::RenameDupFieldName
PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA
PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA
ScrolledWidgetsPane::RemoveIllegalChars
PERCENT AGED UNDER 18 OR OVER 64
ScrolledWidgetsPane::TruncateFieldName
PERCENT AGED UNDER 18 OR OVER 64
ScrolledWidgetsPane::RenameDupFieldName
PERCENT AGED UNDER 18 OR OVER 64
PERCENT AGED UNDER 18 OR OVER 64
ScrolledWidgetsPane::RemoveIllegalChars
PERCENT HOUSEHOLDS BELOW POVERTY
ScrolledWidgetsPane::TruncateFieldName
PERCENT HOUSEHOLDS BELOW POVERTY
ScrolledWidgetsPane::RenameDupFieldName
PERCENT HOUSEHOLDS BELOW POVERTY
PERCENT HOUSEHOLDS BELOW POVERTY
ScrolledWidgetsPane::RemoveIllegalChars
PERCENT OF HOUSING CROWDED
ScrolledWidgetsPane::TruncateFieldName
PERCENT OF HOUSING CROWDED
ScrolledWidgetsPane::RenameDupFieldName
PERCENT OF HOUSING CROWDED
PERCENT OF HOUSING CROWDED
Click FieldNameCorrectionDlg::OnCancelClick
Exit FieldNameCorrectionDlg
In MergeTableDlg::OnCloseClick()
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/jpveillet/Desktop/Repositories/Spatial Data Science/Assignment 3/Census_Data_-_Selected_socioeconomic_indicators_in_Chicago__2008___2012.csvt
Open Layer:Census_Data_-_Selected_socioeconomic_indicators_in_Chicago__2008___2012
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
ds:/Users/jpveillet/Desktop/Repositories/Spatial Data Science/Assignment 3/Census_Data_-_Selected_socioeconomic_indicators_in_Chicago__2008___2012.csvt layer: Census_Data_-_Selected_socioeconomic_indicators_in_Chicago__2008___2012
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/jpveillet/Desktop/Repositories/Spatial Data Science/Assignment 3/census_data.dbf
Open Layer:census_data
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
ds:/Users/jpveillet/Desktop/Repositories/Spatial Data Science/Assignment 3/census_data.dbf layer: census_data
In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnKeyChoice()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
In MergeTableDlg::OnMergeClick()
Open FieldNameCorrectionDlg:
ScrolledWidgetsPane::RemoveIllegalChars
crowded
ScrolledWidgetsPane::TruncateFieldName
crowded
ScrolledWidgetsPane::RenameDupFieldName
crowded
crowded
ScrolledWidgetsPane::RemoveIllegalChars
income
ScrolledWidgetsPane::TruncateFieldName
income
ScrolledWidgetsPane::RenameDupFieldName
income
income
ScrolledWidgetsPane::RemoveIllegalChars
no_diploms
ScrolledWidgetsPane::TruncateFieldName
no_diploms
ScrolledWidgetsPane::RenameDupFieldName
no_diploms
no_diploms
ScrolledWidgetsPane::RemoveIllegalChars
not18to64
ScrolledWidgetsPane::TruncateFieldName
not18to64
ScrolledWidgetsPane::RenameDupFieldName
not18to64
not18to64
ScrolledWidgetsPane::RemoveIllegalChars
poverty
ScrolledWidgetsPane::TruncateFieldName
poverty
ScrolledWidgetsPane::RenameDupFieldName
poverty
poverty
ScrolledWidgetsPane::RemoveIllegalChars
unemp
ScrolledWidgetsPane::TruncateFieldName
unemp
ScrolledWidgetsPane::RenameDupFieldName
unemp
unemp
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
crowded
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
income
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
no_diploms
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
not18to64
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
poverty
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
unemp
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
crowded
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
income
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
nodiploma
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
not18to64
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
poverty
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
unemp
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
crowded
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
income
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
nodiploma
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
not18to64
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
poverty
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
unemp
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
crowded
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
income
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
nodiploma
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
not18to64
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
poverty
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
unemp
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
crowded
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
income
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
nodiploma
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
not18to64
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
poverty
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
unemp
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
Click FieldNameCorrectionDlg::OnCancelClick
Exit FieldNameCorrectionDlg
In TableFrame::OnActivate
Open DataViewerEditFieldPropertiesDlg
In DataViewerEditFieldPropertiesDlg::OnGridComboBox
1
Entering DataViewerEditFieldPropertiesDlg::OnFieldSelected
Entering DataViewerEditFieldPropertiesDlg::OnCellChanging
changing row 7, col 1 from string to integer
In TableFrame::OnActivate
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/jpveillet/Desktop/Repositories/Spatial Data Science/Assignment 2/census_data.dbf
Open Layer:census_data
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
ds:/Users/jpveillet/Desktop/Repositories/Spatial Data Science/Assignment 2/census_data.dbf layer: census_data
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnMergeClick()
Open FieldNameCorrectionDlg:
ScrolledWidgetsPane::RemoveIllegalChars
crowded
ScrolledWidgetsPane::TruncateFieldName
crowded
ScrolledWidgetsPane::RenameDupFieldName
crowded
crowded
ScrolledWidgetsPane::RemoveIllegalChars
income
ScrolledWidgetsPane::TruncateFieldName
income
ScrolledWidgetsPane::RenameDupFieldName
income
income
ScrolledWidgetsPane::RemoveIllegalChars
no_diploms
ScrolledWidgetsPane::TruncateFieldName
no_diploms
ScrolledWidgetsPane::RenameDupFieldName
no_diploms
no_diploms
ScrolledWidgetsPane::RemoveIllegalChars
not18to64
ScrolledWidgetsPane::TruncateFieldName
not18to64
ScrolledWidgetsPane::RenameDupFieldName
not18to64
not18to64
ScrolledWidgetsPane::RemoveIllegalChars
poverty
ScrolledWidgetsPane::TruncateFieldName
poverty
ScrolledWidgetsPane::RenameDupFieldName
poverty
poverty
ScrolledWidgetsPane::RemoveIllegalChars
unemp
ScrolledWidgetsPane::TruncateFieldName
unemp
ScrolledWidgetsPane::RenameDupFieldName
unemp
unemp
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
crowded
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
income
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
no_diploms
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
not18to64
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
poverty
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
unemp
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
crowd
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
inc
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
nodip
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
1864
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
pov
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
unem
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
crowd
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
inc
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
nodip
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
1864
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
pov
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
unem
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
crowd
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
inc
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
nodip
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
1864
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
pov
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
unem
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
Click FieldNameCorrectionDlg::OnCancelClick
In TableFrame::OnActivate
Exit FieldNameCorrectionDlg
In MergeTableDlg::OnCloseClick()
MapCanvas::~MapCanvas()
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs
New Datasource Name:/Users/jpveillet/Desktop/Repositories/Spatial Data Science/Assignment 3/Boundaries - Community Areas (current)

**Comment by lixun910** [comment]
same with #1225
