### ISSUE TITLE
Category Editor: Histogram text been trimmed

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1234]
<img width="467" alt="screen shot 2017-10-24 at 11 18 07 pm" src="https://user-images.githubusercontent.com/2423887/31983334-bb3e104c-b911-11e7-8928-7b86ee39d64e.png">

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.29
Confirmed. Text is no longer trimmed at bottom.
![image](https://user-images.githubusercontent.com/22801047/32034090-1cd53596-b9d6-11e7-9e76-d5b5695afea6.png)

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.137
Verified
Histogram text no longer trimmed.

<img width="725" alt="screen shot 2018-06-14 at 4 56 51 pm" src="https://user-images.githubusercontent.com/37029239/41440410-fdb628c6-6ff3-11e8-9025-977a71b9adc5.png">
