### ISSUE TITLE
Differential Local Moran's I ESDA tool menu colored a grey & Clusters' tool no return results with more than 1000 polygons

### ISSUE THREAD

**Issue by mzjanak** [GeoDaCenter/geoda#1238]
We are encountered with the similar problems using GeoDa 1.12 as previously having been encountered with GeoDa 1.10 in June. Thus, the first problem is related to Differential Local Moran's I ESDA tool which is colored a grey. Hence, one cannot run the analysis anyway although he/she has already prepared spatial weights as well as edit times variables in accordance to recommended steps on the pull down menu. The second problem deals with running all methods within 'Clusters' tool where no analysis cannot be done with approx. more than 1000 polygons as the software shuts down or no responses after clicking on the 'Run' button at every time.

**Comment by lixun910** [comment]
@mzjanak The grey menu options has been fixed in our latest GeoDa (internal). Can you try to verify it? 
Mac OSX: https://www.dropbox.com/s/zxjlxjid20uqgtc/GeoDa1.12.1.29-Installer.dmg?dl=0
Windows 64-bit: https://www.dropbox.com/s/dibnsf75d0iymi8/GeoDa-1.12.1.29-Windows-64bit.exe?dl=0

For "Clusters", which method did you use? and what are the configurations you specified? 
Spectral Clustering, REDCAP and Max-p are slow algorithms and are not scaled well in current version. PCA, KMeans and HCluster should handle 1000 records easily with proper configurations.

We will keep you updated if we have updated "Clusters" module with better performance.

**Comment by mzjanak** [comment]
Dear Sir or Madam, thank you for your rapid response. Firstly, I hereby confirm that the problem related to Differential Local Moran's I ESDA tool, i.e. the grey menu options, has been successfully fixed by you. Thank you very much. I really appreciate it. Relating to the second problem, i.e. Clusters methods, I have checked functionality of all of them with both 1216 and 6354 records (i.e. polygons of municipalities) . Hence, the non-spatial cluster techniques except Spectral Clustering ran well with both datasets and provided results as expected. On the contrary, spatial cluster techniques, i.e. Max-p and REDCAP, as well as Spectral Cluster did not work with 6354 records due to large dataset. Furthermore, the results for Max-p and REDCAP clustering techniques was provided for file with 1216 records, however, not for Spectral Cluster method.

**Comment by mzjanak** [comment]
In addtion, the default setting was used for computation of all clustering methods.

**Comment by mzjanak** [comment]
Last but not least, I take it back the last statement. The Spectral Cluster method with 1216 records works, however, one needs to wait approx. 15 minutes.

**Comment by lixun910** [comment]
@mzjanak 
Here is the GeoDa 1.12.1.39 internal build. The major updates/fixes are using power iteration (eigenvalue algorithm) in MDS and Spectral clustering, which will perform much faster.

Mac: https://www.dropbox.com/s/4su9cbnxyr28w6h/GeoDa1.12.1.39-Installer.dmg?dl=0
Win64: https://www.dropbox.com/s/2vc0ypbu8da2j4u/GeoDa-1.12.1.39-Windows-64bit.exe?dl=0

**Comment by mzjanak** [comment]
Thank you very much for your fantastic job and enthusiasm to find a solution. Thank you very much for your help again. It works!!!

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.137
Verified

All clustering methods with 3085 observations were completed without error.
Additionally, fixed grey Differential Local Moran's I dropdown

<img width="390" alt="differential local moran s i" src="https://user-images.githubusercontent.com/37029239/41439950-6814e20e-6ff2-11e8-8b1c-a5e5f0cfd745.png">
<img width="586" alt="max-p map" src="https://user-images.githubusercontent.com/37029239/41439951-682067a0-6ff2-11e8-9dad-6e9d709dde63.png">
<img width="771" alt="max-p settings" src="https://user-images.githubusercontent.com/37029239/41439952-682ea4c8-6ff2-11e8-8d79-91d38b7b6243.png">
<img width="587" alt="redcap map" src="https://user-images.githubusercontent.com/37029239/41439953-683a601a-6ff2-11e8-8c08-bfd5a214c496.png">
<img width="812" alt="redcap settings" src="https://user-images.githubusercontent.com/37029239/41439954-6846d30e-6ff2-11e8-9adc-3605ca39d3f4.png">
<img width="586" alt="skater map" src="https://user-images.githubusercontent.com/37029239/41439955-685935da-6ff2-11e8-84d0-2b6ddd798284.png">
<img width="782" alt="skater settings" src="https://user-images.githubusercontent.com/37029239/41439956-686798e6-6ff2-11e8-9109-4fe294c5fea7.png">
<img width="595" alt="hbdscan map" src="https://user-images.githubusercontent.com/37029239/41439957-6873b018-6ff2-11e8-8aca-6d1c86c920bd.png">
<img width="873" alt="hbdscan settings" src="https://user-images.githubusercontent.com/37029239/41439958-6881c3f6-6ff2-11e8-81f3-2cfe38a99266.png">
<img width="859" alt="hierarchical" src="https://user-images.githubusercontent.com/37029239/41439959-688beb42-6ff2-11e8-8a09-aabef1539797.png">
<img width="592" alt="spectral map" src="https://user-images.githubusercontent.com/37029239/41439960-68978b78-6ff2-11e8-8cac-dfc7b086b2a0.png">
<img width="795" alt="spectral 3085" src="https://user-images.githubusercontent.com/37029239/41439961-68a22b5a-6ff2-11e8-9bcc-c33fd967dc29.png">
<img width="595" alt="kmedoids plot" src="https://user-images.githubusercontent.com/37029239/41439962-68affac8-6ff2-11e8-9d3b-d70858887450.png">
<img width="862" alt="kmedoids settings" src="https://user-images.githubusercontent.com/37029239/41439963-68bda7cc-6ff2-11e8-9326-6a5fec40d81e.png">
<img width="595" alt="kmedians 3085 map" src="https://user-images.githubusercontent.com/37029239/41439964-68c91206-6ff2-11e8-8be2-858cff09387a.png">
<img width="865" alt="kmedians 3085 settings" src="https://user-images.githubusercontent.com/37029239/41439965-68df61aa-6ff2-11e8-9772-3e9122be5359.png">
<img width="598" alt="kmeans 3085" src="https://user-images.githubusercontent.com/37029239/41439966-68f0b220-6ff2-11e8-9aa5-3f786fcf292d.png">
<img width="862" alt="kmeans 3085 settings" src="https://user-images.githubusercontent.com/37029239/41439968-68fd8ea0-6ff2-11e8-8aab-f3b808631c1a.png">
<img width="496" alt="mds 3085" src="https://user-images.githubusercontent.com/37029239/41439969-690a50cc-6ff2-11e8-8c23-884727613ed7.png">
<img width="412" alt="mds 3085 settings" src="https://user-images.githubusercontent.com/37029239/41439970-6916a78c-6ff2-11e8-97c4-5254654bb53d.png">
<img width="813" alt="pca 3085 obs" src="https://user-images.githubusercontent.com/37029239/41439971-69247dee-6ff2-11e8-82b9-bc37050f5743.png">
