### ISSUE TITLE
Saving/Opening GDA Project with File Geodatabase

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1239]
From user (I have email):

First, thank you for all the great work on GeoDa--I am a big fan.

I am having an issue with GeoDa projects that use File Geodatabase Feature Classes. The Feature Class opens and works well in GeoDa. The project file saves successfully (and with the correct file path). When I reopen the GDA project, however, I get this error:

![image](https://user-images.githubusercontent.com/13679743/32082461-5e47c45c-ba81-11e7-88a0-4b608219cbac.png)

I've triple-checked the file path in the GDA file. I tried creating a system variable with the ESRI File Geodatabase API and restarted GeoDa. I've tried saving the project file in the same folder as the Geodatabase, but none of these solved the issue.

Shapefiles function correctly in the saved projects and reopen, but I would like to use Geodatabase Feature Classes since the NULL values are important in my analysis.

Please advise. 

Also, the main thing I lose each time is the Time Groups. I tried opening the GDA from this window, but I got the same error message. I tried saving a csv from the Save Space-Time Table/Weights, but since I'm working with polygons, it's not a great work around. Are there other ways to save/load the Time Groups, even if I can't save the GDA project file?

-Wright

**Comment by luluzhou766** [comment]
I created a new project file including Time Groups, and a queen weights. I can open the project file with all the information I saved. 

But I had a similar problem yesterday. 
My Mac system crashed, so I have to reinstalled it. Then I cannot open my open project file, as the picture shown below. 
All the files have been in the clouds, including all the initial GIS files and other files created later. And the project file worked well last months.

![screen shot 2018-05-03 at 6 47 34 pm](https://user-images.githubusercontent.com/36253697/39573196-ccde1d86-4f04-11e8-8bb1-f92e5f881682.png)

**Comment by lixun910** [comment]
The original issue has been fixed. 

What @luluzhou766 mentioned is another issue caused by cloud storage, that some files "look like" are existing on your hard drive, but they are not. You need to actually download it (by right click and select from menu), and then try to open it in GeoDa. Or simply copy it from cloud directory to another "local" directory.
