### ISSUE TITLE
scatter plot save as image cropped

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1246]
The image for the scatter plot seems to cut off part of the statistics at the bottom. Compare png image to screen shot below. (Version 1.12.1.31).

![guerry85scatternewplotframe](https://user-images.githubusercontent.com/4008351/32145077-98da9c5a-bc90-11e7-896d-5b9f494c900d.png)
<img width="536" alt="screen shot 2017-10-29 at 10 00 21 am" src="https://user-images.githubusercontent.com/4008351/32145079-9faa050c-bc90-11e7-98c4-9e3436988213.png">

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.33
Verified
