### ISSUE TITLE
MDS settings should not have geometric centroids

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1249]
The MDS settings dialog contains a check box to use geometric centroids. This is not really a suitable option for MDS. Also, not sure how exactly it gets implemented.

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.33
Verified
![image](https://user-images.githubusercontent.com/22801047/32357270-3bf91dc8-c009-11e7-93e3-d517d59f6205.png)
