### ISSUE TITLE
Hierarchical clustering missing geometric centroids weights

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1250]
The dialog for hierarchical clustering has a check box for geometric weights, but does not have the weights slider bar that k-means has.

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.29
Slider not visible:
![image](https://user-images.githubusercontent.com/22801047/32297790-477db97e-bf1e-11e7-8e7f-26270a86ecd2.png)

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.37
Verified
