### ISSUE TITLE
k-means and spectral clustering need summary statistics

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1252]
The cluster procedures need some summary statistics. At the very least, there should be within cluster sum of squares and the ratio of between cluster sum of squares to total sum of squares.

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.33
To clarify: Where in the frame should I look for the summary statistics? 
![image](https://user-images.githubusercontent.com/22801047/32358504-a21ec2fa-c014-11e7-9638-a72f9cf5d273.png)

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
Verified 
<img width="672" alt="12 mar 02" src="https://user-images.githubusercontent.com/36253697/37306054-66e70faa-262e-11e8-843d-1495fe142ee5.PNG">

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v111
OSX
