### ISSUE TITLE
Add a measure of neighbor overlap between two weights (luc)

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1258]
Initially, just listing the common neighbors between weights, but also some interesting
visualizations, maybe using the connectedness graph idea.

**Comment by lixun910** [comment]
Connectivity graph and connectivity map have been implemented since V161. 
Close this issue and new issues or bugs should be opened in new ticket.

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.195 (macOS Mojave, 10.14.3). Jan. 25 build.

Tested **Weights Intersection** and **Weights Union**. 

Datasets: Guerry sample
Weights: KNN-5; Queen-2 (lower incl); Table variable

<img width="852" alt="1258" src="https://user-images.githubusercontent.com/45187310/52550137-6e49f700-2d9c-11e9-861d-0c890b946611.png">

But when **Weights Intersection** is applied to three weights, there seems to be a problem. The **Intersection** of three weights is the **Union** of sub-intersections of each pair. 
EX. A&B&C = (A&B)+(A&C)+(B&C). See below. @lixun910 Could this be a problem?

<img width="1108" alt="1258-2" src="https://user-images.githubusercontent.com/45187310/52550697-cb46ac80-2d9e-11e9-971b-18022981b02d.png">

**Comment by lixun910** [comment]
V219

**Comment by lixun910** [comment]
Fix verified:

Union
<img width="598" alt="Screen Shot 2019-08-02 at 8 34 08 PM" src="https://user-images.githubusercontent.com/2423887/62406764-7f164100-b565-11e9-9937-1612e2e44d6a.png">

Intersect
<img width="661" alt="Screen Shot 2019-08-02 at 8 38 08 PM" src="https://user-images.githubusercontent.com/2423887/62406767-85a4b880-b565-11e9-97fc-bf1e45781b20.png">
