### ISSUE TITLE
Variable Settings dialog: choose time will change existing selections

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1261]

**Comment by YidanJ-Wu** [comment]
Windows 8 
1.12.1.33
What steps do I take to replicate this?

**Comment by lixun910** [comment]
create time-grouped variable, use time player to change time

**Comment by YidanJ-Wu** [comment]
Windows 8 
1.12.1.85
Create time-grouped variable for from for06, for07, for08, for09
![image](https://user-images.githubusercontent.com/22801047/35603324-7ebbe494-0602-11e8-9437-c62ac851863e.png)
Make an arbitrary selection of polygon tracts
![image](https://user-images.githubusercontent.com/22801047/35603414-e4449edc-0602-11e8-8b6e-3201ce274925.png)
Change from time 3 to time 2. the selections change. 
![image](https://user-images.githubusercontent.com/22801047/35603431-f5ef1860-0602-11e8-9110-2a30cedd90c0.png)

**Comment by lixun910** [comment]
@YidanJ-Wu : this is "Animation", which should highlight the observations one by one from min value to max value.

What I mentioned is the "Time->Time Player", when you click "play" with time-grouped variable, the existing highlight should not be changed.

**Comment by YidanJ-Wu** [comment]
@lixun910 my bad. I tried Time -> Time Player on the same NYC file and a few others. The existing highlight didn't change.
