### ISSUE TITLE
cannot generate lowess smoother in Moran's I scatter plot under newest version 

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1262]
I have redownloaded or loaded different datasets, but still view-lowess smoother in moran scatter plot does not work.

os: 1-10-12
vs: 1-12-0-0
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
GdaFrame::OpenProject()
/Users/yiqingzhu/UChicago/Fall 2017/MACS 54000/Assignments/ass5/ass5.gda
Entering Project::Project (existing project)
/Users/yiqingzhu/UChicago/Fall 2017/MACS 54000/Assignments/ass5/ass5.gda
Project::SetProjectFullPath()
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/yiqingzhu/UChicago/Fall 2017/MACS 54000/Assignments/ass3/Boundaries - Community Areas (current)/geo_export_7b4ee7e4-0767-4d0c-9b12-e339ac07ae3c.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
CRIME_RATE
VariableSettingsDlg::GetWeightsId() weight: comm_queen
VariableSettingsDlg::GetWeightsId() weight: comm_queen
Entering LisaCoordinator::LisaCoordinator().
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
Entering LisaCoordinator::InitFromVarInfo()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Entering LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
In LisaCoordinator::registerObserver()
In GdaFrame::OnViewLowessSmoother()
In GdaFrame::OnViewLowessSmoother()
In GdaFrame::OnViewLowessSmoother()
In GdaFrame::OnViewLinearSmoother()
In GdaFrame::OnViewLinearSmoother()
In GdaFrame::OnReportBug()
Open ReportBugDlg.
In GdaFrame::OnReportBug()
Open ReportBugDlg.
In ReportBugDlg::OnOkClick()

**Comment by YidanJ-Wu** [comment]
Bug confirmed in Windows 8 1.12
![image](https://user-images.githubusercontent.com/22801047/32359562-ecb53fb2-c01c-11e7-8878-fc53ec11506b.png)
Fixed in Windows 8 1.12.1.33
