### ISSUE TITLE
switch to official gdal library

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1263]

**Comment by lixun910** [comment]
One customized change in our GDAL/OGR library is adding a feature in CSV reader to parse real numbers that using COMMA or DOT decimal separator. 

This could be done on GeoDa side, see ci #d4b855065. Therefore, this customized change of OGR library is no longer needed.

**Comment by lixun910** [comment]
[test_locale.csv.zip](https://github.com/GeoDaCenter/geoda/files/2887536/test_locale.csv.zip)

Testing csv file (tab delimited):
| id |	value    |
|---|-------   |
| 1  |	1000,2  |
| 2 |	2000,3  |

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.201 (macOS Mojave, 10.14.3). Feb. 20 build.

Fix verified. BTW, does GeoDa allow one to manually specify the delimiter instead of auto-detect? 

<img width="292" alt="1263" src="https://user-images.githubusercontent.com/45187310/53190519-66c1f380-35cf-11e9-8647-d4b7b3ebfc46.png">

**Comment by lixun910** [comment]
@Ashitacarl  In the current version, GeoDa only do auto-detect (using GDAL/OGR) the delimiter when loading a CSV file. This (manually specify the delimiter) could be added as an enhancement feature in GeoDa (next release).
