### ISSUE TITLE
Table Calculator - Enumerate: always reflects original order

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1268]
The sequence numbers created by the Enumerate command always reflect the original order of the observations, rather than the current order, e.g., after sorting. It would be better if the enumerate command reflected the current sorted order, so that it can also be used to reflect the sorting order
for different variables. For example, this is handy in the illustration of how FDR works: sort the observations by p-value and then create a sequence number. However, in the current implementation, the sequence number is always that of the original order of observations. To get the sequence numbers for the sorted observations, one has to enter it by hand ...

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.33
I used the Guerry set to test. Sorted the pop1831 column, then created new variable "ENUMTEST" and populated that in the Calculator dialog. The numbers in ENUMTEST still reflect the original order, not the sorted order. 
![image](https://user-images.githubusercontent.com/22801047/32358705-47b58b1c-c016-11e7-8e91-c73ef9bba781.png)

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.37 
Verified
