### ISSUE TITLE
Background color 

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#1271]
Windows 8 1.12.1.29
The "background color" feature only works when my mouse is hovering over a point: 
![image](https://user-images.githubusercontent.com/22801047/32281341-90c06410-beec-11e7-8733-0acc89b049c1.png)
When the mouse isn't hovering over a point the window looks like this:
![image](https://user-images.githubusercontent.com/22801047/32281374-a43f2abc-beec-11e7-8274-5e1f10a03a0d.png)

Not sure if this is a feature or a bug

**Comment by luluzhou766** [comment]
Win 10, 64bit
Geoda 1.12.1.131

when the background color is set to gray and mouse is not hanging over 

![02](https://user-images.githubusercontent.com/36253697/39416050-1c65a712-4c39-11e8-9322-cc31446dee7b.PNG)

when mouse is hanging over 


![img_0950 1](https://user-images.githubusercontent.com/36253697/39416062-3cb5022e-4c39-11e8-9e1c-8d8d880dac84.jpg)

**Comment by YidanJ-Wu** [comment]
Windows 8 
1.12.1.131 
Verified
