### ISSUE TITLE
Opening two files

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#1272]
Windows 8 
1.12.1.29
I noticed that it's possible to open two .shp files in GeoDa at once.
Click "open files" icon
![image](https://user-images.githubusercontent.com/22801047/32282696-4d33ba9a-bef0-11e7-9d22-cb3c97aa7c44.png)
Open Windows Explorer (not from GeoDa) and double click on .shp file
![image](https://user-images.githubusercontent.com/22801047/32282762-79d9452e-bef0-11e7-862c-d1264e14cc9b.png)
.shp file is now open, but the "Connect to Data Source" dialog is still open. Click on one of the recent files.
![image](https://user-images.githubusercontent.com/22801047/32282819-a5cdd33e-bef0-11e7-9944-fef7ddd47c82.png)
There are now 2 .shp files open
![image](https://user-images.githubusercontent.com/22801047/32282870-c96a417e-bef0-11e7-87d6-cc398d91112d.png)

However, if you open the first .shp file from the "Connect to Data Source" dialog instead of Windows Explorer, it is not possible to open a second .shp file. The "open files" icon is unresponsive. 
![image](https://user-images.githubusercontent.com/22801047/32283041-4df1980c-bef1-11e7-91b7-0145efa0b1e2.png)

**Comment by lixun910** [comment]
Thanks for finding this bug! This could be the issue to crash GeoDa — from the reports that we can’t replicate.

**Comment by YidanJ-Wu** [comment]
Windows 8 
1.12.1.33
Still opens two .shp files
![image](https://user-images.githubusercontent.com/22801047/32357218-bc6fc2c8-c008-11e7-967b-ece59cba758f.png)

**Comment by luluzhou766** [comment]
Win 10, 64bit
Geoda 1.12.1.131

In my system, I cannot open .gda or .shp files directly from Windows
I have to drag them into GeoDa to open the file. 
So, I can only open one file each time. 

![01](https://user-images.githubusercontent.com/36253697/39416239-f764f2b8-4c3a-11e8-82d5-5d09adab216a.PNG)

![03](https://user-images.githubusercontent.com/36253697/39416241-f9ceccf4-4c3a-11e8-972a-d63de034754c.PNG)

**Comment by jkoschinsky** [comment]
Problem persists in GeoDa 1.12.1.133 OSX: You can still open two shapefiles:

<img width="1040" alt="screen shot 2018-06-05 at 1 36 10 pm" src="https://user-images.githubusercontent.com/13679743/40995713-7e4e4652-68c5-11e8-8350-ed8c28da4281.png">

**Comment by VeraB620** [comment]
OS X El Capitan 10.11.6
GeoDa 1.12.1.141

I can only open one .shp file at a time, no warning pops up or anything just nothing happens, only the first map is open and usable.
