### ISSUE TITLE
Spectral Clustering crash

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#1275]
Windows 8 1.12.1.33
Froze when attempting to run Spectral Clustering. I submitted a crash report and left my email address, so that should be showing up in a few minutes. 
![image](https://user-images.githubusercontent.com/22801047/32358537-e9c38d3e-c014-11e7-8356-a2d407fdaf1b.png)

**Comment by lixun910** [comment]
@YidanJ-Wu  This is normal since spectral clustering involves eigen decomposition which takes quadratic time. 

todo:
1 Adding warning message
2 Provide approximation method

**Comment by jkoschinsky** [comment]
todo:
1 Adding warning message
2 Provide approximation method

**Comment by YidanJ-Wu** [comment]
Windows 8 
GeoDa 1.12.1.85
Tried Spectral Clustering on the same file with slightly different specs: 
![image](https://user-images.githubusercontent.com/22801047/35602023-9510d0b2-05fb-11e8-9a69-89af09dd7b02.png)
