### ISSUE TITLE
GeoDa won't close

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#1276]
Windows 8 1.12.1.33
![image](https://user-images.githubusercontent.com/22801047/32359235-7a192b78-c01a-11e7-986e-7c9c13860a35.png)
The close button is sometimes unresponsive. I'm not sure if this is an issue with GeoDa or just my computer. 
Update: File > Exit is also being unresponsive
![image](https://user-images.githubusercontent.com/22801047/32359260-baaf8fce-c01a-11e7-9e0a-9c705ff8e325.png)

**Comment by lixun910** [comment]
@YidanJ-Wu Did you get the same issue on 1.35?

**Comment by YidanJ-Wu** [comment]
I didn't try 1.35, but I tried 1.37 and did not get the same issue.
