### ISSUE TITLE
Clusters - Map heading

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1279]
As it stands, the header for the cluster map just says  "Map". It would be more informative if there were at least some reference to the type of clustering. I am not suggesting listing all the variables, since that will be unwieldy for all but the simplest examples, but something like "Hierarchical Clusters" or
"K-Means Clusters", etc.?

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.39 
Verified
