### ISSUE TITLE
Lowess Smoother does not show; manually calculated lagged standardized variable does not equate those generated by moral plot

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1281]
load project file on Cleveland dataset with previously added queen continuity weight. produce Moran plot for sale price
Manually add standardized variable based on sale price and spatially lagged weighted average of the variable
(Try to) add Lowess smoother

os: 1-10-12
vs: 1-12-1-7
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
GdaFrame::OpenProject()
/Users/KaitingZhou/Downloads/cleveland/clev_sls_154_core.gda
Entering Project::Project (existing project)
/Users/KaitingZhou/Downloads/cleveland/clev_sls_154_core.gda
Project::SetProjectFullPath()
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/KaitingZhou/Downloads/cleveland/clev_sls_154_core.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open project file:/Users/KaitingZhou/Downloads/cleveland/clev_sls_154_core.gda
GdaFrame::OpenProject()
/Users/KaitingZhou/Downloads/cleveland/clev_sls_154_core.gda
Project::GetProjectFullPath()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
POLY_ID
VariableSettingsDlg::GetWeightsId() weight: clev_sls_154_core_q
VariableSettingsDlg::GetWeightsId() weight: clev_sls_154_core_q
Entering LisaCoordinator::LisaCoordinator().
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
Entering LisaCoordinator::InitFromVarInfo()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Entering LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
In LisaCoordinator::registerObserver()
Entering LisaCoordinator::removeObserver
In LisaCoordinator::~LisaCoordinator().
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::removeObserver
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
sale_price
VariableSettingsDlg::GetWeightsId() weight: clev_sls_154_core_q
VariableSettingsDlg::GetWeightsId() weight: clev_sls_154_core_q
Entering LisaCoordinator::LisaCoordinator().
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
Entering LisaCoordinator::InitFromVarInfo()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Entering LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
In LisaCoordinator::registerObserver()
In TableFrame::OnActivate
In OnSaveMoranI()
LisaScatterPlotFrame::OnSaveMoranI
Open FieldNewCalcSheetDlg.
In FieldNewCalcSheetDlg::OnPageChange()
Open DataViewerAddColDlg.
DataViewerAddColDlg::CreateControls()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
In DataViewerAddColDlg::SetDefaultsByType()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::UpdateMinMaxValues()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::UpdateMinMaxValues()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::UpdateMinMaxValues()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnOkClick()
Inserting new column M_ST into Table
In FieldNewCalcSheetDlg::OnApplyClick()
In FieldNewCalcSheetDlg::OnApplyClick()
Open DataViewerAddColDlg.
DataViewerAddColDlg::CreateControls()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
In DataViewerAddColDlg::SetDefaultsByType()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::UpdateMinMaxValues()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::UpdateMinMaxValues()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::UpdateMinMaxValues()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnOkClick()
Inserting new column M_LAG into Table
In FieldNewCalcSheetDlg::OnPageChange()
In FieldNewCalcSheetDlg::OnApplyClick()
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
Open DataViewerDeleteColDlg.
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnDelete()
M_LAG
In TableFrame::OnActivate
In TableFrame::OnActivate
Open DataViewerAddColDlg.
DataViewerAddColDlg::CreateControls()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
In DataViewerAddColDlg::SetDefaultsByType()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::UpdateMinMaxValues()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::UpdateMinMaxValues()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::UpdateMinMaxValues()
DataViewerAddColDlg::UpdateApplyButton()
In TableFrame::OnActivate
Open DataViewerAddColDlg.
DataViewerAddColDlg::CreateControls()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
In DataViewerAddColDlg::SetDefaultsByType()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::UpdateMinMaxValues()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::UpdateMinMaxValues()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::UpdateMinMaxValues()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnOkClick()
Inserting new column M_LAG into Table
In FieldNewCalcSheetDlg::OnApplyClick()
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In FieldNewCalcSheetDlg::OnApplyClick()
In FieldNewCalcSheetDlg::OnApplyClick()
In TableFrame::OnActivate
In OnRan999Per()
Open RandomizationDlg (univariate).
In OnRan999Per()
Open RandomizationDlg (univariate).
Close RandomizationDlg
Click RandomizationDlg::OnOkClick
Click RandomizationDlg::OnOkClick
Click RandomizationDlg::OnOkClick
Click RandomizationDlg::OnOkClick
Click RandomizationDlg::OnOkClick
Click RandomizationDlg::OnOkClick
Click RandomizationDlg::OnOkClick
Click RandomizationDlg::OnOkClick
Click RandomizationDlg::OnOkClick
Click RandomizationDlg::OnOkClick
Click RandomizationDlg::OnOkClick
Click RandomizationDlg::OnOkClick
Click RandomizationDlg::OnOkClick
Click RandomizationDlg::OnOkClick
Click RandomizationDlg::OnOkClick
Click RandomizationDlg::OnOkClick
Close RandomizationDlg
In GdaFrame::OnViewLowessSmoother()
In GdaFrame::OnViewLowessSmoother()
In GdaFrame::OnViewLowessSmoother()
In GdaFrame::OnViewLinearSmoother()
In GdaFrame::OnViewLowessSmoother()
In GdaFrame::OnViewLowessSmoother()
Entering LisaCoordinator::removeObserver
In LisaCoordinator::~LisaCoordinator().
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::removeObserver
MapCanvas::~MapCanvas()
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
Project::GetProjectFullPath()
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs
New Datasource Name:/Users/KaitingZhou/Downloads/cleveland/GdaTmp_clev_sls_154_core.shp
Project::GetSpatialReference()
Project::GetGdaGeometries()
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
POLY_ID
ScrolledWidgetsPane::IsFieldNameValid
unique_id
ScrolledWidgetsPane::IsFieldNameValid
parcel
ScrolledWidgetsPane::IsFieldNameValid
x
ScrolledWidgetsPane::IsFieldNameValid
y
ScrolledWidgetsPane::IsFieldNameValid
N_PRICE
ScrolledWidgetsPane::IsFieldNameValid
sale_price
ScrolledWidgetsPane::IsFieldNameValid
tract10int
ScrolledWidgetsPane::IsFieldNameValid
Quarter
ScrolledWidgetsPane::IsFieldNameValid
year1
ScrolledWidgetsPane::IsFieldNameValid
yrquarter
ScrolledWidgetsPane::IsFieldNameValid
MORAN_STD
ScrolledWidgetsPane::IsFieldNameValid
MORAN_LAG
ScrolledWidgetsPane::IsFieldNameValid
M_LAG
ScrolledWidgetsPane::IsFieldNameValid
M_ST
Exit FieldNameCorrectionDlg
Out OGRDataAdapter::ExportDataSource()
Exiting Project::SaveDataSourceData
Entering Project::SaveProjectConf
In Project::UpdateProjectConf
Exiting Project::SaveProjectConf
In FieldNewCalcSheetDlg::OnClose()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
GdaFrame::OpenProject()
/Users/KaitingZhou/Downloads/cleveland/clev_sls_154_core.gda
Entering Project::Project (existing project)
/Users/KaitingZhou/Downloads/cleveland/clev_sls_154_core.gda
Project::SetProjectFullPath()
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/KaitingZhou/Downloads/cleveland/clev_sls_154_core.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open project file:/Users/KaitingZhou/Downloads/cleveland/clev_sls_154_core.gda
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
sale_price
VariableSettingsDlg::GetWeightsId() weight: clev_sls_154_core_q
VariableSettingsDlg::GetWeightsId() weight: clev_sls_154_core_q
Entering LisaCoordinator::LisaCoordinator().
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
Entering LisaCoordinator::InitFromVarInfo()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Entering LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
In LisaCoordinator::registerObserver()
In GdaFrame::OnViewLinearSmoother()
In GdaFrame::OnViewLowessSmoother()
In GdaFrame::OnEditLowessParams()
In GdaFrame::OnReportBug()
Open ReportBugDlg.
In ReportBugDlg::OnOkClick()
In ReportBugDlg::OnOkClick()

**Comment by lixun910** [comment]
same with 1286 (fixed and replied)
