### ISSUE TITLE
Inconsistent results of k-means clustering

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1283]
There is an inconsistency between the results obtained for k-means clustering depending on how the process is initiated.

Scenario 1:
- take the 6 variables from Guerry, run k-means with k = 4 yields this
![kmeans_4](https://user-images.githubusercontent.com/4008351/32420066-98f21514-c24a-11e7-85c5-b936093867d9.png)

Scenario 2:
- take the 6 variables from Guerry, check the geometric centroids box but set the weights to 0

<img width="394" alt="screen shot 2017-11-05 at 4 51 07 pm" src="https://user-images.githubusercontent.com/4008351/32420095-f4a8f8be-c24a-11e7-9172-e2566cd79498.png">

(in other words this should give the exact same result as above, but it does not)
  this gives the result on the right (original is on left)
<img width="1034" alt="screen shot 2017-11-05 at 4 51 31 pm" src="https://user-images.githubusercontent.com/4008351/32420078-cd928d12-c24a-11e7-922d-6923f711797a.png">

this result is actually slightly better than the first one, with a between/total ratio of 0.4323 compared
to 0.4309 for the original result

- after this, unchecking the geometric centroids box and re-running the k-means gets the same
  result again, same as with the weight set to 0, but different from running it without the check box

All three of these results should be the same.

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.37
Here's what I got when running k-means with the 6 variables shown above and k = 4:
![image](https://user-images.githubusercontent.com/22801047/32478246-52f178ca-c349-11e7-9bb9-33eb8647c119.png)

Here's what I got when running it again, with "Use Geometric Centroids" checked and weighting = 0:
![image](https://user-images.githubusercontent.com/22801047/32478225-2f4b6886-c349-11e7-9b4c-4e7cb53982da.png)

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.39
Verified
Same 6 variables, k = 4
Use Geometric Centroids not checked:
![image](https://user-images.githubusercontent.com/22801047/32614999-25e3e132-c534-11e7-80ba-46aa56d2dee9.png)
Use Geometric Centroids checked, weighting = 0: 
![image](https://user-images.githubusercontent.com/22801047/32615040-419e4f52-c534-11e7-997c-6ec8f58cc4f2.png)
