### ISSUE TITLE
Trouble with LOWESS Smoother in Univariate Moran's I 

### ISSUE THREAD

**Issue by Ashitakarl** [GeoDaCenter/geoda#1286]
![moran i](https://user-images.githubusercontent.com/33434290/32464995-8b9f4cb6-c307-11e7-8c77-18e409600414.png)

This LOWESS function never worked (re-boot does not help).

**Comment by lixun910** [comment]
@Ashitakarl Thanks for your report! We've fixed this issue in our internal build: 
Windows 64bits: https://www.dropbox.com/s/et42ui17yn8w6h2/GeoDa-1.12.1.33-Windows-64bit.exe?dl=0
mac OSX: https://www.dropbox.com/s/2kxcv7xvhweoowj/GeoDa1.12.1.33-Installer.dmg?dl=0

Can you try this new version to verify the fix? Thanks!

**Comment by lixun910** [comment]
Hi Nikita,

Thanks for sending this report! 

We've fixed this issue in our internal build:
Windows 64bits: https://www.dropbox.com/s/et42ui17yn8w6h2/GeoDa-1.12.1.33-Windows-64bit.exe?dl=0
mac OSX: https://www.dropbox.com/s/2kxcv7xvhweoowj/GeoDa1.12.1.33-Installer.dmg?dl=0

Can you try this new version to verify the fix? Thanks!
