### ISSUE TITLE
REDCAP crash

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#1290]
Windows 8 1.12.1.37
Dataset used: Guerry with queen weights file loaded. No other weights files loaded. 
Variable selected: wealth
Method: First-order-ALK
Minimum bound checked. cl_crprop 
All other settings left as default. 

Save in Cluster in field CL. When I ran this, CL already existed and was populated by another set of values. 
I have sent a crash report for this.
![image](https://user-images.githubusercontent.com/22801047/32478397-2a52a032-c34a-11e7-8107-001927fddb43.png)

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.43
Verified

**Comment by VeraB620** [comment]
OS X El Capitan 10.11.6
GeoDa 1.12.1.141

Repeated same steps as YidanJ-Wu for Guerry and Columbus crime, ran 30 times each with no issue. Repeated using different parameters and data sets, running multiples times and had no crash.
