### ISSUE TITLE
Raw rates map is sometimes blank

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#1296]
Windows 8 1.12
Map > Rates calculated map > raw rates 
STATEFP over STATEFP quantile map (smaller window) is blank. 
This is not consistent. Sometimes the rates map is correctly generated. I also haven't seen this error in newer versions of GeoDa but that could just be a matter of further testing.
![image](https://user-images.githubusercontent.com/22801047/32590114-3d22fc3a-c4de-11e7-8290-5ae11b3fe210.png)
Edit: here is another raw rates map with the same dataset, different variables. AWATER/ALAND standard deviation map
![image](https://user-images.githubusercontent.com/22801047/32590203-c06cd2b4-c4de-11e7-8f9a-2fdeabe987de.png)

**Comment by lixun910** [comment]
Is this version 1.12.0.0?  I remember I fixed this issue in latest version. Can you verify it? Thanks!

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.39
Yes, I tested the latest version and it's fixed.
