### ISSUE TITLE
Problem with threshold distance spatial weights matrix

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#1312]
From a user's report about the threshold distance spatial weights matrix: 
> ![a1425904fe1142d5b0b72fb10ac0c171](https://user-images.githubusercontent.com/22801047/32740468-ad0e08b8-c868-11e7-9981-e357a79239be.png)
But, when I use it to run a spatial error model, GeoDa reports “-1.#IND” for Log likelihood, AIC, and LR test.  
![5995ea32005f415a832a3e68e1ea3e70](https://user-images.githubusercontent.com/22801047/32740486-bcea4e54-c868-11e7-9b8c-cc6f2652a50d.png)

I tried to replicate this in Windows 8 1.12.0 using her files and got a crash: 
![crash report](https://user-images.githubusercontent.com/22801047/32740655-2d25cbe4-c869-11e7-8e38-8d674a88a7fc.png)

Will test on newer versions of GeoDa as well. 

Edit: Also got a crash in Windows 8 1.12.1.47

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.47
The original file contained tracts for Arkansas, Mississippi, and Louisiana. I saved the Arkansas tracts as a separate file (Arkansas.shp) and ran the spatial error model on that, using a new weights file with same specifications (Arkansas2.gwt). This time, no crash (prev. crash might be due to file size). Output below: 
![image](https://user-images.githubusercontent.com/22801047/32741910-742d2132-c86d-11e7-8256-bff302a0e99b.png)

Will test on other versions of GeoDa.

**Comment by jkoschinsky** [comment]
from Xun:

There are two different algorithms for spatial lag/error estimation. One is for #obs <= 500, another is for #obs >500. We are talking about the latter in this use case:

I do think it's a bug, and related to computing the log-likelihood for both lag and error model using residuals (Y on X) and residuals (WY on X) -- in this case the computation returns NaN, which is not correct.

In more detail: the maximum size of polynomial is hard coded to 41 (I have no idea why). In this case, the size of one polynomial is 50 > 41 -- this cause the function to compute log of the polynomial returns NaN.
