### ISSUE TITLE
lab crash: Clustering features 1.12.1.7

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1319]
From: 
 Details:
os: 1-10-12
vs: 1-12-1-7
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
ConnectDatasourceDlg::OnSample()
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Applications/GeoDa.app/Contents/MacOS/../Resources/samples.sqlite
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open AbstractClusterDlg.
Open HClusterDlg.
InitVariableCombobox HClusterDlg.
Click HClusterDlg::OnOK

**Comment by lixun910** [comment]
This should be fixed. see https://github.com/GeoDaCenter/geoda/issues/1251
The students in lab should get upgrade to 1.12.1.47.
https://www.dropbox.com/s/uk04o5q46f4og8d/GeoDa1.12.1.47-Installer.dmg?dl=0
https://www.dropbox.com/s/d602yd0eccq9jn7/GeoDa-1.12.1.47-Windows-64bit.exe?dl=0
