### ISSUE TITLE
KMeans crash when minimum bound box checked without value

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1329]
From: lanselin@gmail.com
 Details:
os: 1-10-12
vs: 1-12-1-49
/Users/luc/Desktop/GeoDa.1.12.1.49.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
GdaFrame::OpenProject()
/Users/luc/Desktop/guerry/Guerry_85.gda
Entering Project::Project (existing project)
/Users/luc/Desktop/guerry/Guerry_85.gda
Project::SetProjectFullPath()
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/luc/Desktop/guerry/Guerry_85.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open AbstractClusterDlg.
Open KMeanDlg.
Close KMeansDlg
In GdaFrame::OnAddCentroids()
In Project::AddCentroids
Project::GetCentroids()
Open AbstractClusterDlg.
Open KMeanDlg.
Click KMeansDlg::OnOK

**Comment by lanselin** [comment]
very strange, cannot replicate. i started with the six variables and then added x and y. second time i started with x and y and then added the six variables, that worked.

**Comment by lixun910** [comment]
should be fixed in https://github.com/GeoDaCenter/geoda/issues/1360

vs: 1-12-1-49  Step1. Open KMeans
Step2. check minimum bound box
Step3. select variable and click OK

**Comment by VeraB620** [comment]
OS X El Capitan 10.11.6
GeoDa 1.12.1.141

No crash
<img width="842" alt="screen shot 2018-07-09 at 1 22 51 pm" src="https://user-images.githubusercontent.com/4943475/42468688-3a0918de-837b-11e8-86ae-53f93436d4be.png">

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.14.1
Verified

<img width="856" alt="screen shot 2018-07-16 at 1 41 28 pm" src="https://user-images.githubusercontent.com/37029239/42776878-02f31ed4-88fe-11e8-85b3-c2368bbfcb3e.png">
