### ISSUE TITLE
Regression crash with invalid variable

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1330]
From: 
 Details:
os: 1-10-11
vs: 1-12-0-0
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/vaishalichundi/Documents/MPH Semester 3/GIS/Final Project/Shapefile/UHF_34_DOHMH.shp
Open Layer:UHF_34_DOHMH
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/vaishalichundi/Documents/MPH Semester 3/GIS/Final Project/Shapefile/UHF_34_DOHMH.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnRegressionClassic()
Open RegressionDlg.
RegressionDlg::InitVariableList()
RegressionDlg::OnCButton1Click()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnCWeightCheckClick
Click RegressionDlg::OnCRadio2Selected
Click RegressionDlg::OnCRadio1Selected
Click RegressionDlg::OnCRadio2Selected
Click RegressionDlg::OnCWeightCheckClick
Click RegressionDlg::OnRunClick
y:Ratehops
x:
Percentint

**Comment by lixun910** [comment]
Step 1. Add a new variable (e.g. test) -- do not assign any values
Step 2. Open Regression dialog, specify variable "test" in regression model
Step 3. Click Run will crash GeoDa

**Comment by VeraB620** [comment]
OS X El Capitan 10.11.6
GeoDa 1.12.1.137

verified

<img width="461" alt="screen shot 2018-07-05 at 12 11 45 pm" src="https://user-images.githubusercontent.com/4943475/42337533-b6941b88-804c-11e8-8a97-9b4ed56921eb.png">
