### ISSUE TITLE
Crash: related to project file

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1333]
From: 
 Details:
os: 1-10-12
vs: 1-12-0-0
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/andrewrenninger/Desktop/R/Analytics/Aspatial/Census_Tracts_2000.shp
Open Layer:Census_Tracts_2000
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/andrewrenninger/Desktop/R/Analytics/Aspatial/Census_Tracts_2000.shp
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open MergeTableDlg.
In MergeTableDlg::OnClose()
Open MergeTableDlg.
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/andrewrenninger/Desktop/R/Analytics/Aspatial/Data.csv
Open Layer:Data
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
ds:/Users/andrewrenninger/Desktop/R/Analytics/Aspatial/Data.csv layer: Data
In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnKeyChoice()
Entering MergeTableDlg::OnIncAllClick()
In MergeTableDlg::OnMergeClick()
Open FieldNameCorrectionDlg:
ScrolledWidgetsPane::RemoveIllegalChars
STFID
STFID
ScrolledWidgetsPane::TruncateFieldName
STFID
ScrolledWidgetsPane::RenameDupFieldName
STFID
STFID_1
ScrolledWidgetsPane::RemoveIllegalChars
avg_hh_size
avg_hh_size
ScrolledWidgetsPane::TruncateFieldName
avg_hh_size
avg_h_size
ScrolledWidgetsPane::RenameDupFieldName
avg_h_size
avg_h_size
ScrolledWidgetsPane::RemoveIllegalChars
edu_collegeplus
edu_collegeplus
ScrolledWidgetsPane::TruncateFieldName
edu_collegeplus
edu_c_plus
ScrolledWidgetsPane::RenameDupFieldName
edu_c_plus
edu_c_plus
ScrolledWidgetsPane::RemoveIllegalChars
edu_highschool
edu_highschool
ScrolledWidgetsPane::TruncateFieldName
edu_highschool
edu_h_hool
ScrolledWidgetsPane::RenameDupFieldName
edu_h_hool
edu_h_hool
ScrolledWidgetsPane::RemoveIllegalChars
edu_less_highschool
edu_less_highschool
ScrolledWidgetsPane::TruncateFieldName
edu_less_highschool
edu_l_hool
ScrolledWidgetsPane::RenameDupFieldName
edu_l_hool
edu_l_hool
ScrolledWidgetsPane::RemoveIllegalChars
households_family
households_family
ScrolledWidgetsPane::TruncateFieldName
households_family
house_mily
ScrolledWidgetsPane::RenameDupFieldName
house_mily
house_mily
ScrolledWidgetsPane::RemoveIllegalChars
households_nonfamily
households_nonfamily
ScrolledWidgetsPane::TruncateFieldName
households_nonfamily
house_mily
ScrolledWidgetsPane::RenameDupFieldName
house_mily
ScrolledWidgetsPane::TruncateFieldName
house_mily
hous_ily
hous_ily_1
ScrolledWidgetsPane::RemoveIllegalChars
housing_median_age
housing_median_age
ScrolledWidgetsPane::TruncateFieldName
housing_median_age
housi__age
ScrolledWidgetsPane::RenameDupFieldName
housi__age
housi__age
ScrolledWidgetsPane::RemoveIllegalChars
housing_occupied
housing_occupied
ScrolledWidgetsPane::TruncateFieldName
housing_occupied
housi_pied
ScrolledWidgetsPane::RenameDupFieldName
housi_pied
housi_pied
ScrolledWidgetsPane::RemoveIllegalChars
housing_vacant
housing_vacant
ScrolledWidgetsPane::TruncateFieldName
housing_vacant
housi_cant
ScrolledWidgetsPane::RenameDupFieldName
housi_cant
housi_cant
ScrolledWidgetsPane::RemoveIllegalChars
median_hh_income
median_hh_income
ScrolledWidgetsPane::TruncateFieldName
median_hh_income
media_come
ScrolledWidgetsPane::RenameDupFieldName
media_come
media_come
ScrolledWidgetsPane::RemoveIllegalChars
per_capita_income
per_capita_income
ScrolledWidgetsPane::TruncateFieldName
per_capita_income
per_c_come
ScrolledWidgetsPane::RenameDupFieldName
per_c_come
per_c_come
ScrolledWidgetsPane::RemoveIllegalChars
percent_poverty
percent_poverty
ScrolledWidgetsPane::TruncateFieldName
percent_poverty
perce_erty
ScrolledWidgetsPane::RenameDupFieldName
perce_erty
perce_erty
ScrolledWidgetsPane::RemoveIllegalChars
pop_25_plus
pop_25_plus
ScrolledWidgetsPane::TruncateFieldName
pop_25_plus
pop_2_plus
ScrolledWidgetsPane::RenameDupFieldName
pop_2_plus
pop_2_plus
ScrolledWidgetsPane::RemoveIllegalChars
pop_civ_employed
pop_civ_employed
ScrolledWidgetsPane::TruncateFieldName
pop_civ_employed
pop_c_oyed
ScrolledWidgetsPane::RenameDupFieldName
pop_c_oyed
pop_c_oyed
ScrolledWidgetsPane::RemoveIllegalChars
pop_civ_unemployed
pop_civ_unemployed
ScrolledWidgetsPane::TruncateFieldName
pop_civ_unemployed
pop_c_oyed
ScrolledWidgetsPane::RenameDupFieldName
pop_c_oyed
ScrolledWidgetsPane::TruncateFieldName
pop_c_oyed
pop__yed
pop__yed_1
ScrolledWidgetsPane::RemoveIllegalChars
pop_density
pop_density
ScrolledWidgetsPane::TruncateFieldName
pop_density
pop_d_sity
ScrolledWidgetsPane::RenameDupFieldName
pop_d_sity
pop_d_sity
ScrolledWidgetsPane::RemoveIllegalChars
pop_hispanic
pop_hispanic
ScrolledWidgetsPane::TruncateFieldName
pop_hispanic
pop_h_anic
ScrolledWidgetsPane::RenameDupFieldName
pop_h_anic
pop_h_anic
ScrolledWidgetsPane::RemoveIllegalChars
pop_white_nonhispanic
pop_white_nonhispanic
ScrolledWidgetsPane::TruncateFieldName
pop_white_nonhispanic
pop_w_anic
ScrolledWidgetsPane::RenameDupFieldName
pop_w_anic
pop_w_anic
ScrolledWidgetsPane::RemoveIllegalChars
square_miles
square_miles
ScrolledWidgetsPane::TruncateFieldName
square_miles
squar_iles
ScrolledWidgetsPane::RenameDupFieldName
squar_iles
squar_iles
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
STFID_1
ScrolledWidgetsPane::IsFieldNameValid
avg_h_size
ScrolledWidgetsPane::IsFieldNameValid
edu_c_plus
ScrolledWidgetsPane::IsFieldNameValid
edu_hs
ScrolledWidgetsPane::IsFieldNameValid
edu_l_hs
ScrolledWidgetsPane::IsFieldNameValid
house_fam
ScrolledWidgetsPane::IsFieldNameValid
house_non
ScrolledWidgetsPane::IsFieldNameValid
housi__age
ScrolledWidgetsPane::IsFieldNameValid
housi_pied
ScrolledWidgetsPane::IsFieldNameValid
housi_cant
ScrolledWidgetsPane::IsFieldNameValid
media_come
ScrolledWidgetsPane::IsFieldNameValid
per_c_come
ScrolledWidgetsPane::IsFieldNameValid
per_pov
ScrolledWidgetsPane::IsFieldNameValid
pop_25
ScrolledWidgetsPane::IsFieldNameValid
pop_emp
ScrolledWidgetsPane::IsFieldNameValid
pop_unemp
ScrolledWidgetsPane::IsFieldNameValid
pop_dense
ScrolledWidgetsPane::IsFieldNameValid
pop_hisp
ScrolledWidgetsPane::IsFieldNameValid
pop_whit
ScrolledWidgetsPane::IsFieldNameValid
sq_miles
Exit FieldNameCorrectionDlg
In MergeTableDlg::OnMergeClick()
Open FieldNameCorrectionDlg:
ScrolledWidgetsPane::RemoveIllegalChars
STFID
STFID
ScrolledWidgetsPane::TruncateFieldName
STFID
ScrolledWidgetsPane::RenameDupFieldName
STFID
STFID_1
ScrolledWidgetsPane::RemoveIllegalChars
avg_hh_size
avg_hh_size
ScrolledWidgetsPane::TruncateFieldName
avg_hh_size
avg_h_size
ScrolledWidgetsPane::RenameDupFieldName
avg_h_size
avg_h_size
ScrolledWidgetsPane::RemoveIllegalChars
edu_collegeplus
edu_collegeplus
ScrolledWidgetsPane::TruncateFieldName
edu_collegeplus
edu_c_plus
ScrolledWidgetsPane::RenameDupFieldName
edu_c_plus
edu_c_plus
ScrolledWidgetsPane::RemoveIllegalChars
edu_highschool
edu_highschool
ScrolledWidgetsPane::TruncateFieldName
edu_highschool
edu_h_hool
ScrolledWidgetsPane::RenameDupFieldName
edu_h_hool
edu_h_hool
ScrolledWidgetsPane::RemoveIllegalChars
edu_less_highschool
edu_less_highschool
ScrolledWidgetsPane::TruncateFieldName
edu_less_highschool
edu_l_hool
ScrolledWidgetsPane::RenameDupFieldName
edu_l_hool
edu_l_hool
ScrolledWidgetsPane::RemoveIllegalChars
households_family
households_family
ScrolledWidgetsPane::TruncateFieldName
households_family
house_mily
ScrolledWidgetsPane::RenameDupFieldName
house_mily
house_mily
ScrolledWidgetsPane::RemoveIllegalChars
households_nonfamily
households_nonfamily
ScrolledWidgetsPane::TruncateFieldName
households_nonfamily
house_mily
ScrolledWidgetsPane::RenameDupFieldName
house_mily
ScrolledWidgetsPane::TruncateFieldName
house_mily
hous_ily
hous_ily_1
ScrolledWidgetsPane::RemoveIllegalChars
housing_median_age
housing_median_age
ScrolledWidgetsPane::TruncateFieldName
housing_median_age
housi__age
ScrolledWidgetsPane::RenameDupFieldName
housi__age
housi__age
ScrolledWidgetsPane::RemoveIllegalChars
housing_occupied
housing_occupied
ScrolledWidgetsPane::TruncateFieldName
housing_occupied
housi_pied
ScrolledWidgetsPane::RenameDupFieldName
housi_pied
housi_pied
ScrolledWidgetsPane::RemoveIllegalChars
housing_vacant
housing_vacant
ScrolledWidgetsPane::TruncateFieldName
housing_vacant
housi_cant
ScrolledWidgetsPane::RenameDupFieldName
housi_cant
housi_cant
ScrolledWidgetsPane::RemoveIllegalChars
median_hh_income
median_hh_income
ScrolledWidgetsPane::TruncateFieldName
median_hh_income
media_come
ScrolledWidgetsPane::RenameDupFieldName
media_come
media_come
ScrolledWidgetsPane::RemoveIllegalChars
per_capita_income
per_capita_income
ScrolledWidgetsPane::TruncateFieldName
per_capita_income
per_c_come
ScrolledWidgetsPane::RenameDupFieldName
per_c_come
per_c_come
ScrolledWidgetsPane::RemoveIllegalChars
percent_poverty
percent_poverty
ScrolledWidgetsPane::TruncateFieldName
percent_poverty
perce_erty
ScrolledWidgetsPane::RenameDupFieldName
perce_erty
perce_erty
ScrolledWidgetsPane::RemoveIllegalChars
pop_25_plus
pop_25_plus
ScrolledWidgetsPane::TruncateFieldName
pop_25_plus
pop_2_plus
ScrolledWidgetsPane::RenameDupFieldName
pop_2_plus
pop_2_plus
ScrolledWidgetsPane::RemoveIllegalChars
pop_civ_employed
pop_civ_employed
ScrolledWidgetsPane::TruncateFieldName
pop_civ_employed
pop_c_oyed
ScrolledWidgetsPane::RenameDupFieldName
pop_c_oyed
pop_c_oyed
ScrolledWidgetsPane::RemoveIllegalChars
pop_civ_unemployed
pop_civ_unemployed
ScrolledWidgetsPane::TruncateFieldName
pop_civ_unemployed
pop_c_oyed
ScrolledWidgetsPane::RenameDupFieldName
pop_c_oyed
ScrolledWidgetsPane::TruncateFieldName
pop_c_oyed
pop__yed
pop__yed_1
ScrolledWidgetsPane::RemoveIllegalChars
pop_density
pop_density
ScrolledWidgetsPane::TruncateFieldName
pop_density
pop_d_sity
ScrolledWidgetsPane::RenameDupFieldName
pop_d_sity
pop_d_sity
ScrolledWidgetsPane::RemoveIllegalChars
pop_hispanic
pop_hispanic
ScrolledWidgetsPane::TruncateFieldName
pop_hispanic
pop_h_anic
ScrolledWidgetsPane::RenameDupFieldName
pop_h_anic
pop_h_anic
ScrolledWidgetsPane::RemoveIllegalChars
pop_white_nonhispanic
pop_white_nonhispanic
ScrolledWidgetsPane::TruncateFieldName
pop_white_nonhispanic
pop_w_anic
ScrolledWidgetsPane::RenameDupFieldName
pop_w_anic
pop_w_anic
ScrolledWidgetsPane::RemoveIllegalChars
square_miles
square_miles
ScrolledWidgetsPane::TruncateFieldName
square_miles
squar_iles
ScrolledWidgetsPane::RenameDupFieldName
squar_iles
squar_iles
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
STFID_1
ScrolledWidgetsPane::IsFieldNameValid
avg_h_size
ScrolledWidgetsPane::IsFieldNameValid
edu_c_plus
ScrolledWidgetsPane::IsFieldNameValid
edu_h_hool
ScrolledWidgetsPane::IsFieldNameValid
edu_l_hool
ScrolledWidgetsPane::IsFieldNameValid
house_mily
ScrolledWidgetsPane::IsFieldNameValid
hous_ily_1
ScrolledWidgetsPane::IsFieldNameValid
housi__age
ScrolledWidgetsPane::IsFieldNameValid
housi_pied
ScrolledWidgetsPane::IsFieldNameValid
housi_cant
ScrolledWidgetsPane::IsFieldNameValid
media_come
ScrolledWidgetsPane::IsFieldNameValid
per_c_come
ScrolledWidgetsPane::IsFieldNameValid
perce_erty
ScrolledWidgetsPane::IsFieldNameValid
pop_2_plus
ScrolledWidgetsPane::IsFieldNameValid
pop_c_oyed
ScrolledWidgetsPane::IsFieldNameValid
pop__yed_1
ScrolledWidgetsPane::IsFieldNameValid
pop_d_sity
ScrolledWidgetsPane::IsFieldNameValid
pop_h_anic
ScrolledWidgetsPane::IsFieldNameValid
pop_w_anic
ScrolledWidgetsPane::IsFieldNameValid
squar_iles
Exit FieldNameCorrectionDlg
In MergeTableDlg::OnMergeClick()
Open FieldNameCorrectionDlg:
ScrolledWidgetsPane::RemoveIllegalChars
STFID
STFID
ScrolledWidgetsPane::TruncateFieldName
STFID
ScrolledWidgetsPane::RenameDupFieldName
STFID
STFID_1
ScrolledWidgetsPane::RemoveIllegalChars
avg_hh_size
avg_hh_size
ScrolledWidgetsPane::TruncateFieldName
avg_hh_size
avg_h_size
ScrolledWidgetsPane::RenameDupFieldName
avg_h_size
avg_h_size
ScrolledWidgetsPane::RemoveIllegalChars
edu_collegeplus
edu_collegeplus
ScrolledWidgetsPane::TruncateFieldName
edu_collegeplus
edu_c_plus
ScrolledWidgetsPane::RenameDupFieldName
edu_c_plus
edu_c_plus
ScrolledWidgetsPane::RemoveIllegalChars
edu_highschool
edu_highschool
ScrolledWidgetsPane::TruncateFieldName
edu_highschool
edu_h_hool
ScrolledWidgetsPane::RenameDupFieldName
edu_h_hool
edu_h_hool
ScrolledWidgetsPane::RemoveIllegalChars
edu_less_highschool
edu_less_highschool
ScrolledWidgetsPane::TruncateFieldName
edu_less_highschool
edu_l_hool
ScrolledWidgetsPane::RenameDupFieldName
edu_l_hool
edu_l_hool
ScrolledWidgetsPane::RemoveIllegalChars
households_family
households_family
ScrolledWidgetsPane::TruncateFieldName
households_family
house_mily
ScrolledWidgetsPane::RenameDupFieldName
house_mily
house_mily
ScrolledWidgetsPane::RemoveIllegalChars
households_nonfamily
households_nonfamily
ScrolledWidgetsPane::TruncateFieldName
households_nonfamily
house_mily
ScrolledWidgetsPane::RenameDupFieldName
house_mily
ScrolledWidgetsPane::TruncateFieldName
house_mily
hous_ily
hous_ily_1
ScrolledWidgetsPane::RemoveIllegalChars
housing_median_age
housing_median_age
ScrolledWidgetsPane::TruncateFieldName
housing_median_age
housi__age
ScrolledWidgetsPane::RenameDupFieldName
housi__age
housi__age
ScrolledWidgetsPane::RemoveIllegalChars
housing_occupied
housing_occupied
ScrolledWidgetsPane::TruncateFieldName
housing_occupied
housi_pied
ScrolledWidgetsPane::RenameDupFieldName
housi_pied
housi_pied
ScrolledWidgetsPane::RemoveIllegalChars
housing_vacant
housing_vacant
ScrolledWidgetsPane::TruncateFieldName
housing_vacant
housi_cant
ScrolledWidgetsPane::RenameDupFieldName
housi_cant
housi_cant
ScrolledWidgetsPane::RemoveIllegalChars
median_hh_income
median_hh_income
ScrolledWidgetsPane::TruncateFieldName
median_hh_income
media_come
ScrolledWidgetsPane::RenameDupFieldName
media_come
media_come
ScrolledWidgetsPane::RemoveIllegalChars
per_capita_income
per_capita_income
ScrolledWidgetsPane::TruncateFieldName
per_capita_income
per_c_come
ScrolledWidgetsPane::RenameDupFieldName
per_c_come
per_c_come
ScrolledWidgetsPane::RemoveIllegalChars
percent_poverty
percent_poverty
ScrolledWidgetsPane::TruncateFieldName
percent_poverty
perce_erty
ScrolledWidgetsPane::RenameDupFieldName
perce_erty
perce_erty
ScrolledWidgetsPane::RemoveIllegalChars
pop_25_plus
pop_25_plus
ScrolledWidgetsPane::TruncateFieldName
pop_25_plus
pop_2_plus
ScrolledWidgetsPane::RenameDupFieldName
pop_2_plus
pop_2_plus
ScrolledWidgetsPane::RemoveIllegalChars
pop_civ_employed
pop_civ_employed
ScrolledWidgetsPane::TruncateFieldName
pop_civ_employed
pop_c_oyed
ScrolledWidgetsPane::RenameDupFieldName
pop_c_oyed
pop_c_oyed
ScrolledWidgetsPane::RemoveIllegalChars
pop_civ_unemployed
pop_civ_unemployed
ScrolledWidgetsPane::TruncateFieldName
pop_civ_unemployed
pop_c_oyed
ScrolledWidgetsPane::RenameDupFieldName
pop_c_oyed
ScrolledWidgetsPane::TruncateFieldName
pop_c_oyed
pop__yed
pop__yed_1
ScrolledWidgetsPane::RemoveIllegalChars
pop_density
pop_density
ScrolledWidgetsPane::TruncateFieldName
pop_density
pop_d_sity
ScrolledWidgetsPane::RenameDupFieldName
pop_d_sity
pop_d_sity
ScrolledWidgetsPane::RemoveIllegalChars
pop_hispanic
pop_hispanic
ScrolledWidgetsPane::TruncateFieldName
pop_hispanic
pop_h_anic
ScrolledWidgetsPane::RenameDupFieldName
pop_h_anic
pop_h_anic
ScrolledWidgetsPane::RemoveIllegalChars
pop_white_nonhispanic
pop_white_nonhispanic
ScrolledWidgetsPane::TruncateFieldName
pop_white_nonhispanic
pop_w_anic
ScrolledWidgetsPane::RenameDupFieldName
pop_w_anic
pop_w_anic
ScrolledWidgetsPane::RemoveIllegalChars
square_miles
square_miles
ScrolledWidgetsPane::TruncateFieldName
square_miles
squar_iles
ScrolledWidgetsPane::RenameDupFieldName
squar_iles
squar_iles
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
STFID_1
ScrolledWidgetsPane::IsFieldNameValid
avg_hh
ScrolledWidgetsPane::IsFieldNameValid
edu_c_plus
ScrolledWidgetsPane::IsFieldNameValid
edu_h_HS
ScrolledWidgetsPane::IsFieldNameValid
edu_l_HS
ScrolledWidgetsPane::IsFieldNameValid
house_fam
ScrolledWidgetsPane::IsFieldNameValid
hous_non
ScrolledWidgetsPane::IsFieldNameValid
housi__age
ScrolledWidgetsPane::IsFieldNameValid
housi_pied
ScrolledWidgetsPane::IsFieldNameValid
housi_cant
ScrolledWidgetsPane::IsFieldNameValid
med_income
ScrolledWidgetsPane::IsFieldNameValid
per_c_come
ScrolledWidgetsPane::IsFieldNameValid
per_pov
ScrolledWidgetsPane::IsFieldNameValid
pop_25
ScrolledWidgetsPane::IsFieldNameValid
pop_emp
ScrolledWidgetsPane::IsFieldNameValid
pop_unemp
ScrolledWidgetsPane::IsFieldNameValid
pop_dens
ScrolledWidgetsPane::IsFieldNameValid
pop_hisp
ScrolledWidgetsPane::IsFieldNameValid
pop_white
ScrolledWidgetsPane::IsFieldNameValid
sq_miles
Exit FieldNameCorrectionDlg
In MergeTableDlg::OnCloseClick()
In TableFrame::OnActivate
Open PCPDlg.
Click PCPDlg::OnOkClick
Open PCPFrame.
Open PCPDlg.
Click PCPDlg::OnOkClick
Open PCPFrame.
Open PCPDlg.
Click PCPDlg::OnOkClick
Open PCPFrame.
Open PCPDlg.
Click PCPDlg::OnOkClick
Open PCPFrame.
Entering GdaFrame::OnMapChoices
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
pop_change
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnCanvasBackgroundColor
Click GdaFrame::OnCanvasBackgroundColor
In GdaFrame::OnViewStandardizedData()
In GdaFrame::OnViewOriginalData()
Open PCPDlg.
Click PCPDlg::OnOkClick
Open PCPFrame.
In GdaFrame::ChangeToQuantile(5)
In GdaFrame::OnDisplayStatistics()
In GdaFrame::OnDisplayStatistics()
MapCanvas::~MapCanvas()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
Click GdaFrame::OnLegendUseScientificNotation
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnLegendUseScientificNotation
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnLegendUseScientificNotation
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnLegendUseScientificNotation
MapCanvas::CreateAndUpdateCategories()
Open ScatterPlotMatFrame.
In ScatterPlotMatFrame::OnActivate
In ScatterPlotMatFrame::OnActivate
Open ScatterPlotMatFrame.
In ScatterPlotMatFrame::OnActivate
Open PCPDlg.
Click PCPDlg::OnCancelClick
Open PCPDlg.
Click PCPDlg::OnCancelClick
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
pop
LOGRECNO
STFID_1
Open C3DPlotCanvas.
Close C3DPlotCanvas.
Open PCPDlg.
Click PCPDlg::OnOkClick
Open PCPFrame.
Open PCPDlg.
Click PCPDlg::OnOkClick
Open PCPFrame.
Open PCPDlg.
Click PCPDlg::OnOkClick
Open PCPFrame.
Open PCPDlg.
Click PCPDlg::OnOkClick
Open PCPFrame.
Open PCPDlg.
Click PCPDlg::OnOkClick
Open PCPFrame.
Open PCPDlg.
Click PCPDlg::OnOkClick
Open PCPFrame.
Open PCPDlg.
Click PCPDlg::OnOkClick
Open PCPFrame.
Open PCPDlg.
Click PCPDlg::OnOkClick
Open PCPFrame.
Open PCPDlg.
Click PCPDlg::OnOkClick
Open PCPFrame.
Click GdaFrame::OnClose
Project::GetProjectFullPath()
Click GdaFrame::OnClose
Project::GetProjectFullPath()

**Comment by jkoschinsky** [comment]
there's a bunch of crashes that seem to be related to the project file (if I'm reading this right).
Since we haven't stress-tested the project file much, let's do that, including saving changes after weights creation and working with lots of windows.

**Comment by YidanJ-Wu** [comment]
Haven't had any project file crashes yet but I'll pay extra attention to that feature when testing
