### ISSUE TITLE
Differential Local Morans I cannot run

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#1335]
From a user: 
> we are encountered with the similar problems using GeoDa 1.12 as previously having been encountered with GeoDa 1.10 in June. Thus, the first problem is related to Differential Local Moran's I ESDA tool which is colored a grey. Hence, one cannot run the analysis anyway although he/she has already prepared spatial weights as well as edit times variables in accordance to recommended steps on the pull down menu. 

I ran Differential Local Moran's I with their dataset in 1.12.1.49 and it worked correctly (screenshots below). Will try previous version as well. 
![image](https://user-images.githubusercontent.com/22801047/32919505-b6c0ec6a-caeb-11e7-9694-3a6692827d6d.png)

![image](https://user-images.githubusercontent.com/22801047/32919494-a75b50b2-caeb-11e7-9a4c-9fa754b81283.png)

**Comment by lixun910** [comment]
#1238 same issue and user reports issue has been fixed in latest geoda
