### ISSUE TITLE
Clusters tool does not work when there are more than 1000 observations

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#1336]
From the same user as [Issue 335](https://github.com/GeoDaCenter/geoda/issues/1335): 
> The second problem deals with running all methods within 'Clusters' tool where no analysis cannot be done with approx. more than 1000 polygons as the software shuts down or no responses after clicking on the 'Run' button at every time. 

I tested using their dataset which had 1216 polygons, in 1.12.1.49 and it worked correctly (screenshots below). Will test on older versions. 
![image](https://user-images.githubusercontent.com/22801047/32924688-6da3a230-cb03-11e7-83ec-8712ca4d1d82.png)

**Comment by lixun910** [comment]
same with #1238 
User also reports working fine in latest version: https://github.com/GeoDaCenter/geoda/issues/1238
