### ISSUE TITLE
Z value incorrectly calculated

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#1341]
Windows 8 1.12.1.47
I ran Local Univariate Moran's I on a dataset that appears to have clustering. However, the Z-value was calculated as 0.599 which leads me to believe there might be a bug. 
![image](https://user-images.githubusercontent.com/22801047/33088699-005781c4-ceb4-11e7-9cc4-97017f7c85d1.png)
![image](https://user-images.githubusercontent.com/22801047/33088719-0e59e49c-ceb4-11e7-9f24-409bd7ee19f0.png)
Edit: I may just have an unusual dataset.

**Comment by jkoschinsky** [comment]
Additional notes on this:
The z-score should be I-mean/sd = 0.6590 - (-0.0133)/1.1218 = 0.6709 but
it's 0.5993
and the line for the mean (which I believe is the blue line) should be
-0.0133 but it's placed on the x-axis as larger than I (0.6590).

**Comment by lixun910** [comment]
I will check this. But, the LISA is based on 999 permutation, and global randomization is based on 99999 permutations. 

For Z score value, should it be (0.6590 - -0.0133) / 1.1218 = 0.5993?

**Comment by lanselin** [comment]
0.5993 is the correct result for the z-value

**Comment by jkoschinsky** [comment]
Yes, you're right, it is 0.599304689.
The LISA is independent anyway since you could have significant local
clusters and non-significant global Moran's I but in this case, regardless
of the LISA, there seems to be something off with the mean placement on the
x-axis?

**Comment by YidanJ-Wu** [comment]
To follow up: 
In the first screenshot that I posted, the pseudo p value window was resized. Here's how it looked before resizing: 
![image](https://user-images.githubusercontent.com/22801047/33098945-b761e5ba-ced4-11e7-8106-921a51a65f10.png)

I also found out the reason for the low z-value. MedYrBuilt, the value being analyzed, is years as integers. 1996, 1999, etc. When analyzing another value calculated from (2017 - MedYrBuilt) the distribution looks more like a bell curve with high z value. 
![image](https://user-images.githubusercontent.com/22801047/33099007-f31a3d1e-ced4-11e7-8bad-9dd5817b95db.png)

**Comment by lixun910** [comment]
Is there missing values in this variable? Can you share the data with me?

**Comment by lixun910** [comment]
From Julie: To follow up, I modified the dataset so that the blank value is now an arbitrary integer. The distribution now looks like a bell curve. Thank you for pointing this out! 

This should be handled by GeoDa even with "blank" value in selected variable. I am fixing this. Thanks!

**Comment by lixun910** [comment]
@YidanJ-Wu Thanks for finding this issue! Can you verify it in 1.12.1.55? Thanks!

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.55
Verified
![image](https://user-images.githubusercontent.com/22801047/33224809-1c520346-d133-11e7-9e6e-3bd6ced4944f.png)
