### ISSUE TITLE
Add Neighbors to Selection option missing from map

### ISSUE THREAD

**Issue by anvalanz** [GeoDaCenter/geoda#1343]
I have read the  tutorial: Contiguity-Based Spatial Weights and 
when I have tried to use the option "Add Neighbors to Selection" from a table everything was fine (see the attached file 
![selection_tool_from_table](https://user-images.githubusercontent.com/6723429/33111904-af57ab62-cf50-11e7-9bc8-1058125bfd87.png)
but when I tried to do the same from a map the option was not available (see the attached file)
![selection_tool_missing_from_map](https://user-images.githubusercontent.com/6723429/33111931-d81a3b28-cf50-11e7-9d15-8f06ca3f5972.png) 
although there was an active selection as you can see from the screen capture and as suggested from footnote 2.
I am working with GeoDa 1.12 on Win 10.

**Comment by lixun910** [comment]
@anvalanz  Try the latest GeoDa 1.12.1.47: http://geodacenter.github.io/download_windows.html
You will see a map menu option "Selection and Neighbors":
<img width="418" alt="screen shot 2017-11-22 at 9 31 09 am" src="https://user-images.githubusercontent.com/2423887/33138736-791f74e0-cf68-11e7-9eee-520d5a4d819e.png">
