### ISSUE TITLE
Save image to file not responding

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#1344]
Windows 8 1.12.1.47
I tried to save an image to a file in GeoDa. After right-clicking to create a new folder for my image, GeoDa froze. Might just be a Windows problem. 
![image](https://user-images.githubusercontent.com/22801047/33139427-e0311954-cf72-11e7-9604-05a52e6f9c7b.png)

**Comment by lixun910** [comment]
@YidanJ-Wu Thanks! This should be either windows issue or wxwidgets issue.
