### ISSUE TITLE
threshold distance for polygons

### ISSUE THREAD

**Issue by anvalanz** [GeoDaCenter/geoda#1346]
I am reading the tutorial "Distance-based Spatial Weights" and I have calculated the distance-band weights for the shapefile natregimes (see the attached screenshot)
![screenshot_threshold_distance_weights](https://user-images.githubusercontent.com/6723429/33183135-f03546b8-d076-11e7-99cc-027a8b89ace2.JPG)
When I inspect the gwt file just created, for the obs 6071, which has only 1 neighbor, I do not find the value 90.865247  (threshold distance calculated by the sw) but the value 76.6758507  (see the attached screenshot)
![gwt](https://user-images.githubusercontent.com/6723429/33183244-5a987a84-d077-11e7-8689-b6356ad60119.JPG)
What's the reason for such difference ?

**Comment by anvalanz** [comment]
I have analyzed the gwt  and I have found that 
the threshold distance 90.865247 is for the connection 32007 16083

**Comment by lanselin** [comment]
Fixed example in workbook, should be Elko county, NV, not San Bernardino
