### ISSUE TITLE
Crash Report: shahrzadjune@gmail.com

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1353]
From: shahrzadjune@gmail.com
 Details:
os: 1-10-13
vs: 1-12-0-0
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/Shahrzad/Columbia /GIS/Final Project/Final Shapefile for all opioid deaths and education11_15_17 2_53/opioid_andeverything11_15_17_2_53pm.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnCreateNewIdClick
Try to insert unique id (integer, POLY_ID) column in table.
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnCRadioQueenSelected
Click CreatingWeightDlg::OnCSpinOrderofcontiguityUpdated
Click CreatingWeightDlg::OnCreateClick
In WeightsManFrame::OnActivate
CreateWeights()/Users/Shahrzad/Columbia /GIS/Final Project/File for Geoda/weights_2ndorder_11_23_9_22/opioid_andeverything11_15_17_2_53pm.gal
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnActivate
Close CreatingWeightDlg
In WeightsManFrame::OnActivate
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
In WeightsManFrame::OnActivate
Click VariableSettingsDlg::OnOkClick:
JORates
VariableSettingsDlg::GetWeightsId() weight: opioid_andeverything11_15_17_2_53pm
In WeightsManFrame::OnActivate
VariableSettingsDlg::GetWeightsId() weight: opioid_andeverything11_15_17_2_53pm
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Entering LisaCoordinator::LisaCoordinator().
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
Entering LisaCoordinator::InitFromVarInfo()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Entering LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::CalcLisa()
Entering LisaCoordinator::CalcPseudoP()
Entering LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP()
Exiting LisaCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
In LisaCoordinator::registerObserver()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::removeObserver
Exiting LisaCoordinator::removeObserver
Entering LisaCoordinator::removeObserver
Exiting LisaCoordinator::removeObserver
MapCanvas::~MapCanvas()
Entering LisaCoordinator::removeObserver
In LisaCoordinator::~LisaCoordinator().
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::removeObserver
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In GdaFrame::OnRegressionClassic()
Open RegressionDlg.
RegressionDlg::InitVariableList()
RegressionDlg::OnCButton1Click()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnRunClick
y:JORates
x:
Perc_BA
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnClose()
Close RegressionDlg.
Click RegressionDlg::OnCResetClick
RegressionDlg::InitVariableList()
RegressionDlg::~RegressionDlg()
In TableFrame::OnActivate
In TableFrame::OnActivate
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
In WeightsManFrame::OnActivate
Click VariableSettingsDlg::OnOkClick:
JORates
VariableSettingsDlg::GetWeightsId() weight: opioid_andeverything11_15_17_2_53pm
In WeightsManFrame::OnActivate
VariableSettingsDlg::GetWeightsId() weight: opioid_andeverything11_15_17_2_53pm
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Entering LisaCoordinator::LisaCoordinator().
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
Entering LisaCoordinator::InitFromVarInfo()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Entering LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::CalcLisa()
Entering LisaCoordinator::CalcPseudoP()
Entering LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP()
Exiting LisaCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
In LisaCoordinator::registerObserver()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
In GdaFrame::OnRegressionClassic()
Open RegressionDlg.
RegressionDlg::InitVariableList()
RegressionDlg::OnCButton1Click()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnCWeightCheckClick
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Click RegressionDlg::OnRunClick
y:JORates
x:
Perc_HS
OLS model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In GdaFrame::OnRegressionClassic()
RegressionDlg::OnCListVarinDoubleClicked()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnRunClick
y:JORates
x:
Perc_HS
Perc_BA
OLS model
RegressionDlg::DisplayRegression()
Click RegressionDlg::OnRunClick
y:JORates
x:
Perc_HS
Perc_BA
OLS model
RegressionDlg::DisplayRegression()
RegressionDlg::~RegressionDlg()
Close RegressionDlg.
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In GdaFrame::OnRegressionClassic()
Open RegressionDlg.
RegressionDlg::InitVariableList()
In WeightsManFrame::OnActivate
RegressionDlg::OnCListVarinDoubleClicked()
RegressionDlg::OnCButton1Click()
RegressionDlg::OnCListVarinDoubleClicked()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnCWeightCheckClick
Click RegressionDlg::OnRunClick
y:JORates
x:
Perc_HS
OLS model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
RegressionDlg::OnCButton3Click()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnRunClick
y:JORates
x:
Perc_HS
OLS model
RegressionDlg::DisplayRegression()
Click RegressionDlg::OnCSaveRegressionClick
Click RegressionDlg::OnCRadio2Selected
Click RegressionDlg::OnRunClick
y:JORates
x:
Perc_HS
Spatial Lag model
RegressionDlg::DisplayRegression()
Click RegressionDlg::OnCSaveRegressionClick
RegressionDlg::OnCButton3Click()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnRunClick
y:JORates
x:
Perc_BA
Spatial Lag model
RegressionDlg::DisplayRegression()
RegressionDlg::OnCButton3Click()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnRunClick
y:JORates
x:
Perc_HS
Spatial Lag model
RegressionDlg::DisplayRegression()
Click RegressionDlg::OnRunClick
y:JORates
x:
Perc_HS
Spatial Lag model
RegressionDlg::DisplayRegression()
Click RegressionDlg::OnRunClick
y:JORates
x:
Perc_HS
Spatial Lag model
RegressionDlg::DisplayRegression()
RegressionDlg::OnCButton3Click()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnRunClick
y:JORates
x:
Perc_HS
Spatial Lag model
RegressionDlg::DisplayRegression()
RegressionDlg::OnCButton3Click()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnRunClick
y:JORates
x:
Perc_BA
Spatial Lag model
RegressionDlg::DisplayRegression()
Click RegressionDlg::OnRunClick
y:JORates
x:
Perc_BA
Spatial Lag model
RegressionDlg::DisplayRegression()
Entering LisaCoordinator::removeObserver
Exiting LisaCoordinator::removeObserver
MapCanvas::~MapCanvas()
RegressionDlg::OnCButton4Click()
RegressionDlg::OnCButton5Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::~RegressionDlg()
Close RegressionDlg.
In WeightsManFrame::OnActivate
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
In WeightsManFrame::OnActivate
Click VariableSettingsDlg::OnOkClick:
OLS_RESIDU
VariableSettingsDlg::GetWeightsId() weight: opioid_andeverything11_15_17_2_53pm
In WeightsManFrame::OnActivate
VariableSettingsDlg::GetWeightsId() weight: opioid_andeverything11_15_17_2_53pm
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Entering LisaCoordinator::LisaCoordinator().
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
Entering LisaCoordinator::InitFromVarInfo()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Entering LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::CalcLisa()
Entering LisaCoordinator::CalcPseudoP()
Entering LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP()
Exiting LisaCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
In LisaCoordinator::registerObserver()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
LAG_RESIDU
VariableSettingsDlg::GetWeightsId() weight: opioid_andeverything11_15_17_2_53pm
VariableSettingsDlg::GetWeightsId() weight: opioid_andeverything11_15_17_2_53pm
Entering LisaCoordinator::LisaCoordinator().
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
Entering LisaCoordinator::InitFromVarInfo()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Entering LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::CalcLisa()
Entering LisaCoordinator::CalcPseudoP()
Entering LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP()
Exiting LisaCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
In LisaCoordinator::registerObserver()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
In OnRan999Per()
Open RandomizationDlg (univariate).
Close RandomizationDlg
In OnRan999Per()
Open RandomizationDlg (univariate).
Close RandomizationDlg
Entering LisaCoordinator::removeObserver
Exiting LisaCoordinator::removeObserver
Entering LisaCoordinator::removeObserver
Exiting LisaCoordinator::removeObserver
In GdaFrame::OnRegressionClassic()
Open RegressionDlg.
RegressionDlg::InitVariableList()
RegressionDlg::OnCListVarinDoubleClicked()
RegressionDlg::OnCButton1Click()
RegressionDlg::OnCButton3Click()
Click RegressionDlg::OnCResetClick
RegressionDlg::InitVariableList()
RegressionDlg::OnCListVarinDoubleClicked()
RegressionDlg::OnCButton1Click()
RegressionDlg::OnCListVarinDoubleClicked()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnCWeightCheckClick
Click RegressionDlg::OnRunClick
y:JORates
x:
OLS_RESIDU
OLS model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
Open ExportDataDlg in its Init()
In ExportDataDlg::OnOkClick()
ds:
In RegressionReportDlg::OnClose()
Close RegressionDlg.
RegressionDlg::OnCButton3Click()
RegressionDlg::OnCListVarinDoubleClicked()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnRunClick
y:JORates
x:
OLS_RESIDU
OLS model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnClose()
Close RegressionDlg.
RegressionDlg::OnCButton3Click()
RegressionDlg::OnCListVarinDoubleClicked()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnRunClick
y:JORates
x:
Perc_BA
OLS model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnClose()
Close RegressionDlg.
RegressionDlg::OnCButton3Click()
RegressionDlg::OnCListVarinDoubleClicked()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnCRadio2Selected
Click RegressionDlg::OnRunClick
y:JORates
x:
Perc_BA
Spatial Lag model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnClose()
Close RegressionDlg.
Click RegressionDlg::OnCSaveRegressionClick
RegressionDlg::~RegressionDlg()
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Click GdaFrame::OnClose
Project::GetProjectFullPath()
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Click GdaFrame::OnClose
Project::GetProjectFullPath()
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate

**Comment by lixun910** [comment]
Hi shahrzadjune@gmail.com <mailto:shahrzadjune@gmail.com>

Thanks for reporting this issue!  Can you share your data with us for replicate and fix this issue? We will keep your data confidential. 

Best,

Xun Li, Ph.D.

Assistant Director for Data Science
Center of Spatial Data Science
University of Chicago

**Comment by jkoschinsky** [comment]
regression crash - logged
