### ISSUE TITLE
Can't save table after delete a column which is positioned after a grouped variable

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1354]
From: zhaofy@uchicago.edu
 Details:
os: 1-10-12
vs: 1-12-1-47
/Applications/1Spatial Data/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
GdaFrame::OpenProject()

Entering Project::Project (existing project)

Project::SetProjectFullPath()
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:

Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()

GdaFrame::OpenProject()

Project::GetProjectFullPath()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
Open MergeTableDlg.
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()

Open Layer:census
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick

In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnClose()
In TableFrame::OnActivate
Open MergeTableDlg.
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()

Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick

In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnKeyChoice()
Entering MergeTableDlg::OnIncAllClick()
Entering MergeTableDlg::OnExclOneClick()
In MergeTableDlg::OnMergeClick()
Open FieldNameCorrectionDlg:
ScrolledWidgetsPane::RemoveIllegalChars
County
County
ScrolledWidgetsPane::TruncateFieldName
County
ScrolledWidgetsPane::RenameDupFieldName
County
County_1
ScrolledWidgetsPane::RemoveIllegalChars
Education/ Less than 9th grade
EducationLessthan9thgrade
ScrolledWidgetsPane::TruncateFieldName
EducationLessthan9thgrade
Educa_rade
ScrolledWidgetsPane::RenameDupFieldName
Educa_rade
Educa_rade
ScrolledWidgetsPane::RemoveIllegalChars
Median household income
Medianhouseholdincome
ScrolledWidgetsPane::TruncateFieldName
Medianhouseholdincome
Media_come
ScrolledWidgetsPane::RenameDupFieldName
Media_come
Media_come
ScrolledWidgetsPane::RemoveIllegalChars
education At least bachelors degree
educationAtleastbachelorsdegree
ScrolledWidgetsPane::TruncateFieldName
educationAtleastbachelorsdegree
educa_gree
ScrolledWidgetsPane::RenameDupFieldName
educa_gree
educa_gree
ScrolledWidgetsPane::RemoveIllegalChars
people below poverty
peoplebelowpoverty
ScrolledWidgetsPane::TruncateFieldName
peoplebelowpoverty
peopl_erty
ScrolledWidgetsPane::RenameDupFieldName
peopl_erty
peopl_erty
Click FieldNameCorrectionDlg::OnCancelClick
In TableFrame::OnActivate
Exit FieldNameCorrectionDlg
In TableFrame::OnActivate
In MergeTableDlg::OnMergeClick()
Open FieldNameCorrectionDlg:
ScrolledWidgetsPane::RemoveIllegalChars
County
County
ScrolledWidgetsPane::TruncateFieldName
County
ScrolledWidgetsPane::RenameDupFieldName
County
County_1
ScrolledWidgetsPane::RemoveIllegalChars
Education/ Less than 9th grade
EducationLessthan9thgrade
ScrolledWidgetsPane::TruncateFieldName
EducationLessthan9thgrade
Educa_rade
ScrolledWidgetsPane::RenameDupFieldName
Educa_rade
Educa_rade
ScrolledWidgetsPane::RemoveIllegalChars
Median household income
Medianhouseholdincome
ScrolledWidgetsPane::TruncateFieldName
Medianhouseholdincome
Media_come
ScrolledWidgetsPane::RenameDupFieldName
Media_come
Media_come
ScrolledWidgetsPane::RemoveIllegalChars
education At least bachelors degree
educationAtleastbachelorsdegree
ScrolledWidgetsPane::TruncateFieldName
educationAtleastbachelorsdegree
educa_gree
ScrolledWidgetsPane::RenameDupFieldName
educa_gree
educa_gree
ScrolledWidgetsPane::RemoveIllegalChars
people below poverty
peoplebelowpoverty
ScrolledWidgetsPane::TruncateFieldName
peoplebelowpoverty
peopl_erty
ScrolledWidgetsPane::RenameDupFieldName
peopl_erty
peopl_erty
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
County_1
ScrolledWidgetsPane::IsFieldNameValid
edu<9th
ScrolledWidgetsPane::IsFieldNameValid
income
ScrolledWidgetsPane::IsFieldNameValid
edu>bach
ScrolledWidgetsPane::IsFieldNameValid
ppl<poverty
Click FieldNameCorrectionDlg::OnCancelClick
In TableFrame::OnActivate
Exit FieldNameCorrectionDlg
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
Open DataViewerDeleteColDlg.
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnDelete()
CO_FIPS
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnDelete()
RecenTrend
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnDelete()
RecTren5Yr
In DataViewerDeleteColDlg::OnChoice()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
Open DataViewerDeleteColDlg.
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnDelete()
COUNTY_NAM
In TableFrame::OnActivate
In TableFrame::OnActivate
Open DataViewerEditFieldPropertiesDlg
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
Entering MergeTableDlg::OnExclOneClick()
In MergeTableDlg::OnMergeClick()
Open FieldNameCorrectionDlg:
ScrolledWidgetsPane::RemoveIllegalChars
County
County
ScrolledWidgetsPane::TruncateFieldName
County
ScrolledWidgetsPane::RenameDupFieldName
County
County_1
ScrolledWidgetsPane::RemoveIllegalChars
Education/ Less than 9th grade
EducationLessthan9thgrade
ScrolledWidgetsPane::TruncateFieldName
EducationLessthan9thgrade
Educa_rade
ScrolledWidgetsPane::RenameDupFieldName
Educa_rade
Educa_rade
ScrolledWidgetsPane::RemoveIllegalChars
education At least bachelors degree
educationAtleastbachelorsdegree
ScrolledWidgetsPane::TruncateFieldName
educationAtleastbachelorsdegree
educa_gree
ScrolledWidgetsPane::RenameDupFieldName
educa_gree
educa_gree
ScrolledWidgetsPane::RemoveIllegalChars
people below poverty
peoplebelowpoverty
ScrolledWidgetsPane::TruncateFieldName
peoplebelowpoverty
peopl_erty
ScrolledWidgetsPane::RenameDupFieldName
peopl_erty
peopl_erty
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
County_1
ScrolledWidgetsPane::IsFieldNameValid
edu_9th
ScrolledWidgetsPane::IsFieldNameValid
edu_bach
ScrolledWidgetsPane::IsFieldNameValid
blw_poverty
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
County_1
ScrolledWidgetsPane::IsFieldNameValid
edu_9th
ScrolledWidgetsPane::IsFieldNameValid
edu_bach
ScrolledWidgetsPane::IsFieldNameValid
poverty
In TableFrame::OnActivate
Exit FieldNameCorrectionDlg
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
Open DataViewerEditFieldPropertiesDlg
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In GdaFrame::OnMoveSelectedToTop
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
Open DataViewerDeleteColDlg.
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnDelete()
County_1
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnDelete()
insurance
poverty
edu_bach
edu_9th
In TableFrame::OnActivate
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()

Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick

In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnKeyChoice()
Entering MergeTableDlg::OnIncAllClick()
Entering MergeTableDlg::OnExclOneClick()
Entering MergeTableDlg::OnExclOneClick()
In MergeTableDlg::OnMergeClick()
Open FieldNameCorrectionDlg:
ScrolledWidgetsPane::RemoveIllegalChars
County
County
ScrolledWidgetsPane::TruncateFieldName
County
ScrolledWidgetsPane::RenameDupFieldName
County
County_1
ScrolledWidgetsPane::RemoveIllegalChars
Education/ Less than 9th grade
EducationLessthan9thgrade
ScrolledWidgetsPane::TruncateFieldName
EducationLessthan9thgrade
Educa_rade
ScrolledWidgetsPane::RenameDupFieldName
Educa_rade
Educa_rade
ScrolledWidgetsPane::RemoveIllegalChars
education At least bachelors degree
educationAtleastbachelorsdegree
ScrolledWidgetsPane::TruncateFieldName
educationAtleastbachelorsdegree
educa_gree
ScrolledWidgetsPane::RenameDupFieldName
educa_gree
educa_gree
ScrolledWidgetsPane::RemoveIllegalChars
people below poverty
peoplebelowpoverty
ScrolledWidgetsPane::TruncateFieldName
peoplebelowpoverty
peopl_erty
ScrolledWidgetsPane::RenameDupFieldName
peopl_erty
peopl_erty
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
County_1
ScrolledWidgetsPane::IsFieldNameValid
edu_9th
ScrolledWidgetsPane::IsFieldNameValid
edu_bach
ScrolledWidgetsPane::IsFieldNameValid
poverty
Exit FieldNameCorrectionDlg
Open DataViewerEditFieldPropertiesDlg
In TableFrame::OnActivate
Open DataViewerDeleteColDlg.
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnDelete()
insurance
poverty
edu_bach
edu_9th
County_1
In TableFrame::OnActivate
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()

Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick

In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnKeyChoice()
Entering MergeTableDlg::OnIncAllClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnExclOneClick()
Entering MergeTableDlg::OnExclOneClick()
In MergeTableDlg::OnMergeClick()
Open FieldNameCorrectionDlg:
ScrolledWidgetsPane::RemoveIllegalChars
County
County
ScrolledWidgetsPane::TruncateFieldName
County
ScrolledWidgetsPane::RenameDupFieldName
County
County_1
ScrolledWidgetsPane::RemoveIllegalChars
Education/ Less than 9th grade
EducationLessthan9thgrade
ScrolledWidgetsPane::TruncateFieldName
EducationLessthan9thgrade
Educa_rade
ScrolledWidgetsPane::RenameDupFieldName
Educa_rade
Educa_rade
ScrolledWidgetsPane::RemoveIllegalChars
education At least bachelors degree
educationAtleastbachelorsdegree
ScrolledWidgetsPane::TruncateFieldName
educationAtleastbachelorsdegree
educa_gree
ScrolledWidgetsPane::RenameDupFieldName
educa_gree
educa_gree
ScrolledWidgetsPane::RemoveIllegalChars
people below poverty
peoplebelowpoverty
ScrolledWidgetsPane::TruncateFieldName
peoplebelowpoverty
peopl_erty
ScrolledWidgetsPane::RenameDupFieldName
peopl_erty
peopl_erty
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
County_1
ScrolledWidgetsPane::IsFieldNameValid
edu_9th
ScrolledWidgetsPane::IsFieldNameValid
edu_bach
ScrolledWidgetsPane::IsFieldNameValid
poverty
Exit FieldNameCorrectionDlg
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
Open DataViewerDeleteColDlg.
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnDelete()
County_1
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
Click GdaFrame::OnSaveProject
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs

Project::GetSpatialReference()
Project::GetGdaGeometries()
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
R_EBS
ScrolledWidgetsPane::IsFieldNameValid
smoker
ScrolledWidgetsPane::IsFieldNameValid
RawRate
ScrolledWidgetsPane::IsFieldNameValid
Pop50
ScrolledWidgetsPane::IsFieldNameValid
POP50HALF
ScrolledWidgetsPane::IsFieldNameValid
EBRATE
ScrolledWidgetsPane::IsFieldNameValid
FIPS
ScrolledWidgetsPane::IsFieldNameValid
incidence
ScrolledWidgetsPane::IsFieldNameValid
County
ScrolledWidgetsPane::IsFieldNameValid
EXC_RISK
ScrolledWidgetsPane::IsFieldNameValid
income
ScrolledWidgetsPane::IsFieldNameValid
Male
ScrolledWidgetsPane::IsFieldNameValid
Female
ScrolledWidgetsPane::IsFieldNameValid
R_EBSmale
ScrolledWidgetsPane::IsFieldNameValid
R_EBS_fem
ScrolledWidgetsPane::IsFieldNameValid
MORAN_STD
ScrolledWidgetsPane::IsFieldNameValid
MORAN_LAG
ScrolledWidgetsPane::IsFieldNameValid
MORAN_STD1
ScrolledWidgetsPane::IsFieldNameValid
LISA__REBS
ScrolledWidgetsPane::IsFieldNameValid
LISA__oker
ScrolledWidgetsPane::IsFieldNameValid
Local_LEBS
ScrolledWidgetsPane::IsFieldNameValid
Local_y_sm
ScrolledWidgetsPane::IsFieldNameValid
edu_9th
ScrolledWidgetsPane::IsFieldNameValid
edu_bach
ScrolledWidgetsPane::IsFieldNameValid
poverty
ScrolledWidgetsPane::IsFieldNameValid
insurance
Exit FieldNameCorrectionDlg
Click GdaFrame::OnSaveProject
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs

Project::GetSpatialReference()
Project::GetGdaGeometries()
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
R_EBS
ScrolledWidgetsPane::IsFieldNameValid
smoker
ScrolledWidgetsPane::IsFieldNameValid
RawRate
ScrolledWidgetsPane::IsFieldNameValid
Pop50
ScrolledWidgetsPane::IsFieldNameValid
POP50HALF
ScrolledWidgetsPane::IsFieldNameValid
EBRATE
ScrolledWidgetsPane::IsFieldNameValid
FIPS
ScrolledWidgetsPane::IsFieldNameValid
incidence
ScrolledWidgetsPane::IsFieldNameValid
County
ScrolledWidgetsPane::IsFieldNameValid
EXC_RISK
ScrolledWidgetsPane::IsFieldNameValid
income
ScrolledWidgetsPane::IsFieldNameValid
Male
ScrolledWidgetsPane::IsFieldNameValid
Female
ScrolledWidgetsPane::IsFieldNameValid
R_EBSmale
ScrolledWidgetsPane::IsFieldNameValid
R_EBS_fem
ScrolledWidgetsPane::IsFieldNameValid
MORAN_STD
ScrolledWidgetsPane::IsFieldNameValid
MORAN_LAG
ScrolledWidgetsPane::IsFieldNameValid
MORAN_STD1
ScrolledWidgetsPane::IsFieldNameValid
LISA__REBS
ScrolledWidgetsPane::IsFieldNameValid
LISA__oker
ScrolledWidgetsPane::IsFieldNameValid
Local_LEBS
ScrolledWidgetsPane::IsFieldNameValid
Local_y_sm
ScrolledWidgetsPane::IsFieldNameValid
edu_9th
ScrolledWidgetsPane::IsFieldNameValid
edu_bach
ScrolledWidgetsPane::IsFieldNameValid
poverty
ScrolledWidgetsPane::IsFieldNameValid
insurance
Exit FieldNameCorrectionDlg
Click GdaFrame::OnSaveAsProject
Project::GetProjectFullPath()
Project::SpecifyProjectConfFile()
Project::SetProjectFullPath()
Entering Project::SaveProjectConf
In Project::UpdateProjectConf
Exiting Project::SaveProjectConf

Click GdaFrame::OnSaveProject
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs

Project::GetSpatialReference()
Project::GetGdaGeometries()
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
R_EBS
ScrolledWidgetsPane::IsFieldNameValid
smoker
ScrolledWidgetsPane::IsFieldNameValid
RawRate
ScrolledWidgetsPane::IsFieldNameValid
Pop50
ScrolledWidgetsPane::IsFieldNameValid
POP50HALF
ScrolledWidgetsPane::IsFieldNameValid
EBRATE
ScrolledWidgetsPane::IsFieldNameValid
FIPS
ScrolledWidgetsPane::IsFieldNameValid
incidence
ScrolledWidgetsPane::IsFieldNameValid
County
ScrolledWidgetsPane::IsFieldNameValid
EXC_RISK
ScrolledWidgetsPane::IsFieldNameValid
income
ScrolledWidgetsPane::IsFieldNameValid
Male
ScrolledWidgetsPane::IsFieldNameValid
Female
ScrolledWidgetsPane::IsFieldNameValid
R_EBSmale
ScrolledWidgetsPane::IsFieldNameValid
R_EBS_fem
ScrolledWidgetsPane::IsFieldNameValid
MORAN_STD
ScrolledWidgetsPane::IsFieldNameValid
MORAN_LAG
ScrolledWidgetsPane::IsFieldNameValid
MORAN_STD1
ScrolledWidgetsPane::IsFieldNameValid
LISA__REBS
ScrolledWidgetsPane::IsFieldNameValid
LISA__oker
ScrolledWidgetsPane::IsFieldNameValid
Local_LEBS
ScrolledWidgetsPane::IsFieldNameValid
Local_y_sm
ScrolledWidgetsPane::IsFieldNameValid
edu_9th
ScrolledWidgetsPane::IsFieldNameValid
edu_bach
ScrolledWidgetsPane::IsFieldNameValid
poverty
ScrolledWidgetsPane::IsFieldNameValid
insurance
Exit FieldNameCorrectionDlg
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
Project::GetProjectFullPath()
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs

Project::GetSpatialReference()
Project::GetGdaGeometries()
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
R_EBS
ScrolledWidgetsPane::IsFieldNameValid
smoker
ScrolledWidgetsPane::IsFieldNameValid
RawRate
ScrolledWidgetsPane::IsFieldNameValid
Pop50
ScrolledWidgetsPane::IsFieldNameValid
POP50HALF
ScrolledWidgetsPane::IsFieldNameValid
EBRATE
ScrolledWidgetsPane::IsFieldNameValid
FIPS
ScrolledWidgetsPane::IsFieldNameValid
incidence
ScrolledWidgetsPane::IsFieldNameValid
County
ScrolledWidgetsPane::IsFieldNameValid
EXC_RISK
ScrolledWidgetsPane::IsFieldNameValid
income
ScrolledWidgetsPane::IsFieldNameValid
Male
ScrolledWidgetsPane::IsFieldNameValid
Female
ScrolledWidgetsPane::IsFieldNameValid
R_EBSmale
ScrolledWidgetsPane::IsFieldNameValid
R_EBS_fem
ScrolledWidgetsPane::IsFieldNameValid
MORAN_STD
ScrolledWidgetsPane::IsFieldNameValid
MORAN_LAG
ScrolledWidgetsPane::IsFieldNameValid
MORAN_STD1
ScrolledWidgetsPane::IsFieldNameValid
LISA__REBS
ScrolledWidgetsPane::IsFieldNameValid
LISA__oker
ScrolledWidgetsPane::IsFieldNameValid
Local_LEBS
ScrolledWidgetsPane::IsFieldNameValid
Local_y_sm
ScrolledWidgetsPane::IsFieldNameValid
edu_9th
ScrolledWidgetsPane::IsFieldNameValid
edu_bach
ScrolledWidgetsPane::IsFieldNameValid
poverty
ScrolledWidgetsPane::IsFieldNameValid
insurance
Exit FieldNameCorrectionDlg

**Comment by lixun910** [comment]
Hi Zhaofy,

Thanks for reporting this issue! Can you share your data with us to replicate and fix this issue? I noticed you removed the file path from the log. We will keep your data confidential.

Best,

Xun Li Ph.D.

Assistant Director for Data Science
Center of Spatial Data Science
University of Chicago


On Nov 26, 2017, at 8:43 PM, GeoDaTester <notifications@github.com<mailto:notifications@github.com>> wrote:

RecTren5Yr

**Comment by lixun910** [comment]
confirm the fix with user: zhaofy@uchicago.edu

**Comment by YidanJ-Wu** [comment]
I tested this feature in 1.12.1.57 Windows 8 and didn't crash. I was using a different dataset than the reporting user, though.

**Comment by lixun910** [comment]
Yes, this issue has been fixed in 1.12.1.57
