### ISSUE TITLE
Regression crash

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1357]
From: 
 Details:
os: 1-10-12
vs: 1-12-0-0
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/terrycui/Desktop/FALL 17/GIS/project/US_census_w_gun&crime.shp
Open Layer:US_census_w_gun&crime
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/terrycui/Desktop/FALL 17/GIS/project/US_census_w_gun&crime.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnRegressionClassic()
Open RegressionDlg.
RegressionDlg::InitVariableList()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
selected:0
Click CreatingWeightDlg::OnCRadioRookSelected
Click CreatingWeightDlg::OnCreateClick
In WeightsManFrame::OnActivate
CreateWeights()/Users/terrycui/Desktop/FALL 17/GIS/project/US_census_w_gun&crime.gal
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnActivate
In GdaFrame::OnRegressionClassic()
RegressionDlg::OnCButton1Click()
RegressionDlg::~RegressionDlg()
In GdaFrame::OnRegressionClassic()
Open RegressionDlg.
RegressionDlg::InitVariableList()
RegressionDlg::OnCButton1Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnCWeightCheckClick
Click RegressionDlg::OnCRadio2Selected
Click RegressionDlg::OnRunClick
y:US_crime_2
x:
AGE_5_17
BLACK
eHousing
US_GunOw61
Spatial Lag model

**Comment by lixun910** [comment]
maybe same with #1330 Regression crash with invalid variable

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.143
Verified

<img width="459" alt="screen shot 2018-07-23 at 3 05 56 pm" src="https://user-images.githubusercontent.com/37029239/43100144-084647a8-8e8a-11e8-95c0-2b3102b0dcc3.png">
<img width="349" alt="screen shot 2018-07-23 at 3 05 33 pm" src="https://user-images.githubusercontent.com/37029239/43100145-0855554a-8e8a-11e8-95ac-1149c0e0f2c7.png">
