### ISSUE TITLE
KMeans crash (wait for verification)

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1358]
From: ariel.azar@gmail.com
 Details:
os: 1-10-11
vs: 1-12-1-47
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
In GdaFrame::OnHelpAbout()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/arielazar/Dropbox/PhD/1.1 Autumn 2017/SOCI 30253 SDS/assignments/171128_assignment7/geo_export_dc112fdf-4535-44bb-b0df-5326991fa3f0.shp
Open Layer:geo_export_dc112fdf-4535-44bb-b0df-5326991fa3f0
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/arielazar/Dropbox/PhD/1.1 Autumn 2017/SOCI 30253 SDS/assignments/171128_assignment7/geo_export_dc112fdf-4535-44bb-b0df-5326991fa3f0.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
Open MergeTableDlg.
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/arielazar/Dropbox/PhD/1.1 Autumn 2017/SOCI 30253 SDS/assignments/171128_assignment7/census_ses.csv
Open Layer:census_ses
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
In TableFrame::OnActivate
Exiting ConnectDatasourceDlg::OnOkClick
ds:/Users/arielazar/Dropbox/PhD/1.1 Autumn 2017/SOCI 30253 SDS/assignments/171128_assignment7/census_ses.csv layer: census_ses
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnKeyChoice()
Entering MergeTableDlg::OnIncAllClick()
Entering MergeTableDlg::OnExclAllClick()
Entering MergeTableDlg::OnIncAllClick()
Entering MergeTableDlg::OnExclOneClick()
In MergeTableDlg::OnMergeClick()
Open FieldNameCorrectionDlg:
ScrolledWidgetsPane::RemoveIllegalChars
COMMUNITY AREA NAME
COMMUNITYAREANAME
ScrolledWidgetsPane::TruncateFieldName
COMMUNITYAREANAME
COMMU_NAME
ScrolledWidgetsPane::RenameDupFieldName
COMMU_NAME
COMMU_NAME
ScrolledWidgetsPane::RemoveIllegalChars
HARDSHIP INDEX
HARDSHIPINDEX
ScrolledWidgetsPane::TruncateFieldName
HARDSHIPINDEX
HARDS_NDEX
ScrolledWidgetsPane::RenameDupFieldName
HARDS_NDEX
HARDS_NDEX
ScrolledWidgetsPane::RemoveIllegalChars
PER CAPITA INCOME
PERCAPITAINCOME
ScrolledWidgetsPane::TruncateFieldName
PERCAPITAINCOME
PERCA_COME
ScrolledWidgetsPane::RenameDupFieldName
PERCA_COME
PERCA_COME
ScrolledWidgetsPane::RemoveIllegalChars
PERCENT AGED 16+ UNEMPLOYED
PERCENTAGED16UNEMPLOYED
ScrolledWidgetsPane::TruncateFieldName
PERCENTAGED16UNEMPLOYED
PERCE_OYED
ScrolledWidgetsPane::RenameDupFieldName
PERCE_OYED
PERCE_OYED
ScrolledWidgetsPane::RemoveIllegalChars
PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA
PERCENTAGED25WITHOUTHIGHSCHOOLDIPLOMA
ScrolledWidgetsPane::TruncateFieldName
PERCENTAGED25WITHOUTHIGHSCHOOLDIPLOMA
PERCE_LOMA
ScrolledWidgetsPane::RenameDupFieldName
PERCE_LOMA
PERCE_LOMA
ScrolledWidgetsPane::RemoveIllegalChars
PERCENT AGED UNDER 18 OR OVER 64
PERCENTAGEDUNDER18OROVER64
ScrolledWidgetsPane::TruncateFieldName
PERCENTAGEDUNDER18OROVER64
PERCE_ER64
ScrolledWidgetsPane::RenameDupFieldName
PERCE_ER64
PERCE_ER64
ScrolledWidgetsPane::RemoveIllegalChars
PERCENT HOUSEHOLDS BELOW POVERTY
PERCENTHOUSEHOLDSBELOWPOVERTY
ScrolledWidgetsPane::TruncateFieldName
PERCENTHOUSEHOLDSBELOWPOVERTY
PERCE_ERTY
ScrolledWidgetsPane::RenameDupFieldName
PERCE_ERTY
PERCE_ERTY
ScrolledWidgetsPane::RemoveIllegalChars
PERCENT OF HOUSING CROWDED
PERCENTOFHOUSINGCROWDED
ScrolledWidgetsPane::TruncateFieldName
PERCENTOFHOUSINGCROWDED
PERCE_WDED
ScrolledWidgetsPane::RenameDupFieldName
PERCE_WDED
PERCE_WDED
Click FieldNameCorrectionDlg::OnCancelClick
In TableFrame::OnActivate
Exit FieldNameCorrectionDlg
Entering MergeTableDlg::OnExclOneClick()
In MergeTableDlg::OnMergeClick()
Open FieldNameCorrectionDlg:
ScrolledWidgetsPane::RemoveIllegalChars
HARDSHIP INDEX
HARDSHIPINDEX
ScrolledWidgetsPane::TruncateFieldName
HARDSHIPINDEX
HARDS_NDEX
ScrolledWidgetsPane::RenameDupFieldName
HARDS_NDEX
HARDS_NDEX
ScrolledWidgetsPane::RemoveIllegalChars
PER CAPITA INCOME
PERCAPITAINCOME
ScrolledWidgetsPane::TruncateFieldName
PERCAPITAINCOME
PERCA_COME
ScrolledWidgetsPane::RenameDupFieldName
PERCA_COME
PERCA_COME
ScrolledWidgetsPane::RemoveIllegalChars
PERCENT AGED 16+ UNEMPLOYED
PERCENTAGED16UNEMPLOYED
ScrolledWidgetsPane::TruncateFieldName
PERCENTAGED16UNEMPLOYED
PERCE_OYED
ScrolledWidgetsPane::RenameDupFieldName
PERCE_OYED
PERCE_OYED
ScrolledWidgetsPane::RemoveIllegalChars
PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA
PERCENTAGED25WITHOUTHIGHSCHOOLDIPLOMA
ScrolledWidgetsPane::TruncateFieldName
PERCENTAGED25WITHOUTHIGHSCHOOLDIPLOMA
PERCE_LOMA
ScrolledWidgetsPane::RenameDupFieldName
PERCE_LOMA
PERCE_LOMA
ScrolledWidgetsPane::RemoveIllegalChars
PERCENT AGED UNDER 18 OR OVER 64
PERCENTAGEDUNDER18OROVER64
ScrolledWidgetsPane::TruncateFieldName
PERCENTAGEDUNDER18OROVER64
PERCE_ER64
ScrolledWidgetsPane::RenameDupFieldName
PERCE_ER64
PERCE_ER64
ScrolledWidgetsPane::RemoveIllegalChars
PERCENT HOUSEHOLDS BELOW POVERTY
PERCENTHOUSEHOLDSBELOWPOVERTY
ScrolledWidgetsPane::TruncateFieldName
PERCENTHOUSEHOLDSBELOWPOVERTY
PERCE_ERTY
ScrolledWidgetsPane::RenameDupFieldName
PERCE_ERTY
PERCE_ERTY
ScrolledWidgetsPane::RemoveIllegalChars
PERCENT OF HOUSING CROWDED
PERCENTOFHOUSINGCROWDED
ScrolledWidgetsPane::TruncateFieldName
PERCENTOFHOUSINGCROWDED
PERCE_WDED
ScrolledWidgetsPane::RenameDupFieldName
PERCE_WDED
PERCE_WDED
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
hards_ind
ScrolledWidgetsPane::IsFieldNameValid
inc_pc
ScrolledWidgetsPane::IsFieldNameValid
p_unemp
ScrolledWidgetsPane::IsFieldNameValid
p_nhigh
ScrolledWidgetsPane::IsFieldNameValid
p_18_64
ScrolledWidgetsPane::IsFieldNameValid
p_pover
ScrolledWidgetsPane::IsFieldNameValid
p_crowded
In TableFrame::OnActivate
Exit FieldNameCorrectionDlg
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
Open PCASettingsDlg.
Click PCASettingsDlg::OnOK
Click PCASettingsDlg::OnOK
Click PCASettingsDlg::OnOK
Click PCASettingsDlg::OnOK
Click PCASettingsDlg::OnOK
Click PCASettingsDlg::OnOK
Click PCASettingsDlg::OnOK
Click PCASettingsDlg::OnOK
OnSave PCASettingsDlg.
Click PCASettingsDlg::OnOK
OnSave PCASettingsDlg.
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
Click CreatingWeightDlg::OnIdVariableSelected
selected:1
Click CreatingWeightDlg::OnCRadioQueenSelected
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/Users/arielazar/Dropbox/PhD/1.1 Autumn 2017/SOCI 30253 SDS/assignments/171128_assignment7/queen_1.gal
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnActivate
WeightsManFrame::OnConnectMapBtn()
Open ConnectivityMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In WeightsManFrame::OnActivate
In ConnectivityMapFrame::OnActivate
In ConnectivityMapFrame::OnActivate
In ConnectivityMapFrame::OnActivate
In ConnectivityMapFrame::OnActivate
In ConnectivityMapFrame::OnActivate
In ConnectivityMapFrame::OnActivate
In MapFrame::OnMapBasemap()
Click GdaFrame::OnSetBasemap1
In MapFrame::OnMapBasemap()
Click GdaFrame::OnSetBasemap2
In MapFrame::OnMapBasemap()
Click GdaFrame::OnSetBasemap1
In MapFrame::OnMapBasemap()
Click GdaFrame::OnChangeMapTransparency
Open SliderDialog
In ConnectivityMapFrame::OnActivate
In MapFrame::OnMapBasemap()
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In TableFrame::OnActivate
In ConnectivityMapFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In ConnectivityMapFrame::OnActivate
In GdaFrame::OnOpenHinge15()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PC1
In ConnectivityMapFrame::OnActivate
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnExcessrisk()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
In ConnectivityMapFrame::OnActivate
MapCanvas::~MapCanvas()
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PC1
In ConnectivityMapFrame::OnActivate
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open AbstractClusterDlg.
Open KMeanDlg.
Click KMeansDlg::OnOK
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Open AbstractClusterDlg.
Open HClusterDlg.
Click HClusterDlg::OnOK
In ConnectivityMapFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In TableFrame::OnActivate
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
In TableFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In ConnectivityMapFrame::OnActivate
In ConnectivityMapFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In TableFrame::OnActivate
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Close HClusterDlg
In TableFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
MapCanvas::~MapCanvas()
In TableFrame::OnActivate
MapCanvas::~MapCanvas()
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PC2
In TableFrame::OnActivate
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
MapCanvas::~MapCanvas()
In TableFrame::OnActivate
In TableFrame::OnActivate
Close HClusterDlg
In TableFrame::OnActivate
Close KMeansDlg
In TableFrame::OnActivate
In TableFrame::OnActivate
MapCanvas::~MapCanvas()
In TableFrame::OnActivate
In TableFrame::OnActivate
Open AbstractClusterDlg.
Open SpectralClusteringDlg.
Close HClusterDlg
In TableFrame::OnActivate
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PC1
VariableSettingsDlg::GetWeightsId() weight: queen_1
VariableSettingsDlg::GetWeightsId() weight: queen_1
Entering LisaCoordinator::LisaCoordinator().
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
Entering LisaCoordinator::InitFromVarInfo()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Entering LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
In LisaCoordinator::registerObserver()
Open GetisOrdMapFrame (OnOpenGetisOrd).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PC1
VariableSettingsDlg::GetWeightsId() weight: queen_1
VariableSettingsDlg::GetWeightsId() weight: queen_1
Entering GetisOrdMapFrame::GetisOrdMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Exiting GetisOrdMapFrame::GetisOrdMapFrame
In GetisOrdMapFrame::~GetisOrdMapFrame
MapCanvas::~MapCanvas()
Entering LisaCoordinator::removeObserver
In LisaCoordinator::~LisaCoordinator().
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::removeObserver
Open AbstractClusterDlg.
Open HClusterDlg.
Click HClusterDlg::OnOK
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open AbstractClusterDlg.
Open KMeanDlg.
Click KMeansDlg::OnOK
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
In TableFrame::OnActivate
Click KMeansDlg::OnOK
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
In TableFrame::OnActivate
MapCanvas::~MapCanvas()
Close KMeansDlg
OnClickClose HClusterDlg.
In TableFrame::OnActivate
In TableFrame::OnActivate
Open AbstractClusterDlg.
Open Skater dialog.
On SkaterDlg::CreateControls
On SkaterDlg::InitVariableCombobox
Click SkaterDlg::OnOK
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click SkaterDlg::OnOK
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click SkaterDlg::OnOK
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click SkaterDlg::OnOK
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Close SkaterDlg
On SkaterDlg::~SkaterDlg
In TableFrame::OnActivate
In TableFrame::OnActivate
MapCanvas::~MapCanvas()
In TableFrame::OnActivate
Open AbstractClusterDlg.
Open REDCAP dialog.
On RedcapDlg::Init
On RedcapDlg::CreateControls
On RedcapDlg::InitVariableCombobox
Click RedcapDlg::OnOK
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Close RedcapDlg
On RedcapDlg::~RedcapDlg
Open AbstractClusterDlg.
Open KMeanDlg.
Click KMeansDlg::OnOK
Project::GetCentroids()
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click KMeansDlg::OnOK
Project::GetCentroids()
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click KMeansDlg::OnOK
Project::GetCentroids()
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click KMeansDlg::OnOK
Project::GetCentroids()
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Click KMeansDlg::OnOK
Project::GetCentroids()
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click KMeansDlg::OnOK
Project::GetCentroids()
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Click KMeansDlg::OnOK
Click KMeansDlg::OnOK
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
Click KMeansDlg::OnOK
Project::GetCentroids()
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
Click KMeansDlg::OnOK
Project::GetCentroids()
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click KMeansDlg::OnOK
Project::GetCentroids()
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Close KMeansDlg
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Open AbstractClusterDlg.
Open Skater dialog.
On SkaterDlg::CreateControls
On SkaterDlg::InitVariableCombobox
Click SkaterDlg::OnOK
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Close SkaterDlg
On SkaterDlg::~SkaterDlg
Open AbstractClusterDlg.
Open Max-p dialog.
On MaxpDlg::CreateControls
On MaxpDlg::InitVariableCombobox
Click MaxpDlg::OnOK
Click MaxpDlg::OnOK
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
On MaxpDlg::InitVariableCombobox
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click MaxpDlg::OnOK
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
On MaxpDlg::InitVariableCombobox
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Close MaxpDlg
On MaxpDlg::~MaxpDlg
Open PCASettingsDlg.
Click PCASettingsDlg::OnOK
Close PCASettingsDlg.
Entering GdaFrame::OnMapChoices
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PC1
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In MapFrame::OnMapBasemap()
Click GdaFrame::OnSetBasemap1
In MapFrame::OnMapBasemap()
Click GdaFrame::OnCleanBasemap
In MapFrame::OnMapBasemap()
Click GdaFrame::OnSetNoBasemap
Click GdaFrame::OnCopyImageToClipboard
Click GdaFrame::OnCopyLegendToClipboard
Entering GdaFrame::OnMapChoices
MapCanvas::~MapCanvas()
Open AbstractClusterDlg.
Open KMeanDlg.
Click KMeansDlg::OnOK
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click KMeansDlg::OnOK
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Click KMeansDlg::OnOK
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Close KMeansDlg
MapCanvas::~MapCanvas()
Open AbstractClusterDlg.
Open KMeanDlg.
Click KMeansDlg::OnOK
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click KMeansDlg::OnOK
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click KMeansDlg::OnOK
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click KMeansDlg::OnOK
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click KMeansDlg::OnOK
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click KMeansDlg::OnOK

**Comment by lixun910** [comment]
Hi Ariel,

Thanks for reporting this issue! Can you share your data with us to replicate and fix this issue? We will keep your data confidential.  I also noticed you posted another issue #1356 with spatial lag model. Is that a crash?  

Best,

Xun Li Ph.D.

Assistant Director for Data Science
Center of Spatial Data Science
University of Chicago

**Comment by lixun910** [comment]
possible same with KMeans crash with grouped variable selected #1360

**Comment by VeraB620** [comment]
OS X El Capitan 10.11.6
GeoDa 1.12.1.137

Not sure if the issue was in Ariels data, but using a GeoDa data set and a datasets from Chicago Data Portal, KMeans does not crash.
With larger data sets (311 Tree Trimming Requests from Chicago Data Portal), the lag was very significant (about 5 seconds)
