### ISSUE TITLE
KMeans crash with grouped variable selected

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1360]
From: 
 Details:
os: 1-10-13
vs: 1-12-1-47
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/rachelkim/Downloads/Boundaries - Community Areas (current) (4)/geo_export_78ac4d71-469f-47f8-82c4-d5409116ba4b.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
Open PCASettingsDlg.
Click PCASettingsDlg::OnOK
Click PCASettingsDlg::OnOK
Close HClusterDlg
Open AbstractClusterDlg.
Open HClusterDlg.
Click HClusterDlg::OnOK
Click HClusterDlg::OnOK
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnCopyImageToClipboard
Click GdaFrame::OnCopyLegendToClipboard
Click GdaFrame::OnCopyLegendToClipboard
Close HClusterDlg
Open AbstractClusterDlg.
Open KMeanDlg.
Click KMeansDlg::OnOK

**Comment by lixun910** [comment]
Hi,

Thanks for reporting this issue! Can you try the latest GeoDa 1.12.1.57 with a fix on this issue? You can download it from https://www.dropbox.com/s/sqcuy1a9nn01rks/GeoDa1.12.1.57-Installer.dmg?dl=0 <https://www.dropbox.com/s/sqcuy1a9nn01rks/GeoDa1.12.1.57-Installer.dmg?dl=0>
Please let us know if this issue has been addressed in this new release. Thanks again!

Best,

Xun Li Ph.D.

Assistant Director for Data Science
Center of Spatial Data Science
University of Chicago

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.57
Verified
![image](https://user-images.githubusercontent.com/22801047/33343553-550d29c0-d44b-11e7-8ccb-3172eb7c0ff5.png)
