### ISSUE TITLE
Crash: cancel the "Update Field Name" dialog when save dataset

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1362]
From: 
 Details:
os: 1-10-12
vs: 1-12-1-57
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
GdaFrame::OpenProject()
/Users/Abby/Desktop/Spatial Data Science/Assignment2/MergedDataset_PrjFile.gda
Entering Project::Project (existing project)
/Users/Abby/Desktop/Spatial Data Science/Assignment2/MergedDataset_PrjFile.gda
Project::SetProjectFullPath()
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/Abby/Desktop/Spatial Data Science/Assignment2/Assignment2_MergedDataset[SPATIAL].shp
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open project file:/Users/Abby/Desktop/Spatial Data Science/Assignment2/MergedDataset_PrjFile.gda
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In GdaFrame::OnHelpAbout()
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PC1
VariableSettingsDlg::GetWeightsId() weight: OrigGeog_Queen
VariableSettingsDlg::GetWeightsId() weight: OrigGeog_Queen
Entering LisaCoordinator::LisaCoordinator().
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
Entering LisaCoordinator::InitFromVarInfo()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Entering LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::CalcLisa()
Entering LisaCoordinator::CalcPseudoP()
Entering LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP()
Exiting LisaCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
In LisaCoordinator::registerObserver()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
In GdaFrame::OnSaveLisa()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
Entering LisaCoordinator::removeObserver
Exiting LisaCoordinator::removeObserver
MapCanvas::~MapCanvas()
Entering LisaCoordinator::removeObserver
Exiting LisaCoordinator::removeObserver
MapCanvas::~MapCanvas()
Entering LisaCoordinator::removeObserver
In LisaCoordinator::~LisaCoordinator().
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::removeObserver
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PC1
VariableSettingsDlg::GetWeightsId() weight: OrigGeog_Queen
VariableSettingsDlg::GetWeightsId() weight: OrigGeog_Queen
Entering LisaCoordinator::LisaCoordinator().
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
Entering LisaCoordinator::InitFromVarInfo()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Entering LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::CalcLisa()
Entering LisaCoordinator::CalcPseudoP()
Entering LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP()
Exiting LisaCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
In OnRanOtherPer()
99999
Entering LisaCoordinator::CalcPseudoP()
Entering LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP()
In LisaCoordinator::notifyObservers
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
In OnSigFilter01()
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
In LisaCoordinator::notifyObservers
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
Entering LisaCoordinator::removeObserver
In LisaCoordinator::~LisaCoordinator().
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::removeObserver
MapCanvas::~MapCanvas()
In GdaFrame::OpenNaturalBreaks(6)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PC2
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
MapCanvas::~MapCanvas()
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PC2
VariableSettingsDlg::GetWeightsId() weight: OrigGeog_Queen
VariableSettingsDlg::GetWeightsId() weight: OrigGeog_Queen
Entering LisaCoordinator::LisaCoordinator().
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
Entering LisaCoordinator::InitFromVarInfo()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Entering LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::CalcLisa()
Entering LisaCoordinator::CalcPseudoP()
Entering LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP()
Exiting LisaCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
In OnRanOtherPer()
99999
Entering LisaCoordinator::CalcPseudoP()
Entering LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP()
In LisaCoordinator::notifyObservers
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
In OnSigFilter01()
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
In LisaCoordinator::notifyObservers
MapCanvas::~MapCanvas()
In WeightsManFrame::OnActivate
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
In WeightsManFrame::OnActivate
Entering LisaCoordinator::removeObserver
In LisaCoordinator::~LisaCoordinator().
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::removeObserver
MapCanvas::~MapCanvas()
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
In WeightsManFrame::OnActivate
Click VariableSettingsDlg::OnOkClick:
PC1
VariableSettingsDlg::GetWeightsId() weight: OrigGeog_Queen
In WeightsManFrame::OnActivate
VariableSettingsDlg::GetWeightsId() weight: OrigGeog_Queen
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Entering LisaCoordinator::LisaCoordinator().
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
Entering LisaCoordinator::InitFromVarInfo()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Entering LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::CalcLisa()
Entering LisaCoordinator::CalcPseudoP()
Entering LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP()
Exiting LisaCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
In OnRanOtherPer()
99999
Entering LisaCoordinator::CalcPseudoP()
Entering LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP()
In LisaCoordinator::notifyObservers
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
In OnSigFilter01()
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
In LisaCoordinator::notifyObservers
Open PCPDlg.
Click PCPDlg::OnOkClick
Open PCPFrame.
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PC1
Open BoxPlotCanvas.
Close BoxPlotCanvas.
Entering LisaCoordinator::removeObserver
In LisaCoordinator::~LisaCoordinator().
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::removeObserver
MapCanvas::~MapCanvas()
Open AbstractClusterDlg.
Open KMeanDlg.
Click KMeansDlg::OnOK
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
MapCanvas::~MapCanvas()
Close KMeansDlg
Open AbstractClusterDlg.
Open HClusterDlg.
Click HClusterDlg::OnOK
Close HClusterDlg
Open AbstractClusterDlg.
Open KMeanDlg.
Open Themeless Map (OnOpenThemelessMap).
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnAddCentroids()
In Project::AddCentroids
Project::GetCentroids()
Click KMeansDlg::OnOK
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
MapCanvas::~MapCanvas()
Click KMeansDlg::OnOK
Project::GetCentroids()
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
OnClickClose KMeansDlg.
MapCanvas::~MapCanvas()
Open AbstractClusterDlg.
Open KMeanDlg.
Click KMeansDlg::OnOK
Project::GetCentroids()
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Click KMeansDlg::OnOK
Project::GetCentroids()
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click KMeansDlg::OnOK
Project::GetCentroids()
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click KMeansDlg::OnOK
Project::GetCentroids()
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click KMeansDlg::OnOK
Project::GetCentroids()
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click KMeansDlg::OnOK
Project::GetCentroids()
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click KMeansDlg::OnOK
Project::GetCentroids()
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click KMeansDlg::OnOK
Project::GetCentroids()
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click KMeansDlg::OnOK
Project::GetCentroids()
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click KMeansDlg::OnOK
Project::GetCentroids()
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click KMeansDlg::OnOK
Project::GetCentroids()
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click KMeansDlg::OnOK
Project::GetCentroids()
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click KMeansDlg::OnOK
Project::GetCentroids()
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
MapCanvas::~MapCanvas()
Close KMeansDlg
Open AbstractClusterDlg.
Open Skater dialog.
On SkaterDlg::CreateControls
On SkaterDlg::InitVariableCombobox
Click SkaterDlg::OnOK
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
On SkaterDlg::OnLISACheck
MapCanvas::~MapCanvas()
Close SkaterDlg
On SkaterDlg::~SkaterDlg
Open AbstractClusterDlg.
Open KMeanDlg.
Click KMeansDlg::OnOK
Project::GetCentroids()
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
MapCanvas::~MapCanvas()
Click GdaFrame::OnSaveProject
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs
New Datasource Name:/Users/Abby/Desktop/Spatial Data Science/Assignment2/GdaTmp_Assignment2_MergedDataset[SPATIAL].shp
Project::GetSpatialReference()
Project::GetGdaGeometries()
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
EB_VIOCR
ScrolledWidgetsPane::IsFieldNameValid
POLY_ID
ScrolledWidgetsPane::IsFieldNameValid
area_num_1
ScrolledWidgetsPane::IsFieldNameValid
CommA_Name
ScrolledWidgetsPane::IsFieldNameValid
Serv_Count
ScrolledWidgetsPane::IsFieldNameValid
SERVCAP
ScrolledWidgetsPane::IsFieldNameValid
SERV1000
ScrolledWidgetsPane::IsFieldNameValid
INCOMECAP
ScrolledWidgetsPane::IsFieldNameValid
LifeExpect
ScrolledWidgetsPane::IsFieldNameValid
ViolentCr
ScrolledWidgetsPane::IsFieldNameValid
VIOLENTCAP
ScrolledWidgetsPane::IsFieldNameValid
VIOLEN1000
ScrolledWidgetsPane::IsFieldNameValid
pop2010
ScrolledWidgetsPane::IsFieldNameValid
Perc_Pov
ScrolledWidgetsPane::IsFieldNameValid
Perc_Unemp
ScrolledWidgetsPane::IsFieldNameValid
Perc_Crwd
ScrolledWidgetsPane::IsFieldNameValid
Perc_NoDip
ScrolledWidgetsPane::IsFieldNameValid
Hardship
ScrolledWidgetsPane::IsFieldNameValid
INC_OVER25
ScrolledWidgetsPane::IsFieldNameValid
INC_LE25
ScrolledWidgetsPane::IsFieldNameValid
CommA_Num
ScrolledWidgetsPane::IsFieldNameValid
Homicides
ScrolledWidgetsPane::IsFieldNameValid
RawRtVioCr
ScrolledWidgetsPane::IsFieldNameValid
MORAN_RSTD
ScrolledWidgetsPane::IsFieldNameValid
MORAN_RLAG
ScrolledWidgetsPane::IsFieldNameValid
MORAN_QSTD
ScrolledWidgetsPane::IsFieldNameValid
MORAN_QLAG
ScrolledWidgetsPane::IsFieldNameValid
MORAN_KSTD
ScrolledWidgetsPane::IsFieldNameValid
MORAN_KLAG
ScrolledWidgetsPane::IsFieldNameValid
EBSTDVIOCR
ScrolledWidgetsPane::IsFieldNameValid
MOREB_RSTD
ScrolledWidgetsPane::IsFieldNameValid
MOREB_RLAG
ScrolledWidgetsPane::IsFieldNameValid
MOREB_QSTD
ScrolledWidgetsPane::IsFieldNameValid
MOREB_QLAG
ScrolledWidgetsPane::IsFieldNameValid
MOREB_KSTD
ScrolledWidgetsPane::IsFieldNameValid
MOREB_KLAG
ScrolledWidgetsPane::IsFieldNameValid
CancerD
ScrolledWidgetsPane::IsFieldNameValid
DiabetesD
ScrolledWidgetsPane::IsFieldNameValid
StrokeD
ScrolledWidgetsPane::IsFieldNameValid
InfMort
ScrolledWidgetsPane::IsFieldNameValid
PDIABETESD
ScrolledWidgetsPane::IsFieldNameValid
PSTROKED
ScrolledWidgetsPane::IsFieldNameValid
PCANCERD
ScrolledWidgetsPane::IsFieldNameValid
PINFMORT
ScrolledWidgetsPane::IsFieldNameValid
PC1
ScrolledWidgetsPane::IsFieldNameValid
PC2
ScrolledWidgetsPane::IsFieldNameValid
PC3
ScrolledWidgetsPane::IsFieldNameValid
PC4
ScrolledWidgetsPane::IsFieldNameValid
CL
ScrolledWidgetsPane::IsFieldNameValid
Centroids_X
ScrolledWidgetsPane::IsFieldNameValid
Centroids_Y
ScrolledWidgetsPane::IsFieldNameValid
CL_sk4
ScrolledWidgetsPane::IsFieldNameValid
CL_sk4.2
ScrolledWidgetsPane::RemoveIllegalChars
Centroids_X
Centroids_X
ScrolledWidgetsPane::TruncateFieldName
Centroids_X
Centr_ds_X
ScrolledWidgetsPane::RenameDupFieldName
Centr_ds_X
Centr_ds_X
ScrolledWidgetsPane::RemoveIllegalChars
Centroids_Y
Centroids_Y
ScrolledWidgetsPane::TruncateFieldName
Centroids_Y
Centr_ds_Y
ScrolledWidgetsPane::RenameDupFieldName
Centr_ds_Y
Centr_ds_Y
ScrolledWidgetsPane::RemoveIllegalChars
CL_sk4.2
CL_sk42
ScrolledWidgetsPane::TruncateFieldName
CL_sk42
ScrolledWidgetsPane::RenameDupFieldName
CL_sk42
CL_sk42
Click FieldNameCorrectionDlg::OnCancelClick
Exit FieldNameCorrectionDlg

**Comment by lixun910** [comment]
step: 1. open kmeans dialog
2. change the "Save Cluster in Field" from "CL" to "CL4.2", so "Update Field Name" dialog will be prompt.
3. run Kmeans
4. click File->Save
5. click cancel button in "Update Field Name"

**Comment by lixun910** [comment]
@emochoa 
Thanks for reporting this issue! I just fixed this crash. Can you verify this fix using the latest GeoDa 1.12.1.59: https://www.dropbox.com/s/htv3ku96rdao2sk/GeoDa1.12.1.59-Installer.dmg?dl=0
Thanks!
Best,

Xun Li Ph.D.

Assistant Director for Data Science
Center of Spatial Data Science
University of Chicago

**Comment by lixun910** [comment]
@emochoa  I believe this crash is reported by a student in Luc's class (who also posted the issue https://github.com/GeoDaCenter/geoda/issues/1145)

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.157

<img width="871" alt="screen shot 2018-07-03 at 9 41 08 pm" src="https://user-images.githubusercontent.com/37029239/42253972-fc62ab00-7f09-11e8-8f95-4a88be0a0872.png">
<img width="717" alt="screen shot 2018-07-03 at 9 40 03 pm" src="https://user-images.githubusercontent.com/37029239/42253974-fc949980-7f09-11e8-83ce-ea18836dddc6.png">
<img width="428" alt="screen shot 2018-07-03 at 9 40 29 pm" src="https://user-images.githubusercontent.com/37029239/42253973-fc89462a-7f09-11e8-9b11-097c212c2863.png">
GeoDa crashes when clicking "cancel"

I believe my GeoDa is up to date. I clicked on the dropbox link provided by lixun910 but now page was found.

**Comment by VeraB620** [comment]
OS X El Capitan 10.11.6
GeoDa 1.12.1.141

No prompt to change Field Name, allowed for CL4.2 and ran it it without a crash
<img width="754" alt="screen shot 2018-07-05 at 2 15 29 pm" src="https://user-images.githubusercontent.com/4943475/42343246-15d046ec-805e-11e8-8c2e-c599f064e758.png">

**Comment by jkoschinsky** [comment]
@ncarola: Could you check if you still get a crash? Will send you latest version. thx

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.143
Verified

After changing CL to CL4.2, no "Update Field Name"  pops up and the map runs with out error, similar to VeraB620.
<img width="595" alt="screen shot 2018-07-24 at 7 35 26 pm" src="https://user-images.githubusercontent.com/37029239/43173254-8b9d2690-8f79-11e8-89e7-c8c97072fedf.png">
<img width="869" alt="screen shot 2018-07-24 at 7 35 17 pm" src="https://user-images.githubusercontent.com/37029239/43173255-8bb5c506-8f79-11e8-8239-a4c2f50c6f0c.png">
