### ISSUE TITLE
Max-p doesn't handle well the case "island in weights" 

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1368]
From: kaitingzhou@gmail.com
 Details:
os: 1-10-13
vs: 1-12-1-59
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/KaitingZhou/Google Drive/Spatial Data Science/Project/Public Use Microdata Areas/nyc_pumas.shp
Open Layer:nyc_pumas
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/KaitingZhou/Google Drive/Spatial Data Science/Project/Public Use Microdata Areas/nyc_pumas.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Open AbstractClusterDlg.
Open Max-p dialog.
On MaxpDlg::CreateControls
On MaxpDlg::InitVariableCombobox
Click MaxpDlg::OnOK
On MaxpDlg::InitVariableCombobox
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
On MaxpDlg::OnChangeSeed
Click MaxpDlg::OnOK
On MaxpDlg::InitVariableCombobox
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
On MaxpDlg::OnChangeSeed
Click MaxpDlg::OnOK
On MaxpDlg::InitVariableCombobox
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
On MaxpDlg::OnChangeSeed
On MaxpDlg::OnChangeSeed
Click MaxpDlg::OnOK
On MaxpDlg::InitVariableCombobox
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click MaxpDlg::OnOK
On MaxpDlg::InitVariableCombobox
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click MaxpDlg::OnOK
On MaxpDlg::InitVariableCombobox
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click MaxpDlg::OnOK
On MaxpDlg::InitVariableCombobox
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click MaxpDlg::OnOK
On MaxpDlg::InitVariableCombobox
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click MaxpDlg::OnOK
On MaxpDlg::InitVariableCombobox
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click MaxpDlg::OnOK
On MaxpDlg::InitVariableCombobox
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click MaxpDlg::OnOK
On MaxpDlg::InitVariableCombobox
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Click GdaFrame::OnSaveProject
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs
New Datasource Name:/Users/KaitingZhou/Google Drive/Spatial Data Science/Project/Public Use Microdata Areas/GdaTmp_nyc_pumas.shp
Project::GetSpatialReference()
Project::GetGdaGeometries()
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
POLY_ID
ScrolledWidgetsPane::IsFieldNameValid
puma
ScrolledWidgetsPane::IsFieldNameValid
shape_leng
ScrolledWidgetsPane::IsFieldNameValid
shape_area
ScrolledWidgetsPane::IsFieldNameValid
FEMALE
ScrolledWidgetsPane::IsFieldNameValid
female_aa
ScrolledWidgetsPane::IsFieldNameValid
ttl_pop
ScrolledWidgetsPane::IsFieldNameValid
prime_age
ScrolledWidgetsPane::IsFieldNameValid
foreign
ScrolledWidgetsPane::IsFieldNameValid
badeng
ScrolledWidgetsPane::IsFieldNameValid
white_pop
ScrolledWidgetsPane::IsFieldNameValid
lonely
ScrolledWidgetsPane::IsFieldNameValid
mrrkid
ScrolledWidgetsPane::IsFieldNameValid
samehome
ScrolledWidgetsPane::IsFieldNameValid
ind_art
ScrolledWidgetsPane::IsFieldNameValid
ind_prof
ScrolledWidgetsPane::IsFieldNameValid
commute
ScrolledWidgetsPane::IsFieldNameValid
longcomm
ScrolledWidgetsPane::IsFieldNameValid
inequa
ScrolledWidgetsPane::IsFieldNameValid
occ_serv
ScrolledWidgetsPane::IsFieldNameValid
medhhinc
ScrolledWidgetsPane::IsFieldNameValid
medhouse
ScrolledWidgetsPane::IsFieldNameValid
pubasst
ScrolledWidgetsPane::IsFieldNameValid
selfemp
ScrolledWidgetsPane::IsFieldNameValid
PC1
ScrolledWidgetsPane::IsFieldNameValid
PC2
ScrolledWidgetsPane::IsFieldNameValid
PC3
ScrolledWidgetsPane::IsFieldNameValid
PC4
ScrolledWidgetsPane::IsFieldNameValid
PC5
ScrolledWidgetsPane::IsFieldNameValid
PC6
ScrolledWidgetsPane::IsFieldNameValid
COORD_X
ScrolledWidgetsPane::IsFieldNameValid
COORD_Y
ScrolledWidgetsPane::IsFieldNameValid
CL_k4_c
ScrolledWidgetsPane::IsFieldNameValid
CL_k5_c
ScrolledWidgetsPane::IsFieldNameValid
CL_ck5_w
ScrolledWidgetsPane::IsFieldNameValid
CL_s5
ScrolledWidgetsPane::IsFieldNameValid
CL
ScrolledWidgetsPane::IsFieldNameValid
CL_m
ScrolledWidgetsPane::IsFieldNameValid
CL_m2
ScrolledWidgetsPane::IsFieldNameValid
CL_m3
In FieldNameCorrectionDlg
Out FieldNameCorrectionDlg
start OGRLayerProxy::AddFreatures()
Out OGRDataAdapter::ExportDataSource()
Exiting Project::SaveDataSourceAs
Exiting Project::SaveDataSourceData
Entering Project::SaveProjectConf
Project::GetProjectFullPath()
In Project::UpdateProjectConf
Exiting Project::SaveProjectConf
Click MaxpDlg::OnOK
On MaxpDlg::InitVariableCombobox
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click MaxpDlg::OnOK

**Comment by lixun910** [comment]
Hi Kaiting,

Thanks for reporting this! Is this a crash related to the maxp feature? Can you send me the max-p configuration? as well as the nyc_pumas dataset? so we can replicate and fix this issue. We will keep it confidential. 

Thanks!

Best,

Xun Li,  Ph.D.

Assistant Director of Data Science
Center of Spatial Data Science
University of Chicago
http://spatial.uchicago.edu <http://spatial.uchicago.edu/>

**Comment by lixun910** [comment]
NYC dataset: 
Max-p clustering on PC1-6 (PCA results). Queen-continuity weights. Min # of regions = 4. 
An alternative way to crash it: Min population 5% ~ 15% of ttl_pop

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.61
This is what I got when running Max-P with queen weights, min # of regions = 4, on PC1-6
![image](https://user-images.githubusercontent.com/22801047/33493665-67358c04-d686-11e7-8aef-4f38cfc83351.png)
Output map is below. 
![image](https://user-images.githubusercontent.com/22801047/33493700-838fead4-d686-11e7-8231-d9ea88b44487.png)
I checked the table and the values in PC1-6 are not blank. 
![image](https://user-images.githubusercontent.com/22801047/33493732-99cb7ae8-d686-11e7-9026-d13a3f99e52e.png)

**Comment by lixun910** [comment]
This is correct.

For NYC dataset, the max-p algorithm starts from the North Shore. Since the graph is not fully connected, the only cluster max-p can detect is the one with 3 observations: North Shore, Mid-Island, South Shore. 

However, @YidanJ-Wu specified that minimum number of observations in each cluster is 4, so it's correct that max-p can't find a cluster.

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v113
OSX
