### ISSUE TITLE
Skater doesn't work correctly with islands defined in weights

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1370]

**Comment by YidanJ-Wu** [comment]
GeoDa 1.12.1.61
Windows 8

I used a queen weights file with precision threshold 0.0001. Here is the connectivity histogram:
![image](https://user-images.githubusercontent.com/22801047/33493365-6bf7dfcc-d685-11e7-8abf-77738be4f2c2.png)

This is the map that I got when I ran Skater with 4 clusters: 
![image](https://user-images.githubusercontent.com/22801047/33493308-415855bc-d685-11e7-84ee-4e14f01a34d2.png)

![image](https://user-images.githubusercontent.com/22801047/33493244-0c19aaea-d685-11e7-9732-6393cd65caa0.png)

The 4 variables used are forwh07, hhsiz05, kids2000, rent2008. Here is the settings window:
![image](https://user-images.githubusercontent.com/22801047/33493294-3567f942-d685-11e7-99dc-d325259532fd.png)

**Comment by lanselin** [comment]
this is somewhat confusing. maybe skater started on
Staten Island and then gets stuck. so, in fact, the warning just takes whatever 
subset is not connected to the original tree and calls it “isolated observations”,
which in a strict sense, they are not.

**Comment by lixun910** [comment]
This is caused by randomness of MST function — the starting node to build a MST, in one case (the student in your class) the MST returns a tree contains 52 observations, and in Julie’s case the MST returns a tree contains 3 observations.

**Comment by lanselin** [comment]
how can the randomness of the starting point be controlled?  i guess maybe that is where
the random seed of skater comes in — although i didn’t think we used it.

the skater random starting point should be replicable, so we get the same MST each time.
is that the case?

**Comment by lixun910** [comment]
In boost prim_minimum_spanning_tree(), the default starting vertex is the first vertices when building the graph (g):

IN: root_vertex(vertex_descriptor r)
The vertex that will be the root of the minimum spanning tree. The choice of the root vertex is arbitrary.
Default: *vertices(g).first

It is the same with Skater (R) — which doesn’t allow specify starting vertex. (see skater.c)

How about do a scan when the size of MST is significant less than the number of observations, then pick another random starting vertex, until the size of MST is large enough (e.g. at least half of the tree size) or reach a predefined maximum round of searching (e.g. 10)?

**Comment by lixun910** [comment]
Follow up previous,  I just compared the two weights file created by your student and Julie,  the first rows in the gal files are different. 
One use POLY_ID, one use “Code” 

0 55 nyc_pumas POLY_ID
1 3
2 6 11

0 55 "NYC Data" code
402 4
401 403 404 405

**Comment by lanselin** [comment]
another solution is to rephrase the warning, e.g., “Minimum spanning tree is incomplete,
please adjust the spatial weights” rather than suggesting the observations are isolates
(which they may not be)?
that way, we can keep the MST algorithm as is, but focus on detecting when the number
of nodes is not n-1.

**Comment by lixun910** [comment]
Sorry, I just pasted a wrong piece. Here is the original one:

0 55 "NYC Data" code
501 1
502
502 2
501 503
503 1
502

As you can see, the starting node is the  501, "North Shore”, so it ends up a MST with only 3 nodes.

> 0 55 "NYC Data" code
> 402 4
> 401 403 404 405

**Comment by lixun910** [comment]
OK.  One question: the label “Isolated” in the map legend  —> should change it to “Not clustered”?

**Comment by lanselin** [comment]
yes,  that would be preferred
