### ISSUE TITLE
Crash: Add centroids/Thiessen polygons for duplicates

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1380]
From: 
 Details:
os: 1-10-12
vs: 1-12-0-0
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/julietazzir/Documents/GEOG 305/california.xlsx
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
In TableFrame::OnActivate
GdaFrame::OpenProject()
/Users/julietazzir/Desktop/california.gda
Project::GetProjectFullPath()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Place
Open HistogramFrame.
In HistogramFrame::OnActivate()
In TableFrame::OnActivate
In HistogramFrame::OnActivate()
Open DataMovieDlg.
Entering DataMovieDlg::OnFieldChoice
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
In DataMovieDlg::OnMoveSlider
Entering DataMovieDlg::OnAscendingRB
Close DataMovieDlg::OnClose
Open CatClassifFrame
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/julietazzir/Documents/GEOG 305/United States Gun.zip
Open Layer:United States Gun
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/julietazzir/Documents/GEOG 305/United States Gun.zip
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/julietazzir/Documents/GEOG 305/mass shooting worldwide.xlsx
Open Layer:mass shooting worldwide
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/julietazzir/Documents/GEOG 305/mass shooting worldwide.xlsx
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
In TableFrame::OnActivate
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/julietazzir/Documents/GEOG 305/mass shooting worldwide.xlsx
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
In TableFrame::OnActivate
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/julietazzir/Documents/GEOG 305/mass shooting worldwide.xlsx
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
In TableFrame::OnActivate
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
Close CreatingWeightDlg
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In TableFrame::OnActivate
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
Click GdaFrame::OnToolsWeightsManager
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In TableFrame::OnActivate
In GdaFrame::OnGeneratePointShpFile()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
deaths_a
source_date
In TableFrame::OnActivate
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
MapCanvas::~MapCanvas()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
deaths_a
source_date
In TableFrame::OnActivate
Open CartogramNewFrame.
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Project::GetVoronoiRookNeighborGal()
Project::GetVoronoiRookNeighborMap()
Project::IsPointDuplicates()
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()

**Comment by jkoschinsky** [comment]
1. try loading Excel file with duplicate XYs (e.g. edit Baltimore sample data to get duplicates)
2. map it
3. add centroids to table
4. add Thiessen polygons

**Comment by YidanJ-Wu** [comment]
Windows 8 
GeoDa 1.12.1.85
Loaded CSV with duplicate X and Y values
Added centroids to table
Added thiessen polygons
saved thiessen polygons as .shp file and reopened.
![image](https://user-images.githubusercontent.com/22801047/35662850-0432ec48-06e0-11e8-8be6-cf24634335ce.png)
note the text below: there are 2 polygons selected. "hover obs 481, 508" so the thiessen polygons created from duplicate polygons were saved.
