### ISSUE TITLE
Debug alert window when running co location map

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#1391]
Windows 8 
1.12.1.65
![image](https://user-images.githubusercontent.com/22801047/33700529-6c69a02c-dadf-11e7-9514-18b861337cb2.png)

I got this debug alert when I was about to run the co-location map. 
Possible causes: 
one of the variables I selected had a blank value. 
I changed one of the variables (T114_002) from "string" to "real" in the same GeoDa session. That variable is actually not showing up in the Select Variables dialog. 
![image](https://user-images.githubusercontent.com/22801047/33700590-c2c00d08-dadf-11e7-91e1-d9ea20ffe501.png)

Edit: GeoDa refuses to let me run co-location map. Whenever I close the debug alert window it opens up again.

**Comment by YidanJ-Wu** [comment]
Tried again and it worked this time 
![image](https://user-images.githubusercontent.com/22801047/33701384-2b24f30a-dae4-11e7-8e03-57a4e9319d9c.png)

**Comment by lixun910** [comment]
@YidanJ-Wu  Got it. Thanks for finding this bug!

Can you share the data with me? Thanks!

Xun

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.73
The co-location map works now: 
![image](https://user-images.githubusercontent.com/22801047/34075122-e7354f10-e28a-11e7-80d9-dd65840c8c39.png)

Sometimes the debug alert window pops up (not every time). Then I click "cancel" and the co-location map displays correctly.

**Comment by lixun910** [comment]
Verified in Mac and Ubuntu 18.04 using GeoDa 1.14.
