### ISSUE TITLE
Crash: Time editor with date/time variables

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1398]
From: 
 Details:
os: 3-4-10
vs: 1-12-0-0
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/caillaul/Téléchargements/fire_nrt_V1_22444.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
FRP
Open BoxPlotCanvas.
Close BoxPlotCanvas.
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
Open TimeChooserDlg.
Open VarGroupingEditorDlg.
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListEdit
In VarGroupingEditorDlg::OnIncludeListEdit
In VarGroupingEditorDlg::OnIncludeListEditEnd
In VarGroupingEditorDlg::OnIncludeListEditEnd
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListEdit
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListEditEnd
In VarGroupingEditorDlg::OnClose
Close TimeChooserDlg::OnClose
In GdaFrame::OnCondPlotChoices()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
ACQ_DATE
ACQ_TIME
ACQ_TIME

**Comment by jkoschinsky** [comment]
@YidanJ-Wu 
pls try to break the time editor with date and time variables (e.g. using abandoned car file from Luc's lab).

**Comment by YidanJ-Wu** [comment]
Windows 8
1.12.1.85
Abandoned car file initially had the date field in string format. I used Variable Properties to change the date field into a date format. GeoDa catches rows with blank values in the date field, and will give an error message: 
![image](https://user-images.githubusercontent.com/22801047/35717168-18c66626-07a3-11e8-924c-4f2d67ae5ce8.png)
If any row has an invalid date entered like 2015-09-00 or 2015-09-001 in string format, converting to date format renders that row blank. 
So far no crash. Also worth noting that -01 and -1 are read the same, and that strings like "2015-09-32" are converted to date format without any crash or warning message.
