### ISSUE TITLE
Crash: GeoDa Lab1?

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1402]
From: wintong@uchicago.edu
 Details:
os: 1-10-12
vs: 1-12-1-7
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/winnietong/Desktop/data/Boundaries of Chicago neighborhoods.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnOpenPercentile()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
Open MergeTableDlg.
Entering MergeTableDlg::OnOpenClick()
In MergeTableDlg::OnClose()
Open MergeTableDlg.
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/winnietong/Downloads/comarea (2)/ComArea_ACS14_f.dbf
Open Layer:ComArea_ACS14_f
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
ds:/Users/winnietong/Downloads/comarea (2)/ComArea_ACS14_f.dbf layer: ComArea_ACS14_f
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
In MergeTableDlg::OnMergeClick()
Open FieldNameCorrectionDlg:
ScrolledWidgetsPane::RemoveIllegalChars
PopFP
PopFP
ScrolledWidgetsPane::TruncateFieldName
PopFP
ScrolledWidgetsPane::RenameDupFieldName
PopFP
PopFP_1
ScrolledWidgetsPane::RemoveIllegalChars
Pov50P
Pov50P
ScrolledWidgetsPane::TruncateFieldName
Pov50P
ScrolledWidgetsPane::RenameDupFieldName
Pov50P
Pov50P_1
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
PopFem_1
ScrolledWidgetsPane::IsFieldNameValid
Pov50Pro_1
Exit FieldNameCorrectionDlg
In MergeTableDlg::OnClose()
In GdaFrame::OnOpenRawrate()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
In GdaFrame::OpenQuantile(8)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
Open PCASettingsDlg.
Click PCASettingsDlg::OnOK
OnSave PCASettingsDlg.
Close HClusterDlg
In GdaFrame::OpenNaturalBreaks(4)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PC1
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OpenNaturalBreaks(4)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PC2
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
Open LisaMapFrame (OnOpenUniLisa).
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnCreateNewIdClick
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnCreateNewIdClick
Try to insert unique id (integer, PC1wght) column in table.
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnCRadioQueenSelected
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/Users/winnietong/Desktop/data/Boundaries of Chicago neighborhoodspc1wght.gal
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
Close CreatingWeightDlg
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PC1
VariableSettingsDlg::GetWeightsId() weight: Boundaries of Chicago neighborhoodspc1wght
VariableSettingsDlg::GetWeightsId() weight: Boundaries of Chicago neighborhoodspc1wght
Entering LisaCoordinator::LisaCoordinator().
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
Entering LisaCoordinator::InitFromVarInfo()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Entering LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::CalcLisa()
Entering LisaCoordinator::CalcPseudoP()
Entering LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP()
Exiting LisaCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
In LisaCoordinator::registerObserver()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
In GdaFrame::OpenNaturalBreaks(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PC1
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
In OnSigFilter01()
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
In LisaCoordinator::notifyObservers
In OnSigFilter001()
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
In LisaCoordinator::notifyObservers
In GdaFrame::OnAddNeighborToSelection()
In GdaFrame::OnShowAsConditionalMap()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
Entering LisaCoordinator::removeObserver
Exiting LisaCoordinator::removeObserver
MapCanvas::~MapCanvas()
Entering LisaCoordinator::removeObserver
Exiting LisaCoordinator::removeObserver
Entering LisaCoordinator::removeObserver
In LisaCoordinator::~LisaCoordinator().
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::removeObserver
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Open LocalGearyFrame (OnOpenUniLocalGeary).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PC1
VariableSettingsDlg::GetWeightsId() weight: Boundaries of Chicago neighborhoodspc1wght
VariableSettingsDlg::GetWeightsId() weight: Boundaries of Chicago neighborhoodspc1wght
In LocalGearyCoordinator::LocalGearyCoordinator()
In LocalGearyCoordinator::SetSignificanceFilter()
In LocalGearyCoordinator::InitFromVarInfo()
In LocalGearyCoordinator::DeallocateVectors()
In LocalGearyCoordinator::AllocateVectors()
In LocalGearyCoordinator::StandardizeData()
In LocalGearyCoordinator::CalcLocalGeary()
End LocalGearyCoordinator::CalcLocalGeary()
In LocalGearyCoordinator::CalcPseudoP()
In LocalGearyCoordinator::CalcPseudoP_threaded()
End LocalGearyCoordinator::CalcPseudoP_threaded()
End LocalGearyCoordinator::CalcPseudoP()
Entering LocalGearyMapFrame::LocalGearyMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Entering LocalGearyMapCanvas::LocalGearyMapCanvas()
Entering LocalGearyMapCanvas::CreateAndUpdateCategories()
Entering LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::CreateAndUpdateCategories()
Exiting LocalGearyMapCanvas::LocalGearyMapCanvas()
In LocalGearyCoordinator::registerObserver()
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::MapMenus
Exiting LocalGearyMapFrame::LocalGearyMapFrame
Entering LocalGearyMapFrame::LocalGearyMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Entering LocalGearyMapCanvas::LocalGearyMapCanvas()
Entering LocalGearyMapCanvas::CreateAndUpdateCategories()
Entering LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::CreateAndUpdateCategories()
Exiting LocalGearyMapCanvas::LocalGearyMapCanvas()
In LocalGearyCoordinator::registerObserver()
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::MapMenus
Exiting LocalGearyMapFrame::LocalGearyMapFrame
In LocalGearyCoordinator::CalcPseudoP_range()
In LocalGearyCoordinator::CalcPseudoP_range()
In LocalGearyCoordinator::CalcPseudoP_range()
In LocalGearyCoordinator::CalcPseudoP_range()
End LocalGearyCoordinator::CalcPseudoP_range()
End LocalGearyCoordinator::CalcPseudoP_range()
End LocalGearyCoordinator::CalcPseudoP_range()
End LocalGearyCoordinator::CalcPseudoP_range()
Entering LocalGearyMapCanvas::DisplayRightClickMenu
In LocalGearyMapFrame::OnActivate
In OnSigFilter001()
Entering LocalGearyMapFrame::SetSigFilterX() 3
In LocalGearyCoordinator::SetSignificanceFilter()
In LocalGearyCoordinator::notifyObservers()
In LocalGearyMapFrame::update
Entering LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Entering LocalGearyMapCanvas::CreateAndUpdateCategories()
Entering LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::CreateAndUpdateCategories()
In LocalGearyMapFrame::update
Entering LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Entering LocalGearyMapCanvas::CreateAndUpdateCategories()
Entering LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::CreateAndUpdateCategories()
Exiting LocalGearyMapFrame::SetSigFilterX()
Exiting LocalGearyMapCanvas::DisplayRightClickMenu
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::MapMenus
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::MapMenus
Entering LocalGearyMapCanvas::DisplayRightClickMenu
In LocalGearyMapFrame::OnActivate
In OnSigFilter01()
Entering LocalGearyMapFrame::SetSigFilterX() 2
In LocalGearyCoordinator::SetSignificanceFilter()
In LocalGearyCoordinator::notifyObservers()
In LocalGearyMapFrame::update
Entering LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Entering LocalGearyMapCanvas::CreateAndUpdateCategories()
Entering LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::CreateAndUpdateCategories()
In LocalGearyMapFrame::update
Entering LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Entering LocalGearyMapCanvas::CreateAndUpdateCategories()
Entering LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::CreateAndUpdateCategories()
Exiting LocalGearyMapFrame::SetSigFilterX()
Exiting LocalGearyMapCanvas::DisplayRightClickMenu
Entering LocalGearyMapCanvas::DisplayRightClickMenu
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::MapMenus
In GdaFrame::OnAddNeighborToSelection()
Entering LocalGearyMapFrame::OnAddNeighborToSelection
Exiting LocalGearyMapFrame::OnAddNeighborToSelection
Exiting LocalGearyMapCanvas::DisplayRightClickMenu
Entering LocalGearyMapCanvas::DisplayRightClickMenu
In LocalGearyMapFrame::OnActivate
In OnRanOtherPer()
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::MapMenus
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::MapMenus
99999
Entering LocalGearyMapFrame::RanXPer() 99999
In LocalGearyCoordinator::CalcPseudoP()
In LocalGearyCoordinator::CalcPseudoP_threaded()
End LocalGearyCoordinator::CalcPseudoP_threaded()
End LocalGearyCoordinator::CalcPseudoP()
In LocalGearyCoordinator::notifyObservers()
In LocalGearyMapFrame::update
Entering LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Entering LocalGearyMapCanvas::CreateAndUpdateCategories()
Entering LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::CreateAndUpdateCategories()
In LocalGearyMapFrame::update
Entering LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Entering LocalGearyMapCanvas::CreateAndUpdateCategories()
Entering LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::CreateAndUpdateCategories()
Exiting LocalGearyMapFrame::RanXPer()
Exiting LocalGearyMapCanvas::DisplayRightClickMenu
In LocalGearyCoordinator::CalcPseudoP_range()
In LocalGearyCoordinator::CalcPseudoP_range()
In LocalGearyCoordinator::CalcPseudoP_range()
In LocalGearyCoordinator::CalcPseudoP_range()
End LocalGearyCoordinator::CalcPseudoP_range()
End LocalGearyCoordinator::CalcPseudoP_range()
End LocalGearyCoordinator::CalcPseudoP_range()
End LocalGearyCoordinator::CalcPseudoP_range()
Entering LocalGearyMapCanvas::DisplayRightClickMenu
In LocalGearyMapFrame::OnActivate
In OnSigFilter001()
Entering LocalGearyMapFrame::SetSigFilterX() 3
In LocalGearyCoordinator::SetSignificanceFilter()
In LocalGearyCoordinator::notifyObservers()
In LocalGearyMapFrame::update
Entering LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Entering LocalGearyMapCanvas::CreateAndUpdateCategories()
Entering LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::CreateAndUpdateCategories()
In LocalGearyMapFrame::update
Entering LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Entering LocalGearyMapCanvas::CreateAndUpdateCategories()
Entering LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::CreateAndUpdateCategories()
Exiting LocalGearyMapFrame::SetSigFilterX()
Exiting LocalGearyMapCanvas::DisplayRightClickMenu
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::MapMenus
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::MapMenus
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::MapMenus
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::OnActivate
Entering LocalGearyMapCanvas::DisplayRightClickMenu
In LocalGearyMapFrame::OnActivate
In OnSigFilter0001()
Entering LocalGearyMapFrame::SetSigFilterX() 4
In LocalGearyCoordinator::SetSignificanceFilter()
In LocalGearyCoordinator::notifyObservers()
In LocalGearyMapFrame::update
Entering LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Entering LocalGearyMapCanvas::CreateAndUpdateCategories()
Entering LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::CreateAndUpdateCategories()
In LocalGearyMapFrame::update
Entering LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Entering LocalGearyMapCanvas::CreateAndUpdateCategories()
Entering LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::SyncVarInfoFromCoordinator
Exiting LocalGearyMapCanvas::CreateAndUpdateCategories()
Exiting LocalGearyMapFrame::SetSigFilterX()
Exiting LocalGearyMapCanvas::DisplayRightClickMenu
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::MapMenus
In LocalGearyMapFrame::~LocalGearyMapFrame
In LocalGearyCoordinator::removeObserver()
In LocalGearyMapCanvas::~LocalGearyMapCanvas
MapCanvas::~MapCanvas()
In LocalGearyMapFrame::OnActivate
In LocalGearyMapFrame::~LocalGearyMapFrame
In LocalGearyCoordinator::removeObserver()
In LocalGearyCoordinator::~LocalGearyCoordinator()
In LocalGearyCoordinator::DeallocateVectors()
In LocalGearyMapCanvas::~LocalGearyMapCanvas
MapCanvas::~MapCanvas()
In GdaFrame::OnOpenHinge30()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
In GdaFrame::OnOpenHinge15()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Incid_2015
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Open Themeless Map (OnOpenThemelessMap).
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In WeightsManFrame::OnActivate
In GdaFrame::OnAddCentroids()
In Project::AddCentroids
Project::GetCentroids()
Open AbstractClusterDlg.
Open KMeanDlg.
Click KMeansDlg::OnOK
Project::GetCentroids()
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click KMeansDlg::OnOK
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click KMeansDlg::OnOK
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Close KMeansDlg
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Open AbstractClusterDlg.
Open Max-p dialog.
On MaxpDlg::CreateControls
On MaxpDlg::InitVariableCombobox
Click MaxpDlg::OnOK
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click MaxpDlg::OnOK

**Comment by jkoschinsky** [comment]
@DarcyLinde 
looks like they got a crash doing lab 1:
http://geodacenter.github.io/workbook/1_datascience/lab1.html

**Comment by DarcyLinde** [comment]
At what point did they get the crash? I didn't go through lab 1 entirely because I didn't have the population data

**Comment by jkoschinsky** [comment]
Looks like they crashed on max-p, which isn't part of Lab 1, so they might've gone off course :)

But here's the pop data:
[Community_Pop.csv.zip](https://github.com/GeoDaCenter/geoda/files/1675177/Community_Pop.csv.zip)

**Comment by bsalas11** [comment]
Win 1.14

No crash encountered in lab 1.

No crash encountered with max-p, even with extreme values. I ran through the lab on "cluster analysis (3)" which features max-p and did not find any problems there either.
