### ISSUE TITLE
Differences in tutorial Local Spatial Autocorrelation (1)

### ISSUE THREAD

**Issue by anvalanz** [GeoDaCenter/geoda#1403]

**Comment by anvalanz** [comment]
The numbers for column LISA_P which I have generated following the tutoral are different from those shown in the documentation.
![error_lisa_p](https://user-images.githubusercontent.com/6723429/33800127-b38ceac4-dd3a-11e7-850f-fb1544970366.PNG)
Specifically only the first 2 records show a value of LISA_P which are the same as the documentation all the other records not.
The same doesn't happen for the other variables LISA_I e LISA_CL, so I think I have correctly done all the suggested operations.
What is the reason for such differences ?
My previous issue was about another similar problem of not coincident values using the same Guerry data.
Is it  a problem of stability of software depending on the operating system (MAC OS or WIN OS)?
I am using version 1.12.1.59 on Win 10.

**Comment by lixun910** [comment]
Thanks for reporting this issue!  Very good point!

I just checked our code, and realize this is a very old bug in GeoDa. The reason you see the differences is because of the random number generator in GeoDa doesn’t handle the case with different CPU cores on different machines. In your case:
(which I can replicate), your results are generated by using a 2-core machine. However, I believe the results from the online document are generated by using a 8-core machine. I think this also explain another issue you reported today #1400.

One can generate same LISA results if a seed is specified for RNG on one machine. However, if another user is using a machine with different number of CPU cores, the LISA results will be different even a same seed is specified for RNG.

**Comment by anvalanz** [comment]
How do you think to solve the problem of differente cores and different RNG behaviour ?
In several part of the online documentation is stated that the only way to replicate the results  is to use the same seed (so I haven't changed the default sequence 123456789) but as you are saying this is not enough.
If do not come to a reasonable solution it will be worth to put an advice in the documentation saying that it is impossible to guarantee the replication of the results due to ..... ( a brief explanation) so the user knows this and can continue reading the tutorial without doubt about his correct way of doing the exercise.
Let me know what is the decision of the team.

**Comment by lixun910** [comment]
This is a bug. I am fixing it. Will keep you updated with any new GeoDa release. Thanks!

**Comment by lixun910** [comment]
@anvalanz   I have a new GeoDa version 1.12.1.71 for windows with a fix of this issue. Can you help to verify it ? if you got the same results as mine (running on Mac OS X using 8 cores). Thanks!

You can download it from:  https://www.dropbox.com/s/a7m630tiumj6ncu/GeoDa-1.12.1.71-Windows-64bit.exe?dl=0

My results:  guerry, queen weights, donats, LISA 999 permutations

<img width="1347" alt="screen shot 2017-12-11 at 3 33 32 pm" src="https://user-images.githubusercontent.com/2423887/33857476-13ad2eba-de89-11e7-87ee-d67a1beefcdb.png">

**Comment by anvalanz** [comment]
I have installed the new version 1.12.1.71 as you have suggested and the results are the same of your run so the problem has been fixed as you can see from the screenshot.
 
![lisa_p_results](https://user-images.githubusercontent.com/6723429/33912153-03103b3a-df95-11e7-9efe-6f878d3f7fa5.PNG)

Now just to be precise you should also update the documentation file  with a new run using the last version  (and the same parameters: queen weights, 99999 permutations)  so that users are able to replicate the exercise and to obtain identical results of the documentation.
The results of my run with the same parameters of the documentation are:

![lisa_p_values](https://user-images.githubusercontent.com/6723429/33912679-21db92e2-df97-11e7-80dd-7eb835762185.PNG)

Thanks for your fast reply and fixing.

A.  Valanzano

**Comment by YidanJ-Wu** [comment]
Here's my attempt to replicate on Windows 8, 1.12.1.71
Guerry, donatns, queen weights
999 permutations produced the same results.
![image](https://user-images.githubusercontent.com/22801047/33976743-ee8c8972-e04b-11e7-9da2-7285129eb25c.png)
99999 permutations, custom inference set to 0.01 produced slightly different results.
![image](https://user-images.githubusercontent.com/22801047/33976812-57f85260-e04c-11e7-8309-48c06def39c1.png)
