### ISSUE TITLE
CSV files - problems with special characters

### ISSUE THREAD

**Issue by anvalanz** [GeoDaCenter/geoda#1408]
I have got the following csv file 

![csv_file](https://user-images.githubusercontent.com/6723429/33822881-6c562768-de59-11e7-95bf-5a5976d3cd6e.JPG)

and when I try to load it in GeoDa the form shows this

![preview](https://user-images.githubusercontent.com/6723429/33822924-8b443eb2-de59-11e7-904b-9390f0719c7f.JPG)

everything seems ok but once loaded as a table the situation is the following

![table](https://user-images.githubusercontent.com/6723429/33822988-c7071a96-de59-11e7-972c-cdc37b679a9e.JPG)
and as you can see some values are null.
This happens for values with special characters ù, è, ° .
I haven't find any option to specifiy the Character set to use e.g. UTF-8 or Win 1252 (for latin characters).

Just other two minor issues: 
when I try to increase the number of rows to show in a preview the limit is 11 rows even though you could write any number greater than 10

if the file contains an integer value  in the first record and all the other values are real then these real values are read as integers unless you know the type of values and specify the correct format in the form before loading the table. Do you rely on GDAL functions for reading csv files ?

**Comment by lixun910** [comment]
Did you try right click on table -> Encoding menu item?

<img width="640" alt="screen shot 2017-12-11 at 2 16 51 pm" src="https://user-images.githubusercontent.com/2423887/33854210-14c3eeca-de7e-11e7-9e23-721703c0620a.png">

Yes, GeoDa relies on GDAL to read csv.

**Comment by anvalanz** [comment]
It works if I choose Western European Latin-1 or Western European Latin-9.

Thanks
ps. what's about the limit of 11 rows as preview ?

**Comment by lixun910** [comment]
Did you try the latest version: https://www.dropbox.com/s/a7m630tiumj6ncu/GeoDa-1.12.1.71-Windows-64bit.exe?dl=0

It should fix the issue of limit of 11 rows in preview, as well as the issue of replicable LISA results (which was in my previous email) — also see: https://github.com/GeoDaCenter/geoda/issues/1403

Let me know any questions. Thanks!


Xun Li,  Ph.D.

Assistant Director for Data Science
Center of Spatial Data Science
University of Chicago
http://spatial.uchicago.edu



On Dec 12, 2017, at 1:06 AM, anvalanz <notifications@github.com<mailto:notifications@github.com>> wrote:


It works if I choose Western European Latin-1 or Western European Latin-9.

Thanks
ps. what's about the limit of 11 rows as preview ?

**Comment by anvalanz** [comment]
I  have verified thar the limit of 11 rows in preview  has been fixed.
Thanks
