### ISSUE TITLE
K-Means crash

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#1412]
GeoDa 1.12.1.71
Windows 8 
GeoDa freezes when running Guerry file through K-Means (screenshot below).
![image](https://user-images.githubusercontent.com/22801047/33976255-7a6ab594-e048-11e7-954e-affc0b5cac0c.png)
Also freezes when there are fewer variables selected.
![image](https://user-images.githubusercontent.com/22801047/33976300-d47eda74-e048-11e7-9d20-65d0f06c5494.png)

**Comment by anvalanz** [comment]
I have the same problem: K-Means  crash with Guerry data (Win10  64 bit GeoDa version 1.12.1.71).

Where can I download version 1.12.1.73 64bit ?
On the official website the last stable version is 1.12.1.59

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.110
Verified 

<img width="812" alt="11 mar 07" src="https://user-images.githubusercontent.com/36253697/37258195-f0e73d24-256b-11e8-8a28-e6565f2b082e.PNG">

**Comment by jkoschinsky** [comment]
fix confirmed
GeoDa v 111
OSX
