### ISSUE TITLE
Crash: delete variables from table and save

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1425]
From: 
 Details:
os: 1-10-10
vs: 1-12-1-59
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Volumes/USB DISK/University/GIS IB coursework/Project/ReigateBanstead_lsoa_burg_drug_sex_rates.shp
Open Layer:ReigateBanstead_lsoa_burg_drug_sex_rates
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Volumes/USB DISK/University/GIS IB coursework/Project/ReigateBanstead_lsoa_burg_drug_sex_rates.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
selected:0
Click CreatingWeightDlg::OnCRadioQueenSelected
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/Volumes/USB DISK/University/GIS IB coursework/Project/reigatebanstead_lsoa_qc1.gal
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
Close CreatingWeightDlg
In WeightsManFrame::OnActivate
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
selected:0
Click CreatingWeightDlg::OnCRadioQueenSelected
Click CreatingWeightDlg::OnCSpinOrderofcontiguityUpdated
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/Volumes/USB DISK/University/GIS IB coursework/Project/reigatebanstead_lsoa_qc2.gal
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
Click CreatingWeightDlg::OnCSpinOrderofcontiguityUpdated
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/Volumes/USB DISK/University/GIS IB coursework/Project/reigatebanstead_lsoa_qc3.gal
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
Close CreatingWeightDlg
In WeightsManFrame::OnActivate
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
Entering WeightsManFrame::OnRemoveBtn
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
Entering WeightsManFrame::OnRemoveBtn
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
BURGRATE
VariableSettingsDlg::GetWeightsId() weight: reigatebanstead_lsoa_qc1
VariableSettingsDlg::GetWeightsId() weight: reigatebanstead_lsoa_qc1
Entering LisaCoordinator::LisaCoordinator().
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
Entering LisaCoordinator::InitFromVarInfo()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Entering LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
In LisaCoordinator::registerObserver()
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
DRUGSRATE
VariableSettingsDlg::GetWeightsId() weight: reigatebanstead_lsoa_qc1
VariableSettingsDlg::GetWeightsId() weight: reigatebanstead_lsoa_qc1
Entering LisaCoordinator::LisaCoordinator().
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
Entering LisaCoordinator::InitFromVarInfo()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Entering LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
In LisaCoordinator::registerObserver()
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
VIOLENCE_1
VariableSettingsDlg::GetWeightsId() weight: reigatebanstead_lsoa_qc1
VariableSettingsDlg::GetWeightsId() weight: reigatebanstead_lsoa_qc1
Entering LisaCoordinator::LisaCoordinator().
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
Entering LisaCoordinator::InitFromVarInfo()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Entering LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
In LisaCoordinator::registerObserver()
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
BURGRATE
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
DRUGSRATE
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
Open DataViewerDeleteColDlg.
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnDelete()
VIOLENCE_1
DRUGSRATE
BURGRATE
VIOLENCESE
DRUGSCOUNT
BURGCOUNT
POPULATION
IDAOPIsc
IDACIsc
LIVINGsc
HOUSING_BA
CRIMEsc
HEALTHsc
EDUCsc
EMPLOYsc
INCOMEsc
IMDsc
shape_area
shape_leng
lsoa04nm
lsoa04cd

**Comment by YidanJ-Wu** [comment]
GeoDa 1.12.1.81 
Verified
