### ISSUE TITLE
Scatter plot of Principal Component  in Cluster Analysis(1) tutorial

### ISSUE THREAD

**Issue by anvalanz** [GeoDaCenter/geoda#1427]
Windows version 1.12.1.59 32 bit
The calculations were done following exactly the tutorial and the results are these
![pca_settings](https://user-images.githubusercontent.com/6723429/34146423-388c8f66-e49a-11e7-874e-b6c4d02d53be.JPG)

When I generate the scatter plot with variables PC1 e PC2 the result is this
![scatter_plot_pc1_pc2](https://user-images.githubusercontent.com/6723429/34146479-7cae3852-e49a-11e7-9550-bfb8e911d1fb.JPG)

As you can see the diagram is flipped around a vertical axis and the values (min -5.60, max 4.40) are switched  (tutorial: min -4.40, max 5.60).

**Comment by lixun910** [comment]
This is not a bug: the result may seem different from the standard output, but this is due to the indeterminacy of the signs of the eigenvectors. see: http://geodacenter.github.io/workbook/7a_clusters_1/lab7a.html
