### ISSUE TITLE
Scatter Plot (tutorial EDA) - 1] View Standardized data -2] Set Display precision

### ISSUE THREAD

**Issue by anvalanz** [GeoDaCenter/geoda#1430]
Geoda 1.12.1.59  32 bit on Windows 7 enterprise
![scatter_plot_original_data](https://user-images.githubusercontent.com/6723429/34154691-b32062ea-e4b6-11e7-955f-4a8111497aba.JPG)

1] if I choose View Standardized Data 
![scatter_plot_standardized_data](https://user-images.githubusercontent.com/6723429/34154806-1b8666c2-e4b7-11e7-8018-b0b2002f39c2.JPG)
and as you can see the axis ranges do not change and the diagram is not readble

2] if i change parameter for Set Display precision the number of digit do not change in the diagram, the numbers displayed are always integers (as you can see from the previous screenshot.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.110
Verified 

<img width="602" alt="11 mar 06" src="https://user-images.githubusercontent.com/36253697/37258037-92f6af9e-2569-11e8-84d8-fee153f7328a.PNG">

**Comment by jkoschinsky** [comment]
fix confirmed
GeoDa v 111
OSX
