### ISSUE TITLE
Crash: Test merging table and renaming duplicate field name

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1431]
From: f_moritz@hotmail.com
 Details:
os: 1-10-9
vs: 1-10-0-12
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/moritzfegert/Downloads/Archive
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/moritzfegert/Desktop/Excel country number users ISO3 sheet-2.xlsx
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/moritzfegert/Downloads/ne_10m_admin_0_sovereignty
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/moritzfegert/Downloads/TM_WORLD_BORDERS_SIMPL-0.3.shp
Open Layer:TM_WORLD_BORDERS_SIMPL-0.3
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/moritzfegert/Downloads/TM_WORLD_BORDERS_SIMPL-0.3.shp
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/moritzfegert/Downloads/TM_WORLD_BORDERS_SIMPL-0
GdaFrame::OpenProject()
/Users/moritzfegert/Desktop/GeoDa test data/ePing user map/ePing user map by country.gda
Entering Project::Project (existing project)
/Users/moritzfegert/Desktop/GeoDa test data/ePing user map/ePing user map by country.gda
Project::SetProjectFullPath()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/moritzfegert/Desktop/TM_WORLD_BORDERS_SIMPL-0
Open Layer:TM_WORLD_BORDERS_SIMPL-0.3
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/moritzfegert/Desktop/TM_WORLD_BORDERS_SIMPL-0
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open MergeTableDlg.
In MergeTableDlg::OnKeyChoice()
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/moritzfegert/Downloads/ePing user per country map.xlsx
Open Layer:ePing user per country map
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
ds:/Users/moritzfegert/Downloads/ePing user per country map.xlsx layer: ePing user per country map
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
In MergeTableDlg::OnMergeClick()
Open FieldNameCorrectionDlg:
ScrolledWidgetsPane::RemoveIllegalChars
ISO3
ScrolledWidgetsPane::TruncateFieldName
ISO3
ScrolledWidgetsPane::RenameDupFieldName
ISO3
ScrolledWidgetsPane::TruncateFieldName
ISO3

**Comment by YidanJ-Wu** [comment]
GeoDa 1.12.1.81 
Verified
