### ISSUE TITLE
Save Scatter Plot Matrix as image: add option as for other views

### ISSUE THREAD

**Issue by buracek** [GeoDaCenter/geoda#1435]
Is there any option how to export Scatter Plot Matrix to Image? This option is missing here...

**Comment by lixun910** [comment]
please check in v99

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.110
It says "Save Image As"

![11 mar05](https://user-images.githubusercontent.com/36253697/37257847-6cfec766-2566-11e8-8259-e1d22b3af233.JPG)


The saved image
![11 mar 04](https://user-images.githubusercontent.com/36253697/37257874-d38da11e-2566-11e8-87f9-c9f55d89eb05.png)

**Comment by jkoschinsky** [comment]
svg and postscript options are missing for scatterplot matrix but seems to be the case for all graphs

**Comment by lixun910** [comment]
Yes, a svg and ps are only for simple maps and graphs.
