### ISSUE TITLE
hierarchical clustering summary tab

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1438]
Summary tab of hierarchical clustering: Grey out until tree is cut.

**Comment by lixun910** [comment]
It’s not feasible to disable or grey out the tab. Instead, I add a text
“(Please click Save button to generate summary report.)” in the summary
tab.

**Comment by jkoschinsky** [comment]
How about for the text:

Please save results to see the summary report.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.110
Verified 

<img width="601" alt="11 mar 02" src="https://user-images.githubusercontent.com/36253697/37257651-562f0ed0-2564-11e8-86cb-f3288366aac5.PNG">

<img width="892" alt="11 mar 03" src="https://user-images.githubusercontent.com/36253697/37257654-5bf0de66-2564-11e8-9f60-e68dc7212e29.PNG">

**Comment by jkoschinsky** [comment]
fix confirmed
GeoDa v 111
OSX
