### ISSUE TITLE
recent data doesn't work for double click on gda file

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1442]
When one loads a gda file into the drop files here box, the gda file gets added to the "recent" list. However, when the file is loaded by double clicking on the gda file, this doesn't seem to happen. The "recent " list remains empty.

**Comment by lixun910** [comment]
please check in v99

**Comment by jkoschinsky** [comment]
GeoDa 1.99
MacOSX
fix verified
