### ISSUE TITLE
Weights: add inverse distance & kernel weights

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1445]

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.110
Verified 
<img width="723" alt="11 mar 01" src="https://user-images.githubusercontent.com/36253697/37256298-72a04138-2550-11e8-8f93-3f5b1e461fb7.PNG">

**Comment by jkoschinsky** [comment]
fix confirmed
GeoDa v 111
OSX
