### ISSUE TITLE
Max-p region problem results 

### ISSUE THREAD

**Issue by anvalanz** [GeoDaCenter/geoda#1446]
GeoDa 1.12.1.71  Max-p region Problem results are different from the results of Cluster Analysis (3) tutorial.
![max-p_region_problem](https://user-images.githubusercontent.com/6723429/34442130-6eb092bc-ecc0-11e7-8c93-efec95c738cb.PNG)

**Comment by YidanJ-Wu** [comment]
I got the same output as @anvalanz in 1.12.1.73 on Windows 8
![image](https://user-images.githubusercontent.com/22801047/34533202-d6546f30-f07e-11e7-865f-aabf4ac60f87.png)
![image](https://user-images.githubusercontent.com/22801047/34533208-e03fa136-f07e-11e7-888d-c2c6e168197b.png)

**Comment by lixun910** [comment]
As noted in the tutorial: the cluster methods in GeoDa are under active development and are not yet production grade. 

The one in the tutorial is old, and the new max-p algorithm comes with 3 local search methods: greedy , tabu search and simulated annealing. The result 0.526 in your screenshot is better than the old method.

<img width="930" alt="screen shot 2018-02-02 at 2 57 55 pm" src="https://user-images.githubusercontent.com/2423887/35756783-c7efa8d4-0829-11e8-9aaf-484847bfeb8a.png">
