### ISSUE TITLE
Crash: Weights

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1447]
From: 
 Details:
os: 1-10-13
vs: 1-12-1-59
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/jahairaysabelbandavasquez/Desktop/Geodata_tarea/California.7z
Open Layer:California
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/jahairaysabelbandavasquez/Desktop/Geodata_tarea/California.7z
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/jahairaysabelbandavasquez/Desktop/Geodata_tarea/California/California.shp
Open Layer:California
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/jahairaysabelbandavasquez/Desktop/Geodata_tarea/California/California.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OpenQuantile(6)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
P005001
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
P005001
Open HistogramFrame.
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
In HistogramFrame::OnActivate()
PNG selected
In HistogramFrame::OnActivate()
MapCanvas::~MapCanvas()
In GdaFrame::OpenNaturalBreaks(6)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
P005001
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
P005001
Open HistogramFrame.
In HistogramFrame::OnActivate()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
Open Themeless Map (OnOpenThemelessMap).
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
P052004
Open HistogramFrame.
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
In HistogramFrame::OnActivate()
PNG selected
In GdaFrame::OpenQuantile(6)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
P052004
In HistogramFrame::OnActivate()
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In HistogramFrame::OnActivate()
MapCanvas::~MapCanvas()
In GdaFrame::OpenNaturalBreaks(6)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
P052004
In HistogramFrame::OnActivate()
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
In HistogramFrame::OnActivate()
MapCanvas::~MapCanvas()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
P052015
Open HistogramFrame.
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
In HistogramFrame::OnActivate()
PNG selected
In GdaFrame::OpenNaturalBreaks(6)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
P052015
In HistogramFrame::OnActivate()
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
In HistogramFrame::OnActivate()
MapCanvas::~MapCanvas()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
P052004
Open BoxPlotCanvas.
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
P052004
Open BoxPlotCanvas.
In GdaFrame::OnOpenHinge15()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
P052004
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
MapCanvas::~MapCanvas()
Close BoxPlotCanvas.
In GdaFrame::OnOpenPercentile()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
P052004
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Close BoxPlotCanvas.
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
P052015
Open BoxPlotCanvas.
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
In GdaFrame::OnOpenHinge15()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
P052015
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
MapCanvas::~MapCanvas()
Close BoxPlotCanvas.
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
P005001
Open BoxPlotCanvas.
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
In GdaFrame::OnOpenHinge15()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
P005001
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
MapCanvas::~MapCanvas()
Close BoxPlotCanvas.
Open LisaScatterPlotFrame (OnOpenMSPL).
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
selected:0
Click CreatingWeightDlg::OnCRadioRookSelected
Click CreatingWeightDlg::OnCRadioQueenSelected
Click CreatingWeightDlg::OnCRadioRookSelected
Click CreatingWeightDlg::OnCRadioQueenSelected
Click CreatingWeightDlg::OnCRadioKnnSelected
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Click CreatingWeightDlg::OnCreateNewIdClick
Try to insert unique id (integer, POLY_ID) column in table.
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
selected:1
Click CreatingWeightDlg::OnCRadioDistanceSelected
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/Users/jahairaysabelbandavasquez/Desktop/Geodata_tarea/California/California_intent1.gwt

**Comment by YidanJ-Wu** [comment]
Steps to replicate: 
Open quantile and natural breaks map views of several variables
Save them as PNG
Open LISA scatter plot
Open weights dialog
Select an existing ID variable
Select K nearest neighbors
create new ID (POLY_ID) and select that as the ID variable
Select Distance
Create weights file California_intent1.gwt

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.191 (macOS Mojave, 10.14.1). Jan. 16 build.

No crash observed using Guerry sample data and external dataset with missings.
