### ISSUE TITLE
Create graph representation of connectedness (on top of map)

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1448]

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.109
verified 

<img width="921" alt="9 mar 16" src="https://user-images.githubusercontent.com/36253697/37237315-8be17bb4-2409-11e8-89b2-53b443e780e3.PNG">

**Comment by jkoschinsky** [comment]
fix confirmed
GeoDa v 111
OSX
