### ISSUE TITLE
Crash: LISA save

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1449]
From: 296777192@qq.com
 Details:
os: 1-10-12
vs: 1-12-1-59
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/lily/Documents/paper/province/province2.shp
Open Layer:province2
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/lily/Documents/paper/province/province2.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
selected:6
Click CreatingWeightDlg::OnCRadioQueenSelected
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/Users/lily/Documents/paper/province/province2_mac2.gal
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
Click CreatingWeightDlg::OnCreateNewIdClick
Try to insert unique id (integer, POLY_ID) column in table.
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/Users/lily/Documents/paper/province/province2_mac3.gal
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
Close CreatingWeightDlg
In WeightsManFrame::OnActivate
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
Entering WeightsManFrame::OnRemoveBtn
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::SetDetailsForItem
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
In WeightsManFrame::OnActivate
Click VariableSettingsDlg::OnOkClick
In WeightsManFrame::OnActivate
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
Entering WeightsManFrame::OnRemoveBtn
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::SetDetailsForItem
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
In WeightsManFrame::OnActivate
Click VariableSettingsDlg::OnOkClick
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In TableFrame::OnActivate
MapCanvas::~MapCanvas()
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs
New Datasource Name:/Users/lily/Documents/paper/province/GdaTmp_province2.shp
Project::GetSpatialReference()
Project::GetGdaGeometries()
In OGRDataAdapter::ExportDataSource()

**Comment by YidanJ-Wu** [comment]
Steps to replicate: 
Open file
Show themeless map and table view
Open weights dialog
Create queen weights with a given variable
Create queen weights with a newly created variable (POLY_ID)
Open Lisa settings window
Save data as different name

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.191 (macOS Mojave, 10.14.1). Jan. 16 build.

Followed the same steps, can't replicate this crash.
Dataset used: Guerry sample and external with missings.
