### ISSUE TITLE
Crash after trying to open a .7z file

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#1452]
Windows 8 
1.12.1.59
Tried to replicate the first step of #1447 by opening a .7z file by drag and drop. Got the usual error message. Then I changed the settings on my computer so that .7z file's default program was GeoDa. Double clicked the .7z file, got a different error message in Geoda. 
![image](https://user-images.githubusercontent.com/22801047/34596266-ede70344-f1a3-11e7-90bd-317270043239.png)
Waited a few minutes (did not do anything), then crash.

**Comment by lixun910** [comment]
This is a very unusual case: we are not expecting user to setup GeoDa to be the default program opening .7z file.

We can keep #1447, and with new weights creation design, this should be re-tested.

Thanks!

**Comment by jkoschinsky** [comment]
People who are used to programs like Carto where you drag and drop zip files in the open data field might be trying this. Can we update the error message in that case to something like:

GeoDa does not read compressed files. Please uncompress your data before loading it.

**Comment by lixun910** [comment]
We do have a warning dialog when people drag-n-drop zip file in GeoDa.

What Julie mentioned is binding the .7z file with GeoDa using Windows system setting, which is abnormal.
