### ISSUE TITLE
Weights manager dialog sometimes unresponsive

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#1453]
Windows 8 
1.12.1.59
The 'create' button turns blue but does not bring up dialog to create a new weights file
![image](https://user-images.githubusercontent.com/22801047/34621672-abb73874-f20f-11e7-9b3e-3c941e50cc5d.png)
Load and Remove buttons still work. 
This has only happened after creating weights files in the same session.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.109

Did not meet this problem in recent visions.

**Comment by jkoschinsky** [comment]
fix confirmed
GeoDa v 111
OSX
