### ISSUE TITLE
Crash: Test k-means and REDCAP

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1454]
From: 
 Details:
os: 1-10-13
vs: 1-12-1-59
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/haifeng/Desktop/Shapfile_jan 5/Jan_5_variables.shp
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
selected:2
Click CreatingWeightDlg::OnCRadioDistanceSelected
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/Users/haifeng/Desktop/Shapfile_jan 5/Jan_5_variables.gwt
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
Close CreatingWeightDlg
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Open AbstractClusterDlg.
Open HClusterDlg.
Click HClusterDlg::OnOK
Click HClusterDlg::OnOK
Close HClusterDlg
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
ent_gen
cclass
Open CartogramNewFrame.
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Project::GetVoronoiRookNeighborGal()
Project::GetVoronoiRookNeighborMap()
Project::IsPointDuplicates()
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
In CartogramNewFrame::OnActivate()
Open AbstractClusterDlg.
Open KMeanDlg.
Click KMeansDlg::OnOK
Click KMeansDlg::OnOK
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Open AbstractClusterDlg.
Open REDCAP dialog.
On RedcapDlg::Init
On RedcapDlg::CreateControls
On RedcapDlg::InitVariableCombobox
Click RedcapDlg::OnOK

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.85
Ran on a couple of smaller files with no issues. I ran spectral clustering on the homicides map and got only 1 cluster. Not sure if that's because of the data properties or something in the clustering algorithm
![image](https://user-images.githubusercontent.com/22801047/35602570-93d63b30-05fe-11e8-9c44-e8eff361ae00.png)
![image](https://user-images.githubusercontent.com/22801047/35602580-9d56c59e-05fe-11e8-98e0-355362db826c.png)

**Comment by YidanJ-Wu** [comment]
Windows 8 
GeoDa 1.12.1.85
Redcap also gets stuck in islands. I think this issue was reported in a prior version as well. 
![image](https://user-images.githubusercontent.com/22801047/35602866-2129e6d4-0600-11e8-93ec-f1102213760b.png)
![image](https://user-images.githubusercontent.com/22801047/35602878-30e3c770-0600-11e8-84df-43e6fb2d1b2c.png)

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.143

No apparent issues with kmeans while using datasets with large amount of observations.
<img width="597" alt="screen shot 2018-07-23 at 2 43 15 pm" src="https://user-images.githubusercontent.com/37029239/43099183-ed937cbc-8e86-11e8-82c6-83a33b569ccf.png">
<img width="864" alt="screen shot 2018-07-23 at 2 43 05 pm" src="https://user-images.githubusercontent.com/37029239/43099184-ed9ecb58-8e86-11e8-99d6-f7d336e67d24.png">

redcap also had no apparent issues with the large dataset
<img width="594" alt="screen shot 2018-07-23 at 2 46 57 pm" src="https://user-images.githubusercontent.com/37029239/43099278-4b563de4-8e87-11e8-86c0-d0a59631ed8d.png">
<img width="811" alt="screen shot 2018-07-23 at 2 46 49 pm" src="https://user-images.githubusercontent.com/37029239/43099279-4b649a42-8e87-11e8-91df-1ab34597ec01.png">

Had similar issues with redcap giving me an error with islands. Did the same clustering analysis for kmeans and it worked fine, but when looking at redcap, the below error was displayed.
<img width="803" alt="screen shot 2018-07-23 at 2 54 26 pm" src="https://user-images.githubusercontent.com/37029239/43099666-7ead66ee-8e88-11e8-9481-751fd16fcfed.png">
