### ISSUE TITLE
Crash: Test regression

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1456]
From: 
 Details:
os: 1-10-11
vs: 1-10-0-12
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/eLena/Desktop/LOG PIB TUR 03.12.17.xlsx
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
In TableFrame::OnActivate
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/eLena/Desktop/estados/estados.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PIBG1214
VariableSettingsDlg::GetWeightsId() weight: TURISMOGAL
VariableSettingsDlg::GetWeightsId() weight: TURISMOGAL
Click GdaFrame::OnCopyImageToClipboard
Click GdaFrame::OnCopyImageToClipboard
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PIBHR1214
VariableSettingsDlg::GetWeightsId() weight: TURISMOGAL
VariableSettingsDlg::GetWeightsId() weight: TURISMOGAL
Click GdaFrame::OnCopyImageToClipboard
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PIBACD1214
VariableSettingsDlg::GetWeightsId() weight: TURISMOGAL
VariableSettingsDlg::GetWeightsId() weight: TURISMOGAL
Click GdaFrame::OnCopyImageToClipboard
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
FLUA1214
VariableSettingsDlg::GetWeightsId() weight: TURISMOGAL
VariableSettingsDlg::GetWeightsId() weight: TURISMOGAL
Click GdaFrame::OnCopyImageToClipboard
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PIM01214
VariableSettingsDlg::GetWeightsId() weight: TURISMOGAL
VariableSettingsDlg::GetWeightsId() weight: TURISMOGAL
Click GdaFrame::OnCopyImageToClipboard
In OnRan999Per()
Open RandomizationDlg (univariate).
Close RandomizationDlg
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
ID1214
VariableSettingsDlg::GetWeightsId() weight: TURISMOGAL
VariableSettingsDlg::GetWeightsId() weight: TURISMOGAL
Click GdaFrame::OnCopyImageToClipboard
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PSEG1114
VariableSettingsDlg::GetWeightsId() weight: TURISMOGAL
VariableSettingsDlg::GetWeightsId() weight: TURISMOGAL
Click GdaFrame::OnCopyImageToClipboard
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PSEG1114
VariableSettingsDlg::GetWeightsId() weight: TURISMOGAL
VariableSettingsDlg::GetWeightsId() weight: TURISMOGAL
Entering GdaFrame::OnMapChoices
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PIBG1214
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnCopyImageToClipboard
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
Click GdaFrame::OnCopyImageToClipboard
MapCanvas::~MapCanvas()
Open ScatterPlotMatFrame.
In ScatterPlotMatFrame::OnActivate
In ScatterPlotMatFrame::OnActivate
In ScatterPlotMatFrame::OnActivate
In ScatterPlotMatFrame::OnActivate
Open ExportDataDlg in its Init()
In ScatterPlotMatFrame::OnActivate
Open RegressionDlg.
RegressionDlg::InitVariableList()
RegressionDlg::OnCButton1Click()
RegressionDlg::OnCButton5Click()
RegressionDlg::OnCButton5Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnRunClick
y:PIBG1214
x:
PIBHR1214
PIBACD1214
FLUA1214
PIM01214
ID1214
PSEG1114
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
RegressionDlg::~RegressionDlg()
Close RegressionDlg.
Open RegressionDlg.
RegressionDlg::InitVariableList()
RegressionDlg::OnCButton1Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnRunClick
y:PIBACD1214
x:
PIBHR1214
PIBG1214
PIM01214
PSEG1114
FLUA1214
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnClose()
Close RegressionDlg.
RegressionDlg::OnCButton3Click()
RegressionDlg::OnCButton3Click()
RegressionDlg::OnCButton3Click()
RegressionDlg::OnCButton3Click()
RegressionDlg::OnCButton3Click()
RegressionDlg::OnCButton3Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::~RegressionDlg()
Open RegressionDlg.
RegressionDlg::InitVariableList()
RegressionDlg::OnCButton1Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnRunClick
y:PIBG1214
x:
PIBHR1214
PIBACD1214
FLUA1214
PIM01214
PSEG1114
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnSaveToFile()
Open RegressionDlg.
RegressionDlg::InitVariableList()
RegressionDlg::OnCButton1Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnCWeightCheckClick
Click RegressionDlg::OnCRadio2Selected
Click RegressionDlg::OnRunClick
y:PIBG1214
x:
PIBHR1214
PIBACD1214
FLUA1214
PIM01214
ID1214
PSEG1114
Spatial Lag model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnSaveToFile()
In RegressionReportDlg::OnClose()
Close RegressionDlg.
Click RegressionDlg::OnCRadio3Selected
Click RegressionDlg::OnRunClick
y:PIBG1214
x:
PIBHR1214
PIBACD1214
FLUA1214
PIM01214
ID1214
PSEG1114
Spatial Error model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnSaveToFile()
Click RegressionDlg::OnCRadio1Selected
Click RegressionDlg::OnRunClick
y:PIBG1214
x:
PIBHR1214
PIBACD1214
FLUA1214
PIM01214
ID1214
PSEG1114
OLS model
RegressionDlg::DisplayRegression()
In RegressionReportDlg::OnSaveToFile()
In RegressionReportDlg::OnClose()
Close RegressionDlg.
Entering GdaFrame::OnMapChoices
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
ID1214
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PIBHR0305
Open HistogramFrame.
In HistogramFrame::OnActivate()
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PIBHR0305
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PIBG0305
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
MapCanvas::~MapCanvas()
In TableFrame::OnActivate
Entering GdaFrame::OnMapChoices
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PIBG0608
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
MapCanvas::~MapCanvas()
Entering GdaFrame::OnMapChoices
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PIBG0911
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
MapCanvas::~MapCanvas()
Entering GdaFrame::OnMapChoices
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
ID0305
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
In GdaFrame::OnOpenHinge15()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
ID0305
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Open Themeless Map (OnOpenThemelessMap).
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnCanvasBackgroundColor
MapCanvas::~MapCanvas()
In GdaFrame::OpenNaturalBreaks(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
ID0305
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Open DataMovieDlg.
Entering DataMovieDlg::OnFieldChoice
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
Entering DataMovieDlg::OnFieldChoice
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepForwardButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
Entering DataMovieDlg::OnFieldChoice
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnStepBackButton
DataMovieDlg::OnPlayPauseButton
DataMovieDlg::OnPlayPauseButton
Entering DataMovieDlg::OnFieldChoice
DataMovieDlg::OnPlayPauseButton
Entering DataMovieDlg::OnFieldChoice
DataMovieDlg::OnPlayPauseButton
DataMovieDlg::OnPlayPauseButton
Close DataMovieDlg::OnClose
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
ID0305
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
MapCanvas::~MapCanvas()
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
ID0608
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
MapCanvas::~MapCanvas()
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
ID0911
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnLegendUseScientificNotation
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
Open RegressionDlg.
RegressionDlg::InitVariableList()
RegressionDlg::OnCButton1Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnRunClick
y:PIBG0305
x:
PIBHR0305
PIBACD0305
FLUA0305
ID0305
PSEG0305
PIM0305
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnSaveToFile()
In RegressionReportDlg::OnClose()
Close RegressionDlg.
Click RegressionDlg::OnCWeightCheckClick
Click RegressionDlg::OnCRadio2Selected
Click RegressionDlg::OnRunClick
y:PIBG0305
x:
PIBHR0305
PIBACD0305
FLUA0305
ID0305
PSEG0305
PIM0305
Spatial Lag model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnSaveToFile()
In RegressionReportDlg::OnClose()
Close RegressionDlg.
Click RegressionDlg::OnCRadio3Selected
Click RegressionDlg::OnRunClick
y:PIBG0305
x:
PIBHR0305
PIBACD0305
FLUA0305
ID0305
PSEG0305
PIM0305
Spatial Error model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnClose()
Close RegressionDlg.
Click RegressionDlg::OnCRadio1Selected
Click RegressionDlg::OnRunClick
y:PIBG0305
x:
PIBHR0305
PIBACD0305
FLUA0305
ID0305
PSEG0305
PIM0305
OLS model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnClose()
Close RegressionDlg.
Click RegressionDlg::OnCResetClick
RegressionDlg::InitVariableList()
RegressionDlg::OnCListVarinDoubleClicked()
RegressionDlg::OnCButton1Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnCResetClick
RegressionDlg::InitVariableList()
RegressionDlg::OnCButton1Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnRunClick
y:PIBG0608
x:
PIBHR0608
PIBACD0608
FLUA0608
PIM0608
ID0608
PSEG0609
OLS model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnSaveToFile()
In RegressionReportDlg::OnClose()
Close RegressionDlg.
Click RegressionDlg::OnCRadio2Selected
Click RegressionDlg::OnRunClick
y:PIBG0608
x:
PIBHR0608
PIBACD0608
FLUA0608
PIM0608
ID0608
PSEG0609
Spatial Lag model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnSaveToFile()
In RegressionReportDlg::OnClose()
Close RegressionDlg.
Click RegressionDlg::OnCRadio3Selected
Click RegressionDlg::OnRunClick
y:PIBG0608
x:
PIBHR0608
PIBACD0608
FLUA0608
PIM0608
ID0608
PSEG0609
Spatial Error model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnSaveToFile()
In RegressionReportDlg::OnClose()
Close RegressionDlg.
Click RegressionDlg::OnCRadio1Selected
Click RegressionDlg::OnRunClick
y:PIBG0608
x:
PIBHR0608
PIBACD0608
FLUA0608
PIM0608
ID0608
PSEG0609
OLS model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnClose()
Close RegressionDlg.
Click RegressionDlg::OnCResetClick
RegressionDlg::InitVariableList()
RegressionDlg::OnCButton1Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnRunClick
y:PIBG0911
x:
PIBHR0911
PIBACD0911
FLUA0911
PIM0911
ID0911
PSEG1012
OLS model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnSaveToFile()
Click RegressionDlg::OnCRadio2Selected
Click RegressionDlg::OnCRadio1Selected
Click RegressionDlg::OnRunClick
y:PIBG0911
x:
PIBHR0911
PIBACD0911
FLUA0911
PIM0911
ID0911
PSEG1012
OLS model
RegressionDlg::DisplayRegression()
Click RegressionDlg::OnRunClick
y:PIBG0911
x:
PIBHR0911
PIBACD0911
FLUA0911
PIM0911
ID0911
PSEG1012
OLS model
RegressionDlg::DisplayRegression()
Click RegressionDlg::OnCRadio2Selected
Click RegressionDlg::OnRunClick
y:PIBG0911
x:
PIBHR0911
PIBACD0911
FLUA0911
PIM0911
ID0911
PSEG1012
Spatial Lag model
RegressionDlg::DisplayRegression()
In RegressionReportDlg::OnSaveToFile()
In RegressionReportDlg::OnClose()
Close RegressionDlg.
Click RegressionDlg::OnCRadio3Selected
Click RegressionDlg::OnRunClick
y:PIBG0911
x:
PIBHR0911
PIBACD0911
FLUA0911
PIM0911
ID0911
PSEG1012
Spatial Error model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnClose()
Close RegressionDlg.
Click RegressionDlg::OnRunClick
y:PIBG0911
x:
PIBHR0911
PIBACD0911
FLUA0911
PIM0911
ID0911
PSEG1012
Spatial Error model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnSaveToFile()
In RegressionReportDlg::OnClose()
Close RegressionDlg.
Click RegressionDlg::OnCRadio1Selected
Click RegressionDlg::OnRunClick
y:PIBG0911
x:
PIBHR0911
PIBACD0911
FLUA0911
PIM0911
ID0911
PSEG1012
OLS model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnClose()
Close RegressionDlg.
RegressionDlg::~RegressionDlg()
Click GdaFrame::OnClose
Project::GetProjectFullPath()
Project::HasUnsavedChange()
Click GdaFrame::OnClose
Project::GetProjectFullPath()
Project::HasUnsavedChange()

**Comment by jkoschinsky** [comment]
several other crashes related to regression, so something isn't right

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.14.1

Have had several errors but no clear pattern as it is not dependent on the variables used. Will continue to look into it.
<img width="416" alt="screen shot 2018-07-26 at 6 12 29 pm" src="https://user-images.githubusercontent.com/37029239/43293378-9b4b45fe-90ff-11e8-8fb8-bf85e926e98c.png">

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.143
Determined a path that creates crash every time.

Open GeoDa
Tools > Weights Manager
Load/Create Spatial Weights
Regression > Regression
Choose Dependent Variable
Choose Covariate(s)
Check "weights file" box
Choose Spatial Weight
Click "Spatial Error" bubble
Click "Pred. Val. and Res." box
Run
Go back into Regression dialogue
uncheck weights file
Run
GeoDa crashes

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.151
Verified

Above path works with no crash as in GeoDa version 1.12.1.143
