### ISSUE TITLE
Crash: Testing pending author response

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1459]
From: joseph@redfern.me
 Details:
os: 3-4-14
vs: 1-12-1-57
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()

**Comment by lixun910** [comment]
This is a crash from linux os. Information is not enough to identify issue/bugs. Need to be verified.

**Comment by jkoschinsky** [comment]
contacted user

**Comment by lixun910** [comment]
Information is not enough to identify issue/bugs.
