### ISSUE TITLE
Crash: Testing pending author response

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1461]
From: vagvaf@gmail.com
 Details:
os: 3-4-4
vs: 1-12-1-57
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/vagvaf/Dropbox/LundGIS/4th_Semester/data/origins.shp
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
hospitalac
VariableSettingsDlg::GetWeightsId() weight: origins_distance
VariableSettingsDlg::GetWeightsId() weight: origins_distance
Entering LisaCoordinator::LisaCoordinator().
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
Entering LisaCoordinator::InitFromVarInfo()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Entering LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::CalcLisa()
Entering LisaCoordinator::CalcPseudoP()
Entering LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP()
Exiting LisaCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
In LisaCoordinator::registerObserver()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Open ExportDataDlg in its Init()
In ExportDataDlg::BrowseExportDataSource()
In ExportDataDlg::OnOkClick()
ds:/home/vagvaf/Dropbox/LundGIS/4th_Semester/data/origins_geoda_hospitals.shp
Project::GetSpatialReference()
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
id
ScrolledWidgetsPane::IsFieldNameValid
lat
ScrolledWidgetsPane::IsFieldNameValid
lon
ScrolledWidgetsPane::IsFieldNameValid
geom
ScrolledWidgetsPane::IsFieldNameValid
busstops
ScrolledWidgetsPane::IsFieldNameValid
railstops
ScrolledWidgetsPane::IsFieldNameValid
buslines
ScrolledWidgetsPane::IsFieldNameValid
railines
ScrolledWidgetsPane::IsFieldNameValid
avg_income
ScrolledWidgetsPane::IsFieldNameValid
cbd_dist
ScrolledWidgetsPane::IsFieldNameValid
density
ScrolledWidgetsPane::IsFieldNameValid
hospitalac
ScrolledWidgetsPane::IsFieldNameValid
retailacce
In FieldNameCorrectionDlg
Out FieldNameCorrectionDlg
start OGRLayerProxy::AddFreatures()
Out OGRDataAdapter::ExportDataSource()
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
hospitalac
VariableSettingsDlg::GetWeightsId() weight: origins_distance
VariableSettingsDlg::GetWeightsId() weight: origins_distance
Entering LisaCoordinator::LisaCoordinator().
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
Entering LisaCoordinator::InitFromVarInfo()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Entering LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::CalcLisa()
Entering LisaCoordinator::CalcPseudoP()
Entering LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP()
Exiting LisaCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
In LisaCoordinator::registerObserver()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::removeObserver
Exiting LisaCoordinator::removeObserver
MapCanvas::~MapCanvas()
Entering LisaCoordinator::removeObserver
Exiting LisaCoordinator::removeObserver
Entering LisaCoordinator::removeObserver
In LisaCoordinator::~LisaCoordinator().
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::removeObserver
MapCanvas::~MapCanvas()
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
Click GdaFrame::OnSaveProject
Entering Project::SaveDataSourceData
Exiting Project::SaveDataSourceData
Entering Project::SaveProjectConf
Project::GetProjectFullPath()
In Project::UpdateProjectConf
Exiting Project::SaveProjectConf
Open ExportDataDlg in its Init()
In ExportDataDlg::BrowseExportDataSource()
In ExportDataDlg::OnOkClick()
ds:/home/vagvaf/Dropbox/LundGIS/4th_Semester/data/origins_geoda_hospitals.shp
Project::GetSpatialReference()
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
id
ScrolledWidgetsPane::IsFieldNameValid
lat
ScrolledWidgetsPane::IsFieldNameValid
lon
ScrolledWidgetsPane::IsFieldNameValid
geom
ScrolledWidgetsPane::IsFieldNameValid
busstops
ScrolledWidgetsPane::IsFieldNameValid
railstops
ScrolledWidgetsPane::IsFieldNameValid
buslines
ScrolledWidgetsPane::IsFieldNameValid
railines
ScrolledWidgetsPane::IsFieldNameValid
avg_income
ScrolledWidgetsPane::IsFieldNameValid
cbd_dist
ScrolledWidgetsPane::IsFieldNameValid
density
ScrolledWidgetsPane::IsFieldNameValid
hospitalac
ScrolledWidgetsPane::IsFieldNameValid
retailacce
In FieldNameCorrectionDlg
Out FieldNameCorrectionDlg
start OGRLayerProxy::AddFreatures()
Out OGRDataAdapter::ExportDataSource()
Click GdaFrame::OnSaveAsProject
Project::GetProjectFullPath()
Entering GdaFrame::OnMapChoices
In GdaFrame::OnOpenStddev()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
hospitalac
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
hospitalac
density
Open ScatterNewPlotFrame.
Open Themeless Map (OnOpenThemelessMap).
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
hospitalac
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Open ExportDataDlg in its Init()
In ExportDataDlg::BrowseExportDataSource()
In ExportDataDlg::OnOkClick()
ds:/home/vagvaf/Dropbox/LundGIS/4th_Semester/data/origins_geoda_hospitals.shp
Project::GetSpatialReference()
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
id
ScrolledWidgetsPane::IsFieldNameValid
lat
ScrolledWidgetsPane::IsFieldNameValid
lon
ScrolledWidgetsPane::IsFieldNameValid
geom
ScrolledWidgetsPane::IsFieldNameValid
busstops
ScrolledWidgetsPane::IsFieldNameValid
railstops
ScrolledWidgetsPane::IsFieldNameValid
buslines
ScrolledWidgetsPane::IsFieldNameValid
railines
ScrolledWidgetsPane::IsFieldNameValid
avg_income
ScrolledWidgetsPane::IsFieldNameValid
cbd_dist
ScrolledWidgetsPane::IsFieldNameValid
density
ScrolledWidgetsPane::IsFieldNameValid
hospitalac
ScrolledWidgetsPane::IsFieldNameValid
retailacce
In FieldNameCorrectionDlg
Out FieldNameCorrectionDlg
start OGRLayerProxy::AddFreatures()
Out OGRDataAdapter::ExportDataSource()
In ExportDataDlg::OnOkClick()
ds:/home/vagvaf/Dropbox/LundGIS/4th_Semester/data/origins_geoda_hospitals.shp
Project::GetSpatialReference()
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
id
ScrolledWidgetsPane::IsFieldNameValid
lat
ScrolledWidgetsPane::IsFieldNameValid
lon
ScrolledWidgetsPane::IsFieldNameValid
geom
ScrolledWidgetsPane::IsFieldNameValid
busstops
ScrolledWidgetsPane::IsFieldNameValid
railstops
ScrolledWidgetsPane::IsFieldNameValid
buslines
ScrolledWidgetsPane::IsFieldNameValid
railines
ScrolledWidgetsPane::IsFieldNameValid
avg_income
ScrolledWidgetsPane::IsFieldNameValid
cbd_dist
ScrolledWidgetsPane::IsFieldNameValid
density
ScrolledWidgetsPane::IsFieldNameValid
hospitalac
ScrolledWidgetsPane::IsFieldNameValid
retailacce
In FieldNameCorrectionDlg
Out FieldNameCorrectionDlg
start OGRLayerProxy::AddFreatures()
Out OGRDataAdapter::ExportDataSource()

**Comment by jkoschinsky** [comment]
contacted author

**Comment by lixun910** [comment]
merge table and field name correction dialog
same as #1694 and #1798
