### ISSUE TITLE
weights file creation dialog - typo

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1468]
Apply kernel on diagnal weights, should be "Apply kernel to diagonal (not on diagnal) weights"

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.109
Verified 

<img width="359" alt="9 mar 12" src="https://user-images.githubusercontent.com/36253697/37236239-a66d91c2-23fd-11e8-862c-bced1bc53756.PNG">

**Comment by jkoschinsky** [comment]
fix confirmed
GeoDa v 111
OSX
