### ISSUE TITLE
Crash: Check Grid Creation (Tools-Shape-Create Grid)

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1469]
From: 
 Details:
os: 1-10-12
vs: 1-12-1-59
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
ConnectDatasourceDlg::OnSample()
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Applications/GeoDa.app/Contents/MacOS/../Resources/samples.sqlite
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnRegressionClassic()
Open RegressionDlg.
RegressionDlg::InitVariableList()
MapCanvas::~MapCanvas()
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
RegressionDlg::~RegressionDlg()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
Open CsvFieldConfDlg.
CsvFieldConfDlg::PrereadCSV()
CsvFieldConfDlg::UpdateFieldGrid()
CsvFieldConfDlg::ReadCSVT()
CsvFieldConfDlg::UpdatePreviewGrid()
CsvFieldConfDlg::UpdateXYcombox()
CsvFieldConfDlg::OnOkClick()
CsvFieldConfDlg::WriteCSVT()
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/cutgana/Desktop/rischio_spatial.csv
Open Layer:rischio_spatial
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/cutgana/Desktop/rischio_spatial.csv
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
In TableFrame::OnActivate
Open LisaScatterPlotFrame (OnOpenMSPL).
Open CreateGridDlg
In CreateGridDlg::OnCEdit1Updated()
0.0
In CreateGridDlg::OnCEdit2Updated()
0.0
In CreateGridDlg::OnCEdit3Updated()
0.0
In CreateGridDlg::OnCEdit4Updated()
0.0
In CreateGridDlg::OnCreateClick()
In CreateGridDlg::OnCRadio3Selected()
In CreateGridDlg::OnCRadio1Selected()
In CreateGridDlg::OnCancelClick()
Open CreateGridDlg
In CreateGridDlg::OnCEdit1Updated()
0.0
In CreateGridDlg::OnCEdit2Updated()
0.0
In CreateGridDlg::OnCEdit3Updated()
0.0
In CreateGridDlg::OnCEdit4Updated()
0.0
In CreateGridDlg::OnCEdit1Updated()
4
In CreateGridDlg::OnCEdit1Updated()
45
In CreateGridDlg::OnCEdit2Updated()
.0
In CreateGridDlg::OnCEdit2Updated()
4.0
In CreateGridDlg::OnCEdit2Updated()
47.0
In CreateGridDlg::OnCEdit2Updated()
4.0
In CreateGridDlg::OnCEdit2Updated()
46.0
In CreateGridDlg::OnCEdit2Updated()
46.50
In CreateGridDlg::OnCEdit3Updated()
9.0
In CreateGridDlg::OnCEdit4Updated()
.0
In CreateGridDlg::OnCEdit4Updated()
1.0
In CreateGridDlg::OnCEdit4Updated()
12.0
In CreateGridDlg::OnCreateClick()
In CreateGridDlg::OnCEdit1Updated()
9
In CreateGridDlg::OnCEdit2Updated()
1
In CreateGridDlg::OnCEdit2Updated()
12
In CreateGridDlg::OnCEdit3Updated()
4.0
In CreateGridDlg::OnCEdit3Updated()
45.0
In CreateGridDlg::OnCEdit4Updated()
4.0
In CreateGridDlg::OnCEdit4Updated()
46.0
In CreateGridDlg::OnCEdit4Updated()
46.50
In CreateGridDlg::OnCreateClick()
Open ExportDataDlg in its Init()
In ExportDataDlg::OnOkClick()

**Comment by YidanJ-Wu** [comment]
Windows 8 
1.12.1.85
I made one grid, 2 columns 2 rows without issues.
![image](https://user-images.githubusercontent.com/22801047/35601496-06eae77a-05f9-11e8-853c-704f8ab4942d.png)
Then, without closing this, I created a new grid with the bounding box of Columbus Crimes, 3 columns 3 rows, and saved as grid2.shp. I closed the 2x2 view shown above, attempted to open grid2.shp and got a crash.

**Comment by lixun910** [comment]
(wont fix) This is normal, if one specifies the bounding box of the grid around 0,0. If one wants to add a basemap layer, they should specify the proper X,Y or (Lat,Lon) when create a grid.

<img width="448" alt="screen shot 2018-01-31 at 11 19 06 am" src="https://user-images.githubusercontent.com/2423887/35639784-93ce6d0e-0678-11e8-96a4-2bd29633f98f.png">

**Comment by lixun910** [comment]
Update: the crash will be fixed soon

**Comment by lixun910** [comment]
Please test again, since I can't replicate this on Windows in latest GeoDa 1.12.1.87. Thanks1

**Comment by YidanJ-Wu** [comment]
Windows 8 
1.12.1.87 
I replicated the steps used above for 85 and got a crash when attempting to open the second grid.

**Comment by YidanJ-Wu** [comment]
Windows 8
1.12.1.87
Replicated the steps used above for 85. This time, no crash when attempting to open the second grid.
