### ISSUE TITLE
weights manager needs connectivity graph button

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1471]
As discussed, the connectivity graph should be available from the weights manager as well.

Note, change from weights graph to connectivity graph (since it is actually portrayed as an
unweighted graph)

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.109
Verified 

<img width="275" alt="9 mar 11" src="https://user-images.githubusercontent.com/36253697/37236182-221d3d96-23fd-11e8-98a6-b929e1feeb97.PNG">

**Comment by jkoschinsky** [comment]
fix confirmed
GeoDa v 111
OSX

**Comment by cynthiaho711** [comment]
![screen shot 2018-08-20 at 16 03 00](https://user-images.githubusercontent.com/10076081/44345071-8cd8d080-a492-11e8-817b-aa257cb6ba42.png)

**Comment by cynthiaho711** [comment]
hi, I am missing the button "Connectivity graph"on my weights manager. I am using MacOS.

**Comment by cynthiaho711** [comment]
yes! It is Geoda 1.12.0 1 October 2017

**Comment by jkoschinsky** [comment]
if you can share the spatial file (pls email to spatial@uchicago.edu),
we'll take a look

**Comment by lixun910** [comment]
GeoDa 1.12 1 October 2017 is not the latest version, and it doesn’t have
feature “connectivity graph”. Please use the latest GeoDa 1.12.1.139 from
geodacenter.github.io

Thanks!

**Comment by cynthiaho711** [comment]
On a sidenote, when I check for updates on my current version of Geoda, it says that "No update is required", so I was mistaken that mine is the latest version!

Thanks anyway!:)
