### ISSUE TITLE
unstable behavior of the weights (connectivity) graph

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1472]
Version 1.12.1.81

The connectivity graph drawing does not work well with selected observations.

- when a single observation is selected, the map only shows that observation and the centroids
   of all the polygons:
   - the selected observation and its neighbors should be shown
   - the centroids should not be shown

<img width="1055" alt="screen shot 2018-01-22 at 8 48 22 am" src="https://user-images.githubusercontent.com/4008351/35226717-ce95aade-ff51-11e7-90f3-4421cbc1f1a5.png">

- when a group of observations is selected (e.g., rectangle selection), the map only shows the
  neighbor structure among the selected observations and the centroids of all the polygons:
  - all the neighbors of the selected observations should be shown
  - the centroids should not be shown

<img width="1065" alt="screen shot 2018-01-22 at 8 48 39 am" src="https://user-images.githubusercontent.com/4008351/35226859-272c6cb4-ff52-11e7-9a02-5fd076df32ff.png">

- also, the line thickness of the graph structure is too strong; ideally this should be an adjustable
  quantity

**Comment by lanselin** [comment]
illustration of line thickness issue

<img width="591" alt="screen shot 2018-01-22 at 9 01 18 am" src="https://user-images.githubusercontent.com/4008351/35227154-e8dd7af6-ff52-11e7-8dc2-069a0e5bf921.png">

**Comment by lanselin** [comment]
display weights (connectivity) graph in map menu needs a check box. as it stands, clicking on that item brings up the connectivity graph, and clicking on it again removes it. to be consistent with other interfaces, this should have a check box, off by default.

**Comment by lixun910** [comment]
add option to hide map when display connectivity graph

**Comment by lixun910** [comment]
Add neighbor selection (connectivity map) and connectivity graph in all cluster maps (LISA, LocalG, LocalGeary, LocalJoinCount)

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.109
Verified functions in maps, connectivity maps, and cluster maps: Shown selection and neighbors; connectivity graph; change the thickness of connectivity lines; hide map. 

![img_0460](https://user-images.githubusercontent.com/36253697/37236932-f8d08242-2404-11e8-870a-5eab72755622.JPG)


The centroids will be shown if “Display Centroids” in “Shape Centers” is chosen, and will not disappear with selections. 
<img width="855" alt="9 mar 14" src="https://user-images.githubusercontent.com/36253697/37236964-698dda7a-2405-11e8-89f6-9113324d1a69.PNG">

**Comment by jkoschinsky** [comment]
fix confirmed
GeoDa v 111
OSX
