### ISSUE TITLE
Crash: connectivity graph with neighbor and selection

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1473]
From: lanselin@gmail.com
 Details:
os: 1-10-13
vs: 1-12-1-81
/Users/luc/Desktop/GeoDa.1.12.1.81.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/luc/Desktop/geodatest/natregimes/natregimes.shp
Open Layer:natregimes
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/luc/Desktop/geodatest/natregimes/natregimes.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
Click CreatingWeightDlg::OnCInverseThresholdTextEdit:
In WeightsManFrame::OnActivate
Close CreatingWeightDlg
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
MapCanvas::~MapCanvas()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/luc/Desktop/geodatest/4_weights/natregimes/natregimes.shp
Open Layer:natregimes
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/luc/Desktop/geodatest/4_weights/natregimes/natregimes.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
Click CreatingWeightDlg::OnCInverseThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
selected:8
Click CreatingWeightDlg::OnCRadioRookSelected
Click CreatingWeightDlg::OnCreateClick
In WeightsManFrame::OnActivate
CreateWeights()/Users/luc/Desktop/geodatest/4_weights/natregimes/natregimes_r.gal
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
WeightsManFrame::OnHistogramBtn()
Open ConnectivityHistFrame
In WeightsManFrame::OnActivate
ConnectivityHistFrame::OnActivate
ConnectivityHistFrame::OnActivate
In GdaFrame::OnDisplayStatistics()
In ConnectivityHistFrame::OnDisplayStatistics
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
ConnectivityHistFrame::OnActivate
In WeightsManFrame::OnActivate
WeightsManFrame::OnConnectMapBtn()
Open ConnectivityMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In WeightsManFrame::OnActivate
In ConnectivityMapFrame::OnActivate
In ConnectivityMapFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
WeightsManFrame::OnConnectMapBtn()
In WeightsManFrame::OnActivate
In ConnectivityMapFrame::OnActivate
In GdaFrame::OnAddCentroids()
In Project::AddCentroids
Project::GetCentroids()
In GdaFrame::OnAddNeighborToSelection()
In GdaFrame::OnAddNeighborToSelection()
In GdaFrame::OnDisplayWeightsGraph()
MapCanvas::DisplayWeightsGraph()
Project::GetMeanCenters()
Entering GdaFrame::OnMapChoices
In GdaFrame::OnOpenHinge15()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
hr60
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnDisplayWeightsGraph()
MapCanvas::DisplayWeightsGraph()
Project::GetMeanCenters()
In GdaFrame::OnAddNeighborToSelection()
In GdaFrame::OnDisplayWeightsGraph()
MapCanvas::DisplayWeightsGraph()
In GdaFrame::OnDisplayWeightsGraph()
MapCanvas::DisplayWeightsGraph()
Project::GetMeanCenters()
In GdaFrame::OnDisplayWeightsGraph()
MapCanvas::DisplayWeightsGraph()
In GdaFrame::OnAddNeighborToSelection()

**Comment by lanselin** [comment]
GeoDa crashed after turning connectivity graph on and off and then choosing neighbor and selection

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.157

No crash when turning connectivity graph on and off then choosing neighbor and selection

<img width="708" alt="screen shot 2018-07-02 at 3 05 30 pm" src="https://user-images.githubusercontent.com/37029239/42184066-bbec34fc-7e09-11e8-9920-7d67408f6c5f.png">
