### ISSUE TITLE
map - selection and neighbors logic

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1474]
(v 81)
as it stands, the logic of this item in the map menu/interface is a bit inconsistent. it only works with a selection already made (if there is no current selection, nothing happens). also, it does not differentiate between the actual selection and its neighbors.

so, i suggest, just like for the connectivity graph, to turn this into a check box (off by default):
- with the check box on, any selection (also dynamic) would also include the neighbors, and
  ideally differentiate between the selection and the neighbors

the main difference with the current implementation would be that when you click on selection and neighbors (without a current selection) and then select and observations, something would actually happen -- right now nothing happens, since there was no "current selection" when the neighbors item was activated.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.111
Verified 
![12 mar 01](https://user-images.githubusercontent.com/36253697/37305267-d0b16046-262b-11e8-869a-0a05237c4c28.JPG)
<img width="784" alt="12 mar 01" src="https://user-images.githubusercontent.com/36253697/37305276-d61a3008-262b-11e8-8ef3-5414153bfa1d.PNG">

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v111
OSX
