### ISSUE TITLE
weights file creation - distance band not initialized properly

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1475]
V 81

When clicking on Threshold distance or Inverse distance, the initial value in the box is 0, whereas when selecting Adaptive Kernel, the value in "specify bandwidth" is initialized to the maxmin distance. This is inconsistent.

<img width="527" alt="screen shot 2018-01-22 at 12 58 01 pm" src="https://user-images.githubusercontent.com/4008351/35248563-403adf5a-ff94-11e7-8c23-b738217b9e48.png">

<img width="430" alt="screen shot 2018-01-22 at 12 58 36 pm" src="https://user-images.githubusercontent.com/4008351/35248596-5bb5576a-ff94-11e7-9e9e-1824f3c2188d.png">

<img width="519" alt="screen shot 2018-01-22 at 4 50 03 pm" src="https://user-images.githubusercontent.com/4008351/35248633-7f40dc2c-ff94-11e7-840e-f6a052452941.png">

In order to set the threshold distance or inverse distance one needs to first click on the button below. That is not intuitive. All three designs should be the same, i.e., when selecting the type of weights (e.g., threshold distance, inverse distance) the value in the box should be initialized to the maxmin distance.

(more on the interface in the next issue)

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.107
Verified

<img width="391" alt="8 mar 13" src="https://user-images.githubusercontent.com/36253697/37166683-98ff97d0-22f7-11e8-977d-c78450d05001.PNG">

<img width="384" alt="8 mar 14" src="https://user-images.githubusercontent.com/36253697/37166671-8dcd5028-22f7-11e8-9e59-b89f1e065d80.PNG">

**Comment by jkoschinsky** [comment]
Verified Geoda 107
OSX
