### ISSUE TITLE
kernel weights interface

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1477]
V 81

order of kernels should be same as in GeoDaSpace:
- uniform
- triangular
- Epanechnikov
- quartic
- gaussian

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.97
Verified 

![12](https://user-images.githubusercontent.com/36253697/36702840-b25ffd40-1b50-11e8-9e90-fe9d8ddd2732.JPG)

**Comment by jkoschinsky** [comment]
GeoDa 1.99
MacOSX
fix verified
