### ISSUE TITLE
scatter plot display precision broken

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1478]
in V 1.12.1.81

Display precision in scatter plot is unresponsive (see also #1430). Instead of the two decimal display (as in the workbook), the current display has no decimals. As #1430 (for windows) points out, the Set display precision dialog is unresponsive. This is the case in the mac as well. This issue is more than a month old!

<img width="580" alt="screen shot 2018-01-22 at 7 27 13 pm" src="https://user-images.githubusercontent.com/4008351/35253420-f6c149b0-ffaa-11e7-9736-b9074ba74277.png">

**Comment by lanselin** [comment]
Note: the display precision dialog works for the standardized version of the scatter plot, but not for the unstandardized (raw data) version. The display issue mentioned in #1430 for the standardized graph seems to be fixed (on mac).

**Comment by lixun910** [comment]
@lanselin Actually I did this on purpose: the labels in above plot are all integers, so setting display precision (which is for floating point numbers) doesn't work.  
Anyway, I will change it back.

**Comment by lanselin** [comment]
scatter plot display precision fixed on mac (1.12.1.83)

**Comment by lanselin** [comment]
bubble chart display precision fixed on mac (1.12.1.83)

**Comment by jkoschinsky** [comment]
@DarcyLinde -- please test on Windows

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.93
Verified 
![scatter plot](https://user-images.githubusercontent.com/36253697/36635435-a453cd12-19ac-11e8-9831-ce110d325e3c.png)
