### ISSUE TITLE
Crash Report: Pending user response

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1481]
From: jazzalejandro@yahoo.com
 Details:
os: 1-10-13
vs: 1-12-1-59
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/jazminalejandro/Downloads/LatinAmerica_1.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnActivate
Open CatClassifFrame
CatClassifPanel::OnButtonNew
Open MergeTableDlg.
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/jazminalejandro/Downloads/LatinAmerica_1(1).dbf
Open Layer:LatinAmerica_1(1)
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
ds:/Users/jazminalejandro/Downloads/LatinAmerica_1(1).dbf layer: LatinAmerica_1(1)
Entering MergeTableDlg::OnExclListDClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnExclListDClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnExclListDClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnExclListDClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnExclListDClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnExclListDClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnExclListDClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnExclListDClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnExclListDClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnExclListDClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnExclListDClick()
Entering MergeTableDlg::OnIncOneClick()
In MergeTableDlg::OnMergeClick()
In TableFrame::OnActivate
Click GdaFrame::OnSaveProject
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs
New Datasource Name:/Users/jazminalejandro/Downloads/GdaTmp_LatinAmerica_1.shp
Project::GetSpatialReference()
Project::GetGdaGeometries()
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
SQKM
ScrolledWidgetsPane::IsFieldNameValid
CNTRY_NAME
ScrolledWidgetsPane::IsFieldNameValid
ISO_NUM
ScrolledWidgetsPane::IsFieldNameValid
ISO_3DIGIT
ScrolledWidgetsPane::IsFieldNameValid
OBJECTID
ScrolledWidgetsPane::IsFieldNameValid
SQMI
ScrolledWidgetsPane::IsFieldNameValid
Shape_Leng
ScrolledWidgetsPane::IsFieldNameValid
Shape_Area
ScrolledWidgetsPane::IsFieldNameValid
Urban2014
ScrolledWidgetsPane::IsFieldNameValid
Rural2014
ScrolledWidgetsPane::IsFieldNameValid
Pop2014
In FieldNameCorrectionDlg
Out FieldNameCorrectionDlg
start OGRLayerProxy::AddFreatures()
Out OGRDataAdapter::ExportDataSource()
Exiting Project::SaveDataSourceAs
Exiting Project::SaveDataSourceData
Entering Project::SaveProjectConf
Exiting Project::SaveProjectConf
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()

**Comment by jkoschinsky** [comment]
contacted user - waiting

**Comment by jkoschinsky** [comment]
see other merge table ticket
