### ISSUE TITLE
Crash with spectral clustering: timeout?

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1484]
From: avishekkumar@uchicago.edu
 Details:
os: 3-4-4
vs: 1-12-1-57
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:PG:dbname='syracuse' 
Open Layer:work_orders.break_to_main
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
PG:dbname='syracuse' 
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In MapFrame::OnMapBasemap()
Click GdaFrame::OnSetBasemap5
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
selected:0
Click CreatingWeightDlg::OnCRadioDistanceSelected
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Click CreatingWeightDlg::OnCThresholdTextEdit:
285.786165
Click CreatingWeightDlg::OnCThresholdTextEdit:
28.786165
Click CreatingWeightDlg::OnCThresholdTextEdit:
2.786165
Click CreatingWeightDlg::OnCThresholdTextEdit:
.786165
Click CreatingWeightDlg::OnCThresholdTextEdit:
786165
Click CreatingWeightDlg::OnCThresholdTextEdit:
86165
Click CreatingWeightDlg::OnCThresholdTextEdit:
6165
Click CreatingWeightDlg::OnCThresholdTextEdit:
165
Click CreatingWeightDlg::OnCThresholdTextEdit:
65
Click CreatingWeightDlg::OnCThresholdTextEdit:
5
Click CreatingWeightDlg::OnCThresholdTextEdit:

Click CreatingWeightDlg::OnCThresholdTextEdit:
2
Click CreatingWeightDlg::OnCThresholdTextEdit:
20
Click CreatingWeightDlg::OnCThresholdTextEdit:
200
Click CreatingWeightDlg::OnCThresholdTextEdit:
2000
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/home/avishek/work_orders.break_to_main_2000.gwt
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
Click CreatingWeightDlg::OnCreateClick
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/home/avishek/work_orders.break_to_main_2000.gwt
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnActivate
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
WeightsManFrame::OnHistogramBtn()
Open ConnectivityHistFrame
In WeightsManFrame::OnActivate
ConnectivityHistFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Open GetisOrdMapFrame (OnOpenGetisOrd).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
objectid
VariableSettingsDlg::GetWeightsId() weight: work_orders.break_to_main_2000
VariableSettingsDlg::GetWeightsId() weight: work_orders.break_to_main_2000
Entering GetisOrdMapFrame::GetisOrdMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Exiting GetisOrdMapFrame::GetisOrdMapFrame
In WeightsManFrame::OnActivate
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
Entering WeightsManFrame::OnRemoveBtn
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnCThresholdTextEdit:
000
Click CreatingWeightDlg::OnCThresholdTextEdit:
1000
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/home/avishek/work_orders.break_to_main_1000.gwt
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnActivate
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Open GetisOrdMapFrame (OnOpenGetisOrd).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
objectid
VariableSettingsDlg::GetWeightsId() weight: work_orders.break_to_main_1000
VariableSettingsDlg::GetWeightsId() weight: work_orders.break_to_main_1000
Entering GetisOrdMapFrame::GetisOrdMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Exiting GetisOrdMapFrame::GetisOrdMapFrame
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnCThresholdTextEdit:
100
Click CreatingWeightDlg::OnCThresholdTextEdit:
00
Click CreatingWeightDlg::OnCThresholdTextEdit:
500
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/home/avishek/work_orders.break_to_main_500.gwt
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnActivate
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
WeightsManFrame::OnHistogramBtn()
Open ConnectivityHistFrame
In WeightsManFrame::OnActivate
ConnectivityHistFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Open GetisOrdMapFrame (OnOpenGetisOrd).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
objectid
VariableSettingsDlg::GetWeightsId() weight: work_orders.break_to_main_500
VariableSettingsDlg::GetWeightsId() weight: work_orders.break_to_main_500
Entering GetisOrdMapFrame::GetisOrdMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Exiting GetisOrdMapFrame::GetisOrdMapFrame
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnCThresholdTextEdit:
5000
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/home/avishek/work_orders.break_to_main_5000.gwt
Click CreatingWeightDlg::OnCThresholdTextEdit:
000
Click CreatingWeightDlg::OnCThresholdTextEdit:
4000
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/home/avishek/work_orders.break_to_main_4000.gwt
Click CreatingWeightDlg::OnCThresholdTextEdit:
000
Click CreatingWeightDlg::OnCThresholdTextEdit:
3000
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/home/avishek/work_orders.break_to_main_3000.gwt
Click CreatingWeightDlg::OnCThresholdTextEdit:
300
Click CreatingWeightDlg::OnCThresholdTextEdit:
00
Click CreatingWeightDlg::OnCThresholdTextEdit:
200
Click CreatingWeightDlg::OnCThresholdTextEdit:
2500
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/home/avishek/work_orders.break_to_main_2500.gwt
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnActivate
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Open GetisOrdMapFrame (OnOpenGetisOrd).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
objectid
VariableSettingsDlg::GetWeightsId() weight: work_orders.break_to_main_2500
VariableSettingsDlg::GetWeightsId() weight: work_orders.break_to_main_2500
Entering GetisOrdMapFrame::GetisOrdMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Exiting GetisOrdMapFrame::GetisOrdMapFrame
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In OnSigFilter01()
In OnSigFilter05()
In OnSigFilter01()
In OnSigFilter01()
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
objectid
VariableSettingsDlg::GetWeightsId() weight: work_orders.break_to_main_2500
VariableSettingsDlg::GetWeightsId() weight: work_orders.break_to_main_2500
Entering LisaCoordinator::LisaCoordinator().
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
Entering LisaCoordinator::InitFromVarInfo()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Entering LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::CalcLisa()
Entering LisaCoordinator::CalcPseudoP()
Entering LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP()
Exiting LisaCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
In WeightsManFrame::OnActivate
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
WeightsManFrame::OnHistogramBtn()
Open ConnectivityHistFrame
In WeightsManFrame::OnActivate
ConnectivityHistFrame::OnActivate
ConnectivityHistFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In TableFrame::OnActivate
In GdaFrame::OnMoveSelectedToTop
In TableFrame::OnActivate
In TableFrame::OnActivate
Open AbstractClusterDlg.
Open SpectralClusteringDlg.
Click SpectralClusteringDlg::OnOK

**Comment by jkoschinsky** [comment]
emailed Avishek

**Comment by jkoschinsky** [comment]
probably due to file size?
