### ISSUE TITLE
scatter plot matrix - change default regime regression

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1485]

**Comment by lanselin** [comment]
V 81

Currently, the default "View" setting for the scatter plot matrix is to have Regimes Regression checked. This can be confusing at first. It would be better to have that setting unchecked by default.

<img width="425" alt="screen shot 2018-01-26 at 1 50 19 pm" src="https://user-images.githubusercontent.com/4008351/35462292-2cd30528-02a0-11e8-9a17-9e65252e5ac9.png">

**Comment by lanselin** [comment]
fixed on mac with 1.12.1.83

**Comment by jkoschinsky** [comment]
@DarcyLinde: please test on Windows

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.93
Verified 
![image1](https://user-images.githubusercontent.com/36253697/36635404-0dd7ed00-19ac-11e8-9b18-162458350b7a.jpeg)
