### ISSUE TITLE
bubble chart - display precision broken

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1486]
V 81

See also #1478, same issue, but for the bubble chart. When the variable is seen as being integer, the display precision is disabled.

**Comment by lanselin** [comment]
Same issue in the conditional scatter plots.

**Comment by lanselin** [comment]
Fixed on mac with 1.12.1.83

**Comment by jkoschinsky** [comment]
@DarcyLinde: please test on Windows

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.93
These are the results of bubble chart and conditional scatter plot
![bubble chart](https://user-images.githubusercontent.com/36253697/36635220-30f55f32-19a9-11e8-835e-9fce42a9a3d6.png)
![conditionalscatterplot](https://user-images.githubusercontent.com/36253697/36635221-36f67e8e-19a9-11e8-8ed1-e18d79fc75b7.png)

**Comment by lixun910** [comment]
V103

**Comment by jkoschinsky** [comment]
For the conditional scatterplot, if you try to set the precision to 0, nothing happens (X.0 remains, see below):

<img width="703" alt="screen shot 2018-03-06 at 3 45 52 pm" src="https://user-images.githubusercontent.com/13679743/37060341-95736e32-2155-11e8-899f-8ce2fa90868b.png">

**Comment by jkoschinsky** [comment]
@luluzhou766 Could you check if the save image problem you reported is solved in version 103? It looked fine on OSX but maybe problem persists on Win. Thx

**Comment by luluzhou766** [comment]
Yes Julia, it is fixed in vision 103.


![conditionalscatterplot](https://user-images.githubusercontent.com/36253697/37062992-f3aface2-218f-11e8-8aca-bc9e191b33e4.png)
