### ISSUE TITLE
custom breaks missing for conditional plots

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1487]
V81

The custom breaks option is no longer available for the Vertical Bins Breaks and the Horizontal Bins Breaks options in the conditional plots. This is a problem for all three conditional plots (scatter plot, map and histogram). In the lab notes, the figure shows the old "Create New Custom" option (which has been replaced by Custom Breaks), but those are no longer there.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.97
Verified 
for all three conditional plots

![11](https://user-images.githubusercontent.com/36253697/36702683-00aace36-1b50-11e8-8d53-0720159fe1ac.JPG)

**Comment by jkoschinsky** [comment]
GeoDa 1.99
MacOSX
fix verified
