### ISSUE TITLE
Crash when trying to open qGIS file?

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1488]
From: 
 Details:
os: 1-10-13
vs: 1-12-1-59
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Exiting ConnectDatasourceDlg::OnOkClick
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Exiting ConnectDatasourceDlg::OnOkClick
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/jamesnutt/Library/Mobile Documents/com~apple~CloudDocs/08 Mappings/03 Map Data/packages/Natural_Earth_quick_start/Natural_Earth_quick_start_for_QGIS_v2.qgs
Open Layer:Natural_Earth_quick_start_for_QGIS_v2
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/jamesnutt/Library/Mobile Documents/com~apple~CloudDocs/08 Mappings/03 Map Data/packages/Natural_Earth_quick_start/Natural_Earth_quick_start_for_QGIS_v2.qgs
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
Click GdaFrame::OnClose

**Comment by jkoschinsky** [comment]
@lixun910 -- looks like they're trying to open a qgs file in GeoDa and are getting a crash?

**Comment by lixun910** [comment]
Yes, it looks like so. But I just tried on my side (drag and drop a qgs file in GeoDa, but it didn’t cause a crash).

**Comment by jkoschinsky** [comment]
did you try a raster file?

**Comment by jkoschinsky** [comment]
@lixun910 this might be it:
https://github.com/nvkelso/natural-earth-vector/blob/master/packages/Natural_Earth_quick_start/Natural_Earth_quick_start_for_QGIS_v2.qgs

maybe too large?

**Comment by lixun910** [comment]
I tried this file, it doesn’t crash crash.

**Comment by jkoschinsky** [comment]
can't replicate
