### ISSUE TITLE
Crash: Save Excel file after saving new category with category editor

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1494]
From: 
 Details:
os: 3-4-4
vs: 1-12-1-57
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/agrs1mg0701ce10/Documentos/ciclo 3_espinosa leslye/shape_prv/nxprovincias.shp
Open Layer:nxprovincias
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/agrs1mg0701ce10/Documentos/ciclo 3_espinosa leslye/shape_prv/nxprovincias.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
In TableFrame::OnActivate
In GdaFrame::OnOpenStddev()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
Open MergeTableDlg.
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/agrs1mg0701ce10/Documentos/ciclo 3_espinosa leslye/shape_prv/inec_prv.xls
Open Layer:inec_prv
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
ds:/home/agrs1mg0701ce10/Documentos/ciclo 3_espinosa leslye/shape_prv/inec_prv.xls layer: inec_prv
In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnKeyChoice()
Entering MergeTableDlg::OnIncAllClick()
In MergeTableDlg::OnMergeClick()
Open FieldNameCorrectionDlg:
ScrolledWidgetsPane::RemoveIllegalChars
NñsxMj
NsxMj
ScrolledWidgetsPane::TruncateFieldName
NsxMj
ScrolledWidgetsPane::RenameDupFieldName
NsxMj
NsxMj
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
NsxMj
In FieldNameCorrectionDlg
Out FieldNameCorrectionDlg
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In GdaFrame::OnOpenHinge15()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Densi
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
MapCanvas::~MapCanvas()
In GdaFrame::OnOpenHinge15()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Densi
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
MapCanvas::~MapCanvas()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Densi
Open BoxPlotCanvas.
In TableFrame::OnActivate
In TableFrame::OnActivate
In GdaFrame::OnOpenHinge15()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
TasaAnalf
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Close BoxPlotCanvas.
In GdaFrame::OnSaveCategories()
MapCanvas::OnSaveCategories()
In GdaFrame::OnSaveCategories()
MapCanvas::OnSaveCategories()
In TableFrame::OnActivate
In TableFrame::OnActivate
In OnSaveResults()
MapCanvas::SaveRates()
In GdaFrame::OnRawrate()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
TasaAnalf
OBJECTID
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnSaveCategories()
MapCanvas::OnSaveCategories()
MapCanvas::~MapCanvas()
In TableFrame::OnActivate
MapCanvas::~MapCanvas()
In GdaFrame::OnOpenHinge15()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
TasaAnalf
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnSaveCategories()
MapCanvas::OnSaveCategories()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In GdaFrame::OnOpenHinge15()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
IndEnvej
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
In TableFrame::OnActivate
In GdaFrame::OnOpenHinge15()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
Entering MergeTableDlg::OnOpenClick()
In MergeTableDlg::OnClose()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In GdaFrame::OnOpenHinge15()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Pob
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
In TableFrame::OnActivate
In GdaFrame::OpenNaturalBreaks(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
NsxMj
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
In TableFrame::OnActivate
In GdaFrame::OnPercentile()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnThemelessMap()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::ChangeToQuantile(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
NsxMj
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnUniqueValues()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnSaveCategories()
MapCanvas::OnSaveCategories()
In GdaFrame::OnSaveCategories()
MapCanvas::OnSaveCategories()
In GdaFrame::OnPercentile()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnNewCustomCatClassifA()
MapCanvas::NewCustomCatClassif()
Open CatClassifFrame
In CatClassifPanel::PromptNew
suggested title:
field name:NsxMj
MapCanvas::CreateAndUpdateCategories()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
CatClassifPanel::OnAssocVarChoice
Pob
CatClassifPanel::OnNumCatsChoice
choice: 5
In GdaFrame::OnOpenHinge15()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Pob
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
CatClassifPanel::OnNumCatsChoice
choice: 7
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In GdaFrame::OpenNaturalBreaks(7)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Pob
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
In GdaFrame::OpenNaturalBreaks(7)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PobFem
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In GdaFrame::OnOpenHinge15()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
NBI
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnActivate
MapCanvas::~MapCanvas()
In TableFrame::OnActivate
MapCanvas::~MapCanvas()
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs
New Datasource Name:/home/agrs1mg0701ce10/Documentos/ciclo 3_espinosa leslye/shape_prv/GdaTmp_nxprovincias.shp
Project::GetSpatialReference()
Project::GetGdaGeometries()
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
OBJECTID
ScrolledWidgetsPane::IsFieldNameValid
DPA_PROVIN
ScrolledWidgetsPane::IsFieldNameValid
DPA_DESPRO
ScrolledWidgetsPane::IsFieldNameValid
DPA_VALOR
ScrolledWidgetsPane::IsFieldNameValid
DPA_ANIO
ScrolledWidgetsPane::IsFieldNameValid
REI_CODIGO
ScrolledWidgetsPane::IsFieldNameValid
REN_CODIGO
ScrolledWidgetsPane::IsFieldNameValid
PEE_CODIGO
ScrolledWidgetsPane::IsFieldNameValid
area_m
ScrolledWidgetsPane::IsFieldNameValid
area_ha
ScrolledWidgetsPane::IsFieldNameValid
area_km2
ScrolledWidgetsPane::IsFieldNameValid
COD
ScrolledWidgetsPane::IsFieldNameValid
Prv
ScrolledWidgetsPane::IsFieldNameValid
Km2
ScrolledWidgetsPane::IsFieldNameValid
Pob
ScrolledWidgetsPane::IsFieldNameValid
Densi
ScrolledWidgetsPane::IsFieldNameValid
PobMas
ScrolledWidgetsPane::IsFieldNameValid
PobFem
ScrolledWidgetsPane::IsFieldNameValid
IndEnvej
ScrolledWidgetsPane::IsFieldNameValid
NsxMj
ScrolledWidgetsPane::IsFieldNameValid
NBI
ScrolledWidgetsPane::IsFieldNameValid
TasaAnalf
ScrolledWidgetsPane::IsFieldNameValid
CATEGORIES
In FieldNameCorrectionDlg
Out FieldNameCorrectionDlg
start OGRLayerProxy::AddFreatures()
Out OGRDataAdapter::ExportDataSource()
Exiting Project::SaveDataSourceData
Entering Project::SaveProjectConf
Exiting Project::SaveProjectConf
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/agrs1mg0701ce10/Documentos/ciclo 3_espinosa leslye/shape_prv/inec_prv.xls
Open Layer:inec_prv
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/agrs1mg0701ce10/Documentos/ciclo 3_espinosa leslye/shape_prv/inec_prv.xls
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
In TableFrame::OnActivate
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/agrs1mg0701ce10/Descargas/Change2030Prv.xls
Open Layer:Change2030Prv
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/agrs1mg0701ce10/Descargas/Change2030Prv.xls
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
BSQ_2
Open BoxPlotCanvas.
Close BoxPlotCanvas.
Open GeocodingDlg().
In TableFrame::OnActivate
In TableFrame::OnActivate
Open VarGroupingEditorDlg.
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnClose
Open DataMovieDlg.
Close DataMovieDlg::OnClose
Open CatClassifFrame
CatClassifPanel::OnButtonNew
CatClassifPanel::OnSaveCategories
CatClassifPanel::OnAssocVarChoice
ARB_1
CatClassifPanel::OnNumCatsChoice
choice: 5
CatClassifPanel::OnSaveCategories
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs
New Datasource Name:/home/agrs1mg0701ce10/Descargas/GdaTmp_Change2030Prv.xls

**Comment by jkoschinsky** [comment]
@DarcyLinde 
try loading Excel file, add new category with category editor and save

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.14.1

No issue when using an excel file and adding a new category then saving it to the table.
<img width="745" alt="screen shot 2018-07-26 at 3 03 14 pm" src="https://user-images.githubusercontent.com/37029239/43285637-25422694-90e5-11e8-8fbe-79b085aceec8.png">
<img width="727" alt="screen shot 2018-07-26 at 3 03 06 pm" src="https://user-images.githubusercontent.com/37029239/43285638-2554a210-90e5-11e8-9301-bace0da18031.png">
