### ISSUE TITLE
Crash: Queen weights and connectivity histogram

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1495]
From: 
 Details:
os: 1-10-10
vs: 1-12-1-59
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/rajumainali/Desktop/Municipios.shp
Open Layer:Municipios
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/rajumainali/Desktop/Municipios.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
selected:0
Click CreatingWeightDlg::OnCRadioQueenSelected
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/Users/rajumainali/Desktop/Municipios_weight.gal
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnActivate
WeightsManFrame::OnConnectMapBtn()
Open ConnectivityMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In WeightsManFrame::OnActivate
In ConnectivityMapFrame::OnActivate
In WeightsManFrame::OnActivate
MapCanvas::~MapCanvas()
In WeightsManFrame::OnActivate
Close CreatingWeightDlg
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
MapCanvas::~MapCanvas()
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
WeightsManFrame::OnHistogramBtn()
Open ConnectivityHistFrame
In WeightsManFrame::OnActivate
ConnectivityHistFrame::OnActivate
In WeightsManFrame::OnActivate
WeightsManFrame::OnConnectMapBtn()
Open ConnectivityMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In WeightsManFrame::OnActivate
In ConnectivityMapFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
ConnectivityHistFrame::OnActivate

**Comment by jkoschinsky** [comment]
Pls test queen weights and connectivity histogram with attached data:
[municipios.zip](https://github.com/GeoDaCenter/geoda/files/1682243/municipios.zip)

**Comment by YidanJ-Wu** [comment]
Windows 8 
GeoDa 1.12.1.85
Created queen weights with a new ID field (POLY_ID). 
The connectivity histogram works. There are several polygons with 0 neighbors highlighted in the screenshot below. GeoDa displayed a warning about the neighborless polygons when creating the weights file. 
![image](https://user-images.githubusercontent.com/22801047/35662494-0a18639c-06de-11e8-905d-eeba3d19403b.png)
Did not crash. Other functionalities (Connectivity map, connectivity graph) also worked on this file.
