### ISSUE TITLE
Crash: unknown style flag

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1496]
Details:
os: 2-10-0
vs: 1-8-16-4
Check auto update:
In GdaFrame::OnHelpAbout()
Error: XRC error: 784: unknown style flag 'wxALIGN_CENTER'
In GdaFrame::OnHelpAbout()
Error: XRC error: 784: unknown style flag 'wxALIGN_CENTER'
In GdaFrame::OnCheckUpdates()
In GdaFrame::OnHelpAbout()
Error: XRC error: 784: unknown style flag 'wxALIGN_CENTER'
Open TableFrame.
Open MapFrame.
In MapFrame::OnMapBasemap()
Click GdaFrame::OnSetBasemap8
In GdaFrame::OnHelpAbout()
Error: XRC error: 784: unknown style flag 'wxALIGN_CENTER'
In GdaFrame::OnDisplayStatusBar()
In GdaFrame::OnHelpAbout()
Error: XRC error: 784: unknown style flag 'wxALIGN_CENTER'
In GdaFrame::OnCheckUpdates()
In GdaFrame::OnReportBug()
Open ReportBugDlg.
Entering GdaFrame::OnMapChoices
In MapFrame::OnMapBasemap()
In MapFrame::OnMapBasemap()
Click GdaFrame::OnCleanBasemap
In MapFrame::OnMapBasemap()
Click GdaFrame::OnSetBasemap8
Open LisaScatterPlotFrame (OnOpenMSPL).
Open LisaScatterPlotFrame (OnOpenDiffMoran).
Open LisaScatterPlotFrame (OnOpenMoranEB).
Open RegressionDlg.
Error: XRC error: 6104: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 6189: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 6198: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 6207: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 6214: both 'wxALIGN_CENTRE_VERTICAL' (as part of wxALIGN_CENTER) and 'wxALIGN_CENTRE_VERTICAL' specify vertical alignment and can't be used together
Warning: iCCP: known incorrect sRGB profile
Warning: iCCP: known incorrect sRGB profile
Error: XRC error: 6223: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click GdaFrame::OnClose
Click GdaFrame::OnClose

**Comment by jkoschinsky** [comment]
@lixun910 : they're getting lots of XRC errors - do you know what this could be?

**Comment by lixun910** [comment]
this is from old version geoda and wxwidgets
