### ISSUE TITLE
Crash: Data problem (changing LISA p-values)

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1497]
From: 
 Details:
os: 1-10-10
vs: 1-12-1-59
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/rajumainali/Desktop/Municipios.shp
Open Layer:Municipios
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/rajumainali/Desktop/Municipios.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
selected:0
Click CreatingWeightDlg::OnCRadioQueenSelected
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/Users/rajumainali/Desktop/colombia.gal
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnActivate
WeightsManFrame::OnConnectMapBtn()
Open ConnectivityMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In WeightsManFrame::OnActivate
In ConnectivityMapFrame::OnActivate
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
ID_ESPACIA
VariableSettingsDlg::GetWeightsId() weight: colombia
In ConnectivityMapFrame::OnActivate
VariableSettingsDlg::GetWeightsId() weight: colombia
In ConnectivityMapFrame::OnActivate
Entering LisaCoordinator::LisaCoordinator().
Entering LisaCoordinator::SetSignificanceFilter()
Exiting LisaCoordinator::SetSignificanceFilter()
Entering LisaCoordinator::InitFromVarInfo()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Entering LisaCoordinator::CalcLisa()
Exiting LisaCoordinator::CalcLisa()
Entering LisaCoordinator::CalcPseudoP()
Entering LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP_threaded()
Exiting LisaCoordinator::CalcPseudoP()
Exiting LisaCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In LisaCoordinator::registerObserver()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Entering LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()
Exiting LisaCoordinator::CalcPseudoP_range()

**Comment by YidanJ-Wu** [comment]
Windows 8 
GeoDa 1.12.1.85
The shapefile in municipios.zip doesn't have any fields with numerical values so I can't run LISA. 
![image](https://user-images.githubusercontent.com/22801047/35770324-68d5cb02-08de-11e8-90ea-f19618c242e5.png)

**Comment by jkoschinsky** [comment]
can't replicate
