### ISSUE TITLE
Crash: contacted user

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1498]
From: it.service@nniiem.ru
 Details:
os: 3-4-13
vs: 1-12-1-57
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/www_adm/ownCloud/NNIIEM_SCIENCE/00_MAIN_THEME/SHAPES/R52_INLA_V3.shp
Project::SetupEncoding()
ISO-8859-1
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open AbstractClusterDlg.
Open HClusterDlg.
Click HClusterDlg::OnOK

**Comment by jkoschinsky** [comment]
couldn't replicate
