### ISSUE TITLE
Crash: Skater on Linux

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1500]
From: it.service@nniiem.ru
 Details:
os: 3-4-13
vs: 1-12-1-57
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
In GdaFrame::OnHelpAbout()
In GdaFrame::OnCheckUpdates()
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/www_adm/ownCloud/NNIIEM_SCIENCE/00_MAIN_THEME/SHAPES/R52_INLA_V3.shp
Project::SetupEncoding()
ISO-8859-1
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Open LineChartFrame(Average Charts).
LineChartFrame::InitVariableChoiceCtrl()
LineChartFrame::InitGroupsChoiceCtrl()
LineChartFrame::InitTimeChoiceCtrl()
In LineChartFrame::OnVariableChoice()
LineChartFrame::InitTimeChoiceCtrl()
var: LAT, time1:-1, time2:-1, group1:0, group2:1
In LineChartFrame::OnActivate()
In LineChartFrame::OnVariableChoice()
LineChartFrame::InitTimeChoiceCtrl()
var: C2011, time1:-1, time2:-1, group1:0, group2:1
In LineChartFrame::OnActivate()
In LineChartFrame::OnGroupsChoice()
var name:C2011
In LineChartFrame::OnActivate()
In LineChartFrame::OnActivate()
In LineChartFrame::OnVariableChoice()
LineChartFrame::InitTimeChoiceCtrl()
var: C2017, time1:-1, time2:-1, group1:0, group2:1
In LineChartFrame::OnActivate()
LineChartFrame::OnClose()
Exit LineChartFrame(Average Charts).
Open AbstractClusterDlg.
Open Skater dialog.
On SkaterDlg::CreateControls
On SkaterDlg::InitVariableCombobox
Click SkaterDlg::OnOK

**Comment by YidanJ-Wu** [comment]
Windows 8
GeoDa 1.12.1.85
Tested with user-provided files. 
Open R52_INLA_V3.shp in GeoDa and load the weights file R52_INLA_V3.gal
Averages > Line Chart 
Variable LAT, Group 1 Unselected, Group 2 Selected
Variable C2011, Group 1 Unselected, Group 2 Selected
Variable C2017, Group 1 Unselected, Group 2 Selected
Close Average Charts window
Open Skater dialog, ran Skater with no crash. 
The contents of the field A_NAME have encoding issues (see screenshot below) but the weights file seems unaffected by that.

**Comment by jkoschinsky** [comment]
I also tested the same data on Mac OSX -- no crash.
@lixun910: looks like this is on Linux?
Will send you the data -- note that c2011 and c2012 are constants (zeros only)

**Comment by jkoschinsky** [comment]
see crash that Erin replicated on Linux

**Comment by lixun910** [comment]
v101 no crash on ubuntu
<img width="1002" alt="screen shot 2018-03-06 at 12 22 58 pm" src="https://user-images.githubusercontent.com/2423887/37053354-2406bf4a-2139-11e8-8fdb-2188ee0bfd3a.png">
