### ISSUE TITLE
Linux Crash: Merge table with xls file

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1504]
From: 
 Details:
os: 3-4-4
vs: 1-10-0-8
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/agrs1mg0701ce08/Escritorio/Documentos/respaldo/Ciclo 3_Lalangui Franco/prueba 2/nxprovincias.shp
Open Layer:nxprovincias
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/agrs1mg0701ce08/Escritorio/Documentos/respaldo/Ciclo 3_Lalangui Franco/prueba 2/nxprovincias.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open MergeTableDlg.
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/agrs1mg0701ce08/Escritorio/Documentos/respaldo/Ciclo 3_Lalangui Franco/prueba 2/INEC_Prv.xls
Open Layer:INEC_Prv
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
ds:/home/agrs1mg0701ce08/Escritorio/Documentos/respaldo/Ciclo 3_Lalangui Franco/prueba 2/INEC_Prv.xls layer: INEC_Prv
In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnKeyChoice()
Entering MergeTableDlg::OnIncAllClick()
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/agrs1mg0701ce08/Escritorio/Documentos/respaldo/Ciclo 3_Lalangui Franco/prueba 2/LCM2030Prv_Prc.xls
Open Layer:LCM2030Prv_Prc
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
ds:/home/agrs1mg0701ce08/Escritorio/Documentos/respaldo/Ciclo 3_Lalangui Franco/prueba 2/LCM2030Prv_Prc.xls layer: LCM2030Prv_Prc
Entering MergeTableDlg::OnIncAllClick()
In MergeTableDlg::OnMergeClick()

**Comment by jkoschinsky** [comment]
Seems to be the same crash as https://github.com/GeoDaCenter/geoda/issues/1028
Please try this version 1.12 where the problem is supposed to be fixed
if not, please let us know
