### ISSUE TITLE
local join count -- significance map incorrect for FDR

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1505]
Very strange result. Using 1.12.1.87. Here's the sequence:
- unique values map for a 0-1 variable (17588=1 out of 46311 -- Chicago blocks)
- local join count statistic, computed for default
- run 99999 permutations
- change significance to FDR
The resulting significance map is off and shows the wrong locations as significant. Also, when selecting those, one can see in the table that several empty rows are selected as significant, 
which should not be the case. However, the local cluster map seem correct. Also, entering the
p-value for the FDR as a "custom" p-value, does not change the result.

local cluster and significance map for FDR

<img width="1286" alt="screen shot 2018-02-05 at 12 00 16 pm" src="https://user-images.githubusercontent.com/4008351/35826807-b2f10418-0a6e-11e8-813e-788704f19ab7.png">

selection in table of "significant" locations from the significance map
(e.g., click to select all the sig locations) shows the empty rows

<img width="472" alt="screen shot 2018-02-05 at 12 04 09 pm" src="https://user-images.githubusercontent.com/4008351/35826868-ea784932-0a6e-11e8-8cb5-d33f737ec8f2.png">

also, the matching selection in the cluster map includes many non-significant locations
(i.e., 10415 selected. whereas there are only 2851 "true" significant locations)

<img width="639" alt="screen shot 2018-02-05 at 12 03 48 pm" src="https://user-images.githubusercontent.com/4008351/35826889-02c4a666-0a6f-11e8-9878-7243391d80b3.png">

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.97
Verified 

<img width="904" alt="05" src="https://user-images.githubusercontent.com/36253697/36698832-d3460c24-1b42-11e8-8d87-b5ee6e56a7e4.PNG">

**Comment by jkoschinsky** [comment]
Mac OSX
Geoda 1.12.1.97
Verified: N of high-high the same as N for significant areas after FDR selected
