### ISSUE TITLE
weights manager - update weights characteristics when unknown

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1507]
When loading a weights file that was created previously, the connectivity statistics are shown as "unknown". Instead, these should be calculated on the fly if given as "unknown" since this is easy to do from the weights information. In contrast, for example, it is impossible to figure out from the weights what type of contiguity they might be.

<img width="384" alt="screen shot 2018-02-06 at 3 45 04 pm" src="https://user-images.githubusercontent.com/4008351/35890564-2080c43c-0b55-11e8-8b8b-717e72909268.png">

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.107
Verified 
<img width="409" alt="8 mar 12" src="https://user-images.githubusercontent.com/36253697/37166165-3dbb39a2-22f6-11e8-8014-4c66026e0561.PNG">

**Comment by jkoschinsky** [comment]
Verified Geoda 107
OSX
