### ISSUE TITLE
mds weights - unknown id variable

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1508]
When creating a weights file from an MDS plot, the ID variable is written as "id" to the resulting file (e.g., a gwt file). But if the data set does not contain a variable id, then the weights cannot be loaded.
So, either there should be a dialog to request an ID variable, or if the variable "id" is not currently in the table, it should be added.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.107
Verified

<img width="753" alt="8 mar 11" src="https://user-images.githubusercontent.com/36253697/37165611-fa1c35a8-22f4-11e8-899c-7e75504499e8.PNG">

**Comment by jkoschinsky** [comment]
Verified Geoda 107
OSX
