### ISSUE TITLE
mds weights not added to weights manager upon creation

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1509]
When creating a weights matrix from the MDS results, the file is written but it is not loaded into the current weights manager, in contrast to what happens when creating a "regular" weights file. This should be consistent. Maybe as part of the redesign of the MDS weights creation interface.

Also, the weights characteristics should be computed and added to the listing in the weights manager.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.97
Verified 

<img width="350" alt="07" src="https://user-images.githubusercontent.com/36253697/36700172-d52275ec-1b46-11e8-99a3-a14f62171905.PNG">

**Comment by jkoschinsky** [comment]
GeoDa 1.99
MacOSX
fix verified
