### ISSUE TITLE
mds weights file dialog has extra gwt

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1510]
The file name suggested for the knn weights from the MDS interface has an extra gwt.

<img width="460" alt="screen shot 2018-02-06 at 3 26 57 pm" src="https://user-images.githubusercontent.com/4008351/35892624-0fb57846-0b5f-11e8-8b8b-6aa4c9d56e5d.png">

**Comment by lanselin** [comment]
Also for contiguity weights from MDS.

<img width="411" alt="screen shot 2018-02-06 at 5 00 02 pm" src="https://user-images.githubusercontent.com/4008351/35892664-449bea4a-0b5f-11e8-8c8f-0a4187a60903.png">

**Comment by lanselin** [comment]
V 1.12.1.93 works in mac, can be closed if verified in win/linux

**Comment by YidanJ-Wu** [comment]
Windows 8
GeoDa 1.12.1.93
Verified for .gwt and .gal files created in MDS
![image](https://user-images.githubusercontent.com/22801047/36232493-973df40c-11a7-11e8-9686-12c1d836d8d4.png)
![image](https://user-images.githubusercontent.com/22801047/36232516-ad0cec70-11a7-11e8-89f0-71c9f74512d3.png)
