### ISSUE TITLE
connectivity graph color

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1511]
When the connectivity graph color is changed, e.g., from the default black to yellow, then the color of the outline of neighbors in "Selection and Neighbors" is also changed to the same color, even when the connectivity graph is no longer shown.

In addition, it is not possible to change this color, unless the connectivity graph is brought back up.

Solution:
- add option to change color of neighbors in selection and neighbors

**Comment by lixun910** [comment]
new design

<img width="595" alt="screen shot 2018-02-07 at 12 10 56 pm" src="https://user-images.githubusercontent.com/2423887/35936278-02fe48a2-0c00-11e8-9e71-8a98466e7d51.png">

**Comment by jkoschinsky** [comment]
fix to be verified by @lanselin

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.97
Verified 

![06](https://user-images.githubusercontent.com/36253697/36699570-faf1c7d4-1b44-11e8-9b2f-5dd380de1096.png)

![07](https://user-images.githubusercontent.com/36253697/36699577-fe6ca2b2-1b44-11e8-9900-1fe1deaca6f1.JPG)

**Comment by jkoschinsky** [comment]
GeoDa 1.99
Mac OSX

edge color can be changed without affecting color of neighbor selection
