### ISSUE TITLE
Crash: Saving table with invalid field names

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1512]
From: 
 Details:
os: 1-10-13
vs: 1-12-1-59
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/aprilklein/Documents/Emory/Coursework/Spring 2018/EH 583 Spatial Anal/Lab1/Lab1/mi_countyEEE.shp
Open Layer:mi_countyEEE
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/aprilklein/Documents/Emory/Coursework/Spring 2018/EH 583 Spatial Anal/Lab1/Lab1/mi_countyEEE.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnOpenRawrate()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
NEEE
Nhorse
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
Open ExportDataDlg in its Init()
In GdaFrame::OnOpenExcessrisk()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
NEEE
Nhorse
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
In OnSaveResults()
MapCanvas::SaveRates()
In OnSaveResults()
MapCanvas::SaveRates()
Open Themeless Map (OnOpenThemelessMap).
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnOpenEmpiricalBayes()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
NEEE
Nhorse
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
In GdaFrame::OnOpenExcessrisk()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
NEEE
Nhorse
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open Themeless Map (OnOpenThemelessMap).
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnOpenEmpiricalBayes()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
NEEE
Nhorse
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open Themeless Map (OnOpenThemelessMap).
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnOpenExcessrisk()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
NEEE
Nhorse
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Open Themeless Map (OnOpenThemelessMap).
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnOpenRawrate()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
NEEE
Nhorse
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Open Themeless Map (OnOpenThemelessMap).
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnOpenExcessrisk()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
NEEE
Nhorse
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::SetDetailsForItem
WeightsManFrame::OnHistogramBtn()
Open ConnectivityHistFrame
In WeightsManFrame::OnActivate
ConnectivityHistFrame::OnActivate
In GdaFrame::OnOpenSpatialEmpiricalBayes()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
NEEE
Nhorse
VariableSettingsDlg::GetWeightsId() weight: mi_weights
ConnectivityHistFrame::OnActivate
VariableSettingsDlg::GetWeightsId() weight: mi_weights
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
ConnectivityHistFrame::OnActivate
MapCanvas::~MapCanvas()
ConnectivityHistFrame::OnActivate
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
ConnectivityHistFrame::OnActivate
PNG selected
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Click GdaFrame::OnClose
Project::GetProjectFullPath()
Open ExportDataDlg in its Init()
In ExportDataDlg::OnOkClick()
ds:
In ExportDataDlg::BrowseExportDataSource()
In ExportDataDlg::OnOkClick()
ds:/Users/aprilklein/Desktop/*.gdb
Project::GetSpatialReference()
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
POLY_ID
ScrolledWidgetsPane::IsFieldNameValid
NAME_1
ScrolledWidgetsPane::IsFieldNameValid
AREA_1
ScrolledWidgetsPane::IsFieldNameValid
POP1990_1
ScrolledWidgetsPane::IsFieldNameValid
POP1997_1
ScrolledWidgetsPane::IsFieldNameValid
POP90_SQ_1
ScrolledWidgetsPane::IsFieldNameValid
HOUSEHOL_1
ScrolledWidgetsPane::IsFieldNameValid
NO_FARMS_1
ScrolledWidgetsPane::IsFieldNameValid
1980_COUNT
ScrolledWidgetsPane::IsFieldNameValid
Nhorse
ScrolledWidgetsPane::IsFieldNameValid
NEEE
ScrolledWidgetsPane::IsFieldNameValid
Cas_1000ho
ScrolledWidgetsPane::IsFieldNameValid
X
ScrolledWidgetsPane::IsFieldNameValid
Y
ScrolledWidgetsPane::IsFieldNameValid
R_EXCESS
ScrolledWidgetsPane::IsFieldNameValid
R_RAW_RT
In FieldNameCorrectionDlg
Out FieldNameCorrectionDlg
In ExportDataDlg::OnOkClick()
ds:/Users/aprilklein/Desktop/.gdb
Project::GetSpatialReference()
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
POLY_ID
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
NAME_1
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
AREA_1
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
POP1990_1
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
POP1997_1
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
POP90_SQ_1
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
HOUSEHOL_1
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
NO_FARMS_1
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
1980_COUNT
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
Nhorse
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
NEEE
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
Cas_1000ho
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
X
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
Y
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
R_EXCESS
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
R_RAW_RT
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::RemoveIllegalChars
POLY_ID
ScrolledWidgetsPane::TruncateFieldName
POLY_ID
ScrolledWidgetsPane::RenameDupFieldName
POLY_ID
ScrolledWidgetsPane::TruncateFieldName
POLY_ID

**Comment by jkoschinsky** [comment]
Looks like they're trying to save invalid names for excess risk maps and raw rate maps?
might be other field name problems if you can play with this -- thx

**Comment by YidanJ-Wu** [comment]
Windows 8 
1.12.1.113
No crash with saving rates but I'm curious whether the checkbox on the "Save Rate" form does anything? 
![image](https://user-images.githubusercontent.com/22801047/37995178-218b11c0-31d9-11e8-8c3b-415c4d12afc2.png)

**Comment by lixun910** [comment]
@YidanJ-Wu  Yes, this is from a universal design (for reusing code). For example, when one tries to save results in LISA map, a similar dialog will be showed up with more than one to-be-saved variables. The checkboxes are for selecting which variable the user don't want to save by unchecking the box.
