### ISSUE TITLE
significance map incorrect after selecting FDR

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1519]
This may be related to #1505.

In multivariate local Geary, adjusting the custom significance to FDR makes the full map the same color green, rather than respecting the earlier cut-off values.

This may be generic to the selection of FDR anywhere (still need to check this).

<img width="596" alt="screen shot 2018-02-08 at 1 20 19 pm" src="https://user-images.githubusercontent.com/4008351/35990704-e81eca06-0cd2-11e8-962e-5969790a4105.png">

**Comment by lixun910** [comment]
I think this is correct: if one specifies the FDR value via "Custom Inference", that means this value will be used as the only cut-off value in significance map, so there is only one color for this cut-off value. 
 Let me know what do you think.

**Comment by lanselin** [comment]
I see, but the logic contrasts with the other ones. So, I think it should keep the different
0.05, 0.01 etc. gradations, as much as possible. One color for all hides that differentiation.
Does this make sense?
L.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.97
Verified 
<img width="453" alt="04" src="https://user-images.githubusercontent.com/36253697/36697153-2357af74-1b3e-11e8-9507-6ea352dd7000.PNG">

**Comment by jkoschinsky** [comment]
Mac OSX
Geoda 1.12.1.97
Verified
