### ISSUE TITLE
percent nonzero not saved in project file metadata

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1522]
V 1.12.1.91

The percent non-zero weights characteristic is not saved in the project metadata.

<img width="380" alt="screen shot 2018-02-09 at 9 47 51 am" src="https://user-images.githubusercontent.com/4008351/36033498-389344d8-0d7f-11e8-89f5-3afd9b4ebdb7.png">

<img width="516" alt="screen shot 2018-02-09 at 9 51 03 am" src="https://user-images.githubusercontent.com/4008351/36033503-3f97d50a-0d7f-11e8-8321-e455f95884a1.png">

**Comment by lanselin** [comment]
fixed in mac V 1.12.1.93

**Comment by YidanJ-Wu** [comment]
Windows 8 
1.12.1.93
Verified
![image](https://user-images.githubusercontent.com/22801047/36234175-45692acc-11af-11e8-84e2-638f353704a6.png)
