### ISSUE TITLE
Crash: Regression related to special character variable names?

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1526]
From: martinliz5@hotmail.com
 Details:
os: 1-10-13
vs: 1-12-1-59
/Users/martinliz5/Desktop/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/martinliz5/Desktop/Waller Co. DATA ONLY.xlsx
Open Layer:Waller Co. DATA ONLY
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/martinliz5/Desktop/Waller Co. DATA ONLY.xlsx
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
In TableFrame::OnActivate
In GdaFrame::OnRegressionClassic()
Open RegressionDlg.
RegressionDlg::InitVariableList()
RegressionDlg::OnCButton1Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnRunClick
y:Below Poverty
x:
African Amer00
Asian Amer00
Hispanic00
Occupied housing units: Owner occupied
Occupied housing units: Renter occupied
                                                               years old
6.953122E-310ducation: less than college experience
140732764089344nemployed

**Comment by jkoschinsky** [comment]
Hi,

Thank you for submitting a GeoDa crash report. We are trying to track down regression crashes like yours. 
Would you be able to share your data (for testing only) and the steps before the crash, so we can try to replicate and send you a fixed version?
If you can't share the data, could you share the steps?

Thanks,
Julia

**Comment by jkoschinsky** [comment]
@lixun910 

do you know why numbers are showing up in the field names before the crash?
6.953122E-310ducation: less than college experience
140732764089344nemployed

Are these placeholders for special characters?
This is a common crash, too, so would be great to track this down

**Comment by jkoschinsky** [comment]
try running regression with fields that start with special characters

**Comment by bsalas11** [comment]
Win 1.14

Unable to replicate crash with special characters.
