### ISSUE TITLE
distance weights - incorrect inverse distance property

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1532]
Version 1.12.1.93

When computing a distance band weights matrix without the inverse distance box checked, the 
inverse distance "property"  in the weights manager is nevertheless given as "true".

<img width="397" alt="screen shot 2018-02-13 at 6 46 24 pm" src="https://user-images.githubusercontent.com/4008351/36185602-ebed5e7a-10ee-11e8-8896-e44f15238a70.png">

**Comment by lanselin** [comment]
It seems that the inverse distance property is read incorrectly. The example above is for a regular distance band. For an inverse distance the "inverse distance" property is not shown.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.97
Verified 

Max-min distance weights
<img width="291" alt="min max distance weights" src="https://user-images.githubusercontent.com/36253697/36645789-cf8b1922-1a65-11e8-944b-c6ff5f8ddfa2.PNG">

Inverse distance weights 
<img width="288" alt="inverse" src="https://user-images.githubusercontent.com/36253697/36645793-e6d52bcc-1a65-11e8-8c72-bd01553c913a.PNG">

**Comment by jkoschinsky** [comment]
Mac OSX
Geoda 1.12.1.97
Fix verified
