### ISSUE TITLE
weights manager - discrepancy in minimum distance band

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1533]
V 1.12.1.93

There is a discrepancy between the minimum distance band given by GeoDa and the one given by GeoDaSpace. For example, using Guerry, GeoDa gives 129849.311969 as the max min of the distances between the centroids. GeoDaSpace gives 96726.1432388 for the same shape file.

Some manipulation in R (using rgdal to read the shape file, then coords to extract the centroids, then dist to compute the distance matrix, some conversion to matrix to insert a fake value as the diagonal, then rowMins (from package rpgm) to extract the minimum and finally max from that yields 96724.48, which is much closer to the value from GeoDaSpace/PySAL than the value from GeoDa. I suspect something may be wrong here.

Using the value from GeoDaSpace as a manual distance band in GeoDa creates islands. Using the value from GeoDa as a manual distance band in GeoDaSpace yields a weights file with 2 as the minimum neighbors (it should be 1). But using the distance band from GeoDa in GeoDa yields weights with 1 as the minimum neighbors.

<img width="510" alt="screen shot 2018-02-13 at 6 45 46 pm" src="https://user-images.githubusercontent.com/4008351/36186651-3c983a1a-10f5-11e8-95c0-33658378ab26.png">

<img width="471" alt="screen shot 2018-02-13 at 6 46 05 pm" src="https://user-images.githubusercontent.com/4008351/36186656-488ccc46-10f5-11e8-82f4-e250a088f7e8.png">

**Comment by lanselin** [comment]
confirmed that max min distance is same between GeoDa and GeoDaSpace for point coverage, so the problem is with computing the distances between polygon centroids. maybe the centroids used internally are not the same as the ones computed from the map menu. those match between GeoDa and R, but the distances do not.

<img width="955" alt="screen shot 2018-02-14 at 5 55 04 pm" src="https://user-images.githubusercontent.com/4008351/36237444-783218e6-11b0-11e8-8baa-077a49c8fdde.png">

**Comment by lixun910** [comment]
I just checked: GeoDa gives the correct min bandwidth to guarantee yielding weights with 1 as the minimum neighbors.  In detail, GeoDa using R-tree to compute the actual maximum pair-wise distance (as the min banwidth), which guarantees 1 minimum neighbors.

The methods in R is an approximation algorithm using dist matrix, which is not accurate and slow. I didn't check pysal's algorithm.

**Comment by lanselin** [comment]
The result in R is correct, since it uses the full distance matrix, no R tree. So it gives the maximum of the minima in each row of the distance matrix. Slow, but correct!

**Comment by lixun910** [comment]
Sorry. My bad. I can update the algorithm to calculate the actual dist
value .

**Comment by lanselin** [comment]
But interesting that the R-tree algorithm does not find the correct distance.
Why is that? It works correctly for points.

**Comment by lixun910** [comment]
The centroids created by GeoDa and R are very different, that's the main issue cause the difference of the bandwidth calculation:

Here are R's centroids:
 <img width="609" alt="screen shot 2018-02-16 at 7 57 12 pm" src="https://user-images.githubusercontent.com/2423887/36337441-b0d94fc6-1353-11e8-81e3-16efc05b9ba6.png">

Here are GeoDa's centroids:
<img width="542" alt="screen shot 2018-02-16 at 7 59 24 pm" src="https://user-images.githubusercontent.com/2423887/36337449-ebc4de66-1353-11e8-9da6-82cd6b3b2f27.png">

If apply R's min bandwidth: 96724.48 to GeoDa, you will see some pairs are not within this band: see the graph created using bandwidth=96724.48:
<img width="521" alt="screen shot 2018-02-16 at 8 01 14 pm" src="https://user-images.githubusercontent.com/2423887/36337462-28f3c98c-1354-11e8-8a15-85595046c071.png">

I am checking the centroids creation code in GeoDa now.

**Comment by lanselin** [comment]
But the centroids I got in R from coords on an sp object and the ones generated by
GeoDa were exactly the same.

**Comment by lixun910** [comment]
They are not the same. The first graph is generated from R using your code by adding two lines:
plot(guerry)
points(vv, pch = 3, col = "Red")

**Comment by lixun910** [comment]
You can see for some simple ploygons, R and GeoDa have same centroids, but for some complex (multi-parts, non-contiguity) polygons, the centroids are different.

**Comment by lixun910** [comment]
Since GeoDa's centroids are different than what R/Pysal' centroids, 
the distance matrix generated from GeoDa is different than R/Pysal's dist matrix.

The max value of the distance matrix, which is the min bandwidth in weights creation, from GeoDa is different than R/Pysal's. That's why the max-min distances are different. 

(GeoDa generates same min-max distances with pysal using points dataset. However, for polygons, GeoDa generate a different points dataset (centroids) than pysal, so the min-max distances will be different)

From the GeoDa's centroids map (guerry above), especially the left side and lower right corner, some centroids are on the edge of the polygons, which are not as good as what R generated.

**Comment by lixun910** [comment]
One thing: the R-tree used in GeoDa is for finding the pairs that are far way fast, the distance is still computed using the coords of the centroids. Since the centroids are not the same with R/Pysal, the final distance computed is different than R/Pysal.

**Comment by lixun910** [comment]
This is not right for computing centroid: 

<img width="524" alt="screen shot 2018-02-16 at 9 52 14 pm" src="https://user-images.githubusercontent.com/2423887/36338133-56b663ec-1364-11e8-83bd-a91a73ed8ea4.png">

**Comment by lanselin** [comment]
OK, that makes sense. If some centroids are different (I only checked the first few), especially if they are for critical polygons (i.e., polygons that are large) then the distances would be different.

I thought all these codes used the same algorithm for centroids :-) Isn't that part of the GEOS library?

**Comment by lixun910** [comment]
Yes, there is a centroid function in geos and I am trying to fix this using
GDAL/geos.

**Comment by lixun910** [comment]
Fixed using GEOS (used by GDAL as well).

<img width="509" alt="screen shot 2018-02-18 at 8 03 17 pm" src="https://user-images.githubusercontent.com/2423887/36361143-e7285d80-14e6-11e8-87e7-fe55a53bf2bc.png">

**Comment by jkoschinsky** [comment]
See ticket https://github.com/GeoDaCenter/geoda/issues/1476
