### ISSUE TITLE
weights manager - min neighbors given as unknown when islands

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1534]
V 1.12.1.93

When the weights matrix contains islands (e.g., when the distance band is too small), the "min neighbors" property is given as "unknown", it should be 0.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.97
Verified 

<img width="276" alt="min distance neighbors" src="https://user-images.githubusercontent.com/36253697/36645595-28daafc2-1a63-11e8-9a9a-c7d4242454df.PNG">
