### ISSUE TITLE
mds weights creation - close button doesn't work on mac

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1535]
V 1.12.1.93

After creating a weights file from MDS coordinates, on a Mac, the red close button (x in upper left corner) does not work. One needs to click on the "Close" button in the lower right explicitly. This behavior is different from that in the regular weight file creation dialog.

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.137
Verified

red "x" in upped left works

<img width="497" alt="screen shot 2018-06-15 at 4 09 08 pm" src="https://user-images.githubusercontent.com/37029239/41489679-77698826-70b6-11e8-993e-2b7e3407c485.png">
<img width="402" alt="screen shot 2018-06-15 at 4 08 52 pm" src="https://user-images.githubusercontent.com/37029239/41489680-7779df3c-70b6-11e8-8382-b05e2abb2607.png">
