### ISSUE TITLE
weights - map overwrites connectivity graph

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1536]
V 1.12.1.93

With a connectivity graph is created on a themeless map, a new map type (e.g., change current map type and create a box map) overwrites the connectivity graph, even though it is still given as checked in the menu (connectivity > show graph is checked).

One needs to uncheck show graph and then check it again to have it appear.

So, either the graph should be redrawn on top of the new map, or the check mark should be turned off after a map is created.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.97
Verified 

<img width="448" alt="connectivity graph" src="https://user-images.githubusercontent.com/36253697/36651718-30887ed6-1aa2-11e8-9e2c-85690b714810.PNG">
