### ISSUE TITLE
weights - remove weights removes map

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1537]
V 1.12.1.93

The current logic is such that when one removes a spatial weight from the list in the weights manager, there is a warning that a current view depends on the weights, even though that is not necessarily the case. I suspect that the connectivity graph creates a dependence for any map, even though there hasn't been any weights analysis (or connectivity graph for that matter). As a result, removing the weight also removes the map, which should not happen. This should only happen if there is an active connectivity graph for that weight.

<img width="425" alt="screen shot 2018-02-14 at 6 01 10 pm" src="https://user-images.githubusercontent.com/4008351/36237583-7281588e-11b1-11e8-862f-8f536fc2fe68.png">

**Comment by lixun910** [comment]
Since the current "Connectivity Graph" is based on a regular map window, so it will be difficult to distinguish a map window with "Connectivity->Graph" checked, vs.  a spatial rate map window where a current weights is associated. From a perspective of window instance manager -- it only knows which map windows are associated with current weights. 

So, a fix will be needed to change the basic interface of all base and inherited map windows. I will leave it with the work "Redesign Cluster Maps" https://github.com/GeoDaCenter/geoda/issues/1519

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.97
The non-connectivity map depends on the sequences of opening the weights manager. 
1)	Create a box map first, then open the weights manager.
        When remove weights, the box map disappears without any notice. 
2)	Open the weights manager first, then create a box map.
         The box map remains after either load or remove any weights.

**Comment by lixun910** [comment]
v103

**Comment by jkoschinsky** [comment]
GeoDa 103
OSX

Fixed: Map view that's not dependent on weights stays open when weights are removed, without warning.

However, small thing: If you load weights and then load a Local G map, and remove the weights, you do get the warning below saying two views dependent on the weights when it's actually only one view.

<img width="849" alt="screen shot 2018-03-06 at 3 28 02 pm" src="https://user-images.githubusercontent.com/13679743/37059633-9731c8b0-2153-11e8-81b2-dab1595df4d6.png">

**Comment by lixun910** [comment]
For some reasons, the LISA map is counted as "2 other views". To make it simple, I just change the text to "There are some other views". Let me know if it's good.

**Comment by jkoschinsky** [comment]
Why don't we say: There is at least one view ...

**Comment by lanselin** [comment]
It may be two views because it is both the significance map and cluster map, even though they may not both be visible?

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.107

Fixed: Maps do not depend on weights stay open when weights are removed. 

For weight depended map, there is a warning: 

<img width="404" alt="8 mar 05" src="https://user-images.githubusercontent.com/36253697/37161833-a47fc83e-22eb-11e8-9a62-7d1fc18463ab.PNG">
