### ISSUE TITLE
weights properties - distance vars always shown as centroids

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1538]
The property "distance vars" is always listed as centroids, even for point layers. For the latter, it should be coordinates, not centroids. The difference is that centroids are calculated, whereas the coordinates are just read. Also, if it is always listed as centroids, there is no point in having this property :-)

<img width="406" alt="screen shot 2018-02-14 at 6 08 34 pm" src="https://user-images.githubusercontent.com/4008351/36237694-59e04b72-11b2-11e8-8ed4-12c54252c839.png">

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.97
Verified 
<img width="351" alt="coordinates" src="https://user-images.githubusercontent.com/36253697/36651247-d5cc4c0e-1a9f-11e8-9abd-ac93172b647e.PNG">
