### ISSUE TITLE
Differential Local Morans, Clustering

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#1539]
The following was reported by a user: 
> we are encountered with the similar problems using GeoDa 1.12 as previously having been encountered with GeoDa 1.10 in June. Thus, the first problem is related to Differential Local Moran's I ESDA tool which is colored a grey. Hence, one cannot run the analysis anyway although he/she has already prepared spatial weights as well as edit times variables in accordance to recommended steps on the pull down menu. The second problem deals with running all methods within 'Clusters' tool where no analysis cannot be done with approx. more than 1000 polygons as the software shuts down or no responses after clicking on the 'Run' button at every time. In addition, I attach our training file as a testing one for you as well. The dataset contains panel data concerning on structure of creative industries in 1993, 2004 and 2015 relating to polygons for Slovak municipalities. Tens of Slovak municipalities have been excluded from the analysis by deletion as no creative industries firm had been presented before 2015 there.  

Steps to replicate: 
Create time grouped variable
![image](https://user-images.githubusercontent.com/22801047/36239136-db30ca8e-11cc-11e8-890f-94243856c489.png)

Create or load weights file
Space > Differential Local Morans I
Select time-grouped variable and the times (in this case 0 and 1)
![image](https://user-images.githubusercontent.com/22801047/36239149-f1e95926-11cc-11e8-96ff-4a996ddb0a07.png)
Significance map and LISA Cluster Map produced
![image](https://user-images.githubusercontent.com/22801047/36239199-460cbed0-11cd-11e8-90c4-bc59409bb89f.png)

Spectral clustering froze for a few seconds but eventually unfroze. 
![image](https://user-images.githubusercontent.com/22801047/36239568-57bee10a-11d0-11e8-9564-a43cd23770e1.png)
Crashed on Skater
![image](https://user-images.githubusercontent.com/22801047/36239599-90e61bce-11d0-11e8-92d5-6c55f5a1d5a6.png)

Got this error message with REDCAP (shown below) and Spectral
![image](https://user-images.githubusercontent.com/22801047/36239633-cf9e22f8-11d0-11e8-8bf7-7007f675a9f4.png)

Because the file had so many polygons w/o neighbors, I used a threshold weights file, not queen or k-nearest-neighbors for testing. 
![image](https://user-images.githubusercontent.com/22801047/36239692-40d50572-11d1-11e8-9dda-1e3ced5388d2.png)

**Comment by jkoschinsky** [comment]
@lixun910: I'm assuming the Skater crash is because N is too large at 1,216?

**Comment by lixun910** [comment]
No, I can run skater on NAT in 10 seconds.

**Comment by jkoschinsky** [comment]
ok, then there's another reason for the crash -- will send you the data, thx

**Comment by lixun910** [comment]
@YidanJ-Wu can you share the data with me? Thanks!

**Comment by lixun910** [comment]
@YidanJ-Wu I can't replicate the crash with many configurations on both Win and Mac. Can you try again with v97? THanks!

**Comment by YidanJ-Wu** [comment]
I replicated the crash in 1.12.1.97 on Windows 8
@lixun910 I'll send you the file and logger text.

**Comment by lixun910** [comment]
on Mac<img width="1387" alt="screen shot 2018-03-06 at 11 26 47 am" src="https://user-images.githubusercontent.com/2423887/37052935-0f6af020-2138-11e8-9ba9-fbdeb0886e6d.png">
on Windows
<img width="788" alt="screen shot 2018-03-06 at 11 36 23 am" src="https://user-images.githubusercontent.com/2423887/37052937-1162dd98-2138-11e8-8a95-a1255ebf163a.png">

**Comment by lixun910** [comment]
V103

**Comment by jkoschinsky** [comment]
@YidanJ-Wu Hi Julie, could you also check on your version of Windows if the crash is resolved using version 103? Thx

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.107
Verified
![image](https://user-images.githubusercontent.com/22801047/37173165-792515bc-22d8-11e8-959f-f4bf845b6ca6.png)
![image](https://user-images.githubusercontent.com/22801047/37173183-82bd5058-22d8-11e8-9735-8d34eb866e0f.png)
