### ISSUE TITLE
distance weights - slight adjustment to dialog

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1540]
In the kernel dialog move the number of k nearest neighbors above the use max knn distance as bandwidth item. So move it directly under "Adaptive bandwidth"

<img width="349" alt="screen shot 2018-02-15 at 8 33 30 am" src="https://user-images.githubusercontent.com/4008351/36268401-38374330-122b-11e8-8a0e-7568f01032a9.png">

**Comment by lanselin** [comment]
Also, I am not sure the "Apply kernel to diagonal weights" check box is that intuitive. The default should be (and is) that the diagonal elements are = 1. So, I suggest there are two boxes (with only one enabled):
x diagonal weights = 1 (default)
x apply kernel function to diagonal weights

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.97
Verified 

<img width="364" alt="1540" src="https://user-images.githubusercontent.com/36253697/36651162-311da6f8-1a9f-11e8-9b02-4f4873f8c014.PNG">
