### ISSUE TITLE
kernel weights file - use kwt file extension

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1541]
To keep compatibility with PySAL, use kwt file extension for kernel weights. Also make sure kwt files can be read and are recognized as such.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.97
It is kwt while creating it.
<img width="568" alt="kwt" src="https://user-images.githubusercontent.com/36253697/36650724-d4cf83fa-1a9c-11e8-8883-c09686273ce8.PNG">

But  it shows gwt in the saved file and property table. 
<img width="634" alt="gwt" src="https://user-images.githubusercontent.com/36253697/36650733-df263fd8-1a9c-11e8-95e8-85475f736bb3.PNG">

**Comment by lixun910** [comment]
please check again in v99

<img width="363" alt="screen shot 2018-02-27 at 10 45 22 am" src="https://user-images.githubusercontent.com/2423887/36744954-6065eeea-1bab-11e8-8d63-99a08c76942f.png">

**Comment by jkoschinsky** [comment]
GeoDa 1.99
MacOSX

confirmed that the kernel weights are ultimately saved as a gwt file.  Also, they're not automatically loaded in the weights manager after creation, as the other weights.

<img width="370" alt="screen shot 2018-03-05 at 12 24 45 pm" src="https://user-images.githubusercontent.com/13679743/36992390-5e416846-2070-11e8-8fa7-55b2835cdb28.png">

**Comment by lanselin** [comment]
Confirmed as well: weights file is gwt (even though dialog says kwt) and it does not appear in the weights manager.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.101
The file extension and the cube root are fixed now. 
But I got another bug: the number of neighbor should be 11, not 4. 

<img width="670" alt="17" src="https://user-images.githubusercontent.com/36253697/37049809-02a47974-216a-11e8-8f58-8fbc47b459ba.PNG">



The previous result is come from clicking only the adaptive bandwidth option. But after clicking the number of neighbors and set it to 11, then the result is correct. 


<img width="675" alt="18" src="https://user-images.githubusercontent.com/36253697/37049824-0e83b41c-216a-11e8-8dab-f5766ca2ab7a.PNG">

**Comment by lixun910** [comment]
v103

**Comment by jkoschinsky** [comment]
GeoDa 103
looks correct on Mac OSX

<img width="922" alt="screen shot 2018-03-06 at 3 52 30 pm" src="https://user-images.githubusercontent.com/13679743/37060616-77b9a11c-2156-11e8-91e2-7d744f422d74.png">

@luluzhou766 could you confirm on 103 in Win? thx

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.103
Verified 
<img width="727" alt="21" src="https://user-images.githubusercontent.com/36253697/37063253-b85ae48a-2190-11e8-8fe5-15b5a8c61fb7.PNG">
