### ISSUE TITLE
kernel weights - mismatch k in dialog and k used

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1542]
There seems to be a mismatch between the number of knn neighbors specified in the dialog (in my example 5) and the number actually used (4 as reported in the dialog). The kernel weights file also has four neighbors.

<img width="717" alt="screen shot 2018-02-15 at 8 40 32 am" src="https://user-images.githubusercontent.com/4008351/36268878-88a3d0da-122c-11e8-8327-0238194b63b2.png">

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.97
Verified 
<img width="833" alt="kernel 5" src="https://user-images.githubusercontent.com/36253697/36650258-649b771c-1a9a-11e8-8156-77d4cea0560d.PNG">
