### ISSUE TITLE
Add note to cluster dialogues: For smaller datasets.

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1543]
Add note to cluster dialogues:
Please note: Only supported for smaller datasets.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.93

I used a data set with 1015 observations and tried all the Cluster options. I did not meet any note about data size. Would you please let me know where to look for it?

**Comment by lixun910** [comment]
it's on the dialog. Should be in v97 +
<img width="878" alt="screen shot 2018-02-24 at 12 19 52 pm" src="https://user-images.githubusercontent.com/2423887/36634118-155cbcd0-195d-11e8-92f8-924cd61dc92f.png">

**Comment by luluzhou766** [comment]
Thank you Xun.
The note is not in the V97
I donot have V97+

<img width="724" alt="cluster_data size note" src="https://user-images.githubusercontent.com/36253697/36644877-544eb5d2-1a58-11e8-865c-adcb4dccbcd8.PNG">

**Comment by jkoschinsky** [comment]
confirmed on Mac OSX
GeoDa .97: not included yet:

<img width="776" alt="screen shot 2018-02-26 at 10 43 24 am" src="https://user-images.githubusercontent.com/13679743/36682933-f1cf4acc-1ae1-11e8-8d3b-f1686912fac9.png">

**Comment by lixun910** [comment]
please check  in v99

**Comment by jkoschinsky** [comment]
GeoDa 1.99
MacOSX
fix verified
