### ISSUE TITLE
Crash: Saving results in averages chart

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1544]
From: 
 Details:
os: 1-10-12
vs: 1-12-1-59
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Warning: could not set Working Dir from /Users/liuziqi/Downloads/eu/eu.shp
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/liuziqi/Downloads/eu/eu.shp
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/liuziqi/Documents/UIUC/2018Spring/ACE532/eu/eu.shp
Open Layer:eu
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/liuziqi/Documents/UIUC/2018Spring/ACE532/eu/eu.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open TimeChooserDlg.
Open VarGroupingEditorDlg.
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnRemoveFrListClick
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnRemoveFrListClick
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnCreateGrpClick
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
Open LineChartFrame(Average Charts).
LineChartFrame::InitVariableChoiceCtrl()
LineChartFrame::InitGroupsChoiceCtrl()
LineChartFrame::InitTimeChoiceCtrl()
In LineChartFrame::OnActivate()
In LineChartFrame::OnVariableChoice()
LineChartFrame::InitTimeChoiceCtrl()
var: POLYID, time1:-1, time2:-1, group1:0, group2:1
In LineChartFrame::OnVariableChoice()
LineChartFrame::InitTimeChoiceCtrl()
var: GDP, time1:0, time2:0, group1:0, group2:1
In LineChartFrame::OnActivate()
In LineChartFrame::OnActivate()
In LineChartFrame::OnActivate()
Start LineChartFrame::OnSaveDummyTable
Open ExportDataDlg in its Init()
In ExportDataDlg::BrowseExportDataSource()
In ExportDataDlg::OnOkClick()
ds:/Users/liuziqi/Documents/UIUC/2018Spring/ACE532/eu.gdb
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
STID
ScrolledWidgetsPane::IsFieldNameValid
PERIOD
ScrolledWidgetsPane::IsFieldNameValid
GDP
ScrolledWidgetsPane::IsFieldNameValid
SPACE
In FieldNameCorrectionDlg
Out FieldNameCorrectionDlg
In ExportDataDlg::OnOkClick()
ds:/Users/liuziqi/Documents/UIUC/2018Spring/ACE532/northsouth
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
STID
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
PERIOD
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
GDP
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::IsFieldNameValid
SPACE
Error:no valid entry in datasrc_field_lens, could be a unwritable ds
ScrolledWidgetsPane::RemoveIllegalChars
STID
ScrolledWidgetsPane::TruncateFieldName
STID
ScrolledWidgetsPane::RenameDupFieldName
STID
ScrolledWidgetsPane::TruncateFieldName
STID

**Comment by jkoschinsky** [comment]
It looks like the crash is related to trying to save the results (save dummy or save test results) of the averages chart with duplicate field names. Please test.

<img width="799" alt="screen shot 2018-02-15 at 4 47 10 pm" src="https://user-images.githubusercontent.com/13679743/36285135-06d5d082-1270-11e8-904a-2a0816962ea5.png">

**Comment by YidanJ-Wu** [comment]
Windows 8 
Version 1.12.1.113
I tried saving test results and dummy in this version and had no issues with variable names. 
![image](https://user-images.githubusercontent.com/22801047/37941316-43488bfe-3133-11e8-9a43-10f34da8548f.png)
GeoDa opened the output files correctly (dbf). 
![image](https://user-images.githubusercontent.com/22801047/37941350-6c6d52f8-3133-11e8-83cb-9f81026d3e2a.png)
![image](https://user-images.githubusercontent.com/22801047/37941360-792d4354-3133-11e8-8a87-39236e866d54.png)
