### ISSUE TITLE
kernel - epanechnikov needs to be scaled

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1545]
V 1.12.1.93

The value returned for the Epanechnikov kernel is (1 - z^2). To be consistent with what is given in Anselin and Rey (2014) p. 78 and the implementation in PySAL, the value should be scaled by 0.75.
The expression should be (3/4) (1 - z^2) for z < 1, where z = d/dmax.

**Comment by lanselin** [comment]
The other kernel functions are correct - checked.

**Comment by lixun910** [comment]
This is from pysal: http://pysal.readthedocs.io/en/latest/library/weights/user.html

<img width="527" alt="screen shot 2018-02-16 at 3 57 03 pm" src="https://user-images.githubusercontent.com/2423887/36333056-1532a53e-1332-11e8-8b7c-3e7deaf6d272.png">

**Comment by lanselin** [comment]
It should be scaled. PySAL actually uses the expression for the quadratic. We should use the scaled expression which is the one from Anselin and Rey. PySAL docs are what they are.

**Comment by lixun910** [comment]
Luc's note is correct (the same as in the paper). It's the PYSAL page needs to be updated.
