### ISSUE TITLE
Rates override

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1546]
Details:
os: 2-10-0
vs: 1-8-16-4
Check auto update:
Open TableFrame.
Open MapFrame.
In MapFrame::OnMapBasemap()
Click GdaFrame::OnSelectableOutlineVisible
In GdaFrame::OnDisplayMeanCenters()
Click GdaFrame::OnSelectableOutlineVisible
In GdaFrame::OnStddev()
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
regions
In MapFrame::OnMapBasemap()
In GdaFrame::OnEmpiricalBayes()
Open VariableSettingsDlg
Error: XRC error: 1577: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1583: horizontal alignment flag 'wxALIGN_CENTRE_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1601: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1607: horizontal alignment flag 'wxALIGN_CENTRE_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1615: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1662: horizontal alignment flag 'wxALIGN_CENTER_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1672: horizontal alignment flag 'wxALIGN_CENTER_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick
In MapFrame::OnMapBasemap()
Click GdaFrame::OnBasemapConfig
Open BasemapConfDlg.
In GdaFrame::OnSaveCategories()
In GdaFrame::OnSaveCategories()
In GdaFrame::OnSpatialRate()
Open VariableSettingsDlg
Error: XRC error: 1121: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:

**Comment by jkoschinsky** [comment]
try saving spatial rates, Empirical Bayes rates, and spatial EB rates -- looks like it crashed there. thx

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.113
Messed around with the rates tool. No crash so far but I found that overwriting variables retains the original format. 
For example: saving the categories from a raw rates map as "R_RATES" would create an integer variable. Then, saving the rates from a raw rates map as "R_RATES" would save the rates as integers instead of float because the "R_RATES" variable already existed as an integer.

**Comment by lixun910** [comment]
@YidanJ-Wu yes, this is a normal behavior. When one saves values to an integer field, all (float) values will be converted to integers because the field type can not be changed. User need to save float values to a float field.
