### ISSUE TITLE
Crash: Variable Grouping Editor

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1548]
From: 
 Details:
os: 1-10-13
vs: 1-12-1-59
/Users/Apple/Desktop/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
Open CsvFieldConfDlg.
CsvFieldConfDlg::PrereadCSV()
CsvFieldConfDlg::UpdateFieldGrid()
CsvFieldConfDlg::ReadCSVT()
CsvFieldConfDlg::UpdatePreviewGrid()
CsvFieldConfDlg::UpdateXYcombox()
CsvFieldConfDlg::OnOkClick()
CsvFieldConfDlg::WriteCSVT()
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Volumes/Seagate Backup Plus Drive/GEODA_test/test_4_1/test_4_stata data_result.csv
Open Layer:test_4_stata data_result
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Volumes/Seagate Backup Plus Drive/GEODA_test/test_4_1/test_4_stata data_result.csv
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
Open DataViewerEditFieldPropertiesDlg
In DataViewerEditFieldPropertiesDlg::OnGridComboBox
3
Entering DataViewerEditFieldPropertiesDlg::OnFieldSelected
Entering DataViewerEditFieldPropertiesDlg::OnCellChanging
changing row 3, col 1 from string to date
In DataViewerEditFieldPropertiesDlg::OnGridComboBox
4
Entering DataViewerEditFieldPropertiesDlg::OnFieldSelected
Entering DataViewerEditFieldPropertiesDlg::OnCellChanging
changing row 3, col 1 from string to time
In TableFrame::OnActivate
Close DataViewerEditFieldPropertiesDlg
In TableFrame::OnActivate
Open DataViewerEditFieldPropertiesDlg
In DataViewerEditFieldPropertiesDlg::OnGridComboBox
4
Entering DataViewerEditFieldPropertiesDlg::OnFieldSelected
Entering DataViewerEditFieldPropertiesDlg::OnCellChanging
changing row 3, col 1 from string to time
In DataViewerEditFieldPropertiesDlg::OnGridComboBox
5
Entering DataViewerEditFieldPropertiesDlg::OnFieldSelected
Entering DataViewerEditFieldPropertiesDlg::OnCellChanging
changing row 32, col 1 from integer to datetime
Close DataViewerEditFieldPropertiesDlg
In TableFrame::OnActivate
Click GdaFrame::OnSaveProject
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs
New Datasource Name:/Volumes/Seagate Backup Plus Drive/GEODA_test/test_4_1/GdaTmp_test_4_stata data_result.csv
Project::GetSpatialReference()
Project::GetGdaGeometries()
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
ID
ScrolledWidgetsPane::IsFieldNameValid
ID_2
ScrolledWidgetsPane::IsFieldNameValid
Apt_Name
ScrolledWidgetsPane::IsFieldNameValid
month
ScrolledWidgetsPane::IsFieldNameValid
price_con_index
ScrolledWidgetsPane::IsFieldNameValid
price_apt_index
ScrolledWidgetsPane::IsFieldNameValid
LN_price_con_index
ScrolledWidgetsPane::IsFieldNameValid
LN_price_apt_index
ScrolledWidgetsPane::IsFieldNameValid
price_con_33
ScrolledWidgetsPane::IsFieldNameValid
price_apt_33
ScrolledWidgetsPane::IsFieldNameValid
LN_price_con_33
ScrolledWidgetsPane::IsFieldNameValid
LN_price_apt_33
ScrolledWidgetsPane::IsFieldNameValid
price_sell
ScrolledWidgetsPane::IsFieldNameValid
Juny_Area
ScrolledWidgetsPane::IsFieldNameValid
Gu
ScrolledWidgetsPane::IsFieldNameValid
Dong
ScrolledWidgetsPane::IsFieldNameValid
Sta_Name
ScrolledWidgetsPane::IsFieldNameValid
dummy_trans
ScrolledWidgetsPane::IsFieldNameValid
All_Hou
ScrolledWidgetsPane::IsFieldNameValid
Sta_Dis
ScrolledWidgetsPane::IsFieldNameValid
Y
ScrolledWidgetsPane::IsFieldNameValid
X
ScrolledWidgetsPane::IsFieldNameValid
dummy_ent
ScrolledWidgetsPane::IsFieldNameValid
Room
ScrolledWidgetsPane::IsFieldNameValid
Bath
ScrolledWidgetsPane::IsFieldNameValid
Year
ScrolledWidgetsPane::IsFieldNameValid
Year_2
ScrolledWidgetsPane::IsFieldNameValid
ele_dis
ScrolledWidgetsPane::IsFieldNameValid
mid_dis
ScrolledWidgetsPane::IsFieldNameValid
high_dis
ScrolledWidgetsPane::IsFieldNameValid
univ_dis
ScrolledWidgetsPane::IsFieldNameValid
cen_dis
ScrolledWidgetsPane::IsFieldNameValid
dummy_2005
ScrolledWidgetsPane::IsFieldNameValid
dummy_2007
ScrolledWidgetsPane::IsFieldNameValid
dummy_2008
ScrolledWidgetsPane::IsFieldNameValid
dummy_2009
ScrolledWidgetsPane::IsFieldNameValid
dummy_2017
ScrolledWidgetsPane::IsFieldNameValid
yong
ScrolledWidgetsPane::IsFieldNameValid
RNR
ScrolledWidgetsPane::IsFieldNameValid
Aptname_num
ScrolledWidgetsPane::IsFieldNameValid
station_name_num
ScrolledWidgetsPane::IsFieldNameValid
time_month
ScrolledWidgetsPane::IsFieldNameValid
time_year
ScrolledWidgetsPane::IsFieldNameValid
sta_2
ScrolledWidgetsPane::IsFieldNameValid
ele_dis_2
ScrolledWidgetsPane::IsFieldNameValid
mid_dis_2
ScrolledWidgetsPane::IsFieldNameValid
hgh_dis_2
ScrolledWidgetsPane::IsFieldNameValid
univ_dis_2
ScrolledWidgetsPane::IsFieldNameValid
cen_dis_2
ScrolledWidgetsPane::IsFieldNameValid
group_apt_area
ScrolledWidgetsPane::IsFieldNameValid
time_n
ScrolledWidgetsPane::IsFieldNameValid
group_ID2_area
ScrolledWidgetsPane::IsFieldNameValid
_Itime_year_2006
ScrolledWidgetsPane::IsFieldNameValid
_Itime_year_2007
ScrolledWidgetsPane::IsFieldNameValid
_Itime_year_2008
ScrolledWidgetsPane::IsFieldNameValid
_Itime_year_2009
ScrolledWidgetsPane::IsFieldNameValid
_Itime_year_2010
ScrolledWidgetsPane::IsFieldNameValid
_Itime_year_2011
ScrolledWidgetsPane::IsFieldNameValid
_Itime_year_2012
ScrolledWidgetsPane::IsFieldNameValid
_Itime_year_2013
ScrolledWidgetsPane::IsFieldNameValid
_Itime_year_2014
ScrolledWidgetsPane::IsFieldNameValid
_Itime_year_2015
ScrolledWidgetsPane::IsFieldNameValid
_Itime_year_2016
ScrolledWidgetsPane::IsFieldNameValid
_Itime_year_2017
In FieldNameCorrectionDlg
Out FieldNameCorrectionDlg
start OGRLayerProxy::AddFreatures()
Out OGRDataAdapter::ExportDataSource()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
Open DataViewerEditFieldPropertiesDlg
In DataViewerEditFieldPropertiesDlg::OnGridComboBox
3
Entering DataViewerEditFieldPropertiesDlg::OnFieldSelected
Entering DataViewerEditFieldPropertiesDlg::OnCellChanging
changing row 3, col 1 from time to date
In TableFrame::OnActivate
Close DataViewerEditFieldPropertiesDlg
Click GdaFrame::OnSaveProject
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs
New Datasource Name:/Volumes/Seagate Backup Plus Drive/GEODA_test/test_4_1/GdaTmp_test_4_stata data_result.csv
Project::GetSpatialReference()
Project::GetGdaGeometries()
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
ID
ScrolledWidgetsPane::IsFieldNameValid
ID_2
ScrolledWidgetsPane::IsFieldNameValid
Apt_Name
ScrolledWidgetsPane::IsFieldNameValid
month
ScrolledWidgetsPane::IsFieldNameValid
price_con_index
ScrolledWidgetsPane::IsFieldNameValid
price_apt_index
ScrolledWidgetsPane::IsFieldNameValid
LN_price_con_index
ScrolledWidgetsPane::IsFieldNameValid
LN_price_apt_index
ScrolledWidgetsPane::IsFieldNameValid
price_con_33
ScrolledWidgetsPane::IsFieldNameValid
price_apt_33
ScrolledWidgetsPane::IsFieldNameValid
LN_price_con_33
ScrolledWidgetsPane::IsFieldNameValid
LN_price_apt_33
ScrolledWidgetsPane::IsFieldNameValid
price_sell
ScrolledWidgetsPane::IsFieldNameValid
Juny_Area
ScrolledWidgetsPane::IsFieldNameValid
Gu
ScrolledWidgetsPane::IsFieldNameValid
Dong
ScrolledWidgetsPane::IsFieldNameValid
Sta_Name
ScrolledWidgetsPane::IsFieldNameValid
dummy_trans
ScrolledWidgetsPane::IsFieldNameValid
All_Hou
ScrolledWidgetsPane::IsFieldNameValid
Sta_Dis
ScrolledWidgetsPane::IsFieldNameValid
Y
ScrolledWidgetsPane::IsFieldNameValid
X
ScrolledWidgetsPane::IsFieldNameValid
dummy_ent
ScrolledWidgetsPane::IsFieldNameValid
Room
ScrolledWidgetsPane::IsFieldNameValid
Bath
ScrolledWidgetsPane::IsFieldNameValid
Year
ScrolledWidgetsPane::IsFieldNameValid
Year_2
ScrolledWidgetsPane::IsFieldNameValid
ele_dis
ScrolledWidgetsPane::IsFieldNameValid
mid_dis
ScrolledWidgetsPane::IsFieldNameValid
high_dis
ScrolledWidgetsPane::IsFieldNameValid
univ_dis
ScrolledWidgetsPane::IsFieldNameValid
cen_dis
ScrolledWidgetsPane::IsFieldNameValid
dummy_2005
ScrolledWidgetsPane::IsFieldNameValid
dummy_2007
ScrolledWidgetsPane::IsFieldNameValid
dummy_2008
ScrolledWidgetsPane::IsFieldNameValid
dummy_2009
ScrolledWidgetsPane::IsFieldNameValid
dummy_2017
ScrolledWidgetsPane::IsFieldNameValid
yong
ScrolledWidgetsPane::IsFieldNameValid
RNR
ScrolledWidgetsPane::IsFieldNameValid
Aptname_num
ScrolledWidgetsPane::IsFieldNameValid
station_name_num
ScrolledWidgetsPane::IsFieldNameValid
time_month
ScrolledWidgetsPane::IsFieldNameValid
time_year
ScrolledWidgetsPane::IsFieldNameValid
sta_2
ScrolledWidgetsPane::IsFieldNameValid
ele_dis_2
ScrolledWidgetsPane::IsFieldNameValid
mid_dis_2
ScrolledWidgetsPane::IsFieldNameValid
hgh_dis_2
ScrolledWidgetsPane::IsFieldNameValid
univ_dis_2
ScrolledWidgetsPane::IsFieldNameValid
cen_dis_2
ScrolledWidgetsPane::IsFieldNameValid
group_apt_area
ScrolledWidgetsPane::IsFieldNameValid
time_n
ScrolledWidgetsPane::IsFieldNameValid
group_ID2_area
ScrolledWidgetsPane::IsFieldNameValid
_Itime_year_2006
ScrolledWidgetsPane::IsFieldNameValid
_Itime_year_2007
ScrolledWidgetsPane::IsFieldNameValid
_Itime_year_2008
ScrolledWidgetsPane::IsFieldNameValid
_Itime_year_2009
ScrolledWidgetsPane::IsFieldNameValid
_Itime_year_2010
ScrolledWidgetsPane::IsFieldNameValid
_Itime_year_2011
ScrolledWidgetsPane::IsFieldNameValid
_Itime_year_2012
ScrolledWidgetsPane::IsFieldNameValid
_Itime_year_2013
ScrolledWidgetsPane::IsFieldNameValid
_Itime_year_2014
ScrolledWidgetsPane::IsFieldNameValid
_Itime_year_2015
ScrolledWidgetsPane::IsFieldNameValid
_Itime_year_2016
ScrolledWidgetsPane::IsFieldNameValid
_Itime_year_2017
In FieldNameCorrectionDlg
Out FieldNameCorrectionDlg
start OGRLayerProxy::AddFreatures()
Out OGRDataAdapter::ExportDataSource()
In TableFrame::OnActivate
In TableFrame::OnActivate
Open FieldNewCalcSheetDlg.
Open DataViewerAddColDlg.
DataViewerAddColDlg::CreateControls()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
In DataViewerAddColDlg::SetDefaultsByType()
DataViewerAddColDlg::UpdateApplyButton()
In TableFrame::OnActivate
In FieldNewCalcSheetDlg::OnPageChange()
page idx: -1
In FieldNewCalcSheetDlg::OnClose()
In TableFrame::OnActivate
Open MergeTableDlg.
In MergeTableDlg::OnClose()
In TableFrame::OnActivate
Open VarGroupingEditorDlg.
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnRemoveFrListClick
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnCreateGrpClick
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnCreateGrpClick

**Comment by jkoschinsky** [comment]
try replicating steps before crash:

csv file:
--save string to date
--save string to time
--group variables

**Comment by YidanJ-Wu** [comment]
GeoDa 1.12.1.93
Windows 8 
Open CSV
Right click Edit Variable Properties to change one field from string to date, another field from string to time. One small issue with converting string to time is that incorrect times like 39:69 are not caught
![image](https://user-images.githubusercontent.com/22801047/36355008-115830c0-14a2-11e8-8e86-575edabdab63.png)

Time Editor does not allow grouping variables of different formats. The button for adding a variable is grayed out if formats do not match (see below screenshots). 
![image](https://user-images.githubusercontent.com/22801047/36354980-cbd86736-14a1-11e8-8a39-06ac2faee0f3.png)

![image](https://user-images.githubusercontent.com/22801047/36354976-b891523c-14a1-11e8-8677-c2b40cbe8f2a.png)

**Comment by lixun910** [comment]
I can't see any reason to group date/time/string type variables.  So, my current solution is to restrict grouping on integer/real type variables.

**Comment by jkoschinsky** [comment]
@YidanJ-Wu I agree that only allowing groups of the same type makes sense. Julie, after you converted time and date to string, can you then group those converted string variables?

**Comment by YidanJ-Wu** [comment]
In 1.12.1.97 on Windows, it does allow grouping on strings. However the same error message (shown below) comes up when I try to create a histogram of the string variable at time 0, time 1 etc. 
![image](https://user-images.githubusercontent.com/22801047/36710111-928eb7fe-1b41-11e8-8ea6-7c3e733d0af9.png)
![image](https://user-images.githubusercontent.com/22801047/36710114-995c5dfc-1b41-11e8-8fc9-d5ec7d33c828.png)

**Comment by lixun910** [comment]
please check in v101

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.107
Verified
![image](https://user-images.githubusercontent.com/22801047/37174361-df8f0a8a-22db-11e8-81cd-b0539ccd29df.png)
