### ISSUE TITLE
feature request - metadata on saved classifications in Project File

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1552]
As it stands, there is no metadata to "remember" what a saved category pertains to. Specifically, there is no information on: (1) the original variable; (2) the type of classification (e.g., quartile, equal interval); (3) the intervals with which the classifications correspond. 

I would be nice if this could be recorded in the project file and say brought up in the Table menu as "special variables".

**Comment by lanselin** [comment]
Same holds for when an indicator variable is created through "Save Selection". It would be nice to know what original variable this pertained to. Or, if it was not based on a range selection, that it was a purely geographic/spatial selection, e.g., when using a selection rectangle.

**Comment by lixun910** [comment]
When "Save Categories" from a map window, the meta-data can be saved in a gda project file, and when load from this project file, right click menu from a Table window will show a "Meta-data" menu item with details shown in its submenus: 

<img width="747" alt="Screen Shot 2019-03-21 at 1 14 46 PM" src="https://user-images.githubusercontent.com/2423887/54782215-8f8fd580-4bdb-11e9-92f5-9b7e2ad1a029.png">

**Comment by lixun910** [comment]
When save selection (only "New Selection") to a column using the Selection Tool dialog, the meta-data can be saved in a gda project file, and when load from this project file, right click menu from a Table window will show a "Meta-data" menu item with details shown in its submenus: 

<img width="1072" alt="Screen Shot 2019-03-21 at 1 19 16 PM" src="https://user-images.githubusercontent.com/2423887/54782369-f31a0300-4bdb-11e9-80d2-782e76dbee2f.png">

**Comment by lixun910** [comment]
Verified in GeoDa 1.14 on Mac and Ubuntu.

<img width="747" alt="Screen Shot 2019-08-02 at 7 43 40 PM" src="https://user-images.githubusercontent.com/2423887/62406266-d9ab9f00-b55d-11e9-9b2b-940d7b8fc883.png">
