### ISSUE TITLE
13 crashes related to clusters on Linux: Test

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1565]
From: 
 Details:
os: 3-4-13
vs: 1-12-1-57
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/trescientosmil/Desktop/testclt.shp
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
selected:0
Click CreatingWeightDlg::OnCRadioDistanceSelected
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00485803
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00528132
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0057046
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00612788
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00655116
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.013747
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.021366
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.027292
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0327947
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0366042
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0399905
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0425302
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0446466
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0454931
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0459164
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0463397
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0459164
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0454931
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0450699
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0442233
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0438
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0433767
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0429534
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0425302
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0421069
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0416836
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0412603
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.040837
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0404137
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0399905
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0395672
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0391439
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0387206
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0382973
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0378741
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0374508
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0370275
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0366042
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0361809
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0357576
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0353344
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0344878
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0340645
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0336412
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0332179
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0327947
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0323714
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0319481
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0315248
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0311015
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0306783
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.030255
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0298317
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0294084
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0289851
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0285618
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0281386
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0277153
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.027292
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0268687
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0264454
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0260222
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0255989
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0251756
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0247523
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.024329
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0239057
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0234825
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0230592
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0226359
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0222126
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0217893
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.021366
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0209428
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0205195
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0200962
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0196729
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0192496
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0188264
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0184031
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0179798
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0175565
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0171332
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0162867
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0154401
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0141702
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0133237
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0124771
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0112073
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.010784
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00909086
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00824429
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00697445
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00612788
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00528132
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00443475
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00401147
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00443475
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00485803
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00528132
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0057046
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00612788
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00909086
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0103607
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0120538
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0129004
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0141702
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0145935
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0162867
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0175565
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0188264
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0192496
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0205195
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0209428
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.021366
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0217893
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0222126
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0230592
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0234825
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0264454
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0281386
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0311015
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0336412
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0366042
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0387206
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0421069
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0442233
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0446466
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0442233
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0433767
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0421069
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.040837
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0378741
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0361809
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0336412
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0311015
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0285618
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0264454
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0239057
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0226359
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0205195
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0196729
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0188264
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0184031
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0179798
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0175565
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0171332
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0167099
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0162867
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0158634
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0154401
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0150168
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0145935
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0141702
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.013747
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0133237
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0129004
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0124771
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0120538
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0116306
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0112073
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.010784
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0103607
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00993742
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00951414
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00909086
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00866757
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00824429
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00782101
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00739773
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00697445
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00655116
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00612788
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0057046
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00528132
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00485803
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00443475
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00485803
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.00528132
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0057046
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
0.0057046
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/home/trescientosmil/Desktop/teste.gwt
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnActivate
Open AbstractClusterDlg.
Open Max-p dialog.
On MaxpDlg::CreateControls
On MaxpDlg::InitVariableCombobox
Click MaxpDlg::OnOK
Click MaxpDlg::OnOK

**Comment by jkoschinsky** [comment]
13 crashes related to clusters on Linux, summarized below (will close other tickets). Dataset (e.g. sqlite and shp) listed above, cluster function below. Please test the same cluster functions.

ir_iris_bcn.sqlite
Open Layer:ir_iris_bcn
max-p
spectral clustering

montjuic
Open Layer:data_out.dem_bcn
spectral clustering (2x)
skater
redcap
get centroids spectral clustering (2x)

/Desktop/testclt.shp
hierarchical clustering (2x = replicable crash)
redcap
spectral clustering
max-p (2x)

**Comment by lixun910** [comment]
Can't replicate using GeoDa 1.14 and Ubuntu 18.04. Using lab notes of clustering features, and also using some large dataset. I guess it might be caused by the user terminating GeoDa program while using clustering features on a large dataset -- GeoDa will use all CPU cores to do computation and it will hang with "not responding" status.

Would suggest to close or achieve it to GeoDa 1.12 thread.
