### ISSUE TITLE
Crash: Data synched with dropbox

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1566]
From: 
 Details:
os: 1-10-11
vs: 1-12-0-0
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Exiting ConnectDatasourceDlg::OnOkClick
GdaFrame::OpenProject()
/Users/nahely/Dropbox/COLMEX/3.Tesis/ENADID 2014/base_datos_enadid14_dbf/TMMujer1.dbf
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/nahely/Dropbox/COLMEX/3.Tesis/ENADID 2014/base_datos_enadid14_dbf/TMMujer1.dbf
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
In TableFrame::OnActivate
Open ExportDataDlg in its Init()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
Open ExportDataDlg in its Init()
In ExportDataDlg::OnOkClick()

**Comment by jkoschinsky** [comment]
another crash related to data that's synched with dropbox, which used to cause crashes
