### ISSUE TITLE
Spatial Lags are not the same with knn=4 weights and knn=4&inverse distance weights (guerry)

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1567]

**Comment by YidanJ-Wu** [comment]
Windows 8 
1.12.1.93 
I actually got an error message saying that KNN weights weren't allowed for spatial lag. Is this correct? 
![image](https://user-images.githubusercontent.com/22801047/36436715-b2090290-162a-11e8-99fd-5f7ee430becd.png)

**Comment by lixun910** [comment]
This should be fixed in 97. I will send you a window binary soon.

**Comment by jkoschinsky** [comment]
but the error is still correct

**Comment by lixun910** [comment]
Yes, all gwt/kwt weights will be read as gal (with neighborhood information) for computing spatial lag. So, this dialog should not be prompted.

**Comment by jkoschinsky** [comment]
but the issue is that you shouldn't be able to run spatial regression with non-symmetric weights like KNN.

**Comment by jkoschinsky** [comment]
@YidanJ-Wu can you clarify if you were getting the error for the Moran scatterplot/spatial lag or for spatial regression? The error refers to spatial regression but maybe it also gets prompted in other contexts?

**Comment by YidanJ-Wu** [comment]
I was getting the error for regression with spatial lag: 
![image](https://user-images.githubusercontent.com/22801047/36456042-8714b320-1668-11e8-8591-dfb2bbc5cab2.png)

**Comment by jkoschinsky** [comment]
which is legit and doesn't require changes. thx

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.101
Verified 
<img width="219" alt="19" src="https://user-images.githubusercontent.com/36253697/37050856-ddd2fc44-216c-11e8-91ef-ce56edccd910.PNG">
