### ISSUE TITLE
Crash: saving Excel file after merge

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1575]
From: 
 Details:
os: 3-4-4
vs: 1-12-1-57
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/agrs1mg0302ce12/Escritorio/Info2B_EXP2_data/Data/nxprovincias.shp
Open Layer:nxprovincias
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/agrs1mg0302ce12/Escritorio/Info2B_EXP2_data/Data/nxprovincias.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open AggregationDlg.
In AggregationDlg::OnClose()
Open MergeTableDlg.
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/agrs1mg0302ce12/Escritorio/Info2B_EXP2_data/Data/INEC_Prv.xls
Open Layer:INEC_Prv
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
ds:/home/agrs1mg0302ce12/Escritorio/Info2B_EXP2_data/Data/INEC_Prv.xls layer: INEC_Prv
In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnKeyChoice()
Entering MergeTableDlg::OnIncAllClick()
Entering MergeTableDlg::OnExclAllClick()
In MergeTableDlg::OnCloseClick()
In TableFrame::OnActivate
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/agrs1mg0302ce12/Escritorio/Info2B_EXP2_data/Data/INEC_Prv.xls
Open Layer:INEC_Prv
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
ds:/home/agrs1mg0302ce12/Escritorio/Info2B_EXP2_data/Data/INEC_Prv.xls layer: INEC_Prv
In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnKeyChoice()
Entering MergeTableDlg::OnIncAllClick()
Entering MergeTableDlg::OnExclAllClick()
Entering MergeTableDlg::OnIncOneClick()
In MergeTableDlg::OnCloseClick()
In TableFrame::OnActivate
Entering MergeTableDlg::OnOpenClick()
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/agrs1mg0302ce12/Escritorio/Info2B_EXP2_data/Data/LCM2030Prv_Prc.xls
Open Layer:LCM2030Prv_Prc
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
ds:/home/agrs1mg0302ce12/Escritorio/Info2B_EXP2_data/Data/LCM2030Prv_Prc.xls layer: LCM2030Prv_Prc
In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnCloseClick()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/agrs1mg0302ce12/Escritorio/Info2B_EXP2_data/Data/INEC_Prv.xls
Open Layer:INEC_Prv
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick

**Comment by jkoschinsky** [comment]
This is another crash that we haven't been able to replicate: merging xls file to shp file and then crash on saving file. We've been getting several of these and tested it but still need to catch this.

**Comment by YidanJ-Wu** [comment]
Windows 8 
1.12.1.107
Open .xls file in GeoDa, merge to .shp file, save as .csv and .dbf and as .gda
No issues with .csv or .dbf formats. However did notice that when reopening .gda file the merged field (zip2) did not show up. 
CSV: 
![image](https://user-images.githubusercontent.com/22801047/37177102-1133ddb0-22e4-11e8-8eb5-4297dd77d3cc.png)
table opened from .gda file: 
![image](https://user-images.githubusercontent.com/22801047/37177114-1983310a-22e4-11e8-9fb5-f70ea3e872ad.png)

**Comment by lixun910** [comment]
@YidanJ-Wu  I am trying to replicate your issue. Here is one question:
In your first screenshot, the csv file (which I assume is a merged one) "test2" shows the "zip2" column.
In your second screenshot, there is no "zip2" column.  Is this datasource "cb_2016_us_zcta510_500k testfile"  the excel file opened using .gda project file?  If it is, then it is correct, since GeoDa can't write back to a excel file. That's why you need to save as a csv file or dbf file.

**Comment by jkoschinsky** [comment]
@YidanJ-Wu

**Comment by YidanJ-Wu** [comment]
Yes, "cb_2016_us_zcta510_500k testfile" is the excel file opened using the gda project file. Thanks Xun for clarifying!
