### ISSUE TITLE
contiguity weights - histogram interval labels have wrong precision

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1584]
V 1.12.1.99
<img width="653" alt="screen shot 2018-03-02 at 1 34 37 pm" src="https://user-images.githubusercontent.com/4008351/36923011-bb375e60-1e1e-11e8-86fb-3cf0850d5375.png">

The labels shown under the connectivity histogram have changed. They used to give the intervals as 1, 2, 3, etc. (integer, as they should be), now they are 1.000, 2.000 etc.

Old way:

<img width="653" alt="screen shot 2018-03-02 at 1 34 37 pm" src="https://user-images.githubusercontent.com/4008351/36923028-cbc40f26-1e1e-11e8-9fbd-6f73bcce60b6.png">

New/wrong way:

<img width="663" alt="screen shot 2018-03-02 at 1 33 44 pm" src="https://user-images.githubusercontent.com/4008351/36923042-d3373102-1e1e-11e8-8270-fa94ebbfcdaa.png">

Why has this changed? and this should be fixed.

**Comment by lixun910** [comment]
This is related to https://github.com/GeoDaCenter/geoda/issues/1478  --"Actually I did this on purpose: the labels in above plot are all integers, so setting display precision (which is for floating point numbers) doesn't work.Anyway, I will change it back."

Histogram uses same  print out function: "from" and "to" values are then not detected if they are integers or not.  

Will add an option for histogram to detect and print integers.

**Comment by lanselin** [comment]
OK, but the labels in a connectivity histogram are always integers, so the extra precision is not needed. Also, it clutters up the graph. For the connectivity histogram, it should not be an option, it should be the default.

**Comment by lanselin** [comment]
Actually, my comment did not pertain to the display precision, which indeed does not work. My comment was about the listing of the statistics, which gives the ranges as 1.000 to 2.000, instead of 1 to 2, as it was before (and as it should be).

Since the display precision is disabled (which is a good idea for the connectivity histogram), it should be greyed out on the interface. Currently, it is not. It is available, but it doesn't do anything (never a good idea).

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.107
Verified
<img width="634" alt="8 mar 10" src="https://user-images.githubusercontent.com/36253697/37164227-9e791bce-22f1-11e8-8f8e-03767b41e9f4.PNG">

**Comment by jkoschinsky** [comment]
Verified Geoda 107
OSX
