### ISSUE TITLE
connectivity map selects polygons within polygons

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1585]
V 1.12.1.99

The new connectivity map is supposed to select the neighbors of the observation over which the pointer is located. However, there seems to be an edge case where the neighbor selection is incorrect. The case occurs for counties in Virginia (this happens to be an example in the lab notes) where not only the neighboring counties are selected (i.e., highlighted), but also the "city counties" that are within those counties. However, those city counties are NOT neighbors of the selected county, they are just within counties that are.  See the screen shot below: the small polygons within the larger polygons should not be shown as "neighbors".

<img width="249" alt="screen shot 2018-03-02 at 1 42 50 pm" src="https://user-images.githubusercontent.com/4008351/36923391-0c522b08-1e20-11e8-91d7-deb1f2b780fe.png">

**Comment by lanselin** [comment]
The connectivity graph does this correctly. Note how there are no yellow lines to the 
city counties within the larger county,

<img width="356" alt="screen shot 2018-03-02 at 2 11 20 pm" src="https://user-images.githubusercontent.com/4008351/36924592-162958dc-1e24-11e8-8ed2-33259b9f0104.png">

**Comment by lixun910** [comment]
v101  introduce the fill color of the neighbors to fix this issue.
<img width="271" alt="screen shot 2018-03-05 at 2 33 07 pm" src="https://user-images.githubusercontent.com/2423887/37000956-3ec251ee-2082-11e8-9e26-7c81bd607ef6.png">
<img width="433" alt="screen shot 2018-03-05 at 2 32 35 pm" src="https://user-images.githubusercontent.com/2423887/37000961-401a970e-2082-11e8-9b4a-3e4d78797cbb.png">

**Comment by lanselin** [comment]
Not sure this is the right fix. The real issue is that the city counties inside the neighbors
seem to be identified as neighbors, whereas they are not. Why are they drawn when only
the actual neighbors should be drawn?

**Comment by lixun910** [comment]
It is caused by the transparent fill when draw the neighbors with such "inside city county", so one can't distinguish which one is the neighbor or not.

Here is another screenshot (fill the neighbors with red color), which is the same with the above "connectivity graph":
<img width="837" alt="screen shot 2018-03-05 at 3 22 27 pm" src="https://user-images.githubusercontent.com/2423887/37003175-65fcdf3e-2089-11e8-8f92-73c72b842814.png">

**Comment by lanselin** [comment]
OK, I see, so it’s not that the little islands are drawn as such, just the holes in the big counties!

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.101
Verified 

![21](https://user-images.githubusercontent.com/36253697/37053646-9cfb160e-2174-11e8-9b03-c1df3ad3ca32.JPG)
