### ISSUE TITLE
connectivity map has wrong ID value

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1586]
V 1.12.1.99

When hovering above a location, the connectivity map shows an observation value in the status bar that does not correspond with the ID variable used in the weights. See below, how the old connectivity map shows the ID as 51003, the actual FIPS number, whereas the new map shows 1409, which is the polyid. However, polyid was not used for the weights, but fipsno was.

The connectivity map should show the observation number that matched the ID used in the weights.

<img width="781" alt="screen shot 2018-03-02 at 1 56 47 pm" src="https://user-images.githubusercontent.com/4008351/36924034-fe7c1faa-1e21-11e8-95f3-71aeb8d6792f.png">

<img width="413" alt="screen shot 2018-03-02 at 1 56 58 pm" src="https://user-images.githubusercontent.com/4008351/36924036-02defe8c-1e22-11e8-9708-d83ed0653e53.png">

<img width="551" alt="screen shot 2018-03-02 at 1 56 13 pm" src="https://user-images.githubusercontent.com/4008351/36924044-09d57f72-1e22-11e8-81a0-7a4067aee055.png">

**Comment by jkoschinsky** [comment]
GeoDa 1.99
MacOSX
Not fixed yet in 1.99 (see screenshot below):

<img width="1343" alt="screen shot 2018-03-05 at 1 32 51 pm" src="https://user-images.githubusercontent.com/13679743/36995505-d66e86ec-2079-11e8-8d91-a1e51f72ddf7.png">

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.107
Verified 
![8 mar 09](https://user-images.githubusercontent.com/36253697/37163713-5765891c-22f0-11e8-96e8-1096a13cd253.JPG)

**Comment by jkoschinsky** [comment]
GeoDa 107
Mac OSX

Something still isn't right with the IDs, e.g. sometimes you get the correct result as below (1 neighbor):

<img width="1091" alt="screen shot 2018-03-08 at 6 06 59 pm" src="https://user-images.githubusercontent.com/13679743/37183464-d1b51aec-22fb-11e8-8d3b-38d3ad79537c.png">

but sometimes you get a wrong result, like here, where the same selection is now listed with 32 neighbors, which is incorrect:

<img width="1170" alt="screen shot 2018-03-08 at 6 07 21 pm" src="https://user-images.githubusercontent.com/13679743/37183488-ea852c60-22fb-11e8-9076-0e39b7fa5f80.png">

**Comment by lixun910** [comment]
@jkoschinsky I can't replicate this. Can you verify it again? especially when the mouse point hovering on other point after select one point? because the neighboring information on the status bar is for hovering.

**Comment by lanselin** [comment]
See also #1597. This seems to be a problem for point layers.  The ID referred to in the status bar refers to the currently active weights, not to the weights for which the connectivity graph is constructed. This is not right. We set up different behavior for a regular map (always use the currently active weights) and the connectivity map/graph, always tied to the weights from which they were generated. So, changing the active weights should not affect the IDs and neighbors for a given connectivity map/graph. As far as I can tell, it works for polygons, but not for points, but this may have just been luck.

**Comment by jkoschinsky** [comment]
My steps:

1. open Baltimore and select the one record shown in the screenshot above
2. load weights, open connectivity map and select same record
3. get wrong ID and neighbor info:

<img width="599" alt="screen shot 2018-03-09 at 10 59 55 am" src="https://user-images.githubusercontent.com/13679743/37219452-0f1c4a08-2389-11e8-94ea-3ee8a6aebd10.png">

The ID and neighbors keep changing, too (mostly wrong).

**Comment by lixun910** [comment]
v109

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.109

The rook weights does not match with the Julia’s result, but the threshold distance weights matches with Julia’s results. 
<img width="930" alt="9 mar 01" src="https://user-images.githubusercontent.com/36253697/37232289-4b628830-23e6-11e8-8c03-1b944dcdc1d3.PNG">
<img width="836" alt="9 mar 02" src="https://user-images.githubusercontent.com/36253697/37232290-4b78e940-23e6-11e8-84e9-8d459b8ebd93.PNG">

Created connectivity map/graph depend on the weights creating them; does not depend on the active weights. 
<img width="786" alt="9 mar 03" src="https://user-images.githubusercontent.com/36253697/37232287-4b232776-23e6-11e8-8c02-892ea1c00e58.PNG">

The result from reloading weights is the same with the original one. 
<img width="848" alt="9 mar 04" src="https://user-images.githubusercontent.com/36253697/37232288-4b42ede0-23e6-11e8-9cc5-e7766a636726.PNG">

When hang over other point, the neighboring information on the status bar updated according to the points being hanged over. 
![9 mar 05](https://user-images.githubusercontent.com/36253697/37232347-8c05d540-23e6-11e8-8d92-261844248650.JPG)

**Comment by lixun910** [comment]
Yes, this is correct. Different connectivity graphs should show different
neighbors in different map windows since there weights are different.

**Comment by lanselin** [comment]
Right, this is the desired behavior.

**Comment by jkoschinsky** [comment]
Fix verified in Geoda 111
Mac OSX

<img width="599" alt="screen shot 2018-03-11 at 5 06 01 pm" src="https://user-images.githubusercontent.com/13679743/37259011-8f892122-254e-11e8-9329-a747839882cb.png">
