### ISSUE TITLE
connectivity map does not show the number and IDs of the neighbors

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1587]
V 1.12.1.99

The new connectivity map does not show the number and IDs of the neighbors in the status bar. This needs to be added, otherwise it is not a "connectivity map". Compare the status bar for the old and the new.

<img width="413" alt="screen shot 2018-03-02 at 1 56 58 pm" src="https://user-images.githubusercontent.com/4008351/36924148-69018928-1e22-11e8-9808-0d091a07d8ec.png">

<img width="781" alt="screen shot 2018-03-02 at 1 56 47 pm" src="https://user-images.githubusercontent.com/4008351/36924153-6dea3278-1e22-11e8-82eb-b32117ca06cd.png">

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.107

![8 mar 07](https://user-images.githubusercontent.com/36253697/37162923-6a1aecb6-22ee-11e8-81b5-89cab7327bf4.JPG)

**Comment by jkoschinsky** [comment]
Verified Geoda 107
OSX
