### ISSUE TITLE
contiguity weights can be created without option selected

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1589]
V 1.12.1.99

It seems possible to create a contiguity weights file without having the rook/queen button checked (see screen shot). The created file seems to be rook, although it is difficult to verify (this is what the properties state). It should NOT be possible to create a weights file without an explicit button being checked.

<img width="921" alt="geodascreensnapz787" src="https://user-images.githubusercontent.com/4008351/36947261-4b312036-1f7e-11e8-89a7-62e82f8f94a5.png">

<img width="373" alt="screen shot 2018-03-04 at 7 30 26 am" src="https://user-images.githubusercontent.com/4008351/36947274-549ae4d6-1f7e-11e8-89e2-dcc2430004df.png">

**Comment by lixun910** [comment]
see fix in 43dd418

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.101
The queen button is checked by default.

<img width="388" alt="20" src="https://user-images.githubusercontent.com/36253697/37051995-da9a8e36-216f-11e8-8324-193e6308da00.PNG">
