### ISSUE TITLE
inconsistency in project file for loaded weights

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1590]
V 1.12.1.99

When weights are loaded (i.e., not created in the current project) and then a Project File is created, the information on the symmetry of the weights is incorrect. Whereas the loaded weights give their symmetry as unknown

<img width="398" alt="screen shot 2018-03-04 at 5 22 30 pm" src="https://user-images.githubusercontent.com/4008351/36953630-167995be-1fd1-11e8-9231-56fa75aa0742.png">

the gda project file has it listed as asymmetric

<img width="530" alt="screen shot 2018-03-04 at 5 21 41 pm" src="https://user-images.githubusercontent.com/4008351/36953643-2835d1aa-1fd1-11e8-9448-18aa3b6c8a7a.png">

After loading that gda file, the symmetry is given as asymmetric, whereas it should be unknown.

<img width="363" alt="screen shot 2018-03-04 at 5 23 37 pm" src="https://user-images.githubusercontent.com/4008351/36953656-42e30676-1fd1-11e8-9097-22cb8f7ac351.png">

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.107
Verified 

When loading a weights:
<img width="376" alt="8 mar 03" src="https://user-images.githubusercontent.com/36253697/37160394-06b572a0-22e8-11e8-885e-f1a78ee3f78b.PNG">

Reopen a weights in a saved project file: 
<img width="869" alt="8 mar 04" src="https://user-images.githubusercontent.com/36253697/37160429-19363540-22e8-11e8-8ffc-ba011f931d40.PNG">

**Comment by jkoschinsky** [comment]
Verified Geoda 107
OSX
