### ISSUE TITLE
connectivity graph doesn't show for points

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1593]
When clicking on the connectivity graph button for a point layer (distance-based weights), only the points are mapped. Similarly, when selecting Connectivity > Show Graph for a point layer, only the points are there.

**Comment by lixun910** [comment]
v105

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.107
Verified 
<img width="894" alt="8 mar 02" src="https://user-images.githubusercontent.com/36253697/37158301-faadd132-22e2-11e8-9fc7-15ac74432a80.PNG">

**Comment by jkoschinsky** [comment]
Verified Geoda 107
OSX
