### ISSUE TITLE
Crash: Postgresql DB connection

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1594]
From: 
 Details:
os: 3-4-4
vs: 1-12-1-57
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
In GdaFrame::OnHelpAbout()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:PG:dbname='dmag_domotex_data' 
Open Layer:data_2018_01_14
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
PG:dbname='dmag_domotex_data' 
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate

**Comment by jkoschinsky** [comment]
@lixun910 can you tell what database format they're trying to open here so we can try to replicate?

**Comment by lixun910** [comment]
This report is from the case GeoDa connecting to a Postgresql database using GEoDa 1.12.1.57 on Ubuntu 16.04.  

There are many cases that might cause GeoDa close unexceptionally: e.g. db server is not reachable (network issue, wrong ip address, etc.), a spatial table is too slow to load in GeoDa -- these will cause GeoDa hanging and one needs to kill it (force quite) to restart GeoDa.

**Comment by lixun910** [comment]
Tested using GeoDa 1.14 and Ubuntu 16.04 and Ubuntu 18.04, with a local Postgresql database server. No crash can be replicated.
