### ISSUE TITLE
connectivity graph not tied to weights listed in window header

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1596]
V 107

This may just be an issue for point layers, but the connectivity graph is updated to the currently active weights, not the weights file listed in the header.

For example, for Cleveland in the attached graph for the distance band, the number of neighbors are indicated in the status bar that pertain to the currently active weights, in this case based on queen contiguity for Thiessen polygons.

So, the pointer shows 40925 as having 6 neighbors, whereas it clearly only has one.

<img width="660" alt="geodascreensnapz835" src="https://user-images.githubusercontent.com/4008351/37177266-eeeaffe6-22ec-11e8-8726-b880f5ce89d2.png">

**Comment by lixun910** [comment]
v109

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.109
Verified 
The number of neighbors indicated in the status bar are pertain to the creating weights (listed in the header). It does not depend on the active weights. 

<img width="752" alt="9 mar 09" src="https://user-images.githubusercontent.com/36253697/37234093-c0e6bafc-23ed-11e8-99d7-af3faa833457.PNG">

**Comment by jkoschinsky** [comment]
fix confirmed
GeoDa v 111
OSX
