### ISSUE TITLE
inconsistency between connectivity histogram and connectivity graph

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1597]
V 107

There seems to be something wrong in the linking between the connectivity histogram and the connectivity graph for the same weights. In the example, I click on the right-most bar in the connectivity histogram, the one location with 85 neighbors, but while the connectivity graph selects the proper location and its neighbors, the status bar has the wrong location identified (and the wrong number of neighbors).

<img width="1322" alt="screen shot 2018-03-08 at 9 02 40 pm" src="https://user-images.githubusercontent.com/4008351/37186626-78481004-2314-11e8-86b1-e052e70faaac.png">

**Comment by jkoschinsky** [comment]
see also https://github.com/GeoDaCenter/geoda/issues/1586

**Comment by lixun910** [comment]
V109

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.109
Verified in both polygon and points maps.

<img width="903" alt="9 mar 07" src="https://user-images.githubusercontent.com/36253697/37232963-3531eeae-23e9-11e8-919f-9da5145a9bf4.PNG">


<img width="912" alt="9 mar 06" src="https://user-images.githubusercontent.com/36253697/37232964-3553634a-23e9-11e8-8d25-6e2ae0476b47.PNG">

**Comment by jkoschinsky** [comment]
GeoDa v111
Mac OSX
Fix verified
