### ISSUE TITLE
Why use a wxWidgets built in unicode?

### ISSUE THREAD

**Issue by HPDell** [GeoDaCenter/geoda#1598]
Hi,

I found that  GeoDa is configured to use multibyte charset mode. And it need a header file of wxWidgets at `%wxWidgets_HOME%\lib\mswd\setup.h` that means GeoDa need not to be built in unicode mode. But the two additional dependency `wxmsw31ud.lib` and `wxmsw31ud_gl.lib` are built in unicode mode. Why two Unicode static library go with a non-unicode header file?

**Comment by lixun910** [comment]
Wxwidgets with Unicode support is for internationalization (multi charset).
In GeoDa, wxwidgets has to be compiled with Unicode enabled.

**Comment by HPDell** [comment]
Well, can I build GeoDa with Unicode support and include `setup.h` in the `mswud` folder? I have tried, but an error occured which means I can't build GeoDa with Unicode enabled. I have tried to build it without Unicode endabled but also failed.

I built them in serval ways, but they all failed.

| GeoDa Unicode option | wxWidgets Unicode option | Error |
| ----------------------- | --------------------------- | ----- |
| Enabled | Enabled | Missing some lib whose name ended with `d` not `ud`, and some other errors which is raised by Unicode  |
| Enabled | Disabled | Missing `mswud\setup.h`; LPCTSTR and LPSTR convert error. |
| Disabled | Enabled | Missing `mswd\setup.h` |
| Disabled | Disabled | LPCTSTR and LPSTR convert error. |

So how to build GeoDa and wxWidgets? 

Is it a better way to build them with MinGW32 or MinGW64?

**Comment by lixun910** [comment]
You should go with your first option.  Please see an example of how to compile wxwidgets on windows platform with visual studio in https://github.com/GeoDaCenter/geoda/blob/0fdd3741a07e513f80b6a0590a455afe871ed38b/BuildTools/windows/build.bat#L690 <https://github.com/GeoDaCenter/geoda/blob/0fdd3741a07e513f80b6a0590a455afe871ed38b/BuildTools/windows/build.bat#L690>

An example of compiling command:
nmake -f makefile.vc UNICODE=1 SHARED=1 RUNTIME_LIBS=dynamic MONOLITHIC=1 USE_OPENGL=1 USE_POSTSCRIPT=1 TARGET_CPU=AMD64

MinGW is not recommended.

**Comment by HPDell** [comment]
Thanks. I will try.

I am busy at other works now. Sorry to relpy so late.
