### ISSUE TITLE
Crash with grouped variables

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#1599]
GeoDa 1.12.1.107
Windows 8
I attempted to create custom breaks with time-grouped variables and got a crash. 
Some of the variables in the group had blank values which may have contributed to the crash. Logger text attached below. 
[logger.txt](https://github.com/GeoDaCenter/geoda/files/1800631/logger.txt)

**Comment by YidanJ-Wu** [comment]
Crashed again (same file) when creating custom breaks with time-grouped variables. 
Logger text attached below.
[logger.txt](https://github.com/GeoDaCenter/geoda/files/1800663/logger.txt)

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.137
Verified

<img width="729" alt="screen shot 2018-06-15 at 4 46 27 pm" src="https://user-images.githubusercontent.com/37029239/41490919-d5d20e88-70bb-11e8-8787-0111c5617f49.png">
