### ISSUE TITLE
table calculator dialog does not reflect current columns

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1600]
It seems that the table "insert variable" dialog is not updated with the current state of the variables in the table. In my example below, the order of the variables has been changed in the table, but this order is not shown in the drop down list of where to insert the variable. These should be synchronized.

drop down list:
<img width="163" alt="screen shot 2018-03-11 at 2 55 40 pm" src="https://user-images.githubusercontent.com/4008351/37258929-9f48257a-253c-11e8-9701-9769a002cd67.png">

current state of the table

<img width="1163" alt="screen shot 2018-03-11 at 2 55 48 pm" src="https://user-images.githubusercontent.com/4008351/37258930-ac68f16c-253c-11e8-9387-5275975794d9.png">

**Comment by luluzhou766** [comment]
Win 10, 64bit
Geoda 1.12.1.131
the Order is Verified (first picture)

Originally I wanted to use Cleverland data to test it
but I could not open the Cleveland data in Windows (second picture)
the data can be open in Mac (third picture)

![img_0949](https://user-images.githubusercontent.com/36253697/39415474-58aab934-4c33-11e8-9852-c103365e389f.jpg)
![01](https://user-images.githubusercontent.com/36253697/39415488-8464891a-4c33-11e8-9b2b-28a8b2160500.PNG)

![01](https://user-images.githubusercontent.com/36253697/39415510-c0749da0-4c33-11e8-9a52-344283da7e74.png)

**Comment by jkoschinsky** [comment]
Works in in GeoDa 1.12.1.137 (OSX High Sierra, 10.13.4).
