### ISSUE TITLE
table delete and rename columns inconsistency

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1603]
Noticed something strange in the table manipulations. After a variable/column is deleted, and one of the remaining variables is renamed to the original variable name, the values revert to the originally "deleted" values, not to the values for the renamed variable.

Here is an example. Variables are X, X1, Y, Y1

<img width="456" alt="screen shot 2018-03-12 at 5 01 46 pm" src="https://user-images.githubusercontent.com/4008351/37315566-8d089fe4-2617-11e8-93be-fa921ead6521.png">

Now, X and Y are deleted, X1 and Y1 remain

<img width="246" alt="screen shot 2018-03-12 at 5 02 13 pm" src="https://user-images.githubusercontent.com/4008351/37315580-9b60aa1e-2617-11e8-96d6-1ea2d57f2365.png">

Now X1 is renamed to X and Y1 is renamed to Y, they take on the old values of X and Y, they do not keep their current values.

<img width="244" alt="screen shot 2018-03-12 at 5 02 40 pm" src="https://user-images.githubusercontent.com/4008351/37315603-b9b3e7d8-2617-11e8-9ef3-017b47838d3d.png">

**Comment by jkoschinsky** [comment]
Works in in GeoDa 1.12.1.137 (OSX High Sierra, 10.13.4).
