### ISSUE TITLE
Update language

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1607]
from Luc:

This is a quick fix that maybe you could include into the next build.
There is some inconsistency in the terminology used in the menu
for the local spatial autocorrelation statistics.

This is how it should be:

- Univariate Local Moran’s I
- Bivariate Local Moran’s I
- Differential Local Moran’s I
- Local Moran’s I with EB Rate

(keep as is)

- Local G
- Local G*

(remove the cluster map part)

- Univariate Local Join Count
- Bivariate Local Join Count

(add univariate to the first one)

- Univariate Local Geary
- Multivariate Local Geary

(remove the cluster map part)

Also, “Nonparametric Spatial Autocorrelation” should become “Spatial Correlogram”.

**Comment by luluzhou766** [comment]
Win 10, 64bit
Geoda 1.12.1.131
Verified
![img_0947](https://user-images.githubusercontent.com/36253697/39414748-c5cffa96-4c2a-11e8-8dea-4437e0707c96.jpg)

![img_0948](https://user-images.githubusercontent.com/36253697/39414756-c7287ae4-4c2a-11e8-93a0-6ca942159686.jpg)
