### ISSUE TITLE
Crash：Regression [when more than 5 'Covariates']

### ISSUE THREAD

**Issue by womb2tomb** [GeoDaCenter/geoda#1611]
[Shapefile.zip](https://github.com/GeoDaCenter/geoda/files/1833069/Shapefile.zip)
[logger.txt](https://github.com/GeoDaCenter/geoda/files/1833070/logger.txt)

When I set 6 or more variables for 'Covariates'，the program crashed immediately.
But it will run successfully if the variables for 'Covariates' are less than 6.
I uploaded my data and log file, hope it will help you to find the problem.

**Comment by womb2tomb** [comment]
I have found the problem:
if I set 6 variables for 'Covariates', the 'Degrees of Freedom' will be less than 0, because I have just 6 observations.

The program should warn the user about this when setting varibles.

**Comment by lixun910** [comment]
@womb2tomb Thanks for reporting this crash!  Will fix this and give you an update.

Yes, to run the regression successfully, the number of covariates should be more than the number of observations.

**Comment by jkoschinsky** [comment]
and you want a larger sample size  (e.g. at least 30) to run a regression

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.137
Verified
<img width="420" alt="6 variables selected error message" src="https://user-images.githubusercontent.com/37029239/41435924-e6015894-6fe5-11e8-8329-4ed12bdac278.png">
<img width="471" alt="6 variables selected" src="https://user-images.githubusercontent.com/37029239/41435925-e614730c-6fe5-11e8-91da-7c19cdc09f96.png">
