### ISSUE TITLE
add lowess options to spatial correlogram

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1612]
As it stands, the LOWESS smoother in the spatial correlogram uses the default settings, but there is no way to change that. It would make sense to have the same customization options as for the generic LOWESS.

**Comment by luluzhou766** [comment]
Win 10, 64bit
Geoda 1.12.1.129
Verified
![img_0943](https://user-images.githubusercontent.com/36253697/39361239-0ee2c7fc-4a11-11e8-84e3-4e8c142e111f.JPG)

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.12.1.133 OSX
