### ISSUE TITLE
problem with grouped variables in bivariate moran scatter plot

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1614]
V 115

There seems to be something wrong when grouped variables are used for the bivariate Moran scatterplot. This used to work (see lab notes). However, now, the graph has very strange scales, see below.

<img width="598" alt="screen shot 2018-03-22 at 8 03 26 am" src="https://user-images.githubusercontent.com/4008351/37778736-ed0b250a-2da7-11e8-9237-dd2c2bb6f8ee.png">

The calculated Moran's I is correct, but the graph is not on the right scale. Contrast this with the result when the variables are specified explicitly (i.e., without grouping).

<img width="594" alt="screen shot 2018-03-22 at 8 02 41 am" src="https://user-images.githubusercontent.com/4008351/37778809-1845f7d6-2da8-11e8-9d23-dbebeee913ae.png">

This is the same as how it used to be for the grouped variables, for example in the lab notes:

<img width="613" alt="screen shot 2018-03-22 at 8 03 41 am" src="https://user-images.githubusercontent.com/4008351/37778829-271e19dc-2da8-11e8-8f68-5ea57caa81f4.png">

**Comment by lanselin** [comment]
the same axes problem occurs for the regular Moran scatter plot for grouped variables as well.

<img width="599" alt="screen shot 2018-03-22 at 10 16 13 am" src="https://user-images.githubusercontent.com/4008351/37786568-429bc27e-2dba-11e8-95b0-5430ddc56d01.png">

**Comment by lanselin** [comment]
it seems to have to do with the y-axis, i.e., for the spatially lagged variables

**Comment by lixun910** [comment]
yes, I noticed that. Am checking and fixing all related functions with group variables.

**Comment by jkoschinsky** [comment]
Works in in GeoDa 1.12.1.137 (OSX High Sierra, 10.13.4).
