### ISSUE TITLE
read arcgis spatial weights file (.swm) -- binary 

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1617]
ref: https://github.com/pysal/pysal/blob/master/pysal/core/IOHandlers/arcgis_swm.py

 Opens, reads, and writes weights file objects in ArcGIS swm format.
    Spatial weights objects in the ArcGIS swm format are used in
    ArcGIS Spatial Statistics tools.
    Particularly, this format can be directly used with the tools under
    the category of Mapping Clusters.

    The values for [ORG_i] and [DST_i] should be integers,
    as ArcGIS Spatial Statistics tools support only unique integer IDs.
    For the case where a weights object uses non-integer IDs,
    ArcGISSwmIO allows users to use internal ids corresponding to record numbers,
    instead of original ids.

    The specifics of each part of the above structure is as follows.
  .. table:: ArcGIS SWM Components

| Part    | Data type          |  Description                   | Length    |
|-------|----------------|------------------------|----------|                   
| ID_VAR_NAME | ASCII TEXT|  ID variable name      |               Flexible (Up to the 1st ;)    |
|ESRI_SRS   |  ASCII TEXT  |ESRI spatial reference system|        Flexible (Btw the 1st ; and \\n)  |
|NO_OBS    |   l.e. int  |  Number of observations   |            4        |                 
|     ROW_STD   |   l.e. int    Whether or not row-standardized      4                         
|     WGT_i    |                                                                               
|     ORG_i     |   l.e. int  |  ID of observaiton i         |         4         |                
|     NO_NGH_i    | l.e. int    |Number of neighbors for obs. i (m) |  4    |                     
|     NGHS_i    |                                                                              
|     DSTS_i   |    l.e. int   | IDs of all neighbors of obs. i     |  4*m     |                  
|     WS_i     |    l.e. float  |Weights for obs. i and its neighbors |8*m   |                    
|     W_SUM_i    |  l.e. float | Sum of weights for "    |             8    |

**Comment by lixun910** [comment]
possible issue of the swm format: multi-language support 
e.g. ID variable name, the default data type is ASCII text

**Comment by lixun910** [comment]
Here is the dataset for testing:
[test_dataset.zip](https://github.com/GeoDaCenter/geoda/files/1896526/test_dataset.zip)

**Comment by YidanJ-Wu** [comment]
Windows 8 
1.12.1.119
Recognizes the .swm file format, but I got this error message when loading virginia_queen.swm
![image](https://user-images.githubusercontent.com/22801047/38655506-b3570b7e-3dda-11e8-8c54-13cd3b870149.png)

![image](https://user-images.githubusercontent.com/22801047/38655494-9c2a22b0-3dda-11e8-9734-235b61d1997b.png)

**Comment by lixun910** [comment]
This is not ready in v119. Will send out a new build of v121 soon.

**Comment by jkoschinsky** [comment]
Please test in ArcGIS desktop or ArcGIS Pro:

Using ArcGIS's weights functionality:
try different weights and make sure they can be read into GeoDa v. 121
— .swm: is GeoDa's code robust to different versions of swm (with and without IDs)
—are there any other native weights formats that ArcGIS uses besides swm

**Comment by YidanJ-Wu** [comment]
Geoda 1.12.1.131
Windows 8
SWM and MAT from the test file work in Local Morans, Local Geary, and various cluster functions. Will test further in arcgis pro.

**Comment by YidanJ-Wu** [comment]
GeoDa 1.12.1.133
Windows 8
Created a SWM file in ArcGIS Pro, loaded in GeoDa and got the same error message. 
![image](https://user-images.githubusercontent.com/22801047/39729517-f03133fc-5221-11e8-8111-72e2a8a4cab9.png)
![image](https://user-images.githubusercontent.com/22801047/39729530-01f775c4-5222-11e8-99d0-40a48cc90b2f.png)

**Comment by lixun910** [comment]
Can you share the Swm file? Thanks!

**Comment by YidanJ-Wu** [comment]
I've included the .swm files in the .zip folder

**Comment by YidanJ-Wu** [comment]
GeoDa 1.12.1.137

.swm files created in ArcGIS Pro are now working correctly.
