### ISSUE TITLE
table calculator - problem with grouped variables

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1623]
It seems that there is something wrong after a given time period has been selected for a grouped variable in a calculator operation, i.e., after the box for "all times" has been changed to a given value. The value seems to be stuck to the value chosen in the previous operation. In the example below, I first standardized HR for 90, and then tried to do it for 80, but the time selector was stuck at 90 and greyed out.

<img width="746" alt="screen shot 2018-04-03 at 4 33 45 pm" src="https://user-images.githubusercontent.com/4008351/38277265-6f4b303c-375d-11e8-80f6-3b9f7edcec9f.png">

The only way to change it seems to be to close the calculator interface and start over.

**Comment by lanselin** [comment]
This may be specific to univariate or standardization, since the spatial lag works fine. I didn't check the other options.

**Comment by lanselin** [comment]
Same issue seems to happen when carrying out a bivariate operation. See below, the values below the selected variable are greyed out and cannot be changed.

<img width="745" alt="screen shot 2018-04-03 at 6 09 29 pm" src="https://user-images.githubusercontent.com/4008351/38280323-5954e16c-376a-11e8-88f5-27ea2059140e.png">

**Comment by lixun910** [comment]
v119

**Comment by luluzhou766** [comment]
Win 10, 64bit
Geoda 1.12.1.129
Verified

![img_0936](https://user-images.githubusercontent.com/36253697/39350342-6a7f7c46-49ed-11e8-801d-bd97854bac70.JPG)

![img_0937](https://user-images.githubusercontent.com/36253697/39350350-6f8d94ac-49ed-11e8-8bec-00f66b57adcc.JPG)

![img_0938](https://user-images.githubusercontent.com/36253697/39350355-73c33c66-49ed-11e8-9d5b-94e2ef9086e3.JPG)

![img_0939](https://user-images.githubusercontent.com/36253697/39350365-7d0591ca-49ed-11e8-8fd7-c0dde2f15a5b.JPG)

![img_0940](https://user-images.githubusercontent.com/36253697/39350627-3ab914d0-49ee-11e8-85c2-5e69387b56ef.JPG)
![img_0941](https://user-images.githubusercontent.com/36253697/39350632-3e44928c-49ee-11e8-86c8-6b3f172ce8e6.JPG)
