### ISSUE TITLE
differential moran's I - randomization doesn't seem to work

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1624]
The randomization option for the differential Moran's I (with grouped variables) doesn't seem to work right. The scatter plot is fine, but first the randomization crashed (see crash report). Then, upon restarting GeoDa it doesn't crash, but yields a nonsensical result (see below).

<img width="516" alt="screen shot 2018-04-03 at 6 00 46 pm" src="https://user-images.githubusercontent.com/4008351/38280132-4f84d3a0-3769-11e8-9f5e-6726f13047ab.png">

**Comment by lanselin** [comment]
btw, this used to work fine (current version is 117).

**Comment by lixun910** [comment]
v119

**Comment by luluzhou766** [comment]
Win 10, 64bit
Geoda 1.12.1.129
Verified 
![01](https://user-images.githubusercontent.com/36253697/39348001-d3028c26-49e4-11e8-854d-c1d086dc84bf.PNG)

![02](https://user-images.githubusercontent.com/36253697/39348011-dc904d5a-49e4-11e8-87d9-a70420506119.PNG)

**Comment by jkoschinsky** [comment]
Works in in GeoDa 1.12.1.137 (OSX High Sierra, 10.13.4).

But the lines for 999 permutations are all stacked on top of each other so you can't see the full distribution like you used to. Can we change this back, e.g. by reducing the scale of the X-axis?

**Comment by lixun910** [comment]
@jkoschinsky you can make the window larger to see more details of the distribution.

<img width="519" alt="screen shot 2018-07-05 at 10 56 25 am" src="https://user-images.githubusercontent.com/2423887/42339560-2e19896e-8042-11e8-98b8-d1e299ca6ef9.png">
<img width="902" alt="screen shot 2018-07-05 at 10 56 41 am" src="https://user-images.githubusercontent.com/2423887/42339567-3324ac0e-8042-11e8-9f48-742f967e72f5.png">
<img width="1082" alt="screen shot 2018-07-05 at 10 56 55 am" src="https://user-images.githubusercontent.com/2423887/42339572-370d75ee-8042-11e8-8646-7feebcff93b5.png">

**Comment by VeraB620** [comment]
OS X El Capitan 10.11.6
GeoDa 1.12.1.141

Verified, no problems!
<img width="1043" alt="screen shot 2018-07-05 at 2 34 03 pm" src="https://user-images.githubusercontent.com/4943475/42344060-c167f930-8060-11e8-9a90-aa7528bb069d.png">
<img width="956" alt="screen shot 2018-07-05 at 2 34 35 pm" src="https://user-images.githubusercontent.com/4943475/42344061-c22b8198-8060-11e8-92a7-86c1690b92e2.png">
