### ISSUE TITLE
read Matlab .MAT weights file

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1625]

**Comment by lixun910** [comment]
Here is the dataset for testing:
[test_dataset.zip](https://github.com/GeoDaCenter/geoda/files/1896526/test_dataset.zip)

**Comment by lixun910** [comment]
this will be in v121

**Comment by jkoschinsky** [comment]
Please test some of the matlab files from the links below in GeoDa v121:

http://www.spatial-econometrics.com/html/datasets.zip
http://www.spatial-econometrics.com/html/spexamples.zip

**Comment by YidanJ-Wu** [comment]
Windows 8 
1.12.1.121
Opened .mat weight files in GeoDa. Ran Local Morans I, K means clusters, with no issues. For the Matlab files from spatial-econometrics.com, do they need to be converted before opening in GeoDa?
