### ISSUE TITLE
Crash Report: Test table merge

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1629]
From: [
 Details:
os: 3-4-13
vs: 1-10-0-8
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/edog/Desktop/Hilmara/shp modified.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
Open MergeTableDlg.
In TableFrame::OnActivate
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/edog/Desktop/MAPAHILMARA.csv
Open Layer:MAPAHILMARA
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
ds:/home/edog/Desktop/MAPAHILMARA.csv layer: MAPAHILMARA
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnExclListDClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnExclListDClick()
Entering MergeTableDlg::OnIncOneClick()
In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnMergeClick()
In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnMergeClick()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
In TableFrame::OnActivate
In TableFrame::OnActivate
Open DataViewerAddColDlg.
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnEditDecimals()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
Open FieldNewCalcSheetDlg.
In FieldNewCalcSheetDlg::OnPageChange()
In TableFrame::OnActivate
In FieldNewCalcSheetDlg::OnPageChange()
In FieldNewCalcSheetDlg::OnPageChange()
Open DataViewerAddColDlg.
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
Entering DataViewerAddColDlg::OnOkClick
Inserting new column RATEDIRETA into Table
In TableFrame::OnActivate
In TableFrame::OnActivate
In FieldNewCalcSheetDlg::OnPageChange()
In FieldNewCalcSheetDlg::OnApplyClick()
In TableFrame::OnActivate
In TableFrame::OnActivate
In FieldNewCalcSheetDlg::OnPageChange()
In FieldNewCalcSheetDlg::OnPageChange()
In FieldNewCalcSheetDlg::OnApplyClick()
In FieldNewCalcSheetDlg::OnApplyClick()
In FieldNewCalcSheetDlg::OnApplyClick()
In FieldNewCalcSheetDlg::OnApplyClick()
In FieldNewCalcSheetDlg::OnApplyClick()
In FieldNewCalcSheetDlg::OnApplyClick()
In TableFrame::OnActivate
Open DataViewerDeleteColDlg.
In TableFrame::OnActivate
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnDelete()
RATEDIRETA
In TableFrame::OnActivate
In TableFrame::OnActivate
In GdaFrame::OnOpenPercentile()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
DIRETA
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
field_18
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
In GdaFrame::OnOpenSpatialRate()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
In GdaFrame::OnOpenRawrate()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
INDIRETA
field_18
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In MapFrame::OnMapBasemap()
Click GdaFrame::OnSetBasemap8
In MapFrame::OnMapBasemap()
Click GdaFrame::OnSetBasemap7
Open ExportDataDlg in its Init()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
MapCanvas::~MapCanvas()
In TableFrame::OnActivate
In TableFrame::OnActivate
In GdaFrame::OnOpenRawrate()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
DIRETA
field_18
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
In TableFrame::OnActivate
In MapFrame::OnMapBasemap()
Click GdaFrame::OnSetBasemap7
In MapFrame::OnMapBasemap()
Click GdaFrame::OnSetBasemap1
In MapFrame::OnMapBasemap()
Click GdaFrame::OnSetBasemap7
In GdaFrame::OnSaveCategories()
MapCanvas::OnSaveCategories()
In TableFrame::OnActivate
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
PNG selected
In TableFrame::OnActivate
In TableFrame::OnActivate
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/edog/Desktop/Hilmara/shp modified.shp
Open Layer:shp modified
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
ds:/home/edog/Desktop/Hilmara/shp modified.shp layer: shp modified
Entering MergeTableDlg::OnExclOneClick()
Entering MergeTableDlg::OnExclOneClick()
Entering MergeTableDlg::OnExclOneClick()
Entering MergeTableDlg::OnExclOneClick()
Entering MergeTableDlg::OnExclOneClick()
Entering MergeTableDlg::OnIncOneClick()
In MergeTableDlg::OnMergeClick()
Open FieldNameCorrectionDlg:
ScrolledWidgetsPane::RemoveIllegalChars
NOME
NOME
ScrolledWidgetsPane::TruncateFieldName
NOME
ScrolledWidgetsPane::RenameDupFieldName
NOME
NOME_1
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
NOME_1
Exit FieldNameCorrectionDlg
In TableFrame::OnActivate
In TableFrame::OnActivate
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/edog/Downloads/Limite_Bairro.shp
Open Layer:Limite_Bairro
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
ds:/home/edog/Downloads/Limite_Bairro.shp layer: Limite_Bairro
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnExclOneClick()
In MergeTableDlg::OnMergeClick()
Open FieldNameCorrectionDlg:
ScrolledWidgetsPane::RemoveIllegalChars
NOME
NOME
ScrolledWidgetsPane::TruncateFieldName
NOME
ScrolledWidgetsPane::RenameDupFieldName
NOME
NOME_1
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
NOME_1
Exit FieldNameCorrectionDlg
In TableFrame::OnActivate
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs
New Datasource Name:/home/edog/Desktop/Hilmara/GdaTmp_shp modified.shp
Project::GetSpatialReference()
Project::GetGdaGeometries()
ScrolledWidgetsPane::IsFieldNameValid
PROPORCAO
ScrolledWidgetsPane::IsFieldNameValid
OBJECTID
ScrolledWidgetsPane::IsFieldNameValid
rea
ScrolledWidgetsPane::IsFieldNameValid
NOME
ScrolledWidgetsPane::IsFieldNameValid
REGIAO_ADM
ScrolledWidgetsPane::IsFieldNameValid
AREA_PLANE
ScrolledWidgetsPane::IsFieldNameValid
CODBAIRRO
ScrolledWidgetsPane::IsFieldNameValid
CODRA
ScrolledWidgetsPane::IsFieldNameValid
CODBNUM
ScrolledWidgetsPane::IsFieldNameValid
LINK
ScrolledWidgetsPane::IsFieldNameValid
RP
ScrolledWidgetsPane::IsFieldNameValid
Cod_RP
ScrolledWidgetsPane::IsFieldNameValid
CODBAIRRO_
ScrolledWidgetsPane::IsFieldNameValid
SHAPESTAre
ScrolledWidgetsPane::IsFieldNameValid
SHAPESTLen
ScrolledWidgetsPane::IsFieldNameValid
DIRETA
ScrolledWidgetsPane::IsFieldNameValid
INDIRETA
ScrolledWidgetsPane::IsFieldNameValid
field_18
ScrolledWidgetsPane::IsFieldNameValid
NOME_1
ScrolledWidgetsPane::IsFieldNameValid
NOME_1
ScrolledWidgetsPane::RemoveIllegalChars
NOME_1
NOME_1
ScrolledWidgetsPane::TruncateFieldName
NOME_1
ScrolledWidgetsPane::RenameDupFieldName
NOME_1
NOME_2
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
NOME_2
Exit FieldNameCorrectionDlg

**Comment by jkoschinsky** [comment]
Another merge table crash -- seems to always involve field name problems
like duplicates, invalid names, etc.

**Comment by jkoschinsky** [comment]
We have a number of tickets related to table merges and field name issues.

Please test:
-- start with shapefile
--merge xls or csv to this that has field names that are long and/or contain special characters like -, &, %
--save the new file
--try a number of other things related to the merged tables and field names to try to replicate a crash
--a number of us have tried it and haven't been able to replicate it but crash reports keep flagging this as an issue

**Comment by lixun910** [comment]
Again, this is the same issue when there are duplicate field names in dataset. same as #1694 and #1798.
