### ISSUE TITLE
"Display Centroids" option appears to place centroids incorrectly for multipolygons

### ISSUE THREAD

**Issue by PhilipGriffith** [GeoDaCenter/geoda#1631]
I am using GeoDa version 1.12.1.59 28 November 2017.
I am using the sample NYC Data included with GeoDa.
When selecting "Display Centroids" from the "Shape Centers" menu, the centroids for multipolygons appear to always display within the first (or last?) polygon of the polygon collection, rather than the "center of mass" of the entire multipolygon.
See observations 2, 18 and 35 of the NYC Data for examples of the behavior I am describing.

**Comment by lixun910** [comment]
Thanks @PhilipGriffith ! We just updated the centroid algorithm using GEOS in our latest build, which works better. Can you try this new version 1.12.1.121?: 
OSX: https://www.dropbox.com/s/17ffewpb66ilela/GeoDa1.12.1.121-Installer.dmg?dl=0
Windows: https://www.dropbox.com/s/dr3m6e6py7ykk6k/GeoDa-1.12.1.121-Windows-64bit.exe?dl=0

![image](https://user-images.githubusercontent.com/2423887/38885121-b8543624-4226-11e8-93cc-70c67cb7210a.png)

**Comment by PhilipGriffith** [comment]
That works! Thanks for the quick fix. You all are awesome!
