### ISSUE TITLE
Automatically installs subversion 1.10 instead of 1.12

### ISSUE THREAD

**Issue by ArSunnyBansal** [GeoDaCenter/geoda#1632]
I am trying to install subversion 1.12 for Windows 7 Professional 64-bit, the setup file is named as 1.12 but when the installation starts it shows it is the installation for 1.10. Features under weights manager like kernel weights, connectivity graphs, etc. are missing in 1.10

**Comment by lixun910** [comment]
@ArSunnyBansal  We just released our latest GeoDa (version 1.12.1.125) which includes the new features you mentioned: http://geodacenter.github.io/download.html

**Comment by lixun910** [comment]
@ArSunnyBansal Here is a link for windows 64-bit: https://www.dropbox.com/s/66odv16opvd9hos/geoda_setup_1.12.1.125.exe?dl=0

The installer also shows 1.12 instead of 1.10 if you use this installer. Thanks!
