### ISSUE TITLE
max-p results should include method and parameters

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1638]
As it stands, the results for max-p include the weights, min bound, iterations, distance and
transformation, but they do not include the algorithm that was used, i.e., greedy vs tabu and simulated annealing. This should be fixed.

**Comment by jkoschinsky** [comment]
Works in in GeoDa 1.12.1.137 (OSX High Sierra, 10.13.4):

<img width="898" alt="screen shot 2018-06-06 at 11 08 06 am" src="https://user-images.githubusercontent.com/13679743/41050756-edcac668-6979-11e8-9a84-57563d1fda9b.png">
