### ISSUE TITLE
Crash Report: Copy Image to Clipboard

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1647]
Details:
os: 2-6-1
vs: 1-8-16-4
Check auto update:
In GdaFrame::OpenNaturalBreaks(4)
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
y2005
Open MapFrame.
Click GdaFrame::OnCopyImageToClipboard
In GdaFrame::OnSaveCategories()
Click GdaFrame::OnCopyImageToClipboard
In GdaFrame::OnNewCustomCatClassifA()

**Comment by jkoschinsky** [comment]
Works in in GeoDa 1.12.1.137 (OSX High Sierra, 10.13.4):
<img width="1030" alt="screen shot 2018-06-06 at 10 30 43 am" src="https://user-images.githubusercontent.com/13679743/41048796-28909fe8-6975-11e8-88ff-34384ceff26d.png">

Test in Windows:
- open map with natural breaks
- right-click: copy to clipboard
- paste into text editor

**Comment by jkoschinsky** [comment]
keeping open re.:

"Similar Error to #1653 (XRC error with variable setting dialogue)"
