### ISSUE TITLE
File open/save/save as broken in 1.12.1.137

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1656]
In version 137 the File open, file save and file save as dialog is disabled. It works fine up to 135.

<img width="778" alt="screen shot 2018-05-31 at 3 09 12 pm" src="https://user-images.githubusercontent.com/4008351/40805676-a64f124c-64e4-11e8-925d-c8c4ad62590c.png">

**Comment by lixun910** [comment]
Here is a new binary with linking to correct wxwidgets 3.1 (this is a bug in wx3.1): 
https://s3-us-west-2.amazonaws.com/geodasoftware/GeoDa1.12.1.137-Installer.dmg
