### ISSUE TITLE
Crash Report: LISA

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1659]
From: 
 Details:
os: 3-4-13
vs: 1-12-1-129
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/e/Documentos/GeodaVoronoi.shp
Open Layer:GeodaVoronoi
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/e/Documentos/GeodaVoronoi.shp
Entering OGRTable::OGRTable
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open LisaScatterPlotFrame (OnOpenMSPL).
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnCreateNewIdClick
Try to insert unique id (integer, POLY_ID) column in table.
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/home/e/Documentos/GeodaVoronoi.gal
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnActivate
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
IndNorPmeR
VariableSettingsDlg::GetWeightsId() weight: GeodaVoronoi
VariableSettingsDlg::GetWeightsId() weight: GeodaVoronoi
Entering AbstractCoordinator::AbstractCoordinator().
Entering AbstractCoordinator::SetSignificanceFilter()
Exiting AbstractCoordinator::SetSignificanceFilter()
Exiting AbstractCoordinator::AbstractCoordinator().
Entering LisaCoordinator::LisaCoordinator().
Entering AbstractCoordinator::InitFromVarInfo()
Entering LisaCoordinator::Init()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::Init()
Entering AbstractCoordinator::DeallocateVectors()
Exiting AbstractCoordinator::DeallocateVectors()
Entering AbstractCoordinator::AllocateVectors()
Exiting AbstractCoordinator::AllocateVectors()
Entering LisaCoordinator::Calc()
Exiting LisaCoordinator::Calc()
Exiting AbstractCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
Entering LisaScatterPlotFrame::LisaScatterPlotFrame
Exiting LisaScatterPlotFrame::LisaScatterPlotFrame
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
IndNorPmeR
VariableSettingsDlg::GetWeightsId() weight: GeodaVoronoi
VariableSettingsDlg::GetWeightsId() weight: GeodaVoronoi
Entering AbstractCoordinator::AbstractCoordinator().
Entering AbstractCoordinator::SetSignificanceFilter()
Exiting AbstractCoordinator::SetSignificanceFilter()
Exiting AbstractCoordinator::AbstractCoordinator().
Entering LisaCoordinator::LisaCoordinator().
Entering AbstractCoordinator::InitFromVarInfo()
Entering LisaCoordinator::Init()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::Init()
Entering AbstractCoordinator::DeallocateVectors()
Exiting AbstractCoordinator::DeallocateVectors()
Entering AbstractCoordinator::AllocateVectors()
Exiting AbstractCoordinator::AllocateVectors()
Entering LisaCoordinator::Calc()
Exiting LisaCoordinator::Calc()
Exiting AbstractCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
Entering LisaScatterPlotFrame::LisaScatterPlotFrame
Exiting LisaScatterPlotFrame::LisaScatterPlotFrame
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
IndNorPmeR
VariableSettingsDlg::GetWeightsId() weight: GeodaVoronoi
VariableSettingsDlg::GetWeightsId() weight: GeodaVoronoi
Entering AbstractCoordinator::AbstractCoordinator().
Entering AbstractCoordinator::SetSignificanceFilter()
Exiting AbstractCoordinator::SetSignificanceFilter()
Exiting AbstractCoordinator::AbstractCoordinator().
Entering LisaCoordinator::LisaCoordinator().
Entering AbstractCoordinator::InitFromVarInfo()
Entering LisaCoordinator::Init()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::Init()
Entering AbstractCoordinator::DeallocateVectors()
Exiting AbstractCoordinator::DeallocateVectors()
Entering AbstractCoordinator::AllocateVectors()
Exiting AbstractCoordinator::AllocateVectors()
Entering LisaCoordinator::Calc()
Exiting LisaCoordinator::Calc()
Entering AbstractCoordinator::CalcPseudoP()
Entering AbstractCoordinator::CalcPseudoP_threaded()
Exiting AbstractCoordinator::CalcPseudoP_threaded()
Exiting AbstractCoordinator::CalcPseudoP()
Exiting AbstractCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
Entering LisaScatterPlotFrame::LisaScatterPlotFrame
Exiting LisaScatterPlotFrame::LisaScatterPlotFrame
Entering LisaMapFrame::LisaMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Entering AbstractMapCanvas::AbstractMapCanvas
Exiting AbstractMapCanvas::AbstractMapCanvas
Entering LisaMapCanvas::LisaMapCanvas
Exiting LisaMapCanvas::LisaMapCanvas
In AbstractCoordinator::registerObserver()
Exiting LisaMapFrame::LisaMapFrame
Entering LisaMapFrame::LisaMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Entering AbstractMapCanvas::AbstractMapCanvas
Exiting AbstractMapCanvas::AbstractMapCanvas
Entering LisaMapCanvas::LisaMapCanvas
Exiting LisaMapCanvas::LisaMapCanvas
In AbstractCoordinator::registerObserver()
Exiting LisaMapFrame::LisaMapFrame
Entering AbstractMapCanvas::DisplayRightClickMenu
In GdaFrame::OnSaveLisa()
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Exiting AbstractMapCanvas::DisplayRightClickMenu
In LisaMapFrame::~LisaMapFrame
Entering AbstractCoordinator::removeObserver
Exiting AbstractCoordinator::removeObserver
In LisaMapCanvas::~LisaMapCanvas
In AbstractMapCanvas::~AbstractMapCanvas
MapCanvas::~MapCanvas()
In LisaMapFrame::~LisaMapFrame
Entering AbstractCoordinator::removeObserver
In LisaCoordinator::~LisaCoordinator().
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
In AbstractCoordinator::~AbstractCoordinator().
Entering AbstractCoordinator::DeallocateVectors()
Exiting AbstractCoordinator::DeallocateVectors()
Exiting AbstractCoordinator::removeObserver
In LisaMapCanvas::~LisaMapCanvas
In AbstractMapCanvas::~AbstractMapCanvas
MapCanvas::~MapCanvas()

**Comment by jkoschinsky** [comment]
Test LISA with project file
-- change permuations and pseudo p-values with different weights

**Comment by VeraB620** [comment]
OS X El Capitan 10.11.6
GeoDa 1.12.1.143

I have no had any crashes with LISA (roughly 30 min), chasing permutations and p-values with different weights and saving.
