### ISSUE TITLE
Update text of distance weights warning

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1661]
Users find this error message confusing since they don't realize they can proceed with ok as another option:

![errormsg](https://user-images.githubusercontent.com/13679743/41438779-08229b4c-6fee-11e8-8a3b-3f7bb20a7be3.png)

-----------------------
Please update to:

You can try to proceed but the current threshold distance value might be too large to compute. If it fails, please input a smaller distance band (which might leave some observations neighborless) or use other weights (e.g. KNN).

**Comment by VeraB620** [comment]
OS X El Capitan 10.11.6
GeoDa 1.12.1.141
Text is updated and proceeding works.

<img width="842" alt="screen shot 2018-07-05 at 1 59 19 pm" src="https://user-images.githubusercontent.com/4943475/42342456-c252f318-805b-11e8-8309-09e445ee5dae.png">
<img width="506" alt="screen shot 2018-07-05 at 1 59 49 pm" src="https://user-images.githubusercontent.com/4943475/42342490-d6d09ed0-805b-11e8-86e4-d7699b099e09.png">
