### ISSUE TITLE
connectivity > show selection and neighbors still not quite right

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1664]
There are still problems with the selection/neighbors in the connectivity option in the map menu (beyond those in #1657).

The show selection and neighbors option seems to be always on, which should NOT be the default, because it also affects standard selection (without neighbors). It seems that the regular map menu mimics the behavior of the connectivity map, but that is not a good use case. The hovering feature is good in the connectivity map case, but not when one wants to select observations and find the neighbors. That doesn't seem to work. Selection by clicking only works when the selection/neighbors option is unchecked, but then there are no neighbors.

Also, there is some weird behavior when the selection is made in a different map. At first, the selection and its neighbors is highlighted in any map where connectivity show neighbors and selection is checked (the default), but when moving the pointer into one of those maps, the selections are removed and only the hovering approach works.

There probably should be a different logic dealing with the selection/neighbors in regular maps as compared to the connectivity maps. The latter are fine (hovering), but there should be a way to make a selection without hovering, and there seems to be a linking issue.

**Comment by lixun910** [comment]
Do you mean to "select multiple observations"? You can left click and hold the mouse and then move one the map (it will show a selecting rectangle):
<img width="600" alt="screen shot 2018-12-04 at 12 33 54 pm" src="https://user-images.githubusercontent.com/2423887/49468015-fcb06400-f7c0-11e8-8aa1-7b45f8a4b53a.png">

When you check "Show selection and Neighbors", hovering will be equivalent to point-click-select.

**Comment by Ashitacarl** [comment]
@lixun910 Can we fix the selection by clicking on an observation like what we do on a non-connectivity map? Currently, a connectivity map only supports hovering (the selection changes as you move the mouse).

**Comment by lixun910** [comment]
@Ashitacarl Actually this is a feature that @lanselin wants. One can always open a new map without "Show Section and Neighbors" and do select using point-click, this will link to all maps.
