### ISSUE TITLE
issues with saving zoomed in point map as image

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1669]
Not sure what exactly causes the problem, but the legend is misaligned for a point map that is zoomed in and has a base layer (see below). Adjusting the window size doesn't solve the problem. Making the white space to the left of the actual map larger pushes the legend further into the point map.

![sales_dummiesmapframe](https://user-images.githubusercontent.com/4008351/42910616-10a2cfde-8a9d-11e8-9657-bde1fae3c1b4.png)

![sales_dummiesmapframe1](https://user-images.githubusercontent.com/4008351/42910623-1824b5e2-8a9d-11e8-9ef2-10584ac04615.png)

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.179 (macOS Mojave, 10.14.1).

The legend is separated from the map, no overlapping.

<img width="446" alt="1669" src="https://user-images.githubusercontent.com/45187310/49711186-9d5cb480-fc03-11e8-9dd0-168cb98b2fab.png">
