### ISSUE TITLE
basemap transparency setup issue

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1679]
I am replicating my screen shots from the lab notes, using a NYC equal intervals map
for rent2008 at transparency 0.10 and the maps are different. In the current version
(first screen shot), you can no longer see the Carto light base map. In the lab notes
(March 2018, second screen shot), you could. What changed?

<img width="744" alt="screen shot 2018-07-25 at 7 20 55 am" src="https://user-images.githubusercontent.com/2423887/43206726-39c81d9a-8fdb-11e8-8f7f-3c7783d94a8b.png">
<img width="737" alt="11_759_cartoat10" src="https://user-images.githubusercontent.com/2423887/43206731-3bfe66d2-8fdb-11e8-8fd7-3db4e1c66575.png">

**Comment by lanselin** [comment]
works in macosx, exactly same picture at 0.10 transparency, need to verify in win

**Comment by VeraB620** [comment]
OS X El Capitan 10.11.6
GeoDa 1.12.1.147

I am able to get all the Nokia basemap options but the other options nothing shows up even when changing transparency. Also the Zoom in button does not zoom in, but the zoom out button does work.


<img width="595" alt="screen shot 2018-09-06 at 1 13 21 pm" src="https://user-images.githubusercontent.com/4943475/45176883-f6691680-b1d6-11e8-9396-26a5cee0460f.png">
<img width="593" alt="screen shot 2018-09-06 at 1 13 12 pm" src="https://user-images.githubusercontent.com/4943475/45176892-f8cb7080-b1d6-11e8-8d4c-7e2bc4cc6d61.png">

**Comment by jkoschinsky** [comment]
Yes, Xun is fixing this in current version , thanks

**Comment by lixun910** [comment]
verified:
<img width="602" alt="screen shot 2019-01-15 at 9 39 12 pm" src="https://user-images.githubusercontent.com/2423887/51226728-0542a100-190e-11e9-94b1-7e1b079cc617.png">
