### ISSUE TITLE
Crash when attempting a Spatial Correlogram from xls file

### ISSUE THREAD

**Issue by ncarola** [GeoDaCenter/geoda#1681]
macOS High Sierra 10.13.1
GeoDa 1.12.1.143
Stumbled upon this reproducible crash while testing.

Open Excel File
Table > Points from table
Space > Spatial Correlogram
Clicking anything in the Spatial Correlogram dialogue causes GeoDa to crash

Update: This does not seem to be unique to excel files. Spatial Correlogram seems to crash whenever used no matter the data source.

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.181 (macOS Mojave, 10.14.1). Dec. 10 build.

Fix verified. Can't replicate this crash with excel file or shp file.

<img width="843" alt="1681" src="https://user-images.githubusercontent.com/45187310/50115833-241a1e80-020e-11e9-802e-2dd02b54d166.png">
