### ISSUE TITLE
Weights creation issue: bandwidth threshold doesn't work in kernel

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1682]
I've been using Geoda to create kernel weights these days.
But I found that Geoda seems not be able to calculate the Gaussian weights with a bandwidth threshold.
No matter what the bandwidth is set to, I can only get weights for fixed-number (at most 20) neighbours.

**Comment by jkoschinsky** [comment]
fixed in 1.12.1.151

**Comment by bsalas11** [comment]
Fix verified in GeoDa 1.12.1.183  (Windows 10)
