### ISSUE TITLE
Crash: New ID Spatial Weight with CSV

### ISSUE THREAD

**Issue by ncarola** [GeoDaCenter/geoda#1683]
macOS High Sierra 10.13.1
GeoDa 1.12.1.151

Open CSV
Tools > Weights Manager
Create > Add ID Variable
Click Add Variable
Save

Requires force quitting out of GeoDa. I let run for several minutes but nothing happened. This occurred with both a data set with ~5000 obs and ~200,000 obs. With the larger file, GeoDa would not force quit either and I needed to restart my computer manually.

**Comment by jkoschinsky** [comment]
weights require a spatial file (unless csv is convert to map through XYs it's non-spatial) but should prompt warning instead of hanging.
