### ISSUE TITLE
Regression Screen not visible completely

### ISSUE THREAD

**Issue by shivareddyiirs** [GeoDaCenter/geoda#1684]
I loaded my data. Then opened regression.
I can see list of variables but can not see the right side box for dependent and indepndent variables..

PC: Windows 10 using latest version of GeoDa

**Comment by jkoschinsky** [comment]
Thanks for reporting this. We're looking at this and will fix and let you
know when it's up.

**Comment by shivareddyiirs** [comment]
Hi @jkoschinsky ,
I found that when I increase the width of regression then the other part is also visible.

**Comment by jkoschinsky** [comment]
verified in Win10
