### ISSUE TITLE
inconsistency in change current map type

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1686]
There is an inconsistency in the way the current map type is updated from an existing map. For all the map types, the current map is immediately updated to the new type. For example, when starting with a box map 1.5 and updating to box 3, it is immediate.

However, when selecting a custom category, the next prompt is for a variable. This did not used to be the case. It should be switched back to the old way, where the update is immediate, for the current variable in the map.

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.179 (macOS Mojave, 10.14.1).

Fix verified. 
When switching to a custom category, the default variable is assumed to be the one in use.

<img width="1022" alt="1686" src="https://user-images.githubusercontent.com/45187310/49711523-7901d780-fc05-11e8-9262-fc086decb5f9.png">
