### ISSUE TITLE
box plot default tick marks have changed

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1688]
The question is, why? This is in addition to the centering issue in #1687. For example, compare the screen shot from the workbook, top tick mark is 77 to the current one of 66. Why has this changed?

<img width="377" alt="screen shot 2018-08-03 at 3 36 05 pm" src="https://user-images.githubusercontent.com/4008351/43668794-adcc9f0e-9733-11e8-80cc-4c7de8eb9da2.png">

<img width="287" alt="screen shot 2018-08-03 at 3 35 58 pm" src="https://user-images.githubusercontent.com/4008351/43668799-b23b65f2-9733-11e8-824c-ca033dfca9b9.png">

**Comment by lanselin** [comment]
that is 60, not 66.

**Comment by lanselin** [comment]
same for the scatter plot tick marks on the vertical axis -- why has this changed?

<img width="689" alt="screen shot 2018-08-03 at 3 45 21 pm" src="https://user-images.githubusercontent.com/4008351/43668896-4ebda840-9734-11e8-909f-955a95c7c13b.png">
<img width="503" alt="screen shot 2018-08-03 at 3 44 16 pm" src="https://user-images.githubusercontent.com/4008351/43668908-60eae488-9734-11e8-85ff-c1957bbe0b0f.png">

**Comment by lanselin** [comment]
one more ...


<img width="711" alt="screen shot 2018-08-03 at 3 51 00 pm" src="https://user-images.githubusercontent.com/4008351/43669036-21cff31e-9735-11e8-868e-dfbc139bfcca.png">

<img width="498" alt="screen shot 2018-08-03 at 3 51 06 pm" src="https://user-images.githubusercontent.com/4008351/43669040-28d90f4c-9735-11e8-9b23-ed22193e379f.png">

**Comment by lixun910** [comment]
@lanselin I just checked and they are not changed.

For box plot, it actually compare hinge 3.0 to hinge 1.5
For scatter plot, if uncheck the scale options "Fixed y-axis scale over time”, you will get same results as in your lab notes.

**Comment by lanselin** [comment]
OK, great!
