### ISSUE TITLE
Crash related to saving table with problematic field names

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1694]
From: 
 Details:
os: 3-4-4
vs: 1-12-1-57
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:PG:dbname='Tese' 
Open Layer:statistics_workdays_norm
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
PG:dbname='Tese' 
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open ExportDataDlg in its Init()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnActivate
Open ExportDataDlg in its Init()
In ExportDataDlg::BrowseExportDataSource()
In ExportDataDlg::OnOkClick()
ds:/home/tdcpina/Desktop/windozs_sharing/statistics_workdays_norm2.shp
Project::GetSpatialReference()
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
name_fre
ScrolledWidgetsPane::IsFieldNameValid
nb_bs
ScrolledWidgetsPane::IsFieldNameValid
nb_ch_d
ScrolledWidgetsPane::IsFieldNameValid
nb_psch_d
ScrolledWidgetsPane::IsFieldNameValid
nb_ngch_d
ScrolledWidgetsPane::IsFieldNameValid
mean_abs_d
ScrolledWidgetsPane::IsFieldNameValid
mean_ab_d
ScrolledWidgetsPane::IsFieldNameValid
nb_ch_n
ScrolledWidgetsPane::IsFieldNameValid
nb_psch_n
ScrolledWidgetsPane::IsFieldNameValid
nb_ngch_n
ScrolledWidgetsPane::IsFieldNameValid
mean_abs_n
ScrolledWidgetsPane::IsFieldNameValid
mean_ab_n
ScrolledWidgetsPane::IsFieldNameValid
nb_ch_mp
ScrolledWidgetsPane::IsFieldNameValid
nb_psch_mp
ScrolledWidgetsPane::IsFieldNameValid
nb_ngch_mp
ScrolledWidgetsPane::IsFieldNameValid
mean_abs_mp
ScrolledWidgetsPane::IsFieldNameValid
mean_ab_mp
ScrolledWidgetsPane::IsFieldNameValid
nb_ch_ep
ScrolledWidgetsPane::IsFieldNameValid
nb_psch_ep
ScrolledWidgetsPane::IsFieldNameValid
nb_ngch_ep
ScrolledWidgetsPane::IsFieldNameValid
mean_abs_ep
ScrolledWidgetsPane::IsFieldNameValid
mean_ab_ep
ScrolledWidgetsPane::IsFieldNameValid
Pop_2016
ScrolledWidgetsPane::IsFieldNameValid
dens_pop
ScrolledWidgetsPane::IsFieldNameValid
pc_1864
ScrolledWidgetsPane::IsFieldNameValid
pc_o65
ScrolledWidgetsPane::IsFieldNameValid
pc_unemp
ScrolledWidgetsPane::IsFieldNameValid
med_inc
ScrolledWidgetsPane::IsFieldNameValid
pc_prim
ScrolledWidgetsPane::IsFieldNameValid
pc_sec
ScrolledWidgetsPane::IsFieldNameValid
dens_offic
ScrolledWidgetsPane::IsFieldNameValid
pc_nohab
ScrolledWidgetsPane::IsFieldNameValid
nbpc_com
ScrolledWidgetsPane::IsFieldNameValid
pc_nearpt
ScrolledWidgetsPane::IsFieldNameValid
pc_nearmtr
ScrolledWidgetsPane::IsFieldNameValid
dens_ptstop
ScrolledWidgetsPane::IsFieldNameValid
dens_binfr
ScrolledWidgetsPane::IsFieldNameValid
dens_bpark
ScrolledWidgetsPane::IsFieldNameValid
pc_bpav
ScrolledWidgetsPane::IsFieldNameValid
dens_slpo2
ScrolledWidgetsPane::IsFieldNameValid
dens_slpo5
ScrolledWidgetsPane::IsFieldNameValid
dist_tocc
ScrolledWidgetsPane::IsFieldNameValid
pc_surfimp
ScrolledWidgetsPane::IsFieldNameValid
pc_poppark
ScrolledWidgetsPane::IsFieldNameValid
area
ScrolledWidgetsPane::IsFieldNameValid
long
ScrolledWidgetsPane::IsFieldNameValid
lat
ScrolledWidgetsPane::IsFieldNameValid
nndist_mst
ScrolledWidgetsPane::RemoveIllegalChars
mean_abs_mp
mean_abs_mp
ScrolledWidgetsPane::TruncateFieldName
mean_abs_mp
mean__s_mp
ScrolledWidgetsPane::RenameDupFieldName
mean__s_mp
mean__s_mp
ScrolledWidgetsPane::RemoveIllegalChars
mean_abs_ep
mean_abs_ep
ScrolledWidgetsPane::TruncateFieldName
mean_abs_ep
mean__s_ep
ScrolledWidgetsPane::RenameDupFieldName
mean__s_ep
mean__s_ep
ScrolledWidgetsPane::RemoveIllegalChars
dens_ptstop
dens_ptstop
ScrolledWidgetsPane::TruncateFieldName
dens_ptstop
dens__stop
ScrolledWidgetsPane::RenameDupFieldName
dens__stop
dens__stop
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
mean_as_mp
ScrolledWidgetsPane::IsFieldNameValid
mean_as_ep
ScrolledWidgetsPane::IsFieldNameValid
dens_ptstp
In FieldNameCorrectionDlg
Out FieldNameCorrectionDlg
start OGRLayerProxy::AddFreatures()
Out OGRDataAdapter::ExportDataSource()
In TableFrame::OnActivate
In TableFrame::OnActivate
MapCanvas::~MapCanvas()
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
Entering Project::SaveDataSourceData

**Comment by jkoschinsky** [comment]
YES!!! Thank you for catching this.

**Comment by Ashitacarl** [comment]
Hi @lixun910, Sorry about the confusion.

By "duplicate", I meant two columns with exactly the same name in the file to be merged.

For example, 
1. I export Guerry dataset as csv.
2. In Excel, I created another column "dept" (key variable to be used for merging). Note: to replicate the crash, the two columns should be identical (name + content)

<img width="353" alt="1694-2" src="https://user-images.githubusercontent.com/45187310/51583186-ff603900-1e94-11e9-9c98-c6cb18f9480b.png">

3. In the Guerry sample dataset, Click [Merge] and drag the excel file created above

<img width="474" alt="1694" src="https://user-images.githubusercontent.com/45187310/51583218-20c12500-1e95-11e9-8543-4d80ba991f8c.png">

4. GeoDa crashes. I am not sure if this is exactly what they have done. But having two identical key columns in the csv file to be merged results in a crash.

**Comment by lixun910** [comment]
@Ashitacarl  Got it. Thanks!

**Comment by lixun910** [comment]
[guerry.csv.zip](https://github.com/GeoDaCenter/geoda/files/2789325/guerry.csv.zip)

**Comment by Ashitacarl** [comment]
Hi @jkoschinsky @lixun910 

I just noticed that the test report I posted for this issue should be for #1798 
Shall I re-post it there (#1798) or simply relate to that issue?

Sorry about the mistake.

**Comment by lixun910** [comment]
Thanks! It will be ok: since you mentioned the #1798 here. The two issues
are going to ref each other.

**Comment by jkoschinsky** [comment]
@Ashitacarl 
yes, no problem -- thx for catching this!!

**Comment by lixun910** [comment]
This issue has been fixed by detecting duplicate field names when loading dataset in GeoDa. 

<img width="422" alt="Screen Shot 2019-08-02 at 4 32 17 PM" src="https://user-images.githubusercontent.com/2423887/62403589-2c2b9200-b543-11e9-8058-4dc7450a0f6c.png">
