### ISSUE TITLE
Progress Dialog doesn't update well on Linux

### ISSUE THREAD

**Issue by GoogleCodeExporter** [GeoDaCenter/geoda#17]
```
from Jan 18, 2011

The Progress Dialog when opening a new shp file is slow to update on Windows 
and especially on Linux.  I have tried forcing refreshes and updates to the 
window, but it makes no difference.  The embedded progress bar in the 
Regression Dialog seems to work well on all platforms, but the text on Linux 
does not update well.


```

Original issue reported on code.google.com by `mmcc...@gmail.com` on 5 Mar 2013 at 6:00

**Comment by lixun910** [comment]
Fix verified using GeoDa 1.14 and Ubuntu 16.04 and 18.04

<img width="455" alt="Screen Shot 2019-08-13 at 9 31 09 PM" src="https://user-images.githubusercontent.com/2423887/62994622-b6aca500-be11-11e9-9665-8b5cd133c8dc.png">
