### ISSUE TITLE
Crash Report: Linux crashes after installation

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1706]
From: rizwanalvi1@gmail.com
 Details:
os: 3-4-15
vs: 1-12-1-129
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()

**Comment by jkoschinsky** [comment]
Hi,
Thanks for reporting this bug. If you can send us more info about the steps
preceding this crash, we'll try to replicate and fix.
Thanks, Julia

**Comment by jkoschinsky** [comment]
Please see:
https://s3-us-west-2.amazonaws.com/geodasoftware/geoda_1.12-ubuntu1804.deb
