### ISSUE TITLE
add count for selected added layers at bottom of view

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1722]
There's one small addition that would be really helpful: Could you add the number of selected observations for the added layers to the text at the bottom of a view? Currently it only lists the total selected for the main layer. Since there's no table for the added layers, you can't get the count (especially if several points are stacked). I'm attaching a screenshot FYI.

<img width="510" alt="screen shot 2018-10-02 at 10 18 49 am" src="https://user-images.githubusercontent.com/13679743/46359295-924b3e00-c62e-11e8-88b4-67008df16e6a.png">

**Comment by lixun910** [comment]
[SF_data.zip](https://github.com/GeoDaCenter/geoda/files/2642488/SF_data.zip)

**Comment by bsalas11** [comment]
Fix verified in GeoDa 1.12.1.183  (Windows 10)
