### ISSUE TITLE
weights - type incorrect for weights loaded from file

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1733]
This is an old issue that was fixed before - see screenshot fig 10 from the workbook. But in the latest versions 161 and 169 it is back to the old bug. The type should be listed as "custom", not "rook". For example, in the screenshot a queen weights file was loaded and the type is given as rook.

This bug was fixed before, how come it is back?

<img width="411" alt="screen shot 2018-10-29 at 6 58 45 am" src="https://user-images.githubusercontent.com/4008351/47648602-7f059280-db48-11e8-8896-56808697446c.png">

<img width="394" alt="screen shot 2018-10-29 at 6 58 37 am" src="https://user-images.githubusercontent.com/4008351/47648614-89279100-db48-11e8-96d6-85ad7d371318.png">

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.181 (macOS Mojave, 10.14.1). Dec. 10 build.

Fix verified. When out-of-project weights are loaded, no weights information (on type and symmetry) is assumed. 

<img width="439" alt="1733" src="https://user-images.githubusercontent.com/45187310/50118355-043a2900-0215-11e9-8b4f-0029ee50b5ed.png">
