### ISSUE TITLE
weights - connectivity map does not distinguish neighbors from selection

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1734]
This is also an old issue. See screen shot from workbook with neighbors as white. But in 161 the neighbors are not distinguished from the selected observations (see screen shot). This worked fine before, why the change?

<img width="576" alt="screen shot 2018-10-29 at 7 45 31 am" src="https://user-images.githubusercontent.com/4008351/47650678-fb9b6f80-db4e-11e8-92c2-5c5d4fd4ae67.png">

<img width="584" alt="screen shot 2018-10-29 at 7 45 39 am" src="https://user-images.githubusercontent.com/4008351/47650682-ff2ef680-db4e-11e8-94d5-458bbe76066d.png">

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.179 (macOS Mojave, 10.14.1).

Fix verified. Ego and neighbors (white) are now in different colors in Themeless Connectivity Maps.
In other substantive connectivity maps (e.g. quantile with connectivity), colors are kept in the way they are mapped (a solved problem in #1657 ). 

<img width="600" alt="1734" src="https://user-images.githubusercontent.com/45187310/49711987-e9a9f380-fc07-11e8-830a-b022f72835b0.png">

**Comment by lixun910** [comment]
verified in windows:
<img width="597" alt="screen shot 2019-01-15 at 9 08 42 pm" src="https://user-images.githubusercontent.com/2423887/51225839-c27eca00-1909-11e9-82a4-a8a5863d346b.png">
