### ISSUE TITLE
weights - connectivity map for points doesn't work

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1735]
Selecting a point in the connectivity map doesn't seem to do anything. Compare to workbook Fig 12,
which is how it should be -- and was. Nothing happens now: the neighbors are identified in the status bar, but not highlighted in the map.

<img width="599" alt="screen shot 2018-10-29 at 9 10 50 am" src="https://user-images.githubusercontent.com/4008351/47655259-a1081080-db5a-11e8-9c52-1a890618971b.png">

<img width="717" alt="screen shot 2018-10-29 at 9 11 56 am" src="https://user-images.githubusercontent.com/4008351/47655322-c268fc80-db5a-11e8-8be8-5305cea7b6bb.png">

**Comment by lixun910** [comment]
verified in windows:

<img width="605" alt="screen shot 2019-01-15 at 9 14 56 pm" src="https://user-images.githubusercontent.com/2423887/51226015-a16aa900-190a-11e9-9767-e82b72d410c0.png">
