### ISSUE TITLE
hierarchical clusters - save results issues (1)

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1740]
The note "Please save results to see the summary report" should be removed, I think. The summary report is shown in the dialog and the Save functionality works as for the k-means.

**Comment by lixun910** [comment]
verified:
<img width="877" alt="screen shot 2019-01-15 at 9 13 34 pm" src="https://user-images.githubusercontent.com/2423887/51225985-7c763600-190a-11e9-9b5c-e387c4bcbc7c.png">
