### ISSUE TITLE
hierarchical clusters - save result issues (2)

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1741]
The dialog for saving the summary of the hierarchical clustering has "save pca results". For consistency sake and to keep the same dialog in multiple situations, "save results" would be better.

**Comment by lixun910** [comment]
verified:
<img width="890" alt="screen shot 2019-01-15 at 9 12 24 pm" src="https://user-images.githubusercontent.com/2423887/51225961-5781c300-190a-11e9-8259-aafe6fc3c9c8.png">
