### ISSUE TITLE
Kmeans UI 

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1742]
from luc:
1. I think we can take off the note about "only supported for smaller data sets."

2. the variable settings dialog for k-means says “k means dialog”, but for hierarchical
clustering it says “hierarchical clustering settings”. for consistency sake, i think it 
should say “settings” for both (all).

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.179 (macOS Mojave, 10.14.1).

1. No note "only supported for smaller data sets" shows up;

2. For all clustering methods, the dialog is now "XX settings".

<img width="412" alt="1742" src="https://user-images.githubusercontent.com/45187310/49847772-6fa87480-fd97-11e8-9ddd-4272da8de43d.png">
