### ISSUE TITLE
hierarchical clustering interface

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1744]
A few minor fixes needed on the hierarchical clustering interface. 

- we can remove the note about smaller data sets

- "Spatially constraint" should be "Spatial constraint"

**Comment by lixun910** [comment]
v179

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.179 (macOS Mojave, 10.14.1).

1. No info about smaller datasets remained;
2. "Spatial constraint" correct.

<img width="411" alt="1744" src="https://user-images.githubusercontent.com/45187310/49473290-40ae6380-f7d7-11e8-82ef-179ce811be63.png">
