### ISSUE TITLE
crash: points file with null geometry will crash Thiessen polygon creation

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1747]
See attached points dataset

[Archive.zip](https://github.com/GeoDaCenter/geoda/files/2574648/Archive.zip)

<img width="590" alt="screen shot 2018-11-12 at 9 21 06 pm" src="https://user-images.githubusercontent.com/2423887/48391566-63f85e00-e6c4-11e8-9432-40b993d80b40.png">

**Comment by lixun910** [comment]
v179

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.179 (macOS Mojave, 10.14.1).

Same dataset, one missing geometry info, no crush.

Also tested another dataset with more missing geometry info, no crush.

<img width="600" alt="1747" src="https://user-images.githubusercontent.com/45187310/49472978-6b4bec80-f7d6-11e8-9e41-adc08eee6c26.png">
