### ISSUE TITLE
bivariate Moran scatterplot crashes (time enabled variables)

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1752]
Not sure if my crash report made it, but it is not likely to be very informative, since a lot was going on.

The crash happened when invoking randomization on a bivariate Moran scatterplot with time grouped variables, e.g., hhsiz05 and W_hhsiz02 in the NYC example.

This may be an issue with time enabled variables only, since an earlier one with regular variables worked fine.

**Comment by lixun910** [comment]
v179

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.181 (macOS Mojave, 10.14.1). Dec. 10 build.

Fix verified. No crash observed when doing randomization for grouped variables using NYC data. Also tested natregimes data, no crash either.

<img width="886" alt="1752" src="https://user-images.githubusercontent.com/45187310/50122282-4f5a3900-0221-11e9-8ce0-3776da6d221e.png">
