### ISSUE TITLE
bivariate moran scatter plot - time enabled variables does not show Moran's I

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1753]
The bivariate Moran scatter plot for time enabled variables does not show the Moran's I coefficient on the plot (this is the one that crashes in #1752).

<img width="482" alt="st_moran_plot" src="https://user-images.githubusercontent.com/4008351/48719262-e9eb3c00-ebd1-11e8-9387-aa51adaf9d61.png">

**Comment by lixun910** [comment]
v179
