### ISSUE TITLE
time editor - incorrect number of views open

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1754]
When editing the "time" item in the Time Editor the warning for currently open windows is not correct. For example, it counts as an open window pertaining to the variable the weights manager. It seems like all open windows need to be closed, not just the ones pertaining to the variables that are to be grouped.

**Comment by lixun910** [comment]
v179

**Comment by bsalas11** [comment]
Fix verified in GeoDa 1.12.1.183  (Windows 10)
