### ISSUE TITLE
k medians cluster map - incorrect heading

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1755]
The heading on the cluster map for K-medians says "KMeans Cluster Map". It should be "KMedians Cluster Map".

**Comment by lixun910** [comment]
v179

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.179 (macOS Mojave, 10.14.1).

K-medians cluster map is now under the name "K-medians".

<img width="436" alt="1755" src="https://user-images.githubusercontent.com/45187310/49472215-756ceb80-f7d4-11e8-9b0b-2da319582bea.png">
