### ISSUE TITLE
kmedoids has no maximum iterations

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1756]
The kmedoids clustering settings dialog does not have the maximum iterations option, even though the maximum iterations are reported in the summary (as 1000).

**Comment by lixun910** [comment]
v179

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.179 (macOS Mojave, 10.14.1).

The "maximum iteration" option is now available for k-medoids, with a default value 1000.

<img width="671" alt="1756" src="https://user-images.githubusercontent.com/45187310/49471424-7bfa6380-f7d2-11e8-93b9-bb72c6670469.png">
