### ISSUE TITLE
cluster variable setting typo for iterations

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1757]
The interfaces for the different clustering methods have the option "maximal iterations", it should be "maximum iterations". Note, the summary result reports "maximum" iterations.

**Comment by lixun910** [comment]
v179

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.179 (macOS Mojave, 10.14.1).

"maximal iterations" all replaced by "maximum iterations": KMedoids, KMeans, KMedians, and Spectral.

<img width="625" alt="1757" src="https://user-images.githubusercontent.com/45187310/49471879-a26cce80-f7d3-11e8-92e8-a92de873a809.png">
