### ISSUE TITLE
report weights for geometric centroids

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1760]
When geometric centroids are used in any of the clustering routines, the result should include the value of the weight in the output. Currently, that is not the case.

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.181 (macOS Mojave, 10.14.1). Dec. 10 build.

Fix verified.

K-means, K-median, K-medroids, Spectral, Hierarchical, and HDBScan all report the value of the weight in the output when geometric centroids are used.

<img width="985" alt="1760" src="https://user-images.githubusercontent.com/45187310/50121318-0785e280-021e-11e9-9c60-4a95050160b3.png">
