### ISSUE TITLE
Auto Weighting option not implemented for cluster methods

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1761]
The auto weighting option is not implemented for:

- hierarchical clustering
- spectral clustiong
- HDBscan

Geometric centroids is available, but has not been updated with the auto weighting
as is the case for kmeans, etc.

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.183 (macOS Mojave, 10.14.1). Dec. 19 build.
Dataset: Polygon data from an external source with missings

Fix verified.

Auto-weighting included for spectral clustering, hierarchical clustering, and HDBScan. The outputs are fine. 

<img width="1064" alt="1761" src="https://user-images.githubusercontent.com/45187310/50366672-c30d8600-0540-11e9-8dfb-f778f2938a3a.png">
