### ISSUE TITLE
no summary for geometric centroids in spectral and hdbscan

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1762]
When implementing clustering with geometric centroids and weight = 1, the summary does not report the cluster centers nor the sum of squares statistics, see below.

<img width="459" alt="screen shot 2018-11-27 at 6 49 36 pm" src="https://user-images.githubusercontent.com/4008351/49121427-ffb5cc80-f275-11e8-9128-eb41f87182f7.png">

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.181 (macOS Mojave, 10.14.1). Dec. 10 build.

Fix verified.
Cluster centers and the sum of squares statistics reported.

<img width="973" alt="1762" src="https://user-images.githubusercontent.com/45187310/50120051-f509aa00-0219-11e9-9f4c-546529c6523f.png">
