### ISSUE TITLE
no id variable for gwt skater spanning tree

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1763]
The weights (gwt) created from the "save spanning tree" command in skater do not contain an ID variable. There should be a dialog asking for such a variable before the tree gets saved.

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.181 (macOS Mojave, 10.14.1). Dec. 10 build.

Fix verified. 
the skater gwt now requires the specification of a weights matrix before running the skater. 
The output gwt uses the same ID as specified in the first weight.

<img width="464" alt="1763" src="https://user-images.githubusercontent.com/45187310/50119190-9cd1a880-0217-11e9-904a-683635f40cac.png">
