### ISSUE TITLE
skater spanning tree gwt format incorrect

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1764]
The gwt weights file saved by "save spanning tree" in skater does not have the correct format. Apart from it not having an id variable in the header line (see #1763), it also is not symmetric. The link between any i and j is only recorded once, the symmetric link between j and i is not included.

This leads to strange results, such as the number of neighbors given as 0 whereas there always is at least one neighbor (by definition). For example, observation 5 gives 0 neighbors (last column)

<img width="733" alt="screen shot 2018-11-27 at 7 36 26 pm" src="https://user-images.githubusercontent.com/4008351/49123005-908fa680-f27c-11e8-892e-a678147aea0e.png">

but in fact it has one neighbor

<img width="88" alt="screen shot 2018-11-27 at 7 37 01 pm" src="https://user-images.githubusercontent.com/4008351/49123027-a1d8b300-f27c-11e8-898d-379d7cd70bf7.png">

in the gwt file, the connection between 4 and 5 is included, but the connection between 5 and 4 is not, hence the latter shows up as having no neighbors.

<img width="171" alt="screen shot 2018-11-27 at 7 37 46 pm" src="https://user-images.githubusercontent.com/4008351/49123041-ba48cd80-f27c-11e8-93d5-46db9ccc2e8b.png">

**Comment by lixun910** [comment]
@Ashitacarl  Do you have any other question re this issue? 

By clicking "Save Spanning Tree", GeoDa will save the spanning tree as a GWT weights file. This weights file has the information of "the number of neighbors";
By clicking "Run" button, GeoDa will saves "CL" into current table as a new column.

**Comment by Ashitacarl** [comment]
@lixun910 Sorry that I forgot to reply on the issue. 

I am just wondering how we can add the "number of neighbors" for each observation as a column in the table.

**Comment by lixun910** [comment]
@Ashitacarl  

Got it. In Skater, GeoDa doesn’t save “number of neighbors” information in the table directly, since Skate spanning tree gwt file has this information. User can save the “number of neighbors” to table by using “Connectivity Histogram” and right click “Save Connectivity To Table”.

**Comment by Ashitacarl** [comment]
@lixun910 Great! Thanks.
