### ISSUE TITLE
skater spanning tree weights properties incorrect

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1765]
See also #1763 and #1764. The properties of the skater weights file are not correct in the weights manager. In part, this is because the lack of symmetric entries (#1764), and the lack of an id variable (#1763), but also the type is given as "custom" and the symmetry is given as "unknown". 

To keep consistency with the other weights files, the type should be given as "skater" and the symmetry should be given as symmetric (and the id variable listed). This then would allow the information to be saved in a project file for future use.

<img width="470" alt="screen shot 2018-11-27 at 7 45 51 pm" src="https://user-images.githubusercontent.com/4008351/49123219-730f0c80-f27d-11e8-8e07-4ed1ad7f45ca.png">

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.181 (macOS Mojave, 10.14.1). Dec. 10 build.

In the weights manager, the saved skater gwt weight now is identified as "symmetric".
But the type is "custom" which should be changed into "skater".

<img width="419" alt="1765" src="https://user-images.githubusercontent.com/45187310/50119758-5715df80-0219-11e9-8202-af0bc29764f7.png">

**Comment by lixun910** [comment]
@Ashitacarl This is correct: when you create the skater.gwt, GeoDa knows it is  symmetric -- just like when you create any distance based weights. However, when you load skater.gwt from an external file, GeoDa doesn't detect if it's symmetric or not, so it will be marked as "custom".

**Comment by Ashitacarl** [comment]
@lixun910 But this one is saved from "Saving Spinning Tree" rather than "Loaded" from an external file.  So, the type should be "skater" rather than "custom". The "symmetric" label is correct!

**Comment by lixun910** [comment]
@Ashitacarl  oh, sorry. I see now. We don't have a type "skater", which is basically a name of a spatially constrained clustering method.

**Comment by lixun910** [comment]
Got it. What about the "save spanning tree" function in "Redcap"? Do you want to name it as "redcap" or "skater"? since they are actually the same -- a spanning tree saved in the format of GWT.

**Comment by lanselin** [comment]
Good point. Let’s call it “tree” as the type.

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.183 (macOS Mojave, 10.14.1). Dec. 19 build.
Dataset: Guerry sample data.

Fix verified. "Tree" now included as the type for both skater and redcap.

<img width="387" alt="1765v2-1" src="https://user-images.githubusercontent.com/45187310/50366972-8c386f80-0542-11e9-99b2-a0085c5d46df.png">
