### ISSUE TITLE
Crash: LISA

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1768]
From: 
 Details:
os: 3-4-15
vs: 1-12-1-147
/usr/local/geoda/web_plugins/logger.txt
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/media/D/Documentos/Mestrado/Aula/3-Espacial/Trabalho/br_microrregioes/BRMIE250GC_SIR.shp
Entering OGRTable::OGRTable
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PrMed_2003
VariableSettingsDlg::GetWeightsId() weight: queen1
VariableSettingsDlg::GetWeightsId() weight: queen1
Entering AbstractCoordinator::AbstractCoordinator().
Entering AbstractCoordinator::SetSignificanceFilter()
Exiting AbstractCoordinator::SetSignificanceFilter()
Exiting AbstractCoordinator::AbstractCoordinator().
Entering LisaCoordinator::LisaCoordinator().
Entering AbstractCoordinator::InitFromVarInfo()
Entering LisaCoordinator::Init()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::Init()
Entering AbstractCoordinator::DeallocateVectors()
Exiting AbstractCoordinator::DeallocateVectors()
Entering AbstractCoordinator::AllocateVectors()
Exiting AbstractCoordinator::AllocateVectors()
Entering LisaCoordinator::Calc()
Exiting LisaCoordinator::Calc()
Exiting AbstractCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
Entering LisaScatterPlotFrame::LisaScatterPlotFrame
Exiting LisaScatterPlotFrame::LisaScatterPlotFrame
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PrMed_2003
VariableSettingsDlg::GetWeightsId() weight: queen1
VariableSettingsDlg::GetWeightsId() weight: queen1
Entering AbstractCoordinator::AbstractCoordinator().
Entering AbstractCoordinator::SetSignificanceFilter()
Exiting AbstractCoordinator::SetSignificanceFilter()
Exiting AbstractCoordinator::AbstractCoordinator().
Entering LisaCoordinator::LisaCoordinator().
Entering AbstractCoordinator::InitFromVarInfo()
Entering LisaCoordinator::Init()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::Init()
Entering AbstractCoordinator::DeallocateVectors()
Exiting AbstractCoordinator::DeallocateVectors()
Entering AbstractCoordinator::AllocateVectors()
Exiting AbstractCoordinator::AllocateVectors()
Entering LisaCoordinator::Calc()
Exiting LisaCoordinator::Calc()
Entering AbstractCoordinator::CalcPseudoP_threaded()
Exiting AbstractCoordinator::CalcPseudoP_threaded()
Exiting AbstractCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
Entering LisaScatterPlotFrame::LisaScatterPlotFrame
Exiting LisaScatterPlotFrame::LisaScatterPlotFrame
Entering LisaMapFrame::LisaMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Entering AbstractMapCanvas::AbstractMapCanvas
Exiting AbstractMapCanvas::AbstractMapCanvas
Entering LisaMapCanvas::LisaMapCanvas
Exiting LisaMapCanvas::LisaMapCanvas
In AbstractCoordinator::registerObserver()
Exiting LisaMapFrame::LisaMapFrame
In LisaMapFrame::~LisaMapFrame
Entering AbstractCoordinator::removeObserver
In LisaCoordinator::~LisaCoordinator().
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
In AbstractCoordinator::~AbstractCoordinator().
Entering AbstractCoordinator::DeallocateVectors()
Exiting AbstractCoordinator::DeallocateVectors()
Exiting AbstractCoordinator::removeObserver
In LisaMapCanvas::~LisaMapCanvas
In AbstractMapCanvas::~AbstractMapCanvas
MapCanvas::~MapCanvas()
In OnRan999Per()

**Comment by jkoschinsky** [comment]
1. create weights
2. create different kinds of Local Moran's maps
3. change randomization

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.183 (macOS Mojave, 10.14.1). Dec. 19 build.

Can't replicate this crash. The user dataset (recorded in the crash report) has isolates (queen 1st order). This could be the problem.

But tested with an external dataset with missing values and isolates. No crash.
