### ISSUE TITLE
Crash: LISA and spatial regressions

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1769]
From: 
 Details:
os: 3-4-15
vs: 1-12-1-147
/usr/local/geoda/web_plugins/logger.txt
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/media/D/Documentos/Mestrado/Aula/3-Espacial/Trabalho/br_microrregioes/BRMIE250GC_SIR.shp
Entering OGRTable::OGRTable
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
selected:1
Click CreatingWeightDlg::OnPrecisionThresholdCheck
Click CreatingWeightDlg::OnPrecisionThresholdCheck
Click CreatingWeightDlg::OnCSpinKnnUpdated
Click CreatingWeightDlg::OnCSpinKnnUpdated
Click CreatingWeightDlg::OnCSpinKnnUpdated
Click CreatingWeightDlg::OnCSpinKnnUpdated
Click CreatingWeightDlg::OnCSpinKnnUpdated
Click CreatingWeightDlg::OnCSpinKnnUpdated
Click CreatingWeightDlg::OnCSpinKnnUpdated
Click CreatingWeightDlg::OnCSpinKnnUpdated
Click CreatingWeightDlg::OnCSpinKnnUpdated
Click CreatingWeightDlg::OnCSpinKnnUpdated
Click CreatingWeightDlg::OnCSpinKnnUpdated
Click CreatingWeightDlg::OnCreateClick
Click CreatingWeightDlg::OnCreateClick
Click CreatingWeightDlg::OnCreateClick
CreateWeights()
/media/D/Documentos/Mestrado/Aula/3-Espacial/Trabalho/br_microrregioes/kernel.kwt
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnActivate
WeightsManFrame::OnConnectMapBtn()
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::DisplayNeighbors()
In WeightsManFrame::OnActivate
MapCanvas::~MapCanvas()
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
PrMed_2003
VariableSettingsDlg::GetWeightsId() weight: kernel
VariableSettingsDlg::GetWeightsId() weight: kernel
Entering AbstractCoordinator::AbstractCoordinator().
Entering AbstractCoordinator::SetSignificanceFilter()
Exiting AbstractCoordinator::SetSignificanceFilter()
Exiting AbstractCoordinator::AbstractCoordinator().
Entering LisaCoordinator::LisaCoordinator().
Entering AbstractCoordinator::InitFromVarInfo()
Entering LisaCoordinator::Init()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::Init()
Entering AbstractCoordinator::DeallocateVectors()
Exiting AbstractCoordinator::DeallocateVectors()
Entering AbstractCoordinator::AllocateVectors()
Exiting AbstractCoordinator::AllocateVectors()
Entering LisaCoordinator::Calc()
Exiting LisaCoordinator::Calc()
Entering AbstractCoordinator::CalcPseudoP_threaded()
Exiting AbstractCoordinator::CalcPseudoP_threaded()
Exiting AbstractCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
Entering LisaScatterPlotFrame::LisaScatterPlotFrame
Exiting LisaScatterPlotFrame::LisaScatterPlotFrame
Entering LisaMapFrame::LisaMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Entering AbstractMapCanvas::AbstractMapCanvas
Exiting AbstractMapCanvas::AbstractMapCanvas
Entering LisaMapCanvas::LisaMapCanvas
Exiting LisaMapCanvas::LisaMapCanvas
In AbstractCoordinator::registerObserver()
Exiting LisaMapFrame::LisaMapFrame
Close CreatingWeightDlg
MapCanvas::~MapCanvas()
In GdaFrame::OnRegressionClassic()
Open RegressionDlg.
RegressionDlg::InitVariableList()
RegressionDlg::OnCButton1Click()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnCWeightCheckClick
Click RegressionDlg::OnRunClick
y:lnpm_14_11
x:
ln_pmed_11
OLS model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
RegressionDlg::OnCButton1Click()
RegressionDlg::OnCButton3Click()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnRunClick
y:Lnpm_10_03
x:
ln_pmed_03
OLS model
RegressionDlg::DisplayRegression()
Click RegressionDlg::OnCRadio2Selected
Click RegressionDlg::OnRunClick
y:Lnpm_10_03
x:
ln_pmed_03
Spatial Lag model
Click RegressionDlg::OnCRadio3Selected
Click RegressionDlg::OnRunClick
y:Lnpm_10_03
x:
ln_pmed_03
Spatial Error model
RegressionDlg::~RegressionDlg()
Close RegressionDlg.
In LisaMapFrame::~LisaMapFrame
Entering AbstractCoordinator::removeObserver
In LisaCoordinator::~LisaCoordinator().
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
In AbstractCoordinator::~AbstractCoordinator().
Entering AbstractCoordinator::DeallocateVectors()
Exiting AbstractCoordinator::DeallocateVectors()
Exiting AbstractCoordinator::removeObserver
In LisaMapCanvas::~LisaMapCanvas
In AbstractMapCanvas::~AbstractMapCanvas
MapCanvas::~MapCanvas()
Click GdaFrame::OnClose
Project::GetProjectFullPath()

**Comment by jkoschinsky** [comment]
1. run spatial lag and error regressions
2. save results
3. create LISAs with these results (not something you want to do for real but to test if we can replicate the crash)

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.183 (macOS Mojave, 10.14.1). Dec. 19 build.

Can't replicate the crash. Tested using tables with missings. LISA maps and scatter plots created with errors, residuals, and predicted values.
