### ISSUE TITLE
conditional map - custom classification doesn't work

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1774]
When invoking the Map Color Classification option in the conditional map (to change the classification from the default box map) and selecting a custom classification, a new unconditional map is created
with that classification (after asking for a variable name), but the conditional maps are not updated. The other options all work correctly and update the classification for the conditional maps.
It seems that the custom category invokes the standard map creation rather than the conditional maps.

**Comment by bsalas11** [comment]
Fix verified in GeoDa 1.12.1.183  (Windows 10)
