### ISSUE TITLE
conditional plots - allow a single dimension of conditioning

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1775]
Currently, the setup for the conditional plots is to condition on both the horizontal and the vertical axis. There are many situations where only one conditioning variable is relevant, but this is not possible in GeoDa at this point, since both x and y must be specified. For example, this could be remedied by having an empty category in the variable drop down list for x and y. If empty is selected, that axis is not used in the conditioning.

**Comment by bsalas11** [comment]
Fix verified in GeoDa 1.12.1.183  (Windows 10)
