### ISSUE TITLE
Auto weighting in clustering will crash when use points data

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1778]
steps: 
1 load points data set
2 kmeans
3 check "Use geometric centroid"
4 click "Auto Weighting" button

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.181 (macOS Mojave, 10.14.1).

Same procedure, crushed again. Also crushed for kmedian.

1 load points data set
2 kmeans
2.5 choose the number of clusters
3 check "Use geometric centroid"
4 click "Auto Weighting" button

**Comment by lixun910** [comment]
Can you also try it again with the 10 Dec build? Or send me the data you
tested. Thanks very much!

**Comment by Ashitacarl** [comment]
@lixun910 Sorry. It worked on the Dec. 10 build.

GeoDa 1.12.1.181 (macOS Mojave, 10.14.1).

<img width="837" alt="1778" src="https://user-images.githubusercontent.com/45187310/49850070-d6329000-fda1-11e8-80fa-6c610e2f1eb2.png">

**Comment by lixun910** [comment]
Thanks!
