### ISSUE TITLE
field with encoded string (e.g. chinese) doesn't display correctly on screen 

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1780]
This also causes an issue when merge datasource with encoded strings. For example, when a chinese city name is used as key to merge. 

<img width="592" alt="screen shot 2018-12-08 at 8 10 57 pm" src="https://user-images.githubusercontent.com/2423887/49693006-9c555580-fb25-11e8-869f-0de6db9e9c79.png">

**Comment by lixun910** [comment]
This is a report from a Chinese scholar.

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.179 (macOS Mojave, 10.14.1).

Same problem.

<img width="908" alt="1780-2" src="https://user-images.githubusercontent.com/45187310/49848019-a7fc8280-fd98-11e8-92d4-fe2fd29e985c.png">

**Comment by lixun910** [comment]
Please use v181 which is temporary at http://geodacenter.github.io/download_nightly.html <http://geodacenter.github.io/download_nightly.html>
Thanks

**Comment by lixun910** [comment]
And you also need to use Table->Encoding to select proper encoding (e.g. Chinese Simplified GB2312)

**Comment by Ashitacarl** [comment]
@lixun910 

<img width="842" alt="1780-3" src="https://user-images.githubusercontent.com/45187310/49848210-b303e280-fd99-11e8-8968-38ef8b10351a.png">

Don't know why, but seems still not working properly...

**Comment by lixun910** [comment]
@Ashitacarl sorry, this version is not up-to-date, please try to download again 
https://github.com/GeoDaCenter/geoda/releases/download/1.12.1.181/GeoDa1.12.1.181-Installer.dmg
and the date should be 10 December 2018. Thanks!

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.181 (macOS Mojave, 10.14.1).

Fix verified.

<img width="731" alt="1780-3" src="https://user-images.githubusercontent.com/45187310/49849577-dc277180-fd9f-11e8-8feb-97998b493788.png">

**Comment by lixun910** [comment]
Great. Thanks.
