### ISSUE TITLE
GeoDa shows Debug window after open data from a directory with special characters (Windows Only)

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1782]
This is also reported from a Chinese scholar.

1. Use Windows 7 or above
2. Load a datasource from a directory with special encoded characters (e.g.  Gräz/test.shp)
3. Close GeoDa
4. Reopen GeoDa
5. A debug window will be poped up as below: 

<img width="489" alt="screen shot 2018-12-11 at 2 38 41 pm" src="https://user-images.githubusercontent.com/2423887/49834666-3867a280-fd5a-11e8-8e8b-bec0a4710b9c.png">

**Comment by bsalas11** [comment]
Fix verified in GeoDa 1.12.1.183  (Windows 10)
