### ISSUE TITLE
Turn the cluster centers back into the original variable units

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1786]
from Luc: Turn the cluster centers back into the original variable units (with the standard deviation
and the mean)

**Comment by lixun910** [comment]
@Ashitacarl  can you help to verify it? Thanks!

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.189 (macOS Mojave, 10.14.1). Jan. 15 build.

Dataset: Guerry sample and external. 

Fix verified for K-Means, K-Median, K-Medoids, Spectral, Hierarchical. 
Tested using variables with missing values.
Correct me if I misinterpret the question.

But in the cluster centers, there is only one value shown. I assume this to be the mean. Do we also need to include SD?  

<img width="224" alt="1786" src="https://user-images.githubusercontent.com/45187310/51241817-39d14f80-1944-11e9-9323-502bbf5ed682.png">

**Comment by lixun910** [comment]
Great. Thanks, @Ashitacarl 
No, I think SD is not needed and useful in this case, since the cluster centers just give users an idea where are the centers located (that's why Luc wants they are in original variable units). Also, the cluster center is computed as mean center, and it is just one of many ways to evaluate the clustering results.
