### ISSUE TITLE
Crash: Customized Weights

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1788]
From: 
 Details:
os: 3-4-15
vs: 1-12-1-147
/usr/local/geoda/web_plugins/logger.txt
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/seanandrewchen/SSD/geospatial-projects/transit-projects/nyc-subway-turnstile-data/shapefiles/intensity_turnstile_data.shp
Open Layer:intensity_turnstile_data
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/seanandrewchen/SSD/geospatial-projects/transit-projects/nyc-subway-turnstile-data/shapefiles/intensity_turnstile_data.shp
Entering OGRTable::OGRTable
Project::SetupEncoding()
ISO-8859-1
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnOpenPercentile()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
00MON0000
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Entering GdaFrame::OnMapChoices
Open LisaScatterPlotFrame (OnOpenMSPL).
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
Click CreatingWeightDlg::OnIdVariableSelected
Click CreatingWeightDlg::OnCreateNewIdClick
Try to insert unique id (integer, POLY_ID) column in table.
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
-1.37745e+304
Click CreatingWeightDlg::OnCThresholdTextEdit:
-.000000
Click CreatingWeightDlg::OnCThresholdTextEdit:
-1.000000
Click CreatingWeightDlg::OnCThresholdTextEdit:
-16.000000
Click CreatingWeightDlg::OnCThresholdTextEdit:
-160.000000
Click CreatingWeightDlg::OnCThresholdTextEdit:
-1600.000000
Click CreatingWeightDlg::OnCThresholdTextEdit:
1600.000000
Click CreatingWeightDlg::OnInverseDistCheck
Click CreatingWeightDlg::OnInverseDistCheck
Click CreatingWeightDlg::OnCreateClick
CreateWeights()
/home/seanandrewchen/SSD/geospatial-projects/transit-projects/nyc-subway-turnstile-data/geoda_analysis/intensity_turnstile_data.gwt

**Comment by jkoschinsky** [comment]
1. open point shapefile
2. create distance weights
3. keep adjusting the bandwidth to see if you can get it to crash

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.183 (macOS Mojave, 10.14.1). Dec. 19 build.

Can't replicate the crash.

Tested with 
1) Baltimore Home Sales dataset (sample). 5 distance thresholds used. No crash.
2) External point data, 5 distance thresholds used. No crash. 

But GeoDa gets really slow with more obs and higher thresholds.
