### ISSUE TITLE
Projection error with multiple layers

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1790]
GeoDa v181 Mac OSX
headquarter - satellite data shared before

Steps:
load three multi-layer maps: 
1. headquarters (red) and two satellites (green and blue) together (left view)
2. headquarters (red) and satellites (green) (middle view) 
3. headquarters (red) and satellites (blue) (right view) 

in 1, all points are projected correctly.
In 2+3, some of the point erroneously end up in the lake

<img width="1894" alt="geoda projection error" src="https://user-images.githubusercontent.com/13679743/50559520-ddbcc900-0cbd-11e9-9b05-104f90e9143e.png">

**Comment by lixun910** [comment]
@jkoschinsky Hi Julia can you send me the data in 2 and 3? I can't replicate it using the existing data on my side.

**Comment by jkoschinsky** [comment]
Larissa ran it in Windows and Mac with v183 and problem seems to be fixed:

![issue1790_mac_fixed](https://user-images.githubusercontent.com/13679743/50812767-9ea00080-12d9-11e9-9ccb-54d805f88b14.JPG)
