### ISSUE TITLE
Hierarchical Clusters Crash

### ISSUE THREAD

**Issue by bsalas11** [GeoDaCenter/geoda#1791]
GeoDa v183 
Windows 10

Open up hierarchical clusters -> select variables then try to select “number of clusters,”  GeoDa crashes after making this selection

**Comment by jkoschinsky** [comment]
@bsalas11: can you add data so we can replicate? thx

**Comment by bsalas11** [comment]
<img width="446" alt="gurrey" src="https://user-images.githubusercontent.com/46054957/50663641-f3f1b000-0f6f-11e9-8e41-103ea8502cae.PNG">

(selected the first sample shapefile "Guerry")

<img width="521" alt="heirarch" src="https://user-images.githubusercontent.com/46054957/50663705-256a7b80-0f70-11e9-9cf4-ba14719061ac.PNG">

(open up "hierarchical clustering"
after variables are selected, trying to designate the "number of clusters" causes GeoDa to crash)

**Comment by lixun910** [comment]
@bsalas11  Can you help to verify a fix using V185? Thanks!
https://www.dropbox.com/s/w80gr3jboslgsn1/GeoDa1.12.1.185-Installer.dmg?dl=0

**Comment by bsalas11** [comment]
@lixun910 Can you send me v.185 for Windows instead of .dmg?

**Comment by bsalas11** [comment]
GeoDa 1.12.1.185 (Windows 10).
Fix verified.

![image](https://user-images.githubusercontent.com/46054957/51054715-469c1f00-15a3-11e9-8aac-1c64613ed89a.png)

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.185 (macOS Mojave, 10.14.1). Jan. 11 build.

No crash observed.

<img width="880" alt="1791" src="https://user-images.githubusercontent.com/45187310/51065647-9c84bd00-15cb-11e9-97ef-da5b2ae49818.png">

BUT, when I tested with K-Medians (exactly the same dataset and same steps: select variables > number of clusters > Run > Crash). GeoDa crashed. @lixun910 

No crash observed for K-Means, Hierarchical, Spectral, K-Medoids.

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.187 (macOS Mojave, 10.14.1). Jan. 11 build.

No crash observed for K-Medians following the same steps.

<img width="600" alt="1791-2" src="https://user-images.githubusercontent.com/45187310/51070453-08d0e200-1607-11e9-82dc-b30dbdce8b8b.png">
