### ISSUE TITLE
Differentiate between values in co-location map

### ISSUE THREAD

**Issue by Ashitacarl** [GeoDaCenter/geoda#1794]
This issue is similar to the closed issue #1113 
When values get large, the color difference disappears (between high-high values and high-others). See below. 

Two examples with NYC sample data.

<img width="656" alt="1738" src="https://user-images.githubusercontent.com/45187310/50801226-5f59bb80-12a9-11e9-93ad-3b5f0a5fa91a.png">

**Comment by lixun910** [comment]
@Ashitacarl  Can you help to verify a fix using V185? Thanks!
https://www.dropbox.com/s/w80gr3jboslgsn1/GeoDa1.12.1.185-Installer.dmg?dl=0

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.185 (macOS Mojave, 10.14.1). Jan. 9 build.

Fix verified.

<img width="747" alt="1794-3" src="https://user-images.githubusercontent.com/45187310/50996001-71746d80-14e6-11e9-818a-ff1cd660edae.png">
