### ISSUE TITLE
Crash: grouped variables + Conditional plots

### ISSUE THREAD

**Issue by Ashitacarl** [GeoDaCenter/geoda#1795]
GeoDa 1.12.1.183 (macOS Mojave, 10.14.1). Dec. 19 build.

Data used: NYC sample data; External data w and w/o missing values.

After creating grouped variables in time editor, GeoDa crashes instantly when implementing conditional plots (maps/histograms/scatter plots). No crash for all other plots (box plot, histogram scatter matrix etc). Similar to an old issue #1228 

Warning message (clicking _any_ of the three options causes crash):

<img width="422" alt="1795" src="https://user-images.githubusercontent.com/45187310/50806808-d4cf8700-12bd-11e9-8cfc-715ab8ce3850.png">

**Comment by lixun910** [comment]
@Ashitacarl Thank you! Can you give me more specific steps to replicate this crash?

**Comment by Ashitacarl** [comment]
@lixun910 Sure!

1. Open NYC data;
2. Time editor > create group variables (e.g., forhis06 - forhist09);
3. Leave time editor open;
4. Clicking conditional plot (either of map/scatter plot/histogram) leads to crash.

If time editor is closed after creating the group variable, there is no crash.

<img width="975" alt="1796-2" src="https://user-images.githubusercontent.com/45187310/50884873-b8ad1200-13b1-11e9-9050-10150aedd050.png">

**Comment by lixun910** [comment]
@Ashitacarl  Can you help to verify a fix using V185? Thanks!
https://www.dropbox.com/s/w80gr3jboslgsn1/GeoDa1.12.1.185-Installer.dmg?dl=0

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.185 (macOS Mojave, 10.14.1). Jan. 9 build.

The same problem persists.

<img width="672" alt="1795-3" src="https://user-images.githubusercontent.com/45187310/50996357-463e4e00-14e7-11e9-858d-b40ead50a3fe.png">

**Comment by lixun910** [comment]
@Ashitacarl can you help to verify the fix using this new V185? Thanks!
https://www.dropbox.com/s/w80gr3jboslgsn1/GeoDa1.12.1.185-Installer.dmg?dl=0

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.185 (macOS Mojave, 10.14.1). Jan. 11 build.

Fix verified for Group Variable + Conditional Map and Conditional Histogram.
The problem persists for **Conditional Scatter Plot**.

Relatedly. In the conditional histogram dialog, we cannot select the time period. See below.

<img width="1210" alt="1795-4" src="https://user-images.githubusercontent.com/45187310/51065500-bc67b100-15ca-11e9-901a-060ef4522c12.png">

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.187 (macOS Mojave, 10.14.1). Jan. 11 build.

Fix verified for Group Variable + Conditional Scatter Plot (and also tested conditional histogram/map).
No crash observed.

Fix verified for variable setting dialog in conditional histogram. It now allows selection of different time period for group variables. 

<img width="595" alt="1795-5" src="https://user-images.githubusercontent.com/45187310/51070428-89431300-1606-11e9-96ab-ccea4c098cc4.png">
