### ISSUE TITLE
Crash Report: Edit merged csv table

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1798]
From: 
 Details:
os: 3-4-15
vs: 1-12-1-147
/usr/local/geoda/web_plugins/logger.txt
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/caillaul/Bureau/M1_PEPS/Communes.shp
Open Layer:Communes
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/caillaul/Bureau/M1_PEPS/Communes.shp
Entering OGRTable::OGRTable
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
Open MergeTableDlg.
In TableFrame::OnActivate
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
Open CsvFieldConfDlg.
CsvFieldConfDlg::PrereadCSV()
CsvFieldConfDlg::UpdateFieldGrid()
CsvFieldConfDlg::ReadCSVT()
CsvFieldConfDlg::UpdatePreviewGrid()
CsvFieldConfDlg::UpdateXYcombox()
CsvFieldConfDlg::OnSetupLocale()
Open LocaleSetupDlg.
Click LocaleSetupDlg::OnOkClick
CsvFieldConfDlg::PrereadCSV()
CsvFieldConfDlg::UpdatePreviewGrid()
CsvFieldConfDlg::OnOkClick()
CsvFieldConfDlg::WriteCSVT()
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/caillaul/Bureau/M1_PEPS/correct1.csv
Open Layer:correct1
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
ds:/home/caillaul/Bureau/M1_PEPS/correct1.csv layer: correct1
In MergeTableDlg::OnKeyChoice()
In MergeTableDlg::OnKeyChoice()
Entering MergeTableDlg::OnIncAllClick()
In MergeTableDlg::OnMergeClick()
Open FieldNameCorrectionDlg:
ScrolledWidgetsPane::RemoveIllegalChars
CODE_INSEE
CODE_INSEE
ScrolledWidgetsPane::TruncateFieldName
CODE_INSEE
ScrolledWidgetsPane::RenameDupFieldName
CODE_INSEE
ScrolledWidgetsPane::TruncateFieldName
CODE_INSEE
CODE_SEE
CODE_SEE_1
ScrolledWidgetsPane::RemoveIllegalChars
ZH (1)
ZH1
ScrolledWidgetsPane::TruncateFieldName
ZH1
ScrolledWidgetsPane::RenameDupFieldName
ZH1
ZH1
ScrolledWidgetsPane::RemoveIllegalChars
agri (1)
agri1
ScrolledWidgetsPane::TruncateFieldName
agri1
ScrolledWidgetsPane::RenameDupFieldName
agri1
agri1
ScrolledWidgetsPane::RemoveIllegalChars
artif (1)
artif1
ScrolledWidgetsPane::TruncateFieldName
artif1
ScrolledWidgetsPane::RenameDupFieldName
artif1
artif1
ScrolledWidgetsPane::RemoveIllegalChars
eau (1)
eau1
ScrolledWidgetsPane::TruncateFieldName
eau1
ScrolledWidgetsPane::RenameDupFieldName
eau1
eau1
ScrolledWidgetsPane::RemoveIllegalChars
foret (1)
foret1
ScrolledWidgetsPane::TruncateFieldName
foret1
ScrolledWidgetsPane::RenameDupFieldName
foret1
foret1
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
CODE_SEE_1
ScrolledWidgetsPane::IsFieldNameValid
ZH1
ScrolledWidgetsPane::IsFieldNameValid
agri1
ScrolledWidgetsPane::IsFieldNameValid
artif1
ScrolledWidgetsPane::IsFieldNameValid
eau1
ScrolledWidgetsPane::IsFieldNameValid
foret1
In FieldNameCorrectionDlg
Out FieldNameCorrectionDlg

**Comment by jkoschinsky** [comment]
We've been trying to catch this bug forever but no luck so far.

It looks like they:

- opened a shapefile
- then merged a csv file to the shapefile
- the csv had some invalid field names (duplicate names, "illegal" characters, truncated names, invalid names)
- they then edited the fields
- this generated a crash

If you can create a csv with underscores, parentheses, long names, other special stuff and try to merge it to a shapefile and see if you can track this down, that would be great. Thx

**Comment by lixun910** [comment]
same as #1694
