### ISSUE TITLE
weights interface - variable distance weights interface

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1800]
Weights file creation dialog for variable weights: button should be "Variables" instead of "Table variables". The only variables available are from the Table, so that is redundant.

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.193 (macOS Mojave, 10.14.1). Jan. 24 build.

Fix verified. "Table Variables" now changed into "Variables".

<img width="470" alt="1801" src="https://user-images.githubusercontent.com/45187310/51772740-63137d80-20b2-11e9-8b70-8fa2cb546a33.png">
