### ISSUE TITLE
weights interface - missing default distance metric for variable weights

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1801]
After selecting "Table variables" in the distance weight dialog, the "Distance metric" becomes blank. It should give "Euclidean Distance" as the default, as it does for centroid distances. As it is, there is an extra step involved in selecting the distance metric (V 191 on mac).

<img width="486" alt="screen shot 2019-01-23 at 1 36 18 pm" src="https://user-images.githubusercontent.com/4008351/51638859-640ea880-1f14-11e9-92a5-41ca815dda8c.png">

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.193 (macOS Mojave, 10.14.1). Jan. 24 build.

Fix verified. Euclidean Distance is used as default.

<img width="470" alt="1801" src="https://user-images.githubusercontent.com/45187310/51772685-424b2800-20b2-11e9-9288-2dc99c4661dc.png">
