### ISSUE TITLE
Re-organize Tool menu and add a Tools icon to the toolbar

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1802]
(from Luc)
Tools menu (and icon) would become:
```
- Weights Manager
- Shape > Points from Table
              > Create Grid
- Spatial Join
```

and GeoCode, Spatial Join, Points from Table and GeoCode would be removed from the table option.

**Comment by lixun910** [comment]
Add icon between the table and the weights manager icons on toolbar

**Comment by lixun910** [comment]
<img width="1095" alt="screen shot 2019-01-23 at 9 32 17 pm" src="https://user-images.githubusercontent.com/2423887/51654710-642f9800-1f56-11e9-9fea-7f574f69717f.png">

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.193 (macOS Mojave, 10.14.1). Jan. 24 build.

Fix verified.
1. Tools Option:
<img width="152" alt="1802-1" src="https://user-images.githubusercontent.com/45187310/51772087-b97fbc80-20b0-11e9-9f2b-0e5ab174abd4.png">
```
- Weights Manager
- Shape > Points from Table
              > Create Grid
- Spatial Join
```

2. Table Option:
<img width="651" alt="1802-2" src="https://user-images.githubusercontent.com/45187310/51772300-4296f380-20b1-11e9-9579-3cf9989ad297.png">

GeoCode, Spatial Join, Points from Table removed from the Table Option.

3. Tool icon added between Table and Weights Manager:
<img width="524" alt="1802-3" src="https://user-images.githubusercontent.com/45187310/51772319-54789680-20b1-11e9-8c4e-560c6082732f.png">
