### ISSUE TITLE
multi layer not working after base layer?

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1804]
V 193 on Mac. Moving a point layer on top of a polygon layer doesn't seem to work when invoked from the "edit map layer" icon. Admittedly, the sequence of operations was a bit complex, so it's not clear where exactly the problem occurs. At first, when loading the two maps, everything works fine. Then I added a base layer, which hid one of the layers. After removing the base layer, moving the points back on top of the polygons with the icon didn't work.

<img width="865" alt="screen shot 2019-01-25 at 8 47 08 am" src="https://user-images.githubusercontent.com/4008351/51760067-8290b300-207e-11e9-8abc-d391f12abd66.png">

**Comment by lanselin** [comment]
To be more precise, the figure shows the point layer on top in the dialog, but they do not show on the map.

**Comment by lanselin** [comment]
I suspect it has something to do with interaction with the base layer. It happened again after I put in a base layer and then removed it.

**Comment by lixun910** [comment]
V195
