### ISSUE TITLE
multi layer: pan seems to break connection

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1806]
Panning seems to break the connection between the two layers (v 193). As with the previous issue, it is hart to tell what exactly triggered this, but after changing the outline color (and switching between outlines and boundary only), I used panning to move around. The result it that the point layer (the main layer) moved, but the polygon layer did not (see screen shot). The points should be on top of the polygons, not way above them.

<img width="680" alt="screen shot 2019-01-25 at 10 31 49 am" src="https://user-images.githubusercontent.com/4008351/51765487-c25e9700-208c-11e9-840b-79238e2d4ce9.png">

**Comment by lixun910** [comment]
This issue still exists when load multiple layers with different projections: e.g. first layer is EPSG 4269 and second layer is EPSG3857.

**Comment by lixun910** [comment]
Add "Projection EPSG code" information in Project Information dialog

<img width="708" alt="Screen Shot 2019-03-28 at 3 20 31 PM" src="https://user-images.githubusercontent.com/2423887/55197123-d39c5080-516e-11e9-91cc-51217a6e9255.png">

**Comment by lixun910** [comment]
Allow a user to set CRS (projection) when saving a data source.  The CRS is in Proj4 format. If a user doesn't familiar with CRS, he/she can use the "earth" button to load CRS (projection) from other data source that has targeting CRS (projection):

<img width="901" alt="Screen Shot 2019-03-28 at 8 55 52 PM" src="https://user-images.githubusercontent.com/2423887/55208661-38ba6b00-519c-11e9-8fc7-dd9d1d5abd8b.png">

**Comment by lixun910** [comment]
V219

**Comment by lixun910** [comment]
Fix verified on Mac and Ubuntu 18.04.

<img width="792" alt="Screen Shot 2019-08-02 at 11 51 14 AM" src="https://user-images.githubusercontent.com/2423887/62392265-e0192700-b51b-11e9-9693-d952a245030c.png">

<img width="646" alt="Screen Shot 2019-08-02 at 11 53 18 AM" src="https://user-images.githubusercontent.com/2423887/62392366-22daff00-b51c-11e9-9464-c8ec5573b2bf.png">
