### ISSUE TITLE
table variable calculation vs. caculator

### ISSUE THREAD

**Issue by GoogleCodeExporter** [GeoDaCenter/geoda#181]
```
there is both a table variable calculation and a calculator item in the menu. 
the calculator is Mark’s experimental calculator, but it is still very buggy 
and not very user friendly. on the other hand, it is extremely flexible. we 
need to make a decision as to whether to keep it (will need work streamlining) 
or drop it and stick with the clunky “variable calculation”
```

Original issue reported on code.google.com by `lixun...@gmail.com` on 30 Jun 2015 at 7:25

**Comment by jkoschinsky** [comment]
Can we integrate the "Calculator" as an additional tab in the "Variable Calculation" dialog?
e.g. we could call it "Custom (Beta)"

when you click on the Custom (Beta) tab, it would open the Calculator dialog.
Right now we have so many option in the table right-click option that people are getting confused.

**Comment by lixun910** [comment]
move it to future release
