### ISSUE TITLE
Table - stack: problem with edit variable properties

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1810]
It seems that something is wrong with the edit variable properties functionality after two tables have been stacked. Here is what I did. 1. edit variable properties to set number of decimals for "value" to 2 in table1; 2. do same in table2; 3. stack table1 and table2.

In the new stacked table, the number of decimals is 15 or something, even though in the edit variable properties it is given as 2 (see screen shot). It is possible to adjust the number of decimals in the stacked table, but first they need to be changed to a different number, e.g., 3, and then they can be changed back to 2. But initially, there is a mismatch with what is shown in the table and listed in the edit variable properties dialog.

<img width="390" alt="screen shot 2019-02-07 at 4 25 48 pm" src="https://user-images.githubusercontent.com/4008351/52451873-a1b72800-2af5-11e9-8874-69c47ee84e62.png">

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.201 (macOS Mojave, 10.14.3). Feb. 20 build.

Fix verified. Now stacking tables (point data) does not produce mismatch of actual and displayed decimal degrees.

However, when I tried to stack **csv tables** (no geometry), GeoDa warns me that line data is not supported. See below.

<img width="420" alt="1810-2" src="https://user-images.githubusercontent.com/45187310/53244090-6bd67f80-366f-11e9-937f-3f5cef8e82f5.png">

**Comment by jkoschinsky** [comment]
that's correct -- line data will only be supported later.

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.211 (macOS Mojave, 10.14.3). Mar. 18 build.

Fix verified. Stacking csv tables does not produce the geometry error mentioned above.
