### ISSUE TITLE
bounding box issue with multiple layers

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1817]
If GeoDa loads multiple layers, "full extent" needs to be explicitly set to that for the top layer.
<img width="599" alt="screen shot 2019-02-19 at 8 29 33 pm" src="https://user-images.githubusercontent.com/2423887/53064461-248c9b00-3485-11e9-8c4a-e12be895c167.png">

Besides, in Map Layer Setting dialog, re-ordering the layers will trigger the map to set full extent using top layer automatically. If map already zoomed or panned, the extent will be kept (should be no change).
<img width="383" alt="screen shot 2019-02-19 at 8 30 55 pm" src="https://user-images.githubusercontent.com/2423887/53064548-746b6200-3485-11e9-9d4d-42d5f0efd269.png">

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.201 (macOS Mojave, 10.14.3). Feb. 20 build.

Fix verified. 
When multiple layers are loaded, the map extent uses the first layer loaded for full extent.
When the order of different layers changes, the top layer will be used automatically to set full extent. For zoomed/panned maps, reordering does not make changes to the extent (it only brings the top layer to front). 

@lixun910 Please let me know if I miss anything.

**Comment by lixun910** [comment]
@Ashitacarl Yes, that should cover all cases. Thanks!
