### ISSUE TITLE
Edit String content in Table crashes GeoDa in V197

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1818]
Using GeoDa 1.12.1.197: open Guerry dataset, edit "CODE_DE" column in Table: change 01 to 00.

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.201 (macOS Mojave, 10.14.3). Feb. 20 build.

Tested on a couple of string columns in Guerry sample dataset. No crash observed.
