### ISSUE TITLE
Table: editing is limited to 10 digits in a integer field 

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1819]

**Comment by lixun910** [comment]
Step: (in Table) right click->Add Variable; 
Add a new integer variable
Edit the cell in the newly created column, e.g. input 12345678901 
It only allows to input up to 10 digits.

Fixed in V201

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.201 (macOS Mojave, 10.14.3). Feb. 20 build.

Fix verified. Integers now allow more than 10 digits (the new limit is 19 digits).

<img width="292" alt="1819" src="https://user-images.githubusercontent.com/45187310/53189592-80fad200-35cd-11e9-9d7e-db272c5396c2.png">

**Comment by lixun910** [comment]
Thanks, @Ashitacarl 
Yes, the new limit is 19 digits, which is for max value of int64 number: 9223372036854775807

**Comment by lixun910** [comment]
When input number in the newly created column (integer type), the number is NOT right-aligned.

**Comment by lixun910** [comment]
continue: 
1. “displayed decimal places” in table can't be saved to GeoDa project (.gda) file.
2. add "default displayed decimal places" option in preference dialg

**Comment by lixun910** [comment]
Users can set "default displayed decimal places" in the Preference dialog. 
1. Users need to reopen the dataset to apply the new setting.
2. If using a GeoDa project file (*.gda), the displayed decimal places in *.gda file will overwrite the setting in the Preference dialog.



<img width="721" alt="screen shot 2019-03-06 at 1 38 30 pm" src="https://user-images.githubusercontent.com/2423887/53912062-553c0b00-4015-11e9-9878-52f2d7ed35b6.png">

**Comment by lixun910** [comment]
Fix in V205
When save a GeoDa .gda file, the displayed decimal places should be written in .gda file. GeoDa will read and use the displayed decimal places in .gda file.

<img width="610" alt="screen shot 2019-03-06 at 1 48 56 pm" src="https://user-images.githubusercontent.com/2423887/53912859-1c9d3100-4017-11e9-81ff-d3ca8296ce93.png">

**Comment by lixun910** [comment]
The fix of this issue by introducing new types of cell editor also touches the logic of "Add ID Variable":

In this fix, when a new column is inserted into table, all cell values are set to undefined (or empty) flag. So that user will get a "empty" newly created column:
<img width="140" alt="Screen Shot 2019-03-08 at 1 48 21 PM" src="https://user-images.githubusercontent.com/2423887/54054966-db3c8b00-41a8-11e9-8d3f-763cbb97f303.png">
 
However, using "Add ID variable" to insert a new column with values, the undefined flags should be set to "false" to all the program to read the values in this column. Otherwise, the POLY_ID column will be empty:
<img width="144" alt="Screen Shot 2019-03-08 at 1 54 18 PM" src="https://user-images.githubusercontent.com/2423887/54055245-af6dd500-41a9-11e9-8629-7fd4266feb6e.png">

This issue should be fixed.

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.211 (macOS Mojave, 10.14.3). Mar. 18 build.

Fix verified.
1. New option "Default displayed decimal places in Table" in Preferences/Data Source that applies to all tables imported to GeoDa. This only influences the displayed decimal places but not actual decimal places. 

2. GeoDa project file (*.Gda) can save the decimal places and overwrite that specified in default preferences.

<img width="655" alt="1819-3" src="https://user-images.githubusercontent.com/45187310/54656051-2ea8b600-4a92-11e9-92c3-f8b95ac1eff8.png">

2. Add ID variable does not produce an empty column.
