### ISSUE TITLE
Crash: Thiessen polygons and centroids with duplicate points

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1821]
From: 
 Details:
os: 3-4-15
vs: 1-12-1-147
/usr/local/geoda/web_plugins/logger.txt
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
Open CsvFieldConfDlg.
CsvFieldConfDlg::PrereadCSV()
CsvFieldConfDlg::UpdateFieldGrid()
CsvFieldConfDlg::ReadCSVT()
CsvFieldConfDlg::UpdatePreviewGrid()
CsvFieldConfDlg::UpdateXYcombox()
CsvFieldConfDlg::OnOkClick()
CsvFieldConfDlg::WriteCSVT()
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/orangebacked/Downloads/new_geo_diag.csv
Open Layer:new_geo_diag
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/orangebacked/Downloads/new_geo_diag.csv
Entering OGRTable::OGRTable
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
field_1
Open BoxPlotCanvas.
Close BoxPlotCanvas.
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
IdDiagnostico
IdDiagnostico
Open CartogramNewFrame.
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Project::GetVoronoiRookNeighborGal()
Project::GetVoronoiRookNeighborMap()
Project::IsPointDuplicates()
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()

**Comment by jkoschinsky** [comment]
Looks like a crash related to Thiessen polygons and centroids with duplicate points.

Try:
1. loading larger point dataset with duplicate XYs
2. create Thiessen polygons
3. save centroids

**Comment by lixun910** [comment]
@jkoschinsky  This report is from GeoDa version 1-12-1-147.  It should be fixed in https://github.com/GeoDaCenter/geoda/issues/1380

**Comment by jkoschinsky** [comment]
ok g8
