### ISSUE TITLE
Crash: file name and table field names with special characters

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1822]
From: 
 Details:
os: 3-4-18
vs: 1-12-1-147
/usr/local/geoda/web_plugins/logger.txt
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
Open CsvFieldConfDlg.
CsvFieldConfDlg::PrereadCSV()
CsvFieldConfDlg::UpdateFieldGrid()
CsvFieldConfDlg::ReadCSVT()
CsvFieldConfDlg::UpdatePreviewGrid()
CsvFieldConfDlg::UpdateXYcombox()
CsvFieldConfDlg::OnHeaderCmbClick()
CsvFieldConfDlg::PrereadCSV()
CsvFieldConfDlg::UpdateFieldGrid()
CsvFieldConfDlg::UpdatePreviewGrid()
CsvFieldConfDlg::UpdateXYcombox()
CsvFieldConfDlg::OnOkClick()
CsvFieldConfDlg::WriteCSVT()
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/asus/Завантаження/Заявки, видача, оплата. Клієнти - Заявки.csv
Open Layer:Заявки, видача, оплата. Клієнти - Заявки
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/asus/Завантаження/Заявки, видача, оплата. Клієнти - Заявки.csv
Entering OGRTable::OGRTable
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
In TableFrame::OnActivate
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Заявка
Click VariableSettingsDlg::OnOkClick:
field_2
Open HistogramFrame.

**Comment by jkoschinsky** [comment]
Looks like a crash related to table field names.

Let's see if we can replicate with the same special characters:

1. create csv file with this file name: 
авантаження/Заявки, видача, оплата. Клієнти - Заявки.csv

2. add field name: 
Заявка

3. open histogram

**Comment by lixun910** [comment]
This should be fixed as well:
<img width="672" alt="screen shot 2019-03-01 at 3 25 02 pm" src="https://user-images.githubusercontent.com/2423887/53669980-38c75980-3c36-11e9-9251-48c2c7c05ed0.png">

**Comment by lixun910** [comment]
This is related to https://github.com/GeoDaCenter/geoda/issues/1694
