### ISSUE TITLE
Crash Report: export data

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1823]
From: 
 Details:
os: 3-4-13
vs: 1-12-1-57
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/arminakvn/Google Drive/mario/exporting.csv
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
In TableFrame::OnActivate
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/arminakvn/Google Drive/routing_run/results/analysis_of_results/upd2shp/upd2.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
Open RangeSelectionDlg
In RangeSelectionDlg::OnSelUnselTextChange()
In RangeSelectionDlg::CheckApplySaveSettings()
In RangeSelectionDlg::OnSelUnselTextChange()
In RangeSelectionDlg::CheckApplySaveSettings()
In RangeSelectionDlg::OnRangeTextChange()
In RangeSelectionDlg::OnRangeTextChange()
In RangeSelectionDlg::OnSelUnselTextChange()
In RangeSelectionDlg::CheckApplySaveSettings()
In RangeSelectionDlg::OnSelUnselTextChange()
In RangeSelectionDlg::CheckApplySaveSettings()
In RangeSelectionDlg::OnSelUnselTextChange()
In RangeSelectionDlg::CheckApplySaveSettings()
In RangeSelectionDlg::OnSelUnselTextChange()
In RangeSelectionDlg::CheckApplySaveSettings()
In RangeSelectionDlg::CheckApplySaveSettings()
Open DataViewerDeleteColDlg.
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnDelete()
BNK___PT_1
In RangeSelectionDlg::CheckApplySaveSettings()
TM_CC_PT_1
In RangeSelectionDlg::CheckApplySaveSettings()
TM_CC_PT
In RangeSelectionDlg::CheckApplySaveSettings()
TM_CC_FOT
In RangeSelectionDlg::CheckApplySaveSettings()
TM_CC_CAR
In RangeSelectionDlg::CheckApplySaveSettings()
TM_BNK_PT
In RangeSelectionDlg::CheckApplySaveSettings()
TM_BNK_FOT
In RangeSelectionDlg::CheckApplySaveSettings()
TM_BNK_CAR
In RangeSelectionDlg::CheckApplySaveSettings()
PRC_WHT
In RangeSelectionDlg::CheckApplySaveSettings()
PRC_RENT
In RangeSelectionDlg::CheckApplySaveSettings()
PRC_POV
In RangeSelectionDlg::CheckApplySaveSettings()
PRC_LAT
In RangeSelectionDlg::CheckApplySaveSettings()
PRC_FOR
In RangeSelectionDlg::CheckApplySaveSettings()
PRC_BLC
In RangeSelectionDlg::CheckApplySaveSettings()
PRC_ASIA
In RangeSelectionDlg::CheckApplySaveSettings()
POVERTY
In RangeSelectionDlg::CheckApplySaveSettings()
POP
In RangeSelectionDlg::CheckApplySaveSettings()
BNK_CC_PT
In RangeSelectionDlg::CheckApplySaveSettings()
BNK_CC_FOT
In RangeSelectionDlg::CheckApplySaveSettings()
BNK_CC_CAR
In RangeSelectionDlg::CheckApplySaveSettings()
PCOUNT
In RangeSelectionDlg::CheckApplySaveSettings()
CITYNAME
In RangeSelectionDlg::CheckApplySaveSettings()
intptlon
In RangeSelectionDlg::CheckApplySaveSettings()
intptlat
In RangeSelectionDlg::CheckApplySaveSettings()
awater
In RangeSelectionDlg::CheckApplySaveSettings()
aland
In RangeSelectionDlg::CheckApplySaveSettings()
namelsad
In RangeSelectionDlg::CheckApplySaveSettings()
Open ExportDataDlg in its Init()
In ExportDataDlg::BrowseExportDataSource()
In ExportDataDlg::OnOkClick()
ds:/home/arminakvn/Google Drive/mario/shapeall.shp
Project::GetSpatialReference()
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
ogc_fid
ScrolledWidgetsPane::IsFieldNameValid
geoid
In FieldNameCorrectionDlg
Out FieldNameCorrectionDlg
start OGRLayerProxy::AddFreatures()
Out OGRDataAdapter::ExportDataSource()

**Comment by jkoschinsky** [comment]
please try:
1. load shapefile from google drive
2. delete columns and save
3. select range of observations
4. save as new file

**Comment by lixun910** [comment]
same as #1905
