### ISSUE TITLE
Programa GEOda

### ISSUE THREAD

**Issue by lvsarauz** [GeoDaCenter/geoda#1824]
El programa GEODA cuando instalamos en español, se desactiva todo el menú de Tabla y Ayuda. Funciona correctamente instalándolo en Inglés

**Comment by jkoschinsky** [comment]
When the GEODA program is installed in Spanish, it deactivates the
entire Table and Help menu. Works correctly by installing it in
English.

**Comment by lixun910** [comment]
@lvsarauz Thanks for your feedback!  Can you tell us the GeoDa version number, and which OS are you using (Windows, Mac or Linux)? 

I just tested using GeoDa v161 and latest V201. In both versions, GeoDa in Spanish shows Table and Help menu correctly (see screenshot). Can you also try our latest GeoDa 1.12.1.201 to see if the issue has been addressed? Thanks!

GeoDa V201 download for Mac, Windows and Ubuntu:
http://geodacenter.github.io/download_nightly.html

<img width="967" alt="screen shot 2019-02-27 at 10 06 27 am" src="https://user-images.githubusercontent.com/2423887/53508915-f526f100-3a77-11e9-8804-d45e72c9bb18.png">
