### ISSUE TITLE
Ubuntu 18.04 64 bits build not working

### ISSUE THREAD

**Issue by ThomasG77** [GeoDaCenter/geoda#1827]
I do the following to install the package

    cd /tmp/
    wget https://s3-us-west-2.amazonaws.com/geodasoftware/geoda_1.12-ubuntu1804.deb
    sudo dpkg -i geoda_1.12-ubuntu1804.deb
    sudo apt -f install

Then, I tried to run the shortcut through the GUI, nothing appeared
Then, I run through the command line the script

    /usr/bin/run_geoda.sh

It returns the following error `/usr/local/geoda/GeoDa: symbol lookup error: /usr/local/geoda/GeoDa: undefined symbol: _ZN10OGRFeature16GetFieldAsStringEi`

The error is clearly GDAL related with the name of the symbol containing `OGRFeature`

It could be related to the fact the code seems to depend from GDAL 1.9.2 whereas the default GDAL version and *.so files on Ubuntu 18.04 are using GDAL 2.2.3 according to https://packages.ubuntu.com/search?keywords=gdal&searchon=names&suite=bionic&section=all

**Comment by lixun910** [comment]
@ThomasG77  Thanks for reporting this issue! Our early version of GeoDa on Ubuntu does depend on GDAL 1.9.2 but should be distributed with GeoDa deb. However, I doubt it might be conflicting with existing GDAL 2.2.3 if installed. 

Can you try our latest GeoDa for Ubuntu 18.04 that depends on GDAL that Ubuntu managed to install? http://geodacenter.github.io/download_nightly.html Let me know if this new installer works. Thanks!

**Comment by ThomasG77** [comment]
It does not work better. I got the same issue.
I also see following the link 
http://geodacenter.github.io/download_nightly.html that deb file named "Ubuntu 18.04 (64-bit) Download" in fact points to a "xenial" build (so 16.04 and not 18.04 aka "bionic") but I don't know if it's normal?

**Comment by lixun910** [comment]
@ThomasG77 Yes, the file name is not updated, and should be bionic. 
As I mentioned, if GDAL has already been installed on your Ubuntu, it might conflict with what GeoDa depends on. Here is what's described in GeoDa's DEBIAN control file:
```
Depends: libcurl4-openssl-dev, libgdal-dev, zlib1g, libexpat1, freeglut3, libreadline7, libgtk-3-0, libc-dev-bin, libssl1.0.0, libwebkitgtk-1.0-0
```
In Ubuntu 18.04, the latest GeoDa depends on GDAL 2.0 managed by Ubuntu 18.04:
```
/usr/local/geoda$ ldd GeoDa | grep gdal
	libgdal.so.20 => /usr/lib/libgdal.so.20 (0x00007f47f68f4000)
```
If you have GDAL >2.0 installed already, one solution is to downgrade it, or remove it and let Ubuntu system install the GDAL dependency for GeoDa.

Can you also post the output of: ?
```
ldd /usr/local/geoda/GeoDa
```
Thanks!

**Comment by ThomasG77** [comment]
> If you have GDAL >2.0 installed already, one solution is to downgrade it, or remove it and let Ubuntu system install the GDAL dependency for GeoDa.

If only it was possible: Ubuntu 18.04 already bundles by default GDAL > 2.0 so there is no downgrade path. I could do a manual GDAL build and changes symlink but that would broke all the other sofware installed that need GDAL > 2.0.

The output of `ldd /usr/local/geoda/GeoDa` is the following:

	linux-vdso.so.1 (0x00007fff8d054000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f2a5b67e000)
	libGLU.so.1 => /usr/lib/x86_64-linux-gnu/libGLU.so.1 (0x00007f2a5b40f000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f2a5b0d7000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f2a5aed1000)
	libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007f2a5acc9000)
	libgtk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 (0x00007f2a5a687000)
	libgdk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0 (0x00007f2a5a3d2000)
	libpangocairo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007f2a5a1c5000)
	libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f2a59ea8000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007f2a59c84000)
	libpango-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007f2a59a37000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f2a597e3000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f2a594cd000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f2a5929b000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f2a59033000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f2a58e01000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f2a58be4000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2a589e0000)
	libgdal.so.20 => /usr/lib/libgdal.so.20 (0x00007f2a57664000)
	libcurl.so.4 => /usr/lib/x86_64-linux-gnu/libcurl.so.4 (0x00007f2a573e5000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f2a571dd000)
	libwebkitgtk-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libwebkitgtk-1.0.so.0 (0x00007f2a55006000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2a54c7d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2a548df000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2a546c7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2a544a8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2a540b7000)
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007f2a53e86000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007f2a53bd0000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f2a539a8000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f2a53796000)
	libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007f2a5357b000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f2a53374000)
	libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f2a53170000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f2a52f6a000)
	libatk-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007f2a52d44000)
	libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007f2a529a5000)
	libpangoft2-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007f2a5278f000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f2a5254a000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f2a52340000)
	libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007f2a5213d000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f2a51f2d000)
	libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007f2a51d22000)
	libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007f2a51b18000)
	libXcomposite.so.1 => /usr/lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007f2a51915000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f2a51712000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f2a5145e000)
	libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f2a511b9000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f2a50fb6000)
	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f2a50da9000)
	libthai.so.0 => /usr/lib/x86_64-linux-gnu/libthai.so.0 (0x00007f2a50ba0000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f2a50998000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f2a50726000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2a5d336000)
	libproj.so.13 => /usr/lib/x86_64-linux-gnu/libproj.so.13 (0x00007f2a504b1000)
	libpoppler.so.73 => /usr/lib/x86_64-linux-gnu/libpoppler.so.73 (0x00007f2a5001d000)
	libjson-c.so.3 => /lib/x86_64-linux-gnu/libjson-c.so.3 (0x00007f2a4fe12000)
	libfreexl.so.1 => /usr/lib/x86_64-linux-gnu/libfreexl.so.1 (0x00007f2a4fc09000)
	libqhull.so.7 => /usr/lib/x86_64-linux-gnu/libqhull.so.7 (0x00007f2a4f9af000)
	libgeos_c.so.1 => /usr/lib/x86_64-linux-gnu/libgeos_c.so.1 (0x00007f2a4f77e000)
	libwebp.so.6 => /usr/lib/x86_64-linux-gnu/libwebp.so.6 (0x00007f2a4f515000)
	libepsilon.so.1 => /usr/lib/x86_64-linux-gnu/libepsilon.so.1 (0x00007f2a4f2fd000)
	libodbc.so.2 => /usr/lib/x86_64-linux-gnu/libodbc.so.2 (0x00007f2a4f090000)
	libodbcinst.so.2 => /usr/lib/x86_64-linux-gnu/libodbcinst.so.2 (0x00007f2a4ee7b000)
	libkmlbase.so.1 => /usr/lib/x86_64-linux-gnu/libkmlbase.so.1 (0x00007f2a4ec60000)
	libkmldom.so.1 => /usr/lib/x86_64-linux-gnu/libkmldom.so.1 (0x00007f2a4e9a9000)
	libkmlengine.so.1 => /usr/lib/x86_64-linux-gnu/libkmlengine.so.1 (0x00007f2a4e771000)
	libxerces-c-3.2.so => /usr/lib/x86_64-linux-gnu/libxerces-c-3.2.so (0x00007f2a4e1fd000)
	libopenjp2.so.7 => /usr/lib/x86_64-linux-gnu/libopenjp2.so.7 (0x00007f2a4dfa7000)
	libnetcdf.so.13 => /usr/lib/x86_64-linux-gnu/libnetcdf.so.13 (0x00007f2a4dc85000)
	libhdf5_serial.so.100 => /usr/lib/x86_64-linux-gnu/libhdf5_serial.so.100 (0x00007f2a4d72d000)
	libmfhdfalt.so.0 => /usr/lib/libmfhdfalt.so.0 (0x00007f2a4d507000)
	libdfalt.so.0 => /usr/lib/libdfalt.so.0 (0x00007f2a4d264000)
	libogdi.so.3.2 => /usr/lib/libogdi.so.3.2 (0x00007f2a4d043000)
	libgif.so.7 => /usr/lib/x86_64-linux-gnu/libgif.so.7 (0x00007f2a4ce3a000)
	libCharLS.so.1 => /usr/lib/x86_64-linux-gnu/libCharLS.so.1 (0x00007f2a4cbf3000)
	libgeotiff.so.2 => /usr/lib/x86_64-linux-gnu/libgeotiff.so.2 (0x00007f2a4c9bd000)
	libtiff.so.5 => /usr/lib/x86_64-linux-gnu/libtiff.so.5 (0x00007f2a4c746000)
	libpq.so.5 => /usr/lib/x86_64-linux-gnu/libpq.so.5 (0x00007f2a4c4fd000)
	libdapclient.so.6 => /usr/lib/x86_64-linux-gnu/libdapclient.so.6 (0x00007f2a4c2bc000)
	libdap.so.25 => /usr/lib/x86_64-linux-gnu/libdap.so.25 (0x00007f2a4bf2c000)
	libspatialite.so.7 => /usr/lib/x86_64-linux-gnu/libspatialite.so.7 (0x00007f2a4b7b1000)
	libcurl-gnutls.so.4 => /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 (0x00007f2a4b534000)
	libfyba.so.0 => /usr/lib/x86_64-linux-gnu/libfyba.so.0 (0x00007f2a4b2df000)
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f2a4af1e000)
	libmysqlclient.so.20 => /usr/lib/x86_64-linux-gnu/libmysqlclient.so.20 (0x00007f2a4a90c000)
	libnghttp2.so.14 => /usr/lib/x86_64-linux-gnu/libnghttp2.so.14 (0x00007f2a4a6e7000)
	libidn2.so.0 => /usr/lib/x86_64-linux-gnu/libidn2.so.0 (0x00007f2a4a4ca000)
	librtmp.so.1 => /usr/lib/x86_64-linux-gnu/librtmp.so.1 (0x00007f2a4a2ae000)
	libpsl.so.5 => /usr/lib/x86_64-linux-gnu/libpsl.so.5 (0x00007f2a4a0a0000)
	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f2a49e36000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f2a499be000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f2a49773000)
	libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007f2a49521000)
	liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007f2a49313000)
	libjavascriptcoregtk-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-1.0.so.0 (0x00007f2a48a69000)
	libenchant.so.1 => /usr/lib/x86_64-linux-gnu/libenchant.so.1 (0x00007f2a4885d000)
	libharfbuzz-icu.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz-icu.so.0 (0x00007f2a4865a000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f2a483bc000)
	libgstapp-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstapp-1.0.so.0 (0x00007f2a481ad000)
	libgstaudio-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstaudio-1.0.so.0 (0x00007f2a47f39000)
	libgstfft-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstfft-1.0.so.0 (0x00007f2a47d2e000)
	libgstpbutils-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstpbutils-1.0.so.0 (0x00007f2a47af6000)
	libgstvideo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so.0 (0x00007f2a4785e000)
	libgstbase-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0 (0x00007f2a475e9000)
	libgstreamer-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0 (0x00007f2a472ae000)
	libsecret-1.so.0 => /usr/lib/x86_64-linux-gnu/libsecret-1.so.0 (0x00007f2a4705e000)
	libsoup-2.4.so.1 => /usr/lib/x86_64-linux-gnu/libsoup-2.4.so.1 (0x00007f2a46d6b000)
	libxslt.so.1 => /usr/lib/x86_64-linux-gnu/libxslt.so.1 (0x00007f2a46b2e000)
	libEGL.so.1 => /usr/lib/x86_64-linux-gnu/libEGL.so.1 (0x00007f2a4691a000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f2a46611000)
	libicui18n.so.60 => /usr/lib/x86_64-linux-gnu/libicui18n.so.60 (0x00007f2a46170000)
	libicuuc.so.60 => /usr/lib/x86_64-linux-gnu/libicuuc.so.60 (0x00007f2a45db9000)
	libXt.so.6 => /usr/lib/x86_64-linux-gnu/libXt.so.6 (0x00007f2a45b50000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f2a4594c000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f2a45746000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f2a45531000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f2a45309000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f2a450ee000)
	libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007f2a44e9a000)
	libdatrie.so.1 => /usr/lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007f2a44c93000)
	libnss3.so => /usr/lib/x86_64-linux-gnu/libnss3.so (0x00007f2a4494f000)
	libsmime3.so => /usr/lib/x86_64-linux-gnu/libsmime3.so (0x00007f2a44723000)
	libnspr4.so => /usr/lib/x86_64-linux-gnu/libnspr4.so (0x00007f2a444e6000)
	liblcms2.so.2 => /usr/lib/x86_64-linux-gnu/liblcms2.so.2 (0x00007f2a4428e000)
	libgeos-3.7.0.so => /usr/lib/x86_64-linux-gnu/libgeos-3.7.0.so (0x00007f2a43eed000)
	libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007f2a43ce3000)
	libminizip.so.1 => /usr/lib/x86_64-linux-gnu/libminizip.so.1 (0x00007f2a43ad8000)
	liburiparser.so.1 => /usr/lib/x86_64-linux-gnu/liburiparser.so.1 (0x00007f2a438bd000)
	libhdf5_serial_hl.so.100 => /usr/lib/x86_64-linux-gnu/libhdf5_serial_hl.so.100 (0x00007f2a4369a000)
	libsz.so.2 => /usr/lib/x86_64-linux-gnu/libsz.so.2 (0x00007f2a43497000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f2a43271000)
	libjbig.so.0 => /usr/lib/x86_64-linux-gnu/libjbig.so.0 (0x00007f2a43063000)
	libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f2a42e2d000)
	libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f2a42ac8000)
	libfyut.so.0 => /usr/lib/x86_64-linux-gnu/libfyut.so.0 (0x00007f2a428bf000)
	libfygm.so.0 => /usr/lib/x86_64-linux-gnu/libfygm.so.0 (0x00007f2a426b8000)
	libunistring.so.2 => /usr/lib/x86_64-linux-gnu/libunistring.so.2 (0x00007f2a4233a000)
	libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007f2a42106000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f2a41e85000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f2a41baf000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f2a4197d000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f2a41779000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f2a4156e000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f2a41353000)
	libgssapi.so.3 => /usr/lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007f2a41112000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f2a40ee5000)
	libgsttag-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgsttag-1.0.so.0 (0x00007f2a40caa000)
	liborc-0.4.so.0 => /usr/lib/x86_64-linux-gnu/liborc-0.4.so.0 (0x00007f2a40a2e000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f2a40713000)
	libicudata.so.60 => /usr/lib/x86_64-linux-gnu/libicudata.so.60 (0x00007f2a3eb6a000)
	libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007f2a3e91d000)
	libnssutil3.so => /usr/lib/x86_64-linux-gnu/libnssutil3.so (0x00007f2a3e6ee000)
	libplc4.so => /usr/lib/x86_64-linux-gnu/libplc4.so (0x00007f2a3e4e9000)
	libplds4.so => /usr/lib/x86_64-linux-gnu/libplds4.so (0x00007f2a3e2e5000)
	libaec.so.0 => /usr/lib/x86_64-linux-gnu/libaec.so.0 (0x00007f2a3e0dd000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f2a3ddae000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f2a3db9b000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f2a3d997000)
	libheimntlm.so.0 => /usr/lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007f2a3d78e000)
	libkrb5.so.26 => /usr/lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007f2a3d501000)
	libasn1.so.8 => /usr/lib/x86_64-linux-gnu/libasn1.so.8 (0x00007f2a3d25f000)
	libhcrypto.so.4 => /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007f2a3d029000)
	libroken.so.18 => /usr/lib/x86_64-linux-gnu/libroken.so.18 (0x00007f2a3ce13000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f2a3cbfe000)
	libwind.so.0 => /usr/lib/x86_64-linux-gnu/libwind.so.0 (0x00007f2a3c9d5000)
	libheimbase.so.1 => /usr/lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007f2a3c7c6000)
	libhx509.so.5 => /usr/lib/x86_64-linux-gnu/libhx509.so.5 (0x00007f2a3c57c000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f2a3c344000)

I've also run `nm -D /usr/lib/libgdal.so` and you can see the output at https://labs.webgeodatavore.com/partage/nm_out.txt (too long to put in the issue)

**Comment by lixun910** [comment]
Thanks for sending the nm report! I will take a look at it to see if there
is a solution.

**Comment by lixun910** [comment]
@ThomasG77 Hi, I just checked your nm report and compared with the one on my clean Ubuntu 18.04. They are different: e.g. the symbol _ZN10OGRFeature16GetFieldAsStringEi is missing in your libgdal.so
That means the libgdal.so is different on your machine than on my clean Ubuntu 18.04. 

I further checked the docker you used: 
https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable , and noticed something wrong with the libgdal version comes with the docker:
the gdal version installed on bionic (18.04) is 2.3.2
<img width="961" alt="screen shot 2019-03-01 at 11 08 10 am" src="https://user-images.githubusercontent.com/2423887/53657485-7e265f80-3c13-11e9-915b-61db34ecccfb.png">

It is different than the gdal version on official bionic package, which is 2.2.3: see https://packages.ubuntu.com/bionic/libgdal20

The gdal version 2.3.2 only comes on official cosmic package(Ubuntu 18.10): see https://packages.ubuntu.com/cosmic/libgdal20

Since we don't have a GeoDa deb for Ubuntu 18.10, and the docker you are using is also unstable. I would suggest you install QGIS (if that is the purpose of using the docker) manually on Ubuntu 18.04. In this way, the version of libgdal is managed by Ubuntu, and should have no conflict with GeoDa.

Let me know any questions. Thanks!

**Comment by lixun910** [comment]
@ThomasG77  FYI: Here are more about UbuntuGis repo, (which in this post is claimed "broken") and how to downgrade gdal from 2.3.2 to 2.2.3 if you prefer to do so

https://gis.stackexchange.com/questions/305529/qgis-installation-vanished-re-installation-attempts-produce-dependency-errors

**Comment by ThomasG77** [comment]
I've taken a more complex way by retrieving the default GDAL version compiled files and changing environment variables. Dirty but work as expected at least.

**Recipe to avoid replacing my GDAL version only for GeoDa**

*Retrieve GDAL 2.2.3 default version (mine is an Ubuntu GIS version incompatible with GeoDa) to use it in another directory than default*
```bash
cd /tmp/
mkdir $HOME/gdaldir
mkdir gdaltemp && cd gdaltemp
mkdir libgdal-dev && cd libgdal-dev
wget http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gdal/libgdal-dev_2.2.3+dfsg-2_amd64.deb
ar x libgdal-dev_2.2.3+dfsg-2_amd64.deb
tar xf data.tar.xz
cp -r usr /tmp/gdaldir
cd ..
mkdir libgdal20 && cd libgdal20
wget http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gdal/libgdal20_2.2.3+dfsg-2_amd64.deb
ar x libgdal20_2.2.3+dfsg-2_amd64.deb
tar xf data.tar.xz
cp -r usr $HOME/gdaldir
```

*Use the GDAL version put in the alternate directory*
Then in `/usr/local/geoda/run.sh`, replace:

    export LD_LIBRARY_PATH=$GEODA_HOME/plugins:$ORACLE_HOME:$LD_LIBRARY_PATH
    export GDAL_DATA=$GEODA_HOME/gdaldata

with:

    GDAL_PATH=$HOME/gdal-all/usr

    export PATH=$GDAL_PATH/bin:$PATH
    export LD_LIBRARY_PATH=$GDAL_PATH/lib:$GEODA_HOME/plugins:$ORACLE_HOME:$LD_LIBRARY_PATH

*Run `/usr/local/geoda/run.sh`*

**Comment by lixun910** [comment]
@ThomasG77  Great! Your recipe will be very useful if any others encounter the same issue.
Thanks!
