### ISSUE TITLE
EB Moran and Local Moran - enable saving standardized rates

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1828]
The Save Results option in the EB Local Moran cluster/significance maps does not include an item to save the standardized rates. The same is the case with the save results option for the EB Moran scatter plot. Unlike the rate maps, it is thus not possible to recuperate the EB rates, unless they are computed separately in the calculator.

It would be more consistent to include an option to save the EB rates, e.g., similar to the way the differences can be saved for the differential local moran. This would affect the save results option in both the EB moran scatter plot and the EB local moran maps.

**Comment by lixun910** [comment]
V205: the new options in Save Results dialog

<img width="601" alt="screen shot 2019-03-06 at 1 43 15 pm" src="https://user-images.githubusercontent.com/2423887/53912294-e7441380-4015-11e9-9064-c9538dd5a539.png">
<img width="601" alt="screen shot 2019-03-06 at 1 43 30 pm" src="https://user-images.githubusercontent.com/2423887/53912292-e6ab7d00-4015-11e9-9bb3-b593a0a8079d.png">

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.211 (macOS Mojave, 10.14.3). Mar. 18 build.

Fix verified. Both Moran's I with EB rates and Local Moran's I with EB rates now have an option to save EB Rates. 

<img width="602" alt="1828-1" src="https://user-images.githubusercontent.com/45187310/54655060-67df2700-4a8e-11e9-8129-f63b54bc3537.png">

<img width="598" alt="1828-2" src="https://user-images.githubusercontent.com/45187310/54655065-6f9ecb80-4a8e-11e9-8103-45c696d898a6.png">
