### ISSUE TITLE
bug in natural breaks

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1829]
In the natural breaks map the largest category (for anything beyond 2 categories) seems to always be empty if using data with extreme outlieres:
<img width="740" alt="screen shot 2019-03-05 at 3 31 04 pm" src="https://user-images.githubusercontent.com/2423887/53842074-b4d5e000-3f5b-11e9-9553-eff3ea861610.png">

**Comment by lixun910** [comment]
fix in V205

<img width="595" alt="screen shot 2019-03-05 at 3 28 26 pm" src="https://user-images.githubusercontent.com/2423887/53911917-fffff980-4014-11e9-92c8-b35747c66144.png">

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.217 (macOS Mojave, 10.14.3). Mar. 23 build.
Data: Guerry sample

Fix verified. 
Tested with 1) a positive extreme value, 2) a negative extreme value, and 3) positive + negative extreme values; 4) extreme values with missings

<img width="599" alt="1829" src="https://user-images.githubusercontent.com/45187310/55195406-73aba700-517a-11e9-912d-d6b583ab9e6e.png">
