### ISSUE TITLE
add Negative category in multivariate Local Geary cluster map

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1830]
Multivariate local Geary has both positive (smaller than average) and negative (larger than average) spatial autocorrelation. There should be three categories (positive, negative and not significant).

**Comment by lixun910** [comment]
Fix in V209
<img width="527" alt="Screen Shot 2019-03-09 at 12 47 09 AM" src="https://user-images.githubusercontent.com/2423887/54068031-e6250900-4204-11e9-9f38-75ca7505044c.png">

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.209 (macOS Mojave, 10.14.3). Mar. 9 build.

Fix verified. Tested with Columbus Crime sample and external dataset.

<img width="600" alt="1830" src="https://user-images.githubusercontent.com/45187310/54235340-07c11180-44df-11e9-80b1-28c130a9dad3.png">
