### ISSUE TITLE
bug: Standardize(MAD) computation is incorrect

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1831]
Standardize(MAD):  standardize the original value by subtracting the mean and dividing by the mean absolute difference

<img width="638" alt="screen shot 2019-03-06 at 8 14 41 pm" src="https://user-images.githubusercontent.com/2423887/53933671-9acff680-405c-11e9-970e-c69fe4c3ddd3.png">

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.217 (macOS Mojave, 10.14.3). Mar. 23 build.
Data: Guerry Sample.

Fix verified. The results (with missing values) from GeoDa are identical with that manually computed in Excel.

<img width="533" alt="1831" src="https://user-images.githubusercontent.com/45187310/55197381-6bef0100-5180-11e9-8c14-aa5589a7d2a8.png">
