### ISSUE TITLE
show selection and neighbors

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1832]
when one selects “show selection and neighbors”, the neighbors are not selected in other plots, like a scatter plot or PCP.

the desired behavior:  where both the selection and the neighbors (in connectivity map) are linked to other maps/plots

**Comment by lixun910** [comment]
fixed in V209

e.g. when user mouse over the "connectivity map", both the selection(hover) and its neighbors are linked to MDS scatter plot:
<img width="1106" alt="Screen Shot 2019-03-09 at 12 26 50 AM" src="https://user-images.githubusercontent.com/2423887/54067849-6eee7580-4202-11e9-93f1-b0156bfa9999.png">

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.209 (macOS Mojave, 10.14.3). Mar. 9 build.

With "show selection and neighbors" on, neighbors are also shown in histogram, boxplot, scatter plot, scatter plot matrix, PCP, conditional plots. BUT not in bubble plots or 3D plots. 

<img width="797" alt="1832" src="https://user-images.githubusercontent.com/45187310/54232617-0c82c700-44d9-11e9-9f4d-5c43e339ad47.png">

**Comment by lixun910** [comment]
@Ashitacarl Thanks! Will fix it in bubble plot and 3D plot.

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.217 (macOS Mojave, 10.14.3). Mar. 23 build.
Data: Guerry Sample

Fix verified. Now both bubble plot and 3D plot highlight neighbors.
<img width="1058" alt="1832" src="https://user-images.githubusercontent.com/45187310/55198133-cab57a00-5182-11e9-9205-2865a0281948.png">
