### ISSUE TITLE
Allow user to set display precision in PCP

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1833]

**Comment by lixun910** [comment]
Fixed in V209:

A new menu item (right click): View->Set Display Precision  in PCP
<img width="598" alt="Screen Shot 2019-03-09 at 12 31 48 AM" src="https://user-images.githubusercontent.com/2423887/54067898-f50abc00-4202-11e9-9a0d-1190d573047c.png">

It allows user to set the display precision via a dialog:
<img width="599" alt="Screen Shot 2019-03-09 at 12 31 55 AM" src="https://user-images.githubusercontent.com/2423887/54067900-f76d1600-4202-11e9-95f4-fe518ce2ff3c.png">


Once user clicks the OK button, the PCP will be updated with new display precision
<img width="603" alt="Screen Shot 2019-03-09 at 12 32 00 AM" src="https://user-images.githubusercontent.com/2423887/54067902-fb993380-4202-11e9-9d9d-28feea27b27c.png">

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.209 (macOS Mojave, 10.14.3). Mar. 9 build.

Fix verified. PCP now allows users to set a customized precision.

But in Boxplots and scatter plots, one can only select customize precision for Axes but not for stats below the graph. See below.
<img width="683" alt="1833" src="https://user-images.githubusercontent.com/45187310/54236109-d5b0af00-44e0-11e9-883e-4e2fd3886305.png">

For conditional plots, the third variable's precision cannot be changed. See below.
<img width="729" alt="1833-2" src="https://user-images.githubusercontent.com/45187310/54236185-07c21100-44e1-11e9-873f-c6ee7cc10e23.png">

**Comment by lixun910** [comment]
@Ashitacarl Good point. Will apply the new “Set Display Precision” option in PCP to all other plots.

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.217 (macOS Mojave, 10.14.3). Mar. 23 build.
Data: Guerry Sample.

Fix verified. Setting precision is available for Axes and stats. 
<img width="828" alt="1833-3" src="https://user-images.githubusercontent.com/45187310/55197756-78278e00-5181-11e9-90de-5ba0eed4dcb8.png">
