### ISSUE TITLE
Allow user to set display precision in map legend

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1834]

**Comment by lixun910** [comment]
Add new menu item "Set Display Precision" in right click menu on Map legend:
<img width="602" alt="Screen Shot 2019-03-09 at 12 35 25 AM" src="https://user-images.githubusercontent.com/2423887/54067928-6c405000-4203-11e9-9c03-acb0b4637b14.png">

It allows user to set the display precision via a dialog:
<img width="599" alt="Screen Shot 2019-03-09 at 12 36 29 AM" src="https://user-images.githubusercontent.com/2423887/54067929-6f3b4080-4203-11e9-883f-4d74078dcb20.png">

Once user clicks the OK button, the Map legend will be updated with new display precision
<img width="602" alt="Screen Shot 2019-03-09 at 12 36 38 AM" src="https://user-images.githubusercontent.com/2423887/54067932-72cec780-4203-11e9-9848-ea79b4b78248.png">

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.209 (macOS Mojave, 10.14.3). Mar. 9 build.

This function works for real number variables but not for integers. See below. 

<img width="1141" alt="1834" src="https://user-images.githubusercontent.com/45187310/54236439-8ae36700-44e1-11e9-9bff-8517618d5c5e.png">

Once I create custom breaks, this works fine. See below. rent2002 is an integer in the dataset. I add custom breaks with 0.20 etc as breaks.

<img width="600" alt="1834-2" src="https://user-images.githubusercontent.com/45187310/54236651-13fa9e00-44e2-11e9-96ac-d460dde281ad.png">
