### ISSUE TITLE
Separate "Color for Category" to "Fill Color and Outline Color" in Map window

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1838]
Separate "Color for Category" to "Fill Color and Outline Color" in Map window, so that user can set fill color outline color separately. 

Another issue for windows users: there is no option to set transparency (opacity or alpha) of a color (which is limited by wxWidgets). Also, try to add a menu item to set transparency for windows users only.

<img width="337" alt="Screen Shot 2019-03-21 at 1 33 08 PM" src="https://user-images.githubusercontent.com/2423887/54783162-e3032300-4bdd-11e9-80ea-eb68d6f458dd.png">

**Comment by lixun910** [comment]
fixed in V213

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.217 (macOS Mojave, 10.14.3). Mar. 23 build.
Data: Guerry Sample

Fix verified. There are two separate options now available: 1) outline color and 2) fill color. 

<img width="435" alt="1838" src="https://user-images.githubusercontent.com/45187310/55195583-fe8ca180-517a-11e9-859b-df2e88be674b.png">
