### ISSUE TITLE
Spatial Join enhancement

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1842]
1. Allow spatial join on polygons to polygons
2. Besides spatial counting, also allow the user to specify which variable and what join operation (e.g. mean, median, sum, std dev) in spatial join

**Comment by lixun910** [comment]
Besides spatial counting, also allow the user to specify which variable and what join operation (e.g. mean, median, sum, std dev) in spatial join

<img width="794" alt="Screen Shot 2019-03-29 at 12 15 15 PM" src="https://user-images.githubusercontent.com/2423887/55257195-60511800-521c-11e9-9844-35618fef7c7c.png">

**Comment by lixun910** [comment]
V219

**Comment by bsalas11** [comment]
GeoDa Windows 1.14

Fix verified.

![spcount](https://user-images.githubusercontent.com/46054957/62399644-1f5a6e80-b542-11e9-8860-537733094612.PNG)

![spc](https://user-images.githubusercontent.com/46054957/62399649-23868c00-b542-11e9-9e13-054c90621e41.PNG)
