### ISSUE TITLE
Crash Report: Regression

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1845]
From: 
 Details:
os: 3-4-19
vs: 1-12-1-201
/usr/local/geoda/web_plugins/logger.txt
Click GdaFrame::OnNewProject
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/gnann/geoda/SP/35MUE250GC_SIR.shp
Open Layer:35MUE250GC_SIR
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/gnann/geoda/SP/35MUE250GC_SIR.shp
Entering OGRTable::OGRTable
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnRegressionClassic()
Open RegressionDlg.
RegressionDlg::InitVariableList()
Click RegressionDlg::OnCloseClick
RegressionDlg::~RegressionDlg()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
selected:0
Click CreatingWeightDlg::OnCreateClick
CreateWeights()
/home/gnann/geoda/SP/35MUE250GC_SIR.gal
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnActivate
WeightsManFrame::OnConnectGraphBtn()
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::DisplayWeightsGraph()
Project::GetCentroids()
In WeightsManFrame::OnActivate
MapCanvas::~MapCanvas()
In WeightsManFrame::OnActivate
WeightsManFrame::OnConnectMapBtn()
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::DisplayNeighbors()
In WeightsManFrame::OnActivate
MapCanvas::~MapCanvas()
In WeightsManFrame::OnActivate
WeightsManFrame::OnHistogramBtn()
Open ConnectivityHistFrame
In WeightsManFrame::OnActivate
ConnectivityHistFrame::OnActivate
ConnectivityHistFrame::OnActivate
In WeightsManFrame::OnActivate
In GdaFrame::OnRegressionClassic()
Open RegressionDlg.
RegressionDlg::InitVariableList()
Click RegressionDlg::OnCloseClick
RegressionDlg::~RegressionDlg()

**Comment by jkoschinsky** [comment]
I suspect this is a data problem but it's a reoccurring crash, so let's see if we can catch it:

1. open shapefile
2. create weights
3. open weights histogram and connectivity map
4. open regression and play with different variable and weights selections for classic model

**Comment by lixun910** [comment]
I was able to find the shapefile in this report (see attachment, the data has no numeric data), and did successfully repeat all steps in the report, and no crash. 

GeoDa: 1.12.1.201
Ubuntu: 18.06

[35MUE250GC_SIR.zip](https://github.com/GeoDaCenter/geoda/files/3462364/35MUE250GC_SIR.zip)
