### ISSUE TITLE
Custom breaks category editor do not 'stick' 

### ISSUE THREAD

**Issue by bodelange** [GeoDaCenter/geoda#1847]
I've created custom breaks using the category editor. The values are saved correctly to the .gda project file (file #1) 
![1](https://user-images.githubusercontent.com/49198167/55406754-05415d00-555d-11e9-8bd3-7c17c05d0f70.png)

and applied to a map I then draw with these custom breaks (file #2). ![2](https://user-images.githubusercontent.com/49198167/55406762-08d4e400-555d-11e9-9328-696c5420bcbe.png)

However, whenever I close and reopen the category editor, or switch between custom breaks created earlier, the values for the variable categories revert back to system defaults (file #3). 

![3](https://user-images.githubusercontent.com/49198167/55406832-2e61ed80-555d-11e9-9eaa-b90a75b2e0e7.png)

I'm using GeoDa 1.12.1.201 on a Mac, but had the same problem in 1.12.1.161. Any help appreciated. 

Bo

**Comment by lixun910** [comment]
@bodelange Thanks for reporting this bug! We will fix it soon.

**Comment by bodelange** [comment]
@lixun910 Thanks!

**Comment by lixun910** [comment]
Hi @bodelange , I have an internal version GeoDa 1.12.1.221 with the fix of this bug. Could you help to verify if your issue has been fixed in this build? Thank you very much! 

Download for OSX: https://www.dropbox.com/s/wwoz7p6ln64zs1p/GeoDa1.12.1.221-Installer.dmg?dl=0

**Comment by bodelange** [comment]
Hi @lixun910, I have verified that the issue has indeed been fixed in the 1.12.1.221 build. Thanks a lot.

**Comment by bodelange** [comment]
Is/will the fix also be available for the other platforms? I noticed the same bug in the Windows version.

**Comment by lixun910** [comment]
Yes, I am verifying other fixes in this build. Once it's ready, I will update with you for other platforms. I will also post the download links in our nightly build download page. Thanks!

**Comment by lixun910** [comment]
Test cases (Custom Breaks): https://github.com/GeoDaCenter/geoda/wiki/GeoDa-Test-Cases#1-custom-breaks

**Comment by bodelange** [comment]
Am on a short break. Will look at it when I get back. 

Bo

**Comment by lixun910** [comment]
Sorry, this is for our team. I have a new build with more fixes and will
update with you once it’s ready. Thanks!

**Comment by lixun910** [comment]
V227

**Comment by bsalas11** [comment]
Windows 1.12.1.237

Fix verified. 

Values for edited custom breaks remain after closing the editor and toggling between different custom breaks. Works with the initial map variables and with different permutations.

**Comment by lixun910** [comment]
Fix verified, and will be in GeoDa 1.14, which will be released soon.
