### ISSUE TITLE
GeoDa crash when loading 2nd layer from recent after it was deleted

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1850]
GeoDa crash:

1. load base layer (eg HQ.csv)
2. load 2nd layer (from csv file, eg satellite.csv)
3. close Geoda and delete csv file used as 2nd layer in 2.
4. open GeoDa and reload base layer from recent data
5. add 2nd layer from recent data
= crash since file was deleted

**Comment by lixun910** [comment]
Fix verified.

<img width="637" alt="Screen Shot 2019-08-02 at 10 21 34 AM" src="https://user-images.githubusercontent.com/2423887/62387397-55322f80-b50f-11e9-8b4e-1687845f6a59.png">
