### ISSUE TITLE
Linux Crash: Weights Manager

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1860]
From: 
 Details:
os: 3-4-15
vs: 1-12-1-147
/usr/local/geoda/web_plugins/logger.txt
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/federico/Scrivania/Università/Dugato/Files/mappa-aggiornata/neighborhoods.shp
Entering OGRTable::OGRTable
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnCreateNewIdClick
Try to insert unique id (integer, Peso) column in table.
Click CreatingWeightDlg::OnCreateClick
CreateWeights()
/home/federico/Scrivania/Università/Dugato/Files/gal/neighborhoods2.gal
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Ratio
VariableSettingsDlg::GetWeightsId() weight: neighborhoods2
VariableSettingsDlg::GetWeightsId() weight: neighborhoods2
Entering AbstractCoordinator::AbstractCoordinator().
Entering AbstractCoordinator::SetSignificanceFilter()
Exiting AbstractCoordinator::SetSignificanceFilter()
Exiting AbstractCoordinator::AbstractCoordinator().
Entering LisaCoordinator::LisaCoordinator().
Entering AbstractCoordinator::InitFromVarInfo()
Entering LisaCoordinator::Init()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::Init()
Entering AbstractCoordinator::DeallocateVectors()
Exiting AbstractCoordinator::DeallocateVectors()
Entering AbstractCoordinator::AllocateVectors()
Exiting AbstractCoordinator::AllocateVectors()
Entering LisaCoordinator::Calc()
Exiting LisaCoordinator::Calc()
Entering AbstractCoordinator::CalcPseudoP_threaded()
Exiting AbstractCoordinator::CalcPseudoP_threaded()
Exiting AbstractCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
Entering LisaScatterPlotFrame::LisaScatterPlotFrame
Exiting LisaScatterPlotFrame::LisaScatterPlotFrame
Entering LisaMapFrame::LisaMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Entering AbstractMapCanvas::AbstractMapCanvas
Exiting AbstractMapCanvas::AbstractMapCanvas
Entering LisaMapCanvas::LisaMapCanvas
Exiting LisaMapCanvas::LisaMapCanvas
In AbstractCoordinator::registerObserver()
Exiting LisaMapFrame::LisaMapFrame
Entering LisaMapFrame::LisaMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Entering AbstractMapCanvas::AbstractMapCanvas
Exiting AbstractMapCanvas::AbstractMapCanvas
Entering LisaMapCanvas::LisaMapCanvas
Exiting LisaMapCanvas::LisaMapCanvas
In AbstractCoordinator::registerObserver()
Exiting LisaMapFrame::LisaMapFrame
In WeightsManFrame::OnActivate
Entering WeightsManFrame::OnRemoveBtn
In AbstractCoordinator::numMustCloseToRemove()
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::OnRemoveBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Click GdaFrame::OnClose
Project::GetProjectFullPath()
Click GdaFrame::OnClose
Project::GetProjectFullPath()

**Comment by lixun910** [comment]
@jkoschinsky  can't replicate

**Comment by lixun910** [comment]
Ubuntu 18.04 issue 
Ref to #1932
