### ISSUE TITLE
crash related to field names with merged tables

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1861]
Finally caught one of the table field name crashes in action.

Steps:
- load csv with XY (map displayed)
- merge this with another XY with duplicate field names
- when trying to save as csv field creation error is displayed and it won't let you save
- when saving as shapefile, it displays the field name dialog to correct the names
- after correcting the names, GeoDa crashes

Note: in the file that's merged, the ID field is blank.

will send you the files separately since they're non-public

**Comment by jkoschinsky** [comment]
Tested again and it works once I add the missing field name, so crash is due to blank field name (and I had saved map before merging in case that's related).

**Comment by lixun910** [comment]
Fix verified by Julia, and Xun (on Mac and Ubuntu).
