### ISSUE TITLE
averages tool does not give variables in correct order

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1862]
After the order of variables has been changed in a table (and saved), the averages tool still lists the old order.

Screen shot of averages tool list of variables

<img width="273" alt="Screen Shot 2019-05-01 at 5 37 45 PM" src="https://user-images.githubusercontent.com/4008351/57048014-12269e80-6c38-11e9-9987-ec83b8962a3d.png">

Screen shot of initial variables in table (note distcbd and popd)

<img width="647" alt="Screen Shot 2019-05-01 at 5 38 00 PM" src="https://user-images.githubusercontent.com/4008351/57048039-2b2f4f80-6c38-11e9-8ee9-faa20547168e.png">

**Comment by lixun910** [comment]
Got it. Will fix this soon.

**Comment by lixun910** [comment]
Fix verified (Mac and Ubuntu):

<img width="903" alt="Screen Shot 2019-08-02 at 9 37 50 AM" src="https://user-images.githubusercontent.com/2423887/62385182-392b8f80-b509-11e9-83e1-b3063af6e3fe.png">
