### ISSUE TITLE
Linux Crash: Weights Creation

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1866]
From: 
 Details:
os: 3-4-15
vs: 1-12-1-147
/usr/local/geoda/web_plugins/logger.txt
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/adam/Pulpit/Projekt transport miejski/Dane/Dane Gdańsk/transakcje geokodowanie/lokale 2016_2018.shp
Open Layer:lokale 2016_2018
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/adam/Pulpit/Projekt transport miejski/Dane/Dane Gdańsk/transakcje geokodowanie/lokale 2016_2018.shp
Entering OGRTable::OGRTable
Project::SetupEncoding()
utf-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
selected:0
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
3.92572
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
3.94204
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
3.95837
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
3.97469
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.00733
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.02365
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.03998
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.0563
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.07262
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.08894
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.10526
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.12159
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.13791
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.15423
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.17055
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.18687
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.2032
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.21952
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.23584
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.25216
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.26848
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.25216
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.23584
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.21952
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.18687
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.12159
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.07262
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.02365
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
3.97469
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
3.92572
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
3.9094
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
3.9094
Click CreatingWeightDlg::OnCreateClick
CreateWeights()
/home/adam/Pulpit/Projekt transport miejski/Dane/Dane Gdańsk/transakcje geokodowanie/lokale 2016_2018.gwt
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
3.92572
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
3.94204
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
3.95837
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
3.97469
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
3.99101
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.00733
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.02365
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.03998
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.0563
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.07262
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.08894
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.10526
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.12159
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.13791
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.17055
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.18687
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.2032
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.21952
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.23584
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.25216
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.26848
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.28481
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.30113
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.31745
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.33377
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.35009
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.33377
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.31745
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.28481
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.25216
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.21952
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.17055
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.13791
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.08894
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.0563
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.02365
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
3.99101
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
3.97469
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
3.94204
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
3.9094
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
3.9094
Click CreatingWeightDlg::OnCThresholdTextEdit:

Click CreatingWeightDlg::OnCThresholdTextEdit:
0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0,
Click CreatingWeightDlg::OnCThresholdTextEdit:
0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.5
Click CreatingWeightDlg::OnCreateClick
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.05
Click CreatingWeightDlg::OnCreateClick
CreateWeights()
/home/adam/Pulpit/Projekt transport miejski/Dane/Dane Gdańsk/transakcje geokodowanie/lokale 2016_2018.gwt

**Comment by lixun910** [comment]
@jkoschinsky  I can replicate this crash using GeoDa v1.12.1.147 on Ubuntu 18.04. It is caused by the "space" in the weights file name. It has been in the latter GeoDa version, as well as GeoDa 1.14.
