### ISSUE TITLE
Linux Crash: Spatial Lag Regression

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1868]
From: 
 Details:
os: 3-4-13
vs: 1-12-1-57
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/arminakvn/Google Drive/mario/fixed_test/fixed_test.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open FieldNewCalcSheetDlg.
In FieldNewCalcSheetDlg::OnPageChange()
page idx: -1
In FieldNewCalcSheetDlg::OnPageChange()
page idx: -1
In FieldNewCalcSheetDlg::OnPageChange()
page idx: -1
Open DataViewerAddColDlg.
DataViewerAddColDlg::CreateControls()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
In DataViewerAddColDlg::SetDefaultsByType()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::UpdateMinMaxValues()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::UpdateMinMaxValues()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::UpdateMinMaxValues()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnOkClick()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::CheckName()
DataViewerAddColDlg::UpdateApplyButton()
DataViewerAddColDlg::OnOkClick()
Inserting new column NAT_DFCAR into Table
In FieldNewCalcSheetDlg::OnApplyClick()
In TableFrame::OnActivate
Open ExportDataDlg in its Init()
In ExportDataDlg::BrowseExportDataSource()
In ExportDataDlg::OnOkClick()
ds:/home/arminakvn/Google Drive/mario/fixed_test/fixed_test.csv
Project::GetSpatialReference()
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
NAT_DFCAR
ScrolledWidgetsPane::IsFieldNameValid
ogc_fid
ScrolledWidgetsPane::IsFieldNameValid
geoid
ScrolledWidgetsPane::IsFieldNameValid
field_1
ScrolledWidgetsPane::IsFieldNameValid
geoid_1
ScrolledWidgetsPane::IsFieldNameValid
X
ScrolledWidgetsPane::IsFieldNameValid
Y
ScrolledWidgetsPane::IsFieldNameValid
CITYNAME
ScrolledWidgetsPane::IsFieldNameValid
B1500_2016
ScrolledWidgetsPane::IsFieldNameValid
B1500_2017
ScrolledWidgetsPane::IsFieldNameValid
B1500_2018
ScrolledWidgetsPane::IsFieldNameValid
B1500_2019
ScrolledWidgetsPane::IsFieldNameValid
B2503_2015
ScrolledWidgetsPane::IsFieldNameValid
B2503_2022
ScrolledWidgetsPane::IsFieldNameValid
B2503_2021
ScrolledWidgetsPane::IsFieldNameValid
B2503_2020
ScrolledWidgetsPane::IsFieldNameValid
B2503_2019
ScrolledWidgetsPane::IsFieldNameValid
B2503_2018
ScrolledWidgetsPane::IsFieldNameValid
B2503_2017
ScrolledWidgetsPane::IsFieldNameValid
B2503_2016
ScrolledWidgetsPane::IsFieldNameValid
B2503_2029
ScrolledWidgetsPane::IsFieldNameValid
B2503_2028
ScrolledWidgetsPane::IsFieldNameValid
B2503_2027
ScrolledWidgetsPane::IsFieldNameValid
B2503_2026
ScrolledWidgetsPane::IsFieldNameValid
B2503_2025
ScrolledWidgetsPane::IsFieldNameValid
B2503_2024
ScrolledWidgetsPane::IsFieldNameValid
B2503_2023
ScrolledWidgetsPane::IsFieldNameValid
B2500_2015
ScrolledWidgetsPane::IsFieldNameValid
B2500_2016
ScrolledWidgetsPane::IsFieldNameValid
B2302_2016
ScrolledWidgetsPane::IsFieldNameValid
B2302_2017
ScrolledWidgetsPane::IsFieldNameValid
B2302_2015
ScrolledWidgetsPane::IsFieldNameValid
B1500_2015
ScrolledWidgetsPane::IsFieldNameValid
B1702_2015
ScrolledWidgetsPane::IsFieldNameValid
B1702_2016
ScrolledWidgetsPane::IsFieldNameValid
B0300_2015
ScrolledWidgetsPane::IsFieldNameValid
B0300_2016
ScrolledWidgetsPane::IsFieldNameValid
B0300_2017
ScrolledWidgetsPane::IsFieldNameValid
B0300_2018
ScrolledWidgetsPane::IsFieldNameValid
B0300_2019
ScrolledWidgetsPane::IsFieldNameValid
B2500_2017
ScrolledWidgetsPane::IsFieldNameValid
B2500_2018
ScrolledWidgetsPane::IsFieldNameValid
B9905_2015
ScrolledWidgetsPane::IsFieldNameValid
B9905_2016
ScrolledWidgetsPane::IsFieldNameValid
B9905_2017
ScrolledWidgetsPane::IsFieldNameValid
B9905_2018
ScrolledWidgetsPane::IsFieldNameValid
B1702_2010
ScrolledWidgetsPane::IsFieldNameValid
B1702_2011
ScrolledWidgetsPane::IsFieldNameValid
B0300_2010
ScrolledWidgetsPane::IsFieldNameValid
B0300_2011
ScrolledWidgetsPane::IsFieldNameValid
B0300_2012
ScrolledWidgetsPane::IsFieldNameValid
B0300_2013
ScrolledWidgetsPane::IsFieldNameValid
B0300_2014
ScrolledWidgetsPane::IsFieldNameValid
B2500_2010
ScrolledWidgetsPane::IsFieldNameValid
B2500_2011
ScrolledWidgetsPane::IsFieldNameValid
B9905_2010
ScrolledWidgetsPane::IsFieldNameValid
B9905_2011
ScrolledWidgetsPane::IsFieldNameValid
B9905_2012
ScrolledWidgetsPane::IsFieldNameValid
B9905_2013
ScrolledWidgetsPane::IsFieldNameValid
PCOUNT
ScrolledWidgetsPane::IsFieldNameValid
WHT10
ScrolledWidgetsPane::IsFieldNameValid
BLC10
ScrolledWidgetsPane::IsFieldNameValid
LAT10
ScrolledWidgetsPane::IsFieldNameValid
ASIA10
ScrolledWidgetsPane::IsFieldNameValid
OWN10
ScrolledWidgetsPane::IsFieldNameValid
POV10
ScrolledWidgetsPane::IsFieldNameValid
WHT15
ScrolledWidgetsPane::IsFieldNameValid
BLC15
ScrolledWidgetsPane::IsFieldNameValid
LAT15
ScrolledWidgetsPane::IsFieldNameValid
ASIA15
ScrolledWidgetsPane::IsFieldNameValid
OWN15
ScrolledWidgetsPane::IsFieldNameValid
POV15
ScrolledWidgetsPane::IsFieldNameValid
FRN15
ScrolledWidgetsPane::IsFieldNameValid
UMP15
ScrolledWidgetsPane::IsFieldNameValid
EDU15
ScrolledWidgetsPane::IsFieldNameValid
BLB00
ScrolledWidgetsPane::IsFieldNameValid
HU15
ScrolledWidgetsPane::IsFieldNameValid
VACRAT15
ScrolledWidgetsPane::IsFieldNameValid
POPCH_1016
ScrolledWidgetsPane::IsFieldNameValid
POPCH_1015
ScrolledWidgetsPane::IsFieldNameValid
POPDE_OG15
ScrolledWidgetsPane::IsFieldNameValid
COMDE_CAPT
ScrolledWidgetsPane::IsFieldNameValid
wdiffcar
ScrolledWidgetsPane::IsFieldNameValid
wdiffpt
ScrolledWidgetsPane::IsFieldNameValid
wdifffoot
ScrolledWidgetsPane::IsFieldNameValid
df_car
ScrolledWidgetsPane::IsFieldNameValid
df_pt
ScrolledWidgetsPane::IsFieldNameValid
df_foot
ScrolledWidgetsPane::IsFieldNameValid
bnk_cc_car
ScrolledWidgetsPane::IsFieldNameValid
bnk_c_foot
ScrolledWidgetsPane::IsFieldNameValid
bnk_cc_pt
ScrolledWidgetsPane::IsFieldNameValid
DICHO_CAR
ScrolledWidgetsPane::IsFieldNameValid
DICHO_PT
ScrolledWidgetsPane::IsFieldNameValid
DICHO_FOOT
ScrolledWidgetsPane::IsFieldNameValid
time__utes
ScrolledWidgetsPane::IsFieldNameValid
time_tes_3
ScrolledWidgetsPane::IsFieldNameValid
time_tes_2
ScrolledWidgetsPane::IsFieldNameValid
time_tes_5
ScrolledWidgetsPane::IsFieldNameValid
time_tes_1
ScrolledWidgetsPane::IsFieldNameValid
time_tes_4
ScrolledWidgetsPane::IsFieldNameValid
CITYNAME_1
ScrolledWidgetsPane::IsFieldNameValid
austin
ScrolledWidgetsPane::IsFieldNameValid
boston
ScrolledWidgetsPane::IsFieldNameValid
columbus
ScrolledWidgetsPane::IsFieldNameValid
fort_worth
ScrolledWidgetsPane::IsFieldNameValid
india_olis
In FieldNameCorrectionDlg
Out FieldNameCorrectionDlg
start OGRLayerProxy::AddFreatures()
Out OGRDataAdapter::ExportDataSource()
In GdaFrame::OnRegressionClassic()
Open RegressionDlg.
RegressionDlg::InitVariableList()
RegressionDlg::OnCButton1Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnCWeightCheckClick
Click RegressionDlg::OnCOpenWeightClick
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
selected:1
Click CreatingWeightDlg::OnCRadioKnnSelected
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Click CreatingWeightDlg::OnCRadioDistanceSelected
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Click CreatingWeightDlg::OnDistanceChoiceSelected
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Click CreatingWeightDlg::OnCThresholdTextEdit:

Click CreatingWeightDlg::OnCThresholdTextEdit:
5
In WeightsManFrame::OnActivate
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Click RegressionDlg::OnCRadio2Selected
Click RegressionDlg::OnRunClick
y:NAT_DFCAR
x:
BLC15
LAT15
ASIA15
OWN15
POV15
FRN15
UMP15
EDU15
BLB00
HU15
VACRAT15
POPDE_OG15
COMDE_CAPT
austin
boston
columbus
india_olis
Spatial Lag model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnClose()
Close RegressionDlg.
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
RegressionDlg::OnCButton1Click()
Click RegressionDlg::OnRunClick
y:df_car
x:
BLC15
LAT15
ASIA15
OWN15
POV15
FRN15
UMP15
EDU15
BLB00
HU15
VACRAT15
POPDE_OG15
COMDE_CAPT
austin
boston
columbus
india_olis
Spatial Lag model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnClose()
Close RegressionDlg.
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnRunClick
y:df_car
x:
BLC15
LAT15
ASIA15
OWN15
POV15
FRN15
UMP15
EDU15
BLB00
HU15
VACRAT15
POPDE_OG15
COMDE_CAPT
austin
boston
columbus
india_olis
fort_worth
Spatial Lag model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
RegressionDlg::OnCButton3Click()
Click RegressionDlg::OnRunClick
y:df_car
x:
BLC15
LAT15
ASIA15
OWN15
POV15
FRN15
UMP15
EDU15
BLB00
HU15
VACRAT15
POPDE_OG15
COMDE_CAPT
austin
boston
columbus
india_olis
Spatial Lag model
RegressionDlg::DisplayRegression()

**Comment by lixun910** [comment]
Ubuntu 18.04 issue 
Ref to #1932
