### ISSUE TITLE
Linux Crash: change map categories

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1869]
From: 
 Details:
os: 3-4-15
vs: 1-12-1-147
/usr/local/geoda/web_plugins/logger.txt
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/viviana/Escritorio/UD/Geoestadistica/GeoMelo/PROYECTO/datos/ohiolung/ohlung.shp
Open Layer:ohlung
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/viviana/Escritorio/UD/Geoestadistica/GeoMelo/PROYECTO/datos/ohiolung/ohlung.shp
Entering OGRTable::OGRTable
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()

**Comment by jkoschinsky** [comment]
Linux crash when trying to change map categories

**Comment by lixun910** [comment]
Can't replicate.

GeoDa: 1-12-1-147 https://s3-us-west-2.amazonaws.com/geodasoftware/geoda_1.12-ubuntu1804.deb
Ubuntu 18.04

**Comment by lixun910** [comment]
Ubuntu 18.04 issue 
Ref to #1932
