### ISSUE TITLE
Linux Crash: UTF-8 encoding (Russian?)

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1876]
From: 
 Details:
os: 3-4-18
vs: 1-12-1-201
/usr/local/geoda/web_plugins/logger.txt
Click GdaFrame::OnNewProject
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/or-sirina/Documents/Пространственный анализ/МирР/gadm36.shp
Open Layer:gadm36
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/or-sirina/Documents/Пространственный анализ/МирР/gadm36.shp
Entering OGRTable::OGRTable
Project::SetupEncoding()
UTF-8

**Comment by lixun910** [comment]
@jkoschinsky  Tried to use same path (with Russian characters), and the same version of GeoDa and ubuntu 18.04. Can't replicate it.

**Comment by lixun910** [comment]
Ubuntu 18.04 issue 
Ref to #1932
