### ISSUE TITLE
Linux Crash: 3D Scatterplot

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1877]
From: 
 Details:
os: 3-4-15
vs: 1-12-1-147
/usr/local/geoda/web_plugins/logger.txt
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
Open CsvFieldConfDlg.
CsvFieldConfDlg::PrereadCSV()
CsvFieldConfDlg::UpdateFieldGrid()
CsvFieldConfDlg::ReadCSVT()
CsvFieldConfDlg::UpdatePreviewGrid()
CsvFieldConfDlg::UpdateXYcombox()
CsvFieldConfDlg::OnOkClick()
CsvFieldConfDlg::WriteCSVT()
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/grzegorz/Projects/graduateAdmissions/datasetVer1.1.csv
Open Layer:datasetVer1.1
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/grzegorz/Projects/graduateAdmissions/datasetVer1.1.csv
Entering OGRTable::OGRTable
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
GRE Score
TOEFL Score
Chance of Admit
Open C3DPlotCanvas.

**Comment by lixun910** [comment]
Ubuntu 18.04 issue 
Ref to #1932
