### ISSUE TITLE
Linux Crash: LISA (GeoDa 1.12)

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1890]
From: 
 Details:
os: 3-4-10
vs: 1-12-1-161
/usr/local/geoda/web_plugins/logger.txt
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/diego/Coyoaca_cleaning_data/Análisis de elecciones/SpatialDataAnalysis/SpatialDataAnalysis_Coyoacan/mapa_outilers_corregido.shp
Open Layer:mapa_outilers_corregido
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/diego/Coyoaca_cleaning_data/Análisis de elecciones/SpatialDataAnalysis/SpatialDataAnalysis_Coyoacan/mapa_outilers_corregido.shp
Entering OGRTable::OGRTable
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
Exiting WeightsManFrame::WeightsManFrame
Click GdaFrame::OnToolsWeightsManager
In WeightsManFrame::OnActivate
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In GdaFrame::OnRegressionClassic()
Open RegressionDlg.
RegressionDlg::InitVariableList()
RegressionDlg::OnCButton1Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnCWeightCheckClick
Click RegressionDlg::OnRunClick
y:X.PRDvalid
x:
X.Benefici
casas_sin_
ICEvalidos
Pnocatolic
OLS model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
Click RegressionDlg::OnCRadio2Selected
Click RegressionDlg::OnRunClick
y:X.PRDvalid
x:
X.Benefici
casas_sin_
ICEvalidos
Pnocatolic
Spatial Lag model
RegressionDlg::DisplayRegression()
In RegressionReportDlg::OnClose()
Close RegressionDlg.
RegressionDlg::OnCButton3Click()
Click RegressionDlg::OnRunClick
y:X.PRDvalid
x:
X.Benefici
ICEvalidos
Pnocatolic
Spatial Lag model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnClose()
Close RegressionDlg.
Click RegressionDlg::OnCRadio1Selected
Click RegressionDlg::OnRunClick
y:X.PRDvalid
x:
X.Benefici
ICEvalidos
Pnocatolic
OLS model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnClose()
Close RegressionDlg.
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnRunClick
y:X.PRDvalid
x:
X.Benefici
ICEvalidos
Pnocatolic
casas_sin_
OLS model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
Click RegressionDlg::OnCRadio2Selected
Click RegressionDlg::OnRunClick
y:X.PRDvalid
x:
X.Benefici
ICEvalidos
Pnocatolic
casas_sin_
Spatial Lag model
RegressionDlg::DisplayRegression()
Click RegressionDlg::OnCRadio3Selected
Click RegressionDlg::OnRunClick
y:X.PRDvalid
x:
X.Benefici
ICEvalidos
Pnocatolic
casas_sin_
Spatial Error model
RegressionDlg::DisplayRegression()
Click RegressionDlg::OnSaveToTxtFileClick
Click RegressionDlg::OnSaveToTxtFileClick
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnRunClick
y:X.PRDvalid
x:
X.Benefici
ICEvalidos
Pnocatolic
casas_sin_
IDS
Spatial Error model
RegressionDlg::DisplayRegression()
In RegressionReportDlg::OnClose()
Close RegressionDlg.
RegressionDlg::~RegressionDlg()
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
In GdaFrame::OnRegressionClassic()
Open RegressionDlg.
RegressionDlg::InitVariableList()
RegressionDlg::~RegressionDlg()
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
X.Benefici
VariableSettingsDlg::GetWeightsId() weight: prueba
VariableSettingsDlg::GetWeightsId() weight: prueba
Entering AbstractCoordinator::AbstractCoordinator().
Entering AbstractCoordinator::SetSignificanceFilter()
Exiting AbstractCoordinator::SetSignificanceFilter()
Exiting AbstractCoordinator::AbstractCoordinator().
Entering LisaCoordinator::LisaCoordinator().
Entering AbstractCoordinator::InitFromVarInfo()
Entering LisaCoordinator::Init()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::Init()
Entering AbstractCoordinator::DeallocateVectors()
Exiting AbstractCoordinator::DeallocateVectors()
Entering AbstractCoordinator::AllocateVectors()
Exiting AbstractCoordinator::AllocateVectors()
Entering LisaCoordinator::Calc()
Exiting LisaCoordinator::Calc()
Entering AbstractCoordinator::CalcPseudoP_threaded()
Exiting AbstractCoordinator::CalcPseudoP_threaded()
Exiting AbstractCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
Entering LisaScatterPlotFrame::LisaScatterPlotFrame
Exiting LisaScatterPlotFrame::LisaScatterPlotFrame
Entering LisaMapFrame::LisaMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Entering AbstractMapCanvas::AbstractMapCanvas
Exiting AbstractMapCanvas::AbstractMapCanvas
Entering LisaMapCanvas::LisaMapCanvas
Exiting LisaMapCanvas::LisaMapCanvas
In AbstractCoordinator::registerObserver()
Exiting LisaMapFrame::LisaMapFrame
In LisaMapFrame::~LisaMapFrame
Entering AbstractCoordinator::removeObserver
In LisaCoordinator::~LisaCoordinator().
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
In AbstractCoordinator::~AbstractCoordinator().
Entering AbstractCoordinator::DeallocateVectors()
Exiting AbstractCoordinator::DeallocateVectors()
Exiting AbstractCoordinator::removeObserver
In LisaMapCanvas::~LisaMapCanvas
In AbstractMapCanvas::~AbstractMapCanvas
MapCanvas::~MapCanvas()

**Comment by lixun910** [comment]
I was able to replicate a crash ref #1912 and #1841 of LISA when using a time-grouped variable in GeoDa < 1.12.1.201. This bug has been fixed in the latter version GeoDa and 1.14. 

Replicate step: 
nat regimes dataset
1. create group variable: hr: hr60, hr70, hr80, hr90
2. create a queen contiguity weights
3. LISA-> select group variable hr and time 60, also select "LISA scatter plot" and "LISA significance map"
