### ISSUE TITLE
Table merge bug: integers with commas are cut off 

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1898]
Just came across this bug (Geoda 1.12.1.239 on Moac OSX).

Steps:
1. Merge table to shapefile

Problem:
when table has integers with commas, e.g. 153,084 or 44,263 (see right side of table in image below), GeoDa imports them as 153 and 44 (see left image below), i.e. it truncates the integer at the comma.

<img width="558" alt="bug" src="https://user-images.githubusercontent.com/13679743/59557249-8cb63e00-8f9a-11e9-8811-430404c1b0d7.png">

**Comment by lixun910** [comment]
Fix verified.
![image](https://user-images.githubusercontent.com/2423887/62385017-bb678400-b508-11e9-8b56-4ebcda857639.png)

**Comment by lixun910** [comment]
Using menu item: table->Setup Number Formatting, one can specify the thousand separator and decimal separator manually. For example, if you set “,” to be the decimal separator. Then, the case: 45,128 will be converted to 45.128 (double type) or 45 (integer type).
