### ISSUE TITLE
Linux Crash: Export w/ FieldNameCorrection

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1905]
From: 
 Details:
os: 3-4-4
vs: 1-12-1-161
/usr/local/geoda/web_plugins/logger.txt
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
Open CsvFieldConfDlg.
CsvFieldConfDlg::PrereadCSV()
CsvFieldConfDlg::UpdateFieldGrid()
CsvFieldConfDlg::ReadCSVT()
CsvFieldConfDlg::UpdatePreviewGrid()
CsvFieldConfDlg::UpdateXYcombox()
CsvFieldConfDlg::OnOkClick()
CsvFieldConfDlg::WriteCSVT()
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/kati/Downloads/UN data_cleaned_maternity_leave_2013.xlsx - Essential Data.csv
Open Layer:UN data_cleaned_maternity_leave_2013.xlsx - Essential Data
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/kati/Downloads/UN data_cleaned_maternity_leave_2013.xlsx - Essential Data.csv
Entering OGRTable::OGRTable
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
In TableFrame::OnActivate
Open CatClassifFrame
CatClassifPanel::OnButtonNew
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
In GdaFrame::OnCondPlotChoices()
In TableFrame::OnActivate
In TableFrame::OnActivate
Click GdaFrame::OnSaveProject
Entering Project::SaveDataSourceData
Exiting Project::SaveDataSourceData
Entering Project::SaveProjectConf
Exiting Project::SaveProjectConf
In TableFrame::OnActivate
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
Click GdaFrame::OnNewProject
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/kati/Downloads/ne_110m_admin_0_countries_lakes.shp
Open Layer:ne_110m_admin_0_countries_lakes
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/kati/Downloads/ne_110m_admin_0_countries_lakes.shp
Entering OGRTable::OGRTable
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnSaveProject
Entering Project::SaveDataSourceData
Exiting Project::SaveDataSourceData
Entering Project::SaveProjectConf
Exiting Project::SaveProjectConf
Click GdaFrame::OnSaveAsProject
Project::GetProjectFullPath()
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
MapCanvas::~MapCanvas()
Click GdaFrame::OnNewProject
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/kati/Downloads/ne_110m_admin_0_countries_lakes.shp
Entering OGRTable::OGRTable
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
Click GdaFrame::OnNewProject
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/kati/Downloads/UN data_cleaned_maternity_leave_2013.xlsx - Essential Data.csv
Entering OGRTable::OGRTable
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
Open ExportDataDlg in its Init()
In ExportDataDlg::OnOkClick()
ds:
Open ExportDataDlg in its Init()
Click GdaFrame::OnSaveProject
Entering Project::SaveDataSourceData
Exiting Project::SaveDataSourceData
Entering Project::SaveProjectConf
Exiting Project::SaveProjectConf
Open ExportDataDlg in its Init()
In ExportDataDlg::BrowseExportDataSource()
In ExportDataDlg::OnOkClick()
ds:/home/kati/Documents/Birmingham_University/Lopputyo/UNdata.dbf
Project::GetSpatialReference()
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
Country or area
ScrolledWidgetsPane::IsFieldNameValid
Leave in months
ScrolledWidgetsPane::IsFieldNameValid
Leave as paid months
ScrolledWidgetsPane::RemoveIllegalChars
Country or area
Countryorarea
ScrolledWidgetsPane::TruncateFieldName
Countryorarea
Count_area
ScrolledWidgetsPane::RenameDupFieldName
Count_area
Count_area
ScrolledWidgetsPane::RemoveIllegalChars
Leave in months
Leaveinmonths
ScrolledWidgetsPane::TruncateFieldName
Leaveinmonths
Leave_nths
ScrolledWidgetsPane::RenameDupFieldName
Leave_nths
Leave_nths
ScrolledWidgetsPane::RemoveIllegalChars
Leave as paid months
Leaveaspaidmonths
ScrolledWidgetsPane::TruncateFieldName
Leaveaspaidmonths
Leave_nths
ScrolledWidgetsPane::RenameDupFieldName
Leave_nths
ScrolledWidgetsPane::TruncateFieldName
Leave_nths
Leav_ths
Leav_ths_1
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
Country
ScrolledWidgetsPane::IsFieldNameValid
Leave_months
ScrolledWidgetsPane::IsFieldNameValid
Leave_paid
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
Country
ScrolledWidgetsPane::IsFieldNameValid
Leave_mths
ScrolledWidgetsPane::IsFieldNameValid
Leave_paid
In FieldNameCorrectionDlg
Out FieldNameCorrectionDlg
start OGRLayerProxy::AddFreatures()
Out OGRDataAdapter::ExportDataSource()

**Comment by lixun910** [comment]
@jkoschinsky  Try to use the simulated csv file (attached), and GeoDa 1.12.1.161 on Ubuntu 16.04. Can't replicated.
[UN data_cleaned_maternity_leave_2013.xlsx - Essential Data.csv.zip](https://github.com/GeoDaCenter/geoda/files/3459040/UN.data_cleaned_maternity_leave_2013.xlsx.-.Essential.Data.csv.zip)

**Comment by lixun910** [comment]
ref #1919 
Achieved to #1920
