### ISSUE TITLE
Linux Crash: Geocoding

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1906]
From: 
 Details:
os: 3-4-4
vs: 1-12-1-161
/usr/local/geoda/web_plugins/logger.txt
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/kati/Documents/Birmingham_University/Lopputyo/UNdata.dbf
Open Layer:UNdata
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/kati/Documents/Birmingham_University/Lopputyo/UNdata.dbf
Entering OGRTable::OGRTable
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnActivate
In TableFrame::OnActivate
Open GeocodingDlg().
Open GeocodingDlg().
In GeocodingDlg::OnOkClick()
In GeocodingDlg::run()

**Comment by lixun910** [comment]
@jkoschinsky "Geocoding" feature has been removed from GeoDa.
