### ISSUE TITLE
Linux Crash: Export data

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1913]
From: rodolfolo@uol.com.br
 Details:
os: 3-4-15
vs: 1-12-1-161
/usr/local/geoda/web_plugins/logger.txt
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/rodolfo/Documentos/Programação/PIBIC 2018-2019/Dados/Geo/mapa_Origem_tempo_relativo_distritos.shp
Entering OGRTable::OGRTable
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
Open AggregationDlg.
In TableFrame::OnActivate
Entering AggregationDlg::OnExclListDClick()
Entering AggregationDlg::OnIncOneClick()
In AggregationDlg::OnKeyChoice()
In AggregationDlg::OnOKClick()
Open ExportDataDlg in its Init()

**Comment by jkoschinsky** [comment]
Linux crash: export data

**Comment by lixun910** [comment]
@jkoschinsky  I can replicate this on Ubuntu using GeoDa 1.12.1.161, and it has already been fixed in latter version.

**Comment by lixun910** [comment]
@jkoschinsky This is a bug in aggregation feature. Verified in 1.14
