### ISSUE TITLE
Linux Crash: save geojson

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1914]
From: 
 Details:
os: 3-4-15
vs: 1-12-1-147
/usr/local/geoda/web_plugins/logger.txt
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/alal/Desktop/atlas/data/poverty_exports_v1_aggregatesee_export.geojson
Open Layer:poverty_exports_v1_aggregatesee_export
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/alal/Desktop/atlas/data/poverty_exports_v1_aggregatesee_export.geojson

**Comment by jkoschinsky** [comment]
Linux crash: save geojson

**Comment by lixun910** [comment]
@jkoschinsky  This report is from Ubuntu 16.04 with GeoDa version 1.12.1.147, which is only for Ubuntu 18.04. That means wrong GeoDa version is installed.
