### ISSUE TITLE
Linux Crash Report: Correlogram

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1931]
From: 
 Details:
os: 3-4-15
vs: 1-12-1-147
/usr/local/geoda/web_plugins/logger.txt
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/alides/Documentos/Docencia/Irati/Pesquisa/Eleicoes_Hist/Material_Final_Alides/Geostatistica/1980_Conectado.sqlite
Open Layer:1980_
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/alides/Documentos/Docencia/Irati/Pesquisa/Eleicoes_Hist/Material_Final_Alides/Geostatistica/1980_Conectado.sqlite
Entering OGRTable::OGRTable
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnCreateNewIdClick
Try to insert unique id (integer, POLY_ID) column in table.
Click CreatingWeightDlg::OnCreateClick
CreateWeights()
/home/alides/Documentos/Docencia/Irati/Pesquisa/Eleicoes_Hist/Material_Final_Alides/Geostatistica/1980_.gal
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
Open CorrelogramFrame.
Project::GetCentroids(std::vector<wxRealPoint>& pts)
Project::GetCentroids()
Entering CorrelogramAlgs::MakeCorrRandSamp
Exiting CorrelogramAlgs::MakeCorrRandSamp
In CorrelogramFrame::OnShowCorrelParams()
Entering CorrelParamsFrame::CorrelParamsFrame
Exiting CorrelParamsFrame::CorrelParamsFrame
In CorrelogramFrame::OnActivate()
In CorrelogramFrame::OnActivate()
In CorrelParamsFrame::OnApplyBtn

**Comment by lixun910** [comment]
Ubuntu 18.04 issue 
Ref to #1932
