### ISSUE TITLE
Ubuntu only issues

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1932]
Test GeoDa 1.14 on Ubuntu 16.04 and 18.04 using lab notes. Fix the following issues:

1. On Ubuntu 18.04, the wxWidgets library with GTK caused many crashes (not GeoDa), especially when doing table manipulations and triggers the Table window to resize -- where the crash happens, caused by the optimization level when compiling wxWidgets. It's only on Ubuntu 18.04. There is no related crash happens on Ubuntu 16.04, which suggests the possible cause is the incompatibility of wxWidgets 3.1 library and GTK library on Ubuntu 18.04. After disabled the optimization when compiling wxWidgets, it seems there is no more crash on Ubuntu 18.04.  

2. Saving canvas to a bmp/png file doesn't' work as expected (on Mac/Windows). This is Ubuntu only issue. Has been fixed. 

3. The color buttons in Colocation dialog and Custom category editor dialog are not shown as expected. Has been fixed.
<img width="474" alt="Screen Shot 2019-08-15 at 8 38 53 PM" src="https://user-images.githubusercontent.com/2423887/63143627-1b980480-bfa4-11e9-9f7c-6c683733e923.png">

**Comment by lixun910** [comment]
The binaries/installers of GeoDa 1.14 have been updated so that it has fewer dependencies that might cause conflicts (especially) when installing in a Linux lab environment. 
Also remove the "chmod" commands in scripts.

**Comment by lixun910** [comment]
Save Map As Image and Adjust transparency with basemap issue on Ubuntu only. It behaves differently on Ubuntu (the basemap should not be translucent):

<img width="1442" alt="Screen Shot 2019-08-20 at 4 06 25 PM" src="https://user-images.githubusercontent.com/2423887/63395381-60db7e00-c378-11e9-9bc4-dbc349e706e7.png">

**Comment by lixun910** [comment]
Ubuntu 18.04 with GTK 3.0 The label in sample panel is trimmed

<img width="1078" alt="Screen Shot 2019-08-22 at 4 43 34 PM" src="https://user-images.githubusercontent.com/2423887/63563773-1d6b4600-c517-11e9-8765-3ee7738e349c.png">

**Comment by lixun910** [comment]
Some UI issues on Ubuntu only
<img width="2323" alt="Screen Shot 2019-08-24 at 8 13 38 PM" src="https://user-images.githubusercontent.com/2423887/63645536-3a3d8000-c6b5-11e9-8702-8d6f45752bb8.png">

**Comment by lusdavo** [comment]
Do we know when packages for Ubuntu 19.04 will be available?

**Comment by lixun910** [comment]
@lusdavo working on that... will keep you updated

**Comment by lixun910** [comment]
@lusdavo We have a GeoDa installer for ubuntu 19.04, which you can download here: https://www.dropbox.com/s/enlsf4ltez6wtod/geoda_1.14-1disco1_amd64.deb?dl=0

We plan to put it on GeoDa's website after testing it. If you find any issues, please let us know, so we can fix them. Thanks!

**Comment by lusdavo** [comment]
Awesome, I will try this out and revert. Thanks @lixun910.
