### ISSUE TITLE
GeoDa does have wrong version information on macOS

### ISSUE THREAD

**Issue by core-code** [GeoDaCenter/geoda#1934]
i've downloaded version GeoDa 1.12.1.129 but when selecting it in the Finder, it claims to be version "1.0"
the problem is in your Info.plist file

	<key>CFBundleVersion</key>
	<string>1.0</string>

this should be set to 1.12.1.129

also, the CFBundleShortVersionString entry is missing completely

<img width="711" alt="Screenshot 2019-08-18 at 18 41 31" src="https://user-images.githubusercontent.com/1261954/63227534-f398e300-c1e7-11e9-9a44-72e6fe4a8b5b.png">

**Comment by lixun910** [comment]
@core-code Thanks! see your previous issue: https://github.com/GeoDaCenter/geoda/issues/1698
It has been and will be fixed in the later version of GeoDa.
