### ISSUE TITLE
Crash on 1.14

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1936]
Version: GeoDa 1.14
OSX
Data: election data on Box

Steps:
1. saved selection of counties as new shapefile
2. merged table to shapefile
3. weights manager: add polyid and create queen weights
4. create univariate LISA
5. zoom in to 50 contiguous states

crash

**Comment by lixun910** [comment]
ref to fix #1923 https://github.com/GeoDaCenter/geoda/issues/1923
Also put an enhancement of basemap rendering by limiting the threads downloading tiles less than the # of CPU cores.
