### ISSUE TITLE
Enhancement for vertical axis

### ISSUE THREAD

**Issue by Polskamoze** [GeoDaCenter/geoda#1947]
![image](https://user-images.githubusercontent.com/33057199/64904176-b8130b00-d6f8-11e9-81a8-b6c4a3ac2687.png)
In Windows x64 version, the vertical axis for histograms could be changed from "频率" to "频数", since the vertical axis shows the number of incidence for each bin.

**Comment by lixun910** [comment]
@Polskamoze will do. thanks!

**Comment by lixun910** [comment]
Fixed in new GeoDa 1.14 build: https://www.dropbox.com/s/y15tthfj3y46h15/GeoDa-1.14.0.0-Windows-64bit.exe?dl=0

<img width="280" alt="Screen Shot 2019-09-25 at 7 16 38 PM" src="https://user-images.githubusercontent.com/2423887/65653160-082b8080-dfc9-11e9-994e-7936f53b8f1e.png">
