### ISSUE TITLE
Missing Chinese translation-Boxplot

### ISSUE THREAD

**Issue by Polskamoze** [GeoDaCenter/geoda#1949]
In Windows x64 version, the menu for boxplot has a missing translation for "Hinge", which could be changed to “折叶点(Hinge)”. 
![屏幕截图(4)](https://user-images.githubusercontent.com/33057199/65006148-d6654a80-d934-11e9-8806-cdba367aa9f9.png)

**Comment by lixun910** [comment]
Thanks, @Polskamoze Will update the translations.

**Comment by lixun910** [comment]
fixed in new GeoDa 1.14 buid: https://www.dropbox.com/s/y15tthfj3y46h15/GeoDa-1.14.0.0-Windows-64bit.exe?dl=0

<img width="263" alt="Screen Shot 2019-09-25 at 7 15 45 PM" src="https://user-images.githubusercontent.com/2423887/65653129-ec27df00-dfc8-11e9-9cad-674c7742dfcf.png">
