### ISSUE TITLE
Unable to zoom 3D scatter plot

### ISSUE THREAD

**Issue by Polskamoze** [GeoDaCenter/geoda#1951]
In windows x64 Chinese version, 3D scatterplot cannot be zoomed in or out by pressing the control key and moving the pointer.

**Comment by lixun910** [comment]
@Polskamoze In 3D scatterplot, the control key is used for the red selecting box. One needs to adjust the  x/y/z scrollbar to adjust the size of the selecting box. To zoom in/out the 3D plot, one needs to hold the right-click button and move the mouse up/down.

<img width="819" alt="Screen Shot 2019-09-17 at 9 18 44 AM" src="https://user-images.githubusercontent.com/2423887/65060127-2ab7fc80-d92c-11e9-9342-d30884864299.png">

**Comment by Polskamoze** [comment]
I remember the instruction manual said "Ctrl+click" to zoom in, which I wasn't able to understand at first. Could you also add this instruction to an updated version of instruction manual documentation? Thanks!
