### ISSUE TITLE
Preference setting menu display error

### ISSUE THREAD

**Issue by Polskamoze** [GeoDaCenter/geoda#1952]
![image](https://user-images.githubusercontent.com/33057199/65128588-50c4c600-da2c-11e9-8d96-82e4c2131d32.png)
In Windows x64 Chinese version, the preferences menu setting for "system" tab has display errors as in the screenshot.

**Comment by lixun910** [comment]
@Polskamoze  I've tested it on my side using Win7 and Win 10 on a windows surface laptop, and the preference dialog looks good. Can you tell us which version of windows are you running (win10 or win8)? is it on a PC or laptop (or is it on a virtual machine)? so I can replicate and fix it. Thanks!

<img width="677" alt="Screen Shot 2019-09-18 at 7 41 50 AM" src="https://user-images.githubusercontent.com/2423887/65159256-a6777f00-d9e8-11e9-8891-de9d9b357935.png">
<img width="677" alt="Screen Shot 2019-09-18 at 7 44 48 AM" src="https://user-images.githubusercontent.com/2423887/65159265-a9726f80-d9e8-11e9-8891-3398999e5ea1.png">

**Comment by lixun910** [comment]
Merge to #1953

**Comment by lixun910** [comment]
Thanks, @Polskamoze  ! Can you help to verify if this issue has been fixed in this new build:
Windows 64bit: https://www.dropbox.com/s/y15tthfj3y46h15/GeoDa-1.14.0.0-Windows-64bit.exe?dl=0
Thanks!

**Comment by Polskamoze** [comment]
Win10 laptop. Thanks! 
On 09/18/2019 22:48, Xun Li wrote:

@Polskamoze I've tested it on my side using Win7 and Win 10 on a windows surface laptop, and the preference dialog looks good. Can you tell us which version of windows are you running (win10 or win8)? is it on a PC or laptop (or is it on a virtual machine)? so I can replicate and fix it. Thanks!

**Comment by lixun910** [comment]
Thanks @Polskamoze!
Can you help to verify if this issue has been fixed in this new build?
Windows 64bit:
https://www.dropbox.com/s/y15tthfj3y46h15/GeoDa-1.14.0.0-Windows-64bit.exe?dl=0
Thanks!

**Comment by lixun910** [comment]
Fixed in new GeoDa 1.14 build:  https://www.dropbox.com/s/y15tthfj3y46h15/GeoDa-1.14.0.0-Windows-64bit.exe?dl=0

<img width="658" alt="Screen Shot 2019-09-25 at 7 19 13 PM" src="https://user-images.githubusercontent.com/2423887/65653251-60fb1900-dfc9-11e9-9e24-7caa8683b40d.png">

**Comment by Polskamoze** [comment]
It has been fixed. Thanks!
