### ISSUE TITLE
Archivo_Preferencias no se muestran

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1953]
Las opciones de preferencias no se muestran, aparecen comprimidas en la parte superior, una sobre la otra. Al desplegar las opciones de idioma, las opciones se hacen visibles, pero aún siguen ocultas.  La ventana de opciones no se puede dimensionar. 

os: 3-4-15
vs: 1-14-0-0
/usr/local/geoda/web_plugins/logger.txt
Click GdaFrame::OnNewProject
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
In GdaFrame::OnHelpAbout()
In GdaFrame::OnCheckUpdates()
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
In GdaFrame::OnCheckUpdates()
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
In GdaFrame::OnReportBug()
Open ReportBugDlg.
In GdaFrame::OnReportBug()
Open ReportBugDlg.
In ReportBugDlg::OnOkClick()

**Comment by evermedina** [comment]
![Captura de pantalla_2019-09-19_19-51-45](https://user-images.githubusercontent.com/8810673/65286795-3e738680-db17-11e9-8a36-b68f6524899b.png)
![Captura de pantalla_2019-09-19_19-52-53](https://user-images.githubusercontent.com/8810673/65286796-3e738680-db17-11e9-9115-25a9c2dc4b0b.png)
![Captura de pantalla_2019-09-19_19-53-07](https://user-images.githubusercontent.com/8810673/65286797-3f0c1d00-db17-11e9-8256-4237ed4f2360.png)

**Comment by lixun910** [comment]
Thank you, @evermedina Will fix it and let you know any updates.

**Comment by lixun910** [comment]
Can only replicate this issue in a virtual machine that has a very low screen resolution:
Can't replicate it on regular windows/mac/linux machines (laptops: English OS and Chinese OS)
To avoid this issue, the scrolled dialog style (e.g in KMeans dialog) will be applied to preference dialog so that there is no cluttered UI controls. see #537ff9142

**Comment by evermedina** [comment]
The screen resolution in my Netbook is 1366x768

**Comment by lixun910** [comment]
Thanks! @evermedina Can you help to verify if this new build fixes this issue? 
Ubuntu 18.04: https://www.dropbox.com/s/yqxb2p1xpgha6wm/geoda_1.14.1-1bionic1_amd64.deb?dl=0
Thanks!

**Comment by lixun910** [comment]
Yes, the height 768pixel is not enough to fit the preference dialog.
However, this should be fixed in the new build I just sent, and you can use
mouse to scroll the content of the preference dialog.

Btw, what desktop environment did you use? it looks different than the GTK
in Ubuntu bionic/xenial.

**Comment by evermedina** [comment]
It looks good in Xubuntu 18.04
![Captura de pantalla_2019-09-24_22-42-30](https://user-images.githubusercontent.com/8810673/65563639-a3b4e680-df20-11e9-93d4-8158aaffcfd7.png)
![Captura de pantalla_2019-09-24_22-42-59](https://user-images.githubusercontent.com/8810673/65563640-a3b4e680-df20-11e9-9b9e-e9e689eed02b.png)
![Captura de pantalla_2019-09-24_22-43-47](https://user-images.githubusercontent.com/8810673/65563641-a3b4e680-df20-11e9-841a-6495b19e8d46.png)

**Comment by evermedina** [comment]
An idea / request: you could place the scroll bar only in the "System" dialog. The "System" and "Data sourse" tabs, and the "Reset" and "Closet" buttons without the scroll bar. Sorry for my English.

**Comment by lixun910** [comment]
Sounds good! @evermedina will do and apply in next release. Thank you again!
