### ISSUE TITLE
Crash Report Ubuntu 19.04

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1955]
From: antony.barja8@gmail.com
 Details:
os: 3-5-0
vs: 1-14-0-0
/usr/local/geoda/web_plugins/logger.txt
Click GdaFrame::OnNewProject
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/antony/Descargas/PCA_Amazonia/VUL.shp
Entering OGRTable::OGRTable
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open LisaMapFrame (OnOpenUniLisa).
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
selected:0
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
1.44346
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
1.78262
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
2.29136
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
2.80009
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
3.64799
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
3.98714
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
4.83504
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
5.34378
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
6.19167
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
7.20914
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
8.39619
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
9.58325
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
10.9399
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
11.9574
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
12.9748
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
13.8227
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
14.6706
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
15.3489
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
16.1968
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
16.8751
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
17.8926
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
18.0622
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
18.0622
Click CreatingWeightDlg::OnCreateClick
CreateWeights()
/home/antony/Descargas/PCA_Amazonia/VUL.gwt
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Close CreatingWeightDlg
In WeightsManFrame::OnActivate
WeightsManFrame::OnConnectGraphBtn()
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::DisplayWeightsGraph()
Project::GetCentroids()
In WeightsManFrame::OnActivate

**Comment by lixun910** [comment]
This report is from Ubuntu 19.04, which we don't announce an official GeoDa installer yet.

**Comment by lixun910** [comment]
merge to #1954 from Ubuntu 19.04
