### ISSUE TITLE
Lisa crash Ubuntu 19.04 kernel 5.3

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1957]
From: 
 Details:
os: 3-5-3
vs: 1-14-0-0
/usr/local/geoda/web_plugins/logger.txt
Click GdaFrame::OnNewProject
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/media/daniel/SISTEMA/Users/DANIEL/Desktop/Estadística espacial/20142025067/ndvi/ndvi/ndvigrid.geojson
Entering OGRTable::OGRTable
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open GetisOrdMapFrame (OnOpenGetisOrd).
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Open GetisOrdMapFrame (OnOpenGetisOrd).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
GREEN
VariableSettingsDlg::GetWeightsId() weight: ndvigrid
VariableSettingsDlg::GetWeightsId() weight: ndvigrid
Entering GStatCoordinator::GStatCoordinator().
In GStatCoordinator::SetSignificanceFilter
Exiting GStatCoordinator::SetSignificanceFilter
In GStatCoordinator::InitFromVarInfo
In GStatCoordinator::DeallocateVectors
Out GStatCoordinator::DeallocateVectors
In GStatCoordinator::AllocateVectors
Out GStatCoordinator::AllocateVectors
In GStatCoordinator::CalcGs()
Out GStatCoordinator::CalcGs()
Entering GStatCoordinator::CalcPseudoP
Exiting GStatCoordinator::CalcPseudoP
Out GStatCoordinator::InitFromVarInfo
Exiting GStatCoordinator::GStatCoordinator().
Entering GetisOrdMapFrame::GetisOrdMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Entering GetisOrdMapCanvas::GetisOrdMapCanvas
In GStatCoordinator::FillClusterCats()
Out GStatCoordinator::FillClusterCats()
Exiting GetisOrdMapCanvas::GetisOrdMapCanvas
Exiting GetisOrdMapFrame::GetisOrdMapFrame
Entering GetisOrdMapFrame::GetisOrdMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Entering GetisOrdMapCanvas::GetisOrdMapCanvas
In GStatCoordinator::FillClusterCats()
Out GStatCoordinator::FillClusterCats()
Exiting GetisOrdMapCanvas::GetisOrdMapCanvas
Exiting GetisOrdMapFrame::GetisOrdMapFrame
In GetisOrdMapFrame::OnActivate
In GetisOrdMapFrame::MapMenus
In GetisOrdMapFrame::OnActivate
In GetisOrdMapFrame::OnActivate
In GetisOrdMapFrame::MapMenus
In GetisOrdMapFrame::~GetisOrdMapFrame
In GetisOrdMapCanvas::~GetisOrdMapCanvas
MapCanvas::~MapCanvas()
In GetisOrdMapFrame::OnActivate
In GetisOrdMapFrame::MapMenus
In GetisOrdMapFrame::~GetisOrdMapFrame
In GStatCoordinator::~GStatCoordinator
In GStatCoordinator::DeallocateVectors
Out GStatCoordinator::DeallocateVectors
In GetisOrdMapCanvas::~GetisOrdMapCanvas
MapCanvas::~MapCanvas()
Open LisaMapFrame (OnOpenMultiLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
GREEN
PREC
VariableSettingsDlg::GetWeightsId() weight: ndvigrid
VariableSettingsDlg::GetWeightsId() weight: ndvigrid
Entering AbstractCoordinator::AbstractCoordinator().
Entering AbstractCoordinator::SetSignificanceFilter()
Exiting AbstractCoordinator::SetSignificanceFilter()
Exiting AbstractCoordinator::AbstractCoordinator().
Entering LisaCoordinator::LisaCoordinator().
Entering AbstractCoordinator::InitFromVarInfo()
Entering LisaCoordinator::Init()
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
Entering LisaCoordinator::AllocateVectors()
Exiting LisaCoordinator::AllocateVectors()
Entering LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::StandardizeData()
Exiting LisaCoordinator::Init()
Entering AbstractCoordinator::DeallocateVectors()
Exiting AbstractCoordinator::DeallocateVectors()
Entering AbstractCoordinator::AllocateVectors()
Exiting AbstractCoordinator::AllocateVectors()
Entering LisaCoordinator::Calc()
Exiting LisaCoordinator::Calc()
Entering AbstractCoordinator::CalcPseudoP_threaded()
Exiting AbstractCoordinator::CalcPseudoP_threaded()
Exiting AbstractCoordinator::InitFromVarInfo()
Exiting LisaCoordinator::LisaCoordinator().
Entering LisaScatterPlotFrame::LisaScatterPlotFrame
Exiting LisaScatterPlotFrame::LisaScatterPlotFrame
Entering LisaMapFrame::LisaMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Entering AbstractMapCanvas::AbstractMapCanvas
Exiting AbstractMapCanvas::AbstractMapCanvas
Entering LisaMapCanvas::LisaMapCanvas
Exiting LisaMapCanvas::LisaMapCanvas
In AbstractCoordinator::registerObserver()
Exiting LisaMapFrame::LisaMapFrame
In LisaMapFrame::~LisaMapFrame
Entering AbstractCoordinator::removeObserver
In LisaCoordinator::~LisaCoordinator().
Entering LisaCoordinator::DeallocateVectors()
Exiting LisaCoordinator::DeallocateVectors()
In AbstractCoordinator::~AbstractCoordinator().
Entering AbstractCoordinator::DeallocateVectors()
Exiting AbstractCoordinator::DeallocateVectors()
Exiting AbstractCoordinator::removeObserver
In LisaMapCanvas::~LisaMapCanvas
In AbstractMapCanvas::~AbstractMapCanvas
MapCanvas::~MapCanvas()

**Comment by lixun910** [comment]
Looks like a NDVI grid map, "GREEN" + "PREC" (precipitation?) is used to create a bivariate LISA. 
Does anyone know such a NDVI dataset?

**Comment by lixun910** [comment]
I think its: https://geodacenter.github.io/data-and-lab/ndvi/
But I can't replicate a crash

**Comment by lixun910** [comment]
one thing that the report is from a linux kernel version 5.3, which is very new (9/2019) and not covered with our official release. The latest Ubuntu 19.04 (Disco Dingo) comes with linux kernel version 5.0.
