### ISSUE TITLE
Ubuntu 19.04 kernel 5.0

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1975]
From: 
 Details:
os: 3-5-0
vs: 1-14-0-0
/usr/local/geoda/web_plugins/logger.txt
Click GdaFrame::OnNewProject
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/fernandobarbosa/data/raw/br_municipios/BRMUE250GC_SIR.shp
Open Layer:BRMUE250GC_SIR
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/fernandobarbosa/data/raw/br_municipios/BRMUE250GC_SIR.shp
Entering OGRTable::OGRTable
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open ExportDataDlg in its Init()
Project::GetSpatialReference()
In ExportDataDlg::OnOkClick()
ds:
In ExportDataDlg::BrowseExportDataSource()
In ExportDataDlg::OnOkClick()
ds:/home/fernandobarbosa/data/processed/novmap/novmap_br_municipios.shp
Project::GetSpatialReference()
In OGRDataAdapter::ExportDataSource()
ScrolledWidgetsPane::IsFieldNameValid
ScrolledWidgetsPane::IsFieldNameValid
In FieldNameCorrectionDlg
Out FieldNameCorrectionDlg
start OGRLayerProxy::AddFreatures()
Out OGRDataAdapter::ExportDataSource()
In MapFrame::OnMapAddLayer()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/fernandobarbosa/development/novmap/test_fpd.geojson
Open Layer:test_fpd
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
ds:/home/fernandobarbosa/development/novmap/test_fpd.geojson layer: test_fpd
MapCanvas::DisplayMapLayers()
MapCanvas::DisplayMapLayers()
In MapFrame::OnMapAddLayer()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
ds:/home/fernandobarbosa/data/raw/br_municipios/BRMUE250GC_SIR.shp layer: BRMUE250GC_SIR
MapCanvas::DisplayMapLayers()
MapCanvas::DisplayMapLayers()
MapCanvas::DisplayMapLayers()
Open AbstractClusterDlg.
In KClusterDlg()
In KMeansDlg()
OnClickClose KClusterDlg.
In ~KMeansDlg()
In ~KClusterDlg()
In MapFrame::OnMapAddLayer()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
ds:/home/fernandobarbosa/development/novmap/test_fpd.geojson layer: test_fpd
In MapFrame::OnMapAddLayer()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
ds:/home/fernandobarbosa/development/novmap/test_fpd.geojson layer: test_fpd
MapCanvas::~MapCanvas()
In TableFrame::OnActivate
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
Entering GdaFrame::OnMapChoices
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
Open CatClassifFrame
CatClassifPanel::OnButtonNew
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
Click GdaFrame::OnNewProject
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/fernandobarbosa/development/novmap/test_fpd.geojson
Entering OGRTable::OGRTable
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In MapFrame::OnMapAddLayer()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
ds:/home/fernandobarbosa/data/raw/br_municipios/BRMUE250GC_SIR.shp layer: BRMUE250GC_SIR
MapCanvas::~MapCanvas()
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
Click GdaFrame::OnNewProject
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/fernandobarbosa/development/novmap/test_fpd.geojson
Entering OGRTable::OGRTable
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In MapFrame::OnMapAddLayer()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
ds:/home/fernandobarbosa/data/raw/br_municipios/BRMUE250GC_SIR.shp layer: BRMUE250GC_SIR
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
MapCanvas::~MapCanvas()
Click GdaFrame::OnNewProject
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/fernandobarbosa/development/novmap/test_fpd.geojson

**Comment by lixun910** [comment]
Data used in this report was found: ftp://geoftp.ibge.gov.br/organizacao_do_territorio/malhas_territoriais/malhas_municipais/municipio_2015/Brasil/BR/br_municipios.zip
