### ISSUE TITLE
Map view resize error

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#2034]
GeoDa 1.14
Mac OSX

Steps:
1. reduce size of map view to only header and footer (which I did by accident and this is edge case)
2. Result see screenshot:

<img width="438" alt="geoda crash" src="https://user-images.githubusercontent.com/13679743/71643614-814e0a00-2c81-11ea-98fa-63cddf1ae7dd.png">

**Comment by lixun910** [comment]
Great catch! fixed in 36d5f8697
