### ISSUE TITLE
Wrong labeling of histogram

### ISSUE THREAD

**Issue by arendligtenberg** [GeoDaCenter/geoda#2069]
When making an histogram of a relatively large dataset (500000+ tweets) we noticed that the labeling of the histogram is not correct (x-axis labels are not under the right bars). 

The column used for the histo was a string column contain the language labels such as 'en'  'nl' etc. About 33 different language id were to be plotted

**Comment by lixun910** [comment]
@arendligtenberg Thanks for reporting this issue! Could you post a screenshot of the histogram window? or you can send it to me at xunli@uchicago.edu. Thanks!

**Comment by lixun910** [comment]
@arendligtenberg This bug should be fixed in latest GeoDa 1.16. Thanks for reporting this bug!
