### ISSUE TITLE
Issue with installers

### ISSUE THREAD

**Issue by AustinAMeyer** [GeoDaCenter/geoda#2123]
Hello,

I have noticed an issue where when installing GeoDa silently (/VERYSILENT /SUPPRESSMSGBOXES) using the system account on Windows computers the installer files don't stop running until the computer reboots even though the software is clearly installed. This can be problematic because this blocks other installers if the computer is trying to install other applications. Is there any way you could possibly fix this for a later release?
<img width="700" alt="image" src="https://user-images.githubusercontent.com/51977145/82231625-05342600-98f3-11ea-87f0-ed75ce0a96b3.png">

Thanks,

Austin

**Comment by lixun910** [comment]
@AustinAMeyer Sorry for the late reply. I am not familiar with installation at system level on Windows. Here are something that might block the installation: 
1) GeoDa installation (created by Inno compiler) will check if visual c++ 2010 redistributable has been installed, so you have to install the visual c++ 2010 redistributable package in the command line in silent mode first. e.g. vc++2010.res.exe /quiet 
2) GeoDa installer will check if the older version GeoDa has been installed, so this silent mode command will only work with a clean installation.
Let me know if this helps. Thanks!
