### ISSUE TITLE
Save Image As

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#214]
I'm getting a number of users who want to edit the map in Adobe Illustrator or similar programs. In GeoDa 1.7.45 (MacOSX), when you select svg as image output, nothing happens. Question is also how this works with the basemap (e.g. possible to export map with basemap as image?)

**Comment by lixun910** [comment]
I can export image as svg with 1.7.45 (MacOSX). Can you verify it again?

I am not quite sure, but I think it will be not easy to save basemap into SVG, because SVG is vector based (XML-based) two-dimensional graphics, and basemap is composed by many small tiles (image files).

**Comment by jkoschinsky** [comment]
Works well now in GeoDa 1.7.63: Basemap is saved with shapefile in png and bmp but not svg. Could you make png files the default (instead of svg) since they have the basemap and are smaller than bmp?

**Comment by jkoschinsky** [comment]
I'll leave this open for future releases to put svg back in for people who want to edit in Illustrator.

**Comment by CyrilWendl** [comment]
Hello! How do you export a figure as SVG? If I export them in GeoDa 1.18.12 for Mac, I only see PNG and BMP as options :-( Would be great if this could be implemented.

**Comment by jkoschinsky** [comment]
Hi, We used to have this but disabled it because people are increasingly
moving to capturing GeoDa images as screenshots.

**Comment by CyrilWendl** [comment]
I would love to see it back personally because I like to put vector graphics in my reports whenever possible to have best print quality. But this is why I would use QGIS mostly to export GeoDa figures. So if you can bring it back as an option to a future release, it would be appreciated.

**Comment by jkoschinsky** [comment]
ok, thanks for this feedback -- we'll discuss this since others have
brought this up as well

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.7 Mac OSX

works for the main map without the basemap

**Comment by jkoschinsky** [comment]
for svg and ps basemap can't be overlayed but users can add themselves in Photoshop etc.
