### ISSUE TITLE
Warning message for unprojected coordinates

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#2190]
- there should be a warning when the coordinates are not projected. For example, when using natregimes, it works, but the centroids are lat-lon, which is wrong. I guess when  there is projection information it’s easy to detect when the coordinates are in lat-lon, but when there is no projection information, I’m nor sure if that can be done easily.

It if can be detected, there should be a warning:
  “Warning: coordinates are not projected, distance will be incorrect”
  And then a choice: Proceed anyway Yes, No with No as the default

 If it cannot be detected without projection information then the warning should be:
  “Warning: unknown projection information, distance may be incorrect”
  and then the same choice.

Most importantly, I think the interface should be made consistent with the interface for Skater and SCHC etc., where a weights file must be specified rather than computing queen contiguity on the fly. That would also make is more general and allow network weights etc to be specified.

**Comment by lanselin** [comment]
Same warning is needed for heat map and minimum  spanning tree, since those also rely on Euclidean distances, so that would be incorrect using lat-lon

**Comment by lixun910** [comment]
When load natregimes, add mean centers or centroids to the table, they are in decimal degrees,
so not suitable for clustering.

When then invoke k-means and use the coordinates for clustering, there is no warning - with
other variables or without. K-means uses the centroids in (standardized) decimal degrees, which
is not correct.

solution:
add <X-Centroids> and <Y-Centroids> list them in the “Select Variable” list box:
<img width="436" alt="Screen Shot 2020-07-31 at 2 01 28 PM" src="https://user-images.githubusercontent.com/2423887/89082903-42318580-d344-11ea-97fd-33714fd5ea05.png">

**Comment by lixun910** [comment]
implement the same check we have in the cluster methods in the weights manager

**Comment by lixun910** [comment]
1) if the data is lat-lon and one tries to create Euclidean distance, there should be a warning. 
2) Similarly, if the data are projected and one tries to create an arc distance, same warning.
