### ISSUE TITLE
Help joining relative longitude and latitude data from 2 files. 

### ISSUE THREAD

**Issue by unomics20** [GeoDaCenter/geoda#2191]
Hello All, 

Can you please help me understand if I can obtain community areas for a list of longitudinal and latitudinal addresses. 

**What I have:**

1. I have a shapefile for community areas

2. I have Data set A with columns:
ID - identifiers
Longitude 
Latitude 

Here Longitude and Latitude data represent **specific addresses**, I have 954 addresses. 

Data set B: 
City 
Community Area 
Longitude_CA
Latitude_CA

Here Longitude_CA and Latitude_CA represent the  **Longitude and Latitude for each of  77 community areas**

Is there a way that I can match the Longitude and Latitudinal community area data in Data set B to the longitudinal and latitudinal data for specific addresses (data set A)? 

Here mapping isn't the goal rather to match my addressess to a specific community area. Any help on this is greatly appreciated.

**Comment by lanselin** [comment]
Hi:
This GitHub site is really to report on issues with the software. For other help, like your question, the openspace list should be used:
openspace-list@googlegroups.com 

If you have a shape file with community area boundaries in lat-lon, but just a file with the addresses, then here would be how to proceed:
- create a shape file with the addresses as a point layer -- make sure to specify the projection information for EPSG:4326, that is, enter +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs in the projection definition box before saving the point layer

Then, if you want an ID for the points, start by loading the point layer. Then add the community area layer using the + command in the map window.

Select Tools > Spatial Join.  Select the area ID as the ID Variable.

This will add the community area ID for each point in the point layer. Then save the new point layer.

A detailed illustration is given in 
https://geodacenter.github.io/workbook/01_datawrangling_3/lab1.html

Hope this helps. Sorry for the delay.

L.
