### ISSUE TITLE
hdbscan Update

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#2195]
GeoDa crashes when the min cluster size is larger than the number of observations.
Obviously an edge case, but maybe this can be caught with a warning - similar to the
warning that no clusters can be found.

Example is the 7 point toy data set where hdbscan has min cluster size at 10 by default.

Compare to warning for DBscan.

<img width="419" alt="Screen Shot 2020-07-31 at 5 43 07 PM" src="https://user-images.githubusercontent.com/4008351/89083029-5b8efd80-d355-11ea-866c-7d238f0f3835.png">

**Comment by lixun910** [comment]
Something is still not quite right in the condensed tree, see below.
For min cluster size 20 and min points 10 the map shows 4 clusters,
but the condensed tree only shows three. (liquor store Chicago dataset)

When I select on the tree, I get the clusters back in the cluster map,
but only three of them. When I select cluster 4 in the map, nothing
is selected in the condensed tree.

<img width="1148" alt="Screen Shot 2020-08-15 at 11 37 55 AM" src="https://user-images.githubusercontent.com/2423887/90430585-95ae0e00-e07c-11ea-9f83-933caa96eb31.png">

**Comment by lixun910** [comment]
Condensed Tree: add Zoom in/out using mouse wheel or two-finger scroll on trackpad

**Comment by lixun910** [comment]
condensed tree and dendrogram: the color scheme doesn't match with color scheme in map
