### ISSUE TITLE
doubt

### ISSUE THREAD

**Issue by jesus-rafa** [GeoDaCenter/geoda#2207]
Excellent day.

What are the minimum requirements to install GEODA?

Regards.
Thank you.

**Comment by jkoschinsky** [comment]
in Windows, it's the same as the minimum requirement s for Visual Studio's c++ redistributable:

  *   if x86 or AMD64/x64, a 1.6 GHz or faster processor
  *   1 GB of RAM (1.5 GB if running on a virtual machine).
  *   1 GB of available hard disk space.
  *   1024 by 768 or higher display resolution


<https://spatial-data-science-conference.com/>

________________________________

**Comment by jesus-rafa** [comment]
Muchísimas Gracias!
Saludos
