### ISSUE TITLE
 add Median spatial lag to the Spatial Lag tab in the Calculator

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#2237]
In the dialog, we could add a check box for Median Spatial Lag under the boxes for row-standardize.
In the screen shot below, that would be an extra check box. The default stays as is, but when Median Spatial Lag is selected, the row-standardize and diagonal element boxes should be inactive.

<img width="743" alt="Screen Shot 2020-10-12 at 4 19 46 PM" src="https://user-images.githubusercontent.com/2423887/96029465-95798700-0e0f-11eb-8b82-96607f751879.png">

**Comment by emmaxian** [comment]
Hello, how can i download this calculator? Would you please give me a download link of it ? Thank you very much!

**Comment by jkoschinsky** [comment]
it's part of the GeoDa desktop software:
https://geodacenter.github.io/download.html
Download | GeoDa on Github<https://geodacenter.github.io/download.html>
Help us keep GeoDa free by contributing here.Thank you for supporting free and open-source spatial software! GeoDa is continuously updated. The most current version is GeoDa 1.20 with new features.We found it to be stable but if you encounter a bug, please let us know.You can also report bugs and issues on our Github site.The source code for GeoDa is available here and is released under the ...
geodacenter.github.io


Julia Koschinsky, Ph.D.
Executive Director and Senior Research Associate
Center for Spatial Data Science
University of Chicago
https://spatial.uchicago.edu/

<https://spatial-data-science-conference.com/>
________________________________

**Comment by emmaxian** [comment]
Thank you so much for your answer. I have already download the Geoda software, and I not sure I calculate the spatial lag in a right way. Is it calculated by the "single factor local Moran's I" in the "Spatial analyze"? I can find spatial lag in the result of local Moran's I. But we can not upload self-defined matrix into Geoda, does Geoda can calculate the spatial lag in other way with self-defined matrix? That's all my questions, thank you so much again!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GeoDaCenter/geoda"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月8日(星期二) 上午10:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GeoDaCenter/geoda]  add Median spatial lag to the Spatial Lag tab in the Calculator (#2237)





 it's part of the GeoDa desktop software:
 https://geodacenter.github.io/download.html
 Download | GeoDa on Github<https://geodacenter.github.io/download.html&gt;
 Help us keep GeoDa free by contributing here.Thank you for supporting free and open-source spatial software! GeoDa is continuously updated. The most current version is GeoDa 1.20 with new features.We found it to be stable but if you encounter a bug, please let us know.You can also report bugs and issues on our Github site.The source code for GeoDa is available here and is released under the ...
 geodacenter.github.io
 
 
 Julia Koschinsky, Ph.D.
 Executive Director and Senior Research Associate
 Center for Spatial Data Science
 University of Chicago
 https://spatial.uchicago.edu/
 
 <https://spatial-data-science-conference.com/&gt;
 ________________________________

**Comment by jkoschinsky** [comment]
here are the steps to calculate spatial lags:
https://geodacenter.github.io/workbook/4d_weights_applications/lab4d.html#spatially-lagged-variables

You cannot upload your own spatial weights matrix into GeoDa but you could modify or create a new spatial weights file (.gal<https://geodacenter.github.io/workbook/4a_contig_weights/lab4a.html#gal-weights-file> or .gwt<https://geodacenter.github.io/workbook/4b_dist_weights/lab4b.html#gwt-file>), which can then be used by GeoDa to create spatially lagged variables.


Julia Koschinsky, Ph.D.
Executive Director and Senior Research Associate
Center for Spatial Data Science
University of Chicago
https://spatial.uchicago.edu/

<https://spatial-data-science-conference.com/>
________________________________

**Comment by emmaxian** [comment]
Thank you so much for your patient! I get it. WISH YOU HAVE A GREAT DAY!!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GeoDaCenter/geoda"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月8日(星期二) 中午1:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GeoDaCenter/geoda]  add Median spatial lag to the Spatial Lag tab in the Calculator (#2237)





 here are the steps to calculate spatial lags: 
 https://geodacenter.github.io/workbook/4d_weights_applications/lab4d.html#spatially-lagged-variables 
 
 You cannot upload your own spatial weights matrix into GeoDa but you could modify or create a new spatial weights file (.gal<https://geodacenter.github.io/workbook/4a_contig_weights/lab4a.html#gal-weights-file&gt; or .gwt<https://geodacenter.github.io/workbook/4b_dist_weights/lab4b.html#gwt-file&gt;), which can then be used by GeoDa to create spatially lagged variables. 
 
 
 Julia Koschinsky, Ph.D. 
 Executive Director and Senior Research Associate 
 Center for Spatial Data Science 
 University of Chicago 
 https://spatial.uchicago.edu/ 
 
 <https://spatial-data-science-conference.com/&gt; 
 ________________________________
