### ISSUE TITLE
Geoda / Thiessen polygons / Zone square

### ISSUE THREAD

**Issue by Grimjouw** [GeoDaCenter/geoda#2280]
Hi! i have a map showing pharmacies location. I build Thiessen polygons around the points (pharmacies) and i'd like to count square of each zone and colorize them in accordance with its size. Is it possible to do in Geoda? I know how to do it in ArcGis but i can't find the way to do it in Geoda. 

Appreciate any help/

![Polygons](https://user-images.githubusercontent.com/74733302/99706635-2a316d80-2abd-11eb-8e74-b89a349771b3.png)

**Comment by lixun910** [comment]
@Grimjouw You can export the Thiessen polygons to a new shapefile, and then load it in GeoDa as a polygon layer. You can also merge the data from points to Thiessen polygons then.
