### ISSUE TITLE
Windows: GDAL and Proj registry keys are set globally and interfere with other software packages

### ISSUE THREAD

**Issue by shawnlaffan** [GeoDaCenter/geoda#2374]
OS: Windows 10
GeoDa version: 1.20.8 (latest)

The lines below in the installer script set the GDAL and Proj environment variables in the system registry, globally.  These can then impact other software packages which use different versions of GDAL and Proj.  If I uninstall GeoDa then these other packages work properly.

These variables should be set by GeoDa at run time instead of globally at install time.  

https://github.com/GeoDaCenter/geoda/blob/f46340390f87662b74aaebeb00ab07ae97458885/BuildTools/windows/installer/64bit/GeoDa.iss#L102-L106

Example error is below for software that makes no use of GeoDa, and when GeoDa is not in the path: 

```
Can't load requested DLL: C:\Program Files\GeoDa Software\ogr_FileGDB.dll
126: The specified module could not be found.
```

The registry keys might not be the full story, though, as deleting them while keeping GeoDa does not fix the situation.  Possibly there are other GeoDa components that have side effects.  (Edit - windows seems to keep these env vars set for future cmd windows despite them being deleted from the registry.  Rebooting clears them.)

It's speculation, but I wonder if this has something to do with the regular GeoDa crashes I am experiencing.

**Comment by lixun910** [comment]
Thanks, @shawnlaffan! I will take a look at it.

**Comment by lixun910** [comment]
@shawnlaffan I just removed the GDAL related dll registry from the windows installer, and GeoDa will setup the GDAL env in the runtime. Here is a new build: https://github.com/GeoDaCenter/geoda/releases/download/v1.20/GeoDa-Windows7+-x64-installer.zip
Let me know if this works as expected. Thanks!

**Comment by shawnlaffan** [comment]
Thanks @lixun910  - that seems to have fixed the issue.  

Shawn.
