### ISSUE TITLE
Build for Ubuntu 24.04

### ISSUE THREAD

**Issue by tcubano** [GeoDaCenter/geoda#2493]
**Is your feature request related to a problem? Please describe.**
There's no build for Ubuntu 24.04, only 20.04 and 22.04, and this makes it hard for beginners to install the program.

**Describe the solution you'd like**
I see Github runner images (https://github.com/actions/runner-images) already has Ubuntu 24.04 available to deploy, so I suggest using it. 

**Describe alternatives you've considered**
For now, #2482 works as an alternative to install not only on newer releases of Ubuntu, but also on other distros. Nevertheless, a native release on Ubuntu 24 would be simpler.

Thanks so much for the software and the work you guys do!

**Comment by lixun910** [comment]
Thank you! @tcubano Can you help to verify if this build works on 24.04: https://github.com/GeoDaCenter/geoda/actions/runs/10568695856 Scroll down, you will see GeoDa-1.22.0-noble https://github.com/GeoDaCenter/geoda/actions/runs/10568695856/artifacts/1857154775

**Comment by lixun910** [comment]
Just make another build with freeglut3-dev on ubuntu 24.04. Can you try it https://github.com/GeoDaCenter/geoda/actions/runs/10602096311/artifacts/1866325262 ? Thanks!

**Comment by tcubano** [comment]
Just tried it and now it gives even more errors... Looks like this new ubuntu version doesn't have older prerequisites available to install alongside the program. Do you have any idea what to do? Is the next step trying to pinpoin which of the dependencies aren't available to try to install alternatives of them? Would it make sense to release the software as a Snap or Flatpak (kind of "complete" packages that have install all their dependencies sandboxed)?  
Thanks very much for your work! 
 
`dpkg: dependency problems prevent configuration of geoda:
 geoda depends on libgdal26; however:
  Package libgdal26 is not installed.
 geoda depends on freeglut3; however:
  Package freeglut3 is not installed.
 geoda depends on libssl1.1; however:
  Package libssl1.1 is not installed.
 geoda depends on libwebkit2gtk-4.0-37; however:
  Package libwebkit2gtk-4.0-37 is not installed.`

**Comment by 300000kms** [comment]
It works fine for me! (in Ubuntu 24.04)
Thanks!

**Comment by lixun910** [comment]
Great! I will merge the pull request and upload the debs in https://github.com/GeoDaCenter/geoda/releases/tag/v1.22.0.8
