### ISSUE TITLE
File input: WFS

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#314]
Testing WFS file input with this URL:
http://ndgishub.nd.gov/arcgis/services/Features/Geology/MapServer/WFSServer

It loads the file (11 earthquake locations) but the table is empty and nothing is displayed on the map: Their data error or our read-in error?

<img width="772" alt="screen shot 2016-02-01 at 1 28 19 pm" src="https://cloud.githubusercontent.com/assets/13679743/12730160/bc834da8-c8e7-11e5-8d10-a46296c53106.png">

**Comment by jkoschinsky** [comment]
this WFS link works fine, so probably data error for other one:

http://demo.mapserver.org/cgi-bin/wfs?SERVICE=WFS&VERSION=1.0.0&REQUEST=getfeature&TYPENAME=continents&MAXFEATURES=100

**Comment by jkoschinsky** [comment]
MapInfo test file works well (open input file as well as drag+drop):
[MapInfo.zip](https://github.com/lixun910/geoda/files/112973/MapInfo.zip)

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.83 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).

**Comment by jkoschinsky** [comment]
just checked this WFS again and now its table is empty as well, so re-opening this ticket:

![screen shot 2016-05-26 at 2 44 21 pm](https://cloud.githubusercontent.com/assets/13679743/15591179/62566838-2350-11e6-97a9-542ddd9925e1.png)

**Comment by lixun910** [comment]
This is a bug in GDAL/OGR library. See the fix in gdal-GeoDa17Merge branch: #1f8843a  
https://github.com/lixun910/gdal/commit/1f8843a52b884c2a8fe66bc5ede454790dc8c971

**Comment by jkoschinsky** [comment]
works now (see below).
Verified in GeoDa 1.8.8 (OSX Yosemite, 10.10.5).

<img width="435" alt="screen shot 2016-07-07 at 12 48 52 am" src="https://cloud.githubusercontent.com/assets/13679743/16643687/9b2a8642-43dc-11e6-93dd-b8b139daa1b8.png">
