### ISSUE TITLE
International GeoDa

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#352]
When we have time, one project is to centralize all of GeoDa's error/warning/help messages, so we can easily update and auto-translate them ("international GeoDa"). This would be key to increasing user numbers, e.g. in China.

**Comment by lixun910** [comment]
http://wxwidgets.info/wxtranslation/

Seems easier than we thought.

**Comment by jkoschinsky** [comment]
cool

**Comment by lixun910** [comment]
[Multilingual Applications with wxWidgets.pdf](https://github.com/GeoDaCenter/geoda/files/1038996/Multilingual.Applications.with.wxWidgets.pdf)
