### ISSUE TITLE
GeoDa blurs on Mac Retina Display

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#353]
I found out this when I tried GeoDa on the MacBook with Retina display. The font and icons are all blur on the Retina display. See the comparison:
<img width="573" alt="screen shot 2016-03-04 at 12 08 53 am" src="https://cloud.githubusercontent.com/assets/2423887/13520460/b1506096-e19d-11e5-9b45-4de8e53bbc9f.png">
<img width="573" alt="screen shot 2016-03-04 at 12 06 03 am" src="https://cloud.githubusercontent.com/assets/2423887/13520461/b320cfdc-e19d-11e5-8412-65a7c07c3d6f.png">

After changing the information in .plist file, the fonts are displaying crisp. But the icons and the maps/plots are still not. 

Will take some time to find a solution.

**Comment by jkoschinsky** [comment]
don't think the difference is that significant - for this week, I think
dealing with the crashes is higher priority

On 4 March 2016 at 00:13, Xun Li <notifications@github.com> wrote:

> I found out this when I tried GeoDa on the MacBook with Retina display.
> The font and icons are all blur on the Retina display. See the comparison:
> [image: screen shot 2016-03-04 at 12 08 53 am]
> <https://cloud.githubusercontent.com/assets/2423887/13520460/b1506096-e19d-11e5-9b45-4de8e53bbc9f.png>
> [image: screen shot 2016-03-04 at 12 06 03 am]
> <https://cloud.githubusercontent.com/assets/2423887/13520461/b320cfdc-e19d-11e5-8412-65a7c07c3d6f.png>
>
> After changing the information in .plist file, the fonts are displaying
> crisp. But the icons and the maps/plots are still not.
>
> Will take some time to find a solution.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lixun910/geoda/issues/353>.
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by lixun910** [comment]
with new wxwidgets library, we can get pretty sharp rendering on high DPI screens (e.g. mac retina or windows surface)!!

<img width="1216" alt="screen shot 2017-01-25 at 8 46 15 pm" src="https://cloud.githubusercontent.com/assets/2423887/22321134/b327997c-e357-11e6-8bec-64c687b5d718.png">

**Comment by lixun910** [comment]
<img width="1185" alt="screen shot 2017-01-25 at 11 42 25 pm" src="https://cloud.githubusercontent.com/assets/2423887/22321151/f66d9f92-e357-11e6-9c38-5c4f2b77eac2.png">
