### ISSUE TITLE
strange error message when using project file

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#377]
using the project file for the nyc data, the shape file is loaded fine, etc.
when closing the file, an error message appears that the geometries will be lost since a table file was loaded (see below), but that's incorrect, a shape file was loaded.

i noticed that the project file lists the dbf file as the data source:
            <datasource>
                <type>DBF</type>
                <path>NYC_Sub_borough_Area.dbf</path>
            </datasource>

could that be an issue?

<img width="418" alt="screen shot 2016-03-13 at 5 06 27 pm" src="https://cloud.githubusercontent.com/assets/4008351/13731490/5fa029a2-e940-11e5-86a8-038b23a1cd7c.png">

**Comment by lixun910** [comment]
Yes, the information in project file cause this error message. The OGR will automatically find the .shp file, if specify dbf file path to open. So, the geometries will be read.

Do you want to not showing the map, if only dbf was specified in open path?

**Comment by lanselin** [comment]
no, this is fine then. the project file is Julia’s and it specifies the dbf as the data source
for some reason. so the error message makes sense, even though it seems 
counterintuitive at first.

**Comment by jkoschinsky** [comment]
yes, this was part of the project file path testing tickets we went through

On 13 March 2016 at 14:30, Luc Anselin <notifications@github.com> wrote:

> no, this is fine then. the project file is Julia’s and it specifies the
> dbf as the data source
> for some reason. so the error message makes sense, even though it seems
> counterintuitive at first.
>
>
> > On Mar 13, 2016, at 5:28 PM, Xun Li <notifications@github.com> wrote:
> >
> > Yes, the information in project file cause this error message. The OGR
> will automatically find the .shp file, if specify dbf file path to open.
> So, the geometries will be read.
> >
> > Do you want to not showing the map, if only dbf was specified in open
> path?
> >
> >
> >
> > > On Mar 13, 2016, at 2:25 PM, Luc Anselin <notifications@github.com>
> wrote:
> > >
> > > using the project file for the nyc data, the shape file is loaded
> fine, etc.
> > > when closing the file, an error message appears that the geometries
> will be lost since a table file was loaded (see below), but that's
> incorrect, a shape file was loaded.
> > >
> > > i noticed that the project file lists the dbf file as the data source:
> > >
> > > DBF
> > > NYC_Sub_borough_Area.dbf
> > > could that be an issue?
> > >
> > > <
> https://cloud.githubusercontent.com/assets/4008351/13731490/5fa029a2-e940-11e5-86a8-038b23a1cd7c.png
> >
> > > —
> > > Reply to this email directly or view it on GitHub <
> https://github.com/lixun910/geoda/issues/377>.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/lixun910/geoda/issues/377#issuecomment-196056254>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lixun910/geoda/issues/377#issuecomment-196056404>.
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter
