### ISSUE TITLE
Problem reading .csv header

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#390]
GeoDa 1.7.103 (OSX Yosemite, 10.10.5)

I read this test csv into GeoDa, where one of the variable names consists of numbers only. In this case, GeoDa doesn't recognize the first row as a header row and instead adds automatic field names and an extra first row.

Question is if it possible to still recognize the header row for cases like this. 

Here's the test file:
[test2.csv.zip](https://github.com/lixun910/geoda/files/207325/test2.csv.zip)

**Comment by lixun910** [comment]
That’s how OGR behaves. The fix is easy as just rename the field name from a pure number to something starts with a letter. We can add a dialog to let user choose which row is field name, even the field type (like excel). Then create a csvt file for OGR reading. However, it will take some time. Let me know if you want this feature in current release.

**Comment by jkoschinsky** [comment]
I would log it for the future since it's more of an edge case.

On 6 April 2016 at 13:57, Xun Li <notifications@github.com> wrote:

> That’s how OGR behaves. The fix is easy as just rename the field name from
> a pure number to something starts with a letter. We can add a dialog to let
> user choose which row is field name, even the field type (like excel). Then
> create a csvt file for OGR reading. However, it will take some time. Let me
> know if you want this feature in current release.
>
>
> > On Apr 6, 2016, at 1:53 PM, jkoschinsky <notifications@github.com>
> wrote:
> >
> > GeoDa 1.7.103 (OSX Yosemite, 10.10.5)
> >
> > I read this test csv into GeoDa, where one of the variable names
> consists of numbers only. In this case, GeoDa doesn't recognize the first
> row as a header row and instead adds automatic field names and an extra
> first row.
> >
> > Question is if it possible to still recognize the header row for cases
> like this.
> >
> > Here's the test file:
> > test2.csv.zip <
> https://github.com/lixun910/geoda/files/207325/test2.csv.zip>
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly or view it on GitHub <
> https://github.com/lixun910/geoda/issues/390>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lixun910/geoda/issues/390#issuecomment-206564335>
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by lixun910** [comment]
same issue as #459

**Comment by jkoschinsky** [comment]
GeoDa 1.8.13.5, OSX

It loads correctly now but replaces all field names to field_1, field_2 etc. (see below). If someone has lots of variables with one that has a numeric name, then renaming all is really frustrating.

Is it possible to only rename the numeric one instead of resetting all?

<img width="566" alt="screen shot 2016-09-15 at 10 41 43 am" src="https://cloud.githubusercontent.com/assets/13679743/18556579/51468cce-7b31-11e6-8b12-e4ff197c7763.png">

<img width="291" alt="screen shot 2016-09-15 at 10 41 52 am" src="https://cloud.githubusercontent.com/assets/13679743/18556586/59553ea6-7b31-11e6-98ab-dba0511ccc58.png">

**Comment by lixun910** [comment]
This is a special case that first row has an integer number as field name, so OGR treats the first line as data not header (field names).

Will add an checkbox option in the dialog to allow user specify first row is data or header.

**Comment by lixun910** [comment]
GeoDa will automatically detect header, and separator.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.5 — Mac OSX

problem persists with these two test cases:
[test.zip](https://github.com/GeoDaCenter/geoda/files/666433/test.zip)

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.9 — Mac OSX
Confirmed fix:

<img width="519" alt="screen shot 2017-01-13 at 6 20 36 am" src="https://cloud.githubusercontent.com/assets/13679743/21929830/848a6792-d958-11e6-8e49-b87319a9825b.png">
