### ISSUE TITLE
gdb table and export problems

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#393]
Verified in GeoDa 1.7.109 (OSX Yosemite, 10.10.5

Just out of curiosity, I tried opening a 13 million gdb point file in GeoDa: It worked, which was pretty amazing:

<img width="1083" alt="screen shot 2016-04-14 at 5 20 00 am" src="https://cloud.githubusercontent.com/assets/13679743/14527744/dedbd5e4-0200-11e6-8dd3-155db153e306.png">

After that everything is very slow but that's ok since you can't do ESDA on 13 million anyway. 
One thing that was weird is that the table was empty:

<img width="1599" alt="screen shot 2016-04-14 at 5 20 32 am" src="https://cloud.githubusercontent.com/assets/13679743/14527944/d5c624b8-0201-11e6-90da-7901adc86466.png">

So I went to check if the tables of smaller gdb display correctly but ran into the same problem using columbus:

<img width="1608" alt="screen shot 2016-04-14 at 5 51 32 am" src="https://cloud.githubusercontent.com/assets/13679743/14528679/95e4b734-0205-11e6-8bf2-2ca192d8f5b9.png">

Also confirmed with Ahmed's foreclosure.gdb:
<img width="760" alt="screen shot 2016-04-14 at 8 52 29 am" src="https://cloud.githubusercontent.com/assets/13679743/14534755/6895c5d8-021f-11e6-9528-2ca85d96965e.png">

Then I went to check if I can export the shapefile in GeoDa to gdb to test the table problem from that angle but ran into the following export problem:

1. Open shapefile
2. save as gdb
3. GeoDa prompts you to select or create gdb folder
4. when you do either, it generates this error:

<img width="942" alt="screen shot 2016-04-14 at 5 53 23 am" src="https://cloud.githubusercontent.com/assets/13679743/14528770/03262f3a-0206-11e6-9982-2765674e3de4.png">

**Comment by lixun910** [comment]
Found the issue:

Since GDAL >1.10, it has a built-in plugin called "OpenFileGDB" to read (no write) gdb directory. But, it looks like buggy (not reading table correctly). It is also a reverse engineering of reading FileGDB, maybe has a potential intellectual issue?

In GeoDa 1.6, user needs to install ESRI's official FileGDB library and configure GeoDa to read/write FileGDB format.

Here is the proposed solution, we will ignore the "OpenFileGDB" plugin, and require user to install ESRI's official FileGDB library. Then run the script "install_plugin.sh" (we provide) to configure it.

**Comment by jkoschinsky** [comment]
ok, sounds good.

I checked the gdb instructions:
---------------------------------------------------------------------------------------------------------------------------------------
3. Setup your Windows system environment for File Geodatabase

Add the path of ESRI File Geodatabase (e.g. C:\FileGDB_API\bin) to PATH system variable in "System Properties" dialog (see following example) (Note: you need to add ; before the File Geodatabase Path)
 
4. Restart GeoDa program, then you should be able to connect to Oracle Spatial database by using GeoDa-Oracle-Plugin
---------------------------------------------------------------------------------------------------------------------------------------

Is the reference to Oracle in 4. a mistaken left-over from copy-pasting from the Oracle instructions?

Otherwise we can close.

**Comment by jkoschinsky** [comment]
Verified in http://geodacenter.github.io/formats.html
