### ISSUE TITLE
list the number of observations in the status bar of the table

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#397]

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.7.3 (OSX Yosemite, 10.10.5).

Fixed:
<img width="472" alt="screen shot 2016-05-20 at 9 06 59 pm" src="https://cloud.githubusercontent.com/assets/13679743/15446258/d0ec13dc-1ece-11e6-895f-228c85bdb66a.png">
