### ISSUE TITLE
Avg Chart: Save dummy format

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#401]
When you save the dummy in the averages chart, the outcome variable is saved as integer even if the original format is real:

<img width="1260" alt="screen shot 2016-04-25 at 8 38 32 am" src="https://cloud.githubusercontent.com/assets/13679743/14826796/238e3936-0ba5-11e6-9d6e-cccb03866eb0.png">

Instead, it should just adopt whatever the original format was in the saved file.

**Comment by lixun910** [comment]
Please verify in 1.8.2

**Comment by jkoschinsky** [comment]
Verified in 1.8.2.
