### ISSUE TITLE
GeoDa 1.8 crashes at zoom-in for point dataset

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#404]
GeoDa 1.8 beta

Replicable crash.
Confidential data sent separately.

**Comment by lixun910** [comment]
Please verify in 1.8.2

**Comment by jkoschinsky** [comment]
Confirmed crash is fixed on my side. Waiting to hear back from user to confirm it works on their end as well. If yes, I'll close.

**Comment by jkoschinsky** [comment]
User confirmed fix.
