### ISSUE TITLE
save time differences in differential Moran and local Moran

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#406]
it would be nice to be able to save the differential variables that are created for the differential Moran scatter plot and the differential local Moran. for example, right now there is no way to see which of the low-low clusters correspond to actual decreases (negative yt - yt-1) vs lower increases (positive yt - yt-1). for interpretation, this can be a crucial difference. the only way to do this right now is to actually create a new variable in the table, which duplicates the calculation already carried out for the differential Moran. for the differential local Moran, this could be added under the "save results" dialog, but the Moran scatter plot has no such dialog. alternatively, we may need an additional way to distinguish the positive changes from the negative changes, not for the standardized variables (in the plot), but for the original differences.

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.6.

Tested manually created difference vs. saved results = identical.

Small thing: By default, both the global and local variable name is DIFF_VAL. Let's differentiate them (e.g. DIFF_VAL2) for LISAs to avoid overwriting the same variable name.

<img width="309" alt="screen shot 2016-05-18 at 6 49 26 pm" src="https://cloud.githubusercontent.com/assets/13679743/15380228/78b46d0a-1d29-11e6-984b-8eef898b485a.png">

Also: Significances --> Significance.

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.7.3 (OSX Yosemite, 10.10.5).

Fixed:
<img width="306" alt="screen shot 2016-05-20 at 9 05 52 pm" src="https://cloud.githubusercontent.com/assets/13679743/15446256/a4551fb2-1ece-11e6-8e31-a81590c66cd4.png">
