### ISSUE TITLE
averages chart save dummy needs both space and time ID

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#408]
currently, a file created with the save dummy button in the averages chart writes out a STID (space time id), a space id (e.g. FIPSNO) and a SPACE and (if appropriate) TIME and INTERACT dummy before the variable with the values; however, there is no time ID. 
for example, selecting 1031 counties from natregimes and looking at HR in 60 for selected and unselected gives the following header:

STID,FIPSNO,SPACE,HR
1,27077,0,       0.000000000
2,53019,0,       0.000000000
3,53065,0,       1.863863416

there is no way to figure out what time period the HR pertains to

same for selected in two time periods:

STID,FIPSNO,TIME,SPACE,INTERACT,HR
1,18083,0,1,0,       3.208135833
2,29189,0,1,0,       1.895199271
3,51165,0,1,0,       4.116751060

i suggest STID,SPACEID,TIMEID,TIME,SPACE,INTERACT,VARIABLE
for example:
STID,FIPSNO,PERIOD,TIME,SPACE,INTERACT,HR
(note that the time id will need to be extracted from the time editor

the reason we need a TIME ID in addition to the space ID (and the STID) is for
compatibility with regression programs for panel data.

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.6 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).

<img width="478" alt="screen shot 2016-05-18 at 6 40 56 pm" src="https://cloud.githubusercontent.com/assets/13679743/15380118/1a967d68-1d28-11e6-8e85-772abca0d497.png">

Note that you need to first specify the spatial variable in the weights creation dialogue before it is saved in the dummy file.
