### ISSUE TITLE
averages chart: number of observations in save dummy file is incorrect

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#410]
when comparing a selection in two time periods, only the selected observations are saved to the "save dummy" file. for example selecting 1031 counties and comparing HR between 60 and 90 from natregimes, creates a file with 2062 observations, with SPACE=1 for all observations. the correct output should be a file with 3085x2 observations, with SPACE=1 for the 1031 selected in 60 and 90.

the save dummy file should always have twice the cross-sectional observations, one for each period, with the selected cross-sectional units = 1 and the second time period = 1.

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.6 (OSX Yosemite, 10.10.5).
nat.shp

Fixed: e.g. for selected (1,412) in time 1 and 2, space dummy = 1,412 for time 1 and 1,412 for time 2 = total of 2,824.
