### ISSUE TITLE
averages chart: interface formatting issue

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#411]
the group summary table in the averages chart bumps the selected period to the second line when "unselected" is chosen in both time periods; for selected it lines up very nicely. looks like an extra space may be needed.

<img width="297" alt="screen shot 2016-04-27 at 6 15 09 pm" src="https://cloud.githubusercontent.com/assets/4008351/14871000/33970164-0ca4-11e6-9d63-72b84954cce2.png">

<img width="297" alt="screen shot 2016-04-27 at 6 14 53 pm" src="https://cloud.githubusercontent.com/assets/4008351/14871015/3aa6d13c-0ca4-11e6-9cd0-fed7533cc5f8.png">

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.6 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).

Fixed in OSX:
<img width="349" alt="screen shot 2016-05-18 at 6 25 18 pm" src="https://cloud.githubusercontent.com/assets/13679743/15379874/1e02161c-1d26-11e6-9ac1-34b0409d9fdf.png">

but not yet in Windows:

**Comment by jkoschinsky** [comment]
Problem persists in current version (also Group1 and Group2 dropdown text truncated at Unselec and Selecte):

![win avg](https://cloud.githubusercontent.com/assets/13679743/15456579/b49902c4-2029-11e6-994f-1924811b035c.png)

**Comment by lixun910** [comment]
Your fonts look bigger than the default windows theme, can you change your theme to default one?. Look at mine:
![screen shot 2016-05-22 at 8 53 29 pm](https://cloud.githubusercontent.com/assets/2423887/15459938/686900da-205f-11e6-9610-1fd2a1b5b76f.png)

**Comment by jkoschinsky** [comment]
Yes, you're right - when I change the display to small, I get the same as you. In this case only the Group1/2 end (d of Unselected) is cut off. Let's just change that and then refer people to changing the display settings to small.

![avg win](https://cloud.githubusercontent.com/assets/13679743/15461096/9f626790-206c-11e6-91a3-7badcd7b8222.png)

**Comment by lixun910** [comment]
Please verify it at 1.8.7.5

**Comment by jkoschinsky** [comment]
1.8.7.5 Win7

almost there :) now only d of unselected is cut off (with small font)

![avgtool2](https://cloud.githubusercontent.com/assets/13679743/15555351/366931f2-227d-11e6-875a-58e05ad6c701.png)

**Comment by jkoschinsky** [comment]
GeoDa 1.8.7.9 Win7
Problem persists:

![avg tool view](https://cloud.githubusercontent.com/assets/13679743/15686504/7edfe8fc-2725-11e6-8d46-2f89e61ee574.png)

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.8  (Win 7 Professional (64-bit)).
No more truncation - fixed.

**Comment by lixun910** [comment]
This should be fixed in 1.8.7.11.
