### ISSUE TITLE
AutoUpdate feature for 1.8

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#412]
Add auto-update feature for 1.8.x and future release.

With internet connection,  when starts GeoDa, GeoDa will automatically check if there's newer version; if there is one, prompt user to update. 
<img width="515" alt="screen shot 2016-04-29 at 5 05 28 pm" src="https://cloud.githubusercontent.com/assets/2423887/14932535/b1850c7c-0e2c-11e6-8dd8-18fc9fed5247.png">

User can choose to skip the update (wont prompt in future until another new version comes out); 

but also be able to run update via menu Help->Check Update or About GeoDa->Check Updates

<img width="286" alt="screen shot 2016-04-29 at 4 52 32 pm" src="https://cloud.githubusercontent.com/assets/2423887/14932537/b95d24b6-0e2c-11e6-8970-08e2065f29b6.png">

If no internet connection or bad internet connection, start GeoDa won't check updates.

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.1
