### ISSUE TITLE
averages chart: number of observations in DID regression incorrect

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#415]
in the DID regression output, the number of observations and degrees of freedom do not seem to take into account the two time periods. for example, using natregimes, it lists 3085 whereas it should be 6170

<img width="575" alt="screen shot 2016-05-03 at 12 57 16 pm" src="https://cloud.githubusercontent.com/assets/4008351/14993497/a1da28b4-1130-11e6-8906-3daba393f3c4.png">

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.6 (OSX Yosemite, 10.10.5).

Fixed:

<img width="588" alt="screen shot 2016-05-18 at 5 34 44 pm" src="https://cloud.githubusercontent.com/assets/13679743/15379136/e4505b42-1d1e-11e6-80c9-b9009c7b2a77.png">
