### ISSUE TITLE
averages chart: DID regression results may be incorrect

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#416]
after exporting the dummy variables and running the DID regression "by hand", the results are different. the intercept is different, but the slope coefficient of the dummy is correct, although with the wrong sign.
for example comparing HR60 and HR70, which sets the time dummy to 1 for 70, it is clear that the mean for 70 is greater than the mean for 60, yet the DID coefficient of the time dummy is negative.

<img width="721" alt="screen shot 2016-05-03 at 12 53 47 pm" src="https://cloud.githubusercontent.com/assets/4008351/14993566/02d9865a-1131-11e6-8a08-33b93facc3cc.png">

<img width="575" alt="screen shot 2016-05-03 at 12 57 16 pm" src="https://cloud.githubusercontent.com/assets/4008351/14993574/0e9568ba-1131-11e6-9a29-169458867fa2.png">

<img width="596" alt="screen shot 2016-05-03 at 12 57 54 pm" src="https://cloud.githubusercontent.com/assets/4008351/14993580/1948e82c-1131-11e6-9a4a-bac23ad3fea4.png">

**Comment by lanselin** [comment]
note how the intercept in the DID regression is the average in year 70, whereas it should be the average in year 60, as in the regular regression output. it seems that maybe the dummies are switched around in the DID regression, i.e., year 60 = 1 and year 70 = 0?

**Comment by jkoschinsky** [comment]
When I checked this, it was using t1 = 1960 = 0 and t2=1970 = 1 -- did you
specify it like this in the averages chart or the other way around?
Xun was just saying the code might not have updated.

On 3 May 2016 at 13:17, Luc Anselin <notifications@github.com> wrote:

> note how the intercept in the DID regression is the average in year 70,
> whereas it should be the average in year 60, as in the regular regression
> output. it seems that maybe the dummies are switched around in the DID
> regression, i.e., year 60 = 1 and year 70 = 0?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoDaCenter/geoda/issues/416#issuecomment-216618413>
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by lanselin** [comment]
see screen shot above, period 1 is 60 and period 2 is 70

**Comment by lanselin** [comment]
note, it seems to be with the time dummy, see results below for south selected and comparison between 60 and 70, both the time and interact coefficient are negative, whereas they should be positive (higher rates in south and in 70)

<img width="562" alt="screen shot 2016-05-03 at 7 28 19 pm" src="https://cloud.githubusercontent.com/assets/4008351/15002413/8c8dfaae-1166-11e6-975e-a55a80f9b809.png">


<img width="555" alt="screen shot 2016-05-03 at 7 34 33 pm" src="https://cloud.githubusercontent.com/assets/4008351/15002419/977ad8b0-1166-11e6-9dd4-986c30f4fc41.png">

<img width="722" alt="screen shot 2016-05-03 at 7 28 12 pm" src="https://cloud.githubusercontent.com/assets/4008351/15002429/b3301318-1166-11e6-95d6-a4a53e1bb3be.png">

**Comment by lanselin** [comment]
sorry, here is the correct screen shot for the dummy variable regression

<img width="559" alt="screen shot 2016-05-03 at 7 32 15 pm" src="https://cloud.githubusercontent.com/assets/4008351/15002455/e0678776-1166-11e6-9053-3cb2fff96121.png">

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.6 (OSX Yosemite, 10.10.5).
nat.shp using same specification as above

The results now match in all cases:

<img width="1203" alt="screen shot 2016-05-18 at 9 49 54 pm" src="https://cloud.githubusercontent.com/assets/13679743/15382938/ad9b6a5e-1d43-11e6-97a9-828043feafa6.png">

<img width="1130" alt="screen shot 2016-05-18 at 9 53 36 pm" src="https://cloud.githubusercontent.com/assets/13679743/15382943/b27bf4f8-1d43-11e6-919e-a05c7ffafeeb.png">

<img width="1201" alt="screen shot 2016-05-18 at 9 57 54 pm" src="https://cloud.githubusercontent.com/assets/13679743/15382945/b78276d4-1d43-11e6-8584-c8ee8d1b9614.png">
