### ISSUE TITLE
auto update needs "testing version" and handle poor internet connection

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#418]
1. For testing purpose, a subversion of minor version (odd number) is introduced. For example.
release version: 1.8.4
testing version: 1.8.5  (bug fixe - verify)
testing version: 1.8.5.1 (bug fixe - verify)
testing version: 1.8.5.3 (bug fixe - verify)
...
 (when testing done)
release version: 1.8.6

Testers need to enable the "Testing Mode" by checking the box in "About GeoDa" dialog. 
Normal users can only get updates of release versions (ends with with even number) 

<img width="295" alt="screen shot 2016-05-05 at 1 12 49 pm" src="https://cloud.githubusercontent.com/assets/2423887/15055758/1e88f94c-12c3-11e6-9c5e-05d434d8ec4d.png">

2. With poor internet connection, GeoDa might hangs for about 10 seconds (which is the default response time of LibCurl). This should be addressed.

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.6.
