### ISSUE TITLE
averages chart: correct d.f. for difference in means test?

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#419]
I believe the D.F. listed in the "Do Means Differ" result may be incorrect for the case where all observations are compared in two time periods and when a selection is compared in two time periods. It is correct when a selection is compared to unselected in the same cross-section.

For example, using all in 60 and 70, the D.F. are listed as 3084 (i.e., 3085-1), but the F test in the regression is for a degrees of freedom of 6268 (i.e., 3085x2 - 2) with the identical value for the statistic.
Similarly, for the comparison of selected over two time periods, the d.f. is given as 1411 (i.e. 1412-1).
Shouldn't it be 2822? (1412x2 - 2)

<img width="719" alt="screen shot 2016-05-05 at 4 54 47 pm" src="https://cloud.githubusercontent.com/assets/4008351/15058737/9bcb3f94-12e3-11e6-86ee-8d107ce66763.png">

<img width="558" alt="screen shot 2016-05-05 at 4 55 04 pm" src="https://cloud.githubusercontent.com/assets/4008351/15058745/a63c743e-12e3-11e6-8264-b931b66b8def.png">

<img width="721" alt="screen shot 2016-05-05 at 4 55 44 pm" src="https://cloud.githubusercontent.com/assets/4008351/15058755/b2af4728-12e3-11e6-9110-a2a1c60af46f.png">

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.6 (OSX Yosemite, 10.10.5).

DF values in Averages Tool view now correct (3085x2 - 2 = 6,168):

<img width="1397" alt="screen shot 2016-05-18 at 11 51 14 am" src="https://cloud.githubusercontent.com/assets/13679743/15371105/d67eeeaa-1cee-11e6-8da2-b5d703802aec.png">

but there's still a mismatch for the case of selected vs unselected in the same time period (3083 vs 3084) for the same F-test value:

<img width="1278" alt="screen shot 2016-05-18 at 11 54 05 am" src="https://cloud.githubusercontent.com/assets/13679743/15371302/a2c721d0-1cef-11e6-9e61-d713783b80fd.png">

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.7.3 (OSX Yosemite, 10.10.5).

Fixed:
<img width="1332" alt="screen shot 2016-05-20 at 9 09 30 pm" src="https://cloud.githubusercontent.com/assets/13679743/15446265/2b6220e0-1ecf-11e6-8cef-3670ae723b31.png">
