### ISSUE TITLE
space-time regression: strange error in loading space-time weights gal file

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#421]
After creating a dummy variable file from the averages tool, the matching gal file generates a strange error - see below. The same error appears whether the csv and gal file are generated from save dummy in the cross-sectional case (selected vs unselected) or the space-time case (all in two periods, or selected in two periods). The STID in question is actually present in the data file (see screen shots).
Note that this error is the same whether the csv/gal file pertains to the cross-section (i.e., the standard case with 3085 observations) or the space-time case (with 6170 observations).

error message:
<img width="419" alt="screen shot 2016-05-05 at 5 18 37 pm" src="https://cloud.githubusercontent.com/assets/4008351/15059119/5217be92-12e6-11e6-98f1-9b52ec021e43.png">

the STID is actually on line 46 of the gal file:
<img width="173" alt="screen shot 2016-05-05 at 5 20 14 pm" src="https://cloud.githubusercontent.com/assets/4008351/15059124/5fe2bb94-12e6-11e6-92cd-8c92dcd5f2ce.png">

the STID is present in the csv file:
<img width="319" alt="screen shot 2016-05-05 at 5 20 50 pm" src="https://cloud.githubusercontent.com/assets/4008351/15059135/676d5b08-12e6-11e6-986d-8f18eed29b93.png">

**Comment by jkoschinsky** [comment]
GeoDa 1.8.6 (OSX Yosemite, 10.10.5).

Problem persists.
Steps: 
1. Save dummy in averages chart (in my case selected vs unselected, time 0).
2. Open associated gal file in weights manager that is created at the same time

Result is this same error:

<img width="424" alt="screen shot 2016-05-18 at 7 14 13 pm" src="https://cloud.githubusercontent.com/assets/13679743/15380629/fa71a4d6-1d2c-11e6-8108-c29a79b77437.png">

**Comment by lixun910** [comment]
It should be fixed: I've verified on my side. Please reverify it again. Thanks!

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.7.3 (OSX Yosemite, 10.10.5).

Loads gal file without error now.
