### ISSUE TITLE
GeoDa memorizes last input in DB input not working; Invalid connection causes crash;

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#422]

**Comment by jkoschinsky** [comment]
Could you add a description for this, e.g. is the problem that in this database dialog previously entered DB details were not memorized correctly, and with incorrect entries, the program would crash?

<img width="571" alt="screen shot 2016-05-18 at 7 23 37 pm" src="https://cloud.githubusercontent.com/assets/13679743/15380769/16fead1e-1d2e-11e6-9b39-6bdf832e95a0.png">

**Comment by lixun910** [comment]
On windows, the previous versions can't memorize the last input of this "database" tab (randomly input)
If you input randomly, it will crash in previous versions.

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.7.3 (OSX Yosemite, 10.10.5).

Fixed: Entered random characters: Now program no longer crashes and generates warning instead:

<img width="574" alt="screen shot 2016-05-20 at 9 02 59 pm" src="https://cloud.githubusercontent.com/assets/13679743/15446247/59405f96-1ece-11e6-871d-65881ffe7761.png">
