### ISSUE TITLE
selection tool: # of selected does not seem to be updated correctly

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#424]
There seems to be a problem with the number selected shown on the status bar. For example, using natregimes, when selecting all the negative changes in HR80-HR70 there are 2713 selected. After unselecting these (e.g., clicking in a map), the number of selected shows 1594, whereas it should be 0.

There also seems to be a problem when selecting the category in the Moran cluster map. For example, clicking on the low-low category (which gives 136 observations in the parentheses), selects those, but lists # selected as 1730. Also, when clicking on "not significant" (2689), it gives # selected as 4283, which is larger than the number of observations.

I first encountered this when taking a subselection from a selection, but then discovered it may be a larger problem. For example, when creating a box map, without any selections, the status bar lists #selected as 1594 (again, it should be 0). Clicking on any of the categories, e.g. upper outlier (141) selects them properly on the map, but the #selected is wrong, e.g., 1735.

**Comment by lixun910** [comment]
The fix will touch all the viz code (maps and plots).

The old design is very complex and the logic is tangled (by introducing new_selection, unselection etc.), and the fix will replace it with a simple logic.

But that need a throughout testing. Please keep an eye on this fix.

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.7.3 (OSX Yosemite, 10.10.5).

Checked all tools and couldn't find error anymore.
