### ISSUE TITLE
Update "Enable Testing Mode" logic

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#425]
change the text of the checkbox in "About GeoDa" dialog to “Stable Version and Bug Fixes Only” (default checked). GeoDa only receive updates of stable versions with even numbers (e.g. 1.8.6, 1.8.8...)

If unchecked, GeoDa will receive updates of testing versions with odd numbers (e.g. 1.8.7, 1.8.7.1 ..)

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.7.3 (OSX Yosemite, 10.10.5).

Works!
<img width="290" alt="screen shot 2016-05-20 at 9 14 37 pm" src="https://cloud.githubusercontent.com/assets/13679743/15446274/db7b6e6e-1ecf-11e6-943b-ae8ba872d2c0.png">
