### ISSUE TITLE
create time dummies when saving space-time table/weights in Time Editor

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#426]
It would be nice to create time dummies on the fly when saving the space-time table. This is already implemented in the averages tool, but it would be nice to have it in the generic tool as well. It saves the effort of having to do it explicitly later in a table select and create dummy operation, that would have to be repeated for each time dummy. For example, using natregimes, the dummy variables could be T_60, T_70, T_80 and T_90 - use the same value after T_ as used in the "TIME" variable. The dummy = 1 for the year in question, 0 otherwise. This would make it then very easy to do a simple fixed effects space-time regression in GeoDa (with spatial weights).

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.7.3 (OSX Yosemite, 10.10.5).

Works: Dummies are created with correct # of obs in each time period.

<img width="750" alt="screen shot 2016-05-20 at 9 18 38 pm" src="https://cloud.githubusercontent.com/assets/13679743/15446287/73975e24-1ed0-11e6-9163-f2ee336f4ca2.png">
