### ISSUE TITLE
Averages Chart Crashes

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#429]
Verified in GeoDa 1.8.6 (OSX Yosemite, 10.10.5 

Steps:
I had this setup (DIFF_VALUE was a variable I just created that wasn't saved yet):

<img width="724" alt="screen shot 2016-05-18 at 7 06 32 pm" src="https://cloud.githubusercontent.com/assets/13679743/15380473/b32cefa0-1d2b-11e6-909f-4f1707c1a462.png">

and tried to save the dummy when the program crashed:

<img width="421" alt="screen shot 2016-05-18 at 7 04 45 pm" src="https://cloud.githubusercontent.com/assets/13679743/15380450/741b79a8-1d2b-11e6-8b6d-048553f96a45.png">

(logger.txt wasn't updated since April, so I'm not attaching it)

**Comment by lixun910** [comment]
Can you specify the detailed steps? Can't reproduce on my side yet. Thanks!

**Comment by jkoschinsky** [comment]
I had problems replicating it, too, but will try again.

On 20 May 2016 at 11:58, Xun Li <notifications@github.com> wrote:

> Can you specify the detailed steps? Can't reproduce on my side yet. Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoDaCenter/geoda/issues/429#issuecomment-220690569>
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by lixun910** [comment]
This is actually a bug related to the "Save" function. This is critical, and the fix will be delivered in  1.8.8 soon.

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.7.3 (OSX Yosemite, 10.10.5).
