### ISSUE TITLE
shift-click selection doesn't work for sorted values in table

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#431]
Steps:

1. Select 1st row, then select xth row below
= expected behavior: 1-x is selected:

<img width="752" alt="screen shot 2016-05-20 at 9 24 17 pm" src="https://cloud.githubusercontent.com/assets/13679743/15446311/787b2d70-1ed1-11e6-921d-ed519f119ccd.png">

2. Now sort a column's values and repeat 1
you get this result, which isn't expected:

<img width="749" alt="screen shot 2016-05-20 at 9 24 31 pm" src="https://cloud.githubusercontent.com/assets/13679743/15446312/805c07c6-1ed1-11e6-9aec-135998f9ba70.png">

**Comment by lixun910** [comment]
Please verify it at 1.8.7.5

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.7.5 OSX and Win7.

works now
