### ISSUE TITLE
libssl0.9.8 in ubuntu

### ISSUE THREAD

**Issue by lincolnfrias** [GeoDaCenter/geoda#434]
Installation fails on Ubuntu 16.04 because it is not possible to install libssl0.9.8. How can I solve this?

**Comment by lixun910** [comment]
I have a temporary build for Ubuntu 16.04 (version 1.8.7.5), let me know if this works https://geodacenter.org/downloads/unprotected/GeoDa-1.8.7.5-Ubuntu16.04-64bit.deb

If you are interested, you can try to compile and build GeoDa on Ubuntu from source code:
Please  follow the instruction at https://github.com/GeoDaCenter/geoda/blob/master/BuildTools/ubuntu/readme.txt

Or, you can contribute to GeoDa's build scripts in Travis system.

**Comment by lixun910** [comment]
https://github.com/GeoDaCenter/geoda/blob/master/BuildTools/ubuntu/readme.md

https://github.com/GeoDaCenter/geoda/blob/master/.travis.yml

**Comment by lixun910** [comment]
@lincolnfrias any updates?

**Comment by lincolnfrias** [comment]
Yes, version 1.8.7.5 worked. I just needed to install libwebkitgtk and do a sudo apt-get -f install.
Thank you a lot, @lixun910,  and sorry for the delay.
