### ISSUE TITLE
Drag&Drop doesn't work on Windows after auto-upgrade feature

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#436]
Auto-upgrade on windows required the GeoDa program to be run as Administrator, so that DragNDrop doesn't work. See:https://social.technet.microsoft.com/Forums/windows/en-US/cba0e9b1-25f8-40e5-a888-1435d604f68d/run-as-administrator-prevents-drag-and-drop-working?forum=w7itprosecurity

this is how the UAC works. Drag- and Drop are messages. And sending messages from a program with normal rights, to an application with admin rights can cause security issue.
Do Drag & Drop only work with application with the same rights (program with Admin rights to program with admin rights or program with normal rights to program with normal rights ).

This fix can be downgrade the GeoDa role to normal users (instead of Administrator), but need to verify the auto-upgrade feature is still working.

**Comment by lixun910** [comment]
Note: to verify this issue, you have to download and install windows binaries of 1.8.7.9 (remember to uninstall the old version GeoDa)

**Comment by lixun910** [comment]
32 windows: https://www.dropbox.com/s/5m4t5tcenp635tp/GeoDa-1.8.7.9-Windows-32bit.exe?dl=0
64 windows: https://www.dropbox.com/s/p8m9l6thk21zuzc/GeoDa-1.8.7.9-Windows-64bit.exe?dl=0

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.7.9  (Win 7 Professional (64-bit)).
Drag and drop when opening file (e.g. gda) works now.
