### ISSUE TITLE
Make y-axis labels of weights histogram integers

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#439]
GeoDa 1.8.7.5.

Right now the values of the y-axis of the weights histogram are real instead of integers, which makes it hard to identify the number of neighbors, which can only be integers. Let's change this to integers for readability.

![screen shot 2016-05-25 at 1 49 28 pm](https://cloud.githubusercontent.com/assets/13679743/15555901/c07f29ee-227f-11e6-8e2d-1fa93f5979b5.png)

**Comment by lixun910** [comment]
The number of neighbors are numbers on x-axis?
You want to frequency counts to be integer, right?

**Comment by jkoschinsky** [comment]
yes, exactly, I meant the frequency count on y

On 25 May 2016 at 14:16, Xun Li <notifications@github.com> wrote:

> The number of neighbors are numbers on x-axis?
> You want to frequency counts to be integer, right?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoDaCenter/geoda/issues/439#issuecomment-221710071>
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.7.9 (OSX Yosemite, 10.10.5).
Fixed.

![screen shot 2016-05-31 at 11 25 40 am](https://cloud.githubusercontent.com/assets/13679743/15685825/5a28002e-2722-11e6-81ab-075ffc38da2c.png)
