### ISSUE TITLE
Rename time variable in DID regression output

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#440]
Right now, because we only name the time variable TIME_PERIOD, you can't tell which time period is 0 and 1. Instead of TIME_PERIOD, could you use the variable name from the space-time table where the time dummy = 1, e.g. T_2010?

![screen shot 2016-05-25 at 1 54 49 pm](https://cloud.githubusercontent.com/assets/13679743/15556008/640ff052-2280-11e6-9b9f-c8fe9f72022d.png)

**Comment by lixun910** [comment]
In DID, the two time periods are stacked. 

So, that's why we use "TIME_PERIOD", and can't pick just one time variable name.

 Am I right?

**Comment by lanselin** [comment]
yes, they are stacked, but somehow there has to be intelligence there that knows which time period it is. for example, with the table export function it would have to know which time period to pick. alternatively, we can call it TIME_2, which is always later than whatever the base time is.

**Comment by jkoschinsky** [comment]
Users currently set Period 1 and Period 2 in the averages tool interface
based on the drop-down options that correspond to the labels set in the
space-time table.
Period 1 = 0 and Period 2 = 1. We do have that logic in there now but if
someone specifies a later time as Period 1 and the earlier one as Period 2,
then there's no way to trace this right now.

On 25 May 2016 at 14:55, Luc Anselin <notifications@github.com> wrote:

> yes, they are stacked, but somehow there has to be intelligence there that
> knows which time period it is. for example, with the table export function
> it would have to know which time period to pick. alternatively, we can call
> it TIME_2, which is always later than whatever the base time is.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoDaCenter/geoda/issues/440#issuecomment-221719833>
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by lanselin** [comment]
I think the interface should not allow period 1 to be "after" period 2. that doesn't make sense.

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.7.9 (OSX Yosemite, 10.10.5).

The time label in the regression works great now. 

The T2 > T1 mostly works but there are some instances when you can get T2 before T1, e.g.

1. Select new time grouped variable
2. Group 1 and 2 unselected
3. T1 = 2010, T2 = 1990:

![screen shot 2016-05-31 at 11 15 52 am](https://cloud.githubusercontent.com/assets/13679743/15685615/61a01fea-2721-11e6-91a8-5ba157d284d1.png)

If this is easy to fix, let's do it. Otherwise, since the regression label then updates to T2010_1990, people at least know now what the order is.

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.8
