### ISSUE TITLE
spatial correlogram - variable value error

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#443]
when the spatial correlogram is selected, it is computed right away for the first variable in the variable list, even though such variables are typically ID variables and thus meaningless for analysis. moreover, this can generate an error message "trap", where the "variable value error" (see below) keeps popping up. it would be better to not compute the correlogram until after a variable has been selected *explicitly* similar to the approach for other graphs.

<img width="421" alt="screen shot 2016-06-03 at 5 19 44 pm" src="https://cloud.githubusercontent.com/assets/4008351/15793119/d67bc626-29af-11e6-83a0-a13bb1c97430.png">

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.8.
