### ISSUE TITLE
Average Chart crashes when table is empty

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#444]
use the WFS example (it was empty before 1.8.7.9).
After 1.8.7.9, WFS table has no numeric columns, this dataset also crashes Average Chart

**Comment by lixun910** [comment]
Same crashes of Correlogram.

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.8 (OSX Yosemite, 10.10.5).
No selection possible since there are no numeric data in the table but also no crash.
