### ISSUE TITLE
Is there a way to select secondary key in merging CSV?

### ISSUE THREAD

**Issue by Mandelag** [GeoDaCenter/geoda#446]
Greetings,

Firstly I want to ask, Is it appropriate to ask for new features here? (because i can't find it elsewhere) 

I have a .csv table that I wish to merge with existing spatial data but, it contains duplicate in it. Is it possible to select a(n optional) secondary field for both the 'current table key' and 'import table key'?
eg. 

_Shapefile_
Geom  | City  |  Province
            |    X   |      Y
            |    X   |      Z

_CSV file_
City | Province   | Population
 X    |      Y         |    10000000
 X    |      Z         |    500000

this would be "City" for the primary key, and "Province" for the secondary key, if "City" contains duplicate.

Thanks in advance!

**Comment by lixun910** [comment]
Hi Mandelag,

Thanks for your email! Please post questions or suggestions in Openspace List: https://groups.google.com/forum/#!forum/openspace-list  GeoDa Github issues are only for bug reports and tracking the development of new features.

For your question, GeoDa doesn't have this feature for now. I think maybe you can try some softwares (e.g. excel) to create a new key field from some existing fields, before you use GeoDa to merge tables.

Thanks!

Xun
