### ISSUE TITLE
table: issue with exporting excel files with duplicate column names

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#447]
there seems to be a problem in the edge case where an excel file contains duplicate column names. the file loads properly into GeoDa and the duplicate headers are only shown once. however, when trying to "save as" some other format (e.g., dbf or csv), there is an error pertaining to empty field names. when the duplicate names are removed from the original excel file, everything works fine. so, somehow the handling of the duplicate header is not robust.

<img width="421" alt="screen shot 2016-06-21 at 1 56 05 pm" src="https://cloud.githubusercontent.com/assets/4008351/16242633/0136b260-37b9-11e6-9f24-54333d050114.png">

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.9.1 (OSX Yosemite, 10.10.5).
works now: when saving as xls to dbf with duplicate field name, unique field name is added (e.g. _1), which then saves correctly:

<img width="420" alt="screen shot 2016-07-08 at 10 33 28 pm" src="https://cloud.githubusercontent.com/assets/13679743/16705846/9ac19e8a-455c-11e6-8087-67ea7ab0d216.png">
