### ISSUE TITLE
Problems to export the map using the "Copy Image to Clipboard" "Save Image As"

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#448]
found problems to export the image using the "Copy Image to Clipboard" option or when saving the map as an image file. When import or to paste the image into a word document, get a totally black square. The same happens when open the PNG or BMP file.

**Comment by lixun910** [comment]
About this fix:

On windows, since wxwidgets has an issue to save image with transparency to
png/bmp file (especially when basemap is overlayed). However, save to clipboard works
fine.

On Max osx, both save to image file and clipboard work fine.

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.9.1 (OSX Yosemite, 10.10.5).
save as png and bmp and copy to clipboard work fine on Mac OSX.

On Windows, is there a way to de-activate the save image as option, so people don't try it when it's not working? That way they'll only use the clipboard option.

**Comment by lixun910** [comment]
I would leave it there since save to file works without basemap.

**Comment by jkoschinsky** [comment]
ok, sounds good

**Comment by jkoschinsky** [comment]
I just tried the save image as with NCOVR data on Win 10 surface and got this image (in GeoDa, I had selected CartoDBLight as basemap but no dark background).

![natmapframe](https://cloud.githubusercontent.com/assets/13679743/16824677/fd206fe2-496d-11e6-88cb-329e0d07a2c2.png)

**Comment by lixun910** [comment]
Yes, see the comment above

On windows, since wxwidgets has an issue to save image with transparency to
png/bmp file (especially when basemap is overlayed). However, save to clipboard works
fine.

**Comment by jkoschinsky** [comment]
ok, I see, closing again ;)

**Comment by lixun910** [comment]
would be nice to find a way to tell windows user: there is a problem of saving map with basemap, and suggest them using screenshot or "save to clipboard".

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.5 — Mac OSX
Confirmed fix: copy image to clipboard saves map with basemap.
