### ISSUE TITLE
add support to GeoPackage format.

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#450]
GeoPackage is an open Format for Geospatial Information supported by OGC. 
GDAL has a plugin for GeoPackage vector data: 
http://www.gdal.org/drv_geopackage.html
http://www.gdal.org/ogr_formats.html

**Comment by jkoschinsky** [comment]
Tested in GeoDa1.8.9.3 on Win 10 surface.
Saved shp as geopackage and read it back in, which worked fine.
