### ISSUE TITLE
GeoDa 7/14/2016 subversion 1.8.10 - Weights creation error

### ISSUE THREAD

**Issue by flaviove** [GeoDaCenter/geoda#454]
GeoDa 7/14/2016 subversion 1.8.10 on Windows 10.
After upgrade to 7/14/2016 subversion 1.8.10.- I´m not be able to create "Weights". Back to GeoDa 1.6.7 9 march 15 everything works fine.
Any help will be great.
Thank you in advance.
Flávio Veras

**Comment by jkoschinsky** [comment]
Thanks for logging this. We're looking into this for a fix asap.

**Comment by lixun910** [comment]
@flaviove Can you provide more details? like what configuration did you use when "create weights". If you can share the data, we can replicate the exact case (my email lixun910 at gmail.com)?. we'll look into this and make sure it's fixed. Thanks!

**Comment by flaviove** [comment]
Hi Xun

Thank you for the fast replay.
Attached to it I am sendind the files I used.
"Weight File ID Variable -> CD_GEOCMU"
[Estudo GeoDa - PARANA.zip](https://github.com/GeoDaCenter/geoda/files/369540/Estudo.GeoDa.-.PARANA.zip)
Thanks

**Comment by lixun910** [comment]
@flaviove  Thanks for sharing your data. I just tried on my side in windows 7 with GeoDa 1.8.10 (contiguity weights/distance weights -- default threshold distance and 4 k-nn). All works fine. Can you tell me your specification? and does GeoDa crash?

**Comment by flaviove** [comment]
I am using windows 10
Attached a printscreen that can ilustrate what is happening.

2016-07-18 13:25 GMT-03:00 Xun Li <notifications@github.com>:

**Comment by lixun910** [comment]
@flaviove Thanks! can't see the print screen. can you attach again? Can you also attach a screenshot of the "weights creation" dialog ?

**Comment by flaviove** [comment]
Hi Xun
Sorry for the delay.
I am using Windows 10 64bits.
I am sending some pictures to show you  whats happened.
I used GeoDa vertions 1.6.7, 1.8.8 and 1.8.10.
Using 1.6.7 evething is up and running, but as you can see on the pictures  using versions 1.8.8 and 1.8.10 we got a error.
Cheers
![screenhunter_46 jul 18 21 49](https://cloud.githubusercontent.com/assets/3142178/16934982/e5c48dd4-4d31-11e6-857b-cb96da36ce96.jpg)
![screenhunter_45 jul 18 21 49](https://cloud.githubusercontent.com/assets/3142178/16934983/e5da3d50-4d31-11e6-9025-590f26057e60.jpg)
![screenhunter_44 jul 18 21 48](https://cloud.githubusercontent.com/assets/3142178/16934985/e600d3e8-4d31-11e6-8b9b-d8de22fddffc.jpg)
![screenhunter_43 jul 18 21 48](https://cloud.githubusercontent.com/assets/3142178/16934984/e5f25e1c-4d31-11e6-8e06-c9a94e892090.jpg)
![screenhunter_42 jul 18 21 47](https://cloud.githubusercontent.com/assets/3142178/16934987/e613c548-4d31-11e6-87e4-99fb478913c5.jpg)
![screenhunter_41 jul 18 21 47](https://cloud.githubusercontent.com/assets/3142178/16934990/e6165150-4d31-11e6-98fa-8c2269fbada7.jpg)
![screenhunter_40 jul 18 21 47](https://cloud.githubusercontent.com/assets/3142178/16934988/e613c50c-4d31-11e6-8682-b38bb3298d79.jpg)
![screenhunter_39 jul 18 21 47](https://cloud.githubusercontent.com/assets/3142178/16934989/e614725e-4d31-11e6-9478-0a5689454397.jpg)
![screenhunter_38 jul 18 21 45](https://cloud.githubusercontent.com/assets/3142178/16934986/e6089ef2-4d31-11e6-8191-52983e2bb3f1.jpg)
![screenhunter_37 jul 18 21 45](https://cloud.githubusercontent.com/assets/3142178/16934991/e617fb36-4d31-11e6-8bf6-d7e0fda69ced.jpg)
![screenhunter_36 jul 18 21 45](https://cloud.githubusercontent.com/assets/3142178/16934992/e6216e46-4d31-11e6-9ba8-27bc060689ef.jpg)
![screenhunter_35 jul 18 21 45](https://cloud.githubusercontent.com/assets/3142178/16934994/e62a3f44-4d31-11e6-93b9-d6cefc525015.jpg)
![screenhunter_35 jun 30 10 32](https://cloud.githubusercontent.com/assets/3142178/16934993/e629efe4-4d31-11e6-9f57-b1ff89b98e0d.jpg)

**Comment by lixun910** [comment]
@flaviove 

my best bet is some permission issues came with 1.8.6 GeoDa windows installer. Can you do me a favor to uninstall GeoDa completely (please also manually delete the GeoDa folder at C:\Program Files\GeoDa Software)? then re-install GeoDa 1.8.10 to see if errors can be fixed. 

Thanks for your help!

**Comment by jkoschinsky** [comment]
@flaviove

I just tried to replicate the problem in Win 10 with your data but can
successfully create the rook and queens weights (see images below). I
noticed that it looks like the file path for 1.8.10 is owncloud while 1.8.6
might be local? This could be another thing to test - if you try the same
local folder for 1.8.10 that you're using for 1.8.6 to see if there's a bug
with the path?

thanks for testing this!
Julia

[image: Inline images 1]

[image: Inline images 2]

**Comment by flaviove** [comment]
Hi Xun and Jkoschinsky

BINGO!!!!!!
Here is what I did.
Following what both of you commented.
1. Uninstall GeoDa and erase the C:\Program Files\GeoDa folder
2. Reinstall GeoDa 1.8.10
3. Copy the data to a local outside ownCloud folder
4. Retry create  queens weights ....
5. Bingo!!!! Everything is up and running
Obs. Using GeoDa 1.6.7 we can create weights without copy datas for a local folder.
Thank you so muth for your help Xun and Jkoschinsky
Cheers
![screenhunter_81 jul 19 08 12](https://cloud.githubusercontent.com/assets/3142178/16948075/fc13c9ea-4d88-11e6-92bb-fd8a10dd9cbf.jpg)
![screenhunter_82 jul 19 08 13](https://cloud.githubusercontent.com/assets/3142178/16948082/033d51f0-4d89-11e6-9ddb-ae671f41cbd4.jpg)

**Comment by lixun910** [comment]
@flaviove 

Great! Glad it works for you.

For targeting the problem and finding the solution, can you help us to try one more thing? -- can you use GeoDa 1.6.7 to create weights again, and when you choose save path for weight file, can you specify a owncloud path (because by default GeoDa 1.6.7 choose different path than the opened shapefile)

Thank you!

**Comment by flaviove** [comment]
Hi Xun

Doesn´t matter if the files are inside or outside the ownCloud folder, with GeoDa 1.6.7, I am always capable to create Weight files inside or outside the ownCloud folder or anywere.
If you need something else please tell me. It will be a pleasure.
Cheers

![screenhunter_82 jul 20 08 04](https://cloud.githubusercontent.com/assets/3142178/16984787/a732a17e-4e52-11e6-9dff-e2fe518f1cf1.jpg)
![screenhunter_83 jul 20 08 07](https://cloud.githubusercontent.com/assets/3142178/16984811/bf1b7a7c-4e52-11e6-8aec-d5a8da9a3c4c.jpg)
![screenhunter_84 jul 20 08 07](https://cloud.githubusercontent.com/assets/3142178/16984815/c36c054c-4e52-11e6-8db8-b4bdef98a627.jpg)
![screenhunter_85 jul 20 08 08](https://cloud.githubusercontent.com/assets/3142178/16984818/c7b169da-4e52-11e6-8eab-a76b96039393.jpg)

**Comment by lixun910** [comment]
@flaviove Thank you very much!  I've installed and tested ownCloud on my side, but still can't replicate the error of weights creation with ownCloud. Can you help us do one more test:  can you use GeoDa 1.8.10 to create and save weights file to the directory that GeoDa 1.6.7 was successfully saved to?

In this case, we can rule out if it's ownCloud or GeoDa (since the weights creating code has not been changed)

**Comment by flaviove** [comment]
That is wierd. I did what you tell me to do and no success. On top of that I try to run GeoDa as a admin and got the same error.
I tested using my home computer and did the same test using my computer from work place.
![screenhunter_86 jul 26 08 33](https://cloud.githubusercontent.com/assets/3142178/17137098/b14e010a-530f-11e6-94e4-4869ab86125c.jpg)
![screenhunter_88 jul 26 08 34](https://cloud.githubusercontent.com/assets/3142178/17137117/ca025cb4-530f-11e6-9ac8-9274cae2d35d.jpg)
![screenhunter_90 jul 26 08 35](https://cloud.githubusercontent.com/assets/3142178/17137109/bf933a14-530f-11e6-897f-7d7c744ac425.jpg)
![screenhunter_91 jul 26 08 36](https://cloud.githubusercontent.com/assets/3142178/17137125/d4351726-530f-11e6-8f4b-e4eeeab70df0.jpg)

**Running as an Admin**

![screenhunter_92 jul 26 08 49](https://cloud.githubusercontent.com/assets/3142178/17137137/e6ebd800-530f-11e6-8d6f-f73ecd57cdeb.jpg)

**Comment by lixun910** [comment]
New GeoDa installer will check and uninstall existing GeoDa software. Also try to get proper permission to allow GeoDa write files on disk.
