### ISSUE TITLE
Table - edit properties

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#455]
GeoDa version 1.8.10
Table edit properties conversion from string to integer does not work when missing values are present. For example, in a census data file with PLACE as the ID for a place, there are several missing values. Converting the ID string to an integer fails. After the observations with missing values are removed, it works.

**Comment by lixun910** [comment]
When there is a missing value or an empty string, a message dialog will be prompted to user.

The block question is: what integer value should a "missing value" of string convert to?  Using Gdal can't save a null.

**Comment by jkoschinsky** [comment]
Luc, GDAL converts undefined values to zeros, so your missing values would become zeros: Would that be ok?

Can you send us the file with missing values?

**Comment by jkoschinsky** [comment]
GeoDa 1.8.13.5, OSX
Problem remains for both .dbf and .xls:

Steps:
1. Load either of the test files below with string field (numbers) to be converted to integer (as in FIPS code use case)
2. Go to Edit Variable Properties and try to change from string to integer
3. In both cases, this error is generated:

<img width="746" alt="screen shot 2016-09-15 at 10 20 58 am" src="https://cloud.githubusercontent.com/assets/13679743/18555753/9bac2c9a-7b2e-11e6-99e1-4a7360ecaa5e.png">

[Archive.zip](https://github.com/GeoDaCenter/geoda/files/474989/Archive.zip)

**Comment by lixun910** [comment]
Can you attached the data?

**Comment by jkoschinsky** [comment]
was enclosed below image in previous comment, here's a copy:
[Archive.zip](https://github.com/GeoDaCenter/geoda/files/666396/Archive.zip)

**Comment by lixun910** [comment]
geode supports undefined now, but if values are not valid, a dialog
will be popup to show the details :
<img width="422" alt="screen shot 2017-01-08 at 9 38 10 pm" src="https://cloud.githubusercontent.com/assets/2423887/21756743/cdd0b85a-d5ea-11e6-8009-a639e9d172c1.png">

**Comment by jkoschinsky** [comment]
update text from:
Change variable type for "test4" has failed.
Details: GeoDa can't convert '4564..' to numeric..

to:
GeoDa was unable to change the variable type for "test4".
Details: GeoDa can't convert '4564..' to numeric format.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.9 — Mac OSX
Problem remains when you try to convert string to numeric:

<img width="422" alt="screen shot 2017-01-13 at 5 33 32 am" src="https://cloud.githubusercontent.com/assets/13679743/21928787/6926f19c-d952-11e6-9d6f-30533ec2f1c7.png">

Change to:
GeoDa is unable to change the variable type for "test4", e.g. because it is a string (text) format without numeric values

.

**Comment by lixun910** [comment]
Update fix: when a value can't be convert, a undefined value (empty cell) will be used -- so that no warning message will be raised.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.13 — Mac OSX
Confirmed fix: geoid with undefined values converted from string to integer.

<img width="284" alt="screen shot 2017-01-23 at 8 32 50 pm" src="https://cloud.githubusercontent.com/assets/13679743/22231798/3381f5d0-e1ab-11e6-9f57-49e9118e78df.png">
