### ISSUE TITLE
Table merging with mismatches

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#458]
from Luc - this comes up with lots of users who email me as well:

Use case: Need to extract rows from a larger file that match the census tract IDs for 
Chicago. So, I start with the Chicago file, then open merge on the AREAKEY,
but it doesn’t work. I get a key mismatch error.

What we need: is that any key match between the origin and the destination gets added to the origin, so that the keys in the origin are not changed. If there is no match, missing values are added.

**Comment by jkoschinsky** [comment]
Just confirmed with Luc: Cases to include are the ones where e.g. US table is joined to IL county shapefile (non-IL records in table skipped) or, vice versa, IL table joined to US counties (non-IL counties populated as zero).

What we don't need to do is add new geometry when US table is joined to IL county shapefile (for the non-IL counties). GeoDa won't deal with that case (flag: not possible). This way we only address the matches where the record # of the spatial files stays fixed.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.13.1, OSX

Not working yet.

Steps:
1. Save subset of shapefile A as new shapefile B
2. Then try to merge dbf from complete shapefile A to subsetted shapefile B instead of matching the subset

This generates the following error:
<img width="1010" alt="screen shot 2016-09-14 at 9 23 06 am" src="https://cloud.githubusercontent.com/assets/13679743/18516092/4ab85826-7a5d-11e6-8133-b52bb537b042.png">

when subset shapefile is merged with subset dbf (exact match) it works.
Will email the same data separately.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.13.3, OSX

Verified join of larger file to subset and vice versa: Both worked.

Two issues: In my test case, the original variable had 7 decimal places but after merging only 4 were displayed. Can you change this to whatever the original was? (could be changed through edit properties but it's an extra step and not everyone will know how to do this)

The other issue is that in the case where a subset of records is merged to a larger number of records, it's impossible to tell apart real zeros from missing data zeros. How hard would it be to add a dummy that indicates which records were missing in the merged table, e.g. NoData (with 1 for missing and zero for merged)?

**Comment by lanselin** [comment]
I think we need an actual missing value code, rather than the arbitrary 0 (which is terrible) or something like -999. Not sure if wxWidgets supports this.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.13.5, OSX

still just zeros for missing values:

<img width="1102" alt="screen shot 2016-09-15 at 10 47 01 am" src="https://cloud.githubusercontent.com/assets/13679743/18556701/ce075e64-7b31-11e6-81d3-40b6c381e0ae.png">

**Comment by lixun910** [comment]
Not fix yet, as mentioned last night, need some days to have a intuitive solution by manipulate OGR/GDAL.

**Comment by lixun910** [comment]
merge with csv file (has empty content) still use zeros not undefined

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.5 — Mac OSX
Confirmed fix - undefined values set e.g. for non-IL states when IL data is merged with US shapefile.
