### ISSUE TITLE
Problem with reading in csv: float converted to integer

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#459]
When I read in a csv file (will email to Xun), columns that have float values and zeros (e.g. 2.3456 and 0) are converted to integers (rounded to the closest one) when you open them in GeoDa. Default should be format that preserves the decimals.

<img width="1097" alt="screen shot 2016-08-19 at 11 48 48 am" src="https://cloud.githubusercontent.com/assets/13679743/17817572/c72315bc-6604-11e6-967e-6d7fca731cbd.png">

**Comment by lixun910** [comment]
This is cause by detecting field type using the first row data. 

It has been an issue for a long time, we should have a solution now. One I like is what MS excel does: prompt a dialog to allow user to specify the field type when open a CSV file.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.13.1, OSX

I like the interface and it's clear what to do but the preview below doesn't seem to update when you change the type above. E.g. here there's a mismatch between the type choice above and the preview below:

<img width="580" alt="screen shot 2016-09-14 at 8 43 41 am" src="https://cloud.githubusercontent.com/assets/13679743/18514523/822173d4-7a57-11e6-861a-4dd74c57db75.png">

**Comment by jkoschinsky** [comment]
GeoDa 1.8.13.5, OSX

Verified - works:
<img width="578" alt="screen shot 2016-09-15 at 10 28 46 am" src="https://cloud.githubusercontent.com/assets/13679743/18555960/6653a360-7b2f-11e6-98f9-346eec5ea1ad.png">

Small language update:

Dialog header:
GeoDa Csv Filed Configuration Dialog --> GeoDa .csv File Configuration Dialog

Please Specify Data Type for Each Data Column --> If needed, click on a variable's data type to change it:

**Comment by jkoschinsky** [comment]
See [this issue ](https://github.com/GeoDaCenter/geoda/issues/532)

**Comment by stevencollinscn** [comment]
I encountered this issue on Wins and wonder why it is not checked by default since you can no longer change data type after merging. lol...
![snap2](https://user-images.githubusercontent.com/33796896/37870710-2c6389c8-2faa-11e8-971d-7c21ecb7d04a.jpg)
