### ISSUE TITLE
Problems with shp-> geojson conversion

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#460]
from Marynia: 

Testing geojsons: http://geojson.io/

I'll get the error "not well formed" no matter what, though the shp-> geojson conversion in GeoDa (and the ogr converter online) would not give a geojson that appears, at all. Issues with the geojson forming incorrectly were also confirmed with a programmer in Ross's lab. 

It finally converted correctly using FME. It also converted correctly in-application using this: https://github.com/calvinmetcalf/shapefile-js  (and no "not well formed" error when done that way.

[ChiHealth.zip](https://github.com/GeoDaCenter/geoda/files/427497/ChiHealth.zip)
[Boundaries - City (1).zip](https://github.com/GeoDaCenter/geoda/files/427498/Boundaries.-.City.1.zip)

**Comment by lixun910** [comment]
Update:

The ChiHeahlth shapefile has a projection EPSG: 4269 NAD83. When GeoDa saves it, the related projection has been ignored {csr : value}. However, even added the projection meta data in exported geojson file, the website http://geojson.io/ can't transform it to WGS84 properly. See the points on the map

<img width="498" alt="screen shot 2016-08-29 at 4 19 13 pm" src="https://cloud.githubusercontent.com/assets/2423887/18067926/996567e4-6e04-11e6-85d0-321f42265602.png">

From a post: "In the latest standard GeoJSON is defined to always be in WGS84", so one way to fix it is convert data with any other projections to WGS84 when export to GeoJSON.

Let me know if you want do this.

Also there is a potential feature of GeoDa is "allow user specify which projection  when saveas"

**Comment by jkoschinsky** [comment]
From Marynia:

I believe the same error occurred in QGIS last week, and only my FME workflow conversion worked... But that makes sense why, as FME forces a metadata standard if there is any missing.

**Comment by lixun910** [comment]
OK, just verified that such GeoJson with non-WGS84 projection also can't be loaded by CartoDB.

So, I just added a solution that "when export to GeoJson, GeoDa will automatically using WGS84 (if not, will automatically convert to WGS84)".

**Comment by jkoschinsky** [comment]
verified:

<img width="1580" alt="screen shot 2016-09-14 at 8 53 39 am" src="https://cloud.githubusercontent.com/assets/13679743/18514857/c8b39998-7a58-11e6-9b68-be614e011474.png">
