### ISSUE TITLE
project file default for first order contiguity weights

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#463]
The project file gives <inc_lower_orders> as true for first order rook and queen weights. While in and of itself this is harmless, it really should be set to false, since there is no inclusion of lower order for first order.

**Comment by jkoschinsky** [comment]
fixed:

<img width="342" alt="screen shot 2016-08-31 at 12 42 51 pm" src="https://cloud.githubusercontent.com/assets/13679743/18139788/7c504bae-6f78-11e6-9ede-1c122265f1b6.png">
