### ISSUE TITLE
distance units in Weights Manager properties

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#464]
The distance units given in the Weights Manager seem to be incorrect. In my example for points in Cleveland, given in State Plane coordinates, the critical cut-off distance is given as 3598 miles, which doesn't make sense. It should be in feet, or roughly 0.7 miles. Maybe the contents of the prj file are not read correctly.

[clev_stateplane_projection.txt](https://github.com/GeoDaCenter/geoda/files/439614/clev_stateplane_projection.txt)

<img width="310" alt="clev_d_weightmanager" src="https://cloud.githubusercontent.com/assets/4008351/18011375/e7f93c98-6b82-11e6-8f1d-91c0eb01eb35.png">

**Comment by lixun910** [comment]
Projection file has not been used in weights creation yet. Will check to add this feature.

**Comment by jkoschinsky** [comment]
fixed:
<img width="634" alt="screen shot 2016-08-31 at 2 39 50 pm" src="https://cloud.githubusercontent.com/assets/13679743/18144706/8e5f3a16-6f8d-11e6-9f30-f82bb066d9cd.png">

GeoDa 1.8.11.1 (08-29) on left — previous version on the right
