### ISSUE TITLE
Weights creation bug with X and Y centroids selection v.s. LAT/LON fields selection

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#466]
Luc reported: When create a distance based weights, a comparison of the critical distance
based on X and Y centroids (the Lon and Lat I used to create the
point layer) and one explicitly specifying LON and LAT.
they should be the same, but they are not.

**Comment by jkoschinsky** [comment]
now identical:

<img width="1094" alt="screen shot 2016-08-31 at 12 48 27 pm" src="https://cloud.githubusercontent.com/assets/13679743/18139987/403b87c2-6f79-11e6-8653-1739dd81ae43.png">
