### ISSUE TITLE
1.8.10 ubuntu version crashed: segmentation fault

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#469]
From: Duruz Solange

We would like to inform you of a possible bug of the ubuntu installer/version of GeoDa:

I was trying to install GeoDa on ubuntu (ubuntu 16.04, 64 bit) and followed the indication on http://geodacenter.github.io/download_linux.html
The installation worked without errors, and I am able open GeoDa without problem, but when I try to upload shapefiles, most of the files make GeoDa crash (everything disappears all of a sudden).  It seems to be inherent to the ubuntu version because when I try on windows with the same files, I have no problem.

I also tried to open geoda from the command line to see error message:
Here is the output of the terminal when I open GeoDa

$ run_geoda.sh
chmod: cannot access '/usr/local/geoda/plugins/*.so': No such file or directory
ERROR 1: libclntsh.so.11.1: cannot open shared object file: No such file or directory
ERROR 1: libclntsh.so.11.1: cannot open shared object file: No such file or directory
ERROR 1: libpe.so: cannot open shared object file: No such file or directory
ERROR 1: libpe.so: cannot open shared object file: No such file or directory

I'm not sure of what I'm saying here, but I think that those error are not related to the crash I get when loading the shapefile.

And when I upload a shapefile, i get: Segmentation fault (Core dumped)

**Comment by jkoschinsky** [comment]
feedback from user:

Thank for this fast fix. All my tests with the version 1.8.12 on Ubuntu 16.04 64b succeeded!
Here is the output. You might be interested by the new warn/err messages ... (?).

bancal@siepc-97:~$ run_geoda.sh 
chmod: cannot access '/usr/local/geoda/plugins/*.so': No such file or directory
chmod: changing permissions of '/usr/local/geoda/GeoDa': Operation not permitted
Warning 4: Failed to open /usr/local/geoda/cache.sqlite, Permission denied.
