### ISSUE TITLE
Postgres connection doesn't parse timestamps

### ISSUE THREAD

**Issue by allthesignals** [GeoDaCenter/geoda#471]
The Postgres connector doesn’t seem to detect and parse timestamps correctly (they appear blank in the table view). 

GeoDa: 1.8.12
Postgres: 9.3

![screen shot 2016-09-02 at 2 22 30 pm](https://cloud.githubusercontent.com/assets/5004319/18213967/b79d570a-7118-11e6-9231-e1b47a4f504a.png)

**Comment by lixun910** [comment]
@allthesignals We just rolled out a beta version 1.8.13.3, which has a fix for this issue. Can you download it and verify if this issue has been fixed in 1.8.13.3? Thank you for your support!

The temporary download link for Mac OSX https://www.dropbox.com/s/q1dkw41rx4akm2y/GeoDa1.8.13.3-Installer.dmg?dl=0

**Comment by jkoschinsky** [comment]
Julie, can you confirm and, if fixed, close? thx

**Comment by jkoschinsky** [comment]
leaving open for after release so original bug reporter can confirm it works

**Comment by allthesignals** [comment]
Thank you for looking into this - I am setting up GeoDa again on my machine. AWS is having some trouble, so I can't get the new release. Sorry that I took so long, @lixun910, I can't believe that was in September. I'm excited to try this out.

**Comment by jkoschinsky** [comment]
Hi Matt, Could you send me an email to spatial@uchicago.edu? Then I'll send
you the internal version to test. thx, Julia

**Comment by allthesignals** [comment]
Hi folks, I just tried GeoDa 1.8.14 for Mac OS X, and I'm seeing Postgres dates parse correctly. Excited to use this tool for our upcoming rental listing database project. 

- Matt
