### ISSUE TITLE
significance map legend

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#474]
it would be nice if the map legend for the significance map of the various local statistics would be consistent with the number of permutations. for example, with 999 permutations, the smalles p-value that can be portrayed is 0.001 even though the map legend also includes 0.0001. it would make sense if the legend would only show significance levels that can be mapped for the given number of permutations, e.g., for 99 it would stop at 0.01, for 999 at 0.001, etc.

**Comment by jkoschinsky** [comment]
resolved: 

<img width="550" alt="screen shot 2016-09-14 at 7 50 02 am" src="https://cloud.githubusercontent.com/assets/13679743/18512713/ff770158-7a4f-11e6-930f-18a7455c51f9.png">

<img width="548" alt="screen shot 2016-09-14 at 7 50 21 am" src="https://cloud.githubusercontent.com/assets/13679743/18512718/06ff5542-7a50-11e6-952d-edf6c6cd2d55.png">

<img width="530" alt="screen shot 2016-09-14 at 7 50 35 am" src="https://cloud.githubusercontent.com/assets/13679743/18512727/0b63f2d2-7a50-11e6-86b8-07e9935eb9bb.png">
