### ISSUE TITLE
Map transparency value not updated from default

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#476]
this one's obscure but confusing:

When you change the transparency of a map layer, e.g. to 0.6, then close the transparency dialog and open it again, it shows the default value of 0.3 even though the actual (changed) value is 0.6 (see below). The value shouldn't be the default but the actual (in this case changed) transparency value.

<img width="286" alt="screen shot 2016-09-08 at 4 51 14 am" src="https://cloud.githubusercontent.com/assets/13679743/18345186/feb07d6e-757f-11e6-8785-74d50a162fea.png">

**Comment by jkoschinsky** [comment]
GeoDa 1.8.13.1, OSX
When I select "Change Map Transparency", nothing happens / no dialog appears

**Comment by lixun910** [comment]
Can you try it again? It only works with basemap.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.13.3, OSX
verified
