### ISSUE TITLE
conditional map menu item is wrong

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#480]
in the Map Menu, the item for a conditional map should be just that, not Conditional Plot Map (no plot).

**Comment by jkoschinsky** [comment]
Map menu is fixed to "Conditional Map" but tooltip still says "Conditional Plot" - let's make that Conditional Map, too, for consistency

**Comment by lanselin** [comment]
Which tooltip? The tooltip on the toolbar should remain conditional plot, since it brings up all three types (histogram, map and scatter plot). The conditional map is actually in the menu in two places, under Explore > Conditional Plot > Map and under Map > Conditional Map. I suggest we keep as is, with the generic conditional plot tooltip. Unless I am missing something about the tooltip :-)

**Comment by jkoschinsky** [comment]
sounds good, then I'll close ticket

**Comment by jkoschinsky** [comment]
resolved
