### ISSUE TITLE
Problem reading in data from kmz file

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#482]
From Luc:
It looks like when reading in data from a KMZ file, the variable name is parsed incorrectly. It looks like it is “POLY_ID” whereas it should be POLY_ID. The double quotes are not dropped. He later read in as a shape file without problems, so he is set, but I’m still wondering what is going on here.

From student:
I'm getting an error from GeoDa saying that my variable ID name is invalid. I have a unique identifying number for each polygon, but wanted to let you know that something doesn't seem to be working. I'm running the most recent version of GeoDa 1.8.12 1. I've attached a screenshot. 

My polygons are from a KMZ file, maybe that is causing a problem?

<img width="1191" alt="kmz" src="https://cloud.githubusercontent.com/assets/13679743/18619851/6c23ea30-7dcc-11e6-8eac-5b18a1519f18.png">

**Comment by jkoschinsky** [comment]
Julie, can you confirm on Windows and, if fixed, close? thx

**Comment by YidanJ-Wu** [comment]
Geoda 1.8.15.27 
Windows 8

My version actually doesn't have the option to read KMZ files. 
![geoda problem kmz](https://cloud.githubusercontent.com/assets/22801047/23236074/7b28ddde-f91d-11e6-91d1-80a341b561b0.png)


I did save some KMZ files as KML files in Google Maps though and the names are displaying correctly without quotation marks. 
![image](https://cloud.githubusercontent.com/assets/22801047/23236005/389df5bc-f91d-11e6-849f-7e2e273e41d3.png)
