### ISSUE TITLE
open recents

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#483]
could we have an item "open recent" in the File menu? this was suggested by some users.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.5 — Mac OSX
Confirmed fix with addition of recent tab (see image below).

Only small thing is that you can enlarge the size of the dialog with resizing the recent and sample data preview. If we allow for resizing of the overall view, I would also simultaneously resize the recent and sample data preview. If we can't resize the latter, I would disable resizing the overall view.

<img width="1036" alt="screen shot 2016-12-20 at 4 08 15 pm" src="https://cloud.githubusercontent.com/assets/13679743/21369874/af93d79e-c6ce-11e6-8c37-21e783002810.png">

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.9 — Mac OSX
Confirmed fix.
