### ISSUE TITLE
OneDrive file access problems

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#486]
Several users continue to report file access problems related to remotely stored files, e.g. this user with OneDrive:

![error](https://cloud.githubusercontent.com/assets/13679743/18921412/4d55e00e-856a-11e6-9d00-c794c267b2b3.png)

The error message doesn't point to the problem. Can we enable remote file access?

**Comment by lixun910** [comment]
This is an installation problem (not file access) see the last sentence on the screenshot.

**Comment by lixun910** [comment]
will check if it's path issue

**Comment by jkoschinsky** [comment]
Testing depends on fix of [this issue]([url](https://github.com/GeoDaCenter/geoda/issues/543))

**Comment by jkoschinsky** [comment]
Julie confirmed fix.
