### ISSUE TITLE
LISA hangs when using dataset with small #obs

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#488]
See the attached shapefile, which only contains 3 records.

LISA hangs and one needs to kill to close GeoDa.

[sub.zip](https://github.com/GeoDaCenter/geoda/files/499219/sub.zip)

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.5 — Mac OSX
Confirmed fix:

<img width="599" alt="screen shot 2016-12-21 at 7 37 49 am" src="https://cloud.githubusercontent.com/assets/13679743/21391238/6a5c6556-c750-11e6-8628-854f08553968.png">
