### ISSUE TITLE
csv without header will crash if comma used in text

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#489]
1.8.13.5 GeoDa

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.5 — Mac OSX
Confirmed fix:

<img width="455" alt="screen shot 2016-12-21 at 6 38 03 am" src="https://cloud.githubusercontent.com/assets/13679743/21389566/107eb960-c748-11e6-82b3-5dfacb350d50.png">
