### ISSUE TITLE
Import *.csv file with multiple separator support 

### ISSUE THREAD

**Issue by ricardobarroslourenco** [GeoDaCenter/geoda#490]
Hello!

I'm a new GeoDa user (recently taking classes on Intro to Spatial DS at UChicago), so perhaps, I could be doing a mistake. However I would like to report an issue. GeoDa assumes that CSV files come with pre-defined separators (such as commas for collumns, dots for decimals...).

However this is not mentioned on the `Connect to Data Source` menu, nor at the format [specification](http://geodacenter.github.io/formats.html).

I'm Brazilian, and in Portuguese we separate decimals with `commas` and thousands with `dots`. Also is quite common to use `semicolon` to separate values, or `TABS`. It would be nice to have full CSV support, allowing the user to select the adequate type while loading data. Otherwise it would be necessary to run a script out of GeoDa to preprocess it.

Regards,
Ricardo

**Comment by lixun910** [comment]
Thanks for reporting this! We are working on a similar issue and will support full csv import in next release.

**Comment by ricardobarroslourenco** [comment]
No problem @lixun910 . Marynia Kolak asked me to report this issue to @jkoschinsky , but I've preferred to come here directly.

Cheers,
Ricardo

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.5 — Mac OSX
Confirmed fix. See [this issue](https://github.com/GeoDaCenter/geoda/issues/520).
