### ISSUE TITLE
GeoDa displays string records with special characters as empty cells

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#491]
GeoDa 1.8.13.5

GeoDa displays string records with special characters (in this case Spanish accents) as empty cells. One of the students in Luc's class needs this.

Left (GeoDa) - Right (GIS)

<img width="794" alt="screen shot 2016-10-10 at 4 17 54 pm" src="https://cloud.githubusercontent.com/assets/13679743/19251569/94107708-8f05-11e6-993b-c16545952f0a.png">

**Comment by lixun910** [comment]
Did you Try menu -- encoding?

**Comment by jkoschinsky** [comment]
great, that works, thx.
Is there a way to auto-detect this or raise a flag at read-in to let users
know this option exists?

**Comment by lixun910** [comment]
Yes, see the following, we can keep this ticket open but change the title
to "Auto detect encoding for DBF":

The original DBF standard defines to use ISO8859-1
<http://en.wikipedia.org/wiki/ISO/IEC_8859-1>, and only ISO8859-1. So, when
you get a Shapefile that is really standards conform, it should be
ISO8859-1. Of course, this (very old) restriction is a not really usable
nowadays.

ArcGIS and Geopublisher, AtlasStyler and Geoserver started to extend the
standard to define the encoding. For ArcGIS
<http://support.esri.com/en/knowledgebase/techarticles/detail/21106>,
Geopublisher <http://en.geopublishing.org/> and AtlasStyler SLD Editor
<http://en.geopublishing.org/>, just create a .cpg file (with the same
basename as the other Shapefiles) and fill it with the name of the encoding.

e.g. create a myshape.cpg with a texteditor and insert 5 characters "UTF-8"
and save it. If you then open the Shapefile in ArcGIS or Geopublisher or
AtlasStyler, they will read the textual contents of the DBF in that charset.

Xun Li, Ph.D

Assistant Director for Data Science
Center for Spatial Data Science
University of Chicago
http://spatial.uchicago.edu

**Comment by lixun910** [comment]
can you send me the data (if it comes with the .cpg file)?

**Comment by jkoschinsky** [comment]
just emailed it

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.5 — Mac OSX
Confirmed fix:

<img width="677" alt="screen shot 2016-12-21 at 6 24 50 am" src="https://cloud.githubusercontent.com/assets/13679743/21389238/3a972ea0-c746-11e6-9324-8c9d669a4680.png">
