### ISSUE TITLE
Weights bug related to arc distance

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#493]
From Luc (Nepal data):

Creating distance weights for Nepal. Using arc distance
- set to km, the cutoff is 64.4
- set to mi, the cutoff is 40.0
but then the weights for km have 20 neighborless observations, but the ones for miles are fine:

<img width="1616" alt="screen shot 2016-10-13 at 11 27 37 am" src="https://cloud.githubusercontent.com/assets/13679743/19357627/1f223aa0-9138-11e6-9070-71336b06fe44.png">

**Comment by lixun910** [comment]
fixed in 31185fc

**Comment by jkoschinsky** [comment]
GeoDa 1.8.13.9

Problem fixed - Arc miles and km now generate identical connectivity histograms:

<img width="1518" alt="screen shot 2016-10-16 at 9 11 52 pm" src="https://cloud.githubusercontent.com/assets/13679743/19423370/5348c8bc-93e5-11e6-99ff-38886b15ab6b.png">
