### ISSUE TITLE
Idea for point-in-poly aggregation

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#494]
logging idea we discussed for the future:

one of the things we could think about is if there's a way to link the point-to-polygon aggregation (hexagon binning, grids, admin boundaries) and regionalization of areas to analytic results (like residuals, predicted values) and allow for flexible adjustments of the aggregation so people can explore how different aggregations impact the results. Like an MAUP impact detector. 

The flexible binning is similar to the category editor idea but with scale differences added and the interface could be: adjusting the scale with a slider on the map as associated analytic results views change.

**Comment by lixun910** [comment]
Point-in-polygon aggregation and other related features have been implemented since V165.
Close this ticket, and any issues or bugs should be reported in a new ticket.
