### ISSUE TITLE
updated labels for selecting undefined records

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#501]
btw, love the undefined category in the map - it's very useful.

if I selected all undefined (e.g. N = 16 in ex. below), then in non-spatial views, the toolbar text will say # selected = 16. Can we change this to # selected (undefined) = 16 for all non-spatial views since otherwise people might be looking for the selection and won't find them (see boxplot ex below where nothing is selected with # selected = 16)?

<img width="1385" alt="screen shot 2016-10-18 at 2 54 44 pm" src="https://cloud.githubusercontent.com/assets/13679743/19494035/de901b2e-9542-11e6-8665-88c60a5fc252.png">

**Comment by jkoschinsky** [comment]
actually, a better idea might be to distinguish between selected and selected (undefined). E.g. in the scatterplot example below, 16 undefined and 2 defined are selected. The stats for red (selected) indicate N = 18 but it's really 2 (defined), the rest is excluded.

<img width="1143" alt="screen shot 2016-10-18 at 4 06 18 pm" src="https://cloud.githubusercontent.com/assets/13679743/19496376/d9f2e524-954c-11e6-8a24-f73a5cd74432.png">

**Comment by lixun910** [comment]
The status bar text also needs to handle  space-time variable as well as different variables which may not have same undefined records. Let me know if this solution works.
<img width="1247" alt="screen shot 2016-10-19 at 11 28 50 am" src="https://cloud.githubusercontent.com/assets/2423887/19527848/3c9ad5e0-95ef-11e6-8870-4f35bf14b8f9.png">

**Comment by lixun910** [comment]
For scatter plot stats text deal with undefs:
<img width="1174" alt="screen shot 2016-10-19 at 12 12 39 pm" src="https://cloud.githubusercontent.com/assets/2423887/19529433/7a47cbae-95f5-11e6-9efb-180b78ab80cd.png">

**Comment by jkoschinsky** [comment]
I like this solution - thx

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.5 — Mac OSX
Confirmed fix.
