### ISSUE TITLE
Don't display undefined values in conditional scatterplot

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#503]
GeoDa 1.8.13.9, Mac OSX

In the conditional scatterplot, the 16 undefined values seem to be displayed in the upper right corner plot (stacked on top of each other). Instead they should just be excluded like in the other plots.

<img width="1621" alt="screen shot 2016-10-18 at 3 22 19 pm" src="https://cloud.githubusercontent.com/assets/13679743/19494888/bc83f9ca-9546-11e6-9b73-ec853a20bb68.png">

**Comment by lixun910** [comment]
fixed in https://github.com/lixun910/geoda/commit/0be5883ad3335d0318b2e282ad6da01026c8873e

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.5 — Mac OSX

Confirmed fix but ran into something else: When you try to change the vertical or horizontal bin breaks to 2, three are selected by default.

<img width="1037" alt="screen shot 2016-12-21 at 5 37 35 am" src="https://cloud.githubusercontent.com/assets/13679743/21387944/b52702f0-c73f-11e6-9f8b-9f2bf9fd1e49.png">

**Comment by lixun910** [comment]
Don't understand what's the issue

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.7 — Mac OSX
county and Walgreens data

Looked at this again and I see what the issue is:

When you don't have undefined values and select 2 vertical bin breaks, you get what you expect, like here:

<img width="705" alt="screen shot 2017-01-09 at 8 55 42 am" src="https://cloud.githubusercontent.com/assets/13679743/21770657/cf2c501a-d649-11e6-89f3-96161948082f.png">

However, for files with undefined values, they seem to be put in the upper right micromap (records used to be visible, now invisible), which creates an extra row and column that sets the minimum number of breaks to 3 instead of 2, like here (where I selected 2 vertical breaks):

<img width="1458" alt="screen shot 2017-01-09 at 8 57 54 am" src="https://cloud.githubusercontent.com/assets/13679743/21770689/f906e21a-d649-11e6-8767-5a07193da786.png">

One option is to exclude them instead to get the normal Conditional Plot behavior with undefined values?

**Comment by lixun910** [comment]
The extra column/row is caused by undefined values, which were placed in a special category (undefined) -- you can see this category when you create a theme map. 

The fix is to skip creating a new category for undefined values.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.13 — Mac OSX
Confirmed fix:

<img width="1399" alt="screen shot 2017-01-23 at 6 38 51 pm" src="https://cloud.githubusercontent.com/assets/13679743/22229110/3ddaa956-e19b-11e6-8b34-4d777c67d3ce.png">
