### ISSUE TITLE
LISA calc with undefs incorrect

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#504]

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.9 — Mac OSX
columbus data

Steps:
Compute LISA for HOVAL with specified seed (123456) for three maps:
1. regular 49 area shapefile (HOVAL)
2. new shapefile with 42 areas where HOVAL is defined (undefined areas are removed)
3. regular 49 area shapefile (HOVAL, which has 7 undefined values)

The results for all three are identical:
<img width="1801" alt="screen shot 2017-01-13 at 8 53 13 am" src="https://cloud.githubusercontent.com/assets/13679743/21934408/e7c66d22-d96e-11e6-9e5d-d2e176219f32.png">
<img width="603" alt="screen shot 2017-01-13 at 8 20 21 am" src="https://cloud.githubusercontent.com/assets/13679743/21934421/f79f538a-d96e-11e6-9f62-b46e0b9c4aac.png">

What is weird is that when you:
-- add a new variable TEST = HOVAL
--convert same 7 values to undefined ones (checked that the sums of TEST and HOVAL with undefined are identical)
--and run the LISA with same W and specified seed
 then the result differs:

**Comment by lixun910** [comment]
Randomization also needs to take care of undefined values for computing significance, which causes the above bug.

This fix also applies to Local G/G*.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.13 — Mac OSX
Confirmed fix:

<img width="598" alt="screen shot 2017-01-23 at 7 26 52 pm" src="https://cloud.githubusercontent.com/assets/13679743/22230216/f09c0250-e1a1-11e6-86ae-c3a539b5d5bd.png">
