### ISSUE TITLE
update add basemap warning message

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#507]
"GeoDa cannot find proper projection or geographic coordinate system information to add a basemap. Please update this information (e.g. .prj file)."

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.5 — Mac OSX
Confirmed fix:

<img width="425" alt="screen shot 2016-12-20 at 3 09 46 pm" src="https://cloud.githubusercontent.com/assets/13679743/21368072/61d054f4-c6c6-11e6-8b59-961d2fecc895.png">
