### ISSUE TITLE
merge table broken after undef feature

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#508]
Where is the bug: When merge table, the undefined values also are checked on the imported table to make sure undefs are taken care of, there is a single line buggy code marked all undef markers true and cause all values undefined and not merged to table.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.5 — Mac OSX
Confirmed fix:

<img width="515" alt="screen shot 2016-12-21 at 5 19 59 am" src="https://cloud.githubusercontent.com/assets/13679743/21387413/29c0da62-c73d-11e6-8707-612a61a75537.png">
