### ISSUE TITLE
Add menu item help->report bug

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#509]
Adjust logger file content to track user operations.

Add menu option help->Report Bug to allow user send current logger file via email client to spatial@uchicago.edu

Detect if crash had happened, then prompt (which can be disabled) user to report crash in the same dialog.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.5 — Mac OSX

Current: 
Help - Report Bug

Change to:
Help - Bug Report

I've had two recent crashes where I chose to send crash report after re-opening GeoDa but nothing happens other than opening the FileIO dialog (i.e. no report is added to github)
