### ISSUE TITLE
GeoDa hangs when default distance band includes too many neighbors

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#513]
GeoDa 1.6+

Problem:
GeoDa hangs when the default distance band, which ensures all records are connected, is so large due to remote observations, that the denser records have a lot of neighbors (in the test case several hundred).

Proposed solution:
After distance weights are specified and the user selects "create", a flag is raised if an observation has more than 200 neighbors. Text for flag is below.

Text:
The current threshold distance value is too large to compute. Please input a smaller distance band (which might leave some observations neighborless) or use other weights (e.g. KNN).

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.5 — Mac OSX

Current:
<img width="421" alt="screen shot 2016-12-21 at 4 58 22 am" src="https://cloud.githubusercontent.com/assets/13679743/21386824/48975ad6-c73a-11e6-9dfb-2816e71684d7.png">

Change to:
The current threshold distance value is too large to compute. Please input a smaller distance band (which might leave some observations neighborless) or use other weights (e.g. KNN).

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.9 — Mac OSX
Confirmed fix:

<img width="422" alt="screen shot 2017-01-13 at 7 36 58 am" src="https://cloud.githubusercontent.com/assets/13679743/21931820/1ab39450-d963-11e6-8659-5e8f48f05f6d.png">

**Comment by lixun910** [comment]
Allow user to continue weights creation even the "current threshold distance value is too large to compute".

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.103

<img width="599" alt="7 mar 01" src="https://user-images.githubusercontent.com/36253697/37110071-ca4909ee-2233-11e8-838a-894611480f56.PNG">

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.107
Yes, it created a weigh file. 
<img width="727" alt="8 mar 01" src="https://user-images.githubusercontent.com/36253697/37157403-ab4eac94-22e0-11e8-8c5a-84a728f4e824.PNG">
