### ISSUE TITLE
Merge Table bug: last field merged empty

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#514]
GeoDa 1.8.13.11

Steps:
1. Merge a couple of .xlsx with same ID
2. for some of the files, the last field, which is populated in the original, appears empty after the merge -- for both integers and floats (see attached image: CE03_07)

<img width="1166" alt="screen shot 2016-10-30 at 5 18 30 pm" src="https://cloud.githubusercontent.com/assets/13679743/19840492/2444a7c6-9ec5-11e6-9a9b-f14e83d68c70.png">

**Comment by jkoschinsky** [comment]
actually, looking at this carefully, it looks like this is a display issue rather than a merge issue: Looks like the right edge of the last variable is chopped off but the data are actually there. So the fix would be to not visually truncate the last field's right side for tables with lots of variables?

**Comment by lixun910** [comment]
Can you share the xlsx data with me? thanks!

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.5 — Mac OSX

Fix confirmed:

<img width="748" alt="screen shot 2016-12-20 at 12 47 43 pm" src="https://cloud.githubusercontent.com/assets/13679743/21363524/9006cb50-c6b2-11e6-8cb5-73cf7771f661.png">
