### ISSUE TITLE
Regression: Potential problem with LM Error test

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#516]
From Luc:

GeoDa 1.8.13.5

I ran the standard regression using the natregimes data set with a k-6 nearest neighbor
weights. I wanted to use it as an illustration of ML not working for asymmetric matrices.
All that works: error message for ML Lag. But the results for the LM tests are strange.
They should (by now) be robust to the asymmetry of the weights, but they seem not
to be (or maybe something else is going on). See below.

<img width="575" alt="screen shot 2016-11-04 at 6 50 32 am" src="https://cloud.githubusercontent.com/assets/13679743/20018893/d341d976-a297-11e6-907b-88142d1d1431.png">

**Comment by jkoschinsky** [comment]
From other analyst:

I am currently teaching a course on spatial analysis, and attempting to use GeoDa 1.8.12. We are following the old GeoDa workbook as best as possible, even though it is increasingly out of synch with the current software. The most recent issue is in the calculation/reporting of diagnostics for spatial dependence. 

In running the examples in exercises 23 and 24, the diagnostics reported by the current version of the software bear very little resemblance to those printed in the workbook. The values now reported for LM (lag) are an order of magnitude greater than those previously reported. The values for Robust LM (lag) are the only ones that are anywhere close to the previous versions' results. Most problematic are the results for LM (error), Robust LM (error), and LM (SARMA). These results now consistently, and unhelpfully, have values reported as "inf" and probabilities as 0.000000. See attached summary (GeoDa_DigaosticsBug.rtf) and results files from the current version.

This looks like a bug in the current version of the software. Is it?

[reg_bug.zip](https://github.com/GeoDaCenter/geoda/files/578441/reg_bug.zip)

**Comment by lixun910** [comment]
This is a side bug when fixing the issue https://github.com/GeoDaCenter/geoda/issues/202

The testing only covers the senario: loading weights file and then do regression
The bug appears when creating  weights and then do regression.

fix will be in 1.8.14

**Comment by jkoschinsky** [comment]
fixed!
