### ISSUE TITLE
Add option to specify lat/lon columns in csv file

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#520]

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.5 — Mac OSX
Confirmed.

Here's a suggestion for a slight redesign of the GUI to group variable type and preview (top) and optional settings (bottom). Also switched OK and Cancel to make it consistent with the other dialogs.

In the Baltimore sample csv, XY were formatted as integers. When you change this to real in the top, then it's not immediately applied for specification in lat-lon in the bottom. Is this possible to add on the fly or too complicated?

<img width="542" alt="screen shot 2016-12-21 at 4 21 44 am" src="https://cloud.githubusercontent.com/assets/13679743/21385676/0f589e74-c735-11e6-97f8-50befc62f399.png">

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.9 — Mac OSX
Confirmed fix:

<img width="575" alt="screen shot 2017-01-13 at 7 23 24 am" src="https://cloud.githubusercontent.com/assets/13679743/21931470/34b6518c-d961-11e6-8679-64519f19cd6b.png">
