### ISSUE TITLE
Crash creating weights for remote PostGIS shapefile

### ISSUE THREAD

**Issue by gdj0nes** [GeoDaCenter/geoda#523]

**Comment by garethdavidjones** [comment]
Ubuntu version

**Comment by lixun910** [comment]
Thanks for reporting this crash!

Can you provide some more information for fixing this issue? E.g. What is the configuration of weights creation? What is the geometry type of the PostGIS table? Where do you save the weights file? On Local disk? 

Thanks!

Xun

**Comment by lixun910** [comment]
Which GeoDa version for ubuntu? 1.8.12 64bits?  You can get the version number using menu: Help-About.

Tks

**Comment by lixun910** [comment]
@garethdavidjones any inputs ?

**Comment by garethdavidjones** [comment]
Sorry for the delayed response, I hadn't had a chance to double check things! So it appears to be working fine now, but the crash happened under the following circumstances:

Operating System: Ubuntu 16.04 LTS
GeoDa: 1.8.12

I was creating queen weights congruity 1 from a remote Postgres Post GIS database for a shapefile. The weights file was saved in a local directory on disk.

**Comment by lixun910** [comment]
Thanks, Jones! Will check the crash and let you know if there is a fix soon.

**Comment by jkoschinsky** [comment]
Julie, can you confirm and, if fixed, close? thx

**Comment by jkoschinsky** [comment]
leaving open for after release so original bug reporter can confirm it works

**Comment by lixun910** [comment]
Verified creating weights from remote PostGIS spatial table using GeoDa 1.14.
