### ISSUE TITLE
Scatterplot axis labels do not match data

### ISSUE THREAD

**Issue by timstallmann** [GeoDaCenter/geoda#524]
#Hi -- I'm seeing this issue across several different datasets and across different views in the software, (v 1.8.14 on Mac OS X El Capitan). Scatter plot axis labels do not correspond to the actual data values in those positions. See example below, where the variable range is 0 to 1 but axis labels make it appear that the range is -0.7 to 2.3

<img width="501" alt="screen shot 2016-11-11 at 12 19 40 pm" src="https://cloud.githubusercontent.com/assets/6741938/20223836/61884500-a809-11e6-99fa-56d8c1032453.png">

**Comment by lixun910** [comment]
@timstallmann Thanks for reporting this! The figure you posted is Moran's I scatter plot, which the variable on x-axis are standardized so that the units in the graph correspond to standard deviation. 

Do you have the same issue in regular scatter plot?

**Comment by timstallmann** [comment]
@lixun910 that makes sense! Would it be possible to add a label to the axes indicating they were standardized? For example `VARIABLE_NAME (std. deviation)` as the default axis label rather than just `VARIABLE_NAME`?

I have had this issue on other scatterplots, but perhaps I'm misunderstanding how the output should look. Here's a screenshot of a test case on a standard scatterplot. The highlighted point should have y-value 0.51, but according to the plot axes it has a value below 0.5.

<img width="1423" alt="screen shot 2016-11-14 at 9 14 09 am" src="https://cloud.githubusercontent.com/assets/6741938/20267943/f2580a0a-aa4a-11e6-89e2-50487b7c2902.png">

**Comment by lixun910** [comment]
@timstallmann Thank you! The regular scatter plots should use raw data unless you select "data->View standardized data" from the right-click popup menu.  The screenshot you posted looks like not a completed one. Can you do another screenshot by hovering the mouse on the point you try to highlight, so that on the status bar, you can see the (x,y) value of the selected point. For example:
![screen shot 2016-11-14 at 9 18 21 am](https://cloud.githubusercontent.com/assets/2423887/20270189/c97c4532-aa4b-11e6-8a09-ffce2aa134c4.png)

**Comment by lixun910** [comment]
@jkoschinsky as @timstallmann suggested, in moran scatterplot, "Would it be possible to add a label to the axes indicating they were standardized? For example VARIABLE_NAME (std. deviation) as the default axis label rather than just VARIABLE_NAME?"

**Comment by timstallmann** [comment]
@lixun910 sure thing - here's a screenshot. I can't get the cursor to appear, but I'm hovering over the selected point.

<img width="547" alt="screen shot 2016-11-14 at 10 40 17 am" src="https://cloud.githubusercontent.com/assets/6741938/20270890/deb30552-aa56-11e6-8af1-2327d7e05184.png">

**Comment by lixun910** [comment]
@timstallmann Thanks! Will check on this issue soon, and keep you updated.

**Comment by lixun910** [comment]
@timstallmann I just checked on my side including the code, and can't replicate what you had. One more thing, can you check if the right click popup menu has "Data->View Original Data" checked?
For helping us troubleshooting this issue, is it possible to share your data with us privately? you can send it to spatial@uchicago.edu and we will delete it after troubleshooting. Thanks!

![screen shot 2016-11-14 at 10 47 29 am](https://cloud.githubusercontent.com/assets/2423887/20273666/d075b3da-aa57-11e6-907c-ecfb15efeedd.png)

**Comment by timstallmann** [comment]
@lixun910 confirmed that that is checked. And I know how frustrating it can be to try and duplicate an issue locally!!

This is all public data, so just posting the shapefile here. Here are the steps I followed:
* Open GeoDa
* Open the shapefile
* Click the "Scatterplot" button on the toolbar
* Select independent variable `Pct_NHWht` and dependent variable `pct_trump`

[votes_by_county.zip](https://github.com/GeoDaCenter/geoda/files/589897/votes_by_county.zip)

**Comment by lixun910** [comment]
@timstallmann Thanks for sharing! I actually figured out what was wrong in GeoDa using your data: the ticks on the vertical/horiz axis are (by default) set to with 1 display precision. The 0.5 tick on the y axis should be 0.54 (see this figure). 
<img width="530" alt="screen shot 2016-11-14 at 12 33 10 pm" src="https://cloud.githubusercontent.com/assets/2423887/20277749/79aa3854-aa67-11e6-8194-4e33393f9a1e.png">
In our next release, GeoDa will set the default display precision=2, and also allows user to adjust this number. I could give you an internal build soon this week, and the official release will be out in this month. Let me know if you want to try it out. Thanks again for reporting this and helping solve this issue!

**Comment by timstallmann** [comment]
Wow — thanks for tracking this down!! I’m happy to wait for the next
official update now that I know what’s going on…


On November 14, 2016 at 1:41:06 PM, Xun Li (notifications@github.com) wrote:

@timstallmann <https://github.com/timstallmann> Thanks for sharing! I
actually figured out what was wrong in GeoDa using your data: the ticks on
the vertical/horiz axis are (by default) set to with 1 display precision.
The 0.5 tick on the y axis should be 0.54 (see this figure).
[image: screen shot 2016-11-14 at 12 33 10 pm]
<https://cloud.githubusercontent.com/assets/2423887/20277749/79aa3854-aa67-11e6-8194-4e33393f9a1e.png>
In our next release, GeoDa will set the default display precision=2, and
also allows user to adjust this number. I could give you an internal build
soon this week, and the official release will be out in this month. Let me
know if you want to try it out. Thanks again for reporting this and helping
solve this issue!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GeoDaCenter/geoda/issues/524#issuecomment-260422417>,
or mute the thread

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.5 — Mac OSX
Confirmed fix.
