### ISSUE TITLE
add preference dialog for Geoda for customization

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#525]

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.5 — Mac OSX
Confirmed fix:

<img width="734" alt="screen shot 2016-12-21 at 3 59 41 am" src="https://cloud.githubusercontent.com/assets/13679743/21384902/0261b4e2-c732-11e6-9ba0-ed0a1acee83b.png">

fix small typo:
SQILTE --> SQLITE

<img width="731" alt="screen shot 2016-12-21 at 4 00 01 am" src="https://cloud.githubusercontent.com/assets/13679743/21384937/1d1c2f10-c732-11e6-8483-7e5b5461504c.png">

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.9 — Mac OSX
Confirmed fix:

<img width="619" alt="screen shot 2017-01-13 at 7 19 40 am" src="https://cloud.githubusercontent.com/assets/13679743/21931378/b32903e4-d960-11e6-868f-bec91da8c0cd.png">
