### ISSUE TITLE
Table merge issues

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#526]
GeoDa 1.8.14, Mac OSX

GeoDa is indicating that there are 8,014 duplicate values but there are only 3,108 observations, so something is wrong (non-public data emailed separately):

<img width="939" alt="screen shot 2016-11-25 at 6 57 19 pm" src="https://cloud.githubusercontent.com/assets/13679743/20654938/5ee0dec0-b4e3-11e6-98a0-b2d9840d839c.png">

There's another merge issue that I'll email you separately, too, since those data are also non-public.

**Comment by lixun910** [comment]
Hi Julia,

8014 is not the number of duplicated items, but the actual content that is duplicated: 8014 is the id number which appears at least once in the key field. -- this information gives you hint which keys/rows are duplicated.

Can you verify that?

Xun

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.9 — Mac OSX
Confirmed fix.
