### ISSUE TITLE
regression dialog - debug message

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#527]
In version 1.8.15.3, when changing the type of regression model, e.g., from classic to spatial lag or
spatial error, a debug message appears (attached).
<img width="421" alt="screen shot 2016-12-06 at 6 48 59 am" src="https://cloud.githubusercontent.com/assets/4008351/20926220/d3028198-bb80-11e6-8865-2688e8ab1b8f.png">

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.9 — Mac OSX
Confirmed fix.
