### ISSUE TITLE
Issues with new selection

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#529]
GeoDa 1.8.15.5. (Mac OSX)
columbus data

1. highest crime areas selected (in core)

--when you switch to yellow cross-hatching this seems to be applied to maps but not graphs

--"set transparency of highlighted objects in selection": when this is set to zero, nothing is visible and vice versa. This is confusing since users will think transparency is zero = full color strength, when the opposite is happening. I would instead say: "Set color strength of selected observations" and "set color strength of unselected observations" (then zero is invisible and 255 is full strength).

--right now you can adjust map transparency on the fly (i.e. while preferences are open you can see impact of changed preferences in map) but the plots seem to be locked

<img width="1349" alt="screen shot 2016-12-19 at 4 56 23 pm" src="https://cloud.githubusercontent.com/assets/13679743/21332153/3fe28804-c60c-11e6-84a6-f2b5f641a1f9.png">

<img width="1346" alt="screen shot 2016-12-19 at 4 56 51 pm" src="https://cloud.githubusercontent.com/assets/13679743/21332158/48018ac6-c60c-11e6-821d-5c272f01f8c2.png">

**Comment by jkoschinsky** [comment]
and something isn't quite right yet with the plot selection, e.g. in example below top selection point is all the way to the right at 255 and bottom one is all the way to the left, also at 255. But histogram transparency isn't adjusted after changes are applied.

<img width="1347" alt="screen shot 2016-12-19 at 5 14 31 pm" src="https://cloud.githubusercontent.com/assets/13679743/21332536/aa0636de-c60e-11e6-87a4-34ee041b8f11.png">

**Comment by lixun910** [comment]
Hi Julia, by removing the number of "opacity", do you think it's intuitive enough for user to understand how to use? 
<img width="695" alt="screen shot 2016-12-20 at 1 26 17 pm" src="https://cloud.githubusercontent.com/assets/2423887/21364808/079d2452-c6b8-11e6-9f42-ca9b8d4f25cb.png">

**Comment by jkoschinsky** [comment]
I thought about this as well but then decided against it since it's hard to
replicate a particular setting. E.g. if I like 64 and 125, I can't exactly
that result again if I don't have the numbers without tweaking a lot.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.9 — Mac OSX

Map preferences are fixed but two issues remain:
1. Plot selection preferences now work with boxplot, PCP and scatterplot but not with histogram.
2. 2nd digit of numbers associated with transparency settings are chopped off:

<img width="728" alt="screen shot 2017-01-13 at 7 55 24 am" src="https://cloud.githubusercontent.com/assets/13679743/21932422/24161b14-d966-11e6-807e-ada8521be547.png">

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.13 — Mac OSX
Confirmed fix.
