### ISSUE TITLE
Text for CSV input

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#532]
change text:

--GeoDa Csv Filed Configuration Dialog --> GeoDa CSV File Configuration
--Please Specify Data Type for Each Data Column --> (Optional) You can change the data type for a field
--Add a space between the top table and lat-long

<img width="583" alt="screen shot 2016-12-20 at 4 08 33 am" src="https://cloud.githubusercontent.com/assets/13679743/21346478/2319ad0c-c66a-11e6-874a-b63c15cbf6df.png">

**Comment by jkoschinsky** [comment]
Issues above are fixed but one new issue came up: When you change the number of preview records (as in image below), nothing happens. When you click on ok, the table opens, so preview record changes aren't implemented.

<img width="578" alt="screen shot 2017-01-12 at 11 06 54 am" src="https://cloud.githubusercontent.com/assets/13679743/21899822/55010f9a-d8b7-11e6-912d-c9708c88d94b.png">

**Comment by lixun910** [comment]
It will add/ remove rows in Data Preview. Try to change it in the range of
0 to 5, let me know if you can see how it works.

Xun Li, Ph.D

Assistant Director for Data Science
Center for Spatial Data Science
University of Chicago
http://spatial.uchicago.edu

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.13 — Mac OSX
Confirmed fix:
