### ISSUE TITLE
Remove or disable highlight color for transparency selection

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#542]
GeoDa 1.8.15.5 — Mac OSX

1. have the new transparency selection enabled
2. right-click on map: Color-Highlight Color

this only works with the yellow cross-hatch option. Let's remove or disable this for the transparency selection since it doesn't apply.

<img width="564" alt="screen shot 2016-12-21 at 4 01 55 am" src="https://cloud.githubusercontent.com/assets/13679743/21384982/5796490a-c732-11e6-9257-f8013fda7380.png">

**Comment by lixun910** [comment]
The outlines are not for crosshatching: see the following.
<img width="335" alt="screen shot 2016-12-30 at 10 00 42 pm" src="https://cloud.githubusercontent.com/assets/2423887/21575708/6d41e29a-cedb-11e6-8a58-94227e1f74a7.png">
<img width="348" alt="screen shot 2016-12-30 at 10 00 34 pm" src="https://cloud.githubusercontent.com/assets/2423887/21575709/6d4bb964-cedb-11e6-9210-ab1e779e9ef2.png">

**Comment by jkoschinsky** [comment]
The screenshot was misleading because I was only able to capture the dropdown with the outlines selected but the issue is not with the outlines but with the 2nd dropdown option: Color - Highlight Color. That one is active for transparent selection, which doesn't make sense since you can't change the selection color after the color dialog opens:

<img width="835" alt="screen shot 2017-01-12 at 11 17 39 am" src="https://cloud.githubusercontent.com/assets/13679743/21900314/f63bc66a-d8b8-11e6-8d2a-86edc5024fc2.png">

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.13 — Mac OSX
Confirmed fix.
