### ISSUE TITLE
Test sending bug from GeoDa

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#553]
test sending bug

In GdaFrame::OnReportBug()
Open ReportBugDlg.
In ReportBugDlg::OnOkClick()

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.9 — Mac OSX

Currently bug report submission doesn't seem to work. When you try to submit a bug, you get the following error message:

<img width="584" alt="screen shot 2017-01-13 at 6 39 05 am" src="https://cloud.githubusercontent.com/assets/13679743/21930324/107fac2e-d95b-11e6-8fb0-009f9b1c3a34.png">

**Comment by jkoschinsky** [comment]
Problem remains:

<img width="668" alt="screen shot 2017-01-23 at 7 02 07 pm" src="https://cloud.githubusercontent.com/assets/13679743/22229644/a2cc3ed0-e19e-11e6-91a5-63fcc8c86d4f.png">

**Comment by jkoschinsky** [comment]
problem persists:

<img width="577" alt="screen shot 2017-01-24 at 7 00 08 am" src="https://cloud.githubusercontent.com/assets/13679743/22248130/c85b38f4-e202-11e6-9d92-80bb37e2f4aa.png">

**Comment by jkoschinsky** [comment]
see https://github.com/GeoDaCenter/geoda/issues/620
