### ISSUE TITLE
Unique values and natural breaks maps: Not working right with lots of zeros

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#554]
GeoDa 1.8.15.7 — Mac OSX
NYC schools data: Sum_v1 variable
[nycschooldata.zip](https://github.com/GeoDaCenter/geoda/files/696192/nycschooldata.zip)

GeoDa fails to accurately map variables with lots of zeros in unique value and natural breaks maps (formatted as real or integer). E.g., it doesn't assign one color to zero and other colors to non-zero values:

<img width="1475" alt="screen shot 2017-01-10 at 5 28 45 am" src="https://cloud.githubusercontent.com/assets/13679743/21806924/bfca2a26-d701-11e6-954d-31c3f9828334.png">

<img width="1219" alt="screen shot 2017-01-10 at 5 32 51 am" src="https://cloud.githubusercontent.com/assets/13679743/21806926/c1631a32-d701-11e6-95af-6b308bc2ea06.png">

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.9 — Mac OSX

works better than before (now zeros are identified) but not quite fixed yet:

In some cases (e.g. SUM_v1 variable below), the zero bin includes a range of values from 0 to X, not just zeros:

<img width="796" alt="screen shot 2017-01-11 at 9 04 21 am" src="https://cloud.githubusercontent.com/assets/13679743/21853584/5ed4061a-d7dd-11e6-91cd-7135e89dc2bf.png">

**Comment by lixun910** [comment]
Yes,I remember what Mark told me, for unique value map, if the number of
unique values >10 then the map will be natural breaks? let me know if that
should be changed.


Xun Li, Ph.D

Assistant Director for Data Science
Center for Spatial Data Science
University of Chicago
http://spatial.uchicago.edu

**Comment by jkoschinsky** [comment]
What I think makes more sense is to keep the cap of 10 legend categories
but use actual unique values for the first 1-9 values and then group all
remaining values into the 10th bin, so that's the only bin with a range of
values? We could also add a flag to let people know that's what we're
doing. Otherwise people will be confused since they won't know they're
looking at natural breaks instead of unique values, which they selected.

**Comment by jkoschinsky** [comment]
Luc: increase unique value categories to 20.

Here are 20 qualitative RGB values from Colorbrewer:

166,206,227
31,120,180
178,223,138
51,160,44
251,154,153
227,26,28
253,191,111
255,127,0
106,61,154
255,255,153
177,89,40
255,255,179
190,186,218
251,128,114
128,177,211
179,222,105
252,205,229
217,217,217
188,128,189
204,235,197

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.13 — Mac OSX
Confirmed fix:

<img width="1106" alt="screen shot 2017-01-23 at 7 12 26 pm" src="https://cloud.githubusercontent.com/assets/13679743/22229878/026d9b62-e1a0-11e6-929e-a2bd6ec49a07.png">
