### ISSUE TITLE
Select variables to delete: first part of vars cut off

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#555]
GeoDa 1.8.15.5 — Mac OSX
NYC schools data

In the "Select variables to delete" dialog, the first part of variables is sometimes cut off, like here:
<img width="329" alt="screen shot 2017-01-10 at 5 30 01 am" src="https://cloud.githubusercontent.com/assets/13679743/21807626/48c443fe-d705-11e6-9dc5-902fb357b9ca.png">

**Comment by lixun910** [comment]
I remember this happened before, like when one uses touchpad to scroll horizontally to left/right, and you can always scroll back. The horizontal scroll bar can be only added in Windows platform -- that's a limitation of wxwidgets.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.9 — Mac OSX
Confirmed fix:

<img width="322" alt="screen shot 2017-01-11 at 8 59 23 am" src="https://cloud.githubusercontent.com/assets/13679743/21853357/641b936e-d7dc-11e6-9c93-983ca7b7614b.png">
