### ISSUE TITLE
Table merge problem with .xlsx

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#563]
GeoDa 1.8.15.11 — Mac OSX
Nepal data [nepal.zip](https://github.com/GeoDaCenter/geoda/files/724273/nepal.zip)

Steps:
Merge .xlsx file with unique polyid to shapefile
Generates this error:

<img width="424" alt="screen shot 2017-01-23 at 12 11 00 am" src="https://cloud.githubusercontent.com/assets/13679743/22211974/8b7d4246-e154-11e6-9a12-0c237516f59b.png">

After converting the .xlxs file to dbf (without any other changes), it works without problem.

**Comment by jkoschinsky** [comment]
Xun discovered this is caused by two empty rows at the end of the xlxs file. Looking for ways to delete this before merging.

**Comment by lixun910** [comment]
This is caused by more than one empty rows in xlsx file, and GeoDa detected it and refuse to merge.
Will add a checker to remove empty rows at the end of table in xlsx file.

**Comment by jkoschinsky** [comment]
I added two empty rows to this file and it crashes GeoDa, e.g. when you open it, right-click on table, Edit Variable Properties, then don't touch anything - crash. Replicable.

GeoDa 1.8.15.27 — Mac OSX
[col_test.xls.zip](https://github.com/GeoDaCenter/geoda/files/779067/col_test.xls.zip)

**Comment by lixun910** [comment]
Should be fixed in #622

**Comment by YidanJ-Wu** [comment]
GeoDa 1.8.15.31 - Windows 8 
I tried merging the shapefile to the .xls file in col_test.xls.zip and got this:
![geoda problem 2-28](https://cloud.githubusercontent.com/assets/22801047/23446419/b881ce44-fe08-11e6-910f-cc06d6d8fb87.png)

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.35 — Mac OSX
Confirmed.
