### ISSUE TITLE
Raw rate map settings

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#565]
GeoDa 1.8.15.11 — Mac OSX

In the rates dialog, disable the category choice for map themes that are fixed (percentile, box map, SD) since it doesn't apply/work for these:

<img width="526" alt="screen shot 2017-01-23 at 12 15 57 am" src="https://cloud.githubusercontent.com/assets/13679743/22212656/215fa702-e157-11e6-9277-e0dad55eeb3f.png">

**Comment by lixun910** [comment]
solution: the category spin control will be disabled when choose percentile, box map, SD

<img width="528" alt="screen shot 2017-01-23 at 1 58 05 pm" src="https://cloud.githubusercontent.com/assets/2423887/22220365/04072c30-e174-11e6-8039-67bced7f2539.png">

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.13 — Mac OSX
confirmed fix
