### ISSUE TITLE
Add neighbor selection back to LISAs?

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#566]
GeoDa 1.8.15.11 — Mac OSX

I know we took this out after discussing it but after needing the "Add Neighbors to Selected" feature for LISAs several times, I'm voting to add this back in for the following reason:

Right now when you want to visualize neighbors and cores in LISA, you have to:

1. open table
2. right-click on table
3. go to Selection Tool
4. Add Neighbors to Selection (with weights spec)

Nobody who isn't an insider will know how to find this if the LISA map is the starting point. On the other hand, finding it after right-clicking on the LISA menu is intuitive.

Xun and I discussed this and he found the old right-click code. Luc, can you think of any reason not to put it back at LISA map-right-click?

**Comment by jkoschinsky** [comment]
a bit hard to see white selected neighbors on white background but users can switch to yellow cross hatching if needed.

Let's include neighbors with undefined values as neighbors. Otherwise we have two different results for "add selected to neighbors" e.g. in the linked map for the LISA selection and the table selection tool:

<img width="1252" alt="screen shot 2017-01-23 at 6 08 26 pm" src="https://cloud.githubusercontent.com/assets/13679743/22228489/1e952886-e197-11e6-90f5-b82b6fe6cae4.png">

<img width="1204" alt="screen shot 2017-01-23 at 6 15 28 pm" src="https://cloud.githubusercontent.com/assets/13679743/22228646/26bb2fb4-e198-11e6-81cd-3f4911431560.png">

**Comment by lixun910** [comment]
Hi Julia, 

I think the functions "add neighbor to selection" in table menu has different meaning: the neighbors are only determined by the topology of geometries, which is different than LISA -- the values (undefined) are also considered.

We can't highlight the undefined obs as neighbors in LISA since they are not in actually LISA computation. Highlighting them will make people confused is not correct.

Xun

**Comment by lanselin** [comment]
I think we should be consistent and have the same set of neighbors, irrespective of whether
the values are valid or not. As you point out, these are two different dimensions and I don’t
think we should mix them.
L.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.27 — Mac OSX

confirmed that table and LISA map selection are now identical with undefined values.
