### ISSUE TITLE
View stats in histogram bug

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#578]
View stats not displayed right when records are selected

<img width="602" alt="screen shot 2017-01-25 at 11 12 19 am" src="https://cloud.githubusercontent.com/assets/13679743/22302547/de197190-e2f4-11e6-8e07-403c4d6ee046.png">

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.27 — Mac OSX
Confirmed.

<img width="1197" alt="screen shot 2017-02-15 at 9 40 53 pm" src="https://cloud.githubusercontent.com/assets/13679743/23006458/78210bee-f3c7-11e6-9023-85288ff12a91.png">

Julie, can you confirm and, if fixed, close for Windows? thx

**Comment by YidanJ-Wu** [comment]
GeoDa 1.8.15.27 — Windows 8 
Confirmed.
