### ISSUE TITLE
Add Neighbors to Selected option: LISA

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#580]
Right now the right-click "Add Neighbors to Selected" option for LISA maps, highlights the neighbors of the cores. Per discussion at our Jan. 25 mtg, let's change this to "Show Cores and Neighbors" to display neighbors in the hi-hi, lo-lo, hi-lo, lo-hi colors since this is cumbersome to add.

Let's add Cores Only or Cores and Neighbors to the LISA map view header so people know what they're looking at.

If there's a conflict because an area has more than one values, let's use these rules:
--core trumps neighbor
--in the less likely event that an area j belongs to two i's with opposite core colors (like hi and lo), what color to choose could be prioritized arbitrarily (e.g. hi trumps lo) or by going with the color associated with the core that has the smaller p-value?

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.143
Here are the different visualizations of neighbors and cores possible with the LISA map

With "Show Selection and Neighbors" Selected

<img width="588" alt="screen shot 2018-07-26 at 2 00 17 pm" src="https://user-images.githubusercontent.com/37029239/43282630-45f57994-90dc-11e8-8cc5-99db5cabd972.png">
<img width="594" alt="screen shot 2018-07-26 at 1 47 59 pm" src="https://user-images.githubusercontent.com/37029239/43282187-0d67a058-90db-11e8-9378-7676f82a447d.png">
<img width="410" alt="screen shot 2018-07-26 at 1 48 15 pm" src="https://user-images.githubusercontent.com/37029239/43282186-0d51256c-90db-11e8-8165-3c525c3540e2.png">
<img width="592" alt="screen shot 2018-07-26 at 1 48 50 pm" src="https://user-images.githubusercontent.com/37029239/43282185-0d2c22ee-90db-11e8-8b04-921e885908a0.png">
<img width="588" alt="screen shot 2018-07-26 at 1 49 12 pm" src="https://user-images.githubusercontent.com/37029239/43282183-0d1bbe36-90db-11e8-8701-59f0707e2b60.png">
<img width="595" alt="screen shot 2018-07-26 at 1 49 25 pm" src="https://user-images.githubusercontent.com/37029239/43282182-0d0d7420-90db-11e8-82db-51ee60ffc3e8.png">
<img width="592" alt="screen shot 2018-07-26 at 1 49 39 pm" src="https://user-images.githubusercontent.com/37029239/43282181-0cff039a-90db-11e8-9701-38816c628262.png">
<img width="593" alt="screen shot 2018-07-26 at 1 50 09 pm" src="https://user-images.githubusercontent.com/37029239/43282180-0cf32fca-90db-11e8-8b44-88777c086d7b.png">

Without "Show Selection and Neighbors" Selected

<img width="591" alt="screen shot 2018-07-26 at 2 02 00 pm" src="https://user-images.githubusercontent.com/37029239/43282717-82469a72-90dc-11e8-96ab-06f003be363e.png">
<img width="594" alt="screen shot 2018-07-26 at 2 02 34 pm" src="https://user-images.githubusercontent.com/37029239/43282745-98f0013c-90dc-11e8-9f54-c7311bd352bc.png">
<img width="593" alt="screen shot 2018-07-26 at 2 02 42 pm" src="https://user-images.githubusercontent.com/37029239/43282744-98e43c80-90dc-11e8-9891-e3be1c48512d.png">
<img width="589" alt="screen shot 2018-07-26 at 2 13 13 pm" src="https://user-images.githubusercontent.com/37029239/43283282-1873dcb6-90de-11e8-9e8f-ecb7da790f57.png">
<img width="591" alt="screen shot 2018-07-26 at 2 13 21 pm" src="https://user-images.githubusercontent.com/37029239/43283288-1cd41e56-90de-11e8-8cba-f0c31fc89460.png">
<img width="595" alt="screen shot 2018-07-26 at 2 13 55 pm" src="https://user-images.githubusercontent.com/37029239/43283313-2d79ceea-90de-11e8-80fd-c184b4b3d025.png">
<img width="595" alt="screen shot 2018-07-26 at 2 14 02 pm" src="https://user-images.githubusercontent.com/37029239/43283320-3141ef6c-90de-11e8-94ea-3851f6388518.png">
