### ISSUE TITLE
Does not support linear data

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#581]
Geoda 1.8.15.15 -- Windows 8

Steps: 
1. opened a .shp file (simcounty_outline.shp)
2. error message "Geoda does not support datasource with line data at this time. Please choose a data source with either point or polygon data."

![geoda issue](https://cloud.githubusercontent.com/assets/22801047/22354639/cbb06e30-e3eb-11e6-9ec6-59335e856afa.png)

**Comment by jkoschinsky** [comment]
this is actually a feature rather than a bug :)

GeoDa is designed for area data (can handle points but not designed for
analysis of events), so this is right -- it can't handle streets and other
line data.
