### ISSUE TITLE
Fix boxmap labels

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#582]
Don't include outlier thresholds in boxmap labels because of the problem below (90-114, 114-97.5) when there are no observations in the outlier category:

114 is the threshold beyond which observations are defined as outliers (see image below; the 114 value is determined by 1.5x the IQR). Since PER_WHI doesn't contain any upper outliers, the max value is 97.5. The legend displays the 114 value (threshold) and then jumps back to the highest observed value (97.5).

<img width="828" alt="screen shot 2017-01-29 at 7 00 37 pm" src="https://cloud.githubusercontent.com/assets/13679743/22409858/2c03e1ce-e656-11e6-84ea-16d62ce87088.png">

**Comment by jkoschinsky** [comment]
what to do with box plot/map hinge values that are out of range: E.g. in the attached case the variable is a percentage, i.e. it ranges from 0-100. The hinge is 114, which is also listed as the range for the upper outlier but it's outside of the possible values that could exist for this variable.

**Comment by lixun910** [comment]
Is the upper outlier 114? Upper hinge is Q3/75% percentile?

I think One should expect the "upper outlier" in a box map even there is no observation? So instead of delete this category, just change its label "upper outlier 114-97.5" to "upper outlier 114-inf"

We can talk about it tomorrow

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.27 — Mac OSX
Confirmed fix:

<img width="600" alt="screen shot 2017-02-15 at 9 39 50 pm" src="https://cloud.githubusercontent.com/assets/13679743/23006427/55109b06-f3c7-11e6-94bd-cffbea0e272d.png">
