### ISSUE TITLE
Averages Chart: Add selected vs unselected in different time periods

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#583]
Currently, the Average Chart options are:

1) unselected vs. selected in the same time period or 
2) selected time 0 vs 1 
3) unselected time 0 vs1

Let's also add this 4th option -- selected vs unselected in different time periods:

4) Selected - Unselected - Time 0 - Time 1

The DID does selected vs unselected with time0 and time1 but the interface does not allow that.

**Comment by lixun910** [comment]
I remember we discuss this option before: does it make any sense to compare select and unselected at two different time periods?

**Comment by lanselin** [comment]
In fact, this is what DID does, so the disconnect is between the user interface
that does not allow it and the DID regression that implements it.

**Comment by jkoschinsky** [comment]
The unselected-selected time 0-1 option works in the averages chart (as expected, DID results are the same for selected time0-1, unselected 0-1, and selected-unselected 0-1). The attached example compares unselected time 0 to selected in time 3 but selected, unselected and all are highlighted for time 0 and time 3 in the char with the purple and brown dots. Is it possible to only purple-dot-highlight unselected in time 0 and brown-dot-highlight selected in time 3 to make it more clear what means are being compared?

<img width="801" alt="screen shot 2017-01-31 at 9 53 22 pm" src="https://cloud.githubusercontent.com/assets/13679743/22494838/b6625ec6-e800-11e6-85c1-7184c69ff052.png">

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.27 — Mac OSX

Not fixed yet / still the same as before?

<img width="799" alt="screen shot 2017-02-15 at 9 37 26 pm" src="https://cloud.githubusercontent.com/assets/13679743/23006382/083a46ce-f3c7-11e6-8e48-dfd71df31d8e.png">

**Comment by lixun910** [comment]
Do you mean on the right side of the plot, there are only two legends represent “selected/period1” vs “unselected/period2”?

**Comment by jkoschinsky** [comment]
what I mean is if this is possible:

<img width="685" alt="screen shot 2017-02-15 at 10 15 43 pm" src="https://cloud.githubusercontent.com/assets/13679743/23007169/5f3604fe-f3cc-11e6-9460-3d6d56af3355.png">

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.35— Mac OSX
Confirmed.

<img width="799" alt="screen shot 2017-03-01 at 3 51 46 pm" src="https://cloud.githubusercontent.com/assets/13679743/23483097/1a53af28-fe97-11e6-92db-4ee1e3966e08.png">
