### ISSUE TITLE
Add local cluster maps as theme to conditional map

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#584]
We discussed at the last meeting that it would be great to view the local Moran's I maps and local G maps as the map theme of the conditional maps. May be one way to implement this would be to:

-- first run one of the local cluster maps, 
--then right-click to access a new category (e.g. Show as Cond. Map), 
--which would open the conditional map view where the map theme would be the local cluster theme (can't be changed) and users still have to select an X and Y variable

**Comment by jkoschinsky** [comment]
This is fantastic. Really like this and the interface is very simple and smooth.

Check out the HR90 LISA map conditioned on inequality and resource deprivation: homicide hotspots are especially concentrated in the micromap that's highest on both:

<img width="1331" alt="screen shot 2017-02-15 at 9 30 56 pm" src="https://cloud.githubusercontent.com/assets/13679743/23006255/5a4b1e44-f3c6-11e6-993d-fb938b1d225e.png">

GeoDa 1.8.15.27 — Mac OSX
Confirmed.

Julie, can you confirm and, if fixed, close for Windows? thx
create LISA map, right-click: Show Conditional Map

**Comment by YidanJ-Wu** [comment]
GeoDa 1.8.15.27 Windows 8
Confirmed. 
![image](https://cloud.githubusercontent.com/assets/22801047/23235314/aa019e14-f91a-11e6-8367-39db06f4eabb.png)
