### ISSUE TITLE
Add view + save stats to correlogram

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#585]
From a GeoDa user:

Add view stats to correlogram and right-click save stats to output csv.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.27 — Mac OSX
Confirmed.

<img width="1054" alt="screen shot 2017-02-15 at 9 20 04 pm" src="https://cloud.githubusercontent.com/assets/13679743/23005942/ad999302-f3c4-11e6-821c-8b9f4afdd4cd.png">

Julie, can you confirm and, if fixed, close for Windows? thx

**Comment by YidanJ-Wu** [comment]
Geoda 1.8.15.27 Windows 8 
This is what I get: 
![image](https://cloud.githubusercontent.com/assets/22801047/23234349/6d7c4e92-f917-11e6-8aa7-f444fc763af1.png)
