### ISSUE TITLE
Changing variable types in CSV

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#588]
GeoDa version 1.8.15.21

Opened a CSV file in Geoda. The program crashed when I attempted to change the data type in a column from integer to string. 
![geoda problem](https://cloud.githubusercontent.com/assets/22801047/22568164/5622bc96-e958-11e6-8599-1f2952de6421.png)

**Comment by lixun910** [comment]
confirmed on windows (only)

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.27 — Mac OSX
Confirmed it works.

Julie, can you confirm and, if fixed, close for Windows? thx

**Comment by YidanJ-Wu** [comment]
GeoDa 1.8.15.27
Confirmed on Windows 8
