### ISSUE TITLE
Unexpected Crash

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#589]
Version 1.8.15.21
Windows 8
![geoda problem 1](https://cloud.githubusercontent.com/assets/22801047/22700885/a7a8ed5c-ed21-11e6-86af-b1934edad3d5.png)

I opened a .shp file with point data, added a basemap, and Geoda crashed immediately. This happened two times. The first time, I also had the Nonparametric Spatial Autocorrelation feature running.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.27 — Mac OSX
Confirmed it works with other point data.

<img width="700" alt="screen shot 2017-02-15 at 9 15 24 pm" src="https://cloud.githubusercontent.com/assets/13679743/23005816/f135f76e-f3c3-11e6-81bd-e3d84f3b81d6.png">

Julie, can you confirm and, if fixed, close for Windows? thx

**Comment by YidanJ-Wu** [comment]
Verion 1.8.15.27
Windows 8
Confirmed
