### ISSUE TITLE
Crash when opening WFS file

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#591]
Version 1.8.15.21
Windows 8

Attempted to access a WFS file from this URL: http://hazards.fema.gov/gis/nfhl/services/public/NFHL/MapServer/WFSServer
![geoda problem 2](https://cloud.githubusercontent.com/assets/22801047/22701500/681258f2-ed23-11e6-98fe-1fadf9a6bc67.png)

![geoda problem 3](https://cloud.githubusercontent.com/assets/22801047/22701510/6ef2b1e4-ed23-11e6-885f-c7057c2e0b1e.png)

Edit: Here is the page that I got the WFS link from. https://hazards.fema.gov/femaportal/wps/portal/NFHLWMS

**Comment by lixun910** [comment]
The icon (top-right) on this connect dialog is also not correct.

**Comment by lixun910** [comment]
GeoDa can't set http connection timeout, and this cause a hang and crash if connecting to a "slow" WFS server. A initial timeout=5seconds has been setup, and user can change it in "preference" dialog. Once the timeout been reached, the connection attempts will be terminated.

<img width="720" alt="screen shot 2017-02-09 at 9 08 32 pm" src="https://cloud.githubusercontent.com/assets/2423887/22812700/f0c1fc5e-ef0b-11e6-8f59-ec5cb27b6f74.png">

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.27 — Mac OSX
Confirmed.

Julie, can you confirm and, if fixed, close for Windows? thx

**Comment by YidanJ-Wu** [comment]
GeoDa 1.8.15.27 
Windows 88
Confirmed.
