### ISSUE TITLE
Crash Report: Click Save Category on a themeless map

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#592]
Details:
Error: XRC error: 7366: vertical alignment flag 'wxALIGN_TOP' has no effect inside a vertical box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 7428: vertical alignment flag 'wxALIGN_CENTRE_VERTICAL' has no effect inside a vertical box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 7455: vertical alignment flag 'wxALIGN_CENTRE_VERTICAL' has no effect inside a vertical box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 7482: 'wxEXPAND' is incompatible with vertical alignment flag ''wxALIGN_CENTER_VERTICAL'' in a horizontal box sizer
Error: XRC error: 7496: both 'wxALIGN_CENTRE_HORIZONTAL' (as part of wxALIGN_CENTRE) and 'wxALIGN_CENTER_HORIZONTAL' specify horizontal alignment and can't be used together
Error: XRC error: 7503: both 'wxALIGN_RIGHT' and 'wxALIGN_CENTER_HORIZONTAL' specify horizontal alignment and can't be used together
Open Datasource:WFS:https://mrdata.usgs.gov/wfs/active-mines?request=getfeature&service=WFS&version=1.1.0&typename=mineplant&maxfeatures=10
Open Layer:mineplant
Open TableFrame.
Open MapFrame.
Check auto update:
In MapFrame::OnMapBasemap()
Click GdaFrame::OnSetBasemap1
In MapFrame::OnMapBasemap()
Click GdaFrame::OnCleanBasemap
In MapFrame::OnMapBasemap()
Click GdaFrame::OnSetNoBasemap
In GdaFrame::OnSaveCategories()

**Comment by jkoschinsky** [comment]
Xun, is this the crash report for https://github.com/GeoDaCenter/geoda/issues/602?

**Comment by lixun910** [comment]
No, this is the crash on windows when click Save Category on a themeless map.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.27 — Mac OSX

When you try to save categories of a themeless map in Windows, nothing happens. Let's disable instead since it's not meaningful.

**Comment by YidanJ-Wu** [comment]
GeoDa 1.8.15.29 Windows 8 
Confirmed
