### ISSUE TITLE
Basemap wouldn't load for WFS File

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#593]
Version 1.8.15.21
Windows 8

I opened the file again and tried to add a basemap. The points have geographic coordinates, but the basemap wouldn't show. 
![geoda problem 4](https://cloud.githubusercontent.com/assets/22801047/22702370/0f363e3a-ed26-11e6-97e3-330a6e60f01c.png)

**Comment by lixun910** [comment]
The WFS 
```
https://mrdata.usgs.gov/wfs/active-mines?request=getfeature&service=WFS&version=1.1.0&typename=mineplant&maxfeatures=10
```
you posted seems not correct (the points should be lat-lon pair, but in the data it looks like lon-lat pair). 

I get a warning message to when try to add basemap. Let's verify this again.
![capture](https://cloud.githubusercontent.com/assets/2423887/22806955/3d94f454-eeea-11e6-99f1-00c325bd34c9.PNG)

**Comment by jkoschinsky** [comment]
Julie, can you confirm and, if fixed, close for Windows? thx

**Comment by YidanJ-Wu** [comment]
Version 1.8.15.27
Windows 8
I still did not get a warning message when I tried to add a basemap. This is what shows: 
![geoda problem 10](https://cloud.githubusercontent.com/assets/22801047/23075988/35484d8a-f504-11e6-9684-dfae27e40d3a.png)

**Comment by lixun910** [comment]
the points in WFS url has (33.00195, -111.46) pair, which is not matching to default GIS Point(lon, lat) setup, that's why basemap can not be loaded. 

however, the background should not be black -- will check this on windows

**Comment by lixun910** [comment]
Also, In csv configure dialog, change  Latitude/X to Longitude/X (horizontal west-east),  Longitude/Y to Latitude/Y (vertical, south-north)

**Comment by YidanJ-Wu** [comment]
1.8.15.27
Windows 8
Thanks! I changed the latitude and longitude and now the basemap is loading correctly: 
![image](https://cloud.githubusercontent.com/assets/22801047/23318512/6486fb20-fa98-11e6-8b04-56b4abee4435.png)

**Comment by lixun910** [comment]
OK. The black background showing is because the basemap "carto dark" has been selected.

**Comment by YidanJ-Wu** [comment]
GeoDa 1.8.15.29
Windows 8
Confirmed
