### ISSUE TITLE
preference dialog not showing on Windows

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#594]
Also, the slider bar doesn't work when click on it.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.27 — Mac OSX
Confirmed that this works here.

Julie, can you confirm and, if fixed, close for Windows? thx

**Comment by YidanJ-Wu** [comment]
GeoDa 1.8.15.27 - Windows 8
Preference dialog is showing up but if I resize the window, some of the text gets cut off.
![image](https://cloud.githubusercontent.com/assets/22801047/23078179/34d09778-f50d-11e6-9ef8-e19c23c5ee22.png)

**Comment by lixun910** [comment]
disable resizable option for preference dialog (can't set a minimum size for a wxDialog now)

**Comment by YidanJ-Wu** [comment]
Geoda 1.8.15.29 
Windows 8 
Confirmed
![image](https://cloud.githubusercontent.com/assets/22801047/23344523/b9a79ff4-fc43-11e6-91d7-18772a3d6b21.png)
