### ISSUE TITLE
Basemap won't load for sample data

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#596]
Version 1.8.15.21
Windows 8

I loaded the Baltimore home sales file from the "Sample Data" tab on the right. Got an error message when adding a basemap. 

![geoda problem baltimore 0](https://cloud.githubusercontent.com/assets/22801047/22837397/fef977d2-ef85-11e6-8b86-980aff5b5da3.png)

![geoda problem baltimore 1](https://cloud.githubusercontent.com/assets/22801047/22837403/03b84ab4-ef86-11e6-83cd-8e5119f2cce7.png)

**Comment by jkoschinsky** [comment]
Yes, that's correct since we don't have that prj

**Comment by lixun910** [comment]
wont fix
