### ISSUE TITLE
Wrong basemap loaded

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#597]
Version 1.8.15.21
Windows 8

When I loaded the base map for the Columbus crime map, it showed a map of Kano, Nigeria instead of Columbus, Ohio. 

![geoda problem columbus](https://cloud.githubusercontent.com/assets/22801047/22837707/5af779a2-ef87-11e6-94cf-df37b390d138.png)

![geoda problem columbus 0](https://cloud.githubusercontent.com/assets/22801047/22837735/806d425c-ef87-11e6-9f39-93b9f5500e46.png)

**Comment by jkoschinsky** [comment]
same problem as with Baltimore

**Comment by lixun910** [comment]
wont fix
