### ISSUE TITLE
Scroll bars not moving

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#600]
Verion 1.8.15.21
Windows 8 

Loaded CSV file without any issues, but when I tried to scroll down to look at field names, the scroll bar would not move. 
![geoda problem 5](https://cloud.githubusercontent.com/assets/22801047/22938914/cacd418a-f2a2-11e6-8f0d-b702968df71e.png)

**Comment by lixun910** [comment]
Check the latest version 1.8.15.25 which includes a fix for this issue.

**Comment by YidanJ-Wu** [comment]
Can I get a link to download 1.8.15.25?

**Comment by lixun910** [comment]
https://www.dropbox.com/s/7ewoxypc0ivfsom/GeoDa1.8.15.25-Installer.dmg?dl=0 <https://www.dropbox.com/s/7ewoxypc0ivfsom/GeoDa1.8.15.25-Installer.dmg?dl=0>

**Comment by YidanJ-Wu** [comment]
Do you have a link to the Windows 8 version? I can't open .dmg files on my computer.

**Comment by lixun910** [comment]
https://www.dropbox.com/s/9sqsihcmezg93hv/GeoDa-1.8.15.25-Windows-64bit.exe?dl=0 <https://www.dropbox.com/s/9sqsihcmezg93hv/GeoDa-1.8.15.25-Windows-64bit.exe?dl=0>

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.27 — Mac OSX
Confirmed.

Julie, can you confirm and, if fixed, close for Windows? thx

**Comment by YidanJ-Wu** [comment]
Verion 1.8.15.27
Windows 8
Confirmed
