### ISSUE TITLE
Crashed while saving to a project file

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#602]
Version 1.8.15.21
Windows 8

I opened a file from this URL: http://ndgishub.nd.gov/arcgis/services/Features/Communications/MapServer/WFSServer?request=GetCapabilities&service=WFS
without any problems. Then I tried to save it as CSV and checked the box next to "Create a project file?"

![geoda problem 6](https://cloud.githubusercontent.com/assets/22801047/22940058/47180b0a-f2a6-11e6-8991-1d33cab28a58.png)

**Comment by lixun910** [comment]
confirmed on windows

**Comment by jkoschinsky** [comment]
When I choose the first file of that URL, the histogram and table display ok but the map view is empty:

<img width="1719" alt="screen shot 2017-02-15 at 8 54 05 pm" src="https://cloud.githubusercontent.com/assets/13679743/23005249/0603bbc0-f3c1-11e6-9f03-c7cf05c71040.png">

**Comment by lixun910** [comment]
Hi Julia

Do you have a QGIS or other software that can verify the datasource has geometries (points/polygons)?
Thanks!
Xun

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.27 — Mac OSX
Confirmed that csv saving works with another WFS file.

Julie, can you confirm and, if fixed, close for Windows? thx

**Comment by YidanJ-Wu** [comment]
GeoDa 1.8.15.27 - Windows 8
