### ISSUE TITLE
GeoDa Preference Setup window text not showing up

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#603]
Version 1.8.15.21
Windows 8

When first opening the GeoDa Preference Setup window, the text doesn't show up. It only shows up after resizing the window. 
![geoda problem 8](https://cloud.githubusercontent.com/assets/22801047/22941458/19e30824-f2ab-11e6-8a56-86f8fff15be8.png)

![geoda problem 7](https://cloud.githubusercontent.com/assets/22801047/22941469/1e79d1ba-f2ab-11e6-98ae-d3a19fa66738.png)

**Comment by lixun910** [comment]
Again please check the latest build 1.8.15.25.

**Comment by lixun910** [comment]
I've sent you several emails with the download links. Seems you didn't get my email. Here is the link: https://www.dropbox.com/s/9sqsihcmezg93hv/GeoDa-1.8.15.25-Windows-64bit.exe?dl=0 

Thanks, Julie!

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.27 — Mac OSX
Confirmed.

Julie, can you confirm and, if fixed, close for Windows? thx

**Comment by YidanJ-Wu** [comment]
Verion 1.8.15.27
Windows 8
Confirmed.
