### ISSUE TITLE
Crash Report: Save LISA results to Table

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#616]
Details:
Open MapFrame.
Check auto update:
Click GdaFrame::OnToolsWeightsManager
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
Click CreatingWeightDlg::OnIdVariableSelected
selected:0
Click CreatingWeightDlg::OnCreateNewIdClick
Try to insert unique id (integer, POLY_ID) column in table.
Click CreatingWeightDlg::OnCRadioQueenSelected
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/home/cdrc-x/manchester_LSOA_IMD.gal
Open ConnectivityHistFrame
ConnectivityHistFrame::OnActivate
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
IMDscore
VariableSettingsDlg::GetWeightsId() weight: manchester_LSOA_IMD
VariableSettingsDlg::GetWeightsId() weight: manchester_LSOA_IMD
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
IMDscore
VariableSettingsDlg::GetWeightsId() weight: manchester_LSOA_IMD
VariableSettingsDlg::GetWeightsId() weight: manchester_LSOA_IMD
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
POLY_ID
VariableSettingsDlg::GetWeightsId() weight: manchester_LSOA_IMD
VariableSettingsDlg::GetWeightsId() weight: manchester_LSOA_IMD
Click GdaFrame::OnToolsWeightsManager
Click GdaFrame::OnToolsWeightsManager
Click GdaFrame::OnToolsWeightsCreate
Click CreatingWeightDlg::OnCRadioQueenSelected
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/home/cdrc-x/Documents/adrc/manchester_LSOA_IMD.gal
Open ConnectivityHistFrame
ConnectivityHistFrame::OnActivate
ConnectivityHistFrame::OnActivate
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
IMDscore
VariableSettingsDlg::GetWeightsId() weight: manchester_LSOA_IMD_1
VariableSettingsDlg::GetWeightsId() weight: manchester_LSOA_IMD_1
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
IMDscore
VariableSettingsDlg::GetWeightsId() weight: manchester_LSOA_IMD
VariableSettingsDlg::GetWeightsId() weight: manchester_LSOA_IMD
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
IMDscore
VariableSettingsDlg::GetWeightsId() weight: manchester_LSOA_IMD
VariableSettingsDlg::GetWeightsId() weight: manchester_LSOA_IMD
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
IMDscore
VariableSettingsDlg::GetWeightsId() weight: manchester_LSOA_IMD
VariableSettingsDlg::GetWeightsId() weight: manchester_LSOA_IMD
In GdaFrame::OnSaveLisa()
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0

**Comment by lixun910** [comment]
Thanks for reporting this! This issue has been fixed in latest GeoDa (internal build 1.8.15.27). You can download the latest GeoDa at:
Mac:
https://www.dropbox.com/s/8ld19o146houca2/GeoDa1.8.15.27-Installer.dmg?dl=0
Windows:
https://www.dropbox.com/s/6gtke9ggeli6jim/GeoDa-1.8.15.27-Windows-64bit.exe?dl=0
Let me know if you need a binary for Linux (what linux and which version).
