### ISSUE TITLE
Crash Report: Create Natural Breaks Map

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#618]
Details:
Open TableFrame.
Open MapFrame.
Check auto update:
In GdaFrame::ChangeToNaturalBreaks(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
In GdaFrame::ChangeToEqualIntervals(4)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Click VariableSettingsDlg::OnOkClick
In GdaFrame::ChangeToEqualIntervals(3)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
In GdaFrame::ChangeToEqualIntervals(4)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
Click GdaFrame::OnCloseProjectEvt
In TableFrame::OnClose and actually closing.
Click GdaFrame::OnNewProject
Open TableFrame.
Open MapFrame.
In TableFrame::OnActivate
In GdaFrame::ChangeToEqualIntervals(4)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
IMDscore
In TableFrame::OnActivate
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
IMDscore
Open HistogramFrame.
In HistogramFrame::OnActivate()
In TableFrame::OnActivate
In TableFrame::OnActivate
Click GdaFrame::OnToolsWeightsManager
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
Click CreatingWeightDlg::OnIdVariableSelected
selected:0
Click CreatingWeightDlg::OnCreateNewIdClick
Try to insert unique id (integer, POLY_ID) column in table.
Click CreatingWeightDlg::OnCRadioQueenSelected
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/home/cdrc-j/R work/Confident Spatial Analysis/manchester_LSOA_IMD.gal
In HistogramFrame::OnActivate()
Open ConnectivityHistFrame
ConnectivityHistFrame::OnActivate
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
IMDscore
VariableSettingsDlg::GetWeightsId() weight: manchester_LSOA_IMD
VariableSettingsDlg::GetWeightsId() weight: manchester_LSOA_IMD
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
IMDscore
VariableSettingsDlg::GetWeightsId() weight: manchester_LSOA_IMD
VariableSettingsDlg::GetWeightsId() weight: manchester_LSOA_IMD
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
IMDscore
VariableSettingsDlg::GetWeightsId() weight: manchester_LSOA_IMD
VariableSettingsDlg::GetWeightsId() weight: manchester_LSOA_IMD
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
IMDscore
VariableSettingsDlg::GetWeightsId() weight: manchester_LSOA_IMD
VariableSettingsDlg::GetWeightsId() weight: manchester_LSOA_IMD
In GdaFrame::OnSaveLisa()
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
Click CreatingWeightDlg::OnCThresholdTextEdit:
0.0
In TableFrame::OnActivate
Click GdaFrame::OnSaveProject
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
Click GdaFrame::OnCloseProjectEvt
Close CreatingWeightDlg
In TableFrame::OnClose and actually closing.
Click GdaFrame::OnNewProject
Open TableFrame.
Open MapFrame.
In GdaFrame::ChangeToNaturalBreaks(4)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
IMDscore

**Comment by lixun910** [comment]
Thanks for reporting this!  This issue (as well as #617  #615 #614 #613 #612 #611 #610 #609 #608 #607 #606 #605 #604 #603) has been fixed in latest GeoDa (internal build 1.8.15.27). You can download the latest GeoDa at:

Mac:
https://www.dropbox.com/s/8ld19o146houca2/GeoDa1.8.15.27-Installer.dmg?dl=0

Windows:
https://www.dropbox.com/s/6gtke9ggeli6jim/GeoDa-1.8.15.27-Windows-64bit.exe?dl=0

Let me know if you need a binary for Linux (what linux and which version).

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.27
Confirmed fix on Mac OSX.
