### ISSUE TITLE
Show Cores+Neighbors and Select All Cores+Neighbors differ

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#621]
Show Cores+Neighbors:

<img width="598" alt="screen shot 2017-02-15 at 9 58 33 pm" src="https://cloud.githubusercontent.com/assets/13679743/23006922/6356abd0-f3ca-11e6-9be6-bc9c717454a8.png">

and Select All Cores+Neighbors differ but they should be the same:

<img width="603" alt="screen shot 2017-02-15 at 9 58 23 pm" src="https://cloud.githubusercontent.com/assets/13679743/23006926/69873902-f3ca-11e6-8ee3-f3372a91e82b.png">

Select All Cores+Neighbors is correct, Show .. isn't -- it looks like when you already have observations selected it adds neighbors to those?

Also, the difference btw show and select is that show actually shows the neighbors in the same color as the neighbors, not just select them. We can remove this option for the next release if it's complicated.

**Comment by lixun910** [comment]
"Select All ->Cores+Neighbors" is different than "Select cores and neighbors", which works as you described "it looks like when you already have observations selected it adds neighbors to those"

"Select cores and neighbors" is for current highlighted observation, e.g:
one select&highlight one area:
<img width="418" alt="screen shot 2017-02-24 at 11 13 44 am" src="https://cloud.githubusercontent.com/assets/2423887/23313297/c1f5a0c4-fa82-11e6-82cd-84214f2a11bc.png">
use menu "select cores and neighbors", one can get the following result
<img width="425" alt="screen shot 2017-02-24 at 11 13 57 am" src="https://cloud.githubusercontent.com/assets/2423887/23313321/dc92b71e-fa82-11e6-80e6-d0213535bf4d.png">

"Select All ->Cores+Neighbors" means "show all cores plus their neighbors" in the map -- no matter what current selection is:
<img width="419" alt="screen shot 2017-02-24 at 11 14 17 am" src="https://cloud.githubusercontent.com/assets/2423887/23313361/ff278890-fa82-11e6-902f-4ddbf10d3c58.png">

This is related to "Select All -> cores"   :
<img width="418" alt="screen shot 2017-02-24 at 11 19 07 am" src="https://cloud.githubusercontent.com/assets/2423887/23313392/19caad44-fa83-11e6-824c-51df1f0bca2a.png">

and "Select All -> neighbors of cores:
<img width="414" alt="screen shot 2017-02-24 at 11 19 44 am" src="https://cloud.githubusercontent.com/assets/2423887/23313405/2ddde4ae-fa83-11e6-8f5f-44f958e588f3.png">

The feature "actually shows the neighbors in the same color as the neighbors" is the same with issue https://github.com/GeoDaCenter/geoda/issues/580 . We can leave this feature in next release.

**Comment by lixun910** [comment]
@jkoschinsky not sure if this has been addressed by the newly designed connectivity map

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.191 (macOS Mojave, 10.14.1). Jan. 16 build.

The changes have been recorded in the test here #580

Compared to version 1.12.1.143, the current version has at least two changes:

1. Boundary colors: Clearer than the previous version.
1.1. When connectivity is ON, selected are shown in Red boundaries and neighbors are in Black;

<img width="600" alt="neighbors conne" src="https://user-images.githubusercontent.com/45187310/51418669-85ede100-1b4a-11e9-8eb5-e4a0cb807544.png">
----


1.2 When connectivity is OFF, selected are shown in Grey boundaries.

<img width="600" alt="neighbors" src="https://user-images.githubusercontent.com/45187310/51418688-97cf8400-1b4a-11e9-896a-04c01939e6e4.png">

2. Better resolution.

**Comment by lixun910** [comment]
@Ashitacarl Thanks! I am not sure if this is what Julia wants.
@jkoschinsky I can't remember what's the main purpose of this issue. Can you clarify it again? Thanks!
