### ISSUE TITLE
add geojson url option in Connect datasource dialog

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#629]
Allow user to connect to online geojson datasource:

<img width="1003" alt="screen shot 2017-02-25 at 6 25 19 pm" src="https://cloud.githubusercontent.com/assets/2423887/23336004/e0e179da-fb87-11e6-9f3b-38c1e1e1ef5c.png">

**Comment by YidanJ-Wu** [comment]
GeoDa 1.8.15.29
Windows 8 
The button to select "GeoJson URL" as an option is not showing up.

![image](https://cloud.githubusercontent.com/assets/22801047/23344493/0defca2e-fc43-11e6-92e0-dae1ebdbfaf5.png)

**Comment by YidanJ-Wu** [comment]
Here is the uncropped screenshot: 
![image](https://cloud.githubusercontent.com/assets/22801047/23344508/61f42746-fc43-11e6-954f-95b4d93d3f7e.png)

**Comment by lixun910** [comment]
This should be in 1.8.15.31 and I only have a Mac installer now. Will give you a windows installer soon.

**Comment by YidanJ-Wu** [comment]
GeoDa 1.8.15.31
Windows 8
Confirmed
