### ISSUE TITLE
add quality map print-out for publication purpose

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#630]
For opened map, when click "Save Image As", there will be two options: SVG and Postscript
Both are for quality map print out, the legend is also printed out. For example:
[OGRGeoJSONMapFrame.ps.zip](https://github.com/GeoDaCenter/geoda/files/801713/OGRGeoJSONMapFrame.ps.zip)

<img width="465" alt="screen shot 2017-02-25 at 9 50 04 pm" src="https://cloud.githubusercontent.com/assets/2423887/23336953/647215f4-fba4-11e6-89df-df106da8be5a.png">

**Comment by lixun910** [comment]
this will be in 1.8.15.31

**Comment by YidanJ-Wu** [comment]
GeoDa 1.8.15.31
Windows 8 
Confirmed

**Comment by jkoschinsky** [comment]
remove file name etc. from top of legend (so it only reads LISA Cluster Map) since long file names end up being displayed on top of the basemap.

**Comment by lixun910** [comment]
fixed in latest version. please verify. thanks

**Comment by YidanJ-Wu** [comment]
GeoDa 1.8.16 - Windows 8
Confirmed
