### ISSUE TITLE
Crash Report: Export png crash on windows

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#631]
Details:
vs: 1-8-15-29
Open TableFrame.
Open MapFrame.
Check auto update:
In GdaFrame::OnHelpAbout()
Error: XRC error: 784: unknown style flag 'wxALIGN_CENTRE'
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
hr60
Open MapFrame.
Open ExportDataDlg in its Init()
Click GdaFrame::OnSaveCanvasImageAs

**Comment by YidanJ-Wu** [comment]
Geoda 1.8.15.29
Windows 8 
Here is the screenshot of the crash: 

![geoda issue 0](https://cloud.githubusercontent.com/assets/22801047/23344467/943fb61c-fc42-11e6-9bfb-d56ddede61ca.png)

**Comment by lixun910** [comment]
Thank you, Julie! I just put a 1.8.15.31 binary for windows in dropbox. please verify this issue using 1.8.15.31.

let me know any issues.

**Comment by YidanJ-Wu** [comment]
GeoDa 1.8.15.31 
Windows 8
Confirmed
