### ISSUE TITLE
1.8.14 when save differential moran results on windows

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#632]
A user from China report a crash when save differential moran results using windows

![qq 20170226152120](https://cloud.githubusercontent.com/assets/2423887/23367484/08ec1608-fcd0-11e6-8e01-db13a97d4c03.png)

**Comment by lixun910** [comment]
This has been fixed in 1.8.15.xx new release

**Comment by YidanJ-Wu** [comment]
GeoDa 1.8.15.31 - Windows 8 
Confirmed
