### ISSUE TITLE
Crash postgres connection on Ubuntu

### ISSUE THREAD

**Issue by Jano121** [GeoDaCenter/geoda#633]
I'm trying to connect a Postgres/Postgis db, but it doesn't work. I don't know if its because my database size. Im using GeoDa 1.8.12 on Ubuntu 16.04 LTS and postgres 9.5.6. Is this a bug or problem with my database? 
UPDATE: It works fine on windows 10 with geoda 1.8.14

**Comment by lixun910** [comment]
@Jano121 Thanks for reporting this bug/issue!  We have an internal version 1.8.16 for Ubuntu 16.04 https://www.dropbox.com/s/85cu3jazxd5kvbe/GeoDa-1.8.6-Ubuntu16.04-64bit.deb?dl=0

Can you try this new version to see if the issue/bug has been fixed? Thanks!

**Comment by Jano121** [comment]
@lixun910 Thanks! I finally make it work!
