### ISSUE TITLE
Report Bug can't work on auto-upgraded GeoDa

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#644]
This is an issue on all auto-upgraded GeoDa (version 1.8.16).
The reason is the cache.sqlite (which is for GeoDa configuration, contains Github access key, has not been updated).

This will be delivered as a patch at 1.8.16.4 for all platforms.

**Comment by luluzhou766** [comment]
Win 10, 64bit
Geoda 1.12.1.131

Unable to send out the bug report. 

![01](https://user-images.githubusercontent.com/36253697/39614646-07320dc2-4fa4-11e8-8d4e-918f842d3aeb.PNG)

**Comment by jkoschinsky** [comment]
@bsalas11 @lixun910: is this still an issue or close?

**Comment by lixun910** [comment]
This will be fixed when releasing GeoDa 1.14. You can close it now. Thanks!
