### ISSUE TITLE
Crash Report: OnSpatialRate

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#664]
Details:
os: 2-6-1
vs: 1-8-16-4
Check auto update:
Open TableFrame.
Open MapFrame.
Open RegressionDlg.
Error: XRC error: 6104: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 6189: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 6198: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 6207: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 6214: both 'wxALIGN_CENTRE_VERTICAL' (as part of wxALIGN_CENTER) and 'wxALIGN_CENTRE_VERTICAL' specify vertical alignment and can't be used together
Warning: iCCP: known incorrect sRGB profile
Warning: iCCP: known incorrect sRGB profile
Error: XRC error: 6223: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
In GdaFrame::OnOpenEmpiricalBayes()
Open VariableSettingsDlg
Error: XRC error: 1577: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1583: horizontal alignment flag 'wxALIGN_CENTRE_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1601: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1607: horizontal alignment flag 'wxALIGN_CENTRE_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1615: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1662: horizontal alignment flag 'wxALIGN_CENTER_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1672: horizontal alignment flag 'wxALIGN_CENTER_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick
In GdaFrame::OnRawrate()
Open VariableSettingsDlg
Error: XRC error: 1577: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1583: horizontal alignment flag 'wxALIGN_CENTRE_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1601: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1607: horizontal alignment flag 'wxALIGN_CENTRE_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1615: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1662: horizontal alignment flag 'wxALIGN_CENTER_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1672: horizontal alignment flag 'wxALIGN_CENTER_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick
Click GdaFrame::OnCloseProjectEvt
In TableFrame::OnClose and actually closing.
Click GdaFrame::OnNewProject
Open TableFrame.
Open MapFrame.
In TableFrame::OnActivate
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
hr60
Open MapFrame.
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick
In GdaFrame::OnRawrate()
Open VariableSettingsDlg
Error: XRC error: 1577: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1583: horizontal alignment flag 'wxALIGN_CENTRE_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1601: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1607: horizontal alignment flag 'wxALIGN_CENTRE_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1615: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1662: horizontal alignment flag 'wxALIGN_CENTER_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1672: horizontal alignment flag 'wxALIGN_CENTER_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
hc60
po60
In GdaFrame::OnSpatialRate()
Open VariableSettingsDlg
Error: XRC error: 1121: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.
