### ISSUE TITLE
Overlay of two univariate local cluster maps

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#665]
Luc and I were talking about adding a map that overlays the results of two univariate local cluster maps. Many people are looking for this but and will think the multivariate cluster maps are like the overlays when they are not. So this will be useful for pointing people to a bivariate overlay and for explaining the difference with the multivariate cluster maps.

This is how the overlay map would work:
1. Run a local cluster map for one variable like usual (any type: local Moran, diff local Moran, local G)
2. Same as 1. for another variable (same cluster type)
3. Create a 3rd map of the same type as 1+2 with 4 colors:

A. high-high overlay
B. low-low overlay
C. high-low overlay (for local Moran)
D. low-high overlay (for local Moran)

The colors could be the same as for the local Moran but darker (e.g. darker red and blue) to differentiate them from the local Moran colors.

A would be an area that is high-high in both 1 and 2.
B low low in 1+2.
etc.

When 1 or 2 are updated in terms of permutations or p-values, 3 would update. Not sure if it makes sense to group 1-3 as one separate view or have it as a right-click option in the current ones?

**Comment by lixun910** [comment]
Is this for the feature co-location map?

**Comment by lanselin** [comment]
I believe this has indeed been implemented in the co-location map since that has options for the
coloring schemes for all local cluster maps.
