### ISSUE TITLE
Crash Report: Open Spatial Empirical Bayes Map (crime)

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#672]
Details:
os: 2-10-0
vs: 1-8-16-4
Check auto update:
Open TableFrame.
Open MapFrame.
In TableFrame::OnActivate
Open MergeTableDlg.
Error: XRC error: 1604: horizontal alignment flag 'wxALIGN_CENTER_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1616: horizontal alignment flag 'wxALIGN_CENTER_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1800: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Click GdaFrame::OnToolsWeightsManager
Open Themeless Map (OnOpenThemelessMap).
Open MapFrame.
Click GdaFrame::OnLegendBackgroundColor
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
crime
Open MapFrame.
In GdaFrame::OnOpenHinge15()
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
crime
Open MapFrame.
In GdaFrame::OpenNaturalBreaks(5)
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
crime
Open MapFrame.
In GdaFrame::OnOpenHinge15()
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
crime
Open MapFrame.
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
crime
Open BoxPlotCanvas.
In GdaFrame::OnOpenHinge30()
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
crime
Open MapFrame.
Close BoxPlotCanvas.
Open VariableSettingsDlg
Error: XRC error: 1923: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1932: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1939: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick
In GdaFrame::OnOpenSpatialEmpiricalBayes()
Open VariableSettingsDlg
Error: XRC error: 1121: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
Open MapFrame.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.
