### ISSUE TITLE
Crash Report: On Open SpatialRate

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#674]
Details:
os: 2-6-1
vs: 1-8-16-4
Check auto update:
Open TableFrame.
Open MapFrame.
Open RegressionDlg.
Error: XRC error: 6104: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 6189: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 6198: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 6207: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 6214: both 'wxALIGN_CENTRE_VERTICAL' (as part of wxALIGN_CENTER) and 'wxALIGN_CENTRE_VERTICAL' specify vertical alignment and can't be used together
Warning: iCCP: known incorrect sRGB profile
Warning: iCCP: known incorrect sRGB profile
Error: XRC error: 6223: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click RegressionDlg::OnCWeightCheckClick
Click RegressionDlg::OnPredValCbClick
Click RegressionDlg::OnCoefVarMatrixCbClick
Click RegressionDlg::OnCWeightCheckClick
Click RegressionDlg::OnRunClick
y:x
x:
y
Open RegressionReportDlg.
In RegressionReportDlg::OnClose()
Close RegressionDlg.
Click RegressionDlg::OnRunClick
y:x
x:
y
Open RegressionReportDlg.
In RegressionReportDlg::OnSaveToFile()
In RegressionReportDlg::OnClose()
Close RegressionDlg.
In GdaFrame::OnCheckUpdates()
In GdaFrame::OnHelpAbout()
Error: XRC error: 784: unknown style flag 'wxALIGN_CENTER'
In GdaFrame::OnStddev()
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
area
In GdaFrame::OnOpenSpatialRate()
Open VariableSettingsDlg
Error: XRC error: 1121: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
Open MapFrame.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.
