### ISSUE TITLE
Crash Report: spatial rates

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#683]
Details:
os: 2-6-1
vs: 1-8-16-4
Check auto update:
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
In TableFrame::OnActivate
Open DataViewerAddColDlg.
Error: XRC error: 1052: vertical alignment flag 'wxALIGN_CENTRE_VERTICAL' has no effect inside a vertical box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1062: horizontal alignment flag 'wxALIGN_CENTER_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1066: horizontal alignment flag 'wxALIGN_CENTER_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnEditDecimals()
In TableFrame::OnActivate
In TableFrame::OnActivate
Open DataViewerAddColDlg.
Error: XRC error: 1052: vertical alignment flag 'wxALIGN_CENTRE_VERTICAL' has no effect inside a vertical box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1062: horizontal alignment flag 'wxALIGN_CENTER_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1066: horizontal alignment flag 'wxALIGN_CENTER_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditDecimals()
Entering DataViewerAddColDlg::OnOkClick
Inserting new column GPSEG2017 into Table
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnLabelLeftClickEvent()
Open DataViewerEditFieldPropertiesDlg
Entering DataViewerEditFieldPropertiesDlg::OnCellChanging
changing row 5, col 6 from  to 2
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In GdaFrame::OpenEqualIntervals(5)
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
GPSEG2017
Open MapFrame.
In TableFrame::OnActivate
Open DataViewerAddColDlg.
Error: XRC error: 1052: vertical alignment flag 'wxALIGN_CENTRE_VERTICAL' has no effect inside a vertical box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1062: horizontal alignment flag 'wxALIGN_CENTER_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1066: horizontal alignment flag 'wxALIGN_CENTER_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnChoiceDisplayedDecimals()
In DataViewerAddColDlg::OnChoiceType()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnEditLength()
Entering DataViewerAddColDlg::OnOkClick
Inserting new column POB2015 into Table
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
Open DataViewerEditFieldPropertiesDlg
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnColMoveEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
Open FieldNewCalcSheetDlg.
Warning: iCCP: known incorrect sRGB profile
Warning: iCCP: known incorrect sRGB profile
Error: XRC error: 5353: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL' (as part of wxALIGN_CENTER)' in a vertical box sizer
Error: XRC error: 5393: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_LEFT'' in a vertical box sizer
Error: XRC error: 5428: 'wxALIGN_CENTER' has no effect when combined with 'wxGROW'
Warning: iCCP: known incorrect sRGB profile
Warning: iCCP: known incorrect sRGB profile
Error: XRC error: 5524: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL' (as part of wxALIGN_CENTER)' in a vertical box sizer
In FieldNewCalcSheetDlg::OnPageChange()
Open DataViewerAddColDlg.
Error: XRC error: 1052: vertical alignment flag 'wxALIGN_CENTRE_VERTICAL' has no effect inside a vertical box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1062: horizontal alignment flag 'wxALIGN_CENTER_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1066: horizontal alignment flag 'wxALIGN_CENTER_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnChoiceDisplayedDecimals()
DataViewerAddColDlg::OnChoiceDisplayedDecimals()
Entering DataViewerAddColDlg::OnOkClick
Inserting new column GPSEPECA into Table
In FieldNewCalcSheetDlg::OnApplyClick()
In FieldNewCalcSheetDlg::OnClose()
In TableFrame::OnActivate
In GdaFrame::OpenEqualIntervals(10)
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
GPSEPECA
Open MapFrame.
In TableFrame::OnActivate
In GdaFrame::OpenEqualIntervals(10)
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
GPSEG2017
Open MapFrame.
In MapFrame::OnMapBasemap()
Click GdaFrame::OnSetBasemap5
In MapFrame::OnMapBasemap()
Click GdaFrame::OnBasemapConfig
Open BasemapConfDlg.
In MapFrame::OnMapBasemap()
Click GdaFrame::OnSetBasemap1
In MapFrame::OnMapBasemap()
Click GdaFrame::OnSetBasemap3
In MapFrame::OnMapBasemap()
Click GdaFrame::OnSetNoBasemap
In GdaFrame::OpenEqualIntervals(3)
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
GPSEG2017
Open MapFrame.
In GdaFrame::OnDisplayMeanCenters()
In GdaFrame::OnDisplayCentroids()
In GdaFrame::OnDisplayMeanCenters()
In GdaFrame::OnDisplayCentroids()
In GdaFrame::OnSaveCategories()
In GdaFrame::OnSpatialRate()
Open VariableSettingsDlg
Error: XRC error: 1121: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.
