### ISSUE TITLE
strange intermediate step when opening map

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#688]
In 1.8.18.7, there is a strange intermediate "flicker" step before the map opens when loading a new data set. This happens both when a sample data set is used and when a shape file is dropped into the data box. Before, the map opened instantaneously, now something seems to happen on the screen beforehand.

**Comment by lixun910** [comment]
Maybe related to the compiler, will give you a new build later. 

Any comments on the tool--data --pca?

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX

Flickering still exists, e.g. when opening Ghana data or any other data from recent.
It's like a small version of the map or thumbnail is displayed for one second on top of the middle of the main GeoDa toolbar before the actual map is opened.

**Comment by lixun910** [comment]
can't replicate on my side. can you capture a screen video to me? thanks!

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.103
Verified

**Comment by jkoschinsky** [comment]
Geoda 107
Mac OSX

The general File IO seems to be resolved. What still persists is flickering when you zoom in and draw the selection square (e.g. to select obs 3085 in the natregimes or ncovr data). When you draw the square, which includes polygons and water, it flickers.

<img width="601" alt="screen shot 2018-03-08 at 5 39 54 pm" src="https://user-images.githubusercontent.com/13679743/37182617-c18cd046-22f7-11e8-97a6-974ffaf479df.png">

**Comment by lixun910** [comment]
@jkoschinsky I can't replicate this on my side

I would spend time on Mapbox's OpenGL rendering system for long-term solution of rendering performance.

**Comment by jkoschinsky** [comment]
yes, the zooming generally isn't very stable
