### ISSUE TITLE
pca - saving results number of pca seems fixed

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#689]
The save results number of components seems to be fixed to the number determined by the algorithm. For example, using the six variables for Guerry suggests four. After changing this number to 2 or 6, the Save Results dialog still gives four options.

**Comment by lanselin** [comment]
reopen, see #711

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.

Fixed, see ticket 711 (https://github.com/GeoDaCenter/geoda/issues/711).
