### ISSUE TITLE
(data needed) Crash Report: when open Csv  file

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#696]
Details:
os: 2-10-0
vs: 1-8-16-4
Check auto update:
Open CsvFieldConfDlg.

**Comment by lixun910** [comment]
can't replicate now, user's csv data will be needed for debugging.

Add more logs in GeoDa to trace detail crash report

**Comment by jkoschinsky** [comment]
Closing since we don't know how to replicate.
