### ISSUE TITLE
PCA variable save doesn't work

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#711]
Saving the PCA as new variables doesn't work. The dialog does not prompt for a variable name (see below).
<img width="199" alt="screen shot 2017-04-05 at 12 34 31 pm" src="https://cloud.githubusercontent.com/assets/4008351/24718612/52cd550e-19fc-11e7-8abb-ecf91c4c6f60.png">

**Comment by lanselin** [comment]
The example above was using the Boston data (points). For the Guerry data there is a similar disconnect between the number of components specified in the dialog (4) and the number of variable names offered (3), see below.

<img width="623" alt="screen shot 2017-04-05 at 12 45 28 pm" src="https://cloud.githubusercontent.com/assets/4008351/24719175/596e0ed8-19fe-11e7-9376-e16f6019a2f6.png">

**Comment by lanselin** [comment]
Still not correct in 1.8.16.11hierarchical. For example, when setting the Max Components to 6 in the previous example, only four Variable names are available.

**Comment by jkoschinsky** [comment]
Can you set the default # of components to the max number of components? Currently the default seems to be set to 3. E.g. see image below: There are 5 components but by default only 3 are shown and saved. You can change 3 to 5 under components but people might overlook this.

<img width="862" alt="screen shot 2017-05-29 at 11 25 09 am" src="https://cloud.githubusercontent.com/assets/13679743/26556709/c0fa7b58-4461-11e7-8a7b-16ecf2d23474.png">

**Comment by lanselin** [comment]
I believe the 3 is based on the 95% rule as the suggested number of components to save.

**Comment by jkoschinsky** [comment]
ok, so we want to keep 3 as the default?

**Comment by lanselin** [comment]
no, it will be different in each case, depending on what the 95% criterion gives.
for example, in the Guerry data example, the suggested value is 5.
that’s the way it’s supposed to work, anyway.

**Comment by jkoschinsky** [comment]
ok, verified, it's relative, so this is all set.
