### ISSUE TITLE
K-means cluster codes

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#712]
The k-means cluster codes start at 0, which makes sense since they are based on C code. However, this is not the most intuitive way to represent the clusters. Better to start at 1.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.

<img width="557" alt="screen shot 2017-05-29 at 11 23 05 am" src="https://cloud.githubusercontent.com/assets/13679743/26556631/36b58a8c-4461-11e7-89d6-7edc73d8c94d.png">
