### ISSUE TITLE
Save unsaved changes warning incorrect

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#724]
When closing a project with new variables in the table, the warning of unsaved changes appears even when the table has previously been saved. After a Save operation has been carried out, there should be no more warning of unsaved changes.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.
