### ISSUE TITLE
PCA variable loadings not available

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#725]
In order to interpret the principal components, the loadings of each variable on each component must be available. As it stands, only the components computed for each observation are available. The loadings should be provided in the results window.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.

<img width="406" alt="screen shot 2017-05-29 at 11 07 45 am" src="https://cloud.githubusercontent.com/assets/13679743/26556247/18944180-445f-11e7-9913-b7728c8734dc.png">
