### ISSUE TITLE
Randomization seed not selected automatically

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#726]
When specifying a seed in the randomization procedure, an extra step is needed to check the "use specified seed" option. This should be automatic once a seed has been specified. As it stands it now requires an extra step. This is easily overlooked so that one thinks that one is using the specified seed, but actually may not be.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.

When you click on Use Specified Seed, window to enter seed value pops up automatically:

<img width="690" alt="screen shot 2017-05-29 at 11 21 35 am" src="https://cloud.githubusercontent.com/assets/13679743/26556608/17afba68-4461-11e7-9c00-e36fccc704ea.png">
