### ISSUE TITLE
Moran scatterplot - needs view option to turn on selection

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#729]
The automatic selection with recompilation of the Moran's I for selected and unselected should not be the default, but should be an option. The Moran scatter plot interface needs a "View" option similar to the standard scatter plot, e.g., View > Regimes regression. The default should be "off".

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.

**Comment by jkoschinsky** [comment]
I just tried differential Moran's I with regime regression turned on: By default, the view is sized too small for the left and right selected/unselected scatterplots to display. You have to resize the view to get them to display but people won't know that that's what they need to do. 

<img width="1097" alt="screen shot 2017-05-29 at 9 09 05 pm" src="https://cloud.githubusercontent.com/assets/13679743/26565724/6a4fbfd2-44b3-11e7-8b15-b98d485b42f6.png">

Let's resize the view so the two smaller plots automatically show after choosing regimes regression:

<img width="947" alt="screen shot 2017-05-29 at 9 09 20 pm" src="https://cloud.githubusercontent.com/assets/13679743/26565725/6d52eb32-44b3-11e7-9651-f99f879ffa66.png">

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.
