### ISSUE TITLE
GeoDa crashes when opening csv file

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#739]
Details:

**Comment by lanselin** [comment]
this is from me. geoda crashed when trying to open a csv file. it can't read the log file (using 1.8.16.11a).
<img width="413" alt="screen shot 2017-04-10 at 6 40 17 pm" src="https://cloud.githubusercontent.com/assets/4008351/24886865/586bf900-1e1d-11e7-84fe-8ea0498bb9b7.png">

**Comment by lanselin** [comment]
this may explain a lot of the empty crash reports.

**Comment by YidanJ-Wu** [comment]
Tried to replicate this in 1.8.16.15 Windows 8 
Did not crash

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified: opened csv file fine.
