### ISSUE TITLE
Crash Report: Map without weights

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#750]
Details:
os: 2-6-3
vs: 1-8-16-4
Check auto update:
In GdaFrame::OnHelpAbout()
Error: XRC error: 784: unknown style flag 'wxALIGN_CENTER'
Open TableFrame.
Open MapFrame.
In GdaFrame::OnSpatialRate()
Open VariableSettingsDlg
Error: XRC error: 1121: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:

**Comment by YidanJ-Wu** [comment]
Geoda 1.8.16.4
Windows 8 

This happened when I opened the columbus crime file and attempted to run spatial rates on it. 
There was an error message that said "no weights files found," then GeoDa crashed. 
Will try again after creating a weights file. 
![image](https://cloud.githubusercontent.com/assets/22801047/25073936/f045d6fe-22b6-11e7-8ac1-a13500a7e4e8.png)

**Comment by lixun910** [comment]
Thank you so much for checking this out!

Xun

**Comment by YidanJ-Wu** [comment]
After creating a weights file, the spatial rates feature works fine (no crash).
![image](https://cloud.githubusercontent.com/assets/22801047/25073992/eb8d4696-22b7-11e7-8612-389512416965.png)

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.
