### ISSUE TITLE
Crash Report: SpatialEmpiricalBayes

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#755]
Details:
os: 2-10-0
vs: 1-8-16-4
Check auto update:
Open TableFrame.
Open MapFrame.
In GdaFrame::OnOpenSpatialEmpiricalBayes()
Open VariableSettingsDlg
Error: XRC error: 1121: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
Open MapFrame.

**Comment by lixun910** [comment]
Should be the same with "spatial rates" bug.

**Comment by YidanJ-Wu** [comment]
1.8.16.29
Windows 8

ran Spatial Empirical Bayes. It crashes if one of the variables is time-grouped but works fine otherwise. 
![image](https://cloud.githubusercontent.com/assets/22801047/26510773/83495692-4224-11e7-834a-1ff566c9a5d2.png)

**Comment by lixun910** [comment]
Thanks for finding this!! 
Fixed in e7a1691eb004219c3bc17fdf6b144cf6124d9abc

Will deliver 1.8.16.31 to you soon.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.
