### ISSUE TITLE
Bivariate mapping theme

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#757]
As part of our discussion of https://github.com/GeoDaCenter/geoda/issues/665, we talked about adding  the option for a bivariate mapping theme, like this:
https://true-cost-collaboratory.carto.com/viz/297a15f8-06ab-11e6-9684-0ecd1babdde5/public_map

to allow people to visualize two variables in one map theme.

**Comment by lanselin** [comment]
That's the old Geovista approach. Has been around for a long time. I don't find it very intuitive.
