### ISSUE TITLE
Missing value and merge problem

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#758]
From user:
My version is 1.8.16.4, March 2017 for Windows 8 64-bit. 

I am first loading a shapefile with only the ID. Then, I merge a csv table with a lot of other data based on the ID as key. The merge seems to work fine, but it seems to be struggling with missing values when the variable is a real number, as far as I can tell. I am sending you a screenshot of the table. GeoDa interprets the variables distNoObst-dist2013 as real numbers. Highlighted there is an observation where dist2012 and dist2013 is missing in the csv file but they are zeros instead in the table in Geoda. On the contrary, fat_2000-fat_2012 are interpreted as string variables when I do the merge, and the missing seem to be correctly reported.

I tried to do the merge of the data and the shapefile on ArcGIS and then import the whole thing in GeoDa but this is giving me the same problem when I convert the data to a shapefile, and it does not seem that in ArcGIS there is a way to fix it either. 

I can modify the csv and substitute the missing with some specific value, whereas now they are simply blank. Is there a value that GeoDa would correctly interpret as missing for real variables?

**Comment by lixun910** [comment]
"I can modify the csv and substitute the missing with some specific value, whereas now they are simply blank."

I think the rule to detect a missing value in  csv file is "if it's empty, then it's a missing value".  In previous GeoDa version (can't handle missing values), the empty will be read as 0, and we say it's not correct because it should be missing value.

To my understanding, we should not revert it back to "read empty as 0". Correct me if I was wrong.

**Comment by lanselin** [comment]
No, we should stick with the current policy, but if you look closely at the screen shot, some of the missing values were turned into 0 and they should not have been.

"Highlighted there is an observation where dist2012 and dist2013 is missing in the csv file but they are zeros instead in the table in Geoda. On the contrary, fat_2000-fat_2012 are interpreted as string variables when I do the merge, and the missing seem to be correctly reported."

**Comment by YidanJ-Wu** [comment]
GeoDa 1.8.16.15
Windows 8 

I replicated this problem and the missing values in the csv were rendered as blanks, not 0. 
The two right-most columns (DB and Dummy_Var) were from the imported CSV. Merge was keyed to DB and Date_Built
![image](https://cloud.githubusercontent.com/assets/22801047/25367558/f4e6c9a8-293b-11e7-9b0e-d94d6ac7e16b.png)

**Comment by lixun910** [comment]
Thanks, Julie!

This is correct: missing values were read as blanks in 1.8.16.15.

Previous versions read missing values as 0 when do merge.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified: Missing values left blank after merge:

<img width="523" alt="screen shot 2017-05-29 at 2 19 06 pm" src="https://cloud.githubusercontent.com/assets/13679743/26560144/dac161e2-4479-11e7-8506-abcc59fd1ec8.png">
