### ISSUE TITLE
Space-Time weights connectivity map crashes

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#770]
Confirmed with 1.8.16.15 and 1.8.16.4. After loading a gal file created by the space-time weights saving feature in the time editor, the connectivity histogram works fine, but the connectivity map crashes the program. When selecting the connectivity map, a window opens with blank content (where the map usually appears) and then GeoDa crashes. Also I noticed there is no message about sending a bug report.

Clearly, the space-time weights don't have a matching shape file, but that should not crash the program. Maybe instead there should be a warning, after it is detected that the shape file is not present (or is unknown, hasn't been defined), without crashing the program. The first line of the gal file includes the name of the space-time dbf file where usually the name of the shape file is, so maybe the program looks for a shp/shx combination with the same name, which most likely doesn't exist.

**Comment by lanselin** [comment]
Here's the blank window

<img width="484" alt="screen shot 2017-04-25 at 5 26 22 pm" src="https://cloud.githubusercontent.com/assets/4008351/25410453/7e17bae8-29dc-11e7-9282-d2fb8f521e22.png">

**Comment by lanselin** [comment]
This window stays open for a bit and then the program crashes.

**Comment by lixun910** [comment]
The button “connectivity map” should be disabled if only space-time table (dbf file) and weights are loaded, since there is on map (geometries). This fix will check if geometries present, otherwise “connectivity map” will be disabled. 

When one added geometries (e.g using Tool-Shape-Points From Table), this “connectivity map” button will be enabled.

**Comment by YidanJ-Wu** [comment]
1.8.16.27
Windows 8 

Tried to replicate this. I can't find the option to save as a .gal file. Am I looking in the wrong section? 
![image](https://cloud.githubusercontent.com/assets/22801047/26130068/aa3d3a1c-3a58-11e7-8289-fb8f7f7e5ff6.png)

**Comment by lixun910** [comment]
> On May 16, 2017, at 4:57 PM, YidanJ-Wu <notifications@github.com> wrote:


> There is no specific button for saving only the spacetime weights. It is created when you save space-time variables/table: SaveAs *.gal of a space-time weights is at the "Time editor" dialog (lower right: there is a button). When you click save, choose dbf, and you will see a weights file will be automatically created associated with the dbf.

Then,

**Comment by YidanJ-Wu** [comment]
Hmm. I saved as DBF and a weights file was not automatically created. I just got a .dbf

**Comment by lixun910** [comment]
Here are the steps to get space-time dbf and weights file:

Open datasource: e.g. samples -->US Homicide
Create a weights: queen contiguity weights
Open Time Editor:  create a grouped variable HR using hr60, hr70, hr80
Click  "Save Space-Time Table/Weights"
Save to a dbf file, and you will see a related gal file been created

**Comment by YidanJ-Wu** [comment]
1.8.16.29
Windows 8 

Looks fine so far. I will try another file with added geometries.
![image](https://cloud.githubusercontent.com/assets/22801047/26501992/c968acfa-4200-11e7-97ad-61535a3d3f6b.png)

**Comment by jkoschinsky** [comment]
When I save the space-time table and weights and then try to open it, I get the following error related to the mismatch in N bc of the stacked observations:

<img width="1300" alt="screen shot 2017-05-29 at 2 24 14 pm" src="https://cloud.githubusercontent.com/assets/13679743/26560262/bee2d9dc-447a-11e7-860c-b5d3f609b515.png">

**Comment by lixun910** [comment]
I just replicated this: this message shows up when you didn't close your current project and load the space-time weights directly.  This is what GeoDa supposed to do. 

To use space-time table and weights, you need to close current project, and then "drag-n-drop" saved space-time table (dbf), then load space-time weights.

**Comment by jkoschinsky** [comment]
ok, makes sense. Works with table that has matching N.

GeoDa 1.8.16.33 — Mac OSX
Verified.
