### ISSUE TITLE
PCA GUI

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#788]
reduce 3 options to 2:
1. Method (dropdown: SVD (default) and Eigen)
2. Transformation with dropdown: Raw, Demean, Standardize (default)

Max Components —> Components

—add save option for output

**Comment by jkoschinsky** [comment]
Remove method since we'll drop Eigen. So Transformation is only parameter.

**Comment by YidanJ-Wu** [comment]
GeoDa 1.8.16.27
Windows 8 

Some buttons disappear when the window is resized. 
![image](https://cloud.githubusercontent.com/assets/22801047/26090156/a9c8d36a-39c8-11e7-999c-a5ca558cfc76.png)

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.

**Comment by YidanJ-Wu** [comment]
GeoDa 1.8.16.35 - Windows 8 
Verified
