### ISSUE TITLE
Swap category colors: Only for unique value

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#802]
disable for other maps since those are ordered

**Comment by YidanJ-Wu** [comment]
1.8.16.29
Windows 8 

The feature has not been disabled for other maps. Here's an example of a quantile map with swapped colors: 
![image](https://cloud.githubusercontent.com/assets/22801047/26509604/1611bb8c-421f-11e7-83a6-c7d2326b4f83.png)

**Comment by lixun910** [comment]
Yes, you can change the legend color. But the ticket here is saying one can NO drag-n-drop the legend text to swap colors between two legends.

**Comment by YidanJ-Wu** [comment]
My mistake. Yes, the drag and drop feature is working correctly on the latest version (1.8.16.29)

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.
