### ISSUE TITLE
Add seed and k++ for k-means

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#803]
For k-means:

- Add seed for replicability: set it as global seed across maps
- add k++ (check with Maia): 50-100 initial runs to get better starting point -- allow users to specify # of iterations to run

rename Distance Functions (same for the Hierarchical Clustering Settings):

Distance: 
--Euclidean
--city block

Correlation
--Pearson
--absolute

Cosine:
--signed
--un-signed

Rank 
--Kendall
--Spearman

(also for the Hierarchical Clustering Settings, remove indent of Method: average-linkage)

**Comment by lixun910** [comment]
k-means++ (2007 by Arthur and Vassilvitskii). This algorithm comes with a theoretical guarantee to find a solution that is O(log k) competitive to the optimal k-means solution:
1. Choose one center uniformly at random from among the data points.
2. For each data point x, compute D(x), the distance between x and the nearest center that has already been chosen.
3. Choose one new data point at random as a new center, using a weighted probability distribution where a point x is chosen with probability proportional to D(x)2.
4. Repeat Steps 2 and 3 until k centers have been chosen.

**Comment by YidanJ-Wu** [comment]
1.8.16.29 
Windows 8 
How do I change the Cosine and Rank settings?

**Comment by lixun910** [comment]
Cosine/Rank/Distance/Correlation are types/groups of distance functions ( starts with -- in a tree structure). One should not be able to select any one of them.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.
