### ISSUE TITLE
k-means interface: no way to not choose variables

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#813]
In the K-means interface, after some variables have been selected, and say the geometric mean box is checked, it is no longer possible to not have variables selected and only do the geometric mean. In other words, while it is possible to check and uncheck the geometric means, it is not possible to "un check" (so to speak) the main variable selection. In order to get rid of them, one needs to close the dialog and start it up again. It would be nice if there were a way to uncheck a variable (e.g., double click on it).

**Comment by lixun910** [comment]
On Mac, you can hold "Command" key and then click on the variable list to do "un select".

How about replace current listctrl with one has checkbox?

**Comment by lanselin** [comment]
check box would be a good solution, as long as one can shift click to select a bunch of
variables at a time.

**Comment by lixun910** [comment]
Just checked: the checkbox-listcontrol doesn't support "shift click selection"

**Comment by lanselin** [comment]
I think the shift selection is a must, especially in a multivariate setting where a
lot of variables need to be selected. checking all those boxes individually is a
non-starter. it would be best if there were a key combination to unselect
a selected variable.

**Comment by lixun910** [comment]
Current list control box can do "shift selection” and unselect by holding “Command” key.

Do you want to have “checkbox list control” (since it’s visually better looking) plus “shift selection” ?

**Comment by lanselin** [comment]
as long as command key works on all platforms, i’m fine with that.

**Comment by lixun910** [comment]
This issue (deselect variables in Clustering dialogs) has been fixed since V161.
