### ISSUE TITLE
Crash Report (Regression)

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#816]
Details:
os: 2-10-0
vs: 1-8-16-4
Check auto update:
Open TableFrame.
Open MapFrame.
Open RegressionDlg.
Error: XRC error: 6104: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 6189: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 6198: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 6207: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 6214: both 'wxALIGN_CENTRE_VERTICAL' (as part of wxALIGN_CENTER) and 'wxALIGN_CENTRE_VERTICAL' specify vertical alignment and can't be used together
Warning: iCCP: known incorrect sRGB profile
Warning: iCCP: known incorrect sRGB profile
Error: XRC error: 6223: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click RegressionDlg::OnCWeightCheckClick
Click RegressionDlg::OnCOpenWeightClick
Click GdaFrame::OnToolsWeightsManager
Click RegressionDlg::OnCOpenWeightClick
Click GdaFrame::OnToolsWeightsManager
Click RegressionDlg::OnCRadio2Selected
Click RegressionDlg::OnRunClick
y:crime
x:
inc
neig
Spatial Lag model
Open RegressionReportDlg.
In RegressionReportDlg::OnClose()
Close RegressionDlg.
Click RegressionDlg::OnCWeightCheckClick
Click RegressionDlg::OnRunClick
y:crime
x:
inc
neig

**Comment by YidanJ-Wu** [comment]
GeoDa 1.8.16.25
Windows 8

Ran regression (spatial lag model) on ColumbusCrime with crime as dependent value, "inc" and "neig" as independent values. Weights file included. Did not crash. 
![image](https://cloud.githubusercontent.com/assets/22801047/26029809/fb0bfdea-3803-11e7-894c-254f03985769.png)

**Comment by jkoschinsky** [comment]
the crashes tend to come up with unusual data, e.g. a combination of larger datasets, time-enabled variables, missing values, special characters.

**Comment by YidanJ-Wu** [comment]
1.8.16.27
Windows 8 

Didn't crash, but i got this message 
![image](https://cloud.githubusercontent.com/assets/22801047/26075959/bfbb467c-397c-11e7-8e7c-10e48cf1746c.png)

**Comment by lixun910** [comment]
Thanks, Julie!!!

Crash in regression dialog on windows:  it is caused by 1.
select variable to independent variable list and 2. remove the
independent variable. The program will prompt error message dialog,
because the code is trying to activate not-existing item in the
wxListbox (Covariates). It one clicks Yes, the program will crash.

This bug has been there since version 1.6.x (and earlier). It has been activated because of upgrading of wxWidgets to version 3.1, which is very restrict on operations of wxListBox.

**Comment by lixun910** [comment]
fix in b44a5d64aaa2f016fea2ec62bafdf84d4f3b55aa

**Comment by YidanJ-Wu** [comment]
1.8.16.29
Windows 8
Confirmed fixed

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.
