### ISSUE TITLE
WFS file won't load

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#822]
Version 1.8.16.25
Windows 8 

This is the WFS URL that I used http://gstore.unm.edu/apps/rgis/datasets/7bbe8af5-029b-4adf-b06c-134f0dd57226/services/ogc/wfs?SERVICE=wfs&REQUEST=GetCapabilities&VERSION=1.0.0

![image](https://cloud.githubusercontent.com/assets/22801047/26030747/9aeb5618-3821-11e7-80ce-129189defdb2.png)

![image](https://cloud.githubusercontent.com/assets/22801047/26030753/ae5fb496-3821-11e7-8078-4d6888cc5c39.png)

**Comment by lixun910** [comment]
when you  open this url in a browser,  it has no features. I think GeoDa reports it "Datasource is empty" is correct
