### ISSUE TITLE
Local Geary: Crash Report

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#825]
Details:
os: 1-10-10
vs: 1-8-16-25
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
In GdaFrame::OnHelpAbout()
/Users/Julia/Box Sync/Julia/CSDS/Data/SSI_Welfare Data Sandy Wong/2010/contig2010_var2010.shp
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:/Users/Julia/Box Sync/Julia/CSDS/Data/SSI_Welfare Data Sandy Wong/2010/contig2010_var2010.shp
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::AddTimeVariantOptionsToMenu()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
In TableFrame::OnActivate
Click GdaFrame::OnSaveProject
Entering Project::SaveDataSourceData
Exiting Project::SaveDataSourceData
Entering Project::SaveProjectConf
Exiting Project::SaveProjectConf
In TableFrame::OnActivate
Entering GdaFrame::OnMapChoices
In GdaFrame::OnOpenHinge15()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
diff_2016
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::AddTimeVariantOptionsToMenu()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
diff_2016
SSI10
Open ScatterNewPlotFrame.
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
SSI10
diff_2016
Open ScatterNewPlotFrame.
Entering GdaFrame::OnMapChoices
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
LQ10
diff_2016
Open ScatterNewPlotFrame.
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
selected:1
Click CreatingWeightDlg::OnCRadioQueenSelected
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/Users/Julia/Box Sync/Julia/CSDS/Data/SSI_Welfare Data Sandy Wong/2010/contig2010_var2010q.gal
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnActivate
WeightsManFrame::OnHistogramBtn()
Open ConnectivityHistFrame
In WeightsManFrame::OnActivate
ConnectivityHistFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Close CreatingWeightDlg
Open GetisOrdMapFrame (OnOpenGetisOrd).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
LQ10
VariableSettingsDlg::GetWeightsId() weight: contig2010_var2010q
VariableSettingsDlg::GetWeightsId() weight: contig2010_var2010q
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::GetNameWithTime()
MapCanvas::AddTimeVariantOptionsToMenu()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::AddTimeVariantOptionsToMenu()
In GdaFrame::OnShowAsConditionalMap()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
diff_2016
diff_2012
MapCanvas::GetNameWithTime()
Open ConditionalNewFrame.
In ConditionalClusterMapFrame::OnActivate()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
In ConditionalClusterMapFrame::OnActivate()
MapCanvas::AddTimeVariantOptionsToMenu()
Open LocalGearyFrame (OnOpenUniLocalGeary).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
Open LocalGearyFrame (OnOpenMultiLocalGeary).
Open MultiVariableSettingsDlg.
Click MultiVariableSettingsDlg::OnOK
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::AddTimeVariantOptionsToMenu()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()

**Comment by jkoschinsky** [comment]
This might be the same local Geary bug related to time-enabled variables although I didn't use any of the time-grouped variables (but may be their presence in the data caused the crash). If you can send me a build with th elocal Geary bug fix, I'll test again. thx!

**Comment by YidanJ-Wu** [comment]
1.8.16.29
Windows 8

I ran local Geary on a time-enabled variable, Pov(2010). Did not crash.  
![image](https://cloud.githubusercontent.com/assets/22801047/26503172/4b7a78e6-4205-11e7-8880-181825722804.png)

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.
