### ISSUE TITLE
Crash Report:  Time movie on (changed) time grouped variable

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#827]
Details:
os: 1-10-10
vs: 1-8-16-25
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
/Users/Julia/Box Sync/Julia/CSDS/Data/SSI_Welfare Data Sandy Wong/cleaned shapefile/contig2010/contig2010_var2010.shp
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:/Users/Julia/Box Sync/Julia/CSDS/Data/SSI_Welfare Data Sandy Wong/cleaned shapefile/contig2010/contig2010_var2010.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::AddTimeVariantOptionsToMenu()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
In GdaFrame::OnHelpAbout()
In GdaFrame::OnCheckTestMode():yes
In GdaFrame::OnCheckUpdates()
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
Entering Project::SaveProjectConf
Exiting Project::SaveProjectConf
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
MapCanvas::~MapCanvas()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/Julia/Box Sync/Julia/CSDS/Data/Marynia Food Access/Chi-SDOH/Chi-SDOH.shp
Open Layer:Chi-SDOH
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:/Users/Julia/Box Sync/Julia/CSDS/Data/Marynia Food Access/Chi-SDOH/Chi-SDOH.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::AddTimeVariantOptionsToMenu()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Open LocalGearyFrame (OnOpenMultiLocalGeary).
Open MultiVariableSettingsDlg.
Click MultiVariableSettingsDlg::OnOK
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::AddTimeVariantOptionsToMenu()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
Open LocalGearyFrame (OnOpenUniLocalGeary).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
MEANMI_14
VariableSettingsDlg::GetWeightsId() weight: Chi-SDOH_rook
VariableSettingsDlg::GetWeightsId() weight: Chi-SDOH_rook
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::GetNameWithTime()
MapCanvas::AddTimeVariantOptionsToMenu()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
MapCanvas::GetNameWithTime()
In TableFrame::OnActivate
In TableFrame::OnActivate
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
Entering Project::SaveProjectConf
Project::GetProjectFullPath()
In Project::UpdateProjectConf
Exiting Project::SaveProjectConf
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/Julia/Box Sync/Julia/CSDS/Data/SSI_Welfare Data Sandy Wong/cleaned shapefile/contig2010/contig2010_var2010.shp
Open Layer:contig2010_var2010
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:/Users/Julia/Box Sync/Julia/CSDS/Data/SSI_Welfare Data Sandy Wong/cleaned shapefile/contig2010/contig2010_var2010.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::AddTimeVariantOptionsToMenu()
Entering GdaFrame::OnMapChoices
In GdaFrame::OnOpenHinge15()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
LQ10
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::AddTimeVariantOptionsToMenu()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
Open TimeChooserDlg.
Open VarGroupingEditorDlg.
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListEdit
In VarGroupingEditorDlg::OnIncludeListEditEnd
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListEdit
In VarGroupingEditorDlg::OnIncludeListEditEnd
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnCreateGrpClick
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
MapCanvas::~MapCanvas()
Entering GdaFrame::OnMapChoices
In GdaFrame::OnOpenHinge15()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
LQ
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::AddTimeVariantOptionsToMenu()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::OnPlayPauseButton
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::OnPlayPauseButton
In TimeChooserDlg::OnPlayPauseButton
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::OnPlayPauseButton
In TimeChooserDlg::OnPlayPauseButton
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::OnPlayPauseButton
In TimeChooserDlg::OnPlayPauseButton
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
In TimeChooserDlg::ChangeTime
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::TimeChange()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()
MapCanvas::GetCanvasTitle()
MapCanvas::GetCanvasTitle()
MapCanvas::GetNameWithTime()

**Comment by jkoschinsky** [comment]
This was me:
GeoDa 1.8.16.25 — Mac OSX

Steps:
1. SSI data
2. time group LQ
3. create boxmap of time-grouped variables
4. run time movie
5. select upper outlier, hit pause, back to map, re-select

crash

**Comment by jkoschinsky** [comment]
Replicable crash (just keep going back and forth btw time player and map selection).
Persists in GeoDa 1.8.16.27 — Mac OSX.
Note that there's one undefined value in one of the years.

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.

**Comment by YidanJ-Wu** [comment]
GeoDa 1.8.16.33 
Windows 8
Verified
