### ISSUE TITLE
Add undefined option to selection tool's value assignment

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#828]
Right now, the "assign value" option at the bottom of the selection tool requires a number. In the case below, I want to recode -1 (often also coded as -99) as undefined. Would be good to add this as an option (can be done later, just waned to log this):

<img width="673" alt="screen shot 2017-05-14 at 10 43 20 pm" src="https://cloud.githubusercontent.com/assets/13679743/26041975/f14e80fe-38f6-11e7-86ea-d79f56992821.png">

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.

**Comment by jkoschinsky** [comment]
noticed small typo at bottom of Selection Tool:

(Leave empty as undefined values) --> (Leave empty for undefined values)

<img width="718" alt="screen shot 2017-05-31 at 8 32 57 am" src="https://cloud.githubusercontent.com/assets/13679743/26634292/c6df3cea-45db-11e7-8ea1-c99299dcfa81.png">

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.103
Verified 

<img width="780" alt="7 mar 06" src="https://user-images.githubusercontent.com/36253697/37114897-814998e0-2241-11e8-9678-e50cb0c52d13.PNG">

**Comment by jkoschinsky** [comment]
GeoDa 107
OSX
verified
