### ISSUE TITLE
Crash Report (change table field types)

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#841]
Details:
os: 2-10-0
vs: 1-8-16-4
Check auto update:
In TableFrame::OnActivate
Click GdaFrame::OnToolsWeightsManager
Open LisaScatterPlotFrame (OnOpenMSPL).
Open VariableSettingsDlg

Click VariableSettingsDlg::OnOkClick:
Tasa_alfab
VariableSettingsDlg::GetWeightsId() weight: anafinal
VariableSettingsDlg::GetWeightsId() weight: anafinal
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg

Click VariableSettingsDlg::OnOkClick
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg

Click VariableSettingsDlg::OnOkClick:
Tasa_alfab
VariableSettingsDlg::GetWeightsId() weight: anafinal
VariableSettingsDlg::GetWeightsId() weight: anafinal
Click GdaFrame::OnCopyImageToClipboard
In TableFrame::OnActivate
Open DataViewerEditFieldPropertiesDlg
In DataViewerEditFieldPropertiesDlg::OnGridComboBox
1
Entering DataViewerEditFieldPropertiesDlg::OnFieldSelected
Entering DataViewerEditFieldPropertiesDlg::OnCellChanging
changing row 13, col 1 from real to integer
In TableFrame::OnActivate
Open DataViewerEditFieldPropertiesDlg
In DataViewerEditFieldPropertiesDlg::OnGridComboBox
2
Entering DataViewerEditFieldPropertiesDlg::OnFieldSelected
Entering DataViewerEditFieldPropertiesDlg::OnCellChanging
changing row 13, col 1 from integer to string
In TableFrame::OnActivate
Click GdaFrame::OnCloseProjectEvt

**Comment by VeraB620** [comment]
OS X El Capitan 10.11.6
GeoDa 1.12.1.137
Changing field types works, 
<img width="169" alt="screen shot 2018-06-26 at 9 08 08 am" src="https://user-images.githubusercontent.com/4943475/41918058-2c196ef4-7921-11e8-8548-95b45eca3c6b.png">
<img width="237" alt="screen shot 2018-06-26 at 9 08 01 am" src="https://user-images.githubusercontent.com/4943475/41918059-2d25367a-7921-11e8-900d-df876036babd.png">
<img width="90" alt="screen shot 2018-06-26 at 9 08 15 am" src="https://user-images.githubusercontent.com/4943475/41918062-2e4b2ffa-7921-11e8-8dab-ca1ca1cd8d00.png">
