### ISSUE TITLE
Crash Report (when minimize the map window)

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#864]
Details:

**Comment by jkoschinsky** [comment]
This was my crash -- it's good that it's replicable.
not sure why there are no details. GeoDa 1.8.16.31 Mac OSX.

Here's a screenshot of the views + error before the crash:

[image: Inline images 1]

and afterwards:

[image: Inline images 2]

How to replicate (Chicago data):
1. group variables (like meanmi)
2. open the grouped variables in averages chart
2. open unique values map and make selection
3. drag bottom of unique values view to top so you can only see the toolbar
(I did this by accident!)
--> replicable crash

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.

<img width="1313" alt="screen shot 2017-05-28 at 9 13 29 pm" src="https://cloud.githubusercontent.com/assets/13679743/26534508/89932aba-43ea-11e7-8a95-aa2ec4260b45.png">
