### ISSUE TITLE
slight lag in brushing and linking with lots of open views

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#868]
GeoDa 1.8.16.33 — Mac OSX
Verified.

I have all of the views below open and there's a slight lag in linking and brushing (was using map movie and time player at the same time). Not sure if it's just too many views or if something got goofed up in memory.

<img width="1699" alt="screen shot 2017-05-28 at 9 19 33 pm" src="https://cloud.githubusercontent.com/assets/13679743/26534593/8ded99fa-43eb-11e7-9967-a17cce0cc157.png">

**Comment by lixun910** [comment]
The slight lag is caused the new design (a hack) with transparency support ( has sacrifice the performance a little bit but better than native transparency performance). You will get better performance when switch to "yellow cross-hatch highlighting" on maps (but the plots will not). Let me know if there is still a performance issue.

**Comment by jkoschinsky** [comment]
I just tested this: The same lag persists even with the yellow hatching if you switch to yellow hatching after using transparency. However, if you close the project and start from scratch with yellow hatching from the beginning, the lag disappears (in conditional map, transparency remains even when yellow hatching is selected so there might be some remaining lag due to that).

**Comment by lixun910** [comment]
Yes, the conditional map is a kind of plot (not really map with basemap support), so it shares the same code with other plots. I will leave this ticket open to see if there is any solutions for better performance.

**Comment by luluzhou766** [comment]
Win 10, 64bit
Geoda 1.12.1.131
Verified

I didnot experience lag in linking and brushing. The yellow cross-hatching was not active at the first picture. It is activated later.
 
![01](https://user-images.githubusercontent.com/36253697/39614498-ef25bb1c-4fa2-11e8-8b57-30c1048ee8f8.PNG)

![02](https://user-images.githubusercontent.com/36253697/39614501-f44801fe-4fa2-11e8-9865-c4e9de024de9.PNG)
