### ISSUE TITLE
Recent does not include data sets loaded with gda

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#873]
I just noticed that when a data set is loaded using the project file (drag and drop gda file), that data set is not included in the Recent list. When loading a shape file (not the project file), it is included. This limits the use of the project file, e.g., the "Recent" should remember the weights files and variable groupings.

**Comment by lanselin** [comment]
Correction, it's a little more subtle than that. The file is listed in Recent, but there is no preview. After the file is opened once more, then the preview appears - see screen shots below, before and after loading the Chicago data a second time. First, there is only the file name, without a preview, after loading the file, the preview appears.

<img width="405" alt="screen shot 2017-05-30 at 2 21 22 pm" src="https://cloud.githubusercontent.com/assets/4008351/26600922/7f008b60-4543-11e7-8247-8fa1b36e9138.png">
<img width="420" alt="screen shot 2017-05-30 at 2 21 40 pm" src="https://cloud.githubusercontent.com/assets/4008351/26600923/7f100c8e-4543-11e7-981f-70916b07c541.png">

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.
