### ISSUE TITLE
Local cluster maps - number of observations per class does not adjust

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#874]
I noticed that when the significance filter is adjusted, the number of observations in each category (e.g., high-high, low-low) in the legend does not adjust. So it no longer corresponds to the actual number of highlighted polygons in the map. See attached screen shot for a p value of 0.001.

<img width="578" alt="screen shot 2017-05-30 at 6 59 05 pm" src="https://cloud.githubusercontent.com/assets/4008351/26609951/2c4400a6-456a-11e7-85d8-824ca84a799b.png">

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.
