### ISSUE TITLE
Add variable problem

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#876]
GeoDa 1.8.16.4 - Windows
Data: Scotlip
Steps: Trying to add new variable: rates
Problem: Won't allow you to save variable (name field red and OK button inactive)

from user:

I found the reason of the problem: it's because when I was opening  a new project, I put the file "Nouveau dossier"  directly in the "drop files box" with all the documents included (.dbf, .prj, .qpj & .shp). If I put only the document .shp everything is going fine.

![unnamed](https://cloud.githubusercontent.com/assets/13679743/26633332/abe8925e-45d8-11e7-8bf9-95f854fe5dcc.png)

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.103
Verified 
Rates can be added, calculated and saved.

<img width="266" alt="7 mar 07" src="https://user-images.githubusercontent.com/36253697/37116765-1c461684-2247-11e8-8b90-5024375a76dc.PNG">

**Comment by jkoschinsky** [comment]
Verified Geoda 107
OSX
