### ISSUE TITLE
Transparency settings

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#881]
This might not be something that can be changed but FYI: When you have a map open, then change the transparency settings and then change them back, you need to close the map and re-open it (or open new map) for the new settings to take effect. Is there a way to make this dynamic or does it only apply to subsequent views?

<img width="599" alt="screen shot 2017-05-31 at 10 12 05 pm" src="https://cloud.githubusercontent.com/assets/13679743/26663158/9e20c684-464e-11e7-8fb0-7c3573e91b28.png">

**Comment by lixun910** [comment]
This is what Luc suggests:  the menu item "change the transparency" is for basemap mainly, and its functionality should be disconnected with GeoDa->Preference->Transparency setting. It was disabled when no basemap shows, and we enable it just in case users don't know what to do when they can't see highlights. 

You can use GeoDa->Preference->Transparency for highlight/unhighlight to make a global and permanent adjustment.

**Comment by jkoschinsky** [comment]
ok, sounds good

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.43 — Mac OSX
Verified.
