### ISSUE TITLE
k-means broken?

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#883]
I can't get k-means or hierarchical clustering to generate any clusters, no matter what the specification (see below). Could you check if they broke?

k-means:
<img width="1008" alt="screen shot 2017-05-31 at 10 33 24 pm" src="https://cloud.githubusercontent.com/assets/13679743/26663667/db4c96a2-4651-11e7-8dc3-cbb6f36c3370.png">

hierarchical clustering:
<img width="859" alt="screen shot 2017-05-31 at 10 40 53 pm" src="https://cloud.githubusercontent.com/assets/13679743/26663729/57fd5164-4652-11e7-93ae-d37f9e3639e2.png">

**Comment by jkoschinsky** [comment]
ok, I got it: it seems to be linked to using "test" as the output field name. I had always used that but if I use something else, it works.

**Comment by lixun910** [comment]
This is caused by "test" field is already existed and it's type is DOUBLE, so Kmeans can't write results to this field.

The solution is to raise a warning message box to user to input a unique name.

"This field name already exists (non-integer type). Please input a unique name."

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.43 — Mac OSX
Verified.
