### ISSUE TITLE
Crash Report (windows)

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#892]
Details:
os: 2-6-1
vs: 1-8-16-4
Check auto update:
Click GdaFrame::OnOpenProject

**Comment by lixun910** [comment]
Can you try the latest GeoDa 1.10 (subversion 1.10.0.4) to see if this has been fixed? Thanks!

https://s3-us-west-2.amazonaws.com/geodasoftware/GeoDa-1.10-Windows-64bit.exe
