### ISSUE TITLE
Crash Report (windows)

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#894]
Details:
os: 2-10-0
vs: 1-10-0-0
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()

**Comment by lixun910** [comment]
Can you try the latest GeoDa 1.10 (subversion 1.10.0.4) to see if this has been fixed? Thanks!

https://s3-us-west-2.amazonaws.com/geodasoftware/GeoDa-1.10-Windows-64bit.exe
