### ISSUE TITLE
Differential Local Moran's I problem

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#922]
Differential Local Moran's I ESDA tool is colored a grey. Hence, one cannot run the analysis anyway although he/she has already prepared spatial weights as well as edit times variables in accordance to
recommended steps on the pull down menu.

v. 1.10
19th June 2017 published for Windows 10 64 bit

**Comment by lixun910** [comment]
This is caused by the same broken windows binaries I created yesterday (see issue #923) on my laptop instead of MacPro in office (due to Internet connection issue in China).  This should be fixed with uploading recreated windows binaries from MacPro.

**Comment by lixun910** [comment]
I just check again, and this is a different problem caused by the broken windows binaries. 
It's the menu item "Differential Local Moran" not been enabled (I just tested the toolbar menu item which works).

Will fix this soon.

**Comment by lixun910** [comment]
Hi Julia Here is a quick build (from MacPro) with the fix of menu item "Differential Local Moran" issue for this windows user: https://s3-us-west-2.amazonaws.com/geodasoftware/GeoDa-1.10.0.12-Windows-64bit.exe

Can you test it and send this link to the user? If everything is fine, I can upload to our download site.

Thank you!

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.103
Verified 

<img width="447" alt="7 mar 08" src="https://user-images.githubusercontent.com/36253697/37122409-600c607e-2258-11e8-9738-bed868f46736.PNG">

**Comment by jkoschinsky** [comment]
Verified Geoda 107
OSX
