### ISSUE TITLE
GeoDa bug report

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#923]
I have encountered difficulties with running the program twice or more times during the one Windows 10 session. Thus, it is impossible to run the program again until restart my computer.

v. 1.10
19th June 2017 published for Windows 10 64 bit

**Comment by lixun910** [comment]
The windows binaries are not correctly built on my laptop for the version I uploaded yesterday with the small fix (the version number display). I just have a chance to connect to the MacPro in your office using VPN and create new binaries again. This should be fixed.

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.1.143
Verified

No problems closing and opening several datasources. Also attempted doing different analyses on the same datasource and had no issues either.
