### ISSUE TITLE
GeoDa hangs across multiple Mac desktops

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#944]
From GeoDa user (1.10 on MacBookPro):

I like to work on several desktops on my computer, and I slide back in forth between them. I had the html metadata open on one desktop and GeoDa on the other, and I was Renaming/Deleting variables. I dragged the GeoDa dataset to the same desktop as the html so I could compare the variable names more easily. When I slid back to the desktop with GeoDa and tried to use the Delete or Rename box (I forget which), the whole program froze for maybe 10mn (GeoDa existed and I could move it around but I couldn't do anything to it, and it didn't quit when I asked it to. After 10mn it functioned normally.

Not sure this can be addressed but FYI.

**Comment by lixun910** [comment]
works fine using GeoDa 1.12 and multi-monitors
![img_9162](https://user-images.githubusercontent.com/2423887/33295475-c7d60d78-d392-11e7-9a00-2050190bcbed.JPG)
