### ISSUE TITLE
Crash Report: Can't close GeoDa

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#945]
Details:
os: 2-10-0
vs: 1-8-16-4
Check auto update:
Open RegressionDlg.
Error: XRC error: 6104: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 6189: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 6198: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 6207: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 6214: both 'wxALIGN_CENTRE_VERTICAL' (as part of wxALIGN_CENTER) and 'wxALIGN_CENTRE_VERTICAL' specify vertical alignment and can't be used together
Warning: iCCP: known incorrect sRGB profile
Warning: iCCP: known incorrect sRGB profile
Error: XRC error: 6223: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click RegressionDlg::OnCWeightCheckClick
Click RegressionDlg::OnRunClick
y:Z_NTEN10
x:
DENS10
Z_GAS10
Z_NBIH10
Z_CLOA10
Z_NEDU10
Z_INMI10
Z_NVIV10
OLS model
Open RegressionReportDlg.
In RegressionReportDlg::OnSaveToFile()
In RegressionReportDlg::OnClose()
Close RegressionDlg.
Click RegressionDlg::OnSaveToTxtFileClick
Click RegressionDlg::OnCSaveRegressionClick
Click RegressionDlg::OnCSaveRegressionClick
In GdaFrame::OpenQuantile(9)
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick
In GdaFrame::OnOpenPercentile()
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick
In GdaFrame::OpenQuantile(10)
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
OLS_RESIDU
Open MapFrame.
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
OLS_RESIDU
VariableSettingsDlg::GetWeightsId() weight: queen1
VariableSettingsDlg::GetWeightsId() weight: queen1
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
OLS_RESIDU
VariableSettingsDlg::GetWeightsId() weight: queen1
VariableSettingsDlg::GetWeightsId() weight: queen1
In OnRan999Per()
Open RandomizationDlg (univariate).
Click RandomizationDlg::OnOkClick
Click RandomizationDlg::OnOkClick
Close RandomizationDlg
In TableFrame::OnActivate
Open DataViewerAddColDlg.
Error: XRC error: 1052: vertical alignment flag 'wxALIGN_CENTRE_VERTICAL' has no effect inside a vertical box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1062: horizontal alignment flag 'wxALIGN_CENTER_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1066: horizontal alignment flag 'wxALIGN_CENTER_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
Entering DataViewerAddColDlg::OnOkClick
Inserting new column ZZ_NTENT10 into Table
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnActivate
Open FieldNewCalcSheetDlg.
Warning: iCCP: known incorrect sRGB profile
Warning: iCCP: known incorrect sRGB profile
Error: XRC error: 5353: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL' (as part of wxALIGN_CENTER)' in a vertical box sizer
Error: XRC error: 5393: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_LEFT'' in a vertical box sizer
Error: XRC error: 5428: 'wxALIGN_CENTER' has no effect when combined with 'wxGROW'
Warning: iCCP: known incorrect sRGB profile
Warning: iCCP: known incorrect sRGB profile
Error: XRC error: 5524: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL' (as part of wxALIGN_CENTER)' in a vertical box sizer
In FieldNewCalcSheetDlg::OnPageChange()
In FieldNewCalcSheetDlg::OnApplyClick()
In FieldNewCalcSheetDlg::OnApplyClick()
In TableFrame::OnActivate
Open RegressionDlg.
Error: XRC error: 6104: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 6189: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 6198: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 6207: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 6214: both 'wxALIGN_CENTRE_VERTICAL' (as part of wxALIGN_CENTER) and 'wxALIGN_CENTRE_VERTICAL' specify vertical alignment and can't be used together
Warning: iCCP: known incorrect sRGB profile
Warning: iCCP: known incorrect sRGB profile
Error: XRC error: 6223: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click RegressionDlg::OnCWeightCheckClick
Click RegressionDlg::OnRunClick
y:Z_NTEN10
x:
ZZ_NTENT10
OLS model
Open RegressionReportDlg.
In RegressionReportDlg::OnClose()
Close RegressionDlg.
Click RegressionDlg::OnCSaveRegressionClick
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
ZZ_NTENT10
VariableSettingsDlg::GetWeightsId() weight: queen1
VariableSettingsDlg::GetWeightsId() weight: queen1
In GdaFrame::OpenQuantile(10)
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
OLS_RESIDU
Open MapFrame.
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
OLS_RESIDU_2
Open MapFrame.
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Error: XRC error: 1254: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1261: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
OLS_RESIDU_2
VariableSettingsDlg::GetWeightsId() weight: queen1
VariableSettingsDlg::GetWeightsId() weight: queen1
Open RegressionDlg.
Error: XRC error: 6104: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 6189: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 6198: 'wxGROW' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 6207: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 6214: both 'wxALIGN_CENTRE_VERTICAL' (as part of wxALIGN_CENTER) and 'wxALIGN_CENTRE_VERTICAL' specify vertical alignment and can't be used together
Warning: iCCP: known incorrect sRGB profile
Warning: iCCP: known incorrect sRGB profile
Error: XRC error: 6223: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click RegressionDlg::OnCoefVarMatrixCbClick
Click RegressionDlg::OnCoefVarMatrixCbClick
Click RegressionDlg::OnPredValCbClick
Click RegressionDlg::OnPredValCbClick
Click GdaFrame::OnClose
Click GdaFrame::OnClose
Click GdaFrame::OnClose

**Comment by lixun910** [comment]
The report is from GeoDa 1.8.16.
