### ISSUE TITLE
Crash Report: Time Editor (can't close GeoDa directly)

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#951]
From: 
 Details:
os: 1-10-12
vs: 1-10-0-12
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Volumes/TCM/Barranquilla/Analysis/Dengue/Shapefile/Season_Year/06July_fromR/Dengue_season_year2_POP4.shp
Open Layer:Dengue_season_year2_POP4
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Volumes/TCM/Barranquilla/Analysis/Dengue/Shapefile/Season_Year/06July_fromR/Dengue_season_year2_POP4.shp
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::SetDetailsForItem
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
In WeightsManFrame::OnActivate
Click VariableSettingsDlg::OnOkClick:
INC_Q1_14
VariableSettingsDlg::GetWeightsId() weight: WEIGHT1
In WeightsManFrame::OnActivate
VariableSettingsDlg::GetWeightsId() weight: WEIGHT1
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Open VarGroupingEditorDlg.
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListEdit
In VarGroupingEditorDlg::OnIncludeListEditEnd
In VarGroupingEditorDlg::OnIncludeListEditEnd
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListEdit
In VarGroupingEditorDlg::OnIncludeListEditEnd
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListEdit
In VarGroupingEditorDlg::OnIncludeListEditEnd
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListEdit
In VarGroupingEditorDlg::OnIncludeListEditEnd
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListEdit
In VarGroupingEditorDlg::OnIncludeListEditEnd
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListEdit
In VarGroupingEditorDlg::OnIncludeListEditEnd
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListEdit
In VarGroupingEditorDlg::OnIncludeListEditEnd
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListEdit
In VarGroupingEditorDlg::OnIncludeListEditEnd
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListEdit
In VarGroupingEditorDlg::OnIncludeListEditEnd
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListEdit
In VarGroupingEditorDlg::OnIncludeListEditEnd
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListSelection
In VarGroupingEditorDlg::OnIncludeListEdit
In VarGroupingEditorDlg::OnIncludeListEditEnd
In VarGroupingEditorDlg::OnCreateGrpClick
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
Open LisaMapFrame (OnOpenDiffLisa).
Open DiffMoranVarSettingDlg.
Click DiffMoranVarSettingDlg::OnOK
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In OnRanOtherPer()
LisaScatterPlotFrame::OnRanOtherPer
99999
Open RandomizationDlg (univariate).
Click GdaFrame::OnCopyImageToClipboard
In OnRanOtherPer()
99999
Click GdaFrame::OnCopyImageToClipboard
Click GdaFrame::OnCopyImageToClipboard
Close RandomizationDlg
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Open LisaMapFrame (OnOpenDiffLisa).
Open DiffMoranVarSettingDlg.
Click DiffMoranVarSettingDlg::OnOK
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In OnRanOtherPer()
LisaScatterPlotFrame::OnRanOtherPer
99999
Open RandomizationDlg (univariate).
Click GdaFrame::OnCopyImageToClipboard
Click GdaFrame::OnCopyImageToClipboard
Click GdaFrame::OnCopyImageToClipboard
Close RandomizationDlg
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Open LisaMapFrame (OnOpenDiffLisa).
Open DiffMoranVarSettingDlg.
Click DiffMoranVarSettingDlg::OnOK
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In OnRanOtherPer()
LisaScatterPlotFrame::OnRanOtherPer
99999
Open RandomizationDlg (univariate).
Click GdaFrame::OnCopyImageToClipboard
Click GdaFrame::OnCopyImageToClipboard
Click GdaFrame::OnCopyImageToClipboard
Close RandomizationDlg
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Open LisaMapFrame (OnOpenDiffLisa).
Open DiffMoranVarSettingDlg.
Click DiffMoranVarSettingDlg::OnOK
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In OnRanOtherPer()
LisaScatterPlotFrame::OnRanOtherPer
99999
Open RandomizationDlg (univariate).
Click GdaFrame::OnCopyImageToClipboard
In OnRanOtherPer()
99999
Click GdaFrame::OnCopyImageToClipboard
Click GdaFrame::OnCopyImageToClipboard
Close RandomizationDlg
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Open LisaScatterPlotFrame (OnOpenDiffMoran).
Open DiffMoranVarSettingDlg.
Click DiffMoranVarSettingDlg::OnOK
In OnRanOtherPer()
LisaScatterPlotFrame::OnRanOtherPer
99999
Open RandomizationDlg (univariate).
Click GdaFrame::OnCopyImageToClipboard
Close RandomizationDlg
Open LisaMapFrame (OnOpenUniLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
OBJECTID
VariableSettingsDlg::GetWeightsId() weight: WEIGHT1
VariableSettingsDlg::GetWeightsId() weight: WEIGHT1
Open LisaMapFrame (OnOpenDiffLisa).
Open DiffMoranVarSettingDlg.
Click DiffMoranVarSettingDlg::OnOK
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In OnRanOtherPer()
99999
Click GdaFrame::OnCopyImageToClipboard
Click GdaFrame::OnCopyImageToClipboard
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Open LisaMapFrame (OnOpenDiffLisa).
Open DiffMoranVarSettingDlg.
Click DiffMoranVarSettingDlg::OnOK
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In OnRanOtherPer()
LisaScatterPlotFrame::OnRanOtherPer
99999
Open RandomizationDlg (univariate).
Click GdaFrame::OnCopyImageToClipboard
In OnRanOtherPer()
99999
Click GdaFrame::OnCopyImageToClipboard
Click GdaFrame::OnCopyImageToClipboard
Close RandomizationDlg
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Open LisaMapFrame (OnOpenDiffLisa).
Open DiffMoranVarSettingDlg.
Click DiffMoranVarSettingDlg::OnOK
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In OnRanOtherPer()
LisaScatterPlotFrame::OnRanOtherPer
99999
Open RandomizationDlg (univariate).
Click GdaFrame::OnCopyImageToClipboard
In OnRanOtherPer()
99999
Click GdaFrame::OnCopyImageToClipboard
Click GdaFrame::OnCopyImageToClipboard
Close RandomizationDlg
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Open LisaMapFrame (OnOpenDiffLisa).
Open DiffMoranVarSettingDlg.
Click DiffMoranVarSettingDlg::OnOK
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In OnRanOtherPer()
LisaScatterPlotFrame::OnRanOtherPer
999
Open RandomizationDlg (univariate).
Close RandomizationDlg
In OnRanOtherPer()
LisaScatterPlotFrame::OnRanOtherPer
99999
Open RandomizationDlg (univariate).
Click GdaFrame::OnCopyImageToClipboard
In OnRanOtherPer()
99999
Click GdaFrame::OnCopyImageToClipboard
Click GdaFrame::OnCopyImageToClipboard
Close RandomizationDlg
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Open LisaMapFrame (OnOpenDiffLisa).
Open DiffMoranVarSettingDlg.
Click DiffMoranVarSettingDlg::OnOK
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In OnRanOtherPer()
LisaScatterPlotFrame::OnRanOtherPer
99999
Open RandomizationDlg (univariate).
Click GdaFrame::OnCopyImageToClipboard
In OnRanOtherPer()
99999
Click GdaFrame::OnCopyImageToClipboard
Click GdaFrame::OnCopyImageToClipboard
Click GdaFrame::OnCopyImageToClipboard
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
INC_Q
Open BoxPlotCanvas.
Click GdaFrame::OnCopyImageToClipboard
Close BoxPlotCanvas.
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In VarGroupingEditorDlg::OnClose
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Close RandomizationDlg
MapCanvas::~MapCanvas()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Volumes/TCM/Barranquilla/Analysis/CHIK/Shapefile/Season-Year/POP4/CHIK_season-year_POP4.shp
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
Open VarGroupingEditorDlg.
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnCreateGrpClick
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
INC_Q
Open HistogramFrame.
In HistogramFrame::OnActivate()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
INC_Q
Open BoxPlotCanvas.
Close BoxPlotCanvas.
Click GdaFrame::OnClose
Project::GetProjectFullPath()
Project::HasUnsavedChange()
Click GdaFrame::OnClose
Project::GetProjectFullPath()
Project::HasUnsavedChange()

**Comment by lixun910** [comment]
Can't replicate this crash using GeoDa 1.10 and Ubuntu 16.04 (from the report)
