### ISSUE TITLE
Crash Report: Merge Table

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#953]
From: 
 Details:
os: 1-10-10
vs: 1-10-0-12
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/utplutpl/Desktop/provincias 21 rony/provincias_21_sing_y_znd.shp
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
Open MergeTableDlg.
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/utplutpl/Desktop/base energia_07-14.xls
Open Layer:base energia_07-14
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
In TableFrame::OnActivate
Exiting ConnectDatasourceDlg::OnOkClick
ds:/Users/utplutpl/Desktop/base energia_07-14.xls layer: base energia_07-14
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
In MergeTableDlg::OnMergeClick()
Entering MergeTableDlg::OnExclAllClick()
In MergeTableDlg::OnKeyChoice()
Entering MergeTableDlg::OnIncAllClick()
Entering MergeTableDlg::OnExclAllClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncAllClick()
Entering MergeTableDlg::OnExclAllClick()
Entering MergeTableDlg::OnIncAllClick()
Entering MergeTableDlg::OnExclAllClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncAllClick()
Entering MergeTableDlg::OnExclAllClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
In MergeTableDlg::OnMergeClick()
In TableFrame::OnActivate
In TableFrame::OnActivate
In MergeTableDlg::OnCloseClick()
In TableFrame::OnActivate
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/utplutpl/Desktop/base energia.xls
Open Layer:base energia
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
In TableFrame::OnActivate
Exiting ConnectDatasourceDlg::OnOkClick
ds:/Users/utplutpl/Desktop/base energia.xls layer: base energia
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnExclAllClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
In MergeTableDlg::OnMergeClick()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/utplutpl/Desktop/base energia.xls
Open Layer:base energia
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
In TableFrame::OnActivate
Exiting ConnectDatasourceDlg::OnOkClick
ds:/Users/utplutpl/Desktop/base energia.xls layer: base energia
Entering MergeTableDlg::OnIncOneClick()
In MergeTableDlg::OnMergeClick()
In TableFrame::OnActivate
In TableFrame::OnActivate
In MergeTableDlg::OnCloseClick()
In TableFrame::OnActivate
Entering MergeTableDlg::OnOpenClick()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/utplutpl/Desktop/co2.xls
Open Layer:co2
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
In TableFrame::OnActivate
Exiting ConnectDatasourceDlg::OnOkClick
ds:/Users/utplutpl/Desktop/co2.xls layer: co2
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
Entering MergeTableDlg::OnIncOneClick()
In MergeTableDlg::OnMergeClick()

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.14.1
Verified

No crash after merging an xls. file with a shape file
<img width="414" alt="screen shot 2018-07-09 at 2 15 43 pm" src="https://user-images.githubusercontent.com/37029239/42471738-74e41e00-8384-11e8-831e-2f307e4f08b8.png">
<img width="470" alt="screen shot 2018-07-09 at 2 15 37 pm" src="https://user-images.githubusercontent.com/37029239/42471739-74eeb694-8384-11e8-90e7-72e92d4150fc.png">
<img width="743" alt="screen shot 2018-07-09 at 2 15 25 pm" src="https://user-images.githubusercontent.com/37029239/42471740-74fcc19e-8384-11e8-8db7-7af881efa2c9.png">
