### ISSUE TITLE
Crash Report: Weights creation

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#956]
From: 
 Details:
os: 1-10-12
vs: 1-10-0-12
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/amybekkerman/Documents/Spatial Workshop Files/police/police.xlsx
Open Layer:police
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/amybekkerman/Documents/Spatial Workshop Files/police/police.xlsx
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
Open DataViewerAddColDlg.
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
In DataViewerAddColDlg::OnChoiceType()
DataViewerAddColDlg::OnChoiceDisplayedDecimals()
Entering DataViewerAddColDlg::OnOkClick
Inserting new column LOGUNEMP into Table
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
Open FieldNewCalcSheetDlg.
In TableFrame::OnActivate
Open DataViewerEditFieldPropertiesDlg
In TableFrame::OnActivate
Open DataViewerDeleteColDlg.
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnDelete()
LOGUNEMP
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
Open DataViewerAddColDlg.
DataViewerAddColDlg::OnEditName()
In TableFrame::OnActivate
Open DataViewerAddColDlg.
DataViewerAddColDlg::OnEditName()
In FieldNewCalcSheetDlg::OnPageChange()
In FieldNewCalcSheetDlg::OnPageChange()
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
Open DataViewerEditFieldPropertiesDlg
In TableFrame::OnActivate
In TableFrame::OnActivate
Open DataViewerAddColDlg.
DataViewerAddColDlg::OnEditName()
In TableFrame::OnActivate
In FieldNewCalcSheetDlg::OnPageChange()
In FieldNewCalcSheetDlg::OnPageChange()
In FieldNewCalcSheetDlg::OnPageChange()
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In FieldNewCalcSheetDlg::OnClose()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Users/amybekkerman/Documents/Spatial Workshop Files/police/police.shp
Open Layer:police
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/amybekkerman/Documents/Spatial Workshop Files/police/police.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
In GdaFrame::OnOpenPercentile()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
CRIME
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
In TableFrame::OnActivate
MapCanvas::~MapCanvas()
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
ConnectDatasourceDlg::OnSample()
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Applications/GeoDa.app/Contents/MacOS/../Resources/samples.sqlite
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
ue90
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnHinge15()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnStddev()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::ChangeToNaturalBreaks(5)
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnThemelessMap()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::ChangeToQuantile(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
ue90
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
selected:0
Click CreatingWeightDlg::OnCRadioQueenSelected
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/Users/amybekkerman/Documents/Spatial Workshop Files/queen_homicides.gal
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/Applications/GeoDa.app/Contents/Resources/US Homicides.gal
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnActivate
WeightsManFrame::OnConnectMapBtn()
Open ConnectivityMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In WeightsManFrame::OnActivate
In ConnectivityMapFrame::OnActivate
In ConnectivityMapFrame::OnActivate
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
ue90
In ConnectivityMapFrame::OnActivate
Open HistogramFrame.
In HistogramFrame::OnActivate()
In ConnectivityMapFrame::OnActivate
In HistogramFrame::OnActivate()
In ConnectivityMapFrame::OnActivate
In WeightsManFrame::OnActivate
MapCanvas::~MapCanvas()
WeightsManFrame::OnHistogramBtn()
Open ConnectivityHistFrame
In WeightsManFrame::OnActivate
ConnectivityHistFrame::OnActivate
In WeightsManFrame::OnActivate
WeightsManFrame::OnConnectMapBtn()
Open ConnectivityMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In WeightsManFrame::OnActivate
In ConnectivityMapFrame::OnActivate
ConnectivityHistFrame::OnActivate
In ConnectivityMapFrame::OnActivate
ConnectivityHistFrame::OnActivate
MapCanvas::~MapCanvas()
In WeightsManFrame::OnActivate
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnCRadioKnnSelected
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Click CreatingWeightDlg::OnCSpinKnnUpdated
Click CreatingWeightDlg::OnCreateClick
CreateWeights()/Applications/GeoDa.app/Contents/Resources/US Homicides.gwt
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnActivate
WeightsManFrame::OnHistogramBtn()
Open ConnectivityHistFrame
In WeightsManFrame::OnActivate
ConnectivityHistFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnCRadioDistanceSelected
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
1.46578
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
1.46578
Click CreatingWeightDlg::OnCThresholdSliderUpdated:
1.46578
Click CreatingWeightDlg::OnDistanceChoiceSelected
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Click CreatingWeightDlg::OnCThresholdTextEdit:
9
Click CreatingWeightDlg::OnCThresholdTextEdit:
90
Click CreatingWeightDlg::OnCreateClick
In WeightsManFrame::OnActivate
CreateWeights()/Applications/GeoDa.app/Contents/Resources/US Homicides.gwt
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate

**Comment by VeraB620** [comment]
OS X El Capitan 10.11.6
GeoDa 1.12.1.137
No crash for weights creation.
Tried with: Multiple types of weights created for same data (data off GeoDa and Chicago Portal), after merging and stacking data, different types of weights (continuity and distance)
Played around with weights for about 15 min, no crash, no lag
