### ISSUE TITLE
Crash Report: Correlogram + Centroids

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#957]
From: 
 Details:
os: 3-4-8
vs: 1-10-0-8
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:PG:dbname='myriad_temp' 
Open Layer:rooftop_20170713
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
PG:dbname='myriad_temp' 
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Entering GdaFrame::OnMapChoices
Open Themeless Map (OnOpenThemelessMap).
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:PG:dbname='myriad_temp' 
Open Layer:myriad_roofdates
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
PG:dbname='myriad_temp' 
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
gmdateint
latitude
Open ScatterNewPlotFrame.
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
longitude
latitude
Open CartogramNewFrame.
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Project::GetVoronoiRookNeighborGal()
Project::GetVoronoiRookNeighborMap()
Project::IsPointDuplicates()
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
In CartogramNewFrame::OnActivate()
In CartogramNewFrame::OnActivate()
In CartogramNewFrame::OnMapPan()
In CartogramNewFrame::OnMapExtent()
In CartogramNewFrame::OnActivate()
Entering GdaFrame::OnMapChoices
In GdaFrame::OnOpenPercentile()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
gmdateint
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In MapFrame::OnMapBasemap()
Click GdaFrame::OnSetBasemap1
In MapFrame::OnMapBasemap()
In MapFrame::OnMapBasemap()
Click GdaFrame::OnSetBasemap7
MapCanvas::~MapCanvas()
In TableFrame::OnActivate
MapCanvas::~MapCanvas()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
gmdateint
latitude
longitude
Open C3DPlotCanvas.
Close C3DPlotCanvas.
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
gmdateint
Open BoxPlotCanvas.
Close BoxPlotCanvas.
Open ScatterPlotMatFrame.
In ScatterPlotMatFrame::OnActivate
In ScatterPlotMatFrame::OnActivate
In ScatterPlotMatFrame::OnActivate
In ScatterPlotMatFrame::OnActivate
In ScatterPlotMatFrame::OnActivate
Open PCPDlg.
Click PCPDlg::OnIncAllClick
Click PCPDlg::OnOkClick
Open PCPFrame.
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
gmdateint
latitude
longitude
Open ConditionalNewFrame.
In ConditionalMapFrame::OnActivate()
Open LisaMapFrame (OnOpenMultiLisa).
Open LisaMapFrame (OnOpenUniLisa).
Open GetisOrdMapFrame (OnOpenGetisOrd).
Open CorrelogramFrame.
Project::GetCentroids(std::vector<wxRealPoint>& pts)
Project::GetCentroids()
In CorrelogramFrame::OnShowCorrelParams()
In CorrelogramFrame::OnActivate()
Project::CalcUnitSphereRtreeStats()
Project::GetCentroids()
In CorrelogramFrame::OnActivate()
In CorrelogramFrame::OnActivate()
Project::GetCentroids(std::vector<wxRealPoint>& pts)
Project::GetCentroids()
Project::GetCentroids(std::vector<wxRealPoint>& pts)
Project::GetCentroids()
Project::GetCentroids(std::vector<wxRealPoint>& pts)
Project::GetCentroids()

**Comment by jkoschinsky** [comment]
try adding centroids to the table and then running correlogram on them before saving them

**Comment by bsalas11** [comment]
Win 1.14

Unable to replicate. Did not crash with any permutations on correlograms or centroids.
