### ISSUE TITLE
Crash Report: SaveDataSourceAs

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#966]
From: 
 Details:
os: 1-10-10
vs: 1-10-0-8
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Volumes/ROMER/Base_dados/SETORES_SENC_IBGE/SETORES_RECORTADOS/RM_POA/SETORES_IBGE_IVS_POP_URB.shp
Open Layer:SETORES_IBGE_IVS_POP_URB
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Volumes/ROMER/Base_dados/SETORES_SENC_IBGE/SETORES_RECORTADOS/RM_POA/SETORES_IBGE_IVS_POP_URB.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnCreateNewIdClick
Try to insert unique id (integer, POLY_ID) column in table.
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnCRadioQueenSelected
Click CreatingWeightDlg::OnCreateClick
In WeightsManFrame::OnActivate
CreateWeights()/Users/romerogomes/Downloads/SETORES_IBGE_IVS_POP_URB.gal
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
WeightsManFrame::OnHistogramBtn()
Open ConnectivityHistFrame
In WeightsManFrame::OnActivate
ConnectivityHistFrame::OnActivate
Close CreatingWeightDlg
ConnectivityHistFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Open LisaMapFrame (OnOpenDiffLisa).
Open LisaMapFrame (OnOpenMultiLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
IVS_2010
0X1.FFFD5B2F0CCP-1028VU_ID
VariableSettingsDlg::GetWeightsId() weight: SETORES_IBGE_IVS_POP_URB
VariableSettingsDlg::GetWeightsId() weight: SETORES_IBGE_IVS_POP_URB
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs
New Datasource Name:/Volumes/ROMER/Base_dados/SETORES_SENC_IBGE/SETORES_RECORTADOS/RM_POA/GdaTmp_SETORES_IBGE_IVS_POP_URB.shp
Project::GetSpatialReference()
Project::GetGdaGeometries()
ScrolledWidgetsPane::IsFieldNameValid
POLY_ID
ScrolledWidgetsPane::IsFieldNameValid
NOME_UDH
ScrolledWidgetsPane::IsFieldNameValid
AREA_UDH
ScrolledWidgetsPane::IsFieldNameValid
POPULACAO
ScrolledWidgetsPane::IsFieldNameValid
IVS_2010
ScrolledWidgetsPane::IsFieldNameValid
IVS_RT
ScrolledWidgetsPane::IsFieldNameValid
IVS
ScrolledWidgetsPane::IsFieldNameValid
IVS_INF
ScrolledWidgetsPane::IsFieldNameValid
SITUACAO
ScrolledWidgetsPane::IsFieldNameValid
ID
ScrolledWidgetsPane::IsFieldNameValid
AVU_UDH_ID
ScrolledWidgetsPane::IsFieldNameValid
AREA_ID
ScrolledWidgetsPane::IsFieldNameValid
0X1.FFFD5B2FD2CP-1028VU_ID
ScrolledWidgetsPane::IsFieldNameValid
I_IVS_2010
ScrolledWidgetsPane::RemoveIllegalChars
0X1.FFFD5B2FC08P-1028VU_ID
AVU_ID
ScrolledWidgetsPane::TruncateFieldName
AVU_ID
ScrolledWidgetsPane::RenameDupFieldName
AVU_ID
AVU_ID
Click FieldNameCorrectionDlg::OnCancelClick
Exit FieldNameCorrectionDlg

**Comment by jkoschinsky** [comment]
Table field name - fixed
