### ISSUE TITLE
confusion about select cores and neighbors in local cluster maps

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#971]
The option "select cores and neighbors" seems to only work when some of the
cores have been selected. It doesn't seem to do anything with the default cluster
map. There seems to be some duplication with the option Select All > Cores and 
Neighbors. Should the option be called "cores and neighbors of selection" instead?

**Comment by lanselin** [comment]
I suggest to change the item "Cores and neighbors of selection" to "Selection and neighbors", that would make clear that this only works when a selection has been made and (maybe?) end the confusion with the Select All > Cores and neighbors. The confusion (in my view) is that the "Selection and neighbors" works for any selection, not just a cluster core, whereas the other ones should only work for the core clusters that are identified.

**Comment by lanselin** [comment]
I verified that "Cores and neighbors of selection" (to be renamed) works whenever a selection has been made. Without a selection, it does nothing, that's why we should remove the reference to cores.

Also, I may have suggested this elsewhere, there is no reason not to add this option to any thematic map, since it pertains to a "selection" and its neighbors, not to the cores of the clusters.

**Comment by lanselin** [comment]
The Select All > options do NOT work for the local geary map. They do work for local Moran and the local G statistics.

**Comment by lixun910** [comment]
Verified:
(select all > select cores)
<img width="602" alt="screen shot 2019-01-15 at 10 04 30 pm" src="https://user-images.githubusercontent.com/2423887/51227433-95ceb080-1911-11e9-9fbe-a62be7899dbd.png">
(select all > neighbors of cores)
<img width="604" alt="screen shot 2019-01-15 at 10 04 37 pm" src="https://user-images.githubusercontent.com/2423887/51227454-aaab4400-1911-11e9-9007-adae1a001245.png">
(select all > cores and neighbors)
<img width="601" alt="screen shot 2019-01-15 at 10 04 44 pm" src="https://user-images.githubusercontent.com/2423887/51227464-b5fe6f80-1911-11e9-9d37-6e69850827ec.png">
