### ISSUE TITLE
Add GeoDa to sourceforge for faster download in China

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#982]
Right now, it’s slow to download GeoDa in China because AWS access isn’t efficient. Add GeoDa to sourceforge: Since they have mirror servers in Chica, this should enable faster downloads in China. Integrate the tracking of user counts with our current counter since downloads from China are sizable.

**Comment by lixun910** [comment]
We have a download option using Github now, and it's accessible in China: https://github.com/GeoDaCenter/geoda/releases
