### ISSUE TITLE
Leave the zoomed-in extent when turning off basemap

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#984]
Leave the zoomed-in extent when turning off basemap

Steps:
1. Turn basemap on
2. Zoom into map
3. turn off basemap

GeoDa resets map to full extent, so you have to zoom in again. Leave the zoomed-in extent when turning off basemap.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.103
Not Fixed yet
After turning off basemap, Geoda resets to full extent.

**Comment by lixun910** [comment]
Same as https://github.com/GeoDaCenter/geoda/issues/1190
Zoom resets whenever basemap is changed #1190
Has been verified.
