### ISSUE TITLE
Flag non-matching .prj instead of displaying distorted map?

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#985]
Right now, when a spatial file is loaded with a non-matching .prj file, GeoDa doesn't generate an error but displays a distorted map (see below). Is there a way to flag this instead?

Data: [KingCounty_HouseSales.zip](https://github.com/GeoDaCenter/geoda/files/1167793/KingCounty_HouseSales.zip)

Map without .prj file:
<img width="604" alt="screen shot 2017-07-22 at 8 31 49 pm" src="https://user-images.githubusercontent.com/13679743/28495614-361117dc-6f21-11e7-81f6-80dfa8cb7694.png">

Map with .prj file:
<img width="601" alt="screen shot 2017-07-22 at 8 31 41 pm" src="https://user-images.githubusercontent.com/13679743/28495616-37be395c-6f21-11e7-99e6-b17462bbbdb5.png">

which seems to be WGS84 but there must still be sth wrong:

GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]

**Comment by lixun910** [comment]
user should provide a valid prj file. Carto does the same thing when a invalid prj file is provided:
<img width="1314" alt="screen shot 2018-07-06 at 5 54 31 pm" src="https://user-images.githubusercontent.com/2423887/42405094-c789ac42-8145-11e8-9778-482e26cc5b97.png">
