### ISSUE TITLE
randomization for Moran scatterplot does not respect regimes setting

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#989]
The randomization option for the Moran scatter plot gives results for all, selected and unselected whenever a selection is active, even when the "regimes regression" option is unchecked. It should only give those sets of results when the regimes regression option is checked.

**Comment by jkoschinsky** [comment]
Works in in GeoDa 1.12.1.137 (OSX High Sierra, 10.13.4).

<img width="1033" alt="screen shot 2018-06-06 at 10 42 14 am" src="https://user-images.githubusercontent.com/13679743/41049348-57a460b6-6976-11e8-982e-1f0e069adbfe.png">
