### ISSUE TITLE
Inference in Local Statistics

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#990]
In the new interface, there should be three additional options:
1. Any value between 0.0 and 1.0 -- user entry
2. The Bonferroni bound for a pre-set alpha level
3. The False Discovery Rate(FDR) for a pre-set alpha level

**Comment by jkoschinsky** [comment]
Three options are there but significance is not bound by 1, e.g. you can enter 1.2. Set bounds to 0-1.

<img width="346" alt="screen shot 2017-09-27 at 5 55 09 pm" src="https://user-images.githubusercontent.com/13679743/30941818-0bd3f5fa-a3ad-11e7-9e63-d5959a586bff.png">

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.19
Verified

**Comment by VeraB620** [comment]
OS X El Capitan 10.11.6
GeoDa 1.12.1.137
Verified, whenever adding a bound greater then 1, it reverts to 1
