### ISSUE TITLE
Table - identify duplicate entries

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#997]
When creating a weights matrix, it is quite common to use an administrative ID that ends up having duplicate values, say when two separate polygons pertain to the same "block" or other areal unit, or when two polygons pertain to the same county (e.g., some counties in North Carolina with islands as separate polygons). It would be nice if there was an easy way to identify those entries with duplicate values, so that the underlying shape file (or other) could be fixed.

**Comment by lanselin** [comment]
There are still two problems in reporting the results of the duplicate entries.
1. the entries are sorted by row, but they should be sorted by value. in many tables, there is not necessarily a direct connection between the row and the entry -- see attached example for Chicago blocks.
2. there is no way to export the list. this is a problem, especially when the list is long, as in my example. the dialog is blocked, so that it is not possible to check in the table without closing the dialog, which also closes the list. any chance we can write the list as a text file?
<img width="567" alt="screen shot 2017-08-09 at 1 08 38 pm" src="https://user-images.githubusercontent.com/4008351/29143206-2cea89b8-7d09-11e7-842e-ed4280378b12.png">

**Comment by lanselin** [comment]
also, it seems that the count of duplicate values is not correct. there were many more than 10 duplicate values in my example.

**Comment by luluzhou766** [comment]
Win 10, 64bit
Geoda 1.12.1.131

The duplicate entries list can be exported. 
But the entries are not sorted by values. 

![01](https://user-images.githubusercontent.com/36253697/39613590-d4f69048-4f9a-11e8-8649-b2e7869563f5.PNG)


![02](https://user-images.githubusercontent.com/36253697/39613592-d781d8c2-4f9a-11e8-89cf-d414c839d1e0.PNG)

**Comment by jkoschinsky** [comment]
Works in in GeoDa 1.12.1.137 (OSX High Sierra, 10.13.4):
- records sorted by value
- can be saved
- correct count for test case below: 

<img width="811" alt="screen shot 2018-06-06 at 10 50 59 am" src="https://user-images.githubusercontent.com/13679743/41049984-c207447c-6977-11e8-83fa-f39165331086.png">
