### ISSUE TITLE
Crash: Update Natural Breaks Categories

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#998]
From: joseph.ariwi@ryerson.ca
 Details:
os: 1-10-12
vs: 1-10-0-12
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Click GdaFrame::OnRecentDSClick
/Users/Jojo/Documents/MSA-Accessibility/DA_TORONTO_CSD/TorontoCSD_Access.shp
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Users/Jojo/Documents/MSA-Accessibility/DA_TORONTO_CSD/TorontoCSD_Access.shp
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open LisaMapFrame (OnOpenMultiLisa).
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnCreateNewIdClick
Try to insert unique id (integer, POLY_ID) column in table.
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected
selected:0
Click CreatingWeightDlg::OnCreateNewIdClick
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnCRadioQueenSelected
Click CreatingWeightDlg::OnCreateClick
In WeightsManFrame::OnActivate
CreateWeights()/Users/Jojo/Documents/MSA-Accessibility/DA_TORONTO_CSD/TorontoCSD_Access.gal
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::update(WeightsManState* o)
WeightsManFrame::OnConnectMapBtn()
Open ConnectivityMapFrame
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In WeightsManFrame::OnActivate
In ConnectivityMapFrame::OnActivate
In WeightsManFrame::OnActivate
MapCanvas::~MapCanvas()
In WeightsManFrame::OnActivate
Close CreatingWeightDlg
Open LisaMapFrame (OnOpenMultiLisa).
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
zMHA_ADD_p
zDOC_COMP
VariableSettingsDlg::GetWeightsId() weight: TorontoCSD_Access
VariableSettingsDlg::GetWeightsId() weight: TorontoCSD_Access
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In OnRan999Per()
MapCanvas::~MapCanvas()
MapCanvas::~MapCanvas()
Click GdaFrame::OnCanvasBackgroundColor
In GdaFrame::OpenNaturalBreaks(6)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
zMHA_ADD_p
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()

**Comment by jkoschinsky** [comment]
I tried changing the natural breaks categories in the map and all works fine.
Julie, could you check on Windows, too, since another Win user did report a related crash?

**Comment by lixun910** [comment]
Can't replicate crash using natural breaks (with null values, extreme values) using GeoDa 1.14 and Ubuntu 16.04 and Ubuntu 18.04

<img width="487" alt="Screen Shot 2019-08-13 at 9 29 29 PM" src="https://user-images.githubusercontent.com/2423887/62994571-7b11db00-be11-11e9-85ff-a787f8f71b4c.png">
