### ISSUE TITLE
Crash Conditional Map LISA: Try Replicating

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#999]
From: 
 Details:
os: 1-10-12
vs: 1-10-0-12
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Volumes/TCM/Barranquilla/Analysis/Dengue/Shapefile/Attributes/Den_Attrib_pop-to-ento.shp
Open Layer:Den_Attrib_pop-to-ento
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Volumes/TCM/Barranquilla/Analysis/Dengue/Shapefile/Attributes/Den_Attrib_pop-to-ento.shp
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
MapCanvas::~MapCanvas()
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Volumes/TCM/Barranquilla/Analysis/Dengue/Shapefile/Attributes/Den_Attrib_pop-to-ento.shp
Open Layer:Den_Attrib_pop-to-ento
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Volumes/TCM/Barranquilla/Analysis/Dengue/Shapefile/Attributes/Den_Attrib_pop-to-ento.shp
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open RegressionDlg.
RegressionDlg::InitVariableList()
RegressionDlg::OnCButton1Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
RegressionDlg::OnCButton2Click()
Click RegressionDlg::OnCWeightCheckClick
Click RegressionDlg::OnCOpenWeightClick
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Click RegressionDlg::OnRunClick
y:INCIDENCE
x:
SES
Hous_dens_
Perc_Veg
MALE
FEMALE
145540use
0x1.fffd4306d58p-1028partmen
Euc_dist_w
Nov12Housi
OLS model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
In RegressionReportDlg::OnClose()
Close RegressionDlg.
RegressionDlg::OnCButton3Click()
RegressionDlg::OnCButton3Click()
RegressionDlg::OnCButton3Click()
Click RegressionDlg::OnRunClick
y:INCIDENCE
x:
SES
Hous_dens_
Perc_Veg
145540use
Euc_dist_w
Nov12Housi
OLS model
RegressionDlg::DisplayRegression()
Open RegressionReportDlg.
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
Open DataMovieDlg.
Close DataMovieDlg::OnClose
Entering GdaFrame::OnMapChoices
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
INCIDENCE
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
INCIDENCE
SES
Open CartogramNewFrame.
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Project::GetVoronoiRookNeighborGal()
Project::GetVoronoiRookNeighborMap()
Project::IsPointDuplicates()
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
In CartogramNewFrame::OnActivate()
In CartogramNewFrame::OnMapExtent()
In CartogramNewFrame::OnMapPan()
In CartogramNewFrame::OnMapRefresh()
In GdaFrame::OnOpenHinge15()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
INCIDENCE
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
In GdaFrame::OnOpenEmpiricalBayes()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
RegressionDlg::~RegressionDlg()
Close RegressionDlg.
MapCanvas::~MapCanvas()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/Volumes/TCM/Barranquilla/Analysis/Dengue/Shapefile/Cases_aggregate/POP4/Dengue_cases_POP4.shp
Open Layer:Dengue_cases_POP4
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Volumes/TCM/Barranquilla/Analysis/Dengue/Shapefile/Cases_aggregate/POP4/Dengue_cases_POP4.shp
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnOpenEmpiricalBayes()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
CASES
POP4
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::~MapCanvas()
In TableFrame::OnActivate
In GdaFrame::OnOpenSpatialEmpiricalBayes()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::SetDetailsForItem
In GdaFrame::OnOpenSpatialEmpiricalBayes()
Open VariableSettingsDlg
In WeightsManFrame::OnActivate
Click VariableSettingsDlg::OnOkClick:
CASES
POP4
VariableSettingsDlg::GetWeightsId() weight: WEIGHT1
In WeightsManFrame::OnActivate
VariableSettingsDlg::GetWeightsId() weight: WEIGHT1
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In WeightsManFrame::OnActivate
Open DataMovieDlg.
Entering DataMovieDlg::OnFieldChoice
DataMovieDlg::OnPlayPauseButton
Close DataMovieDlg::OnClose
In WeightsManFrame::OnActivate
MapCanvas::~MapCanvas()
In WeightsManFrame::OnActivate
Open ExportDataDlg in its Init()
Click GdaFrame::OnCloseProjectEvt
Project::GetProjectFullPath()
In TableFrame::OnClose and actually closing.
Project::CleanupPairsHLState()
Entering Project::~Project
Exiting Project::~Project
MapCanvas::~MapCanvas()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/Volumes/TCM/Barranquilla/Analysis/Dengue/Shapefile/Season_Year/UPDATE_COMPLETE/Dengue_season_year_COMP2016.shp
Project::SetupEncoding()
UTF-8
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open VarGroupingEditorDlg.
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnAddToListClick
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnCreateGrpClick
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
Open LisaMapFrame (OnOpenDiffLisa).
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::OnActivate
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnLoadBtn
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::update(WeightsManState* o)
In WeightsManFrame::OnWListItemSelect
In WeightsManFrame::SetDetailsForItem
In WeightsManFrame::SetDetailsForItem
Open LisaMapFrame (OnOpenDiffLisa).
Open DiffMoranVarSettingDlg.
In WeightsManFrame::OnActivate
Click DiffMoranVarSettingDlg::OnOK
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Click GdaFrame::OnSaveProject
Entering Project::SaveDataSourceData
Exiting Project::SaveDataSourceData
Entering Project::SaveProjectConf
Project::GetProjectFullPath()
In Project::UpdateProjectConf
Exiting Project::SaveProjectConf
Open ExportDataDlg in its Init()
In ExportDataDlg::BrowseExportDataSource()
In ExportDataDlg::OnOkClick()
ds:/Volumes/TCM/Barranquilla/Analysis/Dengue/Shapefile/GeoDa/Den-seas-year.shp
Project::GetSpatialReference()
ScrolledWidgetsPane::IsFieldNameValid
OBJECTID
ScrolledWidgetsPane::IsFieldNameValid
SETU_CCDGO
ScrolledWidgetsPane::IsFieldNameValid
SETU_NAREA
ScrolledWidgetsPane::IsFieldNameValid
SETU_NANO
ScrolledWidgetsPane::IsFieldNameValid
SHAPE_Leng
ScrolledWidgetsPane::IsFieldNameValid
SHAPE_Area
ScrolledWidgetsPane::IsFieldNameValid
BARRIO
ScrolledWidgetsPane::IsFieldNameValid
URBANO_COD
ScrolledWidgetsPane::IsFieldNameValid
ID
ScrolledWidgetsPane::IsFieldNameValid
POP4
ScrolledWidgetsPane::IsFieldNameValid
cas_Q1-14C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q2-14C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q3-14C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q4-14C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q1-15C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q2-15C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q3-15C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q4-15C
ScrolledWidgetsPane::IsFieldNameValid
INC_Q1_14
ScrolledWidgetsPane::IsFieldNameValid
INC_Q2_14
ScrolledWidgetsPane::IsFieldNameValid
INC_Q3_14
ScrolledWidgetsPane::IsFieldNameValid
INC_Q4_14
ScrolledWidgetsPane::IsFieldNameValid
INC_Q1_15
ScrolledWidgetsPane::IsFieldNameValid
INC_Q2_15
ScrolledWidgetsPane::IsFieldNameValid
INC_Q3_15
ScrolledWidgetsPane::IsFieldNameValid
INC_Q4_15
ScrolledWidgetsPane::IsFieldNameValid
INC_Q1_16
ScrolledWidgetsPane::IsFieldNameValid
INC_Q2_16
ScrolledWidgetsPane::IsFieldNameValid
INC_Q3_16
ScrolledWidgetsPane::IsFieldNameValid
INC_Q4_16
ScrolledWidgetsPane::IsFieldNameValid
cas_Q1-16C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q2-16C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q3-16C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q4-16C
ScrolledWidgetsPane::RemoveIllegalChars
cas_Q1-14C
cas_Q114C
ScrolledWidgetsPane::TruncateFieldName
cas_Q114C
ScrolledWidgetsPane::RenameDupFieldName
cas_Q114C
cas_Q114C
ScrolledWidgetsPane::RemoveIllegalChars
cas_Q2-14C
cas_Q214C
ScrolledWidgetsPane::TruncateFieldName
cas_Q214C
ScrolledWidgetsPane::RenameDupFieldName
cas_Q214C
cas_Q214C
ScrolledWidgetsPane::RemoveIllegalChars
cas_Q3-14C
cas_Q314C
ScrolledWidgetsPane::TruncateFieldName
cas_Q314C
ScrolledWidgetsPane::RenameDupFieldName
cas_Q314C
cas_Q314C
ScrolledWidgetsPane::RemoveIllegalChars
cas_Q4-14C
cas_Q414C
ScrolledWidgetsPane::TruncateFieldName
cas_Q414C
ScrolledWidgetsPane::RenameDupFieldName
cas_Q414C
cas_Q414C
ScrolledWidgetsPane::RemoveIllegalChars
cas_Q1-15C
cas_Q115C
ScrolledWidgetsPane::TruncateFieldName
cas_Q115C
ScrolledWidgetsPane::RenameDupFieldName
cas_Q115C
cas_Q115C
ScrolledWidgetsPane::RemoveIllegalChars
cas_Q2-15C
cas_Q215C
ScrolledWidgetsPane::TruncateFieldName
cas_Q215C
ScrolledWidgetsPane::RenameDupFieldName
cas_Q215C
cas_Q215C
ScrolledWidgetsPane::RemoveIllegalChars
cas_Q3-15C
cas_Q315C
ScrolledWidgetsPane::TruncateFieldName
cas_Q315C
ScrolledWidgetsPane::RenameDupFieldName
cas_Q315C
cas_Q315C
ScrolledWidgetsPane::RemoveIllegalChars
cas_Q4-15C
cas_Q415C
ScrolledWidgetsPane::TruncateFieldName
cas_Q415C
ScrolledWidgetsPane::RenameDupFieldName
cas_Q415C
cas_Q415C
ScrolledWidgetsPane::RemoveIllegalChars
cas_Q1-16C
cas_Q116C
ScrolledWidgetsPane::TruncateFieldName
cas_Q116C
ScrolledWidgetsPane::RenameDupFieldName
cas_Q116C
cas_Q116C
ScrolledWidgetsPane::RemoveIllegalChars
cas_Q2-16C
cas_Q216C
ScrolledWidgetsPane::TruncateFieldName
cas_Q216C
ScrolledWidgetsPane::RenameDupFieldName
cas_Q216C
cas_Q216C
ScrolledWidgetsPane::RemoveIllegalChars
cas_Q3-16C
cas_Q316C
ScrolledWidgetsPane::TruncateFieldName
cas_Q316C
ScrolledWidgetsPane::RenameDupFieldName
cas_Q316C
cas_Q316C
ScrolledWidgetsPane::RemoveIllegalChars
cas_Q4-16C
cas_Q416C
ScrolledWidgetsPane::TruncateFieldName
cas_Q416C
ScrolledWidgetsPane::RenameDupFieldName
cas_Q416C
cas_Q416C
Click FieldNameCorrectionDlg::OnOkClick
ScrolledWidgetsPane::IsFieldNameValid
cas_Q1_14C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q2_14C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q3_14C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q4_14C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q1_15C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q2_15C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q3_15C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q4_15C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q1_16C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q2_16C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q3_16C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q4_16C
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
In VarGroupingEditorDlg::OnNewGroupNameChange
In VarGroupingEditorDlg::OnUngroupedListSelection
Exit FieldNameCorrectionDlg
Click GdaFrame::OnSaveProject
Entering Project::SaveDataSourceData
Project::SaveOGRDataSource()
Entering Project::SaveDataSourceAs
New Datasource Name:/Volumes/TCM/Barranquilla/Analysis/Dengue/Shapefile/Season_Year/UPDATE_COMPLETE/GdaTmp_Dengue_season_year_COMP2016.shp
Project::GetSpatialReference()
Project::GetGdaGeometries()
ScrolledWidgetsPane::IsFieldNameValid
OBJECTID
ScrolledWidgetsPane::IsFieldNameValid
SETU_CCDGO
ScrolledWidgetsPane::IsFieldNameValid
SETU_NAREA
ScrolledWidgetsPane::IsFieldNameValid
SETU_NANO
ScrolledWidgetsPane::IsFieldNameValid
SHAPE_Leng
ScrolledWidgetsPane::IsFieldNameValid
SHAPE_Area
ScrolledWidgetsPane::IsFieldNameValid
BARRIO
ScrolledWidgetsPane::IsFieldNameValid
URBANO_COD
ScrolledWidgetsPane::IsFieldNameValid
ID
ScrolledWidgetsPane::IsFieldNameValid
POP4
ScrolledWidgetsPane::IsFieldNameValid
cas_Q114C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q214C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q314C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q414C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q115C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q215C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q315C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q415C
ScrolledWidgetsPane::IsFieldNameValid
INC_Q1_14
ScrolledWidgetsPane::IsFieldNameValid
INC_Q2_14
ScrolledWidgetsPane::IsFieldNameValid
INC_Q3_14
ScrolledWidgetsPane::IsFieldNameValid
INC_Q4_14
ScrolledWidgetsPane::IsFieldNameValid
INC_Q1_15
ScrolledWidgetsPane::IsFieldNameValid
INC_Q2_15
ScrolledWidgetsPane::IsFieldNameValid
INC_Q3_15
ScrolledWidgetsPane::IsFieldNameValid
INC_Q4_15
ScrolledWidgetsPane::IsFieldNameValid
INC_Q1_16
ScrolledWidgetsPane::IsFieldNameValid
INC_Q2_16
ScrolledWidgetsPane::IsFieldNameValid
INC_Q3_16
ScrolledWidgetsPane::IsFieldNameValid
INC_Q4_16
ScrolledWidgetsPane::IsFieldNameValid
cas_Q116C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q216C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q316C
ScrolledWidgetsPane::IsFieldNameValid
cas_Q416C
Exit FieldNameCorrectionDlg
Exiting Project::SaveDataSourceData
Entering Project::SaveProjectConf
In Project::UpdateProjectConf
Exiting Project::SaveProjectConf
Open ExportDataDlg in its Init()
Open ProjectInfoDlg.
Project::GetProjectFullPath()
In GdaFrame::OnSelectNeighborsOfCores()
In GdaFrame::OnSelectCores()
In GdaFrame::OnAddNeighborToSelection()
In GdaFrame::OnShowAsConditionalMap()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
INC_Q
INC_Q
Open ConditionalNewFrame -- LISA.

**Comment by lixun910** [comment]
I was able to replicate this crash on GeoDa 1.10 on Ubuntu 16.04 64bit, using time grouped variable in Differential LISA. This crash has been fixed in the GeoDa 1.14.
